### ISSUE TITLE
Removing corrupted VM

### ISSUE THREAD

**Issue by pcnova** [MicrosoftDocs/windows-powershell-docs#1010]
Is there any guidance on how to remove a VM for which you no longer have the files, e.g., because they're missing or corrupt? This cmdlet returns an error saying the VM cannot be found, and Hyper-V Manager does not list the VM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f3f349-c2e3-67f4-2eb4-0244ddd78479
* Version Independent ID: b6246c5a-9530-d76e-b66d-6ea7e4564db6
* Content: [Remove-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/remove-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/remove-vm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/remove-vm.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @pcnova  thank you for providing feedback.

The issues section of this repository is intended for documentation feedback.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
