### ISSUE TITLE
Issue with Get-VipHostMapping

### ISSUE THREAD

**Issue by yyakushev** [MicrosoftDocs/windows-powershell-docs#102]
Hello,

I've tried this cmdlet on the windows server 2016 OS Version: 10.0.14393 N/A Build 14393, PSVersion                      5.1.14393.1480 and get the same values for all VIP entries. 
During the investigation, I found that the problem in Get-VipConnectivityInfo.psm1 of HNVDiagnostics module. The $newEntry=$entry.Clone() doesn't work properly and return the copy of the last values for all elements in the hashtable $DIPInterfaceToHos. If we add instead of clone() new function like this one

function NewEntry {
    $entry=@{}
    $hostInfoEntry=@{}
    $hostInfoEntry.Add('Name', "")
    $hostInfoEntry.Add('Credentials', [System.Management.Automation.PSCredential]$null)
    $entry.Add('PortProfile', "")
    $entry.Add('HostInfo', $hostInfoEntry)
    $entry
}

and change  $newEntry=$entry.clone() to $newEntry=NewEntry in Get-VipHostMapping function, we receive the correct result.

Regards,
Yaroslav

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @yyakushev thanks for your feedback.
I reviewed the article and did not find any reference to that psm1 module that could would need to edit the documentation for Get-VipHostMapping, can you kindly let me know what you see is wrong with this article?

Thank you

**Comment by yyakushev** [comment]
Hi Andres,

Sorry, I think that I added the issue into the wrong place. The problem that I mentioned was in a module HNVDiagnostics. It happened half and year ago and I don't know if it still exist. I think we can safely close this issue.

Thank you,
Yaroslav

**Comment by get-itips** [comment]
Thanks to you @yyakushev

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @yyakushev 
Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
