### ISSUE TITLE
Confirm-SecureBootUefi/Get-SecureBootUEFI

### ISSUE THREAD

**Issue by JordanTheITGuy** [MicrosoftDocs/windows-powershell-docs#1021]
Both of these cmdlets write to the error stream when BIOS or UEFI are not found. The goal I seems to have been to produce three possible outputs with a set of booleans, however this means it generates an "error" that isn't really an error just a validation of if a computer supports or doesnt support UEFI. I would prefer to see an output message that could be properly interpreted over a true thrown error as this incorrectly creates errors in the transcript log. Is this by design if so why? 

Additionally, this command doesn't properly process the ErrorAction "SilentlyContinue" or "ErrorAction Stop" for a cmdlet. It only works if you set  error action preference for the session. According to the Get-Help -full - it should support all comomon parameters. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea950120-025b-d301-24cf-c9adbcbb33a7
* Version Independent ID: 4bb3ad86-2169-b897-548c-6e9117c5b8b6
* Content: [Confirm-SecureBootUEFI (secureboot)](https://docs.microsoft.com/en-us/powershell/module/secureboot/confirm-securebootuefi?view=win10-ps)
* Content Source: [docset/windows/secureboot/confirm-securebootuefi.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/secureboot/confirm-securebootuefi.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@JordanTheITGuy 

The issue tracker of this repository is intended for product documentation issues.

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
