### ISSUE TITLE
Typo: "48-bit" should read "48-digit"

### ISSUE THREAD

**Issue by zzzz4** [MicrosoftDocs/windows-powershell-docs#1022]
"cmdlet creates a random 48-bit recovery password"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ba23fe-4cf9-e36c-cb26-0f04484fb392
* Version Independent ID: 4a116594-a3d6-804e-883f-72cb79e9dc21
* Content: [Add-BitLockerKeyProtector (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/add-bitlockerkeyprotector?view=win10-ps)
* Content Source: [docset/windows/bitlocker/add-bitlockerkeyprotector.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/add-bitlockerkeyprotector.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@zzzz4 The issue has been noted and the document will be revised in the light of your feedback.

Thanks.
