### ISSUE TITLE
Typo: "48-bit" should read "48-digit"

### ISSUE THREAD

**Issue by zzzz4** [MicrosoftDocs/windows-powershell-docs#1023]
"cmdlet creates a random 48-bit recovery password"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35517b3c-d00e-c08d-c274-8b606ad87bfa
* Version Independent ID: 3428c627-8703-752e-fbdf-52526f281f57
* Content: [Enable-BitLocker (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/enable-bitlocker?view=win10-ps)
* Content Source: [docset/windows/bitlocker/enable-bitlocker.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/enable-bitlocker.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@zzzz4 

The issue has been noted and the document will be revised in the light of your feedback.

Thanks.

**Comment by e0i** [comment]
Similar to: #1022

**Comment by e0i** [comment]
@zzzz4 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
