### ISSUE TITLE
Clarify the acceptable values for -GptType  

### ISSUE THREAD

**Issue by zzzz4** [MicrosoftDocs/windows-powershell-docs#1026]
I haven't done exhaustive tests, but it appears that not all GUID strings are acceptable values.

See https://docs.microsoft.com/en-us/dotnet/api/system.guid.tostring?view=netcore-2.2
VALID
* Guid.ToString("B")

NOT VALID ("The specified partition type is not valid." error)
* Guid.ToString("N")
* Guid.ToString("D")
* Guid.ToString("P")
* Guid.ToString("X")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e854ce1-0e6c-2261-c35d-94e2faaa96bc
* Version Independent ID: 95312c3e-0f34-cb59-04f1-3cbe6762287a
* Content: [New-Partition (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/new-partition?view=win10-ps)
* Content Source: [docset/windows/storage/new-partition.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/new-partition.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @zzzz4 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@zzzz4 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
