### ISSUE TITLE
QuarantineDuration / Quarantine­Threshold missing

### ISSUE THREAD

**Issue by MKoeppl-Microsoft** [MicrosoftDocs/windows-powershell-docs#1029]
Hi, the Get-Cluster output above seems to be from an older version as on recent S2016 builds there are more objects returned. Like QuarantineDuration / Quarantine­Threshold. 
Would love to see links to those values, there defaults and meanings from this page here. 
Thanks, Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df1397d-e142-f92c-0b63-45e2f7a42d7e
* Version Independent ID: 37129d51-1cbc-6dc8-87cd-29a209c1ba83
* Content: [Get-Cluster (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/get-cluster?view=win10-ps#feedback)
* Content Source: [docset/windows/failoverclusters/get-cluster.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/get-cluster.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @MKoeppl-Microsoft 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@MKoeppl-Microsoft 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
