### ISSUE TITLE
Add a link to the RSAT module

### ISSUE THREAD

**Issue by MrDoNotBreak** [MicrosoftDocs/windows-powershell-docs#1033]
I think it would be helpful if you included a link either to the RSAT package or to a page with information regarding RSAT - for instance like: https://support.microsoft.com/en-us/help/2693643/remote-server-administration-tools-rsat-for-windows-operating-systems

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b818a192-215c-28b8-ba97-fbfae965da7c
* Version Independent ID: 99bc3217-b6da-1c1a-5ab9-a6cc52ef47f8
* Content: [ActiveDirectory](https://docs.microsoft.com/en-us/powershell/module/addsadministration/?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/activedirectory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/activedirectory.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@MrDoNotBreak 

The issue is being routed to Windows PowerShell writing team for investigation. You'll be notified with relevant updates as content gets updated.

Thank you for providing feedback.

**Comment by e0i** [comment]
@MrDoNotBreak 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
