### ISSUE TITLE
Typo - in description 

### ISSUE THREAD

**Issue by abstract17** [MicrosoftDocs/windows-powershell-docs#1038]
issue section:
------------------------------------------------------------------------------------------------
Description
The Add-VMRemoteFx3dVideoAdapter cmdlet adds a '''RemovteFX '''video adapter in a virtual machine.
----------------------------------------------------------------------------------------------
details -
in discription '''RemoteFx'''' is typed as ''' RemovteFx  '''.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3571a9e-34de-2d1c-5f5d-fb86246309e1
* Version Independent ID: a0931325-bca9-797c-a0a8-7c444ba7a131
* Content: [Add-VMRemoteFx3dVideoAdapter (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmremotefx3dvideoadapter?view=win10-ps#feedback)
* Content Source: [docset/windows/hyper-v/add-vmremotefx3dvideoadapter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/add-vmremotefx3dvideoadapter.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@abstract17 Thank you for providing feedback.

We are investigating the issue and will follow-up with updates.

**Comment by e0i** [comment]
@abstract17 

@abstract17 

It seems that the issue has already been addressed with the following commit.

[[e840853 ] typo: Removte -&gt; Remote ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/e840853eb71dd8a49c8116a535f917d1eef74bcb)

We are thus closing this issue since it seems to be resolved.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
