### ISSUE TITLE
Password Exposure

### ISSUE THREAD

**Issue by MWRobertson** [MicrosoftDocs/windows-powershell-docs#1040]
Unless I'm doing something wrong, if you use the -Password flag there doesn't appear to be a way to either enter the password securely or pass a credentials variable. It looks like I'm being asked to enter the plaintext password with the cmdlet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a28e55f1-0862-f421-d8f9-d21793b9a88c
* Version Independent ID: 684f76eb-0b8c-3fbb-4f0c-1e12ccf1405d
* Content: [New-SmbMapping (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/new-smbmapping?view=win10-ps#feedback)
* Content Source: [docset/windows/smbshare/new-smbmapping.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/smbshare/new-smbmapping.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @MWRobertson 

The issues section of this repository is intended for documentation problems only.

Please consider checking any relevant resources and asking the community regarding your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

If you feel that this document can also be updated with information related to your request, please comment and re-open this issue we would love to to follow-up with documentation updates.

Thank you for getting in touch.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
