### ISSUE TITLE
-Replace parameter error - Semicolon separated not comma

### ISSUE THREAD

**Issue by ozthe2** [MicrosoftDocs/windows-powershell-docs#1041]
-Replace
 

Specifies values for an object property that will replace the current values. Use this parameter to replace one or more values of a property that cannot be modified using a cmdlet parameter. To modify an object property, you must use the LDAP display name. You can modify more than one property by specifying a **comma-separated list**. The format for this parameter is:

-Replace @{Attribute1LDAPDisplayName=value[]**,** Attribute2LDAPDisplayName=value[]}

Should be:

Specifies values for an object property that will replace the current values. Use this parameter to replace one or more values of a property that cannot be modified using a cmdlet parameter. To modify an object property, you must use the LDAP display name. You can modify more than one property by specifying a **semicolon separated list**. The format for this parameter is:

-Replace @{Attribute1LDAPDisplayName=value[]**;** Attribute2LDAPDisplayName=value[]}

-----------------

Semicolon separated, not comma.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30217138-eb8c-ab9a-4e11-991c6164cbd9
* Version Independent ID: 88ff510e-6402-5163-404f-e9154f59b381
* Content: [Set-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/set-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-aduser.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@ozthe2 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.
