### ISSUE TITLE
Add-ADFineGrainedPasswordPolicySubject example 4 typo

### ISSUE THREAD

**Issue by 3ter** [MicrosoftDocs/windows-powershell-docs#1043]
Hi there,

in **example 4** it says
```powershell
Get-ADGroup -Filter {lastname -eq "Fuller"} | Add-ADFineGrainedPasswordPolicySubject -Identity DlgtdAdminsPSO
```

which should be
```powershell
Get-ADUser -Filter {lastname -eq "Fuller"} | Add-ADFineGrainedPasswordPolicySubject -Identity DlgtdAdminsPSO
```

as `Get-ADGroup` doesn't have a property _lastname_ and the description says "to any **users** whose last name is Fuller".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 353a2a78-7715-3b9b-0896-0bf508497b74
* Version Independent ID: 1abb6ebb-7c86-5c77-edf0-75c97609d92a
* Content: [Add-ADFineGrainedPasswordPolicySubject (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/add-adfinegrainedpasswordpolicysubject?view=win10-ps)
* Content Source: [docset/windows/addsadministration/add-adfinegrainedpasswordpolicysubject.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/add-adfinegrainedpasswordpolicysubject.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @3ter 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@3ter 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
