### ISSUE TITLE
New-ADServiceAccount wrong parameter information in description

### ISSUE THREAD

**Issue by 3ter** [MicrosoftDocs/windows-powershell-docs#1044]
In the description there is mention of a `-Standalone` parameter which is (no longer) present for the cmdlet.

> To create a standalone MSA which is linked to a specific computer, the -Standalone parameter is used.

I'm pretty positive that it has been replaced by the `-RestrictToSingleComputer` parameter so the description should reflect the change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd731d8-61d8-f6b3-0e8a-3decfe25a184
* Version Independent ID: 3338b8fe-1364-ecd7-eb5c-5ab25d054df7
* Content: [New-ADServiceAccount (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @3ter 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@3ter 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
