### ISSUE TITLE
Add section to explain how to get these cmdlets if they are missing from your machine

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/windows-powershell-docs#1045]
I spent a decent amount of time trying to find out how to add these cmdlets to my powershell environment.  I think all of these are in the Windows Feature RSAT-Clustering-Powershell.  I'll propose a PR which indicates that.  It would be very helpful if the rest of the documents here also explained how to get the cmdlets if they're missing in your powershell environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3e12c0-7173-c914-7807-4baf68994331
* Version Independent ID: 7a47799e-a3ca-e16d-27d8-e288a129632e
* Content: [FailoverClusters](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/failoverclusters.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/failoverclusters.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@MarkIannucci

We'll follow-up with reviews to your PR.

Thank you for your generous contribution. Much appreciated.
