### ISSUE TITLE
Typo in the Description

### ISSUE THREAD

**Issue by CreaterNo1** [MicrosoftDocs/windows-powershell-docs#1047]
There is a typo in the description in the -Filter section. The Asterix (*) should be after the "other than" words.
"Note: PowerShell wildcards other than , such as ?, are not supported by the *Filter syntax."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0b9f4db-305b-847a-1ab6-ad3b547a91f7
* Version Independent ID: a626e689-b2ba-6a11-c17b-9f1fd0e565cd
* Content: [Get-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-aduser?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/get-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/get-aduser.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@CreaterNo1 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@CreaterNo1 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
