### ISSUE TITLE
Suggested Improvement

### ISSUE THREAD

**Issue by DavidUnboxed** [MicrosoftDocs/windows-powershell-docs#1048]
Please add the ability to exclude disabled/unlinked when using "all".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b1b069-1d92-d783-ba1c-7f18f3a501ec
* Version Independent ID: 9ab7a246-fa1f-bd55-a9a9-bb48fba59738
* Content: [Get-GPO (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/get-gpo?view=win10-ps#feedback)
* Content Source: [docset/windows/grouppolicy/get-gpo.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/get-gpo.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@DavidUnboxed 

The issue tracker of this repository is intended for product documentation issues only.

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)


Thanks.

**Comment by e0i** [comment]
@officedocsbot close
