### ISSUE TITLE
Mount-DiskImage does not respect the WhatIf parameter

### ISSUE THREAD

**Issue by MCTSQL** [MicrosoftDocs/windows-powershell-docs#1049]
Mount-DiskImage does not respect the WhatIf parameter

**Example**
- **Input**: _Mount-DiskImage -ImagePath c:\iso\MyImage.iso -WhatIf_
- **Output**:
- - **Expected**: _no mounted image_
- - **Actual**: _mounted image_

**$PSVersionTable**
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543feba4-c3b8-188e-f53f-614763723f26
* Version Independent ID: b8b6b157-df42-8b88-43d3-41ae0f865d91
* Content: [Mount-DiskImage (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/mount-diskimage?view=win10-ps#feedback)
* Content Source: [docset/windows/storage/mount-diskimage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/mount-diskimage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@MCTSQL

The issues section of this repository is intended for documentation feedback.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
