### ISSUE TITLE
Edit-NanoServerImage Example1 problem

### ISSUE THREAD

**Issue by TamasKazsoki** [MicrosoftDocs/windows-powershell-docs#105]
In the Edit-NanoServerImage Example1 there is a problem: "-MediaPath D:\" Edit-NanoServerImage PowerShell method does not have "-MediaPath" option available. Only -BasePath and -TargetPath.

**Comment by e0i** [comment]
@TamasKazsoki Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
