### ISSUE TITLE
Access denied even when running as administrator

### ISSUE THREAD

**Issue by srochford46** [MicrosoftDocs/windows-powershell-docs#1051]
I keep getting access denied even when I'm running as administrator. I used this script to test:
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
Confirm-SecureBootUEFI

The first two lines give the message "True" (ie I am in elevated mode) but the next throws the error: Confirm-SecureBootUEFI : Unable to set proper privileges. Access was denied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea950120-025b-d301-24cf-c9adbcbb33a7
* Version Independent ID: 4bb3ad86-2169-b897-548c-6e9117c5b8b6
* Content: [Confirm-SecureBootUEFI (secureboot)](https://docs.microsoft.com/en-us/powershell/module/secureboot/confirm-securebootuefi?view=win10-ps#feedback)
* Content Source: [docset/windows/secureboot/confirm-securebootuefi.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/secureboot/confirm-securebootuefi.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@srochford46 

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
