### ISSUE TITLE
Blocked inheritance question

### ISSUE THREAD

**Issue by SirJewDanielBerg** [MicrosoftDocs/windows-powershell-docs#1053]
Hi.

This article doesn't clarify if GPOs in other parent OUs different to the parent OU of MyOU would apply.

For example, if I have a user in a completely different parent OU and sub-OU, with a GPO to map a drive as a user setting, would that GPO apply when said user logs into a machine that is inside an OU in a completely different parent OU that has blocked inheritance turned on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0768068-c8ac-91de-3f3c-e31e01f4a225
* Version Independent ID: ebe4263f-4a02-c9f1-8c9d-2a445590d724
* Content: [Set-GPInheritance (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/set-gpinheritance?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/set-gpinheritance.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/set-gpinheritance.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@SirJewDanielBerg 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by velkovb** [comment]
@SirJewDanielBerg Hi, Thank you for your feedback on MicrosoftDocs. If I correctly understand your question, mapping a drive is a User setting so the GPO that does it will apply in on the user. The location and GPOs for the machine do not have effect on user settings. Let me know if that answers your question.

**Comment by e0i** [comment]
@SirJewDanielBerg We are closing this issue as we couldn't get response from your side regarding additional details. Feel free to re-open this issue with clarifications and we'll follow-up with a PR. Thank you.

**Comment by e0i** [comment]
@officedocsbot close
