### ISSUE TITLE
"Example 3: Block inheritance for an OU in a domain" is wrong

### ISSUE THREAD

**Issue by SirJewDanielBerg** [MicrosoftDocs/windows-powershell-docs#1054]
I think the title for Example 3 should be "Example 3: Unblock inheritance for an OU in a domain".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0768068-c8ac-91de-3f3c-e31e01f4a225
* Version Independent ID: ebe4263f-4a02-c9f1-8c9d-2a445590d724
* Content: [Set-GPInheritance (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/set-gpinheritance?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/set-gpinheritance.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/set-gpinheritance.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @SirJewDanielBerg 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.
