### ISSUE TITLE
What does no return value mean?

### ISSUE THREAD

**Issue by MikeChristensen** [MicrosoftDocs/windows-powershell-docs#1063]
What does it mean if Import-PfxCertificate does not output anything or return anything, however nothing gets imported into the cert store?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f36c4f79-411b-f859-7488-456b65e61e73
* Version Independent ID: 9a5652dd-c33c-a658-9ee1-3af47189136a
* Content: [Import-PfxCertificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-pfxcertificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/import-pfxcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/import-pfxcertificate.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by MikeChristensen** [comment]
For example:

![image](https://user-images.githubusercontent.com/6528426/58120290-c96c6080-7bb9-11e9-9743-82b5c15bbb01.png)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by MikeChristensen** [comment]
Figured this out, I believe this is the behavior when the PFX file has no private key.

**Comment by e0i** [comment]
@officedocsbot close
