### ISSUE TITLE
Get-TlsCipherSuite - No Documentation on "Protocols"

### ISSUE THREAD

**Issue by danieldjewell** [MicrosoftDocs/windows-powershell-docs#1067]
Get-TlsCipherSuite returns the "Protocols" value but there is no information/reference to what these values are or how to resolve them. Perhaps a link to that information or inclusion of a table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec96c08-42f2-4f28-312f-0bd043aa74c2
* Version Independent ID: 563d7048-b46e-c459-168c-ff2aa028a0d1
* Content: [Get-TlsCipherSuite (tls)](https://docs.microsoft.com/en-us/powershell/module/tls/get-tlsciphersuite?view=win10-ps#feedback)
* Content Source: [docset/windows/tls/get-tlsciphersuite.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/tls/get-tlsciphersuite.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@danieldjewell 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@danieldjewell 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
