### ISSUE TITLE
The description of ServicePrincipalNames is not correct

### ISSUE THREAD

**Issue by juanirm** [MicrosoftDocs/windows-powershell-docs#1071]
Though the issue has been marked as "Closed" on https://github.com/MicrosoftDocs/windows-powershell-docs/issues/246 I can still see the description of the ServicePrincipalNames as originally reported on that issue. 

As title:

-ServicePrincipalNames
Use the DateTime syntax when you specify this parameter. Time is assumed to be local time unless otherwise specified. When a time value is not specified, the time is assumed to 12:00:00 AM local time. When a date is not specified, the date is assumed to be the current date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22bb7107-c501-6b6f-1f6a-dcb66c65b703
* Version Independent ID: b73926ab-2463-30a9-ccc9-7038fbcd98f3
* Content: [Set-ADServiceAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/Set-ADServiceAccount?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/set-adserviceaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-adserviceaccount.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@juanirm The issue is under investigation. Thank you for providing this feedback.

**Comment by j0rt3g4** [comment]
Solved for all 6 files in PR #1080

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
I think in this example the second dash should be removed:
-ServicePrincipalNames**-**@{Add="SQLservice\accounting.corp.contoso.com:1456"};{Remove="SQLservice\finance.corp.contoso.com:1456"}

In set-adserviceaccount.md you should add the yaml table below the parameter description.

**Comment by j0rt3g4** [comment]
@dariomws306 can you specify where are those changes needs to be added?

**Comment by dariomws306** [comment]
The dash should be removed on all the articles.

And yaml table here:
docset/windows/addsadministration/set-adserviceaccount.md

**Comment by j0rt3g4** [comment]
@dariomws306  you are right sir, that was a typo ...

**Comment by j0rt3g4** [comment]
@dariomws306  the Recommendations are already on the PR #1080

**Comment by dariomws306** [comment]
Thanks! Good work!

**Comment by dariomws306** [comment]
Sorry @j0rt3g4, I think you should apply the dash update also on new-adserviceaccount.md.

Also I see that you have modified parameter type from HashTable to String on Set-ADServiceAccount.md, you should leave them as HashTable there (String is ok on Net-ADServiceAccount.md).

Thanks!

**Comment by j0rt3g4** [comment]
@dariomws306  Sure thing, it's done.

**Comment by dariomws306** [comment]
@j0rt3g4 Did you revert type to Hashtable on set-adserviceaccount.md?

**Comment by j0rt3g4** [comment]
No o haven't change that

**Comment by j0rt3g4** [comment]
No

**Comment by e0i** [comment]
Apologies, I have put the PR review request in the issue instead of the PR :man_facepalming:

**Comment by j0rt3g4** [comment]
@dariomws306  @e0i It's done

**Comment by e0i** [comment]
@juanirm 

Upon your feedback, We have updated the content with relevant changes accordingly.

Thank you for bringing this issue to attention.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by juanirm** [comment]
I am sorry to say this but I can still see the issue on the page.
https://docs.microsoft.com/en-us/powershell/module/addsadministration/Set-ADServiceAccount?view=win10-ps

If you go to the "-ServicePrincipalNames" explanation section it is still saying the "Date format" text.
Have you checked this before closing?

**Comment by j0rt3g4** [comment]
@juanirm The corrections are done via **continuous integration** that they could take days to be merged into the public content, please be patient, and let us know if after a week the content is still not visible.
Thank you for your feedback.

**Comment by j0rt3g4** [comment]
@juanirm  If you check the ".md" file at https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-adserviceaccount.md#-serviceprincipalnames
you will realize that the content is already changed there, the only missing part is "continuous integration" to merge the content into the public that would be done in the following days. 👍

**Comment by juanirm** [comment]
Fair enough, I thought that the closing included the full CICD pipe. I'll close it then. 👍

**Comment by j0rt3g4** [comment]
It closes the issue but it should be fully updated soon :)
