### ISSUE TITLE
PrintManager and WindowsUpdateProvider module update issue

### ISSUE THREAD

**Issue by gtl23** [MicrosoftDocs/windows-powershell-docs#108]
While running the update-help, i'm getting this error. 

`PS C:\> Update-Help PrintManagement
Update-Help : Failed to update Help for the module(s) 'PrintManagement' with UI
culture(s) {en-US} : Unable to connect to Help content. The server on which Help content
is stored might not be available. Verify that the server is available, or wait until the
server is back online, and then try the command again.
At line:1 char:1
+ Update-Help PrintManagement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateHelpCo
   mmand

PS C:\> Update-Help WindowsUpdateProvider
Update-Help : Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI
culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI culture en-US. Make
sure the HelpInfoUri property in the module manifest is valid or check your network
connection and then try the command again.
At line:1 char:1
+ Update-Help WindowsUpdateProvider
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.
   UpdateHelpCommand`

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @gtl23 thanks for your comments, I think your questions are more suitable for support services, @yogkumgit will kindly redirect you to the right place.
Thaks!

**Comment by yogkumgit** [comment]
@gtl23  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:
https://docs.microsoft.com/powershell/#pivot=main&panel=community

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
