### ISSUE TITLE
help mentions non-existent productkey parameter

### ISSUE THREAD

**Issue by klishb** [MicrosoftDocs/windows-powershell-docs#1090]
The help for "Set-WindowsEdition" says this:

The ProductKey parameter is required for changing online Server images.

That parameter does not exist in this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf4133c-7c5c-dfcb-3e83-0d41e590d64e
* Version Independent ID: d7205783-6a2b-7178-009f-6929ab0deff8
* Content: [Set-WindowsEdition (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/set-windowsedition?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/dism/Set-WindowsEdition.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/dism/Set-WindowsEdition.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @klishb 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
Updates soon.
