### ISSUE TITLE
New-HgsGuardian and smartcards "Unable to find CNG Key"

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/windows-powershell-docs#1093]
# Overview

Unable to create HGS guardian with smartcard certificate. Is this not a supported scenario? 

# Expected Behavior

Ability to run `New-HgsGuardian -EncryptionCertificateThumprint $enc -SigningCertificateThumbprint $sign` with certificate thumbprints of smartcard-protected certificates. 

# Actual behavior 

Receiving the error "Invoke-CimMethod : Unable to find CNG Key of the '_<thumbprint_' certificate." when attempting to use a certificate stored in a virtual smartcard (Microsoft Smart Card Key Storage Provider). 

Importing 

![smartcard_guardian_1](https://user-images.githubusercontent.com/17114534/58765280-2f040980-8537-11e9-896f-9f25bee19688.png)
![smartcard_guardian_2](https://user-images.githubusercontent.com/17114534/58765281-2f9ca000-8537-11e9-9e88-70e182cd2d3c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94e7d278-67af-8203-e912-edef3b2c4c9c
* Version Independent ID: a926229a-3322-0f78-9061-b165c957ab48
* Content: [New-HgsGuardian (hgsclient)](https://docs.microsoft.com/en-us/powershell/module/hgsclient/new-hgsguardian?view=win10-ps)
* Content Source: [docset/windows/hgsclient/new-hgsguardian.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hgsclient/new-hgsguardian.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @milesgratz  thank you for providing feedback.

Note that the issues section of this repository is intended for product documentation issues.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
Hello, @milesgratz 

The issues section of this repository is intended for documentation problems only.

Please consider checking any relevant resources and asking the community regarding your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

If you feel that this document can also be updated with information related to your request, please comment and re-open this issue we would love to to follow-up with documentation updates.

Thank you for providing feedback.

**Comment by sowjanya365** [comment]
Hi @e0i 

This issue can be closed. Thank you.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by milesgratz** [comment]
In case anyone is curious - we received confirmation from Microsoft Premier support that this scenario is unsupported. You must use a Key Storage Provider that is non-interactive (e.g. HSM)
