### ISSUE TITLE
Get-help redirects to wrong page

### ISSUE THREAD

**Issue by nascar3000** [MicrosoftDocs/windows-powershell-docs#1099]
"get-help Enable-DedupVolume -online" command targets page =&gt; "https://docs.microsoft.com/en-us/powershell/module/data-deduplication/enable-dedupvolume" and page returns 404 seems correct one should be this page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a58a562-0f2f-0cdb-49a8-4c1540655a41
* Version Independent ID: e57597b5-dfce-1e7e-558f-f0440c714ee5
* Content: [Enable-DedupVolume (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/enable-dedupvolume?view=win10-ps#feedback)
* Content Source: [docset/windows/deduplication/enable-dedupvolume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/enable-dedupvolume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@nascar3000 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
This is a known issue with the updatable help pipeline that affects the `Get-Help` and `Update-Help` commands.

There are ongoing efforts to rework the publishing engine. Once matured, failures to update modules are also going to be addressed. Internal sources inform us, the independent collaborators that it is going to take a lot of work.

There have been multiple reports of the help commands not working so please refer to issue #2247 for tracking the progress of this situation.

Thank you.
