### ISSUE TITLE
Get-WindowsOptionalFeature

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/windows-powershell-docs#1106]
So I tried Get-WindowsFeature on 1903 but it didn't recognise the cmdlet. Looks like the way forward now is Get-WindowsOptionalFeature? If so, maybe put a note somewhere about that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f316a89-c55d-5875-13a6-0cc3388f11fd
* Version Independent ID: 4a4059ac-2e0b-2640-8996-ebd0c54ad3a9
* Content: [Get-WindowsFeature (Microsoft.Windows.ServerManager.Migration)](https://docs.microsoft.com/en-us/powershell/module/microsoft.windows.servermanager.migration/get-windowsfeature?view=win10-ps#feedback)
* Content Source: [docset/windows/Microsoft.Windows.ServerManager.Migration/get-windowsfeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/Microsoft.Windows.ServerManager.Migration/get-windowsfeature.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@codaamok 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
