### ISSUE TITLE
Using SQL authentication instead of Windows...

### ISSUE THREAD

**Issue by Davedwin** [MicrosoftDocs/windows-powershell-docs#1108]
I banged my head on the wall for a couple of hours trying to figure this out, so I'm deciding to share. Hopefully, it gets posted. 

To use SQL instead of Windows Authentication method change the -SetPropertyValue attribute "Trusted_Connection=Yes' to "Trusted_Connection=No". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e6b24fa-0ad0-4d24-eb0a-378b8acdeea9
* Version Independent ID: c67b845b-c7d3-d084-52ba-154f7ddb4ab2
* Content: [Add-OdbcDsn (wdac)](https://docs.microsoft.com/en-us/powershell/module/wdac/add-odbcdsn?view=win10-ps)
* Content Source: [docset/windows/wdac/add-odbcdsn.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/wdac/add-odbcdsn.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by Davedwin** [comment]
It's working, I just wanted to share what I found as it wasn't documented anywhere.
