### ISSUE TITLE
'Add-WindowsPackage' is not recognized

### ISSUE THREAD

**Issue by MooreSys** [MicrosoftDocs/windows-powershell-docs#1115]
The term 'Add-WindowsPackage' is not recognized as the name of a cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19dfb03-4f92-397e-b9e5-f758f600f2aa
* Version Independent ID: 7ba6c305-c08a-1c59-d034-dadc00d426dd
* Content: [Add-WindowsPackage (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/add-windowspackage?view=win10-ps#feedback)
* Content Source: [docset/windows/dism/add-windowspackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/add-windowspackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@MooreSys In our investigation it has been found that there might be version incompatibilities for this cmdlet between the version you are running and of documentation.

Would you be able to clarify which Windows version you have been running for that cmdlet?

Thanks in advance.

**Comment by e0i** [comment]
@MooreSys Following up.

**Comment by e0i** [comment]
@MooreSys 

We are closing this issue as there hasn't been a response from your side regarding the details on the issue.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
