### ISSUE TITLE
Module [vpnclient] - Set-VpnConnectionIpsecConfiguration - No way to view current config

### ISSUE THREAD

**Issue by danieldjewell** [MicrosoftDocs/windows-powershell-docs#1116]
This might be more than just a documentation issue (possibly more of a referral to the [vpnclient] module team...) ... However, there is no way to *view* the current settings set by this command: the ```Get-VpnConnection``` cmdlet does not display the Ipsec configuration and there is no corresponding ```Get-VpnConnectionIpsecConfiguration``` cmdlet. 

Although this cmdlet does indeed have a way to set to "defaults" (i.e. ```-RevertToDefault```) - the documentation does not specify what those defaults are. 

Obviously, the inability to display current settings or know what the defaults are makes troubleshooting a connection issue caused by mismatched IPsec settings a real issue. On a side note, an update of the documentation to confirm/clarify that this is modifying the *IPsec* (e.g. Phase 2) configuration or the Phase 1 (ISAKMP - IKEv1//IKEv2) configuration. 

Thank you, as always!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb2472e-4c1f-b26f-709b-12336de2728b
* Version Independent ID: e0eff45a-be41-6dbb-ab48-724c08a854b5
* Content: [Set-VpnConnectionIPsecConfiguration (vpnclient)](https://docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionipsecconfiguration?view=win10-ps#feedback)
* Content Source: [docset/windows/vpnclient/set-vpnconnectionipsecconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/vpnclient/set-vpnconnectionipsecconfiguration.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by gl1xtx** [comment]
(get-vpnconnection).ipseccustompolicy seems to work

**Comment by msbemba** [comment]
@danieldjewell Thank you for your feedback. As @gl1xtx mentioned  (get-vpnconnection).ipseccustompolicy should be able to provide you the IPsec configuration.

Thanks
Sri

**Comment by e0i** [comment]
Hello @danieldjewell ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
