### ISSUE TITLE
Remove-DnsServerResourceRecord: Remove SRV record

### ISSUE THREAD

**Issue by ivoruetsche** [MicrosoftDocs/windows-powershell-docs#1117]
Hi

How can I remove a specific SRV record?

I can specify these options:
-ZoneName "test.mydomain.com"
-Name "_test._tcp"
-RRType "SRV"

But how looks the -RecordData parameter? It should be a string, but how should looks like this string?

A get give me these output:
PS C:\windows\system32> (Get-DnsServerResourceRecord -ZoneName "test.mydomain.com" -Name "_test._tcp" -RRType "SRV").RecordData

DomainName     : test.
Port           : 20
Priority       : 5
Weight         : 10
PSComputerName :

DomainName     : test1.
Port           : 31
Priority       : 11
Weight         : 21
PSComputerName :

PS C:\windows\system32>

How looks like a RecordData string for the 2nd record?

Ivo

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @ivoruetsche 

The issues section of this repository is intended for documentation problems only.

Please consider checking any relevant resources and asking the community regarding your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

If you feel that this document can also be updated with information related to your request, please comment and re-open this issue we would love to to follow-up with documentation updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
