### ISSUE TITLE
DISM Module Repository

### ISSUE THREAD

**Issue by NeoBeum** [MicrosoftDocs/windows-powershell-docs#1118]
Does the DISM Module have a GitHub Repository so I can add and extend the WinPE Features on Demand Package? There are several options missing. I tried searching the PowerShell 
WinPE-DismCmdlets-Package~31bf3856ad364e35

I tried searching https://github.com/PowerShell and couldn't find it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2909a7c-0b34-e12f-d03f-402e895d3886
* Version Independent ID: 583e305b-89cd-15a4-15de-822209712318
* Content: [DISM](https://docs.microsoft.com/en-us/powershell/module/dism/?view=win10-ps)
* Content Source: [docset/windows/dism/dism.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/dism.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by NeoBeum** [comment]
I'll be adding

```
Cleanup-WindowsImage-Path <PATH> -AnalyzeComponentStore 
Cleanup-WindowsImage -Path <PATH> -StartComponentCleanup 
Cleanup-WindowsImage-Path <PATH> -StartComponentCleanup -ResetBase
```

and adding Aliases for the above
```
Repair-WindowsImage -Path <PATH> -AnalyzeComponentStore 
Repair-WindowsImage -Path <PATH> -StartComponentCleanup 
Repair-WindowsImage -Path <PATH> -StartComponentCleanup -ResetBase
Optimize-WindowsImage -Path <PATH> -AnalyzeComponentStore
Optimize-WindowsImage -Path <PATH> -StartComponentCleanup 
Optimize-WindowsImage -Path <PATH> -StartComponentCleanup -ResetBase
```

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by sukihanabi** [comment]
Hello, @NeoBeum There isn't a dedicated repo for the said cmdlet in DISM but these cmdlet is included within the Windows PowerShell repository.

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/repair-windowsimage.md
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/optimize-windowsimage.md

Would you please verify that the cmdlet you would like to add are working.

Thank you for your feedback.

**Comment by NeoBeum** [comment]
@sukihanabi 

There's currently a bug with a few of the cmdlets when using -LogPath
Wimgapi is invoked, and the log finishes there.

I'll add a detailed report when I am able to review what you have sent to me at home later.

**Comment by e0i** [comment]
Hello @NeoBeum Please create a separate ticket for the respective cmdlets that fail with -LogPath. 

This issue is being closed as @sukihanabi seems to have answered your question.

Feel free to re-open this issue if there is something that you'd like to have added to the associated documentation.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
