### ISSUE TITLE
Confirm prompt defaults to $true

### ISSUE THREAD

**Issue by Nothing4You** [MicrosoftDocs/windows-powershell-docs#1119]
Related: https://social.technet.microsoft.com/Forums/windowsserver/en-US/68274d6e-db57-43ad-beca-aaa048438842/removeadgroupmember-disable-confirm-prompt?forum=winserverpowershell

Remove-ADPrincipalGroupMembership asks for confirmation even without passing -Confirm.
Taken from the linked page above I was able to get it to silently process by passing -Confirm:$false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a040d973-5979-a10d-bbed-3b4221f45cda
* Version Independent ID: dc1ba824-fdb3-9160-9e74-c6ecf57629b5
* Content: [Remove-ADPrincipalGroupMembership (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/remove-adprincipalgroupmembership?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/activedirectory/Remove-ADPrincipalGroupMembership.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Remove-ADPrincipalGroupMembership.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by sowjanya365** [comment]
Hi @Nothing4You 

Thank you for reaching out!

Yes, document has been updated with the notes section. 

https://docs.microsoft.com/en-us/powershell/module/activedirectory/remove-adprincipalgroupmembership?view=winserver2012-ps#notes

By default, this cmdlet has the -Confirm parameter set, which prompts you to confirm before a removal of the specified object type can occur. To bypass prompting for confirmation before removal, you can specify -Confirm:$false when using this cmdlet.

Hope this clarifies. Thank you.

**Comment by Nothing4You** [comment]
Hi @sowjanya365, thanks for your response.
That note should not be needed if the parameter documentation gets corrected here: https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Remove-ADPrincipalGroupMembership.md#-confirm
The `Default value` should be `True` from my understanding.

**Comment by sowjanya365** [comment]
Hi @Nothing4You 

Thanks for your inputs. We've updated the document now. Once the PR gets merged, we will be able to see the changes.

**Comment by e0i** [comment]
@Nothing4You 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
