### ISSUE TITLE
Example has a typo

### ISSUE THREAD

**Issue by dmraymond** [MicrosoftDocs/windows-powershell-docs#1120]
CertifcateStoreName should be CertificateStoreName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 057d153d-fc39-2e9a-e58f-1f20f7d7859a
* Version Independent ID: ad1f5a0d-4fac-d809-f683-ebed799d70da
* Content: [Add-NetIPHttpsCertBinding (networktransition)](https://docs.microsoft.com/en-us/powershell/module/networktransition/add-netiphttpscertbinding?view=win10-ps#feedback)
* Content Source: [docset/windows/networktransition/add-netiphttpscertbinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/networktransition/add-netiphttpscertbinding.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@dmraymond 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
