### ISSUE TITLE
Page is not finished

### ISSUE THREAD

**Issue by v-stsech** [MicrosoftDocs/windows-powershell-docs#1123]
This is not completed. 
It would be nice to have a description of the effect of running the command. How is the ecc curve chosen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 192ebef7-3fd8-5691-2d89-3616ab2a44fc
* Version Independent ID: 088e91d5-11c8-d20e-2593-9d92853e1c36
* Content: [Disable-TlsEccCurve (tls)](https://docs.microsoft.com/en-us/powershell/module/tls/disable-tlsecccurve?view=win10-ps#feedback)
* Content Source: [docset/windows/tls/disable-tlsecccurve.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/tls/disable-tlsecccurve.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@v-stsech 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
