### ISSUE TITLE
Thanks for the cmdlets

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-powershell-docs#1125]
I have created following scripts  after reading this article

$Apps = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Apps"
$Apps.RootCauses.Resolutions[0]

$Audio = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Audio"
$Audio.RootCauses.Resolutions[0]

$BITS = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\BITS"
$BITS.RootCauses.Resolutions[0]

$Bluetooth = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Bluetooth"
$Bluetooth.RootCauses.Resolutions[0]

$Device = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Device"
$Device.RootCauses.Resolutions[0]

$DeviceCenter = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\DeviceCenter"
$DeviceCenter.RootCauses.Resolutions[0]

$IEBrowseWeb = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\IEBrowseWeb"
$IEBrowseWeb.RootCauses.Resolutions[0]

$IESecurity = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\IESecurity"
$IESecurity.RootCauses.Resolutions[0]

$Keyboard = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Keyboard"
$Keyboard.RootCauses.Resolutions[0]

$Networking = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Networking"
$Networking.RootCauses.Resolutions[0]

$PCW = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\PCW"
$PCW.RootCauses.Resolutions[0]

$Power = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Power"
$Power.RootCauses.Resolutions[0]

$Printer = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Printer"
$Printer.RootCauses.Resolutions[0]

$Search = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Search"
$Search.RootCauses.Resolutions[0]

$Speech = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Speech"
$Speech.RootCauses.Resolutions[0]

$Video = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Video"
$Video.RootCauses.Resolutions[0]

$WindowsMediaPlayerConfiguration = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\WindowsMediaPlayerConfiguration"
$WindowsMediaPlayerConfiguration.RootCauses.Resolutions[0]

$WindowsMediaPlayerMediaLibrary = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\WindowsMediaPlayerMediaLibrary"
$WindowsMediaPlayerMediaLibrary.RootCauses.Resolutions[0]

$WindowsMediaPlayerPlayDVD = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\WindowsMediaPlayerPlayDVD"
$WindowsMediaPlayerPlayDVD.RootCauses.Resolutions[0]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0e7274c-7030-8adf-6d96-0fcec5abe467
* Version Independent ID: bb0bb9f3-5ee9-8319-9166-6459e785b757
* Content: [Get-TroubleshootingPack (troubleshootingpack)](https://docs.microsoft.com/en-us/powershell/module/troubleshootingpack/get-troubleshootingpack?view=win10-ps)
* Content Source: [docset/windows/troubleshootingpack/get-troubleshootingpack.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/troubleshootingpack/get-troubleshootingpack.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@RAJU2529 Would you kindly clarify the subject of this issue?

Since issues section of this repository is for product documentation issues, we would like to know what is missing, what needs to be updated, etc.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
