### ISSUE TITLE
Please add information about -Version

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/windows-powershell-docs#1126]
and what it actually changes in the behavior

Sample:
New-StoragePool -Version WindowsServer2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915197ed-248f-4e41-4647-20f02bcd9989
* Version Independent ID: b2332c94-b147-fcfb-1b8a-83c0dd1f99a3
* Content: [New-StoragePool (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/New-StoragePool?view=win10-ps#feedback)
* Content Source: [docset/windows/storage/new-storagepool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/new-storagepool.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by sowjanya365** [comment]
Hi @rafalfitt 

Thank you for reaching out!

We don't see a parameter mapped to this command. Are you saying. we need to add this parameter? Kindly elaborate more and help us understand your query. 

Thank you.

**Comment by rafalfitt** [comment]
Probably yes.
Powershell on my fully patched Windows 1903 shows such parameter:
![2019-07-17 122800](https://user-images.githubusercontent.com/36852431/61368568-70a20700-a88e-11e9-8d54-ba86afe5486a.png)

**Comment by e0i** [comment]
Hello, @rafalfitt 

The `-Version` has been introduced in Server 2019, which is not currently supported and the current documentation only covers only the following:

- Windows 10 and Windows Server 2016 PowerShell
- Windows 8 and Windows Server 2012 PowerShell
- Windows 8.1 and Windows Server 2012 R2 PowerShell


Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by masiton** [comment]
Can you please elaborate what do you mean by the parameter not being supported? I had my Storage Pool in version "Windows Server 2019". Upon executing Update-StoragePool cmdlet, it is now showing a version value of "vNext". I can't find anything about what does this mean, what exactly has been updated, what has been changed, what is new and most importantly, what vNext even means.

**Comment by VLG17** [comment]
@rafalfitt @masiton "vNext" corresponds to the next Windows build. More details [here ](https://techcommunity.microsoft.com/t5/windows-server-insiders/announcing-windows-server-vnext-preview-build-19551/m-p/1133432) and [here](https://blogs.windows.com/windowsexperience/2019/11/19/announcing-windows-server-vnext-insider-preview-build-19023/).

Until the new build comes out, i guess this will not get documented. As to why you are seeing this with build 1903, i don't have an answer unfortunately. Are you maybe in the [Insider Program](https://techcommunity.microsoft.com/t5/windows-server-insiders/bd-p/WindowsServerInsiders)? Did you install any new updates (maybe Powershell related) which could influence this?

**Comment by rafalfitt** [comment]
I was not on any Insider Program build. But semi-frequently I do run:

Get-Module -ListAvailable | Update-Module -Verbose
Update-Help -Force -ErrorAction Continue
