### ISSUE TITLE
This command does not work when attempting to update records that are stored in a zonescope.

### ISSUE THREAD

**Issue by BearGFR** [MicrosoftDocs/windows-powershell-docs#1127]
Attempting to use this command to update records in a zonescope (both -zonename and -zonescope specified) does not work. It always returns an error:

set-dnsserverresourcerecord : Resource record in OldInputObject not found in scope &lt;scopename&gt; of zone &lt;zonename&gt; on server &lt;server&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2335a3db-5fe1-404b-aa3d-a3b4f10086fa
* Version Independent ID: 3dfd55d0-2210-626c-b9a6-f584316ec374
* Content: [Set-DnsServerResourceRecord (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/set-dnsserverresourcerecord?view=win10-ps#feedback)
* Content Source: [docset/windows/dnsserver/set-dnsserverresourcerecord.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/set-dnsserverresourcerecord.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@BearGFR 

The issues section of this repository is for product documentation issues.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
