### ISSUE TITLE
"profile" argument, default value should probably be "Any" instead of "None"

### ISSUE THREAD

**Issue by pgorod** [MicrosoftDocs/windows-powershell-docs#1128]
The "profile" argument of New-NetFirewallRule is stated in this page as having a default value of "None", but the text a few lines above says the default is "Any" which I guess makes more sense, since you "None" is not an accepted firewall profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a81ceb77-8de5-8c07-c0c4-fa3d616d859f
* Version Independent ID: 736dd392-788a-c102-dfcb-29a08c2c9f9d
* Content: [New-NetFirewallRule (netsecurity)](https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps#feedback)
* Content Source: [docset/windows/netsecurity/new-netfirewallrule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netsecurity/new-netfirewallrule.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@pgorod 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
