### ISSUE TITLE
AccountInactive Param 

### ISSUE THREAD

**Issue by archgriffin** [MicrosoftDocs/windows-powershell-docs#1131]
I think the information for the parameter means Windows 2003 or higher, the way it is currently worded makes it sound like it only works in a domain function level of 2003. 

"Note that this attribute is only used when the domain is in Windows Server 2003 Domain Functional Level, so this parameter will only work in that mode."
I would think this is what is meant
"Note that this attribute is only used when the domain is in Windows Server 2003 or higher Domain Functional Level, so this parameter will only work in those modes."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87483a05-ea3b-19c2-3d31-4701e03e68e2
* Version Independent ID: 917d2078-1e43-895a-e3cb-d6e64844196e
* Content: [Search-ADAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/search-adaccount?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/search-adaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/search-adaccount.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@archgriffin 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.
