### ISSUE TITLE
Confirm-SecureBootUEFI Fails on Windows Server 2012 Server Core

### ISSUE THREAD

**Issue by PaleHoser** [MicrosoftDocs/windows-powershell-docs#1132]
FYI -

I've successfully used Invoke-Command -ComputerName RemoteMachineName {Confirm-SecureBootUEFI} for full installs of Windows Server 2012.

Using Invoke-Command -ComputerName RemoteMachineName {Confirm-SecureBootUEFI} for Server Core installs of Windows Server 2012 returns:

"The term 'Confirm-SecureBootUEFI' is not recognized as the name of a cmdlet, function, script file, or operable program.  Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

If I run Import-Module SecureBoot first on the Server Core machine, the cmdlet does report successfully.  Please update the documentation to include this detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea950120-025b-d301-24cf-c9adbcbb33a7
* Version Independent ID: 4bb3ad86-2169-b897-548c-6e9117c5b8b6
* Content: [Confirm-SecureBootUEFI (secureboot)](https://docs.microsoft.com/en-us/powershell/module/secureboot/confirm-securebootuefi?view=win10-ps#feedback)
* Content Source: [docset/windows/secureboot/confirm-securebootuefi.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/secureboot/confirm-securebootuefi.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @PaleHoser thank you for providing feedback.

Note that the issues section of this repository is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
