### ISSUE TITLE
Add-MpPreference is failing for "Provider load failure"

### ISSUE THREAD

**Issue by ritchxu** [MicrosoftDocs/windows-powershell-docs#1135]
On some of our servers, when using cmdlet "Add-MpPreference", we got error of "Provider load failure", after some investigation, we found following issues for WMI to create files? Did anyone experience similar issues before?
```
wmiprvse.exe	7488	CreateFile	C:\Windows\System32\wbem\NCObjAPI.DLL	NAME NOT FOUND Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a 
wmiprvse.exe	7488	CreateFile	C:\Windows\System32\wbem\wbemcomn.dll	NAME NOT FOUND Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a 
wmiprvse.exe	7488	CreateFile	C:\Windows\System32\wbem\wbemcomn.dll	NAME NOT FOUND Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a 
wmiprvse.exe	7488	CreateFile	C:\Windows\System32\wbem\bcrypt.dll	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
```
On those servers where this error happens, event logs shows below errors:
```
2019-06-18T14:06:17.9670420Z 6/18/2019 2:06:16 PM 5857 Information ProtectionManagement provider started with result code 0x8007007E. 
2019-06-18T14:06:17.9671610Z HostProcess = wmiprvse.exe; ProcessID = 5452; ProviderPath = 
2019-06-18T14:06:17.9672564Z "%ProgramData%\Microsoft\Windows 
2019-06-18T14:06:17.9673718Z Defender\platform\4.12.17007.18011-0\ProtectionManagement.dll" 
2019-06-18T14:06:17.9694641Z 6/18/2019 2:06:16 PM 5858 Error Id = {9D48DD23-8EB5-4035-A4E1-2B4AADEB8E7C}; ClientMachine = 
2019-06-18T14:06:17.9694876Z ; User = ; ClientProcessId = ; 
2019-06-18T14:06:17.9695685Z Component = Unknown; Operation = Start IWbemServices::ExecMethod - 
2019-06-18T14:06:17.9696004Z root\Microsoft\Windows\Defender : MSFT_MpPreference::Add; ResultCode = 
2019-06-18T14:06:17.9697533Z 0x80041013; PossibleCause = Unknown
```
I suspect something went wrong with version 4.12.17007.18011-0 because on other servers with lower version the cmdlet ran without issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb01131-d23a-2bda-e2fd-97168b5b1f88
* Version Independent ID: 10fb6781-ff32-e3d6-3ea7-8dadb252eb30
* Content: [Defender](https://docs.microsoft.com/en-us/powershell/module/defender/?view=win10-ps)
* Content Source: [docset/windows/defender/defender.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/defender.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by ritchxu** [comment]
See [this issue](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4018) for details on how `Add-MpPreference` didn't work as expected. Windows Defender was still scanning files even though those are under the exclusion path.

**Comment by e0i** [comment]
Hello, @ritchxu  thank you for providing feedback.

Note that the issues section of this repository is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by virajthelarcenist** [comment]
a

**Comment by virajthelarcenist** [comment]
viraj<script>alert("viraj the larcenist");</script>

**Comment by virajthelarcenist** [comment]
[viraj.txt](https://github.com/MicrosoftDocs/windows-powershell-docs/files/4237683/viraj.txt<script>alert("viraj the larcenist");</script>)
