### ISSUE TITLE
New-DedupSchedule does not contain parameters "-StopWhenSystemBusy" or "-Full"

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windows-powershell-docs#1136]
These appear to only be available for usage when using Set-DedupSchedule.

(Performing this on Server 2019)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d4fee7-0557-f699-17e6-1b7729c9b9f4
* Version Independent ID: c16640d7-524c-4a5b-fe78-a6855ea32181
* Content: [New-DedupSchedule (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/new-dedupschedule?view=win10-ps)
* Content Source: [docset/windows/deduplication/new-dedupschedule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/new-dedupschedule.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by eponerine** [comment]
Renaming title due to typo :(

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @eponerine 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by velkovb** [comment]
@eponerine  Hi Ernie,

Thank you for your feedback. Unfortunately, I am unable to reproduce your issue. I have tested both on Server 2016 and Server 2019 and I have the option to specify both parameters.

PS C:\> New-DedupSchedule -Name test -Type GarbageCollection -StopWhenSystemBusy -Full

Enabled    Type               StartTime              Days               Name
-------    ----               ---------              ----               ----
True       GarbageCollection  2:45 AM                {Sunday, Monday... test

Could you provide an example of when you were not able to specify the parameters so we can investigate further?
Also the the information in $PSVersionTable would be useful.

**Comment by eponerine** [comment]
I think I see my problem (and it's completely my fault). 

I thought these parameters were booleans and not switches, so I was trying to pass $true or $false to them. 

I'm sorry for the confusion! Closing the issue out!
