### ISSUE TITLE
Description is wrong

### ISSUE THREAD

**Issue by jricha34** [MicrosoftDocs/windows-powershell-docs#1137]
The description "The Get-ADTrust cmdlet returns all trusted domain objects in the directory." is wrong. This doesn't return all trusted domain objects in the directory. It returns all trusted domain objects in the domain that you are querying. To get all of them for the entire directory would require looping through all of the domains in the forest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73d6bb3c-4ba4-8fd9-0942-7ee7a041eed2
* Version Independent ID: 6dd6c53e-d0f1-3721-d435-4a12c5d79fb2
* Content: [Get-ADTrust (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-adtrust?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Get-ADTrust.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Get-ADTrust.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@jricha34 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by sukihanabi** [comment]
@jricha34 , as we checked, "Get-ADTrust" cmdlet returns all trusted domain objects in the Active Directory. As well as the cmdlet "Get-ADTrust "domain.com" " ; this get the trusted domain object with name 'domain.com'. Perhaps, you can provide more information or references to the inquiry.

**Comment by e0i** [comment]
@jricha34 During the discussion of the related PR #1255, it has been concluded by the reviewers that no changes to the document are necessary. Thank you for taking the time to improve PowerShell documentation.
