### ISSUE TITLE
Remove-DnsServerResourceRecord : InputObject for resource record has an invalid value. 

### ISSUE THREAD

**Issue by alexfreu69** [MicrosoftDocs/windows-powershell-docs#1149]
The command fails with a RecordData value like this:

Remove-DnsServerResourceRecord -RRType SRV -Name "_misc._tcp" -ZoneName "something.local" -RecordData "[0][10][1234][1.1.1.1.]"

Please add a documentation for the correct syntax. It should be:

Remove-DnsServerResourceRecord -RRType SRV -Name "_misc._tcp" -ZoneName "something.local" -RecordData "0","10","1234","1.1.1.1."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a112950f-5cf2-6644-8295-c854ffe72690
* Version Independent ID: 29be8200-81bd-a278-61da-61fb9afef1bd
* Content: [Remove-DnsServerResourceRecord (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/remove-dnsserverresourcerecord?view=win10-ps#feedback)
* Content Source: [docset/windows/dnsserver/remove-dnsserverresourcerecord.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/remove-dnsserverresourcerecord.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by sowjanya365** [comment]
Hi @alexfreu 

Thanks for reaching out!

We don't find anywhere on the document mentioning this - RecordData "[0][10][1234][1.1.1.1.]"

We only found this example.

PS C:\> Remove-DnsServerResourceRecord -ZoneName "contoso.com" -RRType "A" -Name "Host01" -RecordData "10.17.1.41"

Please elaborate more and help us to understand your query. Thank you.

**Comment by alexfreu** [comment]
This doesn't work either - especially if you want to filter for the port as well. Just try it out yourself.
AF.


Am 16.07.2019 18:40 schrieb sowjanya365 <notifications@github.com>:

Hi @alexfreu<https://github.com/alexfreu>

Thanks for reaching out!

We don't find anywhere on the document mentioning this - RecordData "[0][10][1234][1.1.1.1.]"

We only found this example.

PS C:> Remove-DnsServerResourceRecord -ZoneName "contoso.com" -RRType "A" -Name "Host01" -RecordData "10.17.1.41"

Please elaborate more and help us to understand your query. Thank you.

**Comment by sowjanya365** [comment]
Hi @alexfreu 

Thank you for the prompt response. 

Yes, we don't see any issue with the command. Kindly let us know the error that you get. It helps us to understand the issue. Thank you.

**Comment by alexfreu** [comment]
PS C:\Windows\system32>>  get-DnsServerResourceRecord -RRType SRV -ZoneName "sub.domain.local"



HostName                  RecordType Type       Timestamp            TimeToLive      RecordData

--------                  ---------- ----       ---------            ----------      ----------

_foo._tcp                 SRV        33         0                    01:00:00        [0][10][2380][8.8.4.4.]

_foo._tcp                 SRV        33         0                    01:00:00        [0][10][2380][1.1.1.1.]

_foo._tcp                 SRV        33         0                    01:00:00        [0][10][2380][8.8.8.8.]



The second entry should be deleted. We take the RecordData from this output as string (which obviously is wrong)



PS C:\Windows\system32>> remove-DnsServerResourceRecord -RRType SRV -Name "_foo._tcp" -ZoneName "sub.domain.local" -RecordData "[0][10][2380][1.1.1.1.]"

remove-DnsServerResourceRecord : InputObject for resource record has an invalid value. Failed to remove the resource record on xxxxxx server. Please check extended error for additional details.

At line:1 char:1

+ remove-DnsServerResourceRecord -RRType SRV -Name "_foo._tcp" -ZoneNam ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidData: (PLW0400-ADC0001:root/Microsoft/...rResourceRecord) [Remove-DnsServerResourceRecord], CimException

    + FullyQualifiedErrorId : WIN32 13,Remove-DnsServerResourceRecord

Am 16.07.2019 19:21 schrieb sowjanya365 <notifications@github.com>:

Hi @alexfreu<https://github.com/alexfreu>

Thank you for the prompt response.

Yes, we don't see any issue with the command. Kindly let us know the error that you get. It helps us to understand the issue. Thank you.

**Comment by sowjanya365** [comment]
Hi @alexfreu 

Thank you. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: 
https://docs.microsoft.com/office365/admin/contact-support-for-business-products 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by alexfreu** [comment]
Why should I open a ticket? I already have a solution.

**Comment by sowjanya365** [comment]
Sure, Can you explain where and what exactly needs to be changed? Thank you.

**Comment by sowjanya365** [comment]
Hello @alexfreu69 

Apologies for the delayed response. 

Are you referring this change in the following section?

https://docs.microsoft.com/en-us/powershell/module/dnsserver/remove-dnsserverresourcerecord?view=win10-ps#inputs

Please confirm. Thank you.

**Comment by sowjanya365** [comment]
Hi @alexfreu69 

Hope you are doing well!

We're closing this issue as we have not received your response and enough information to investigate further. 

We've verified from our end the "Example 3: Remove an A record". We don't find any issue with this command. 

PS C:\> Remove-DnsServerResourceRecord -ZoneName "contoso.com" -RRType "A" -Name "Host01" -RecordData "10.17.1.41"

Thank you!

**Comment by dieselVtwin** [comment]
Can this issue be re-opened, please?

I believe that @alexfreu69 was requesting additional information in the documentation on the subject of removing an "SRV" record using the Remove-DnsServerResourceRecord.

Removing an "A" record is less complex than than removing an "SRV" record when using the Remove-DnsServerResourceRecord cmdlet.  This is because the RecordData attribute is single valued in an "A" record, but is multivalued in an "SRV" record.

When using either the DNS GUI console or the Add-DnsServerResourceRecord cmdlet, the multiple values of the SRV record must be specifically listed.

Also, the format of the data in the RecordData attribute of an SRV record doesn't match between the Get-DnsServerResourceRecord and the Remove-DnsServerResourceRecord.

The RecordData in an "SRV" record returned using Get-DnsServerResourceRecord is square bracket delimited and in the format of "[<Priority>][<Weight>][<Port>][<HostFQDN>]", like "[0][100][88][somehost.somedomain.sometdl.]".

The RecordData in an "SRV" record being removed using the Remove-DnsServerResourceRecord is comma delimited and in the format of [<Priority>,<Weight>,<Port>,<HostFQDN>", like "0,100,88,somehost.somedomain.sometdl.".

However, I don't find the Remove cmdlet intuitive when working with "SRV" records, and the example of the "A" record doesn't help with the RecordData of an "SRV" record.

Providing an example or explanation of this in the documentation would be useful.

Thanks,
Alan

**Comment by e0i** [comment]
@dieselVtwin Thank you for following up. Under investigation.

**Comment by msbemba** [comment]
@dieselVtwin Thank you for your feedback. We have made changes to the doc via PR# https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2050

Thanks
Sri
