### ISSUE TITLE
PowerShell Docs not syncing to website

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/windows-powershell-docs#1170]
@e0i  Interesting problem I just discovered:

![image](https://user-images.githubusercontent.com/447485/60910182-0fef4a80-a24e-11e9-956c-0568e26fc866.png)

However, if you go to the associated markdown page for the Format-Volume cmdlet, you will see the documentation is correct:

https://docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=win10-ps (WRONG)

https://raw.githubusercontent.com/MicrosoftDocs/windows-powershell-docs/master/docset/windows/storage/format-volume.md (CORRECT, go to line 93):

> ### Example 2: Full format using FAT32
> ```
> PS C:\>Format-Volume -DriveLetter D -FileSystem FAT32 -Full -Force
> ```

What's amazing is this was [fixed _9 months ago_](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/6fdd3c9274917e0ebb1e2e2d57c8444f3b9d0490), indicating there is a _serious problem_ with how the windows-powershell-docs GitHub Repo syncs back to the website

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Under investigation.

**Comment by e0i** [comment]
Hello @jzabroski The deployment system has been fixed and public contributions via GitHub are now being continuously synced to live. Thank you for providing feedback.
