### ISSUE TITLE
how to import from other store (like My)

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/windows-powershell-docs#1171]
tried this but doesn't work: 
```powershell
$cert = Get-ChildItem "cert:\LocalMachine\My" | Where-Object { $_.Subject -match "CN=ldap.my-corp.com" }
Import-Certificate -Filepath $cert -CertStoreLocation "cert:\LocalMachine\Root"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c694289c-79f5-03cd-38aa-5d2ec76988bd
* Version Independent ID: 0a5a5227-c7da-d308-9fca-857b49f6cf7c
* Content: [Import-Certificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-certificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/import-certificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/import-certificate.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by TiloGit** [comment]
this works but requires an export first: 

```powershell
$cert = Get-ChildItem "cert:\LocalMachine\My" | Where-Object { $_.Subject -match "CN=ldap.my-corp.com" }
Export-Certificate -Cert $cert -FilePath c:\tools\ldapcert.sst -Type SST
Import-Certificate -Filepath c:\tools\ldapcert.sst -CertStoreLocation "cert:\LocalMachine\Root"
```

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@TiloGit 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.

**Comment by TiloGit** [comment]
this was an ask to expand your examples of this documentation page for the case I listed.

**Comment by e0i** [comment]
@TiloGit 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you for providing clarifications.

**Comment by sukihanabi** [comment]
Hello @TiloGit, as we checked command: "Import-Certificate -Filepath $cert -CertStoreLocation "cert:\LocalMachine\Root" " will work if you have an exported file save on your file location.

The provided export and import file command works as well, and it is already in the example provided in the repo.

See Export-Certificate for reference, https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/export-certificate.md

**Comment by TiloGit** [comment]
@ sukihanabi I was looking for an example without save cert locally (copy from store to store) but might not be an option.

**Comment by e0i** [comment]
@TiloGit Based on the reviewer's discussion regarding a PR attempt for this issue, #1256, it has been found that such an example is not necessary. Thank you for taking the time to participate in improving documentation.
