### ISSUE TITLE
Parameter missing: Recipe

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/windows-powershell-docs#1174]
This command (Add-WindowsCapability) accepts a `-Recipe` parameter too, but this parameter is not documented here.

![Screenshot](https://user-images.githubusercontent.com/17097175/61182614-3f85c480-a64b-11e9-9245-7110a4162b52.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a11a3f-a432-fd7e-d05e-8b80e891b3af
* Version Independent ID: 256de206-99fd-d0d4-4f1a-3321432d36f8
* Content: [Add-WindowsCapability (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/add-windowscapability?view=win10-ps#feedback)
* Content Source: [docset/windows/dism/add-windowscapability.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/add-windowscapability.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @skycommand 

The `-Recipe` parameter has been introduced in Server 2019, which is not currently supported and the current documentation covers up to version 2016.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
