### ISSUE TITLE
unreliable

### ISSUE THREAD

**Issue by mchaudoir** [MicrosoftDocs/windows-powershell-docs#1175]
does anyone use Get-GPPrefRegistryValue?  I have found the command to be unreliable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccebfc52-6153-93ac-5d5b-f83e83c03d08
* Version Independent ID: 274176d0-a2c7-0baf-12c7-9ce3c27dc0a6
* Content: [Get-GPPrefRegistryValue (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/get-gpprefregistryvalue?view=win10-ps#feedback)
* Content Source: [docset/windows/grouppolicy/get-gpprefregistryvalue.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/get-gpprefregistryvalue.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@mchaudoir 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your question via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
