### ISSUE TITLE
Note that downloading the module is required

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/windows-powershell-docs#1184]
What the title says, mostly. This module must be downloaded from PSGallery before it can be used. I would appreciate it if this fact was stated on this page, as I thought this module was built into Windows like (most of) the other modules in this part of the Module Browser. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4269e6eb-f6f6-d9f3-ac74-00708976d272
* Version Independent ID: b6d99f97-2394-8974-abfa-30fd85529c18
* Content: [Microsoft.DiagnosticDataViewer](https://docs.microsoft.com/en-us/powershell/module/Microsoft.DiagnosticDataViewer/?view=win10-ps)
* Content Source: [docset/windows/Microsoft.DiagnosticDataViewer/Microsoft.DiagnosticDataViewer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/Microsoft.DiagnosticDataViewer/Microsoft.DiagnosticDataViewer.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @wjk 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by sowjanya365** [comment]
Hi @wjk 

Thanks for reaching out!

 On Windows-based computers, if features that are included with the operating system have cmdlets to manage them, those modules are preinstalled. When you install a Windows feature, by using, for example, the Add Roles and Features Wizard in Server Manager, or the Turn Windows features on or off dialog box in Control Panel, any PowerShell modules that are part of the feature are installed. Many other modules come in an installer or Setup program that installs the module. And we need to import the missing modules manually. 

Hope this clarifies your query. Thank you!
