### ISSUE TITLE
syntax correction

### ISSUE THREAD

**Issue by fatherjack** [MicrosoftDocs/windows-powershell-docs#1193]
Example 3 references a non-existent function **Get-FirewallRule** when it should reference the topic of this page **Get-NetFirewallRule**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca016e79-1b11-8004-99aa-362cf6c082e9
* Version Independent ID: 2c7f3269-445e-b9dd-a382-5f64f44ab770
* Content: [Get-NetFirewallPortFilter (netsecurity)](https://docs.microsoft.com/en-us/powershell/module/netsecurity/get-netfirewallportfilter?view=winserver2012r2-ps#examples)
* Content Source: [docset/winserver2012r2-ps/netsecurity/Get-NetFirewallPortFilter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/netsecurity/Get-NetFirewallPortFilter.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @fatherjack 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@fatherjack 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
