### ISSUE TITLE
-DestinationName parameter is not respected in Windows 10 1809 build 17763.557

### ISSUE THREAD

**Issue by rewritten1** [MicrosoftDocs/windows-powershell-docs#1194]
I tried using Export-WindowsImage and everything except the -DestinationName parameter is respected when the command is run. -DestinationName ends up being the name of the image you are exporting from instead of the one manually specified. Using Dism.exe to export the image with desired DestinationName does not have this problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c0afe94-7b25-575a-ccdb-982d5b9a3802
* Version Independent ID: faf9321f-f51c-e452-1c34-1e58cb18c666
* Content: [Export-WindowsImage (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/export-windowsimage?view=win10-ps#feedback)
* Content Source: [docset/windows/dism/export-windowsimage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/export-windowsimage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@rewritten1 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
