### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by lihas** [MicrosoftDocs/windows-powershell-docs#1202]
Configurable Language and Cultural Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2bb150e-210b-eb88-6855-3ac7f6d02edf
* Version Independent ID: fa4119ca-f762-62cc-8421-d4673035c76e
* Content: [Get-WinSystemLocale (international)](https://docs.microsoft.com/en-us/powershell/module/international/get-winsystemlocale?view=win10-ps#feedback)
* Content Source: [docset/windows/international/get-winsystemlocale.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/international/get-winsystemlocale.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Resolved via the following commit,

[[ GitHub] History for docset/windows/international/Get-WinSystemLocale.md - MicrosoftDocs/windows-powershell-docs ](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/master/docset/windows/international/Get-WinSystemLocale.md)

Thank you.
