### ISSUE TITLE
Example 5 Formatting

### ISSUE THREAD

**Issue by danijeljw** [MicrosoftDocs/windows-powershell-docs#1208]
The second line of Example 5 is formatted incorrectly. It's a string and should be explicitly passed through like one of these two lines:
```powershell
PS C:\> $vhdsize = '127GB' 
PS C:\> $vhdsize = "127GB"
```
The third line should be formatted the same as all your other documentation too. The pipe control should have a space following it on the line. From this:
```powershell
PS C:\> New-VHD -Path $vhdpath -Dynamic -SizeBytes $vhdsize | Mount-VHD -Passthru |Initialize-Disk -Passthru |New-Partition -AssignDriveLetter -UseMaximumSize |Format-Volume -FileSystem NTFS -Confirm:$false -Force
```
to this:
```powershell
PS C:\> New-VHD -Path $vhdpath -Dynamic -SizeBytes $vhdsize | Mount-VHD -Passthru | Initialize-Disk -Passthru | New-Partition -AssignDriveLetter -UseMaximumSize | Format-Volume -FileSystem NTFS -Confirm:$false -Force
```
This keeps it uniform and easy for the user to read. It also matches the first instance of the pipe control being used too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4fcdbfc-802a-3308-b689-ce8ea3bde1c6
* Version Independent ID: 831f5800-5656-9b40-9f78-57c82234351d
* Content: [New-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/new-vhd?view=win10-ps#feedback)
* Content Source: [docset/windows/hyper-v/new-vhd.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/new-vhd.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@danijeljw Thank you for your feedback. We have made changes to the doc via PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1248

Thanks
Sri

**Comment by e0i** [comment]
@danijeljw In our investigation it has been [found](https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1248#issuecomment-523106778) that no changes are necessary to the referenced documentation.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
