### ISSUE TITLE
-SizeBytes Switch cannot interpret MB,GB values

### ISSUE THREAD

**Issue by danijeljw** [MicrosoftDocs/windows-powershell-docs#1209]
The `-SizeBytes` values in each example cannot interpret the text being provided.

It needs to be converted to type `[UInt64]`. Also the math involved can be counted in-line. These examples do not support a user being able to apply them to real-world scenarios. It needs to be explained that a GB is 1024 MB, which is 1024 KB which is 1024 Bytes.

So for **Example 5**,  the line that reads:
```powershell
PS C:\> $vhdsize = 127GB
```
Should actually read:
```powershell
PS C:\> $vhdsize = (127*[Math]::Pow(1024,3))
```
This counts our 127GB into 21474836480 Bytes as required in the correct format for the user in-place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4fcdbfc-802a-3308-b689-ce8ea3bde1c6
* Version Independent ID: 831f5800-5656-9b40-9f78-57c82234351d
* Content: [New-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/new-vhd?view=win10-ps#feedback)
* Content Source: [docset/windows/hyper-v/new-vhd.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/new-vhd.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@danijeljw Thank you for your feedback. We have made changes to the example and it can tracked via PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1245

Thanks
Sri

**Comment by e0i** [comment]
@danijeljw 

In our investigation it has been [concluded](https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1245#issuecomment-523101480) that no change to the document is necessary.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
