### ISSUE TITLE
Download Link for WDAC

### ISSUE THREAD

**Issue by karthiktippireddy9** [MicrosoftDocs/windows-powershell-docs#121]
Hello,

Can someone please help me getting the download link for WDAC module.

Thanks

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @karthiktippireddy9 
Thanks for getting in touch.
Is there any issue that you see in documentation? If not, @yogkumgit can redirect you to support to help you.

**Comment by yogkumgit** [comment]
@karthiktippireddy9 Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:
https://docs.microsoft.com/powershell/#pivot=main&panel=community

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
