### ISSUE TITLE
Error in NetConnectionResult

### ISSUE THREAD

**Issue by dennisl68-castra** [MicrosoftDocs/windows-powershell-docs#1210]
The text refers to three parameters but one of them isn’t possible to specify. 
The -ICMP parameter doesn’t exist (but it should really be implemented). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b964ddae-3304-7413-57be-19ae13a2af08
* Version Independent ID: 2a976f70-cc7b-cf2c-341b-ba1612744f13
* Content: [Test-NetConnection (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/test-netconnection?view=win10-ps#feedback)
* Content Source: [docset/windows/nettcpip/test-netconnection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nettcpip/test-netconnection.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@dennisl68-castra Thank you. I see that the document is not updated without the -ICMP parameter.

Hope this helps!

Thanks
Sri

**Comment by e0i** [comment]
Hello @dennisl68-castra  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
