### ISSUE TITLE
Wrong documenation

### ISSUE THREAD

**Issue by SergeGrd** [MicrosoftDocs/windows-powershell-docs#1212]
This article is speaking about Import-VM for Windows 10/Windows 2016 host, mentioning XML files.
Hyper-V doesn't use XML file for configurations in Windows 10 & Windows 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42fa5406-e41f-9941-9bc4-3c305f9135af
* Version Independent ID: 3274511d-d9d5-6397-f168-db8918a4bebb
* Content: [Import-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/import-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/import-vm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/import-vm.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@SergeGrd Thank you for your feedback. We have made changes to the document to reflect the correct formar (.vmcx)

Thanks
Sri

**Comment by e0i** [comment]
@SergeGrd 

It has been found that the issue has already been addressed with the following commit.

[[689ab24 ] Changed xml to newly vcmx format ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/689ab24dfce50ccf597be547cf5cf0ea421b7081#diff-1093261d95a05b88444b0a724d052d79)

We are thus marking this issue as resolved. Feel free to re-open it if you feel it hasn't been resolved.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
