### ISSUE TITLE
Clarification between Get-DnsClientNrptPolicy and Get-DnsClientNrptRule

### ISSUE THREAD

**Issue by frasercarter** [MicrosoftDocs/windows-powershell-docs#1213]
can we please have some clarification on to what the difference is between the Policy and Rule? I have assumed that the Rules are settings configured, while the Policy are rules currently applied?

Or are the rules configured via Intune / CSP while Policy is configured via Group policy.

I am unable to find any clear documentation on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9447ef4c-8b69-e9b5-ec7f-b12689ff69cc
* Version Independent ID: 2c523bc8-89a2-d986-a55a-0357a7bea37f
* Content: [Get-DnsClientNrptPolicy (dnsclient)](https://docs.microsoft.com/en-us/powershell/module/dnsclient/get-dnsclientnrptpolicy?view=win10-ps)
* Content Source: [docset/windows/dnsclient/get-dnsclientnrptpolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsclient/get-dnsclientnrptpolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by MaratMussabekov** [comment]
Hello @frasercarter ,
Rules are applied to the GPO or local computer.
Policy **shows** the configuration applied to the local computer (like the result of local NRPT rules and GPO NRPT rules applied)
More details are in [this article](https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn593632(v%3Dws.11)).
Thank you

**Comment by e0i** [comment]
Hello @frasercarter ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
