### ISSUE TITLE
Wouldn't it be lovely to remotely query a machine with get-mpcomputerstatus?

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/windows-powershell-docs#1214]
With a -computer parameter.  

Any chance of that ever happening? Or do we have to do a WMI query to get that info remotely?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@vboyev-MSFT 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by e0i** [comment]
@vboyev-MSFT 

Your feedback has been noted to be shared with the product team. Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
