### ISSUE TITLE
what does the @ mean in the output of show-dnsservercache

### ISSUE THREAD

**Issue by tlsalex** [MicrosoftDocs/windows-powershell-docs#1216]
I want to know what does the @ mean in the output of show-dnsservercache

In linux dns configuration file , the @ , usually means the domain name that the configuration file is created for.

But I feel confuse here in windows show-dnsservercache.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@tlsalex 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by e0i** [comment]
@tlsalex 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by msbemba** [comment]
@tlsalex  Thank you for your feedback. @ is the Hostname for the particular record type (it is NS record in the doc). Usually To create a Blank record admins use an @ in the Hostname field. This represents an empty prefix (so the name exactly matches the domain name. The @ hostname is also referred to as the the root of the domain.

Hope this helps!

Thanks
Sri

**Comment by e0i** [comment]
Hello @tlsalex  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
