### ISSUE TITLE
Formatting of -Mode options is hard to read

### ISSUE THREAD

**Issue by TBBle** [MicrosoftDocs/windows-powershell-docs#1217]
The various options for `-Mode` run together into a single paragraph. I suspect the `--` is actually supposed to be an unordered list marker.

Was this a missed conversion from another documentation format?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a37cff7-cc5c-0de2-e84e-a2c56cde57cc
* Version Independent ID: 6c80c1f4-8ea2-1a41-b4d8-a28f9e50cb97
* Content: [Optimize-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/optimize-vhd?view=win10-ps#)
* Content Source: [docset/windows/hyper-v/optimize-vhd.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/optimize-vhd.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
