### ISSUE TITLE
Example does not properly demonstrate command

### ISSUE THREAD

**Issue by Rich-Lang** [MicrosoftDocs/windows-powershell-docs#1223]
1) The sample has formatting issues.
2) If you run the commands in the sample, it will not produce the results shown.   Not clear if this is just outdated or sample expects some external configuration change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0d5ae0d-56da-7ea2-4628-00727dc340d8
* Version Independent ID: 1ded5d7f-1df5-48b8-abd7-4c78c90ad538
* Content: [Reset-IISServerManager (iisadministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/reset-iisservermanager?view=win10-ps#feedback)
* Content Source: [docset/windows/iisadministration/reset-iisservermanager.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/iisadministration/reset-iisservermanager.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
