### ISSUE TITLE
Example 2 is misleading

### ISSUE THREAD

**Issue by Rich-Lang** [MicrosoftDocs/windows-powershell-docs#1224]
The second example has a bizarre output.  The default output should be as follows.  

An error occurred on the server when processing the URL. Please contact the system administrator. &lt;p/&gt; If you are the system administrator please click &lt;a href="https://g
o.microsoft.com/fwlink/?LinkID=82731"&gt;here&lt;/a&gt; to find out more about this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51cdca0a-de14-9ef4-6488-404968dcb273
* Version Independent ID: 0a08acf0-78bb-1d77-7f60-91e2244e8296
* Content: [Get-IISConfigAttributeValue (iisadministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigattributevalue?view=win10-ps)
* Content Source: [docset/windows/iisadministration/get-iisconfigattributevalue.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/iisadministration/get-iisconfigattributevalue.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
