### ISSUE TITLE
It seems like this page links a wrong target?

### ISSUE THREAD

**Issue by yanxiaodi** [MicrosoftDocs/windows-powershell-docs#1226]
When I click `remove-appxpackage` link in the left menu, it shows `Move-AppxPackage`? Is it wrong?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f43873-0e34-6ec2-8bde-479945d49ed9
* Version Independent ID: 914c97a9-7dc2-6ddd-4756-7ec210db3fe8
* Content: [Move-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/remove-appxpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/remove-appxpackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by nnpcYvIVl** [comment]
I have the same problem.

**Comment by e0i** [comment]
@yanxiaodi 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by msbemba** [comment]
@yanxiaodi Thank you for your feedback. We have made changes to the doc and the same  can be tracked via PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1247

Thanks
Sri

**Comment by yanxiaodi** [comment]
Good job. Thanks a lot.
