### ISSUE TITLE
3rd example description

### ISSUE THREAD

**Issue by doah78** [MicrosoftDocs/windows-powershell-docs#1228]
Example 3 says it disables all users in an OU, I believe this should be Enables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab398405-7c47-e48a-358c-51d8190b3a57
* Version Independent ID: 35d65237-8fa9-4937-04d4-976018286c3b
* Content: [Enable-ADAccount (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/enable-adaccount?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/activedirectory/Enable-ADAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Enable-ADAccount.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
