### ISSUE TITLE
Linting rules

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/windows-powershell-docs#123]
Since the CONTRIBUTING guidelines suggest using VSCode for MarkDown editing, and the VSCode MarkDown page calls out the markdownlint extension, [markdownlint](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md), it seemed that adding linting rules, etc. would be a good idea.

Requirements would be:

1. Decide on desired rules [Rules](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md)
2. Add appropriately configured .markdownlint.json in root of project
3. Update contrib guidelines
4. Apply linting rules to existing markdown files.

**Comment by e0i** [comment]
@dsolodow  Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by dsolodow** [comment]
It's actually for either the CONTRIBUTING.md or in .vscode.
Just thinking that some linting rules for the markdown files under the docs might be a good way to help manage consistency.

**Comment by sdwheeler** [comment]
@e0i We have markdownlint rules in the PowerShell-Docs repo. I suggest using these.
See https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/.markdownlint.json
