### ISSUE TITLE
Get-ADTrust reporting of 'UsesAESKeys' is broken

### ISSUE THREAD

**Issue by canix1** [MicrosoftDocs/windows-powershell-docs#1235]
In Module (1.0.1.0) ActiveDirectory the command Get-ADTrust always reports 'UsesAESKeys' as false even though the property msDS-SupportedEncryptionTypes is set to ( AES128_CTS_HMAC_SHA1_96 | AES256_CTS_HMAC_SHA1_96 ) on the trusted domain object.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@canix1 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
