### ISSUE TITLE
 bypass the 24 snapshot limitation in set-vmreplication cmdlet  -RecoveryHistory.

### ISSUE THREAD

**Issue by watashi-Amine** [MicrosoftDocs/windows-powershell-docs#124]
@MicrosoftGuyJFlo  @MicrosoftHeidi 
hi,
i want to bypass the 24 snapshot limitation in set-vmreplication cmdlet  -RecoveryHistory.
how can i do that ?

think you.

**Comment by MicrosoftGuyJFlo** [comment]
The best place to ask for assistance is in the article for the PowerShell command below. I don't believe it can be bypassed but the author of the command reference should be better able to assist. I only write for Azure AD. 

https://docs.microsoft.com/powershell/module/hyper-v/set-vmreplication?view=win10-ps
