### ISSUE TITLE
Slight typo underneath "Outputs"

### ISSUE THREAD

**Issue by lrandall-gillsch** [MicrosoftDocs/windows-powershell-docs#1275]
Very slight typo in the sentence underneath "Outputs", it says "This complete does not generate any input.", should it be "This cmdlet does not generate any output."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95c56f6b-36ab-d05f-44a3-418d43be7c91
* Version Independent ID: 4fc21770-9fa1-9877-bcde-b9c7b6cf7dfd
* Content: [Invoke-GPUpdate (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/invoke-gpupdate?view=win10-ps#feedback)
* Content Source: [https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2fgrouppolicy%2finvoke-gpupdate.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2fgrouppolicy%2finvoke-gpupdate.md&version=GBlive&_a=contents)
* Product: **w10**
* Technology: **powershell-windows**
* Git Login: **andreabarr**
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@lrandall-gillsch Thank you for the feedback. We have made these changes on the doc via PR # https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1577

Thanks
Sri

**Comment by e0i** [comment]
@lrandall-gillsch 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
