### ISSUE TITLE
"The Domain Name System (DNS) directory" is not specified

### ISSUE THREAD

**Issue by wmassingham** [MicrosoftDocs/windows-powershell-docs#1278]
This doc says the file is exported to the DNS directory, but does not say where that is. It appears to be C:\Windows\System32\dns, at least on my system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b473c75d-eba0-92b2-3bab-8cfc6e19c440
* Version Independent ID: ecee7d9f-783a-53d0-53aa-ee5f63f4fcad
* Content: [Export-DnsServerZone (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/export-dnsserverzone?view=win10-ps#feedback)
* Content Source: [https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2fdnsserver%2fexport-dnsserverzone.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2fdnsserver%2fexport-dnsserverzone.md&version=GBlive&_a=contents)
* Product: **w10**
* Technology: **powershell-windows**
* Git Login: **andreabarr**
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@wmassingham Thank you for your feedback. The location for DNS directory is C:\Windows\System32\dns. I have that information via PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1578

Thanks
Sri

**Comment by e0i** [comment]
Closing via #1578
