### ISSUE TITLE
remove-appxpackage

### ISSUE THREAD

**Issue by ehegazy** [MicrosoftDocs/windows-powershell-docs#1279]
remove-appxpackage show alawys . Move-AppxPackage wrong article 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc0b0cd3-1201-f5e2-907e-5712eda675da
* Version Independent ID: b722fa48-0af3-27ea-9f86-4f48b9972d19
* Content: [Move-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps#feedback)
* Content Source: [https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2fappx%2fremove-appxpackage.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2fappx%2fremove-appxpackage.md&version=GBlive&_a=contents)
* Product: **w10**
* Technology: **powershell-windows**
* Git Login: **andreabarr**
* Microsoft Alias: **v-anbarr**

**Comment by cconrado** [comment]
Yes its the wrong commands

**Comment by e0i** [comment]
@eheg

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.

**Comment by cconrado** [comment]
@e0i yes exactly the pages were linked incorrectly. now they aren't

**Comment by RAJU2529** [comment]
today I will check
