### ISSUE TITLE
Command fails : Get-Help about_ActiveDirectory_ObjectModel 

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/windows-powershell-docs#1281]
The command in this line in the document does not work, or needs additonal modules predefined, not sure, please update document: 

Your sentence: For a list of supported types for &lt;value&gt;, type Get-Help about_ActiveDirectory_ObjectModel

The command results in  Get-Help could not find about_ActiveDirectory_ObjectModel in a help file in this session.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c80552-2be1-2869-5ea8-2368bb3dd2c8
* Version Independent ID: 8d825bb9-93d8-16ca-22f0-a8191d642a50
* Content: [Get-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-aduser?view=win10-ps)
* Content Source: [https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2faddsadministration%2fget-aduser.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2faddsadministration%2fget-aduser.md&version=GBlive&_a=contents)
* Product: **w10**
* Technology: **powershell-windows**
* Git Login: **andreabarr**
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
This is a known issue with the updatable help pipeline that affects the `Get-Help` and `Update-Help` commands.

There are ongoing efforts to rework the publishing engine. Once matured, failures to update modules are also going to be addressed. Internal sources inform us, the independent collaborators that it is going to take a lot of work.

There have been multiple reports of the help commands not working so please refer to issue #2247 for tracking the progress of this situation.

Thank you.
