### ISSUE TITLE
Example 1 Typo

### ISSUE THREAD

**Issue by arielmoisis** [MicrosoftDocs/windows-powershell-docs#1282]
New-NetEventSession -SessionName "Session01"
should read New-NetEventSession -Name "Session01"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85e4b0e-eebc-3a46-3fbd-bb8f3623594a
* Version Independent ID: c002c70e-70c1-1f64-713f-e897cce205a3
* Content: [Add-NetEventPacketCaptureProvider (neteventpacketcapture)](https://docs.microsoft.com/en-us/powershell/module/neteventpacketcapture/add-neteventpacketcaptureprovider?view=winserver2012r2-ps#feedback)
* Content Source: [https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwinserver2012r2-ps%2fneteventpacketcapture%2fAdd-NetEventPacketCaptureProvider.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwinserver2012r2-ps%2fneteventpacketcapture%2fAdd-NetEventPacketCaptureProvider.md&version=GBlive&_a=contents)
* Product: **powershell**
* Technology: **powershell**
* Git Login: **andreabarr**
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@arielmoisis Thank you for your feedback. We have made the changes to the example via PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1310

**Comment by e0i** [comment]
@arielmoisis 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
