### ISSUE TITLE
Page needs more details

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#1289]
This page describes the Set-SMBServerConfiguration command, including all the parameters you use to turn on/off SMB server properties. But the action of some of these properties is not explained. For example, what is a server announcement? What does validate target name do in practice, for example? 

This page is fine if you know what you are doing, configuration wise, but more detail would be useful.
Also rather than putting the details here, how about a more detailed page on these settings (and refer to that page here)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf1abaf-c268-b76f-48b5-5f5723fecb83
* Version Independent ID: 0c17d9d3-bbc4-f467-b44c-d78bb0c7e370
* Content: [Set-SmbServerConfiguration (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=win10-ps#feedback)
* Content Source: [https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2fsmbshare%2fset-smbserverconfiguration.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwindows%2fsmbshare%2fset-smbserverconfiguration.md&version=GBlive&_a=contents)
* Product: **w10**
* Technology: **powershell-windows**
* Git Login: **andreabarr**
* Microsoft Alias: **v-anbarr**

**Comment by pietilag** [comment]
Needs info on which OS's this runs on.

**Comment by e0i** [comment]
Closing via #1674

**Comment by doctordns** [comment]
So where do I go for details on what a server announcement is and what it looks like? 
And what does validate target name do in practice?
The extra examples were quite what I had in mind.

**Comment by velkovb** [comment]
@doctordns Hi Thomas,

I completely agree with you that one should be able to find more information from this page. You cannot learn everything for a server functionality form the PowerShell help.

> This page is fine if you know what you are doing, configuration wise, but more detail would be useful.

I think that one should actually understand what he is doing before coming here :)

I believe that the following two articles can be included in the cmdlet description according to the version:
[Overview of file sharing using the SMB 3 protocol in Windows Server](https://docs.microsoft.com/windows-server/storage/file-server/file-server-smb-overview)
[Server Message Block Overview](https://docs.microsoft.co/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831795(v=ws.11))

Also if one wants to go into more details, here is the protocol specification: [[MS-SMB2]: Server Message Block (SMB) Protocol Versions 2 and 3](https://docs.microsoft.com/openspecs/windows_protocols/ms-smb2/5606ad47-5ee0-437a-817e-70c366052962)

I will start working on adding this info in the articles.
