### ISSUE TITLE
Misspelling in Disable-NetAdapterPowerManagement Example

### ISSUE THREAD

**Issue by buenyamin-olgun** [MicrosoftDocs/windows-powershell-docs#129]
https://github.com/MicrosoftDocs/windows-powershell-docs/tree-save/master/docset/windows/netadapter/disable-netadapterpowermanagement.md

Original:
### Example 2: Disable power management on a specified network adapter using InputObject
```
PS C:\> $NetAdapter1 = Get-NetAdapter -Name "Ethernet 3"
PS C:\> Disable-NetAdapterPowerMangement -InputObject $NetAdapter1
```

Expected:
### Example 2: Disable power management on a specified network adapter using InputObject
```
PS C:\> $NetAdapter1 = Get-NetAdapter -Name "Ethernet 3"
PS C:\> Disable-NetAdapterPowerManagement -InputObject $NetAdapter1
```

**Comment by brianlic-msft** [comment]
@buenyamin-olgun Thank you for catching this! I've updated the topic accordingly.
