### ISSUE TITLE
Unable to edit this page

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#1290]
I can leave a comment on this page but I am unable to edit it.

There is a typo I was going to try to fix, but I'm locked out of editing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85e4b0e-eebc-3a46-3fbd-bb8f3623594a
* Version Independent ID: c002c70e-70c1-1f64-713f-e897cce205a3
* Content: [Add-NetEventPacketCaptureProvider (neteventpacketcapture)](https://docs.microsoft.com/en-us/powershell/module/neteventpacketcapture/add-neteventpacketcaptureprovider?view=winserver2012r2-ps#feedback)
* Content Source: [https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwinserver2012r2-ps%2fneteventpacketcapture%2fAdd-NetEventPacketCaptureProvider.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/powershell?path=%2fdocset%2fwinserver2012r2-ps%2fneteventpacketcapture%2fAdd-NetEventPacketCaptureProvider.md&version=GBlive&_a=contents)
* Product: **powershell**
* Technology: **powershell**
* Git Login: **andreabarr**
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @doctordns 

Find below the link to the document source. Feel free to create a PR fixing that typo and we would be more than glad rolling it into review.

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/neteventpacketcapture/Add-NetEventPacketCaptureProvider.md

Thank you for taking the initiative to improve documentation.
