### ISSUE TITLE
Wrong examples

### ISSUE THREAD

**Issue by nezaras2000** [MicrosoftDocs/windows-powershell-docs#1304]
The examples in this page doesn't work, and there is no parameter CLUSTER for this cmdlet.
It should be Get-ClusterStorageSpacesDirect -Node "Node01.mydomain.local"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a07e3d56-dd77-0d40-0225-09713067dfb4
* Version Independent ID: 457364b0-9bc3-5fae-4f2e-601d588652d1
* Content: [Get-ClusterStorageSpacesDirect (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/get-clusterstoragespacesdirect?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/get-clusterstoragespacesdirect.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/failoverclusters/get-clusterstoragespacesdirect.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@nezaras2000 Thank you for your feedback. We have made the changes in the doc via PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1579

Thanks
Sri

**Comment by e0i** [comment]
@nezaras2000 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
