### ISSUE TITLE
Missing -MultiPolicyFormat parameter on New-CIPolicy

### ISSUE THREAD

**Issue by miketheitguy** [MicrosoftDocs/windows-powershell-docs#1306]
1903 Adds additional parameters to New-CIPolicy. Likewise, supporting documentation around the usage of this parameter and the changes to Code Integrity are missing on other document pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5e8ac6-f123-7aeb-147d-0fbf44a0691c
* Version Independent ID: ddd7f02d-549f-52dd-4b15-04b7ef3a521e
* Content: [New-CIPolicy (configci)](https://docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=win10-ps#feedback)
* Content Source: [docset/windows/configci/new-cipolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/configci/new-cipolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @miketheitguy 

Although the version 1903 is not yet supported within the documentation, such coverage has been planned to be delivered.

Thank you for the feedback.
