### ISSUE TITLE
-Filter parameter missing from "Parameters" section

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/windows-powershell-docs#1313]
I'm trying to see what I can do with the -Filter parameter; from memory, I can't use Regex, but wanted to confirm it here.  The only info about filter syntax is to run "Get-Help about_ActiveDirectory_Filter", which just gives me a list of ActiveDirectory cmdlets, presumably that use the filter syntax?  Either way, it doesn't tell me much about how to use the -Filter parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8337d2-8c17-df81-3184-128e17d9d163
* Version Independent ID: fa6e2a23-2a2d-16f7-079b-e2f5bdd8d938
* Content: [Get-ADComputer (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adcomputer?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/get-adcomputer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsadministration/get-adcomputer.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@JakeMoe Thank you for your feedback.

I can see the -Filter parameter section in the article. You can see it here in github as well:
[Get-ADComputer F-ilter](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsadministration/Get-ADComputer.md#-filter)

Here is a version of the article [about_ActiveDirectory_Filter](https://docs.microsoft.com/previous-versions/windows/server/hh531527(v=ws.10))

**Comment by JakeMoe** [comment]
Hi @velkovb ,

For the -Filter paramter, yes, I can see info there now, but the history of that page cuts off a month after my comment, so I can't tell you what I saw then.

The only other comment I'd say is that it'd probably be worth linking that "Get-Help about_ActiveDirectory_Filter" to the link you shared.  Otherwise, I'm ok if you close this now.

Cheers,

Jake Moe

**Comment by velkovb** [comment]
@JakeMoe Hi Jake,

That is a good idea I will include it in the article. Otherwise, it seems like the file is not present in the help files of recent versions of Windows but I found examples where people were able to find it in Server 2012.
