### ISSUE TITLE
Apparently bug in Applications collections

### ISSUE THREAD

**Issue by Pingulea** [MicrosoftDocs/windows-powershell-docs#1314]
I'm trying to list the sub-applications of a site selected with Get-IISSite.
My site has 3 sub-applications.
Yet $selectedSite.Applications.Count reports only 1 app - the root application of the site.
I've also tried $appsConfigCollection = Get-IISConfigCollection -ConfigElement $siteConfigElement.
It seems that only the root application of a site is captured :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e672185-5966-7077-2fa7-1357e1f4f538
* Version Independent ID: 1b1fe37f-0a53-f8dd-a516-68883e52f226
* Content: [Get-IISSite (iisadministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/Get-IISSite?view=win10-ps#feedback)
* Content Source: [docset/windows/iisadministration/get-iissite.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/iisadministration/get-iissite.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sowjanya365** [comment]
Hi @Pingulea 

Thank you for contacting us! 

This feedback system is for documentation corrections or improvements. 

This article shows the information about how we can get the IIS web sites, their current status and other key information. The issue you are trying to explain is out of the scope of this document. 

Please let us know if you have any questions. Thank you!

**Comment by e0i** [comment]
Hello @Pingulea,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
