### ISSUE TITLE
PKIClient folder/path/module should be PKI

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/windows-powershell-docs#133]
The module that ships within Windows 10 is not called `PKIClient`, it's called `PKI`:

```
C:\Users\Joey> Get-Command -Module PKI

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-CertificateEnrollmentPolicyServer              1.0.0.0    PKI
Cmdlet          Export-Certificate                                 1.0.0.0    PKI
Cmdlet          Export-PfxCertificate                              1.0.0.0    PKI
Cmdlet          Get-Certificate                                    1.0.0.0    PKI
Cmdlet          Get-CertificateAutoEnrollmentPolicy                1.0.0.0    PKI
Cmdlet          Get-CertificateEnrollmentPolicyServer              1.0.0.0    PKI
Cmdlet          Get-CertificateNotificationTask                    1.0.0.0    PKI
Cmdlet          Get-PfxData                                        1.0.0.0    PKI
Cmdlet          Import-Certificate                                 1.0.0.0    PKI
Cmdlet          Import-PfxCertificate                              1.0.0.0    PKI
Cmdlet          New-CertificateNotificationTask                    1.0.0.0    PKI
Cmdlet          New-SelfSignedCertificate                          1.0.0.0    PKI
Cmdlet          Remove-CertificateEnrollmentPolicyServer           1.0.0.0    PKI
Cmdlet          Remove-CertificateNotificationTask                 1.0.0.0    PKI
Cmdlet          Set-CertificateAutoEnrollmentPolicy                1.0.0.0    PKI
Cmdlet          Switch-Certificate                                 1.0.0.0    PKI
Cmdlet          Test-Certificate                                   1.0.0.0    PKI
```

This is breaking `Get-Help -Online` for PKI cmdlets:

```powershell
C:\Users\Joey> Get-Help -Online Get-Certificate -Verbose
VERBOSE: Help URI: http://go.microsoft.com/fwlink/p/?linkid=287528
```

This fwlink redirects to https://docs.microsoft.com/en-us/powershell/module/pki/get-certificate?view=winserver2012r2-ps while the help is actually located at https://docs.microsoft.com/en-us/powershell/module/pkiclient/get-certificate?view=winserver2012r2-ps

While we *could* change the fwlinks to point `pkiclient` instead of `pki` in the URL, this breaks the pattern of all other modules where the name of the module matches the path.

Furthermore, the module landing page at https://docs.microsoft.com/en-us/powershell/module/pkiclient/?view=winserver2012r2-ps reflects the name of the module as if it was called `PKIClient`.

**Comment by kevsully** [comment]
Quick comment on this. And thanks Joey for articulating this so well. From an end-user perspective, if they were to need to access online help content their typical thinking is;

> PS c:> Help get-certificate -online

They do not care about the name of the module. So if there was a name change on the module PKICLIENT vs. PKI, I'm not sure it matters. the landing content should be as current as possible and the name changes should be 'noted' in those docs. ("The PKI module was named PKICLIENT in a previous life" or whatever the reason for the discrepancy).

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by e0i** [comment]
@officedocsbot unassign @e0i

**Comment by kenwith** [comment]
Related: https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1623

**Comment by e0i** [comment]
Closing as the related PR #1623 has been merged.
