### ISSUE TITLE
iscsi-virtualdisk - defaults to dynamic vhdx?

### ISSUE THREAD

**Issue by martinbherbener** [MicrosoftDocs/windows-powershell-docs#135]
Hi,

https://docs.microsoft.com/en-us/powershell/module/iscsitarget/new-iscsivirtualdisk (New-IscsiVirtualDisk) examples 1 and 3 state that the example commands as written create fixed virtual disks, but the existence and description of the `-UseFixed` parameter strongly suggest that the default is a dynamic disk, and an experiment seems to verify this.  Are the examples just missing the parameter, or is there something more complicated going on?

thanks

Martin

**Comment by e0i** [comment]
@martinbherbener  Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by martinbherbener** [comment]
Hi,

There is a link in the original comment.  However, it appears that the documentation has been updated since I left the comment, and my comment/concern is no longer applicable, so I'll close.

thanks

Martin
