### ISSUE TITLE
Update-Help fails for PrintManagement module

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/windows-powershell-docs#137]
_From @dsolodow on February 9, 2018 15:43_

update-help : Failed to update Help for the module(s) 'PrintManagement' with UI culture(s) {en-US} : Unable to connect
to Help content. The server on which Help content is stored might not be available. Verify that the server is
available, or wait until the server is back online, and then try the command again.
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateHelpCommand

_Copied from original issue: PowerShell/PowerShell-Docs#2115_

**Comment by e0i** [comment]
@officedocsbot close
