### ISSUE TITLE
Documentation for Add-Appxpackage is incomplete ({{Fill ...}})

### ISSUE THREAD

**Issue by TPXP** [MicrosoftDocs/windows-powershell-docs#1398]
Hello,

While reading docs for [Add-AppxPackage](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/add-appxpackage.md), I noticed some switches are not documented properly, like [ForceUpdateFromAnyVersion](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/add-appxpackage.md#-forceupdatefromanyversion) and the ones below. Instead of the description, it only shows `{{Fill <field> description}}`.

Could you please update this file with what's supposed to be instead of the `{{Fill}}` tag ?

Many thanks in advance,

**Comment by e0i** [comment]
Hello, @TPXP An update has been planned and queued to be delivered for this known problem. A PR will be referenced to this issue soon. Thank you for providing feedback.

**Comment by msbemba** [comment]
@TPXP Thank you for your feedback. We have added missing descriptions to the document via PR # https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1639

Thanks
Sri

**Comment by TPXP** [comment]
Awesome, looks great. Feel free to close this issue then. :-)
