### ISSUE TITLE
Online documentation for Set-ProcessMitigation has commands that don't run correctly

### ISSUE THREAD

**Issue by SCLD-FJaramillo** [MicrosoftDocs/windows-powershell-docs#1429]
Online documentation for Set-ProcessMitigation has the following command:

`Set-Processmitigation -Name test.exe -Remove -Disable DEP`

Running the command 

`Set-Processmitigation -Name iexplore.exe -Disable DEP`

on a fresh Windows 10 1903 install and then running

`Set-Processmitigation -Name -Remove iexplore.exe -Disable DEP`

gives the following error:

`WARNING: Error while setting DEP: C000000D`

The same is true for other applications, system level settings, other mitigation types, and the '-Reset' cmdlet as well.

**Comment by SCLDGit** [comment]
@e0i - Jumping on to ask, is there a better place to discuss bugs within the Get-ProcessMitigation and Set-ProcessMitigation modules than this repo? We've found quite a few, and it would be nice to be able to get some answers without having to pay $500 every time we've found something wrong.

**Comment by e0i** [comment]
Hello, @SCLDGit 

Yes, 

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by MaratMussabekov** [comment]
Hello @SCLD-FJaramillo ,
ufortunately, I wasn't able to reproduce your issue (for me , command **Set-Processmitigation -Name  iexplore.exe -Disable DEP -Remove** worked correctly in 1903).
1. could you please check whether you are running the command as a user that has sufficient permissions?
2. could you please provide output of **Get-Processmitigation -Name  iexplore.exe** command?

Thank you

**Comment by SCLD-FJaramillo** [comment]
I just tried the cmdlet that you suggested, I'm attaching the results:

![after](https://user-images.githubusercontent.com/54039217/68130577-93156a00-fee9-11e9-96d8-15ac2b6e6b96.png)
![Before](https://user-images.githubusercontent.com/54039217/68130578-93156a00-fee9-11e9-9177-5324ccefc15a.png)
![WindowsVersion](https://user-images.githubusercontent.com/54039217/68130579-93156a00-fee9-11e9-8e26-2fc239da8c63.png)

I'm running powershell as Administrator in a windows 10 1903 version

Thanks.

**Comment by MaratMussabekov** [comment]
Hello @SCLD-FJaramillo ,
Please try the following (it was workaround for error C000000D in Windows 10 1809, hope it will work for 1903 as well): Delete file **C:\Windows\Microsoft.NET\assembly\GAC_64\Microsoft.ProcessMitigations.Commands\v4.0_10.0.0.0__31bf3856ad364e35\Microsoft.ProcessMitigations.Commands.dll** and then restart the PC. Then try to run command again.
If it doesn't work, I would recommend to raise a ticket in [Microsoft Support Portal](https://support.microsoft.com).
Thank you

**Comment by SCLD-FJaramillo** [comment]
Hi,

I don’t have the file Microsoft.ProcessMitigations.Commands.dll in the suggested location, I checked in the two Windows 10 1903 computers that I’m testing on

Thanks.

**Comment by MaratMussabekov** [comment]
Dear @SCLD-FJaramillo ,
please also check folders C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.ProcessMitigations.Commands.resources\v4.0_10.0.0.0_en_31bf3856ad364e35\ and C:\Windows\Microsoft.NET\assembly\GAC_32\Microsoft.ProcessMitigations.Commands\v4.0_10.0.0.0__31bf3856ad364e35\

Thank you

**Comment by SCLD-FJaramillo** [comment]
Hi,

I don’t have the “Microsoft.ProcessMitigations.Commands.resources” folder in the first path, and I don’t have the “Microsoft.ProcessMitigations.Commands” on the second path.

Thanks.

**Comment by MaratMussabekov** [comment]
Hi @SCLD-FJaramillo,
Did you try to create a support request?
Thank you

**Comment by SCLD-FJaramillo** [comment]
We did open a support ticket around four weeks ago(Support Request #   119100724006908).
Kenneth Dawkins has been working with us.

Thanks

**Comment by e0i** [comment]
@SCLD-FJaramillo 

The problematic behavior of mentioned commands could not be reproduced and it is better to consult appropriate support channels for this issue, as the issues section of this repository is intended for documentation and content issues only.

Thank you.

**Comment by Xorlent** [comment]
Remove the -Remove switch from the command, since it's not a system-level setting you're controlling.  Like so:
`Set-Processmitigation -Name iexplore.exe -Disable DEP`
