### ISSUE TITLE
Who Wrote This Article

### ISSUE THREAD

**Issue by chenrylee** [MicrosoftDocs/windows-powershell-docs#144]
Too many errors, and mess layout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 605d2db1-fc1c-b4c0-f4d9-cc832b762328
* Version Independent ID: 472459c9-2351-ba16-89df-23431c6a1984
* Content: [Set-ADForest (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/set-adforest?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/activedirectory/Set-ADForest.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Set-ADForest.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by rodmhgl** [comment]
@chenrylee - Can you please be more specific or work toward implementing the fixes?

**Comment by chenrylee** [comment]
@rodmhgl I fixed some errors I found on github after that comment.

**Comment by e0i** [comment]
@chenrylee Could you clarify your complaints regarding this document? We would like to follow up and update the document as necessary.



> @rodmhgl I fixed some errors I found on github after that comment.

@chenrylee We couldn't find any pull requests or commits regarding this issue. If you have made changes to your local repository, consider pushing it to GitHub and opening a PR, as we'll review and merge your changes.

Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
