### ISSUE TITLE
Missing DFL

### ISSUE THREAD

**Issue by nedpyle** [MicrosoftDocs/windows-powershell-docs#145]
The WS2016 domain mode is missing. It is value 7. 

There is no new WS2019 domain mode, for when this doc expands to include later OS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f00f6550-a7fb-5720-381a-4c5e579fe2d8
* Version Independent ID: 20683780-ef3b-d0e4-20dc-6e2932d7c130
* Content: [Set-ADDomainMode (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-addomainmode?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/set-addomainmode.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-addomainmode.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith  please merge this PR, if you find it suitable.

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @nedpyle 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
