### ISSUE TITLE
MIssing WS2016 FFL

### ISSUE THREAD

**Issue by nedpyle** [MicrosoftDocs/windows-powershell-docs#146]
The forest mode is missing WS2016 (value 7).

The new WS2019 does not have a new DFL, when you get to that doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ffd495-8dfe-a45e-7220-2a6dde4128e3
* Version Independent ID: d3d743a1-5ba3-d1a4-e389-4c0037d54db3
* Content: [Set-ADForestMode (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-adforestmode?view=win10-ps)
* Content Source: [docset/windows/addsadministration/set-adforestmode.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-adforestmode.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith please merge this PR, if you find it suitable.

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @nedpyle 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
