### ISSUE TITLE
Unclear `-Confirm` behavior

### ISSUE THREAD

**Issue by tydaeus** [MicrosoftDocs/windows-powershell-docs#1463]
The documentation for `-Confirm` indicates that the default value is False, but the examples and observed behavior would seem to indicate that the default value for `-Confirm` is True.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c4d0f8-540a-7860-e927-88cc2897d5c0
* Version Independent ID: 8b436f4a-a516-21e3-e92c-731b5a4d3cae
* Content: [Unregister-ScheduledTask (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/unregister-scheduledtask?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/Unregister-ScheduledTask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/scheduledtasks/Unregister-ScheduledTask.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sdwheeler** [comment]
@tydaeus Be definition, the default value for SwithParameter type parameters is `False`. It become true when you use it. That means if you do not use `-Confirm` then its value is false an you do not get prompted for confirmation. But when you use `-Confirm` it become true so you get prompted.

**Comment by velkovb** [comment]
Hello @tydaeus 

Hello @lrandall-gillsch 

Thank you for trying to make MicrosoftDocs a better place.

By default switch parameters are always false. unless explicitly specified - [Switch Parameters](https://docs.microsoft.com/powershell/developer/cmdlet/types-of-cmdlet-parameters#switch-parameters). Here you are not prompted because of the -Confirm parameter but because the impact of the cmdlet is High. You could read more about cmdlet confirm impact and preference - [$ConfirmPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables#$ConfirmPreference), [ConfirmImpact](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute#confirmimpact)

Let me know if you have any questions.

**Comment by tydaeus** [comment]
@velkovb, in that case, I'd recommend mentioning the high impact status in the MicrosoftDocs page and/or the `Get-Help` file, and hopefully summarizing or linking through to https://docs.microsoft.com/en-us/powershell/developer/cmdlet/users-requesting-confirmation, which appears to have the most concise description of this behavior.

Documentation and `Get-Help` for `Unregister-ScheduledTask` `-Confirm` both only mention the request confirmation behavior and neglect the high impact status, so as someone attempting to quickly read through the documentation to put a script together, I would not expect the behavior to be governed differently.

**Comment by velkovb** [comment]
@tydaeus Thanks, that link really combines the info better. Unfortunately, the impact is not present in the help files, I guess that could be a general recommendation to Microsoft. The description of the `-Confirm` is the same everywhere so it could be included there. 

Meanwhile if you would like to get the impact level of a cmdlet you could do it with `Get-Command`
```
(Get-Command Remove-Item).ImplementingType.GetCustomAttributes($true)


NounName                : Item
VerbName                : Remove
DefaultParameterSetName : Path
SupportsShouldProcess   : True
SupportsPaging          : False
SupportsTransactions    : True
ConfirmImpact           : Medium
HelpUri                 : https://go.microsoft.com/fwlink/?LinkID=113373
RemotingCapability      : PowerShell
TypeId                  : System.Management.Automation.CmdletAttribute

Value          : Command = {commandInfo}
Name           :
Type           :
Target         :
TargetTypeName :
TypeId         : System.Diagnostics.DebuggerDisplayAttribute
```
For functions (like `Unregister-ScheduleTask`) you will see directly the code with `Get-Command`
```
(Get-Command Unregister-ScheduledTask).ScriptBlock.Attributes


PositionalBinding       : False
DefaultParameterSetName : ByPath
SupportsShouldProcess   : True
SupportsPaging          : False
SupportsTransactions    : False
ConfirmImpact           : High
HelpUri                 :
RemotingCapability      : PowerShell
TypeId                  : System.Management.Automation.CmdletBindingAttribute

Type             : {Microsoft.Management.Infrastructure.CimInstance}
ProviderCmdlet   :
ParameterSetName : {__AllParameterSets}
TypeId           : System.Management.Automation.OutputTypeAttribute

Type             : {Microsoft.Management.Infrastructure.CimInstance#Root/Microsoft/Windows/TaskScheduler/MSFT_Scheduled
                   Task}
ProviderCmdlet   :
ParameterSetName : {__AllParameterSets}
TypeId           : System.Management.Automation.OutputTypeAttribute
```

**Comment by e0i** [comment]
Hello @tydaeus,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
