### ISSUE TITLE
Please update site to include all available parameters for New-OBRetentionPolicy

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/windows-powershell-docs#1490]
Please update the documentation for **New-OBRetentionPolicy**. As of now Version 2.0.0.0 of the module MSOnlineBackup has more parameters for this Cmdlet.
```powershell
New-OBRetentionPolicy [[-RetentionDays] <long>] [[-RetentionWeeklyPolicy]] [[-WeekDaysOfWeek] {Sunday | Monday |
    Tuesday | Wednesday | Thursday | Friday | Saturday}] [[-WeekTimesOfDay] <List[timespan]>] [[-RetentionWeeks]
    <long>] [[-RetentionMonthlyPolicy]]  [<CommonParameters>]
```
Anyway the usage of these parameters isn't quite clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4bcdbe7-9625-475a-7b53-6d1a58f58885
* Version Independent ID: ccc019ea-f72a-1ae7-884b-c7be802342e8
* Content: [New-OBRetentionPolicy (msonlinebackup)](https://docs.microsoft.com/en-us/powershell/module/msonlinebackup/new-obretentionpolicy?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/msonlinebackup/New-OBRetentionPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/msonlinebackup/New-OBRetentionPolicy.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@diecknet 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by DoctorQuandary** [comment]
Can we re-open this? It appears the documentation for this command has gone missing again.

**Comment by binoyjt** [comment]
@e0i Not sure why this was closed. Its still not resolved as the parameters are not defined. It also does not detail out which of these parameters as mandatory depending on the policy setting. Can we please re-open this?
