### ISSUE TITLE
Wrong brackets

### ISSUE THREAD

**Issue by zjorz** [MicrosoftDocs/windows-powershell-docs#151]
Hi,

In the EXAMPLE1 the following brackets are used:
Set-AdfsAttributeStore -TargetName "ContosoAttributeStore01" -Configuration @("runmode" = "verbose"; configParaName2 = configParaValueNew)

The following brackets should be used instead:
Set-AdfsAttributeStore -TargetName "ContosoAttributeStore01" -Configuration @{"runmode" = "verbose"; configParaName2 = configParaValueNew}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16cb3105-3187-d18a-6c81-8fac8ee47bb4
* Version Independent ID: 63f9d5da-bca6-1002-4756-b538418c11b8
* Content: [Set-AdfsAttributeStore (adfs)](https://docs.microsoft.com/en-us/powershell/module/adfs/set-adfsattributestore?view=win10-ps)
* Content Source: [docset/windows/adfs/set-adfsattributestore.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/set-adfsattributestore.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Malind19** [comment]
Created pull request.
 https://github.com/MicrosoftDocs/windows-powershell-docs/pull/866

**Comment by e0i** [comment]
@officedocsbot close
