### ISSUE TITLE
CongestionProvider section outdated?

### ISSUE THREAD

**Issue by martin-ellis** [MicrosoftDocs/windows-powershell-docs#1519]
In the section on CongestionProvider, the page states that the default would be NewReno for clients and DCTCP for servers. However, on a recent Windows 10 client machine, it seems that CUBIC TCP (RFC 8312) is default, and has been since Fall Creators Update:
https://datatracker.ietf.org/meeting/100/materials/slides-100-tcpm-updates-on-windows-tcp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cad82b8-0378-9d52-6c8e-60968df4bb20
* Version Independent ID: d0c54e85-bca5-e13e-7297-0ee5002093f6
* Content: [Get-NetTCPSetting (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/get-nettcpsetting?view=win10-ps)
* Content Source: [docset/windows/nettcpip/Get-NetTCPSetting.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/nettcpip/Get-NetTCPSetting.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@martin-ellis 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
