### ISSUE TITLE
Get-Help about_ActiveDirectory_ObjectModel is not useful advice

### ISSUE THREAD

**Issue by ticktickMOF** [MicrosoftDocs/windows-powershell-docs#1522]
the output is
PS C:\depot\aws_prep1\buildsystem\atlasprda&gt; Get-Help about_ActiveDirectory_ObjectModel

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
Get-ADAuthenticationPolicy        Cmdlet    ActiveDirectory           Gets one or more Active Directory Domain Services authentication policies.
Get-ADAuthenticationPolicySilo    Cmdlet    ActiveDirectory           Gets one or more Active Directory Domain Services authentication policy silos.
Get-ADCentralAccessPolicy         Cmdlet    ActiveDirectory           Retrieves central access policies from Active Directory.
Get-ADCentralAccessRule           Cmdlet    ActiveDirectory           Retrieves central access rules from Active Directory.
Get-ADClaimTransformPolicy        Cmdlet    ActiveDirectory           Returns one or more Active Directory claim transform objects based on a specified filter.
Get-ADClaimType                   Cmdlet    ActiveDirectory           Returns a claim type from Active Directory.
Get-ADComputer                    Cmdlet    ActiveDirectory           Gets one or more Active Directory computers.
Get-ADDomainController            Cmdlet    ActiveDirectory           Gets one or more Active Directory domain controllers based on discoverable services criteria, search parameters or by providing a domain controller...
Get-ADFineGrainedPasswordPolicy   Cmdlet    ActiveDirectory           Gets one or more Active Directory fine grained password policies.
Get-ADGroup                       Cmdlet    ActiveDirectory           Gets one or more Active Directory groups.
Get-ADObject                      Cmdlet    ActiveDirectory           Gets one or more Active Directory objects.
Get-ADOptionalFeature             Cmdlet    ActiveDirectory           Gets one or more Active Directory optional features.
Get-ADOrganizationalUnit          Cmdlet    ActiveDirectory           Gets one or more Active Directory organizational units.
Get-ADReplicationConnection       Cmdlet    ActiveDirectory           Returns a specific Active Directory replication connection or a set of AD replication connection objects based on a specified filter.
Get-ADReplicationSite             Cmdlet    ActiveDirectory           Returns a specific Active Directory replication site or a set of replication site objects based on a specified filter.
Get-ADReplicationSiteLink         Cmdlet    ActiveDirectory           Returns a specific Active Directory site link or a set of site links based on a specified filter.
Get-ADReplicationSiteLinkBridge   Cmdlet    ActiveDirectory           Returns a specific Active Directory site link bridge or a set of site link bridge objects based on a specified filter.
Get-ADReplicationSubnet           Cmdlet    ActiveDirectory           Returns a specific Active Directory subnet or a set of AD subnets based on a specified filter.
Get-ADResourceProperty            Cmdlet    ActiveDirectory           Gets one or more resource properties.
Get-ADResourcePropertyList        Cmdlet    ActiveDirectory           Retrieves resource property lists from Active Directory.
Get-ADResourcePropertyValueType   Cmdlet    ActiveDirectory           Retrieves a resource property value type from Active Directory.
Get-ADServiceAccount              Cmdlet    ActiveDirectory           Gets one or more Active Directory managed service accounts or group managed service accounts.
Get-ADTrust                       Cmdlet    ActiveDirectory           Returns all trusted domain objects in the directory.
Get-ADUser                        Cmdlet    ActiveDirectory           Gets one or more Active Directory users.

it doesn't tell anything about how to use -Filter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb74884d-b4e3-3b14-8dcf-b5ab76654fcb
* Version Independent ID: cffb3241-9c76-0e74-a661-27e414120b3c
* Content: [Get-ADObject (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adobject?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/Get-ADObject.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsadministration/Get-ADObject.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
This is a known issue with the updatable help pipeline that affects the `Get-Help` and `Update-Help` commands.

There are ongoing efforts to rework the publishing engine. Once matured, failures to update modules are also going to be addressed. Internal sources inform us, the independent collaborators that it is going to take a lot of work.

There have been multiple reports of the help commands not working so please refer to issue #2247 for tracking the progress of this situation.

Thank you.
