### ISSUE TITLE
Additional information

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-powershell-docs#1527]
I've executed the cmdlet on my Windows 10 (version 1903, build 18362.418) Pro x64 and I've seen the below output with some additional information

TpmPresent                : True
TpmReady                  : True
ManufacturerId            : 1229346816
ManufacturerIdTxt         : IFX
ManufacturerVersion       : 4.40
ManufacturerVersionFull20 : Not Supported for TPM 1.2
ManagedAuthLevel          : Delegated
OwnerAuth                 :
OwnerClearDisabled        : True
AutoProvisioning          : Enabled
LockedOut                 : False
LockoutHealTime           : Not Supported for TPM 1.2
LockoutCount              : Not Supported for TPM 1.2
LockoutMax                : Not Supported for TPM 1.2
SelfTest                  : {128, 0, 1, 255}

Which is the meaning of the fields not described in this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4d48d0a-9739-1f28-00e0-8b6ba293ccce
* Version Independent ID: f6589833-3cc9-017b-4000-339e03239c4b
* Content: [Get-Tpm (trustedplatformmodule)](https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/get-tpm?view=win10-ps#feedback)
* Content Source: [docset/windows/trustedplatformmodule/Get-Tpm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/trustedplatformmodule/Get-Tpm.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by LuigiBruno** [comment]
> @LuigiBruno
> The issue has been noted and the document will be revised in the light of your feedback.
> Thank you.

Thank you @e0i.

**Comment by e0i** [comment]
@LuigiBruno 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by LuigiBruno** [comment]
> @LuigiBruno
> With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

Thank you @e0i.
