### ISSUE TITLE
note about SupportsShouldProcess bugs

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/windows-powershell-docs#1539]
Hi documentation team

There are some critical bugs with -Confirm and -WhatIf parameters
(https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/35264179-new-smbshare-whatif-not-working)

It is unlikely that the product guys will fix it any time soon due to too-low-number of votes.

Do you think you can make a note in the description of these two parameters saying that they are declared, but not implemented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1702c36-ad82-ffae-1f30-a43780020196
* Version Independent ID: ea1157b4-1084-ca11-6bdd-bf8ef57c1f5b
* Content: [New-SmbShare (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=winserver2012-ps&redirectedfrom=MSDN)
* Content Source: [docset/winserver2012-ps/smbshare/New-SmbShare.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/smbshare/New-SmbShare.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by shivtorov** [comment]
and this note is desireable for all relevant cmdlets:
Get-SmbShare
Remove-SmbShare
Set-SmbShare

**Comment by e0i** [comment]
Hello, @shivtorov 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.
