### ISSUE TITLE
Set-WebApplicationProxyConfiguration is Missing Some Parameter Descriptions

### ISSUE THREAD

**Issue by X-Guardian** [MicrosoftDocs/windows-powershell-docs#1541]
In the `WebApplicationProxy` module, the following `Set-WebApplicationProxyConfiguration` parameters are missing descriptions:

- ADFSTokenAcceptanceDurationSec
- UserIdleTimeoutAction
- UserIdleTimeoutSec

**Comment by e0i** [comment]
@X-Guardian Thank you for providing this nice catch.

The issue has been noted and the document will be revised in the light of your feedback.

Have a nice day.
