### ISSUE TITLE
Parameter Description is Wrong

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/windows-powershell-docs#1544]
For ComputerName, it states:

&gt; Specifies an array of names of computers. The cmdlet adds these computers to the replication group specified by the GroupName parameter. You can use a comma separated list and the wildcard character (*).

This is incorrect for Get-DfsrState, as it does not add any computer to a replication group - seems like perhaps a bad copy/paste from another article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed30c38-fd28-bfee-32b7-ac7a1fb45779
* Version Independent ID: 2b31eaaa-22e9-76e1-c162-58eae3f3e745
* Content: [Get-DfsrState (dfsr)](https://docs.microsoft.com/en-us/powershell/module/dfsr/get-dfsrstate?view=win10-ps#feedback)
* Content Source: [docset/windows/dfsr/Get-DfsrState.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dfsr/Get-DfsrState.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @ChrisKibble 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.
