### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by therefriedbean** [MicrosoftDocs/windows-powershell-docs#155]
I've been learning powershell. I would like to help my company automate much of the work we do. I see you can give a "principal" for the security context of the task. I've been reading this is a CIM object. 

My feedback is -- It would be nice to have a link that explains how to set your security context/principal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a43f16-2c96-fb74-263f-fb113d07ab66
* Version Independent ID: a93374e6-2115-c17f-bd4c-ab4efc958143
* Content: [New-ScheduledTask (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtask?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/new-scheduledtask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/new-scheduledtask.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@kenwith A PR #927 available for this issue. Please review. Thanks.

**Comment by kenwith** [comment]
Please send all Office and Windows PowerShell through @AndreaBarr and she will track down product team members that own the area and get sign off.

**Comment by e0i** [comment]
@AndreaBarr Please have the PR #927 for this issue reviewed. Thanks.

**Comment by e0i** [comment]
@therefriedbean We have updated the documentation with relevant links. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
