### ISSUE TITLE
Page needs even more details

### ISSUE THREAD

**Issue by JulioQc** [MicrosoftDocs/windows-powershell-docs#1553]
What registry keys does this command modify? For example, what is changed when running "Set-SmbServerConfiguration -EnableSMB2Protocol $true -force"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf1abaf-c268-b76f-48b5-5f5723fecb83
* Version Independent ID: 0c17d9d3-bbc4-f467-b44c-d78bb0c7e370
* Content: [Set-SmbServerConfiguration (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=win10-ps#outputs)
* Content Source: [docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/smbshare/Set-SmbServerConfiguration.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @JulioQc 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by JulioQc** [comment]
@e0i I found my answers: 

"HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters"
either SMB1 or SMB2 set to 0 or 1
