### ISSUE TITLE
Get-Childitem misspelling

### ISSUE THREAD

**Issue by GitHubBJW** [MicrosoftDocs/windows-powershell-docs#1554]
When performing:
Get-Help Get-Childitem -Full

The following result is returned for the -LiteralPath parameter in the help (using PS 5.1.18362.145)
"    -LiteralPath <String[]>
        Specifies, as a string arrya, a path to one or more locations. Unlike the Path.......
"
Notice the word 'arrya' should be array.

Thank you.

**Comment by e0i** [comment]
Hello, @GitHubBJW 

The online [article](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-5.1) for `Get-Childitem` is located in [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs) repository.

The mentioned typo seems to be not present in the article. Please ensure that your documentation cache is up to date and consider providing a feedback to the relevant repository if the problem persists.

Thank you for providing feedback.
