### ISSUE TITLE
Typo in Menu for TlsEccCurve

### ISSUE THREAD

**Issue by steeleprice** [MicrosoftDocs/windows-powershell-docs#1555]
Enable-TlcEccCurve in the left PowerShell Reference Menu should be corrected to Enable-TlsEccCurve 
(I can't edit the menu or I would submit the change.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d4ffef-9c4d-a310-208a-e6487236a9fc
* Version Independent ID: bd229190-de67-c9b8-1ee6-e35222022df5
* Content: [Enable-TlsEccCurve (tls)](https://docs.microsoft.com/en-us/powershell/module/tls/enable-tlcecccurve?view=win10-ps#feedback)
* Content Source: [docset/windows/tls/Enable-TlcEccCurve.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/tls/Enable-TlcEccCurve.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@steeleprice 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.
