### ISSUE TITLE
Example 1 does include private key 

### ISSUE THREAD

**Issue by AvrumFocus** [MicrosoftDocs/windows-powershell-docs#1559]
The description on example 1 claims that the example exports the certificate without its private key, while from my testing the private key does get included when it exists on the computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65b6499-db87-1c88-eca1-1bd76e6345c2
* Version Independent ID: 44dfc71a-6349-1192-3a7c-6881ab1ec843
* Content: [Export-Certificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/export-certificate?view=win10-ps#feedback)
* Content Source: [docset/windows/pkiclient/Export-Certificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/pkiclient/Export-Certificate.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @AvrumFocus 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@AvrumFocus In our investigation we have confirmed that the private key is indeed being exported and the issue is being escalated as a bug. Thank you for providing this valuable feedback.
