### ISSUE TITLE
AttackSurfaceReductionOnlyExclusions

### ISSUE THREAD

**Issue by nashuatek** [MicrosoftDocs/windows-powershell-docs#1563]
This parameter is missing from the documentation: AttackSurfaceReductionOnlyExclusions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40540e99-10c7-209d-f017-ccd36a5edb36
* Version Independent ID: 95c94241-a8d0-69b3-ec0d-f1c56b3ff360
* Content: [Remove-MpPreference (defender)](https://docs.microsoft.com/en-us/powershell/module/defender/remove-mppreference?view=win10-ps#feedback)
* Content Source: [docset/windows/defender/Remove-MpPreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/defender/Remove-MpPreference.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@nashuatek  Thank you for your feedback. We have added more details to the doc via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1952

Thanks
Sri

**Comment by e0i** [comment]
Closing via #1952.
