### ISSUE TITLE
Decide what to do about enumeration of modules for Client v. Server and 2016 v. 2019

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/windows-powershell-docs#1566]
Right now, the most up-to-date docset is called "Windows 10 and Server 2016", which carries a number of problems:

* there are some modules that I don't believe shipped until Server 2019 sitting in that docset
* some modules don't ship on Client, and others don't ship on Server
* some modules were introduced in Windows 10 during "obscure" (i.e. non-LTS or non-Server) milestones, but it's unclear to users

I'm currently building an internal spreadsheet of all modules I know about within Microsoft, and am working to learn where and when they shipped. This can certainly feed what we want to do from a moniker/docset perspective, but I think we should figure out how much we want to splinter and manage docsets before I start populating things with info.

**Comment by e0i** [comment]
@joeyaiello Hello Joey, We'd be happy to update the repository according to the spreadsheet. Thank you.

**Comment by e0i** [comment]
The documentation now has drop-down options for versions Server 2019 and Server 2022.
