### ISSUE TITLE
The cmdlet not worked

### ISSUE THREAD

**Issue by pengzhisun** [MicrosoftDocs/windows-powershell-docs#1568]
I've tried to execute this cmdlet, but only created an empty backend pool resource without any backend ip configurations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45300feb-159a-6671-75d1-4bd72c291aa1
* Version Independent ID: d5adde6a-0571-8095-8086-88b08abea686
* Content: [New-NetworkControllerLoadBalancerBackendAddressPool (networkcontroller)](https://docs.microsoft.com/en-us/powershell/module/networkcontroller/new-networkcontrollerloadbalancerbackendaddresspool?view=win10-ps)
* Content Source: [docset/windows/networkcontroller/New-NetworkControllerLoadBalancerBackendAddressPool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/networkcontroller/New-NetworkControllerLoadBalancerBackendAddressPool.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@pengzhisun. Sír could you tell me command you are typed. if possible give screenshot of error

**Comment by pengzhisun** [comment]
> @pengzhisun. Sír could you tell me command you are typed. if possible give screenshot of error

Hi @RAJU2529 , there is no error after this command, I've tried to add an IPConfig  object for one VM NIC to a new load balancer backend pool, but after the command execution, only an empty backend pool created without the IPConfig to be added.

The sample scripts to re-pro:

```powershell

# Get IP Config for one VM NIC with IP Address "172.20.0.110" in Virtual Network "test-vnet"
$VNETName = "test-vnet"
$NICIpAddress = "172.20.0.110"
$VNET = Get-NetworkControllerVirtualNetwork -ConnectionUri $Uri -Credential $Creds -PassInnerException | Where-Object { $_.ResourceMetadata.ResourceName -eq $VNETName }
$NIC = Get-NetworkControllerNetworkInterface -ConnectionUri $Uri -Credential $Creds -PassInnerException | Where-Object { $_.Properties.IpConfigurations.Properties.Subnet.ResourceRef -eq $VNET.Properties.Subnets[0].ResourceRef -and $_.Properties.IpConfigurations.Properties.PrivateIpAddress -eq $NICIpAddress }
$IpConfig = $NIC.Properties.IpConfigurations[0]

# New SLB Backend Pool for an existed SLB in the same vnet
$BEPool = New-Object Microsoft.Windows.NetworkController.LoadBalancerBackendAddressPoolProperties
$BEPool.backEndIpConfiguration = $IpConfig

New-NetworkControllerLoadBalancerBackEndAddressPool -ConnectionUri $Uri -LoadBalancerId "{some-slb-id}" -ResourceId "test-pool" -Properties $BEPool
```

**Comment by e0i** [comment]
@pengzhisun 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
