### ISSUE TITLE
The MountPath example does not work, needs modifying

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/windows-powershell-docs#1569]
Hi

(At least when I try this) on Server 2016 and I put a mountPath that contains something like "c:\users\..." it does not work. It only works for me when I use the root of the drive "c:\"  ... I learned this from others discussing the same and coming up with this. Why a mountpath is needed in the Import when it is not needed in the export is mind boggling.

Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b1f7af-3a6a-ca25-4329-93fbd6226e32
* Version Independent ID: 56773c31-28cb-6254-dc2e-f6af7aaa3697
* Content: [Import-StartLayout (startlayout)](https://docs.microsoft.com/en-us/powershell/module/startlayout/import-startlayout?view=win10-ps#feedback)
* Content Source: [docset/windows/startlayout/Import-StartLayout.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/startlayout/Import-StartLayout.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@blouwagie. Sir this topic about getting start layout xml from mounted windows image. 
I think C:\users is not correct mounted point.

Did you mounted windows image .wim file before entering  commands in PS?

**Comment by blouwagie** [comment]
Hi
I just tried the commands as per the instructions. If other commands are
needed first they should be documented.
Any way, as long as I put c:\ as the mount path it worked. Any other path
did not work. Certainly the mount path as in the documentation did not work.
It is frustrating that the export and import command have differing syntax.
My comment is about poor documentation, as I figured out how to work around
the documentation. I just hope you can make the documentation clear for
others (not for me)
Thx

bart

bart@louwagie.com

**Comment by e0i** [comment]
@blouwagie 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by darthmarx** [comment]
Same problem here, import command doesn't work with mounted image to C:\TEST\MOUNT
It says: Import-StartLayout : The path C:\TEST\MOUNT\ did not resolve to a file.
@blouwagie would you mind sharing your workaround?

**Comment by blouwagie** [comment]
If I remember correctly.
I used just the drive letter for the mount path, no subfolders

Bart Louwagie

**Comment by RAJU2529** [comment]
@blouwagie  I got the same error as @darthmarx   got, but i solved  in another way i didnt used mount path command, instead i copied the imported  .xml to the destination,.

i used the following commands 

**Mount-WindowsImage -imagepath "C:\test\offline\install.wim" /index 1 -Path "C:\test\mount" -Optimize**

**Copy-Item -Path C:\Layouts\Customlayout.xml -Destination 
C:\test\mount\Users\Default\AppData\Local\Microsoft\Windows\Shell\DefaultLayouts.xml**

**DisMount-WindowsImage -Path "C:\test\mount" -CheckIntegrity -Save**

**Comment by VLG17** [comment]
@blouwagie Thank you for providing this feedback. I have created a change request with the cmdlet modification. 

Regarding why it only works with "C:\" (or other workarounds like using a variable) we will need to wait for the authors to intervene.

In my opinion it makes sense to use the root because of the -MountPath definition from the article - "Specifies the path where you mounted the .wim file and **specifies the local appdata folder for the default user.**"

**Comment by e0i** [comment]
Closing via above comment and the merged PR addressing the issue, #1823. Thank you, all.
