### ISSUE TITLE
Clarity updates

### ISSUE THREAD

**Issue by giwleb** [MicrosoftDocs/windows-powershell-docs#157]
You might consider adding a link for the valid rrsandf_plural values, and also describe what the expected outcome will be if the feature is already installed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d05b2e2-d244-3807-ef9a-c88b0e7a207a
* Version Independent ID: 5e7493c1-7e9e-1a48-4318-7059eb1d3e26
* Content: [Install-WindowsFeature (servermanager)](https://docs.microsoft.com/en-us/powershell/module/servermanager/install-windowsfeature?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/servermanager/Install-WindowsFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/servermanager/Install-WindowsFeature.md)
* Service: **unspecified**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
Hello, @giwleb 

The `rrsandf_plural` values have actually been typos and have been fixed with recent changes to documentation. See issue #581 for details. 

Thanks for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
