### ISSUE TITLE
Adfs Module: Parameters and Cmdlets introduced in Server 2019 Missing from Documentation

### ISSUE THREAD

**Issue by X-Guardian** [MicrosoftDocs/windows-powershell-docs#1571]
The following cmdlets and parameters introduced in the Windows Server 2019 version of ADFS, are missing from the documentation:

#### Set-AdfsProperties

- ExtranetLockoutMode
- ExtranetLockoutThresholdFamiliarLocation

#### Set-AdfsGlobalAuthenticationPolicy

- EnablePaginatedAuthenticationPages

### Cmdlets Missing

- Update-AdfsArtifactDatabasePermission
- Get-ADFSAccountActivity
- Set-ADFSAccountActivity
- Reset-ADFSAccountLockout

References:
- [AD FS Extranet Lockout and Extranet Smart Lockout](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection)
- [AD FS paginated sign-in](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-paginated-sign-in)

**Comment by RAJU2529** [comment]
@X-Guardian. Sir I don't have server 2019 OS, so I cant check. If you think missing cmdlets are really needed and should be updated, then Create new PR with GitHub login.
Thanking  sir

**Comment by X-Guardian** [comment]
Not helpful @RAJU2529. If you can't check, don't comment.

**Comment by e0i** [comment]
The mentioned changes have been introduced in Server 2019, which is not currently supported, and the current documentation only covers up to version 2016.

Thank you for providing feedback.

**Comment by mukhea1991** [comment]
Guys,
I have checked form the below cmdlets in ADFS 2019 and it is working from there:
Get-ADFSAccountActivity
Set-ADFSAccountActivity
Reset-ADFSAccountLockout

The primary problem is with UPN, which is causing confusion as most of environments have separate/different Domain Netbios and email domain. In most cases email domain are used for UPN which will not be supported for ADFS 2019. I will suggest to use UPN in following format:
samaccountname@ADDomainnetbios

I am unsure currently with Update-AdfsArtifactDatabasePermission, but will need to check the same later.

Thanks,
Abhishek Mukherjee
