### ISSUE TITLE
pkiclient module is not available

### ISSUE THREAD

**Issue by ubreddy** [MicrosoftDocs/windows-powershell-docs#1576]
Not sure where to import the pkiclient module from on windows 10. not available in powershell 6 or 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa44e0de-b8a0-a89a-78ec-fb85f080c4ff
* Version Independent ID: da88acb9-808b-1750-5da2-3dd9fa658174
* Content: [New-SelfSignedCertificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps#feedback)
* Content Source: [docset/windows/pkiclient/New-SelfSignedCertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/pkiclient/New-SelfSignedCertificate.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by parameshbabu** [comment]
it seems you need to look for pspki module.

**Comment by roelofz** [comment]
This is bizar. Following https://docs.microsoft.com/en-us/learn/modules/configure-network-for-azure-virtual-machines/5-exercise-create-azure-vpn-gateway this command fails on the powershell in the portal. No way to update the Powershell in the portal. So how to train?
