### ISSUE TITLE
appending each time?

### ISSUE THREAD

**Issue by JohnNelsonNmbr2** [MicrosoftDocs/windows-powershell-docs#1582]
Does this cmdlet overwrite the WindowsUpdate.log each time it runs or does it append each time?  Just planning out my strategy for running this and wondering if I need to add in a purge step.  The documentation isn't clear on how it handles rows that already exist in the target log file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee8ec10d-d91b-96b5-83be-043ae1a563ed
* Version Independent ID: 0b6ce2ed-bdb1-fd9e-89e0-b3948faf595b
* Content: [Get-WindowsUpdateLog (windowsupdate)](https://docs.microsoft.com/en-us/powershell/module/windowsupdate/get-windowsupdatelog?view=win10-ps#feedback)
* Content Source: [docset/windows/windowsupdate/Get-WindowsUpdateLog.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/windowsupdate/Get-WindowsUpdateLog.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@johncdawson. Normally all windows update logs will be stored in **C:\Windows\logs\WindowsUpdate** in .etl formats.

If you need new log files, then you must delete all .etl files after  getting **WindowsUpdateLog**
I hope this answered

**Comment by e0i** [comment]
Hello @JohnNelsonNmbr2,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
