### ISSUE TITLE
Does the RemoveData parameter completely erase data?

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-powershell-docs#1585]
If I use the clear-disk cmdlet with RemoveData parameter, can I safely use the Bitlocker "Encrypt only used space" option without having to worry about previous data on disk?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37de68a-e057-f398-7ae5-9664ebabfa6a
* Version Independent ID: d546bb03-3173-3740-b1a6-aa3e8f4b3a47
* Content: [Clear-Disk (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/clear-disk?view=win10-ps)
* Content Source: [docset/windows/storage/Clear-Disk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/storage/Clear-Disk.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by csm10495** [comment]
Not sure if this fully helps though it really only deletes the partition/file table info. (so several sectors at the start of the drive and at the end). Data on the middle is still intact.

**Comment by Martony78** [comment]
The Bitlocker « encrypt only used space » option is therefore a security breach...

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by Martony78** [comment]
I was not looking for support, I was asking for information about what the clear-disk cmdlet exactly do, since the doc didn’t clearly explain it.
BTW I asked this 3 years ago….
