### ISSUE TITLE
Broken description

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/windows-powershell-docs#1589]
Description section says:

>The Get-WindowsFeature cmdlet gets information about rrsandf_plural that are both available for installation and already installed on a computer that is running Windows Server 2012 R2 or an offline virtual hard disk (VHD) that is running Windows Server 2012 R2.

Issues:
* `rrsandf_plural` shall be replaced with appropriate words
* `Windows Server 2012 R2` shall be replaced with a more generic OS reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed4918e-8ebc-6b11-17fa-8c9662065bab
* Version Independent ID: 8d17a25e-ea2d-71cb-8c7d-965a8851d83d
* Content: [Get-WindowsFeature (servermanager)](https://docs.microsoft.com/en-us/powershell/module/servermanager/get-windowsfeature?view=winserver2012r2-ps&viewFallbackFrom=win10-ps)
* Content Source: [docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@shivtorov Thank you for your feedback. We have updated the doc to reflect appropriate words and the same can be tracked via PR # https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1635
Meanwhile, windows server 2012 R2 is correct as this particular document pertains to that OS only.

Thanks
Sri

**Comment by e0i** [comment]
@shivtorov 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
