### ISSUE TITLE
出现异常CimException

### ISSUE THREAD

**Issue by LD126** [MicrosoftDocs/windows-powershell-docs#1594]
在本机powershell使用此命令后出现CimException异常

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3f07ff81-8cce-53cb-c5b3-f9e4ca89d36c
* Version Independent ID: 2d6a4140-bba7-0635-42f3-3885b75332a2
* Content: [Add-NetNatStaticMapping (netnat)](https://docs.microsoft.com/zh-cn/powershell/module/netnat/Add-NetNatStaticMapping?view=win10-ps#feedback)
* Content Source: [docset/windows/netnat/Add-NetNatStaticMapping.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/netnat/Add-NetNatStaticMapping.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by idanhacm** [comment]
Trying to configure Static mapping using an ExternalIPAddress other than 0.0.0.0
Get us this message:
"Add-NetNatStaticMapping : The process cannot access the file because it is being used by another process."

**Comment by e0i** [comment]
Translated:

465/5000
看来最好通过[PowerShell社区链接]（https://docs.microsoft.com/powershell/#pivot=main&panel=community）来回答这个问题。

有关特定于PowerShell的错误报告，请访问[GitHub上的PowerShell]（https://github.com/powershell/powershell/issues/）。

此存储库的问题部分用于与文档有关的内容修复。 如果您想对文章本身进行改进，请随时重新打开。

谢谢。
