### ISSUE TITLE
Add-ClusterResourceDependency has an incorrect example and unclear parameters

### ISSUE THREAD

**Issue by paul-alt-delete** [MicrosoftDocs/windows-powershell-docs#1596]
The current example for Add-ClusterResourceDependency is incorrect:
```PowerShell
Add-ClusterResourceDependency -Cluster "FileServer-(cluster1FS12)(Cluster Disk 2)" -Resource "Cluster Disk 4"
```
The generic `-Cluster` parameter indicates what cluster to connect to, not the resource to add the new dependency to.

When I checked the parameter descriptions to find the correct usage, I found that some parameters seem mutually exclusive (like `-InputObject` and `-Resource`). But this isn't called out, and the command doesn't use parameter sets to enforce that. I tried testing different parameter combinations on a 2012 R2 test cluster, and found three valid combinations. So ideally, the documentation should be updated to show those three usage options:

```PowerShell
# Example 1: Corrected version of the current example
Add-ClusterResourceDependency -Resource 'File Server (\\cluster1FS12)' -Provider 'Cluster Disk 4'

# Example 2: Pipe in the main resource, add the dependency using the -Provider parameter
Get-ClusterResource -Name 'File Server (\\cluster1FS12)' | Add-ClusterResourceDependency -Provider 'Cluster Disk 4'

# Example 3: Pipe in the main resource, add the dependency using the -Resource parameter
Get-ClusterResource -Name 'File Server (\\cluster1FS12)' | Add-ClusterResourceDependency -Resource 'Cluster Disk 4'
```
Example 2 and 3 show how the -Resource parameter can mean different things depending on how the command is run. **Based on context, `-Resource` can mean opposite things,** either
- the resource to modify (will be set to depend on the other resource), *or*
- the dependency to add (will be added to the other resource as a dependency).

I found that surprising and unintuitive, and I'd suspect that others will be confused by it as well. I haven't seen any other PowerShell commands from Microsoft with behavior like that, so it's probably worth explicitly calling out. I'm assuming that the behavior is unintentional, but is kept for backwards compatibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 407bae70-7d15-5c36-101d-3b17852771d7
* Version Independent ID: ee6c092a-941c-dfbe-b59d-40e2b1ea9cfe
* Content: [Add-ClusterResourceDependency (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcedependency?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/Add-ClusterResourceDependency.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/failoverclusters/Add-ClusterResourceDependency.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@paul-alt-delete Hello Paul,

Thank you for trying to make MicrosoftDocs a better place.

This is very confusing indeed. I think it is some kind of a glitch in cmdlet behaviour. I did some tests as well and the logical thing is:
 - InputObject - the resource to be modified
 - Resource - name of the resource to be modified
 - Provider - the resource to be added as dependency

This example could explain it:
` Get-ClusterResource TestService | Add-ClusterResourceDependency -Resource TestIP2 -Provider TestIP`
Here the **Resource** parameter is ignored and only the resource specified in the **Provider** parameter is added as dependency.

I will fix the example and escalate the other part as bug.
