### ISSUE TITLE
Example is empty

### ISSUE THREAD

**Issue by reuvygroovy** [MicrosoftDocs/windows-powershell-docs#1597]
Hi the example on the page has no content. It's unclear how to use this example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b6535e-7541-05b7-9e9c-375e29719968
* Version Independent ID: ccdedaf1-8d1d-7ad5-78d0-39a57286bdd2
* Content: [Remove-RDDatabaseConnectionString (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/remove-rddatabaseconnectionstring?view=win10-ps#feedback)
* Content Source: [docset/windows/remotedesktop/Remove-RDDatabaseConnectionString.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/remotedesktop/Remove-RDDatabaseConnectionString.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@reuvygroovy  Thank you for your feedback. We have updated the document with an example via PR # https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1636

Thanks
Sri

**Comment by e0i** [comment]
@reuvygroovy 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
