### ISSUE TITLE
-Stage is missing a description

### ISSUE THREAD

**Issue by slic0r** [MicrosoftDocs/windows-powershell-docs#1599]
-Stage parameter is missing a description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb4f0d3-57cc-12ec-4782-50c4bd76d3df
* Version Independent ID: a6e3366f-d935-d534-b0e9-f250095f9294
* Content: [Add-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=win10-ps#feedback)
* Content Source: [docset/windows/appx/Add-AppxPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/appx/Add-AppxPackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sowjanya365** [comment]
Hello @slic0r 

Thank you for reaching out! 

Some of the parameters which are available in the Windows Server 16 version, are not available in the Windows Server 2012 and Windows Server 2012 R2 versions.

For -Stage parameter description, please see the following links.

https://docs.microsoft.com/powershell/module/appx/add-appxpackage?view=winserver2012-ps 

https://docs.microsoft.com/powershell/module/appx/add-appxpackage?view=winserver2012r2-ps

Hope this clarifies your query. Thank you!
