### ISSUE TITLE
Default Behavior Change

### ISSUE THREAD

**Issue by lbarker66** [MicrosoftDocs/windows-powershell-docs#1603]
The test-connection default behavior now returns a failure at internetbeacon.msedge.com since it appears that site is no longer up. If this was on purpose a change in the documentation might be in order. there are customers who use that simple code to determine internet connectivity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdd28627-2f68-16e1-2916-c03fbf2873b8
* Version Independent ID: 3d77efba-83e2-b25c-09fd-d9c847293587
* Content: [Test-NetConnection (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/test-netconnection?view=win10-ps#feedback)
* Content Source: [docset/windows/nettcpip/Test-NetConnection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/nettcpip/Test-NetConnection.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @lbarker66 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@lbarker66 

We have had the confirmation that the remote site is in fact up.

See the command result quoted below,

```PowerShell
09:19:53|C:\>Test-NetConnection


ComputerName           : internetbeacon.msedge.net
RemoteAddress          : 72.21.81.200
InterfaceAlias         : Ethernet 3
SourceAddress          : xxxxxxx
PingSucceeded          : True
PingReplyDetails (RTT) : 3 ms
```

Feel free to re-open the issue should you notice the same behavior again.

Thank you for providing feedback.

**Comment by MrTatiTunes** [comment]
So why we have slui error related to this site all the time?
