### ISSUE TITLE
States that this cmdlet takes Wildcard characters in the "Description" but not under any parameters

### ISSUE THREAD

**Issue by JustinCredible-** [MicrosoftDocs/windows-powershell-docs#1604]
All parameters show on this page as "Accept wildcard characters: False". Does this cmdlet actually support wildcard characters, and if so, on which parameters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4fd499f-546f-5562-08b0-a92f23bec915
* Version Independent ID: 31fd5cc9-54eb-9301-ac02-af596e5a786f
* Content: [Remove-Printer (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/remove-printer?view=win10-ps#feedback)
* Content Source: [docset/windows/printmanagement/Remove-Printer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/printmanagement/Remove-Printer.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by JustinCredible-** [comment]
Testing this cmdlet, at the very least the "Name" parameter does accept wildcards.

**Comment by msbemba** [comment]
@JustinCredible- Thank you for your feedback. We have edited the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1637

Thanks
Sri

**Comment by e0i** [comment]
@JustinCredible- 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
