### ISSUE TITLE
Command doesn't allow filtering on RecordData

### ISSUE THREAD

**Issue by rem8** [MicrosoftDocs/windows-powershell-docs#1605]
PS C:\Users\admin> Get-DnsServerResourceRecord -RRType PTR -ComputerName dns.server.name -ZoneName 12.10.in-addr.arpa | ? {$_.HostName -eq "193.0"}

HostName                  RecordType Type       Timestamp            TimeToLive      RecordData
--------                  ---------- ----       ---------            ----------      ----------
193.0                     PTR        12         0                    00:10:00        your.server.name.

Assuming you want to check if a record PTR exists for server

PS C:\Users\admin&gt; Get-DnsServerResourceRecord -RRType PTR -ComputerName dns.server.name -ZoneName 12.10.in-addr.arpa | ? {$_.RecordData -eq "your.server.name."}

This doesn't return anything, but if you filter by hostname ($_.HostName -eq "193.0"}, it shows proper data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1701e8ed-ce3f-3a03-2f12-9438d8046fec
* Version Independent ID: 5d58a38c-5fb1-92c4-55a1-ef45aadbdcfd
* Content: [Get-DnsServerResourceRecord (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserverresourcerecord?view=win10-ps#feedback)
* Content Source: [docset/windows/dnsserver/Get-DnsServerResourceRecord.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dnsserver/Get-DnsServerResourceRecord.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issues section of this repository is used for documentation problems, not bugs related to the PowerShell modules.

Related UserVoice report: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/37356952-possible-bug-in-dns-module-get-dnsserverresourcere

 Feel free to re-open in case you would like to suggest improvements to the article itself.

Thank you.
