### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-powershell-docs#1607]
Example 1 says "scans for driver information". It does not. It scans for all executables, with the -UserPEs switch.
Example 2 says "This command scans for driver information". It does not. It also scans all executables. However, compared to the first example, it uses the -Fallback parameter, which creates a hash value for files not identified by signature.
I don't see that example 2 relates to "invalid signature format". It simply relates to unsigned executables.
The -ScriptFileNames parameter is missing a description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5e8ac6-f123-7aeb-147d-0fbf44a0691c
* Version Independent ID: ddd7f02d-549f-52dd-4b15-04b7ef3a521e
* Content: [New-CIPolicy (configci)](https://docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=win10-ps)
* Content Source: [docset/windows/configci/New-CIPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/configci/New-CIPolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @Air-Git

Your feedback concerning the scanning of drivers versus executable is being routed to the Product Team for investigation.

The description for missing ScriptFileNames parameter will be incorporated into documentation. 

Thank you for Providing feedback.

**Comment by VLG17** [comment]
@Air-Git thank you for providing this feedback. I have created a request to modify "driver information" with "user mode executables (applications) along with kernel mode binaries such as drivers".

Regarding the missing alias for "-ScriptFileNames", it's not missing, it's indeed not set/declared. It's not the only parameter of this cmdlet without an alias. You can check the parameters that have aliases with:

**(Get-Command (Read-Host "Enter a PowerShell Cmdlet Name")).parameters.values | where aliases | select name, aliases**

![image](https://user-images.githubusercontent.com/41186174/76748935-50f81100-6784-11ea-8524-aaecc6f05117.png)

**Comment by Air-Git** [comment]
Thanks VLG17. I'm not sure where the alias comes in. I was simply stating that, in the document, the parameter -ScriptFileNames is lacking a description.  All the other parameters have a short paragraph describing them, but not this one.

**Comment by VLG17** [comment]
@Air-Git Now that you mention it, i'm not quite sure how i came to the conclusion that you were reffering to the alias. My bad. I'll look into adding a description for the -ScriptFileNames parameter.

**Comment by e0i** [comment]
@Air-Git The document has been revised according to your feedback. Closing via PR #1829 
Thank you.
