### ISSUE TITLE
Undocumented PowerShell parameters for Deduplication

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windows-powershell-docs#1611]
It appears that in Server 2019 (and maybe even only _newer_ CUs of 2019), there are some new parameters.

Can we get info on:

```
-SkipReconciliation
-FastStart
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4d791f4-b957-f34d-cb58-cba3b9289952
* Version Independent ID: b0becec5-2d6a-e004-ae6c-b2bf55455b17
* Content: [Start-DedupJob (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/start-dedupjob?view=win10-ps)
* Content Source: [docset/windows/deduplication/Start-DedupJob.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/deduplication/Start-DedupJob.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sowjanya365** [comment]
Hi @eponerine 

Thank you for reaching out! 

This document serves the purpose of Windows server 2016 version. That is why we don't find them in this document. 

Hope this clarifies your query. Thank you!

**Comment by eponerine** [comment]
> This document serves the purpose of Windows server 2016 version. That is why we don't find them in this document.

Is there any plan to update the docs to include 2019?

**Comment by e0i** [comment]
@eponerine Yes, An entire section for Server 2019 is being planned. Please note that this is an unofficial response based on correspondence with the managers. Thank you.

**Comment by dyehya** [comment]
@o0nj @sowjanya365-zz This document still does not reference these in the current versions that apply to Server 2019 or newer. This should be reopened. Also this link shows as the "current" version of the document and these are still not documented.
