### ISSUE TITLE
word missing

### ISSUE THREAD

**Issue by benjamin-army** [MicrosoftDocs/windows-powershell-docs#1615]
"The Optimize-VHD cmdlet optimizes the allocation of space in or more virtual hard disk files, except for fixed virtual hard disks." Is it should be "The Optimize-VHD cmdlet optimizes the allocation of space in **ONE** or more virtual hard disk files, except for fixed virtual hard disks."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a28123af-9919-1114-e2c3-0256d75603e5
* Version Independent ID: 9840aef7-2f2f-5118-9902-f5fee8737157
* Content: [Optimize-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/optimize-vhd?view=win10-ps#feedback)
* Content Source: [docset/windows/hyper-v/Optimize-VHD.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/hyper-v/Optimize-VHD.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Closing via #1726
