### ISSUE TITLE
-PassThru parameter

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/windows-powershell-docs#1616]
I think there's been a change in behaviour for the returning object and now the lack of `-PassThru` parameter. I'm not sure when this change occurred, rumour has it in 1809 / Server 2019 onwards. 

Also, I notice currently there isn't a drop down at the top left to choose version for Windows 10 (1809+) and Windows Server 2019, is this somewhere else or in the works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c2b0ea-629e-ca77-722a-3091aad1fb57
* Version Independent ID: a834cf9d-2344-fd0e-8c8b-ecc4b1567ae6
* Content: [Dismount-DiskImage (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/dismount-diskimage?view=win10-ps#feedback)
* Content Source: [docset/windows/storage/Dismount-DiskImage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/storage/Dismount-DiskImage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Content for Server 2019 has not been published yet and we have been informed that it is under delivery.
