### ISSUE TITLE
Errors in Formatting

### ISSUE THREAD

**Issue by Felix382** [MicrosoftDocs/windows-powershell-docs#1617]
Example 6 is missing and Example 7 is within Parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8337d2-8c17-df81-3184-128e17d9d163
* Version Independent ID: fa6e2a23-2a2d-16f7-079b-e2f5bdd8d938
* Content: [Get-ADComputer (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adcomputer?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/Get-ADComputer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsadministration/Get-ADComputer.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@Felix382 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by msbemba** [comment]
@Felix382 Thank you for your feedback. We have corrected the formatting and added example6 and 7 to the document via PR# https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1638

Thanks
Sri
