### ISSUE TITLE
The language for the -SearchScope paramater is murky.

### ISSUE THREAD

**Issue by CMDMC12** [MicrosoftDocs/windows-powershell-docs#1625]
> A Base query searches only the current path or object.

If I were to say to you "search the Example OU for users", you would actually look in that OU for users right? Instead this parameter will return nothing if you just specify an OU. 

> A OneLevel query searches the immediate children of that path or object. 

To me, this would search the OU you give it, plus any OUs directly within that OU.

> A Subtree query searches the current path or object and all children of that path or object.

This is fine. 

Honestly I would've made Base the default SearchScope, but it's far too late to change that. Too much in the wild would break, I'm sure.

I suggest the following changes:
> A Base query searches only **for** the ~~current~~ **given** ~~path or object~~ user. **If an OU is given as the SearchBase, no results will be returned.**

> A OneLevel query searches the immediate children of that path or object. **This option only works when an OU is given as the SearchBase. If a user is given, no results are returned.**

**Comment by e0i** [comment]
@CMDMC12 

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by CMDMC12** [comment]
> @CMDMC12
> 
> Could you clarify which documentation you're referring to? A link would be helpful.
> 
> Thanks.

https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-aduser?view=win10-ps

It looks like it was taken directly from what's used for Get-ADObject (https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-aduser?view=win10-ps)
