### ISSUE TITLE
Set-NetConnectionProfile usage example does not work

### ISSUE THREAD

**Issue by hmhackmaster** [MicrosoftDocs/windows-powershell-docs#1629]
The usage example for changing the network category of a connection profile ( [Direct Link](https://docs.microsoft.com/en-us/powershell/module/netconnection/set-netconnectionprofile?view=win10-ps&source=docs#examples) ) does not work. Tested on Windows 10 Enterprise 1903 & Windows Server 2019.

The commands referenced in the article are reproduced here:

```

PS C:\> $NetworkProfile = Get-NetConnectionProfile -InterfaceAlias Ethernet1

PS C:\> $NetworkProfile.NetworkCategory = Public

PS C:\> Set-NetConnectionProfile -InputObject $NetworkProfile
```

The usage example could be shorted to the following (functional) single-command.
```
PS C:\> Set-NetConnectionProfile -InterfaceAlias Ethernet1 -NetworkCategory "Public"
```

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 983029b7-7f55-a30a-b842-ef19a0f88e7c
* Version Independent ID: 253ace06-2925-2ca8-4cb3-30d167678bfd
* Content: [Set-NetConnectionProfile (netconnection)](https://docs.microsoft.com/en-us/powershell/module/netconnection/set-netconnectionprofile?view=win10-ps&source=docs#feedback)
* Content Source: [docset/windows/netconnection/Set-NetConnectionProfile.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/netconnection/Set-NetConnectionProfile.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by prerequisites** [comment]
it will be unavailable after restart os
