### ISSUE TITLE
Info that you need to run Get-ComputeProcess in an elevated PowerShell is missing

### ISSUE THREAD

**Issue by alexandair** [MicrosoftDocs/windows-powershell-docs#163]
It's not documented that you need to run Get-ComputeProcess in an elevated PowerShell.

Also, an error message when you run it as a standard user is cryptic and unusable:

```get-computeprocess : There are no more endpoints available from the endpoint mapper. (Exception from HRESULT: 0x800706D9)```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b816875d-f1cb-0097-14ce-9fbb9580ee69
* Version Independent ID: b46540fe-fd69-d285-cbec-576056b85a76
* Content: [Get-ComputeProcess (hostcomputeservice)](https://docs.microsoft.com/en-us/powershell/module/hostcomputeservice/get-computeprocess?view=win10-ps)
* Content Source: [docset/windows/hostcomputeservice/get-computeprocess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hostcomputeservice/get-computeprocess.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
hi @alexandair thanks for your feedback, I'll create a PR to improve the article based on your comment.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @alexandair Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
