### ISSUE TITLE
Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/NetAdapter documentation link

### ISSUE THREAD

**Issue by rgl** [MicrosoftDocs/windows-powershell-docs#1634]
Please provide a hyperlink to the output object Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/NetAdapter documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee40ff57-db70-878c-8ece-2afb83c1bb2e
* Version Independent ID: a8582de4-f170-b3f1-feba-6b3f2e2bfaad
* Content: [Get-NetAdapter (netadapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/get-netadapter?view=win10-ps#feedback)
* Content Source: [docset/windows/netadapter/Get-NetAdapter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/netadapter/Get-NetAdapter.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@rgl. Here is the hyperlink
**https://docs.microsoft.com/en-us/dotnet/api/microsoft.management.infrastructure.ciminstance?view=pscore-6.2.0**

**Comment by rgl** [comment]
The link should be to somewhere that documents the output object of the Get-NetAdapter cmdlet, which seems to be ROOT/StandardCimv2/NetAdapter and not the base CimInstance.

**Comment by velkovb** [comment]
@rgl Hello Rui,
I have updated the article with a link to the class docs. Here it is for your reference as well:
[Cim-NetowrkAdapter](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/cim-networkadapter)
