### ISSUE TITLE
Invalid parameter shown in example

### ISSUE THREAD

**Issue by jgpisani** [MicrosoftDocs/windows-powershell-docs#165]
Your example for removing a personal session host assignment shows a parameter that does not exist, "PersonalVirtualDesktop"

-PersonalVirtualDesktop "PVD-12"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e400bdbd-6187-3838-33b2-4eafd5ac88bd
* Version Independent ID: 905690a8-47ba-12cc-cceb-191faa6ccd38
* Content: [Remove-RDPersonalVirtualDesktopAssignment (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/remove-rdpersonalvirtualdesktopassignment?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/remove-rdpersonalvirtualdesktopassignment.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/remove-rdpersonalvirtualdesktopassignment.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by VLG17** [comment]
changes have been made and commit merged.

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and sharing this explanation. @jgpisani 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
