### ISSUE TITLE
Getting an error if passing "-User" field with this command

### ISSUE THREAD

**Issue by KrupalJoshi** [MicrosoftDocs/windows-powershell-docs#1651]
Hi,

I am using this command from the PowerShell in the one of Node of cluster.

If i am passing "-User" parameter with user name it gives an error.

Get-ClusterAccess -User administrator
Get-ClusterAccess : User administrator cannot be found.
At line:1 char:1
+ Get-ClusterAccess -User administrator
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (administrator:String) [Get-ClusterAccess], Exception
    + FullyQualifiedErrorId : Get-ClusterAccess,Microsoft.FailoverClusters.PowerShell.GetClusterAccessCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 196c7422-6841-30bf-5cd8-be346db24c1e
* Version Independent ID: 2382c49d-88bd-ff12-dbae-27dce66a1fc1
* Content: [Get-ClusterAccess (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/get-clusteraccess?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/Get-ClusterAccess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/failoverclusters/Get-ClusterAccess.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@KrupalJoshi. I also checked the same command, i too received the same error.
So i think this cmdlet is  for  windows  2016

**Comment by e0i** [comment]
It seems that this question can best be answered via [PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.

Thank you.
