### ISSUE TITLE
ErrorAction is ignored

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/windows-powershell-docs#1657]
It seems `-ErrorAction Stop` is ignored for Get-DhcpServerv4Failover. I expect it to throw a terminating error and stop executing when given this parameter value, except execution continues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e37a36a-b11d-c619-5d89-ad348653f6b4
* Version Independent ID: 1a992256-3703-833f-c16f-c604058be07d
* Content: [Get-DhcpServerv4Failover (dhcpserver)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4failover?view=win10-ps)
* Content Source: [docset/windows/dhcpserver/Get-DhcpServerv4Failover.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dhcpserver/Get-DhcpServerv4Failover.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issue tracker of this repository is intended for product documentation issues only.

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)


Thanks.
