### ISSUE TITLE
Permissions Required for this Cmdlet?

### ISSUE THREAD

**Issue by tcjdunkeson** [MicrosoftDocs/windows-powershell-docs#1660]
What are the permissions required to use this cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67146b0-81ce-ad05-432d-602c57d6b4b7
* Version Independent ID: 8cf9c0cd-5a3d-3f5a-eb1b-7f0480f2feab
* Content: [Invoke-RDUserLogoff (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/invoke-rduserlogoff?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/Invoke-RDUserLogoff.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/remotedesktop/Invoke-RDUserLogoff.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sowjanya365** [comment]
Hi @tcjdunkeson 

Thank you for reaching out! 

You should try the command with the domain admin permissions. 

Hope this clarifies your query. Thank you!
