### ISSUE TITLE
Typo in first sentence

### ISSUE THREAD

**Issue by damiankras** [MicrosoftDocs/windows-powershell-docs#1662]
In first sentence there should be VMCollectionType instead of VMCollectionTpe 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34de619-5249-e2ad-df4a-ed03597322fc
* Version Independent ID: 19fd8733-98dd-1251-4a41-741e251ccbc9
* Content: [New-VMGroup (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/new-vmgroup?view=win10-ps#feedback)
* Content Source: [docset/windows/hyper-v/New-VMGroup.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/hyper-v/New-VMGroup.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Fixed in #1663.
