### ISSUE TITLE
Typo in Example 2 code: "-WeeksInterval" should be "-IntervalWeeks"

### ISSUE THREAD

**Issue by MCTSQL** [MicrosoftDocs/windows-powershell-docs#1669]
Typo in Example 2 code: "-WeeksInterval" should be "-IntervalWeeks"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56ce6678-7852-6308-f7c9-9473c4001758
* Version Independent ID: 041fff23-d521-b173-08a4-b1da92b2d173
* Content: [Add-CauClusterRole (clusterawareupdating)](https://docs.microsoft.com/en-us/powershell/module/clusterawareupdating/add-cauclusterrole?view=win10-ps#feedback)
* Content Source: [docset/windows/clusterawareupdating/Add-CauClusterRole.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/clusterawareupdating/Add-CauClusterRole.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@MCTSQL The associated PR, #1672 has been merged. Thank you for the feedback.
