### ISSUE TITLE
Typo in Example 2 code: "-WeeksInterval" should be "-IntervalWeeks"

### ISSUE THREAD

**Issue by MCTSQL** [MicrosoftDocs/windows-powershell-docs#1670]
Typo in Example 2 code: "-WeeksInterval" should be "-IntervalWeeks"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc3cd81-89c1-2177-3714-08f80f8d7363
* Version Independent ID: b26ff96d-d53e-4aa4-9dce-0e176eb1f804
* Content: [Set-CauClusterRole (clusterawareupdating)](https://docs.microsoft.com/en-us/powershell/module/clusterawareupdating/set-cauclusterrole?view=win10-ps)
* Content Source: [docset/windows/clusterawareupdating/Set-CauClusterRole.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/clusterawareupdating/Set-CauClusterRole.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@MCTSQL 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
