### ISSUE TITLE
Azure Automate Module

### ISSUE THREAD

**Issue by ALopes21** [MicrosoftDocs/windows-powershell-docs#1675]
How do you import this module into Azure Automation runbooks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d545e9a-1c44-5e71-4d9a-2ad6aa31ddab
* Version Independent ID: 67677fbc-3e52-d292-659d-6d3e11d0fef1
* Content: [ActiveDirectory](https://docs.microsoft.com/en-us/powershell/module/addsadministration/?view=win10-ps)
* Content Source: [docset/windows/addsadministration/ActiveDirectory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsadministration/ActiveDirectory.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also, feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
