### ISSUE TITLE
domain win10 pro 1903 does not contain this cmdlet

### ISSUE THREAD

**Issue by VectorBCO** [MicrosoftDocs/windows-powershell-docs#1679]
RSAT not installed and i do not see any requirements for that
looks like some pre-requisites is not defined 
As a user i want to have alternative for gpudate /force  in powershell commandlets but this is not fully supported alternative...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95c56f6b-36ab-d05f-44a3-418d43be7c91
* Version Independent ID: 4fc21770-9fa1-9877-bcde-b9c7b6cf7dfd
* Content: [Invoke-GPUpdate (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/invoke-gpupdate?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/Invoke-GPUpdate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/grouppolicy/Invoke-GPUpdate.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@VectorBCO Just now i checked on standardalone computer running with windows 10 1909 with administartor powershell

**Invoke-Gpupdate**  does  not work.
But  **Gpupdate  /force**        works  fine
Also  **Gpupdate**   works  fine

**Comment by bahnjee** [comment]
From what I have found, this cmdlet doesn't show up (in Enterprise, at least) until version 2004 (InsiderPreview).  Just checked 1903, 1909 and 2004.

**Comment by bahnjee** [comment]
...should have mentioned, I don't have RSAT/GPMC installed on the 2004 machine.

**Comment by RAJU2529** [comment]
> GPMC

Are you uisng windows 10 Home edition , in home edition gpmc  does not have enabled, But we enable by  entering commands

**Comment by bahnjee** [comment]
I pretty clearly indicated this is on **Enterprise**.

**Comment by velkovb** [comment]
@VectorBCO @bahnjee 
The description of the module states that you need to have RSAT installed for it to work:
[GroupPolicy](https://docs.microsoft.com/powershell/module/grouppolicy/?view=win10-ps)

> This topic contains the brief descriptions of the Windows PowerShell cmdlets that are for use in administering Group Policy in Windows Server and Windows client with Remote Server Administration Tools (RSAT) installed. (RSAT includes the GPMC and the Group Policy cmdlets.)

Let me know if you have any questions.

**Comment by VectorBCO** [comment]
> @VectorBCO @bahnjee 
> The description of the module states that you need to have RSAT installed for it to work:
> [GroupPolicy](https://docs.microsoft.com/powershell/module/grouppolicy/?view=win10-ps)
> 
> > This topic contains the brief descriptions of the Windows PowerShell cmdlets that are for use in administering Group Policy in Windows Server and Windows client with Remote Server Administration Tools (RSAT) installed. (RSAT includes the GPMC and the Group Policy cmdlets.)
> 
> Let me know if you have any questions.
> 

2 comments:
1 gpupdate /force working fine on each PC or Server as with RSAT same than without RSAT
2 if this particular command have any limitations as a user i want to get ref link to the page where this limitations described (if list of this limitations is terribly big), or this limitations should be added to the notes (where desribided that this cmdlet not working on windows 7)

**Comment by velkovb** [comment]
@VectorBCO 

This issue was opened for Win10 not Windows 7. I have included link to the module description that states you need RSAT tools to get the cmdlet. Do you have any issues after installing RSAT?

Windows 7 support ended so I do not think you will get anything for it. It will have to keep using gpupdate.

**Comment by VectorBCO** [comment]
@velkovb i do not have any issues (at all) but as a system admin i would not install rsat on each client pc for getting same result that i will get without rsat.

If MS have a plan for replacing 100 years console tools, then this tools at leat should have similar functionality with similar requirements. And once again gpupdate working fine without any additional prerequsites on every windows os (even not supported anymore win xp or win 7). But if similar tool have *any* additional limitations (compare to original console tool) this limitations should be added to the help for this particular tool (commandlet or function)

**Comment by velkovb** [comment]
@VectorBCO 
I understand your frustration.

Usually cmdlets in the same module have the same requirements and those requirements are listed on the module page like it is for the GroupPolicy module. No point to have it in every single cmdlet of the module. 

Regarding the second part of this comment, here we are trying to solve issues with the documentation of PowerShell, we cannot solve issues with functionality. You can submit this feedback in other ways to Microsoft.

P.S. Recent Windows 10 release enable you to install only certain parts of RSAT tools.

```powershell
Get-WindowsCapability -Name RSAT* -Online | Select-Object -Property Name, State
Add-WindowsCapability -Name Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0 -Online
```

**Comment by bahnjee** [comment]
_"No point to have it in every single cmdlet of the module."_

I completely disagree.  It would take only adding "RSAT must be installed" (or similar) to add the requirements in each cmdlet's description.  If I'm researching a cmdlet's usage, I'm not likely going to dig _upwards_ to find the pre-reqs...especially when it makes no sense that RSAT must be installed to use PoSh to do a basic GPUpdate.

**Comment by velkovb** [comment]
@bahnjee I can't really think of cmdlet that actually states what needs to be installed for it to work. IT is pretty clear you need the PowerShell module that it is part of. For example, none of the Active Directory cmdlets list that Active Directory PowerShell module needs to be installed.
