### ISSUE TITLE
Separation of multiple hashtables with semicolon?

### ISSUE THREAD

**Issue by vikingtiger** [MicrosoftDocs/windows-powershell-docs#168]
I believe there is an error in the text. Under the Certificates parameter section, it says:

> You can specify more than one operation by using a list separated by semicolons. For example, use the following syntax to add and remove Certificates values:
> -Certificates @{Add=value1,value2,...};@{Remove=value3,value4,...}

I cannot understand how this example can be valid. If you specify a separate hashtable for the "Add" action, then a semicolon, the semicolon would terminate the statement. The rest of the line would be read as a separate statement, no?

I would think that one must either:
 * Specify multiple actions in the same hashtable, such as `@{"Add"=$certToAdd; "Remove"=$certToRemove}` ...or...
 * Specify an array/list of multiple hashtables, separated by *commas*, such as `@{"Add"=$certToAdd},@{"Remove"=$certToRemove}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30217138-eb8c-ab9a-4e11-991c6164cbd9
* Version Independent ID: 88ff510e-6402-5163-404f-e9154f59b381
* Content: [Set-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/set-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-aduser.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @vikingtiger thanks for your feedback.
Tested in a lab and the given example did not worked as a HashTable.
I will propose to change the given example by creating a pull request.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @vikingtiger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
