### ISSUE TITLE
Fails on double-hop needlessly

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/windows-powershell-docs#1684]
This command fails on double-hop needlessly - if executing remote and using a UNC physicalpath, it will fail.  The underlying appcmd and Microsoft.Web.Management will not fail.

Please add remarks explaining this situation.  I burned weeks of man-hours trying to work around this problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c262e5-c8b2-0503-d422-0598a47c2061
* Version Independent ID: ae81bda2-6cc8-d1aa-f03e-29c62a741641
* Content: [New-WebApplication (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-webapplication?view=winserver2012-ps&source=docs#feedback)
* Content Source: [docset/winserver2012-ps/webadminstration/New-WebApplication.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/webadminstration/New-WebApplication.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@Pxtl Hello Martin,

Thank you for your feedback. 

I am trying to replicate the issue. Could you share the OS Version and PowerShell version where you are having this issue? Furthermore, if you could give an example of the failing cmdlet it will be great.

Hope to hear from you soon.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
