### ISSUE TITLE
New-DfsnRoot does not create the shared folder on the DFS Server

### ISSUE THREAD

**Issue by thesmall** [MicrosoftDocs/windows-powershell-docs#1692]
The `New-DfsnRoot` cmdlet will not create a shared folder in the DFSRoots folder on the DFS server if it does not exist. This leads to the error:

`New-DFSNRoot : Root target share "\\dc01.domain.com\shares" wasn't found. Namespace root target share should exist when creating new namespace`

The DFS Management MMC Snapin on the other hand, will note that the DFSRoots share will be created if it doesn't exist:

`Root shared folder:  A shared folder will be created if one does not exist`

The New-DfsnRoot cmdlet should create the share in the DFSRoots folder if it does not exist (in the case of initial provisioning of a DFS Namespace) on a given DFS server.

At the very least, the help document for this cmdlet should be updated to note this discrepancy. 

Sanitized function call:

`New-DFSNRoot -Path \\domain.com\shares -TargetPath \\dc01.domain.com\shares -Description "Sample Description." -TimeToLiveSec 600 -State Online -Type DomainV2`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6e5e5e-0ce9-46dd-553c-f45fc0e11a97
* Version Independent ID: e9d7cb09-768e-a05e-b825-d23c3d142e52
* Content: [New-DfsnRoot (dfsn)](https://docs.microsoft.com/en-us/powershell/module/dfsn/new-dfsnroot?view=win10-ps)
* Content Source: [docset/windows/dfsn/New-DfsnRoot.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dfsn/New-DfsnRoot.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
