### ISSUE TITLE
Name only accepts private subnets

### ISSUE THREAD

**Issue by audunmg** [MicrosoftDocs/windows-powershell-docs#1696]
Not sure if it's intentional, but the Name fails if I try to add a subnet which does not fall into the 10.0.0.0/8 or 192.168.0.0/16 ranges

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c142eb5-bb83-78ca-ff87-f64cf1c0d99b
* Version Independent ID: f91021d2-50f8-fa52-de1e-1f4f169788f8
* Content: [New-ADReplicationSubnet (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adreplicationsubnet?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/activedirectory/New-ADReplicationSubnet.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/activedirectory/New-ADReplicationSubnet.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@audunmg Hello,

Thank you for your feedback. 

I have just done a quick test and it seems to work for me.
![image](https://user-images.githubusercontent.com/10958657/82119310-faa84e00-9785-11ea-8cda-c9a1964db96f.png)
Could you give the PowerShell command that did not work for you?

**Comment by e0i** [comment]
Closing the issue as the discussion hasn't developed towards a resolution.

**Comment by e0i** [comment]
Closing the issue as the discussion hasn't developed towards a resolution.
