### ISSUE TITLE
Conflicting information for Network Category

### ISSUE THREAD

**Issue by trboomer** [MicrosoftDocs/windows-powershell-docs#1711]
acceptable values for this parameter are:

Public
Private

Type:	NetworkCategory
Accepted values:	Public, Private, DomainAuthenticated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 983029b7-7f55-a30a-b842-ef19a0f88e7c
* Version Independent ID: 253ace06-2925-2ca8-4cb3-30d167678bfd
* Content: [Set-NetConnectionProfile (netconnection)](https://docs.microsoft.com/en-us/powershell/module/netconnection/set-netconnectionprofile?view=win10-ps)
* Content Source: [docset/windows/netconnection/Set-NetConnectionProfile.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/netconnection/Set-NetConnectionProfile.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Closing via #1748
