### ISSUE TITLE
Reset all the information that was collected.

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windows-powershell-docs#1717]
It was missing a command that can be deleted as generated information. Like resetting all the information that was collected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b272698-ab7f-2f52-854d-f8bb9bef4031
* Version Independent ID: ca859312-75ff-b9bd-b1aa-1e462f492445
* Content: [systeminsights](https://docs.microsoft.com/en-us/powershell/module/systeminsights/?view=win10-ps)
* Content Source: [docset/windows/systeminsights/SystemInsights.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/systeminsights/SystemInsights.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **jgerend**

**Comment by e0i** [comment]
Hello, @gabrielluizbh 

Would you be able to clarify what needs to be updated in the documentation? Is the document misleading?

We would like to follow-up with content updates accordingly.

Thank you for providing feedback.
