### ISSUE TITLE
What is a DNS Server Virtulizatio Instance

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#1718]
This page should point to a description to a DNS Server Virtualization instance.
What is it?
How do I use it?
Why do I care?
I suspect this information exists but this page (and the pages describing the three related cmdlets) should be updated to point to this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce196ff9-7aa0-4e70-8995-d134a90a1840
* Version Independent ID: 592fd2b2-c1da-604a-ce3a-c9283325a112
* Content: [Get-DnsServerVirtualizationInstance (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsservervirtualizationinstance?view=win10-ps#feedback)
* Content Source: [docset/windows/dnsserver/Get-DnsServerVirtualizationInstance.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dnsserver/Get-DnsServerVirtualizationInstance.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@doctordns Hi Thomas,

Thanks for your feedback.

There is a brief description in the [Add-DnsServerVirtualizationInstance](https://docs.microsoft.com/powershell/module/dnsserver/add-dnsservervirtualizationinstance) article page. PowerShell documentation purpose is to show how to use the commands not explain in details the product/functionality.

**Comment by doctordns** [comment]
Those two sentences are a starting point.
But how about at least a reference to setting up, and using one?

Also - the example is somewhat unhelpful - what for example does 8231 even mean in business terms?  And what is 'Host' Tennant? It is not clear just what the result of this command is. Specifically what DNS queries are now possible and how does setting an instance to affect the DNS Server's resolution.  A before/after example showing how this command affects DNS resolution would be most helpful. 

Examples should help me to understand how I can apply this cmdlet into my arsenal. But the article offers no clue what the example is actually doing. In specific, what specifically happens when you ad one of these?

This page can be made better.

And if you do not want to provide the depth HERE, how about an about_DNSVirtualizationthat you can point to from here?

**Comment by spricer** [comment]
**doctordns** is correct here. There is no single article to suggest where this should be used, no example, no scenarios.
