### ISSUE TITLE
Update-Help fails to update 'Whea' module

### ISSUE THREAD

**Issue by kukucz** [MicrosoftDocs/windows-powershell-docs#172]
Windows Server 2016 v1607 Build 14393.2155

PS C:\Users\Administrator> update-help
update-help : Failed to update Help for the module(s) 'Whea' with UI culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI
culture en-US. Make sure the HelpInfoUri property in the module manifest is valid or check your network connection and then try the command
again.
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Comment by SergiuEnachi** [comment]
same on windows server 2012 v6.2.9200

**Comment by username-is-already-taken2** [comment]
+1 I'm using 2016 too

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
I think these questions are more suitable for support services, @yogkumgit can you kindly take over? Thanks

**Comment by yogkumgit** [comment]
@kukucz Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: 
https://docs.microsoft.com/powershell/#pivot=main&panel=community

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
