### ISSUE TITLE
Link "Outputs" directly to Microsoft.Web.Administration.ApplicationPool docs page

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/windows-powershell-docs#1721]
This would help people looking for ways to achieve functionality present in the older `WebAdministration` module, that is now encapsulated by the `ApplicationPool` class. For example, that module has a `Stop-WebAppPool "blah"` cmdlet that now essentially maps to [`(Get-IISAppPool -Name "blah").Stop()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.administration.applicationpool.stop).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea2e289-d548-6a5c-76c1-ba5492b10144
* Version Independent ID: bb663769-9975-8a51-096f-7af01034f583
* Content: [Get-IISAppPool (iisadministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisapppool?view=win10-ps)
* Content Source: [docset/windows/iisadministration/Get-IISAppPool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/iisadministration/Get-IISAppPool.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@IanKemp Hello Ian,

I have added a link to the WebAdministration module in the Related links sections.
