### ISSUE TITLE
Pipeline termination when using Select -First 1

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windows-powershell-docs#1722]
Let's do something simple, like grabbing a single node of our cluster:

 `Get-ClusterNode | Select -First 1`

You end up with the following pipeline errors:

```
Name        State Type
----        ----- ----
NODE-01     Up    Node
Get-ClusterNode : The pipeline has been stopped.
    + CategoryInfo          : NotSpecified: (:) [Get-ClusterNode], ClusterCmdletException
    + FullyQualifiedErrorId : Get-ClusterNode,Microsoft.FailoverClusters.PowerShell.GetNodeCommand
Get-ClusterNode : The pipeline has been stopped.
    + CategoryInfo          : NotSpecified: (:) [Get-ClusterNode], ClusterCmdletException
    + FullyQualifiedErrorId : Get-ClusterNode,Microsoft.FailoverClusters.PowerShell.GetNodeCommand
Get-ClusterNode : The pipeline has been stopped.
    + CategoryInfo          : NotSpecified: (:) [Get-ClusterNode], ClusterCmdletException
    + FullyQualifiedErrorId : Get-ClusterNode,Microsoft.FailoverClusters.PowerShell.GetNodeCommand
Get-ClusterNode : The pipeline has been stopped.
    + CategoryInfo          : NotSpecified: (:) [Get-ClusterNode], ClusterCmdletException
    + FullyQualifiedErrorId : Get-ClusterNode,Microsoft.FailoverClusters.PowerShell.GetNodeCommand
```

It appears that this is an issue with a lot of the Failover Clustering cmdlets. Try it with other FCM commands!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 480b7c0b-928c-9484-29cf-d17531f97ad6
* Version Independent ID: d19377b2-9a8f-f6c4-be9d-295e3a639da4
* Content: [Get-ClusterNode (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/get-clusternode?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/Get-ClusterNode.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/failoverclusters/Get-ClusterNode.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by eponerine** [comment]
It looks like if you wrap the Clustering cmdlets in parens, and then pipe, it works. This is still really horrible behavior.

**Comment by e0i** [comment]
It seems that this question can best be answered via [PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.

Thank you.
