### ISSUE TITLE
Broken Link - "WSUS Module"

### ISSUE THREAD

**Issue by NikTeslaNY** [MicrosoftDocs/windows-powershell-docs#1723]
You have a broken link in the Powershell docs.

From the page: 

    https://docs.microsoft.com/en-us/powershell/module/updateservices/?view=win10-ps

if you enter "wsus" in the search field on the left pane the first result is "wsus module". Clicking that gets a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abd96a6f-4148-6fef-f1d3-471681d27806
* Version Independent ID: 1aed4a27-e8ce-1715-17ad-a8914eb5f3c6
* Content: [UpdateServices](https://docs.microsoft.com/en-us/powershell/module/updateservices/?view=win10-ps#feedback)
* Content Source: [docset/windows/updateservices/UpdateServices.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/updateservices/UpdateServices.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@NikTeslaNY  Thank you for your feedback. We have modified the document accordingly.

Thanks
Sri
