### ISSUE TITLE
Link to  "Configurable Language and Cultural Settings" is broken.

### ISSUE THREAD

**Issue by taksis** [MicrosoftDocs/windows-powershell-docs#1728]
It links to http://go.microsoft.com/fwlink/?LinkID=242307, but content is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bcd6e9-7aee-ec93-4707-3207d0166ea6
* Version Independent ID: beb3e794-eaad-4f56-175c-73f07fc19a39
* Content: [Set-Culture (international)](https://docs.microsoft.com/en-us/powershell/module/international/Set-Culture?view=win10-ps#feedback)
* Content Source: [docset/windows/international/Set-Culture.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/international/Set-Culture.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Closing via #1860
