### ISSUE TITLE
Make it clear that logging off and back on / a reboot  is required for a change to take effect

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/windows-powershell-docs#1729]
Also worth noting that, while a change is pending, `Get-WinUILanguageOverride` reports the _pending_ value, not the _still effective_ one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7a3ba70-d892-e517-a985-e1809d03c516
* Version Independent ID: 9714d505-9681-61c2-b022-4529be823713
* Content: [Set-WinUILanguageOverride (international)](https://docs.microsoft.com/en-us/powershell/module/international/set-winuilanguageoverride?view=win10-ps)
* Content Source: [docset/windows/international/Set-WinUILanguageOverride.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/international/Set-WinUILanguageOverride.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by VLG17** [comment]
@mklement0 Thank you for spotting the missing step. I have created a request which adds this.

Regarding your second observation about "Get-WinUILanguageOverride", could you please open a new issue in [the article which contains that faulty information](https://docs.microsoft.com/en-us/powershell/module/international/get-winuilanguageoverride?view=win10-ps)?

**Comment by mklement0** [comment]
Thanks, @VLG17  - please see #1824

**Comment by e0i** [comment]
Closing via #1822. Thank you, all.
