### ISSUE TITLE
Import-CSV with Remove-DnsServerResourceRecord limited to 2  arguments

### ISSUE THREAD

**Issue by sjhloco** [MicrosoftDocs/windows-powershell-docs#1731]
When trying to use Import-CSV with Remove-DnsServerResourceRecord for bulk delete of records the number of values you can take from the CSV file is limited to only 2 arguments. Is this by design or a bug? Doing a similar thing using Import-CSV with Add-DnsServerResourceRecord you can use all the values from the CSV.

For example:

**The CSV file**
PS C:\Users\Administrator> Import-Csv -Path "C:\temp\temp_csv.csv"
ZoneName      Name       RRType
<rawtext>--------      ----       ------<rawtext>
stesworld.com computer43 A

**If I try to remove the record using the CSV it errors**
PS C:\Users\Administrator> Import-Csv -Path "C:\temp\temp_csv.csv" | Remove-DNSServerResourceRecord
Remove-DNSServerResourceRecord : The input object cannot be bound because it did not contain the information required to bind all mandatory
parameters:  InputObject
At line:1 char:43
<rawtext>+ ... ort-Csv -Path "C:\temp\temp_csv.csv" | Remove-DNSServerResourceRecord<rawtext>
<rawtext>+                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<rawtext>
   <rawtext> + CategoryInfo          : InvalidArgument: (@{ZoneName=stes...er43; RRType=A}:PSObject) [Remove-DnsServerResourceRecord], ParameterBindin
   gException<rawtext>
  <rawtext>  + FullyQualifiedErrorId : InputObjectMissingMandatory,Remove-DnsServerResourceRecord<rawtext>

All the arguments in the CSV are correct and in the correct format as if I run it and specific any of the arguments from the CSV as a flag it works fine:

**Specify ZoneName as a flag**
PS C:\Users\Administrator> Import-Csv -Path "C:\temp\temp_csv.csv" | Remove-DNSServerResourceRecord -ZoneName stesworld.com

Confirm
Removing DNS resource record set by name computer43 of type A from zone stesworld.com on DC1 server. Do you want to continue?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

**Specify Name as a flag**
PS C:\Users\Administrator> Import-Csv -Path "C:\temp\temp_csv.csv" | Remove-DNSServerResourceRecord -Name computer43

Confirm
Removing DNS resource record set by name computer43 of type A from zone stesworld.com on DC1 server. Do you want to continue?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

**Specify RRType as a flag**
PS C:\Users\Administrator> Import-Csv -Path "C:\temp\temp_csv.csv" | Remove-DNSServerResourceRecord -RRType A

Confirm
Removing DNS resource record set by name computer43 of type A from zone stesworld.com on DC1 server. Do you want to continue?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

**Comment by e0i** [comment]
For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.

Thank you.
