### ISSUE TITLE
The command is loading and loading forever without execution

### ISSUE THREAD

**Issue by ali-h2010** [MicrosoftDocs/windows-powershell-docs#1733]
It worked once and i got the package in all new users but when removed the pacakge provision and tried again, it's not applying the provision.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678cf8fb-4a65-3660-c818-b17e1490b703
* Version Independent ID: c7670040-daad-57f2-3dad-453210dcf35e
* Content: [Add-AppxProvisionedPackage (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/add-appxprovisionedpackage?view=win10-ps)
* Content Source: [docset/windows/dism/Add-AppxProvisionedPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dism/Add-AppxProvisionedPackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
