### ISSUE TITLE
Make it clear that this command requires a reboot to take effect

### ISSUE THREAD

**Issue by solvingj** [MicrosoftDocs/windows-powershell-docs#1738]
Initially this was going to be effectively a copy of this issue which exists for the Culture cmdlets: 
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1730

However, upon further examination, this issue is materially different.  There seems to be no way to perform `Set-WinSystemLocale` command and ever see a new value with  `Get-WinSystemLocale` without a reboot.  This should at least be documented as it's very confusing and unique behavior to this one setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7bfd66-3c04-14d3-7cb2-6fd4bbbf2347
* Version Independent ID: ca07c620-8910-59a6-500d-5c98dec9db36
* Content: [Set-WinSystemLocale (internationalcmdlets)](https://docs.microsoft.com/en-us/powershell/module/internationalcmdlets/set-winsystemlocale?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/internationalcmdlets/Set-WinSystemLocale.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/internationalcmdlets/Set-WinSystemLocale.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@solvingj  Thank you for your feedback. The cmdlet description is now added with a Note that "because this is a system setting, this can only be changed by a user with Administrator permissions, and changes do not take effect until the computer is restarted."

Hope this helps!

Thanks
Sri

**Comment by e0i** [comment]
@solvingj 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
