### ISSUE TITLE
Syntax section incomplete

### ISSUE THREAD

**Issue by jeffreymcclain** [MicrosoftDocs/windows-powershell-docs#1751]
The Syntax section is missing parameters defined in the Parameters section, specifically "AllUsers" and "PreserveApplicationData".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc0b0cd3-1201-f5e2-907e-5712eda675da
* Version Independent ID: b722fa48-0af3-27ea-9f86-4f48b9972d19
* Content: [Remove-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps#feedback)
* Content Source: [docset/windows/appx/Remove-AppxPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/appx/Remove-AppxPackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@jeffreymcclain  Thank you for your feedback. We have modified the doc via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1944

Thanks
Sri

**Comment by e0i** [comment]
Closing the issue via merged PR #1944. It might take a few days for changes to take effect online. Thank you.
