### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Taballe** [MicrosoftDocs/windows-powershell-docs#1756]
Hi,
You have a typo in example 3:
"Example 3: Turn on SMB singing and encryption".

I'm sure it's a great singer, but I think you want "signing" here.  ;)

Have a nice day,
Tania

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf1abaf-c268-b76f-48b5-5f5723fecb83
* Version Independent ID: 0c17d9d3-bbc4-f467-b44c-d78bb0c7e370
* Content: [Set-SmbServerConfiguration (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=win10-ps#feedback)
* Content Source: [docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/smbshare/Set-SmbServerConfiguration.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by doctordns** [comment]
Fixed in #1769 - thanks for the report
