### ISSUE TITLE
BootDevice has to be defined as VHD for a disk to be provisioned

### ISSUE THREAD

**Issue by AlBrough** [MicrosoftDocs/windows-powershell-docs#1757]
If -NewVHDPath parameter is specified when using the New-VM Cmdlet and -BootDevice is set to CD or NetworkAdapter no disk is provisioned. 
Using -BootDevice CD halts and errors out, -BootDevice NetworkAdapter creates the Virtual Machine but no disk is created or attached.
I would think that most cases of provisioning a VM that a disk would be required no matter which primary boot device is specified.

I know that the VM could be provisioned with whichever boot method and amended after the fact but this requires more lines of code which is superfluous.

**Comment by AlBrough** [comment]
also, if -BootDevice is set to CD is defined, the network controller is added as the boot device as there is no option to define a path to a CD/DVDDrive in New-VM Cmdlet

**Comment by velkovb** [comment]
@AlBrough Hello Al,

Thank you for your feedback.

I was not able to reproduce your issue. Could you share the OS version and PowerShell version that you are using?
Furthermore, the exact commands will be useful as well. 
For me with `-BootDevice NetworkAdapter` everything worked without any issues:
```powershell
PS C:\> New-VM -Name Test1 -NewVHDPath C:\VMs\test1.vhdx -NewVHDSizeBytes 40GB -MemoryStartupBytes 1GB -BootDevice NetworkAdapter -Generation 2
```
```output
Name  State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
----  ----- ----------- ----------------- ------   ------             -------
Test1 Off   0           0                 00:00:00 Operating normally 9.0
```
The VM and the VHD are created without any problems.
However, with `-BootDevice CD` for Generation 2 VMs, I got an error and the VM didn't create but the VHD did:
```powershell
PS C:\> New-VM -Name Test1 -NewVHDPath C:\VMs\test1.vhdx -NewVHDSizeBytes 40GB -MemoryStartupBytes 1GB -BootDevice CD -Generation 2                                                                                                  
```
```output
New-VM : Failed to add device 'Synthetic Disk Drive'.                                                                   Cannot attach storage media to the controller because the specified location is in use.                                 'Test1' failed to add device 'Synthetic Disk Drive'. (Virtual machine ID 150990F6-3252-45D7-BE42-D38961E2A94A)          'Test1': Cannot attach storage media to the controller because the specified location is in use. (Virtual machine ID 15 0990F6-3252-45D7-BE42-D38961E2A94A)
At line:1 char:1
+ New-VM -Name Test1 -NewVHDPath C:\VMs\test1.vhdx -NewVHDSizeBytes 40G ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidState,Microsoft.HyperV.PowerShell.Commands.NewVM
```

When I tried Generation 1 VM, it worked with CD:
```powershell
PS C:\Users\gosho> New-VM -Name Test1 -NewVHDPath C:\VMs\test1.vhdx -NewVHDSizeBytes 40GB -MemoryStartupBytes 1GB -BootDevice CD -Generation 1
```
```output
Name  State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
----  ----- ----------- ----------------- ------   ------             -------
Test1 Off   0           0                 00:00:00 Operating normally 9.0
```

It think the combination `-BootDevice CD` and `-Generation 2` is failing because the cmdlet is trying to attach the CD drive to an IDE controller which is not present in Gen 2 VMs.
