### ISSUE TITLE
x86 compatilibity.

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/windows-powershell-docs#1758]
Please put a note that this module is 64bit only. It will not work on x86 or ARM in emulation on the pro x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2967e3-e716-36ce-58b7-eb0ffc873bf0
* Version Independent ID: 2ec65e0d-cdaf-5084-d693-067b1a76aec3
* Content: [Get-NetConnectionProfile (netconnection)](https://docs.microsoft.com/en-us/powershell/module/netconnection/get-netconnectionprofile?view=win10-ps#feedback)
* Content Source: [docset/windows/netconnection/Get-NetConnectionProfile.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/netconnection/Get-NetConnectionProfile.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@stephenc01 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1941

Thanks
Sri

**Comment by e0i** [comment]
@stephenc01 In the reviewer's investigation, It has been found that supplementing the suggested changes would not be necessary. Thank you for providing feedback.
