### ISSUE TITLE
Example is wrong

### ISSUE THREAD

**Issue by TNwestpointtg** [MicrosoftDocs/windows-powershell-docs#176]
The example uses the wrong parameter -ScriptDestinationFolder should be -DestinationFolder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a51e1f-cc0a-aa4d-098d-0f0540ebc04f
* Version Independent ID: ad4bcc6a-ff95-cb51-2fb4-8140ba09f5ab
* Content: [Export-AdfsDeploymentSQLScript (adfs)](https://docs.microsoft.com/en-us/powershell/module/adfs/export-adfsdeploymentsqlscript?view=win10-ps)
* Content Source: [docset/windows/adfs/export-adfsdeploymentsqlscript.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/export-adfsdeploymentsqlscript.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@TNwestpointtg  With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
