### ISSUE TITLE
Need link to Microsoft.HyperV.PowerShell.VirtualMachine

### ISSUE THREAD

**Issue by RichardMeadowsTC** [MicrosoftDocs/windows-powershell-docs#1762]
I need to know what can be done with Microsoft.HyperV.PowerShell.VirtualMachine.  Where  is the documentation for it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3bf152-630f-3a0a-b309-929b0899a637
* Version Independent ID: 6b16356b-f935-5497-5c28-0a9d71a1fb51
* Content: [Get-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/get-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/Get-VM.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/hyper-v/Get-VM.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by doctordns** [comment]
This object is returned from Get-VM. You can find details about what it contains by using Get-Member, like this:L
```powershell
Get-VM * | Select-Object -First 1 | Get-Member
```

What else do you need to know?

**Comment by RichardMeadowsTC** [comment]
Every thing I need to know, I learn from debugger.  I should not have to debug the code. Please get some real documentation.

Richard Meadows

**Comment by doctordns** [comment]
The open-source documentation repo does a good job of documenting cmdlets as well as the objects within the .NET Framework and used by PowerShell. So if you want to find out more about the two object types emitted by Get-ChildItem, easy. 

Other cmdlets, implemented by CDXML, return  'WMI objects' - a .net object which wraps the WMI Data. For those cmdlets, WMI documentation is reasonable albeit focused at the developer, not the IT Pro.

In your case, the object type is produced by the Hyper-V product team whose objects do not appear to have details documented explicitly. When you do need to use them (eg setting nested virtualization) there are details on how to do it. 

With that said, I agree that It would be useful to have all the Hyper-V object types explicitly documented.  But any detailed documentation would likely require product team input. 

This page, though, is not where to fix this issue. Separate documentation is needed to solve the problem.  I suggest _this_ issue be closed and a new one opened along the lines of "Hyper-V Objects Need Documentation" and set out the specific object types that need to be documented.

**Comment by RichardMeadowsTC** [comment]
This page isn’t documentation for Get-VM? I expect and demand that it document what it is returning.

Richard Meadows

**Comment by doctordns** [comment]
This page documents one cmdlet. You would need separate pages to document the individual objects across this module. Such documentation would need to come from the Hyper-V team and not the open source MS Docs team since the code is not open source. 

This issue should be closed and a new one opened to document the objects. There are quite a few so this is not a small ask. 

FWIW I am currently writing a book chapter about these cmdlets and I too would like these objects defined. But there are better ways of achieving it. Are you interested in helping?

And finally, this is an open source project. Demanding it do things is hardly ever likely to be helpful.

**Comment by RichardMeadowsTC** [comment]
Where is Microsoft.  Have the died?

Richard Meadows

**Comment by doctordns** [comment]
I have opened a new issue for this. 

See: #1776

THIS issue (#1762) should be closed.

**Comment by AriFordsham** [comment]
> this is an open source project

So Microsoft are turning to open source to document their commercial products?

**Comment by doctordns** [comment]
The documentation at docs.microsoft, and more recently learn.microsoft.com are indeed open-source projects. This allows the community to fix minor issues or make small improvements. I have issued a lot of PRs to fix grammar and spelling issues, add examples, and clarify the behaviour of PowerShell components. This makes a lot of sense to me!
