### ISSUE TITLE
Bad info

### ISSUE THREAD

**Issue by joel74** [MicrosoftDocs/windows-powershell-docs#1763]
This page references a nonexistent cmdlet in its one example: Get-MsmqMessage. Terrible

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c2ea23-dc65-80d3-7cc1-d1fc61e0954f
* Version Independent ID: ba1410a2-4359-0ae7-32e1-e4dcdf255d5d
* Content: [Receive-MsmqQueue (msmq)](https://docs.microsoft.com/en-us/powershell/module/msmq/receive-msmqqueue?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/msmq/Receive-MsmqQueue.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/msmq/Receive-MsmqQueue.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@joel74 An independent contributor will soon be able to follow-up with a clarification regarding your question. Thank you for providing feedback.

**Comment by e0i** [comment]
Closing via #1821
