### ISSUE TITLE
Replace and Nulls

### ISSUE THREAD

**Issue by bmcmcm** [MicrosoftDocs/windows-powershell-docs#1764]
It's worth noting that Set-ADUser with a replace operation will generate an error if any of the properties to update are being updated will a null. An error will be generated and the command will fail even if several properties to be updated have values. For example, if $CSV.desc = null and $CSV.dept = "D602",  the following will fail with an ADInvalidOperationException:

$account | Set-ADUser -Replace @{department=$($CSV.dept);description=$($CSV.desc)} -Credential $cred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8918842f-aade-158a-b4bc-6b78cf9baf6b
* Version Independent ID: 4ea95b5f-9e2a-8ab2-95b6-3d8524b712e3
* Content: [Set-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/Set-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsadministration/Set-ADUser.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by PChipVIA** [comment]
Workaround if I may in your case would be to use splatting and replace the CSV headers.  You could then generate the command dynamically.  Haven't tested but would look like:

$CSVData = Import-CSV myfile.csv -Header "SAMAccountName","Department","Description","Office","EmployeeNumber"

ForEach ($CSV in $CSVData) {
    $SetADUserSplat = $ReplaceHash = @{}
    $ClearHash = @()
    ForEach ($Property in $CSV | Get-Member | ? MemberType -eq NoteProperty | ? Name -ne SAMAccountName | Select -ExpandProperty Name) {
        If ([string]::IsNullOrEmpty($CSV."$Property")) {
            $ClearHash += $Property
        } else {
            $ReplaceHash.Add($Property,$CSV."$Property")
        }
    }
    if ( ($ClearHash | Measure).Count -gt 0 ) { $SetADUserSplat.Add('Clear',($ClearHash -join ',')) }
    if ( ($ReplaceHash | Measure).Count -gt 0 ) { $SetADUserSplat.Add('Replace',$ReplaceHash) }
    $SetADUserSplat.Add('Identity',$CSV.SamAccountName)

    Set-ADUser @SetADUserSplat
}

**Comment by velkovb** [comment]
@bmcmcm Hello,

Thank you for your feedback.

I have tested this and it seems to be the same for all operations - _Replace_, _Remove_, _Add_. The solution proposed by @PChipVIA is a good one and I guess the general idea is you could verify the values before you pass to the **Set-ADUser** cmdlet. I will update the article to include the information.
