### ISSUE TITLE
How to see the full InstanceId?

### ISSUE THREAD

**Issue by colossusb** [MicrosoftDocs/windows-powershell-docs#1765]
How to see the full InstanceId?

Also, why is there no --help -h command? 

Surely this is a common standard scross command line apps? 

How else can the user work out what to do? (assuming they have no internet access)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7100f632-3c9c-34ab-174c-bb698b9f8072
* Version Independent ID: e6f3da0c-5da8-4d5b-56ca-f1d195649494
* Content: [Get-PnpDevice (pnpdevice)](https://docs.microsoft.com/en-us/powershell/module/pnpdevice/get-pnpdevice?view=win10-ps#feedback)
* Content Source: [docset/windows/pnpdevice/Get-PnpDevice.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/pnpdevice/Get-PnpDevice.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@colossub   . You can get help commands by typing  
**help Get-PnpDevice**   in powershell with administrator
