### ISSUE TITLE
Unable to suppress Format-Volume confirmation dialog ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/windows-powershell-docs#1767]
Hello,

Can an example be supplied that shows how to suppress the Format-Volume "Confirmation" dialog?  

I have tried several combinations using -Confirm:$false, -Force, etc. and in all cases, the Windows Format Volume confirmation dialog always appears and remains until dismissed manually.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e25c556-9b12-fd52-b83b-8d4adb0a0fd9
* Version Independent ID: 206ed939-b414-f831-849e-dcbbac2b78c0
* Content: [Format-Volume (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=win10-ps#feedback)
* Content Source: [docset/windows/storage/Format-Volume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/storage/Format-Volume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@bdcoder2 Hello,

Thank you for your feedback.

Surprisingly I am seeing the exact opposite of the behaviour you are describing. I cannot make it confirm before formatting the volume. Could you share the OS version and PowerShell version that you are using?

Thanks.

**Comment by bdcoder2** [comment]
@velkovb - OS version and PowerShell version:

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363

$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  752   
```

**Comment by velkovb** [comment]
![image](https://user-images.githubusercontent.com/10958657/81604167-27501480-93d8-11ea-9f4f-ecea7e517678.png)
I still cannot reproduce. 
- What is the output of your $ConfirmPreference variable? 
- Are you trying to run it on a boot partition?

**Comment by bdcoder2** [comment]
@velkovb - Apologies, it has been a while and I looked back in my notes - when I reported this issue, I was trying to format data disks on an Azure VM - so the Powershell version and OS version would have been different from what I reported in my previous reply (which was from my workstation).

From my notes the Azure VM created was:

```
vm_publisher_name = "MicrosoftWindowsServer"
vm_offer = "WindowsServer"
vm_sku = "2019-datacenter-gensecond"
vm_size = "Standard_DS2_v2"
vm_image_version = "latest"
```
Both data disks were 128 GB in size and the disk config params were:
```
         $disk_config = New-AzDiskConfig `
                        -SkuName "Premium_LRS" `
                        -OsType Windows `
                        -DiskSizeGB 128 `
                        -Location Canada `
                        -CreateOption Empty `
                        -ErrorAction Stop
```
The script I was using to initialize, partition and format the disks was:
```

<#
 Use letters F through Y for disk drive letters, because:
 C - Is used for OS disk
 D - Is used for a temp disk
 E - Is typically used/allocated to the CD-ROM
#>
$drive_letters = 70..89 | ForEach-Object { [char]$_ }

<#
 Get uninitialized disks, exit if none found.
 If the disk has recently just become present on the server, it will 
 be in a RAW partition style state ...
#>

$disk_list = Get-Disk | Where partitionstyle -eq 'RAW' | sort number

if ( $disk_list -eq $null )
{

   Write-Output "No RAW disks were found"

   Break

}


Write-Output "Preparing Disks:"

$count = 0

Try
{
    
   foreach ( $disk in $disk_list )
   {

      $drive_letter = $drive_letters[ $count ].ToString()

      Write-Output "Drive Letter: $drive_letter"

      Write-Output "- Initialize ..."

      Initialize-Disk -Number $disk.Number -PartitionStyle MBR | Out-null

      Write-Output "- Partition ..."

      New-Partition -DiskNumber $disk.Number -UseMaximumSize -DriveLetter $drive_letter | Out-null

      Write-Output "- Formatting ..."

      Format-Volume -DriveLetter $drive_letter -FileSystem NTFS -NewFileSystemLabel $drive_letter -Force | Out-null

      #
      # Create a temp directory on the drive ...
      #

      Write-Output "- Creating temp directory ..."

      $path = $drive_letter + ":\temp"

      New-Item -ItemType Directory -Force -Path $path | Out-Null

      Write-Output "- Done"

      $count++

   }

}
Catch
{

   Write-Output ( "* ERROR: " + $_.Exception.ToString() )

   Break

}

```
The script would execute just fine, but there would always be a Format-Volume confirmation dialog left open AFTER the script ran.

Again, apologies - I should have included all of the above in my original post, but was pressed for time and assumed it was just a Powershell issue -- perhaps the issue is more related to Powershell on Azure VM's?

**Comment by velkovb** [comment]
@bdcoder2 Hi,

Thanks for the detailed response. I think I know what you mean now, I have encountered similar thing in AWS. Do you refer to the following prompt?
![image](https://user-images.githubusercontent.com/10958657/81781632-1d760080-9501-11ea-920c-f36ca04d508e.png)
If so that is not from PowerShell at all. This is when you bring online an uninitialized disk.

**Comment by bdcoder2** [comment]
@velkovb - Correct !   Confirmation dialogs seem to be left "hanging" after the powershell script runs.

**Comment by e0i** [comment]
Closing as it seems the situation has come out in the clear. Thank you for the discussion.

**Comment by bdcoder2** [comment]
@e0i - Closed? - So no solution available?

**Comment by e0i** [comment]
Closing because the dialog in question does not surface from PowerShell and thus providing a related example within the article would be out of scope. See:

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1767#issuecomment-627790968

**Comment by bdcoder2** [comment]
Thanks for clarifying !
