### ISSUE TITLE
How to list iscsi active connections on Windows 2008 R2 

### ISSUE THREAD

**Issue by rajeshr988** [MicrosoftDocs/windows-powershell-docs#177]
Os windows 2008 R2

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @rajeshr988 
This is for creating issues with current articles, is there any issue with any article that you stumbled upon? if so, can you kindly provide it?
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution. @rajeshr988 hope there is no update required in this article. If you see there is a need to update the article please reopen the issue with specific inputs. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
