### ISSUE TITLE
PowerShell fwlink doesn't get here

### ISSUE THREAD

**Issue by vitahall** [MicrosoftDocs/windows-powershell-docs#1775]
On a Server 2019 machine without help installed, PowerShell gives "http://go.microsoft.com/fwlink/?LinkID=241952" as the link to open the web-based help. That link redirects to "http://technet.microsoft.comlibrary/jj635706(v=wps.620).aspx", which fails because there's no slash between "technet.microsoft.com" and "library". If you insert the slash, you then get redirected to docs.microsoft.com and end up here (at "https://docs.microsoft.com/en-us/powershell/module/smbshare/get-smbsession" as of this writing).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb8c019c-3fd2-c11e-0477-96dcd4ad8848
* Version Independent ID: db6f3479-388b-da9b-7149-f2439f66aebe
* Content: [Get-SmbSession (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/get-smbsession?view=winserver2012-ps&redirectedfrom=MSDN#feedback)
* Content Source: [docset/winserver2012-ps/smbshare/Get-SmbSession.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/smbshare/Get-SmbSession.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sdwheeler** [comment]
I updated the FWLinks to point to the correct location on docs.microsoft.com
