### ISSUE TITLE
Remove vs Clear

### ISSUE THREAD

**Issue by PChipVIA** [MicrosoftDocs/windows-powershell-docs#1777]
It's not clear when to use -Remove vs when to use -Clear.  I would assume that -Remove is useful for multi-valued properties to remove 1+ out of many while -Clear will empty out the attribute entirely?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8918842f-aade-158a-b4bc-6b78cf9baf6b
* Version Independent ID: 4ea95b5f-9e2a-8ab2-95b6-3d8524b712e3
* Content: [Set-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/Set-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsadministration/Set-ADUser.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@PChipVIA Thank you for your feedback. We have added a note to the document about Clear and Remove via PR# https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1943

 The Difference between  -Clear and -remove is that -Clear Completely removes all data within an attribute. You can use -Remove to remove a value from a multivalued attribute, Such as removing a single Phone number without affecting other items in the list.

Hope this Helps!

Thanks
Sri
