### ISSUE TITLE
What version of Powershell required

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/windows-powershell-docs#1778]
Running Windows 10 build 1903 with Active Directory module, I get:
The term 'Get-DhcpServer4Lease' is not recognized as the name of a cmdlet, function, script file, or operable 
program.
Get-Module shows:
Manifest   2.0.0.0    DhcpServer 
It would be nice if the actual requirements for this cmdlet were given.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c852fd-4ae4-381f-6064-a9ae25d1b6d7
* Version Independent ID: b7bb4c06-591f-acec-8fc2-af671f6b9a72
* Content: [Get-DhcpServerv4Lease (dhcpserver)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4lease?view=win10-ps#feedback)
* Content Source: [docset/windows/dhcpserver/Get-DhcpServerv4Lease.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dhcpserver/Get-DhcpServerv4Lease.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by doctordns** [comment]
The command is actually **Get-DhcpServerv4Lease**.

Get-Module gets basic details of the modules. You need to use Get-Command to get the commands in a given module.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
