### ISSUE TITLE
Need link to Output Object Model

### ISSUE THREAD

**Issue by DavidBerg-MSFT** [MicrosoftDocs/windows-powershell-docs#178]
The output documentation should include a link to the definition of the output object model, so we can see what properties it has.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01bff7f4-2d2b-06d8-15c3-b09e78172a69
* Version Independent ID: 227d0fed-5ba9-be92-e275-b3442cbeb165
* Content: [Get-VirtualDisk (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-virtualdisk?view=win10-ps#outputs)
* Content Source: [docset/windows/storage/get-virtualdisk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-virtualdisk.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @DavidBerg-MSFT thanks for your suggestion.
I will suggest thru a PR to update the article with this information.

**Comment by DavidBerg-MSFT** [comment]
Thanks.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @DavidBerg-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
