### ISSUE TITLE
Missing full working example

### ISSUE THREAD

**Issue by matdavis2121** [MicrosoftDocs/windows-powershell-docs#1780]
In order for the IIS drive to be visible / accessible / intellisense-ed, it needs to be imported using the
Import-Module Webadministration PSCommand

In order to get the path itself, you can either pipe the output to
Get-WebFilePath 'IIS:\Sites\Default Web Site' | Select-Object {$_.FullName}

Or assign the output of Get-WebFilePath to a variable, $myPath, then qualify it with, $myPath.FullName

Any corrections, please let me know.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8661b42-579a-396a-d7d0-425d9cb11e4e
* Version Independent ID: 9c401335-f7be-699b-57ba-e2218a9caa7c
* Content: [Get-WebFilePath (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/get-webfilepath?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/webadminstration/Get-WebFilePath.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/webadminstration/Get-WebFilePath.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@matdavis2121 Hello,

Thank you for trying to make MicrosoftDocs a better place.

I am afraid I do not fully understand the issue. What you have described is the normal behaviour even for the Get-Item cmdlet. However, on my test machine I was able to get intellisense even without importing the module in advance.

What PowerShell version are you using?

**Comment by matdavis2121** [comment]
Hi Velkovb.
Thanks for your reply.

1. Suggestion
Mentioning you may need to install the webadministration module if the IIS drive isn't showing

2. PSVersion - PSVersion: 5.1.18362.752
Even for the request above, I learned how to find my ps version previously from googling but I think it's important to not assume I know how to do something, like assume I don't know how to find the version of powershell I'm using so you could tell me how. Otherwise, I'd have to google how to find the version of powershell I'm using.

**Comment by velkovb** [comment]
Hi,

Apologies for not sharing the info about PSVersion. What about the windows OS version?

From my tests it intellisense works without importing the module even on PowerShell 3.0. Regarding the installation, the webadministation module is installed together with IIS, you cannot install it separately.

**Comment by matdavis2121** [comment]
OS VERSION = Windows 10

No prob at all on the $PSVersiontable command. There's so much to powershell so I think it's on Microsoft as a teacher and on me as a student to really cover those basics as much as we can. You know now a days though that the pattern is more so, I want to do this, let me google it, then try it, then google and repeat until I get it to work.
-
_"From my tests it intellisense works without importing the module even on PowerShell 3.0. Regarding the installation, the webadministation module is installed together with IIS, you cannot install it separately."_
-
I think that this has something to do with the powershell session itself. There have definitely been times when the reference to the PSDrive throws an error and importing the module solves the issue for me.

I'm using the powershell ISE so that may be where we are differing? Many modules can be imported from what I can tell. Running the Import-Module Webadministration has worked for me multiple times

**Comment by velkovb** [comment]
Thank you for the detailed response.

PowerShell ISE and console behave differently sometimes, indeed. I remember in the past that when running scripts I have had a similar issue and had to explicitly import the module in the beginning of the script. 

Just tried it on my Win10 machine using PowerShell ISE and it works. Might be some issue that go fixed along the way, cannot really say.

P.S. Maybe a faster way to get the path:
`(Get-WebFilePath 'IIS:\Sites\Default Web Site').FullName`

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. 

Thank you for the discussion.
