### ISSUE TITLE
SMB Server Announcement Comments Appear Not to Work in Server 2019

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#1781]
I set SMB Server announcements like this:

```powershell
# 6. Turn on Sserver announcements
$SHT3 = @{
    ServerHidden   = $false
    AnnounceServer = $true
    Confirm        = $false
    AnnounceComment = "Have A Nice Day!"
}
Set-SmbServerConfiguration @SHT3
```

However, the *AnnounceComment* is not transmitted in the SMB Announce packet. You can see this in the screen shot which  I posted to Pastebin:
https://imagebin.ca/v/5CdFrkN8wrus

This document should note
1. The announcement message is not set propertly in the SMB packet
2. The purpose of these announcements (ie to populate the Master Browse and Domain Master Browser so as to populate MY Network NeighborHood).a
As you can see, the announcements are made, but the comment is not present.

This page should noce that despite setting a comment, no comment appears in the SMB Packets.
It would also be useful to clarify the purpose of announcements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf1abaf-c268-b76f-48b5-5f5723fecb83
* Version Independent ID: 0c17d9d3-bbc4-f467-b44c-d78bb0c7e370
* Content: [Set-SmbServerConfiguration (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=win10-ps#feedback)
* Content Source: [docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/smbshare/Set-SmbServerConfiguration.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@doctordns 

Thank you for your ongoing involvement with the repository to improve the documentation.

Currently, the content in this repository does not cover Server 2019 topics, and it would perhaps be a better idea to  check with PowerShell community for your problem via the link below,

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thanks again.
