### ISSUE TITLE
Get-WebApplication cmdlet not working (webadministration module)

### ISSUE THREAD

**Issue by RomBrz** [MicrosoftDocs/windows-powershell-docs#1784]
The Get-WebApplication cmdlet don't work.. I tried everything i could here, but always give me an empty answer.
For example:

$AppPool = 'DefaultAppPool'
Get-WebApplication -name $AppPool

give an empty answer... the Get-WebApplication alone give empty answer too.

I don't know if something changed recently, but it's strange that today a script that i made some time ago didn't work (and the last time i used it, used to work).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72263164-a877-cd1d-6956-80984bfb7707
* Version Independent ID: bdadb496-3c7b-9e26-5489-3efd21a8bae7
* Content: [Get-WebApplication (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/Get-WebApplication?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/Get-WebApplication.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/webadminstration/Get-WebApplication.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@RomBrz 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
