### ISSUE TITLE
Invalid parameter list for Windows 2012 R2 Powershell

### ISSUE THREAD

**Issue by fernis** [MicrosoftDocs/windows-powershell-docs#1788]
There is no OwningProcess parameter or output in Windows 2012 R2 Powershell, even with WMF 5.1.  The documentation of this commandlet is erronously the same as for Windows Server 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a05bc83-3fe9-2f49-f476-463c5196bd3d
* Version Independent ID: 328b5f52-a72a-25e1-62c1-5ddf72182ec4
* Content: [Get-NetTCPConnection (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/get-nettcpconnection?view=winserver2012r2-ps#feedback)
* Content Source: [docset/winserver2012r2-ps/nettcpip/Get-NetTCPConnection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012r2-ps/nettcpip/Get-NetTCPConnection.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @fernis 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by msbemba** [comment]
@fernis Thank you for your feedback. The output from Get-NetTcpConnection does have an OwningProcess property, but it only lists the PID. I have added an example Via PR# https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1870 on the parameter usage.

Hope this helps.

Thanks
Sri

**Comment by e0i** [comment]
Closing via merged commit #1870.
