### ISSUE TITLE
certificateValidationMode when LDAPSigning is Turned On

### ISSUE THREAD

**Issue by vishalmasih** [MicrosoftDocs/windows-powershell-docs#1789]
There is no documentation on how to set the certificateValidationMode when LDAP Signing is turned on. So Get-ASUser is failing with the following error:
_Get-ADUser : The X.509 certificate *********** chain building failed. The certificate that was used has a trust chain that cannot be  verified. Replace the certificate or change the certificateValidationMode. A certificate chain could not be built to a trusted root authority._

**Comment by e0i** [comment]
@vishalmasih 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by vishalmasih** [comment]
This was a certificate trust issue and has been resolved. Apologies for the false alarm.
