### ISSUE TITLE
can't remove network printers

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#179]
remove-printer can't remove printers created with 'add-printer -connectionname \\\\server\printer'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba92300d-c4a2-207e-90d4-dc7883dbb901
* Version Independent ID: 3450990c-ce0b-7c0b-da93-6085485afd2b
* Content: [Remove-Printer (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/remove-printer?view=win10-ps)
* Content Source: [docset/windows/printmanagement/remove-printer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/printmanagement/remove-printer.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@jszabo98 Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: 
https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
