### ISSUE TITLE
Clarify where to run this command

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#1793]
If I have two servers I am managing (HV1 and HV2) and I want to enable VM Migration _from_ HV1 _to_ HV2, what do I need to specify? I'd like to see an example showing this scenairo,.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b413ab11-edbf-2844-3e95-2a84db86afa1
* Version Independent ID: 2ff8694d-2bd3-b0c9-a280-654f430e0574
* Content: [Enable-VMMigration (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmmigration?view=win10-ps#feedback)
* Content Source: [docset/windows/hyper-v/Enable-VMMigration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/hyper-v/Enable-VMMigration.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@doctordns 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by msbemba** [comment]
@doctordns  Thank you for your feedback. We have added an example on how to enable the Host for migration via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1871

Thanks
Sri

**Comment by e0i** [comment]
> @doctordns Thank you for your feedback. We have added an example on how to enable the Host for migration via PR##1871
> 
> Thanks
> Sri

Closing via contributor's PR, thank you.
