### ISSUE TITLE
Please include option to see AppLocker policies configured via CSP

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/windows-powershell-docs#1794]
This commandlet is relying on policy (either local or via GPO). Another option to set AppLocker settings is via Configuration Service Provider (CSP) - please add viewing the settings set via CSP as an option.

Thanks in advance,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b60297e-1e65-c5a3-5b47-d67a56ca552f
* Version Independent ID: e8f885d5-683e-c781-eedf-624314be984a
* Content: [Get-AppLockerPolicy (applocker)](https://docs.microsoft.com/en-us/powershell/module/applocker/get-applockerpolicy?view=win10-ps)
* Content Source: [docset/windows/applocker/Get-AppLockerPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/applocker/Get-AppLockerPolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issue tracker of this repository is intended for product documentation issues.

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thank you.
