### ISSUE TITLE
Dead link: Configurable Language and Cultural Settings

### ISSUE THREAD

**Issue by Function-10** [MicrosoftDocs/windows-powershell-docs#1795]
Please provide an up to date link for the text "Configurable Language and Cultural Settings".

The current link is http://go.microsoft.com/fwlink/?LinkID=242307 which redirects to https://msdn.microsoft.com/Areas/Epx/Content/500.aspx?aspxerrorpath=/en-us/globalization/mt662310 and shows an error of "Unable to Service Request"

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a11678-87ce-8ea5-7576-e20bd620c483
* Version Independent ID: d0ffa193-0023-d5b8-8c08-8ba2b3d43219
* Content: [Set-WinUserLanguageList (international)](https://docs.microsoft.com/en-us/powershell/module/international/set-winuserlanguagelist?view=win10-ps&source=docs#feedback)
* Content Source: [docset/windows/international/Set-WinUserLanguageList.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/international/Set-WinUserLanguageList.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Closing via #1860
