### ISSUE TITLE
It is not practical

### ISSUE THREAD

**Issue by sergioPerez-e** [MicrosoftDocs/windows-powershell-docs#1796]
Missing examples of use, combinations with other instructions and often do not show the unit of the result of a command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e73e02c-6320-8ebc-5bea-5cf288340ede
* Version Independent ID: 201b54ab-7995-f51c-df21-34c0b48de098
* Content: [New-Partition (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/new-partition?view=win10-ps)
* Content Source: [docset/windows/storage/New-Partition.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/storage/New-Partition.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@sergioPerez-e 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.
