### ISSUE TITLE
How can I get a list of dfsn folder targets in my network?

### ISSUE THREAD

**Issue by deftclaw** [MicrosoftDocs/windows-powershell-docs#1803]
"You can specify a DFS namespace folder path to see all the targets for that path." 

However:
"PS C:\> get-dfsnroot
Path                             Type      Properties   TimeToLiveSec State  Description
----                             ----      ----------   ------------- -----  -----------
\\domain.name\Accepted$        ********** Site Costing 300           Online

PS C:\> get-dfsnFolderTarget -path \\domain.name\Accepted$
get-dfsnfoldertarget : Path "\\domain.name\Accepted$" is invalid namespace folder path. Namespace
folder path should be in format: [...] \\domain\share\folder... for domain namespaces."
[...]* I cut the part of the error text about local server for brevity
*** Truncated irrelevant/potentially sensitive data
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ba40c7a-ebf4-b471-24b2-2e04496e0f0d
* Version Independent ID: 2afd8487-734f-949d-0d8e-8d6a13c41797
* Content: [Get-DfsnFolderTarget (dfsn)](https://docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnfoldertarget?view=win10-ps#feedback)
* Content Source: [docset/windows/dfsn/Get-DfsnFolderTarget.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dfsn/Get-DfsnFolderTarget.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@deftclaw 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
