### ISSUE TITLE
Windows-compliant firmware update process

### ISSUE THREAD

**Issue by TYChrisLi** [MicrosoftDocs/windows-powershell-docs#1805]
[Enter feedback here]
Dear Sirs,

  Could anybody tell me what's the conditions for Windows-compliant firmware update process for SATA SSD?
  Thanks a lot.

Best Regards,

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88615396-8c69-9e99-4d9d-0776d8c3f055
* Version Independent ID: 687124ec-21db-97a4-0917-e9d8eba63c94
* Content: [Get-StorageFirmwareInformation (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-storagefirmwareinformation?view=win10-ps)
* Content Source: [docset/windows/storage/Get-StorageFirmwareInformation.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/storage/Get-StorageFirmwareInformation.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@TYChrisLi 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
