### ISSUE TITLE
Support for CAA?

### ISSUE THREAD

**Issue by ildjarnisdead** [MicrosoftDocs/windows-powershell-docs#1806]
Will there be support for CAA records in the near future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014fb5df-2480-2136-1257-2aade82e4c4a
* Version Independent ID: 38c0b3be-3aa8-7926-716c-aa28367d6df7
* Content: [Resolve-DnsName (dnsclient)](https://docs.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname?view=win10-ps)
* Content Source: [docset/windows/dnsclient/Resolve-DnsName.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dnsclient/Resolve-DnsName.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/PowerShell/PowerShell/issues/6076> requests implementing `Resolve-DnsName` for PowerShell on non-Windows operating systems and suggests using the DnsClient.NET library, which already [supports CAA records](https://dnsclient.michaco.net/docs/DnsClient.Protocol.CaaRecord.html).

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
