### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DaviidLeMaster** [MicrosoftDocs/windows-powershell-docs#1808]
There is a typo on line "TpmPresent. Whether there is a TMP on the current computer."
Should say "Where there is a TPM on the current computer."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 980e3da2-eab1-e85f-ec2e-c0243a7e1f0d
* Version Independent ID: 43b2fb3e-f339-e9a2-8155-05d99d1e38f7
* Content: [Enable-TpmAutoProvisioning (trustedplatformmodule)](https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/enable-tpmautoprovisioning?view=win10-ps#feedback)
* Content Source: [docset/windows/trustedplatformmodule/Enable-TpmAutoProvisioning.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/trustedplatformmodule/Enable-TpmAutoProvisioning.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Closing via #1816 

@DaviidLeMaster Thank you for providing feedback.
