### ISSUE TITLE
Documentation on -Perfmon option should be added to Set-VMProcessor help

### ISSUE THREAD

**Issue by LongJohnCoder** [MicrosoftDocs/windows-powershell-docs#1809]
Documentation on -Perfmon option should be added. ( https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/performance-monitoring-hardware )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 476ea856-4da3-298b-9fd7-2aaf22935d62
* Version Independent ID: 4163eaf5-0adf-50b2-40c4-e357a5db7671
* Content: [Set-VMProcessor (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmprocessor?view=win10-ps)
* Content Source: [docset/windows/hyper-v/Set-VMProcessor.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/hyper-v/Set-VMProcessor.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @LongJohnCoder 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by msbemba** [comment]
@LongJohnCoder Thank you for your feedback. We cannot add this is a parameter to the document as this is generic for all processors. However, I have added a tip on how to enable performance monitor on intel processors and use the switch via PR# https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/performance-monitoring-hardware

Thanks 
Sri

**Comment by e0i** [comment]
@LongJohnCoder The content has been updated in the light of your feedback, thank you.
