### ISSUE TITLE
Typo in link

### ISSUE THREAD

**Issue by papinifrancesco** [MicrosoftDocs/windows-powershell-docs#181]
[Enter feedback here]
At the end of the page the link is wrong (a / is missing):
https://technet.microsoft.comlibrary/bb877985.aspx  WRONG

https://technet.microsoft.com/library/bb877985.aspx  CORRECT

please correct the small typo, regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a616f9-f98e-b0fb-0af2-8b6a0b781c8d
* Version Independent ID: 6e01e3d3-aa84-ef17-d33f-f3102671bffc
* Content: [Get-NetPrefixPolicy (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/get-netprefixpolicy?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/nettcpip/Get-NetPrefixPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/nettcpip/Get-NetPrefixPolicy.md)
* Service: **unspecified**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by Malind19** [comment]
Created pull request.
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/867

**Comment by e0i** [comment]
@officedocsbot close
