### ISSUE TITLE
There is a wrong parameter name on example "C:\> Get-ClusterGroup -Name FileServer1 | Format-List -Process *"

### ISSUE THREAD

**Issue by Park-minkyu** [MicrosoftDocs/windows-powershell-docs#1810]
"-Process" is not a recognizable parameter for format-list
that parameter supposed to be "-Property"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16b9ba58-b508-07da-bd3f-a4efe6eb718f
* Version Independent ID: 38c918c7-8be2-d036-8915-2268794dfeff
* Content: [Get-ClusterGroup (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/get-clustergroup?view=win10-ps#feedback)
* Content Source: [docset/windows/failoverclusters/Get-ClusterGroup.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/failoverclusters/Get-ClusterGroup.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @Park-minkyu 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by msbemba** [comment]
@Park-minkyu Thank you for your feedback. We have made changes to the document via PR #https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1869

Thanks
Sri

**Comment by Park-minkyu** [comment]
Am I able to close this issue? When this changes will be released?

**Comment by Park-minkyu** [comment]
@msbemba

**Comment by msbemba** [comment]
@Park-minkyu You will have an option to Close the issue. However, Once the document is updated we will proceed with closing the issue from our side. 

Thanks
Sri

**Comment by Park-minkyu** [comment]
Doc Fixed Confirmed! Thank you!
![image](https://user-images.githubusercontent.com/56732077/79818673-5409a100-83c3-11ea-9d7c-c39b95cdb46e.png)
