### ISSUE TITLE
Authentication for Add-VpnS2SInterface with GRETunnel option

### ISSUE THREAD

**Issue by shirishphade** [MicrosoftDocs/windows-powershell-docs#1811]
Hi Team,

Is there plan to provide Authentication for GRE VPN. I am referring to "Add-VpnS2SInterface" command with  "-GreTunnel" option.

Even if in future releases this option would be available, please let me that also.

Regards
Shirish
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e19b1abe-578c-7477-c71a-af60676f4b17
* Version Independent ID: 033b7f6e-733b-d14e-a27e-f617c3d6e864
* Content: [Add-VpnS2SInterface (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/add-vpns2sinterface?view=win10-ps)
* Content Source: [docset/windows/remoteaccess/Add-VpnS2SInterface.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/remoteaccess/Add-VpnS2SInterface.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@shirishphade 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
