### ISSUE TITLE
Remove-Printer leaves an entry under Printers & Scanners

### ISSUE THREAD

**Issue by Jamal-A-Mohamed** [MicrosoftDocs/windows-powershell-docs#1813]
When Remove-printer is used it still leaves an entry under printers & Scanners.
I have to log in and manually remove that entry from under that.

**Comment by Jamal-A-Mohamed** [comment]
#Get-printers 
$pcname = ""
$delete = Get-Printer -ComputerName $pcname | Where-Object {$_.Name -notlike "*HP LaserJet Pro M404*" -and $_.PortName -like "USB*"}
if($delete) { foreach($printer in $delete) { 
$printername = $printer.Name
$printerdriver = $printer.DriverName$
printerport = $printer.PortName
$credential = Get-Credential
invokecommand -computername $pcname -Credential $credential -scriptblock {
Remove-Printer $using:printernameRemove-PrinterDriver -Name $using:printerdriverRemove-PrinterPort -Name $using:PrinterPort
Restart-Service -Name Spooler 
}
}

**Comment by Jamal-A-Mohamed** [comment]
`#Get-printers 
$pcname = ""
$delete = Get-Printer -ComputerName $pcname | Where-Object {$_.Name -notlike "*HP LaserJet Pro M404*" -and $_.PortName -like "USB*"}

if($delete) { 
foreach($printer in $delete) { 
$printername = $printer.Name
$printerdriver = $printer.DriverName
$printerport = $printer.PortName


$credential = Get-Credential
$pathToDevcon = ''
invoke-command -computername $pcname -Credential $credential -scriptblock  {

New-item HKLM:\SOFTWARE\Policies\Microsoft\Windows -Name 'Device Metadata' 
New-ItemProperty -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\'Device Metadata' -PropertyType DWORD -Name 'PreventDeviceMetadaFromNetwork' -Value 1
Remove-Printer  $using:printername
Remove-PrinterDriver -Name $using:printerdriver
Remove-PrinterPort -Name $using:PrinterPort
New-PSDrive -Credential $using:credential -PSProvider FileSystem -Root $Using:pathtoDevcon -Name Devcon
$files = Get-ChildItem  C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\en-US\
foreach($file in $files ){ 
$filename = $file.Name
start-process "c:\windows\system32\takeown.exe" -argumentlist '/f "C:\Program Data\Microsoft\Windows\DeviceMetadataStore\enus\$filename"'
$acl = get-acl "ACLPath"
Set-Acl -Path  "C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\en-US\$filename" -AclObject $acl 
Remove-Item -Path   "C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\en-US\$filename"-Confirm:$false
Remove-Item  "C:\ProgramData\Microsoft\Windows\DeviceMetadataCache" -Recurse -Force
}

$instanceid = (Get-PnpDevice -FriendlyName $using:Printername).instanceid
$instanceid
copy-item Devcon:\devcon.exe -Destination "Localpath"
$remove = "Localpath\devcon.exe"  remove "@$instanceid"
remove-item "LocalPath\devcon.exe"
$remove


Restart-Service -Name Spooler 
Remove-PSDrive -Name Devcon

}

}

}

`

**Comment by Jamal-A-Mohamed** [comment]
Before running script: 
![2020-03-12 15_57_17-GoToAssist](https://user-images.githubusercontent.com/37128483/76566378-a11c5e00-647a-11ea-87e0-3b77c1945838.png)
After running script:
![2020-03-12 15_59_43-GoToAssist](https://user-images.githubusercontent.com/37128483/76566396-aaa5c600-647a-11ea-9920-183bfc052093.png)

I have to click on remove.

**Comment by e0i** [comment]
Note that the feedback section you have submitted this feedback from is intended for product documentation issues only.

Please consider checking with PowerShell community for your problem so that it gets resolved quickly.

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thank you.
