### ISSUE TITLE
Protocol information

### ISSUE THREAD

**Issue by cobbjb** [MicrosoftDocs/windows-powershell-docs#1819]
Under New-NetFirewallRule, this sentence does not make clear what port1 or port2 are: "If a port number is identified by using port1 or port2, then this parameter must be set to TCP or UDP."  My experience has been that setting a port at all requires the protocol to be set to either TCP or UDP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27788386-303d-156f-7f35-87c226fca966
* Version Independent ID: 42b9abc6-2907-03dc-12f3-43d0a360e5d5
* Content: [New-NetFirewallRule (netsecurity)](https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps#feedback)
* Content Source: [docset/windows/netsecurity/New-NetFirewallRule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/netsecurity/New-NetFirewallRule.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @cobbjb 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.
