### ISSUE TITLE
Confusing description, additional information needed

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/windows-powershell-docs#1824]
> The `Get-WinUILanguageOverride` cmdlet specifies that a user-preferred display language should be used for the Windows user interface (UI)

The cmdlet _gets_ an existing override (set via `Set-WinUILanguageOverride`), it doesn't _set_ anything,.

> If no override setting is used, the display language is dynamically determined from the user language list.

While that is true in general, I don't think it's worth mentioning here - the link to `Set-WinUILanguageOverride` should cover that.

What _is_ worth mentioning here is that if an override is neither in effect _nor pending_ (see below), the return value is `$null`, which is probably worth repeating in the "Outputs" section.

Also worth mentioning that while a change is _pending_ (a `Set-WinUILanguageOverride` call requires a logoff+logon or a reboot to take effect), `Get-WinUILanguageOverride` already reports the _pending_ value, not the one _still in effect_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56a5c207-ed56-1849-45a2-eb307c03eac1
* Version Independent ID: 6331714a-3325-f6f8-dc24-471f9fe4b426
* Content: [Get-WinUILanguageOverride (international)](https://docs.microsoft.com/en-us/powershell/module/international/get-winuilanguageoverride?view=win10-ps)
* Content Source: [docset/windows/international/Get-WinUILanguageOverride.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/international/Get-WinUILanguageOverride.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by VLG17** [comment]
@mklement0 Thank you for opening a separate issue and for the details. I've created a request to get these added.

**Comment by e0i** [comment]
Closing via #1828
