### ISSUE TITLE
#1697

### ISSUE THREAD

**Issue by RichardMueller-8175** [MicrosoftDocs/windows-powershell-docs#1827]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b95dea5-b744-5d31-247e-655a813955f3
* Version Independent ID: 6e10a260-6f36-3d94-8a5c-4fb2367cfb76
* Content: [Set-ADUser (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/set-aduser?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Set-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/activedirectory/Set-ADUser.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issue is missing feedback.

**Comment by RichardMueller-8175** [comment]
I try to keep track of my feedback, but I have no record of having submitted #1826 or #1827. Both deal with the documentation for the -Office parameter for the Set-ADUser cmdlet, but that was dealt with (and fixed) in feedback #1697.
However, I see now that the same issue with the -Office parameter applies to the New-ADUser cmdlet. Maybe I meant to provide feedback to this doc:New-ADUser (activedirectory)


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
New-ADUser (activedirectory)

<p sourcefile="winserver2012-ps/activedirectory/New-ADUser.md" sourcestartlinenumber="1">The New-ADUser cmdlet c...
 |

 |

 |



Sorry for the confusion.    On Tuesday, March 31, 2020, 07:28:53 PM CDT, Onur <notifications@github.com> wrote:  
 
 


Closed #1827.
