### ISSUE TITLE
print job

### ISSUE THREAD

**Issue by pravinabhale** [MicrosoftDocs/windows-powershell-docs#1831]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b19891-f4af-5486-bf2b-9fd134b33bce
* Version Independent ID: 0ab408db-7b1e-e62a-d689-61b163e1e8fe
* Content: [Get-PrintJob (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/get-printjob?view=win10-ps)
* Content Source: [docset/windows/printmanagement/Get-PrintJob.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/printmanagement/Get-PrintJob.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issue is missing feedback.
