### ISSUE TITLE
AddWindowsFeature is wrong

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/windows-powershell-docs#1838]
AddWindowsFeature should be Add-WindowsFeature 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4c3519-c742-91e4-d29a-c2fbfc9a711c
* Version Independent ID: 406c1cf6-1ab8-7f22-1ecb-374ffe246ddd
* Content: [Install-AdcsCertificationAuthority (adcsdeployment)](https://docs.microsoft.com/en-us/powershell/module/adcsdeployment/install-adcscertificationauthority?view=win10-ps)
* Content Source: [docset/windows/adcsdeployment/Install-AdcsCertificationAuthority.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/adcsdeployment/Install-AdcsCertificationAuthority.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@AndreaBarr . Please review  PR #1839

**Comment by e0i** [comment]
Closing via #1838
