### ISSUE TITLE
How to get the adapter that is currently used for internet connection ?

### ISSUE THREAD

**Issue by beppe9000** [MicrosoftDocs/windows-powershell-docs#1845]
I think an example of doing that should be in the examples list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee40ff57-db70-878c-8ece-2afb83c1bb2e
* Version Independent ID: a8582de4-f170-b3f1-feba-6b3f2e2bfaad
* Content: [Get-NetAdapter (netadapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/get-netadapter?view=win10-ps)
* Content Source: [docset/windows/netadapter/Get-NetAdapter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/netadapter/Get-NetAdapter.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@beppe9000 . just enter the below command in PowerShell with admin rights , you will get currently  using internet connection adapter.

**Get-NetAdapter**

![Capture](https://user-images.githubusercontent.com/3296790/77330313-2c340880-6d45-11ea-8d5f-9a26bc04edbe.JPG)

**Comment by beppe9000** [comment]
But how can I get a reference to the interface in a variable for a batch script? Is the active connection guaranteed to be the one with the largest `ifIndex` and Up` status?  Or is the first one always?

![image](https://user-images.githubusercontent.com/6625123/77376584-f147ca00-6d70-11ea-9861-550127567f1a.png)

**Comment by RAJU2529** [comment]
@beppe9000 . In your screenshot, last adapter Wi-Fi is connected , internet is working currently it shows UP. With 150mbps

**Comment by beppe9000** [comment]
I had tought of an usage case like this:```
$a = Get-NetAdapter -> some operations;
echo "Your internet connection is using interface $a"
```

**Comment by LinuxOnTheDesktop** [comment]
I'd like to know how to write a script like that too, and I think others would as well. I am surprised that `Get-NetAdapter` does not have a flag along the lines of `-active`.

**Comment by RAJU2529** [comment]
@LinuxOnTheDesktop . Thanks I seen the commands page. Page is nice. Thanks for sharing the link

**Comment by beppe9000** [comment]
Tahnks for the example. Is it guaranteed to be only one 'Up' connection?

**Comment by e0i** [comment]
It seems that the article deserves an example for listing the active adapter. Expect updates soon. Thank you for the discussion.

**Comment by velkovb** [comment]
@beppe9000 
Hi,

I think you are looking into the wrong cmdlet to find your adapter with active internet connection. The information abou internet connectivity is returned by `Get-NetConnectionProfile`
```powershell
 Get-NetAdapter -InterfaceIndex $(Get-NetConnectionProfile | ? IPv4Connectivity -eq "Internet").InterfaceIndex
```

**Comment by beppe9000** [comment]
thanks. very useful too
