### ISSUE TITLE
404 when running Update-Help for module ThreadJob, but content reported as available

### ISSUE THREAD

**Issue by dgellow** [MicrosoftDocs/windows-powershell-docs#1846]
Hi,

I'm facing the following issue when running `Update-Help` on my machine.

`PS >  Update-Help -Module ThreadJob -Force -Verbose -UICulture en-US -ErrorAction Continue`

Which errors with:
> Update-Help: Failed to update Help for the module(s) 'ThreadJob' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
> English-US help content is available and can be installed using: Update-Help -UICulture en-US.

Trying to fetch the help content results in a 404 Not Found, though the error message also specifies that it actually exists in `en-US` locales.

I have the same issue for `PSDesiredStateConfiguration`, `ThreadJob`, and `WindowsUpdateProvider`.

**Comment by e0i** [comment]
This is a known issue with the updatable help pipeline that affects the `Get-Help` and `Update-Help` commands.

There are ongoing efforts to rework the publishing engine. Once matured, failures to update modules are also going to be addressed. Internal sources inform us, the independent collaborators that it is going to take a lot of work.

There have been multiple reports of the help commands not working so please refer to issue #2247 for tracking the progress of this situation.

Thank you.
