### ISSUE TITLE
Update-Help fails with "A Help URI cannot contain more than 10 redirections. Specify a valid Help URI."

### ISSUE THREAD

**Issue by dgellow** [MicrosoftDocs/windows-powershell-docs#1847]
Hi,

I get the following redirection error when running `Update-Help` from my machine.

`PS >  Update-Help -Module ConfigDefender -Force -Verbose -UICulture en-US -ErrorAction Continue`

The command errors with:
> Update-Help: Failed to update Help for the module(s) 'ConfigDefender' with UI culture(s) {en-US} : A Help URI cannot contain more than 10 redirections. Specify a valid Help URI..
> English-US help content is available and can be installed using: Update-Help -UICulture en-US. 

I have the same error for those modules:
- ConfigDefender
- Defender
- HgsClient
- HgsDiagnostics
- Microsoft.PowerShell.Operation.Validation
- UEV
- Whea
- WindowsDeveloperLicense

**Comment by e0i** [comment]
This is a known issue with the updatable help pipeline that affects the `Get-Help` and `Update-Help` commands.

There are ongoing efforts to rework the publishing engine. Once matured, failures to update modules are also going to be addressed. Internal sources inform us, the independent collaborators that it is going to take a lot of work.

There have been multiple reports of the help commands not working so please refer to issue #2247 for tracking the progress of this situation.

Thank you.
