### ISSUE TITLE
Details missing for some parameters

### ISSUE THREAD

**Issue by wiseleaf23** [MicrosoftDocs/windows-powershell-docs#1848]
For some parameters, the details are still missing, for example at "ConnectedDevice", it says: {{Fill ConnectedDevice Description}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92ec95a-1435-b770-694d-a84ba44bb7b6
* Version Independent ID: 51f44b3e-3e72-ed61-1ffd-243305ff52ea
* Content: [Install-ProvisioningPackage (provisioning)](https://docs.microsoft.com/en-us/powershell/module/provisioning/install-provisioningpackage?view=win10-ps#feedback)
* Content Source: [docset/windows/provisioning/Install-ProvisioningPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/provisioning/Install-ProvisioningPackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@wiseleaf23 . could you please tell me the list of missing details according to you.

**Comment by wiseleaf23** [comment]
> @wiseleaf23 . could you please tell me the list of missing details according to you.

For the following parameters, the description is missing (on the MS Docs webpage):
-ConnectedDevice
-ForceInstall
-LogsDirectoryPath
-WprpFile

It will literally say "{{Fill ... Description"

The following parameters do have this description:
-PackagePath
-QuietInstall

**Comment by e0i** [comment]
@wiseleaf23 

The article has been noted to be revised in the light of your feedback.

Thank you.
