### ISSUE TITLE
-RouteMetric does not work

### ISSUE THREAD

**Issue by d4nr055** [MicrosoftDocs/windows-powershell-docs#1849]
When running this command with the -RouteMetric parameter Powershell returns the error "Add-VpnConnection : A parameter cannot be found that matches parameter name 'routemetric'." 
Is this parameter new? Should I be running a specific version or module of powershell? 
Is there a reason why the Add-VpnConnection command is available but the parameter -RouteMetric is not found?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59b602a8-0420-adf8-bc2c-116a336fc37f
* Version Independent ID: ac7c834d-81d1-30f9-951e-36bc3a30aaaa
* Content: [Add-VpnConnectionRoute (vpnclient)](https://docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnectionroute?view=win10-ps#feedback)
* Content Source: [docset/windows/vpnclient/Add-VpnConnectionRoute.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/vpnclient/Add-VpnConnectionRoute.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by mikenor** [comment]
Add-VpnConnection is a different cmdlet and does not have the RouteMetric parameter. This page is about the Add-VpnConnectionRoute cmdlet.

**Comment by e0i** [comment]
Closing via @mikenor's answer. Thank you.
