### ISSUE TITLE
Missing Properties

### ISSUE THREAD

**Issue by injector22** [MicrosoftDocs/windows-powershell-docs#1851]
This cmdlet returns various properties for the volume. most of these are either missing from the documentation or badly documented.

For example this is the description for VolumeStatus: 
      Whether BitLocker currently protects some, all, or none of the data on the volume.
Yet the cmdlet returns an integer. Without a way to cross reference the int to a mode/status the description doesn't do much.

Others are just outright missing all together like MetadataVersion doesn't even have a description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d45c4d3-7bab-6996-343f-e038c780a9f9
* Version Independent ID: 39573aaa-9107-77be-df58-d67f4d0a11b0
* Content: [Get-BitLockerVolume (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/get-bitlockervolume?view=win10-ps#feedback)
* Content Source: [docset/windows/bitlocker/Get-BitLockerVolume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/bitlocker/Get-BitLockerVolume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@injector22 Hello,
Thank you for trying to make MicrosoftDocs a better place. 
Could you show an example where the VolumeStatus is displayed as an integer? 
I see it is displayed properly everywhere.

MetadataVersion is missing indeed and I believe the following link provides the necessary info [GetVersion-Win32-EncryptableVolume](https://docs.microsoft.com/en-us/windows/win32/secprov/getversion-win32-encryptablevolume). I will work on adding this in the article.

**Comment by injector22** [comment]
![image](https://user-images.githubusercontent.com/5377979/81500025-60379e80-929d-11ea-8953-de3a12121c85.png)

**Comment by injector22** [comment]
![image](https://user-images.githubusercontent.com/5377979/81500034-6ded2400-929d-11ea-9e50-60cd9cb87b17.png)

**Comment by velkovb** [comment]
Thank you for the quick response. I see that you are using ConverTo-Json. Without it you will get proper output of the command:
![image](https://user-images.githubusercontent.com/10958657/81500547-811ee480-92db-11ea-9d74-0244a36687db.png)

I would assume numbers correspond to the values described here:
[GetConversionStatus-Win32-EncryptableVolume](https://docs.microsoft.com/en-us/windows/win32/secprov/getconversionstatus-win32-encryptablevolume)
