### ISSUE TITLE
PeerASN limited to at most 65534

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/windows-powershell-docs#1854]
On windows server 2019 the powershell module Add-BgpPeer does not allow to specify an *PeerASN* higher than 65534, as even though it is of type uint32, there is a validateRange(1, 65534) set, therefore 32-bit asn's or private asn's cannot be used.

The localASN parameter also has this bug, even though it is not listed within cdxml, it still fails with biger AS numbers.

![image](https://user-images.githubusercontent.com/2544867/77568948-b907cf00-6ec9-11ea-9dbc-1c0e38bb98eb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03f71fb-9804-6d6b-a0a4-32c6ac8922c1
* Version Independent ID: ccafb83e-a48e-8563-73ac-fec02b4a19eb
* Content: [Add-BgpPeer (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/Add-BgpPeer?view=win10-ps#feedback)
* Content Source: [docset/windows/remoteaccess/Add-BgpPeer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/remoteaccess/Add-BgpPeer.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@agowa338 . Number 65534KB is used for limitation  size for log events.
Mine is not an answer to your query

**Comment by e0i** [comment]
@agowa338 The article pertains to Windows versions _10_ and _Server 2016_, and not to _2019_. 

That nuance will most likely be addressed with Server 2019 content when it comes out. Thank you.
