### ISSUE TITLE
-ExceptionPrefix example required please

### ISSUE THREAD

**Issue by Function-10** [MicrosoftDocs/windows-powershell-docs#1855]
The error I get is "The web-proxy for VPN connection profile xxx cannot be configured. : The parameter is incorrect."
I have tried all of these combinations
    -ExceptionPrefix (*.domain.tld,10.*.*.*)
    -ExceptionPrefix "*.domain.tld,10.*.*.*"
    -ExceptionPrefix ("*.domain.tld,10.*.*.*")
    -ExceptionPrefix ".domain.tld,10.0.0.0/8"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8155055-18f2-1812-2490-d6f2bd46c895
* Version Independent ID: 296df57c-c0d7-ea0c-6a72-686ea57f2374
* Content: [Set-VpnConnectionProxy (vpnclient)](https://docs.microsoft.com/en-nz/powershell/module/vpnclient/set-vpnconnectionproxy?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/vpnclient/Set-VpnConnectionProxy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012r2-ps/vpnclient/Set-VpnConnectionProxy.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by Vestarija** [comment]
Same problem here!

**Comment by e0i** [comment]
Under investigation.

**Comment by tsimmons** [comment]
Need an example that enables exceptions either by partial IP address using wildcard or IP address using subnet notations, as well as partial domain matching (mydomain.com, *.mydomain.com); Is this even possible?

**Comment by Vestarija** [comment]
Hi everyone!
Still nothing new?

**Comment by e0i** [comment]
It has taken a while but an independent contributor is going to follow up with a response soon. Thank you.

**Comment by Vestarija** [comment]
Sorry to insist but know when we will have a return? Indeed I cannot activate a GPO because of this problem, it is not less than 80 of my users who are affected :(

**Comment by e0i** [comment]
Sorry to hear that you are experiencing difficulties. I am letting the contributor know of this priority. Thank you for following up.

**Comment by velkovb** [comment]
@Function-10 Hello,
I agree this is quite annoying issue. While in the interface you can specify both wildcards and cidr in PowerShell it does not work. Could you try the following syntax:
` -ExceptionPrefix '205.', '*.microsoft.com'`

**Comment by Vestarija** [comment]
Yes!! Many thanks!

**Comment by Function-10** [comment]
Doesn't seem to work for me

```PowerShell
PS C:\> Add-VpnConnectionRoute -ConnectionName "redacted" -PassThru -AllUserConnection -RouteMetric 5 -DestinationPrefix '205.','*.microsoft.com'
Add-VpnConnectionRoute : Cannot process argument transformation on parameter 'DestinationPrefix'. Cannot convert value to type System.String.
At line:1 char:115
+ ... Connection -RouteMetric 5 -DestinationPrefix '205.','*.microsoft.com'
+                                                  ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-VpnConnectionRoute], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-VpnConnectionRoute
PS C:\>
```

**Comment by velkovb** [comment]
> Doesn't seem to work for me
> 
> ```powershell
> PS C:\> Add-VpnConnectionRoute -ConnectionName "redacted" -PassThru -AllUserConnection -RouteMetric 5 -DestinationPrefix '205.','*.microsoft.com'
> Add-VpnConnectionRoute : Cannot process argument transformation on parameter 'DestinationPrefix'. Cannot convert value to type System.String.
> At line:1 char:115
> + ... Connection -RouteMetric 5 -DestinationPrefix '205.','*.microsoft.com'
> +                                                  ~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Add-VpnConnectionRoute], ParameterBindingArgumentTransformationException
>     + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-VpnConnectionRoute
> PS C:\>
> ```

This issue is for **Set-VpnConnectionProxy** not **Add-VpnConnectionRoute**

**Comment by Vestarija** [comment]
> @ Function-10 Bonjour,
> je suis d'accord que c'est un problème assez ennuyeux. Dans l'interface, vous pouvez spécifier à la fois des caractères génériques et cidr dans PowerShell, cela ne fonctionne pas. Pourriez-vous essayer la syntaxe suivante:
> ` -ExceptionPrefix '205.', '*.microsoft.com'`

Sorry to come back so late, I realized that the syntax is good for PowerShell but that without '*' after an IP address (example '192.168.') I do not access the address. I need to add '*' manually for it to work (example '192.168.*')

Do you have a solution?

**Comment by kyleli666** [comment]
The Example2 is wrong in the document. It incorrectly writes -ExceptionPrefix as -ExcludePrefix.
And there is still bug with this -ExceptionPrefix para, see #3639 and #2027
