### ISSUE TITLE
This page should link to instructions on how to cause Windows to dump in response to a machine check

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-powershell-docs#1856]
This cmdlet injects a machine check into the VM.  Windows, by default, ignores this.  The following link says how to fix that.  https://docs.microsoft.com/en-us/windows/win32/debug/configuring-automatic-debugging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15879589-bf38-cdfc-b358-03c72e9b9411
* Version Independent ID: 08df00f8-48eb-fe48-1e4b-20dd9ed6a521
* Content: [Debug-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/debug-vm?view=win10-ps#feedback)
* Content Source: [docset/windows/hyper-v/Debug-VM.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/hyper-v/Debug-VM.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@jakeoshins Thank you for pointing out this important nuance. The article is under investigation.

**Comment by msbemba** [comment]
@jakeoshins Thank you for your feedback. We have added the link to the related links section of the document via PRhttps://github.com/MicrosoftDocs/windows-powershell-docs/pull/1868

Thanks
Sri

**Comment by e0i** [comment]
Closing via #1868
