### ISSUE TITLE
PSpath in an argument for Remove-WebGlobalModule

### ISSUE THREAD

**Issue by nir-yurman** [MicrosoftDocs/windows-powershell-docs#1857]
https://docs.microsoft.com/en-us/powershell/module/webadminstration/remove-webglobalmodule?view=winserver2012-ps#examples

and therefore running the code listed in the example in the page will result in error code
IIS:\&gt;Remove-WebGlobalModule -Name testGlobalModule -PSPath "IIS:\Sites\Default Web Site"

thanks!
nyurman@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd94a7e3-6d90-4af3-ca92-3d1e14fa68ba
* Version Independent ID: c8090811-75ed-913f-cae8-78f97b796931
* Content: [Remove-WebGlobalModule (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/remove-webglobalmodule?view=winserver2012-ps#examples)
* Content Source: [docset/winserver2012-ps/webadminstration/Remove-WebGlobalModule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/webadminstration/Remove-WebGlobalModule.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@nir-yurman The code sample is under investigation. Thank you.
