### ISSUE TITLE
Download help link in PKIClient failed

### ISSUE THREAD

**Issue by Zentris** [MicrosoftDocs/windows-powershell-docs#186]
The link 

> http://go.microsoft.com/fwlink/?linkid=390811

 failed to "The website is not available".

The link is notice on the site 

> https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/pkiclient.md

Pls. correct the link.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
hi @Zentris thanks for your suggestion, we removed the link because it's not valid anymore.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @zentris
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
