### ISSUE TITLE
Please add a reference to the minimum supported Windows 10 version

### ISSUE THREAD

**Issue by qmatteoq** [MicrosoftDocs/windows-powershell-docs#1864]
Working with some customers we have find out that not all the parameters of the Remove-AppxPackage command are supported in every version of Windows 10. For example, on Windows Server 2016 (based on Windows 10 14393), the -AllUsers parameter is not recognized. It works fine, instead, on machines running Windows 10 1809 and above.

Can you please add this information?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc0b0cd3-1201-f5e2-907e-5712eda675da
* Version Independent ID: b722fa48-0af3-27ea-9f86-4f48b9972d19
* Content: [Remove-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps#feedback)
* Content Source: [docset/windows/appx/Remove-AppxPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/Remove-AppxPackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
An independent contributor will follow up with your feedback, thank you for the heads up.

**Comment by e0i** [comment]
Unfortunately, the existing documentation covers up to version 2016 and we have been informed that the documentation support for Server 2019 is in progress.

Thank you for providing feedback.
