### ISSUE TITLE
Thanks to all authors 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-powershell-docs#1865]
Just now i  setted those policies like below

**Set-WheaMemoryPolicy -ComputerName "DESKTOP-620M1SS"
Set-WheaMemoryPolicy -DisableOffline $False
Set-WheaMemoryPolicy -DisablePFA $False
Set-WheaMemoryPolicy -PersistMemoryOffline $True
Set-WheaMemoryPolicy -PFAPageCount 64
Set-WheaMemoryPolicy -PFAErrorThreshold 16
Set-WheaMemoryPolicy -PFATimeout 86400**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13fe1ac7-aa67-12e6-80f5-790fbc268e0f
* Version Independent ID: a345a9b2-0682-a17f-ffac-c8685039d1d5
* Content: [Set-WheaMemoryPolicy (whea)](https://docs.microsoft.com/en-us/powershell/module/whea/set-wheamemorypolicy?view=win10-ps)
* Content Source: [docset/windows/whea/Set-WheaMemoryPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/whea/Set-WheaMemoryPolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
And thank you for your ongoing involvement with the improvement with the documentation. Much appreciated. :)
