### ISSUE TITLE
Is it safe to unregister

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-powershell-docs#1866]
Just now i have seen many background apps are running, but I want to stop apps running background completely.
1. what will happen, if i unregister background apps?
2. Is it possible to re-register the apps to run background 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37759cf5-838e-bbf5-661b-70f971a8e81f
* Version Independent ID: 536697c7-42f8-96cd-013c-de3dd5317254
* Content: [Unregister-AppBackgroundTask (appbackgroundtask)](https://docs.microsoft.com/en-us/powershell/module/appbackgroundtask/unregister-appbackgroundtask?view=win10-ps)
* Content Source: [docset/windows/appbackgroundtask/Unregister-AppBackgroundTask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appbackgroundtask/Unregister-AppBackgroundTask.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello @RAJU2529,

It seems that [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)  would be a better platform to ask this question.

 Feel free to reply if there is anything else that could be done to improve the document itself.

Kind regards
