### ISSUE TITLE
Set-DnsServerResourceRecord: incorrect and error-prone example

### ISSUE THREAD

**Issue by george-chakhidze** [MicrosoftDocs/windows-powershell-docs#187]
In **Example 1**, `$NewObj = $OldObj` assignment DOES NOT create a new instance of an object; it should be replaced with `$OldObj.Clone()` method call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2335a3db-5fe1-404b-aa3d-a3b4f10086fa
* Version Independent ID: 3dfd55d0-2210-626c-b9a6-f584316ec374
* Content: [Set-DnsServerResourceRecord (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/set-dnsserverresourcerecord?view=win10-ps)
* Content Source: [docset/windows/dnsserver/set-dnsserverresourcerecord.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/set-dnsserverresourcerecord.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by george-chakhidze** [comment]
... or `Get-DnsServerResourceRecord` must be called twice; like so:

```powershell
$OldObj = Get-DnsServerResourceRecord -Name "Host01" -ZoneName "contoso.com" -RRType "A"
$NewObj = Get-DnsServerResourceRecord -Name "Host01" -ZoneName "contoso.com" -RRType "A"
...
```

or

```powershell
$OldObj = Get-DnsServerResourceRecord -Name "Host01" -ZoneName "contoso.com" -RRType "A"
$NewObj = $OldObj.Clone()
```

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith please merge this PR, if you find it suitable.

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @george-chakhidze Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
