### ISSUE TITLE
after new-netnat , ping -l 1473 [gateway] timeout 

### ISSUE THREAD

**Issue by chenhui-cvte** [MicrosoftDocs/windows-powershell-docs#1875]
in my case
my system has 1 wireless and 2 RJ45 port 
wireless and one RJ45 as a external port, another RJ45 as internal port that fix ip 192.168.153.254/24 
I create a nat 
`New-NetNat -Name TEST_NAT -InternalIPInterfaceAddressPrefix 192.168.153.0/24
`
after new-netnat , ping -l 1473 [gateway] timeout ,
and then remove-netnat   -Name TEST_NAT, ping -l 1473 [gateway]  is ok

BTW; ping -l 1472 [gateway] is ok

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
