### ISSUE TITLE
symbol should be removed

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-powershell-docs#1876]
[ ]     should be removed , command does not work 
here is the proof

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 127e356b-4383-b1bd-7c3b-b3f105139f94
* Version Independent ID: b8b827de-0e92-fa96-c943-b88a305a0310
* Content: [Get-AppxDefaultVolume (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/get-appxdefaultvolume?view=win10-ps#feedback)
* Content Source: [docset/windows/appx/Get-AppxDefaultVolume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/Get-AppxDefaultVolume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
here is the proof
![Capture05](https://user-images.githubusercontent.com/3296790/78365925-67ec8f00-75dd-11ea-8cd1-9cb30912a8cb.JPG)

**Comment by msbemba** [comment]
@RAJU2529 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1973

Thanks
Sri

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

@JohanFreelancer9

**Comment by JohanFreelancer9** [comment]
No copy to edit.

**Comment by msbemba** [comment]
@RAJU2529 Thank you for the feedback. I think that all cmdlet's documentation includes the [<CommonParameters>] the difference with this one is that it has no other parameters than the common ones. The syntax is not implying that you have to run Get-AppxDefaultVolume [] it is actually telling you that you can run Get-AppxDefaultVolume -Verbose.

Hope this Helps!

Thanks
Sri

**Comment by RAJU2529** [comment]
@msbemba . So should i close the issue or not .

**Comment by msbemba** [comment]
@RAJU2529 Thank you for the feedback. Yes this can be closed as there is no changes needed in the document.

Thanks again!
Sri

**Comment by RAJU2529** [comment]
@msbemba . Thanks
