### ISSUE TITLE
one command does not work

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-powershell-docs#1877]
**Get-SecureBootUefi -Name dbt | Format-List**

above command does not work, remaining all accepted  values worked and received output

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ea34a8a-8dd7-653c-bc79-c5635467b616
* Version Independent ID: 03713847-2d7b-a408-497c-8b89b43f40ef
* Content: [Get-SecureBootUEFI (secureboot)](https://docs.microsoft.com/en-us/powershell/module/secureboot/get-securebootuefi?view=win10-ps)
* Content Source: [docset/windows/secureboot/Get-SecureBootUEFI.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/secureboot/Get-SecureBootUEFI.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@AndreaBarr . Please clarify,  is my Asus  laptop manufacturer does not added  **dbt**  vaules in  UEFI  firmware in bios.  
i want to know the reason. I am waiting for your answer.
If the problems with firmware, then i will contact to the security team of laptop manufacturer.

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also, feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
