### ISSUE TITLE
received  errors

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-powershell-docs#1878]
i tried with different locations with different extension files, But all commands given same  error.

**The specified extrinsic Method does not exist**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb87f59-17f0-ed3c-ed60-e0b02b7e6cd5
* Version Independent ID: 283d68af-7b25-72eb-13d8-238b58377fbd
* Content: [Set-FileIntegrity (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/set-fileintegrity?view=win10-ps)
* Content Source: [docset/windows/storage/Set-FileIntegrity.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/Set-FileIntegrity.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems only.

Please consider checking any relevant resources and asking the community regarding your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

If you feel that this document can also be updated with information related to your request, please comment and re-open this issue we would love to follow-up with documentation updates.

Thank you for providing feedback.
