### ISSUE TITLE
Great!, Thanks a lot!

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windows-powershell-docs#188]
It's been many years since M$ wrote useful documents. This one is really great, especially because of the useful examples. Thank you very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76941bf7-7663-5996-9952-0f7fb1ca5d64
* Version Independent ID: b7516ed6-22ad-b979-1eb6-5936611a2a79
* Content: [Get-NetRoute (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/get-netroute?view=win10-ps)
* Content Source: [docset/windows/nettcpip/get-netroute.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nettcpip/get-netroute.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@schittli Glad to hear your feedback. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
