### ISSUE TITLE
Incorrect seperator

### ISSUE THREAD

**Issue by ruddj** [MicrosoftDocs/windows-powershell-docs#1880]
The top of page has:
```
Specify criteria in the following format:

operator, value01, value02, . . . , operator, value03, value04, . . .
```

There should be a ; not a , before the second operator
```
operator, value01, value02, . . .  ; operator, value03, value04, . . .
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61bdd29f-421b-1d6f-689b-ccc7a6965bb8
* Version Independent ID: f2ba42ac-933d-bc4b-0fc1-75c73f0d475d
* Content: [Add-DnsServerQueryResolutionPolicy (dnsserver)](https://docs.microsoft.com/en-gb/powershell/module/dnsserver/add-dnsserverqueryresolutionpolicy?view=win10-ps#feedback)
* Content Source: [docset/windows/dnsserver/Add-DnsServerQueryResolutionPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/Add-DnsServerQueryResolutionPolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
This changes  can be done from  the author side after verifying the commands

**Comment by msbemba** [comment]
@ruddj Thank you for your feedback. We have corrected the doc via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1940

Thanks
Sri

**Comment by e0i** [comment]
Closing via #1940
