### ISSUE TITLE
Difference between Net-NetIPAddress and Set-NetIPAddress

### ISSUE THREAD

**Issue by PChipVIA** [MicrosoftDocs/windows-powershell-docs#1881]
A DHCP address is an "existing IP Address", so going from DHCP to fixed IP one uses the "Set" or the "New" cmdlet?  Some clarification needed on use cases of both cmdlets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e57816b-1566-54f6-6d06-cf9b8cc0a7a6
* Version Independent ID: f0719282-04c9-a760-656b-20de8673369a
* Content: [Set-NetIPAddress (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/set-netipaddress?view=win10-ps)
* Content Source: [docset/windows/nettcpip/Set-NetIPAddress.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nettcpip/Set-NetIPAddress.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
**The Set-NetIPAddress cmdlet modifies IP address configuration properties of an existing IP address**

created by **New-NetIPAddress**

**Comment by PChipVIA** [comment]
So when using DHCP it means using the SET cmdlet to set the current IP to a fixed address?

Please define: 

> existing IP address.  

> 

It's clear to you, I can see, but is DHCP based IP an _existing IP_ or not?

**Comment by RAJU2529** [comment]
@PChipVIA . **DHCP based IP an existing IP or not?**  this needs to be addressed by DHCP advanced users, so keep waiting for solutions.

**Comment by PChipVIA** [comment]
@RAJU2529 Thanks for the follow up.  It is not a DHCP question it is an IP question.  More specifically it is a definitions issue.

**Comment by kkzainul** [comment]
What is the command to configure the WINS ip address?

**Comment by velkovb** [comment]
@PChipVIA 
When you network adapter is configured via DHCP it already has an existing IP address. However, with the `Set-NetIPAddress` you cannot modify the IP address itself or change it from DHCP to static. You can only modify properties like Type, PrefixLength...

To go from DHCP to static you need to use the `Set-NetIPInterface` cmdlet and when you switch to static you will then have to use the `New-NetIPAddress` cmdlet to create a static IP for the adapter.

Let me know if you have any questions.

**Comment by velkovb** [comment]
> What is the command to configure the WINS ip address?

@kkzainul WINS is not used to configure IP addresses. It is a legacy service that translates NetBIOS names into IP addresses. Not sure if anyone still uses WINS, people use DNS now.
