### ISSUE TITLE
Insufficient or incorrect example

### ISSUE THREAD

**Issue by lordyoda** [MicrosoftDocs/windows-powershell-docs#1882]
This page has an example for a different commandlet and lacks sufficient troubleshooting information

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3f965bf-0a92-3ae1-d48b-848c21cccc7f
* Version Independent ID: 1a496429-05fc-af14-c71a-bba1f0c42651
* Content: [Get-ADFSEndpoint (adfs)](https://docs.microsoft.com/en-ca/powershell/module/adfs/get-adfsendpoint?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/adfs/Get-ADFSEndpoint.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/adfs/Get-ADFSEndpoint.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
The content has been revised accordingly. Thank you for the feedback.
