### ISSUE TITLE
Example not working - Get-ADUser <user> -Properties Extended | Get-Member

### ISSUE THREAD

**Issue by TiagoJSilva** [MicrosoftDocs/windows-powershell-docs#1885]
Get-ADUser : One or more properties are invalid.
Parameter name: Extended
At line:1 char:1
+ Get-ADUser Administrator -Properties Extended | Get-Member
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Administrator:ADUser) [Get-ADUser], ArgumentExcep
   tion
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDire
   ctory.Management.Commands.GetADUser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a4eb77a-834c-0412-8f9f-9c515172237e
* Version Independent ID: 0228a754-2177-71d0-92cc-ae144070947e
* Content: [Get-ADUser (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps&redirectedfrom=MSDN&viewFallbackFrom=winserver2012r2-ps#feedback)
* Content Source: [docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Get-ADUser.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@TiagoJSilva . I think this cmdlet works on server OS with active domain-joined machines.

I am not sure. Let experienced users will help

**Comment by TiagoJSilva** [comment]
> @TiagoJSilva . I think this cmdlet works on server OS with active domain-joined machines.
> 
> I am not sure ,Whether the above sentence is correct or not.
> Let experienced users will help.

I was running Server2016Core Primary Domain Controller at the time. Since it's on Server2012 pages, I don't think it's an issue with PoSh version. The "Extended" keyword doesn't exist as an option for -Properties. -Properties needs an enumerated list of specific properties.

**Comment by RAJU2529** [comment]
@TiagoJSilva . Thanks for replying, i don't have knowledge on AD, so please wait, let other users will give solutions.

**Comment by sowjanya365** [comment]
Hi @TiagoJSilva 

Thanks for reaching out to us! 

If you your computer is running Windows 8.1 or Windows Server 2012 R2,  the command fails.

This is a known issue. To resolve this issue, install update rollup 2928680, or install the hotfix that is described in this article. 

https://support.microsoft.com/help/2923122/one-or-more-properties-are-invalid-error-when-you-run-the-get-aduser-o

Hope this clarifies. Thank you!

**Comment by tGecko** [comment]
This is still / again an issue. Windows 11 22621.1555
Powershell 7.3.4
`PS C:\Users\user> Get-ADUser user-Properties Extended | Get-Member
Get-ADUser: One or more properties are invalid. (Parameter 'Extended')`

Also in Windows Powershell 5.1.22621.963
`PS C:\Users\user> Get-ADUser user-Properties Extended | Get-Member
Get-ADUser : Mindestens eine Eigenschaft ist ungültig.
Parametername: Extended`
