### ISSUE TITLE
AD

### ISSUE THREAD

**Issue by Olia911** [MicrosoftDocs/windows-powershell-docs#1886]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e05ef45-75ec-afa6-ca4a-4a8d7539b8df
* Version Independent ID: 89c730c3-d612-d2c1-8a7c-2a49cb8b1b37
* Content: [Enable-ADAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/Enable-ADAccount?view=win10-ps)
* Content Source: [docset/windows/addsadministration/Enable-ADAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Enable-ADAccount.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Feedback is missing from the issue.
