### ISSUE TITLE
Additional Information may be helpful

### ISSUE THREAD

**Issue by rvkota** [MicrosoftDocs/windows-powershell-docs#1889]
1. What are the pre-requisites to use this cmdlet (example is the -Name &lt;param-value&gt; should already been added)
2. What are the errors/exceptions and some explanation on them.
Thank you
Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f32bb33-ebbe-7127-50d6-efc13c9a69a3
* Version Independent ID: 83538ea8-2449-2895-5b15-9f9bf9bf8d17
* Content: [Add-DnsServerResourceRecordCName (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecordcname?view=win10-ps#feedback)
* Content Source: [docset/windows/dnsserver/Add-DnsServerResourceRecordCName.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/Add-DnsServerResourceRecordCName.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by MaratMussabekov** [comment]
Hello,
**What are the pre-requisites to use this cmdlet** - the only prerequisite is that the zone specified in ZoneName parameter must exist on the DNS server
**example is the -Name <param-value> should already been added** - no, the record will be created even if the name specified in Name parameter wasn't added yet.
**What are the errors/exceptions and some explanation on them** - this kind of information is out of scope of the articles that describe cmdlets. The template contains only sections Syntax, Description, Examples, Parameters and Outputs.

Thank you
