### ISSUE TITLE
Workgroup computer

### ISSUE THREAD

**Issue by ramuvr** [MicrosoftDocs/windows-powershell-docs#1890]
If a computer is a standalone work group computer, can this command be used to import GPO? This article doesn't clarify usage about non-domain computers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721012cd-3681-ac79-ce1b-24c1fdc7ef72
* Version Independent ID: 1cecde44-8893-4d3e-13f0-aad34af7dfe5
* Content: [Import-GPO (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/import-gpo?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/Import-GPO.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/Import-GPO.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@ramuvr Hi Ramu,

Thank you for trying to make MicrosoftDocs a better place.

I have tested your scenario and it seems it does not work outside of a domain.
![image](https://user-images.githubusercontent.com/10958657/82703277-41adac00-9c7c-11ea-9b70-09f30dde72a0.png)

Let me know if you have any questions.
