### ISSUE TITLE
Total lack of docs

### ISSUE THREAD

**Issue by BizD3V** [MicrosoftDocs/windows-powershell-docs#1892]
Given the complexity of this cmdlet, having NO documentation for any of the parameters isn't helpful. The parameters listed are just common ones, what does "CompanyName" for example do in the case of a WSS migration??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d569cd-4428-2d98-4353-ebe47443b1a8
* Version Independent ID: 3793f067-254d-1fca-7e0f-28be94d3f122
* Content: [Start-WssConfigurationService (wsssetup)](https://docs.microsoft.com/en-us/powershell/module/wsssetup/start-wssconfigurationservice?view=winserver2012r2-ps#feedback)
* Content Source: [docset/winserver2012r2-ps/wsssetup/Start-WssConfigurationService.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/wsssetup/Start-WssConfigurationService.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The page now has complete descriptions of all cmdlet parameters.

There has been an ongoing effort for quite a long time to provide with the missing descriptions on some cmdlets similar to this one.

Thanks for bringing this to attention, and stay well and safe.
