### ISSUE TITLE
Undocumented Feature with Server 2016 and SQL or Exchange

### ISSUE THREAD

**Issue by damtrx** [MicrosoftDocs/windows-powershell-docs#1894]
Scenario:

Two or more **Windows Server 2016** in Windows Failover Cluster Scenario. In the current example SQL 2016 AlwaysON cluster or Exchange Database availability group. 

V**olume D** is configured on two or more servers in Failover Cluster Scenario and it is not configured as Shared disk or Clustered Shared Volume disk.

Execute **Format-Volume D** and it will format all the Volumes on the Failover Cluster that are with DriveLetter **D** . No exceptions. All volumes on all the nodes.

There is no way to suppress this and no information regarding this feature

**Comment by e0i** [comment]
Hello, Can you provide the associated article this problem stems from? Thank you.

**Comment by damtrx** [comment]
Hi Onur,
There is no article. If you use Format-Volume and you have Clustered resources on ws 2016 and use Exchange or SQL then the command line will format all the volumes.

Get command will return all the volumes in the cluster too
Feel free to contact me at +359898483707 if you want for more details.
I work for a MS partner company and we can use my company teams too
Martin.dutsov@tbs.tech

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by e0i** [comment]
@damtrx 

We don't do customer support, given this is rather a bug report, please consider consulting [PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) channel regarding your product feedback.

We use the issue tracker of this repository for fixing errors in documentation article content.

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community for your situation,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thank you.

**Comment by damtrx** [comment]
Onur,

It is not a support issue but a bug in the implementation of the cmdlets.
I want this to be changed in the repo because obviosly is not documented feature.

I can do it from here, but I can do it though my premier support.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by velkovb** [comment]
@damtrx Thanks for your report.

This sure is a "feature" you would not expect and it seems like it was introduced in Server 2016. I was able to find a person with a similar problem that claims to have reported it to Microsoft Support and they have confirmed the behaviour. You can check here:
[Windows Server 2016 Failover Cluster Get-Volume lists all volumes](https://social.technet.microsoft.com/Forums/f1c20967-b08c-4654-97a8-82ae9a8045d3/windows-server-2016-failover-cluster-getvolume-lists-all-volumes?forum=winserverClustering)

Here we could only update the article so it warns users of this possible outcome. I will update the article to include that as a note. If you have premier support you could try that way in escalating it as a bug.

**Comment by damtrx** [comment]
Hi Boris,

Actually I tried to raise this as an incident but someone decided that this is not a big issue and closed the request.
This is not documented feature and believe me “get-disk” and few other CMDlets like “format-volume” in SQL cluster made my day/night pretty good 😉

Please update the articles for all DISK related cmd-lets in scenario like Always On cluster or Exchange DAG (some file replication services might be related too)

Thanks .


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
