### ISSUE TITLE
Forest or domain

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/windows-powershell-docs#1897]
Should I run Add-KdsRootKey once per forest or once per domain?  Can you please add the answer to the documentation?  Maybe at the end of the description would be a good place for this note.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2b0a25f-89dc-b70f-d791-328aa8e64e64
* Version Independent ID: 877326d0-d86b-f528-d45a-e04a36da04d0
* Content: [Add-KdsRootKey (kds)](https://docs.microsoft.com/en-us/powershell/module/kds/add-kdsrootkey?view=win10-ps#feedback)
* Content Source: [docset/windows/kds/Add-KdsRootKey.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/kds/Add-KdsRootKey.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@schnitz76  Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1975

Thanks
Sri

**Comment by e0i** [comment]
The changes introduced via the associated PR #1975 has been merged. Thank you for the feedback.
