### ISSUE TITLE
Wrong switch in example

### ISSUE THREAD

**Issue by ramuvr** [MicrosoftDocs/windows-powershell-docs#1898]
The "Example 1: Report if programs are allowed to run" example shown has the switch as XMLPath instead of XmlPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58784a4-b266-2b63-927f-8022e1b8a849
* Version Independent ID: 2149e6ed-22f9-4cf3-e277-cc90c92e8d09
* Content: [Test-AppLockerPolicy (applocker)](https://docs.microsoft.com/en-us/powershell/module/applocker/test-applockerpolicy?view=win10-ps)
* Content Source: [docset/windows/applocker/Test-AppLockerPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/applocker/Test-AppLockerPolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@ramuvr Thank you for your feedback. We have made changes to the doc via PE #https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1971

Thanks
Sri

**Comment by e0i** [comment]
Closing via #1971
