### ISSUE TITLE
"Unknown" value for the Type parameter

### ISSUE THREAD

**Issue by Ulyssys** [MicrosoftDocs/windows-powershell-docs#190]
What purpose is the "Unknown" value for the Type parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17726ad0-c69c-4327-4260-55f822bcaa56
* Version Independent ID: 65e311f4-e8d0-85d5-cede-bd24cfd20ca0
* Content: [New-ClusterFaultDomain (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/new-clusterfaultdomain?view=win10-ps#related-links)
* Content Source: [docset/windows/failoverclusters/new-clusterfaultdomain.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/new-clusterfaultdomain.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith please merge this PR, if find it suitable

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @Ulyssys 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
