### ISSUE TITLE
Elevation required for Get- verb command?

### ISSUE THREAD

**Issue by toxicbubble** [MicrosoftDocs/windows-powershell-docs#1900]
Why does Get-WindowsOptionalFeature require elevation just to query what's even present \ available. It should be possible to see if something is installed or even exists without admin rights. This would be especially useful for detection scripts in SCCM when deployed to users (where the detection script evaluates in the context of the user)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6c867c5-8521-8bd1-6f48-a49bd3971738
* Version Independent ID: 429b4dbf-b12b-6a68-b272-ed72f8843ef6
* Content: [Get-WindowsOptionalFeature (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/get-windowsoptionalfeature?view=win10-ps#feedback)
* Content Source: [docset/windows/dism/Get-WindowsOptionalFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/Get-WindowsOptionalFeature.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@toxicbubble  Thank you for your feedback.. The get-windowsoptionalfeature requires access to system files which is denied when running the cmdlet without elevated privileges.

Thank you and as such there are no changes needed to this document. @e0i 

Thanks
Sri
