### ISSUE TITLE
Stop-ClusterResource 

### ISSUE THREAD

**Issue by stuyun** [MicrosoftDocs/windows-powershell-docs#1901]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 29d75d3e-75e1-1e4d-8370-210b4b1ec87c
* Version Independent ID: 283ae92f-3f7f-1bcd-edc8-294abdf06e47
* Content: [Remove-ClusterResource (failoverclusters)](https://docs.microsoft.com/zh-cn/powershell/module/failoverclusters/remove-clusterresource?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/failoverclusters/Remove-ClusterResource.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/failoverclusters/Remove-ClusterResource.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Closing via missing feedback.
