### ISSUE TITLE
cmdlet examples

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-powershell-docs#1906]
Example "set-ProcessMitigation -Name Notepad.exe -Enable SEHOP -Disable MandatoryASLR" does not work, as MandatoryASLR is invalid parameter. 

Could doc include examples on -Remove and -Reset?
I cannot manage to use those two switches.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ab88b71-84f4-7777-7791-06869c5d7caf
* Version Independent ID: f56d8bcc-0c53-0338-3e58-f30c45071651
* Content: [Set-ProcessMitigation (processmitigations)](https://docs.microsoft.com/en-us/powershell/module/processmitigations/set-processmitigation?view=win10-ps)
* Content Source: [docset/windows/processmitigations/Set-ProcessMitigation.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/processmitigations/Set-ProcessMitigation.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@juanand  Thank you for your feedback. We have made some changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1991

Thanks
Sri
