### ISSUE TITLE
Resolve-DnsName returns more than 25 A and AAAA records

### ISSUE THREAD

**Issue by jaellio** [MicrosoftDocs/windows-powershell-docs#1915]
When I use the Resolve-DnsName cmdlet I get a lot more than 25 records in response. In the doc it is mentioned that the max records returned is 25. I may have misunderstood this note, but I thought I would bring it to your attention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014fb5df-2480-2136-1257-2aade82e4c4a
* Version Independent ID: 38c0b3be-3aa8-7926-716c-aa28367d6df7
* Content: [Resolve-DnsName (dnsclient)](https://docs.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname?view=win10-ps#feedback)
* Content Source: [docset/windows/dnsclient/Resolve-DnsName.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsclient/Resolve-DnsName.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by MaratMussabekov** [comment]
Checked and confirmed, there is no limit for 25 records
