### ISSUE TITLE
Broken link - EventTracManCmdlets

### ISSUE THREAD

**Issue by smithnigelw** [MicrosoftDocs/windows-powershell-docs#1916]
The hyperlink is 404 for EventTracingManagement (EventTracManCmdlets)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd5a23d7-280d-fe41-aa71-fb94390d606a
* Version Independent ID: 6e9677e3-763f-9689-3219-69b7c8b7685d
* Content: [Windows 10 and Windows Server 2016](https://docs.microsoft.com/en-us/powershell/windows/get-started?view=win10-ps#feedback)
* Content Source: [docset/docs-conceptual/windows/get-started.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/docs-conceptual/windows/get-started.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by smithnigelw** [comment]
Presumably, you should replace:
  https://docs.microsoft.com/en-us/powershell/module/eventtracmancmdlets/
by:
  https://docs.microsoft.com/en-us/powershell/module/eventtracingmanagement/

**Comment by msbemba** [comment]
@smithnigelw Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1972

Thanks
Sri

**Comment by e0i** [comment]
Closing via associated PR #1972 having been merged. Thank you for the feedback.
