### ISSUE TITLE
backup Id

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-powershell-docs#192]
There is no indication on how to identify what a backup ID of a GPO is or what the GUID of a GPO is.  I've discovered that the GUID of the GPO is found using ADUC.  However, I have not been able to discover what the backup ID of a GPO would be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50ff2fd6-2f9a-41ef-7374-5bd98f7a1833
* Version Independent ID: e23abbeb-19ae-469f-a24f-7ae35e26d229
* Content: [Restore-GPO (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/restore-gpo?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/restore-gpo.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/restore-gpo.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by rodmhgl** [comment]
That is a bit beyond the scope of this help file, but you can find more information here: https://community.spiceworks.com/how_to/129132-how-to-back-up-and-restore-group-policy-objects

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks @poortom1004 for your suggestion, I'll add a PR to update and improve the article.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @poortom1004 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
