### ISSUE TITLE
misleading description for #3

### ISSUE THREAD

**Issue by madrum** [MicrosoftDocs/windows-powershell-docs#1923]
For example 3, the "Name" parameter indicates it is for a computer named VMS1 and a share named VMS1. It appears that "-Name" is for the name of the share, not the name of the computer. 

"This command retrieves the SMB shares on the computer named VMS1.

Example 3: Display information about the SMB share named 'VMS1' on the local computer in a list"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a82643cf-0f56-5790-c27a-86f6c19c5423
* Version Independent ID: 4f20dd35-7e82-ae1e-4484-10899dce23a8
* Content: [Get-SmbShare (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/get-smbshare?view=win10-ps#feedback)
* Content Source: [docset/windows/smbshare/Get-SmbShare.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/smbshare/Get-SmbShare.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@madrum  Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1992

Thanks
Sri
