### ISSUE TITLE
Create an AppLocker policy from audited events - Warning Message

### ISSUE THREAD

**Issue by GrahamYoung05** [MicrosoftDocs/windows-powershell-docs#1924]
Please add a warning message if DLL files are found in the audited events, possibly add "Get-AppLockerFileInformation -EventLog -LogPath "Microsoft-Windows-AppLocker/EXE and DLL" -EventType Audited | where {$_.path -like '*.exe'} | new-applockerpolicy | set-applockerpolicy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85eefdb0-7152-6a15-d3ab-bce41205759e
* Version Independent ID: 35f599ea-e3f4-23bc-fd57-2885af5f64e0
* Content: [New-AppLockerPolicy (applocker)](https://docs.microsoft.com/en-us/powershell/module/applocker/new-applockerpolicy?view=win10-ps#feedback)
* Content Source: [docset/windows/applocker/New-AppLockerPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/applocker/New-AppLockerPolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issue tracker of this repository is intended for product documentation issues only.

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)


Thanks.

**Comment by GrahamYoung05** [comment]
The product documentation that shows the powershell example 3 “Create an AppLocker policy from audited events” can cause workstations to enable rule enforcement on DLL files if they are found in the audited events and cause the workstation to not trust Windows DLL files and not boot properly. This is why I suggest adding a warning to the example.

Graham Young
Technology OneSource Consulting Engineer
NetGain Technologies<http://www.netgainit.com/>

859-397-8996 Direct
866-375-5422 Helpdesk
gyoung@netgainit.com<mailto:gyoung@netgainit.com>

**Comment by e0i** [comment]
@GrahamYoung05 Thank you for following up with a clarification. Passing this issue to contributors for investigation.

**Comment by msbemba** [comment]
@GrahamYoung05 Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1990

Thanks
Sri

**Comment by msbemba** [comment]
@GrahamYoung05 Thank you for your feedback. Unfortunately, we are not able to verify this at the moment and we will be archiving this for now.

Thanks
Sri
