### ISSUE TITLE
Help syntax for ServicePrincipalNames is partially incorrect

### ISSUE THREAD

**Issue by SeanQuinlan** [MicrosoftDocs/windows-powershell-docs#1930]
Two of the example lines have incorrect syntax:
`@{Add=value1,value2,...};@{Remove=value3,value4,...}`
Should be:
`@{Add=value1,value2,...;Remove=value3,value4,...}`

`-ServicePrincipalNames-@{Add="SQLservice\accounting.corp.contoso.com:1456"};{Remove="SQLservice\finance.corp.contoso.com:1456"}`
Should be:
`-ServicePrincipalNames @{Add="SQLservice/accounting.corp.contoso.com:1456";Remove="SQLservice/finance.corp.contoso.com:1456"}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4121df29-b82c-2f0d-7d71-000a41094d91
* Version Independent ID: b1993985-f892-bd2b-2e64-69c1eaaff2ad
* Content: [Set-ADComputer (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-adcomputer?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/Set-ADComputer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Set-ADComputer.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@SeanQuinlan Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1989

Thanks
Sri

**Comment by e0i** [comment]
Closing via #1989
