### ISSUE TITLE
How to set IIS WebApplication Start Mode to AlwaysRunning via command line?

### ISSUE THREAD

**Issue by ajsjunior** [MicrosoftDocs/windows-powershell-docs#1933]
There are additional parameters for the New-WebApplication? I need to set Start Mode to AlwaysRunning via powershell script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb8ca05f-dc53-fc1a-4a22-32eb460e3084
* Version Independent ID: d360069f-d3d9-51f8-141b-a9c897c0e50f
* Content: [New-WebApplication (webadministration)](https://docs.microsoft.com/en-us/powershell/module/webadministration/new-webapplication?view=win10-ps)
* Content Source: [docset/windows/webadministration/New-WebApplication.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/webadministration/New-WebApplication.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
