### ISSUE TITLE
Example 2 does not run

### ISSUE THREAD

**Issue by ruddj** [MicrosoftDocs/windows-powershell-docs#1947]
The sample 2 does not run. Appears the * should be a new line.
```
$Printers = Get-Printer * Foreach ($Printer in $Printers){     Get-PrinterProperty -PrinterName $Printer.name }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb51ea01-25b1-c7da-707c-41af3a1e4fee
* Version Independent ID: 6897c4a9-b1ea-ad1c-2b59-63a64a0a3762
* Content: [Get-PrinterProperty (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/get-printerproperty?view=win10-ps)
* Content Source: [docset/windows/printmanagement/Get-PrinterProperty.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/printmanagement/Get-PrinterProperty.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@ruddj Thank you for your feedback. We have modified the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1974

Thanks
Sri

**Comment by e0i** [comment]
The related PR #1974 has been merged and it might take a few days for changes to be fully published online. Thank you for providing feedback.
