### ISSUE TITLE
Within Trigger is there an option to stop task if it runs longer than: x timespan

### ISSUE THREAD

**Issue by holyhom8** [MicrosoftDocs/windows-powershell-docs#1955]
My question is specifically about Edit Trigger&gt;Advanced settings&gt;Stop task if it runs longer than 
I have used the ...SettingsSet option to set the 'Stop the task if it runs longer than' in Settings tab

This has raised my interest also
https://serverfault.com/questions/604083/task-scheduler-2-0-difference-between-stop-task-if

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ce19ed-65a3-a416-73ff-3388c0503647
* Version Independent ID: c2af9c57-b677-e836-1c60-595fcc64bb14
* Content: [New-ScheduledTaskTrigger (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps#feedback)
* Content Source: [docset/windows/scheduledtasks/New-ScheduledTaskTrigger.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/New-ScheduledTaskTrigger.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by MaratMussabekov** [comment]
Hello,
unfortunately this function is not supported by **New-ScheduledTaskTrigger** cmdlet.
The only option is to use **ExecutionTimeLimit** parameter of the **New-ScheduledTaskSettingsSet** cmdlet
Thank you
