### ISSUE TITLE
How to setup a trigger like this which runs for daily mutliple times for 12 times with 1hr duration with option stop all running tasks at end of rep duration

### ISSUE THREAD

**Issue by holyhom8** [MicrosoftDocs/windows-powershell-docs#1957]
Edit Trigger
Daily
Repeat task every 1hour
for a duration of 12 hours
Stop all running tasks at end of repetition duration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ce19ed-65a3-a416-73ff-3388c0503647
* Version Independent ID: c2af9c57-b677-e836-1c60-595fcc64bb14
* Content: [New-ScheduledTaskTrigger (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/New-ScheduledTaskTrigger.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/New-ScheduledTaskTrigger.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also, feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
