### ISSUE TITLE
Add-VpnConnectionRoute not always working

### ISSUE THREAD

**Issue by jmichler** [MicrosoftDocs/windows-powershell-docs#196]
Can you clarify why the following fails:
Add-VpnConnectionRoute myVPN 217.243.137.208/27

Add-VpnConnectionRoute :  Invalid parameter DestinationPrefix 217.243.137.208/27. : Falscher Parameter.
In Zeile:1 Zeichen:1
+ Add-VpnConnectionRoute myVPN 217.243.137.208/27
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (myVPN:root/Microsoft/...ConnectionRoute) [Add-VpnConnectionRoute], CimException
    + FullyQualifiedErrorId : WIN32 87,Add-VpnConnectionRoute

it's working fine for e.g. 10.128.0.0/16

**Comment by theoneandonly-vector** [comment]
same problem here with: "10.0.0/24"

it's working using 10.128.0.0/16.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @jmichler how are you?
This is to inform of issues in docs article, is there any article that you see presents issues and need to be improved? if not, @yogkumgit will kindly redirect you to some support resources that will help you.
Thank you

**Comment by jmichler** [comment]
Hi,
the question/problem is clearly described, I think this is not about a doc but a bug in the cmdlet

**Comment by yogkumgit** [comment]
@jmichler Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: 
https://docs.microsoft.com/powershell/#pivot=main&panel=community

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
