### ISSUE TITLE
Problems with New-WebBinding cmdlet

### ISSUE THREAD

**Issue by jrbilodeau** [MicrosoftDocs/windows-powershell-docs#197]
Hi,

I'm trying to use the New-WebBinding cmdlet to add an HTTPS binding to a site that already has an HTTP binding and discovered a few bugs with the cmdlet. 

Here is the command that I ran
New-WebBinding -Name MyWebSite -HostHeader mywebsite.ca -IPAddress * -Protocol https -Port 443 -SslFlags 3

This creates the binding, however tryingto browse the site via https://mywebsite.ca fails to load. If I go into IIS Manager and look at the bindings for this site under SSL Certificate it is greyed out but says "Not selected". If I simply uncheck either the SNI or Central certificate store option and recheck it "Not selected" disapears and everything works.

Also in the New-WebBinding cmdlet for the -Protocol property if i type HTTPS in caps, the setting applies in an odd way.
All of the information shows up in the Bindind information column in IIS manager, and nothing shows up in the Port and IP Address column.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd15223d-e472-cbe7-15d6-dbbd4a373351
* Version Independent ID: 87dd59f6-b943-fc82-9b39-d79c2f487dd1
* Content: [New-WebBinding (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-webbinding?view=winserver2012-ps&viewFallbackFrom=win10-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/New-WebBinding.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @jrbilodeau  how  are you? thanks for your feedback.

This is to inform of issues in docs  article, is there any article that you see presents issues and need to be   improved? if not, @yogkumgit will kindly redirect you to some support  resources that will help you.
Thank you

**Comment by yogkumgit** [comment]
@jrbilodeau Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: 
https://docs.microsoft.com/powershell/#pivot=main&panel=community

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
