### ISSUE TITLE
Missing documentation on New-SmbGlobalMapping

### ISSUE THREAD

**Issue by WAftring** [MicrosoftDocs/windows-powershell-docs#1978]
There is reference to New-SmbGlobalMapping in a few locations:

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/persistent-storage

But there is no documentation on these cmdlets and the information provided in the Get-Help for these cmdlets is very limited.

```
NAME
    New-SmbGlobalMapping
    
SYNTAX
    New-SmbGlobalMapping [[-LocalPath] <string>] [-RemotePath] <string> -Credential <pscredential> [-Persistent 
    <bool>] [-RequireIntegrity <bool>] [-RequirePrivacy <bool>] [-UseWriteThrough <bool>] [-FullAccess <string[]>] 
    [-DenyAccess <string[]>] [-CimSession <CimSession[]>] [-ThrottleLimit <int>] [-AsJob] [-WhatIf] [-Confirm]  
    [<CommonParameters>]
    

ALIASES
    nsmbgm
    

REMARKS
    Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help.
        -- To download and install Help files for the module that includes this cmdlet, use Update-Help.
```

Update-Help does not provide any new information for this module.

Is there additional information for these cmdlets and if so where is it documented?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2324344d-f39e-d62c-f565-bad3ec9a192b
* Version Independent ID: cf9f6f2c-a255-120b-d6cf-7f71429f0c41
* Content: [New-SmbMapping (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/new-smbmapping?view=win10-ps#feedback)
* Content Source: [docset/windows/smbshare/New-SmbMapping.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/smbshare/New-SmbMapping.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by jfbradfo** [comment]
This applies to all three SmbGlobalMapping cmdlets.  Get-Help -online indicates that the URI for the online help is either broken or doesn't exist.  

What additional information has been put out since this was posted?

Thanks!

**Comment by e0i** [comment]
This is a known issue with the updatable help pipeline that affects the `Get-Help` and `Update-Help` commands.

There are ongoing efforts to rework the publishing engine. Once matured, failures to update modules are also going to be addressed. Internal sources inform us, the independent collaborators that it is going to take a lot of work.

There have been multiple reports of the help commands not working so please refer to issue #2247 for tracking the progress of this situation.

Thank you.
