### ISSUE TITLE
Vauge, inaccurate, and poorly done. 

### ISSUE THREAD

**Issue by brandonfhall** [MicrosoftDocs/windows-powershell-docs#1979]
Doesn't include most of the actual parameters, and the one it does show is inaccurate. Also does not detail how, or what combination of commands needs to be used for which result. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4bcdbe7-9625-475a-7b53-6d1a58f58885
* Version Independent ID: ccc019ea-f72a-1ae7-884b-c7be802342e8
* Content: [New-OBRetentionPolicy (msonlinebackup)](https://docs.microsoft.com/en-us/powershell/module/msonlinebackup/new-obretentionpolicy?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/msonlinebackup/New-OBRetentionPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/msonlinebackup/New-OBRetentionPolicy.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by MaratMussabekov** [comment]
Hello @brandonfhall ,
Yes, it should contain following parameters:

**RetentionDays** – how long to retain backup points (and it is not limited to 30 days, as it is shown in the article)

**RetentionWeeklyPolicy** – whether to retain weekly backup point
**WeekDaysOfWeek** –  at which day to perform weekly backup {Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday}
**WeekTimesOfDay** – at which time weekly backup should be taken
**RetentionWeeks** – how many weeks weekly backup should be retained

**RetentionMonthlyPolicy** – whether to retain monthly backup point
**MonthWeeksOfMonth** – at which week of the month monthly backup should be taken {First | Second | Third | Fourth | Last} (cannot be used with MonthDaysOfMonth parameter, requires MonthDaysOfWeek parameter) 
**MonthDaysOfWeek** – at which day of week monthly backup should be done {Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday}  (cannot be used with MonthDaysOfMonth parameter, requires MonthWeeksOfMonth parameter)
**MonthDaysOfMonth** – at which day of month monthly backup should be taken (cannot be used with MonthWeeksOfMonth and MonthDaysOfWeek parameters)
**MonthTimesOfDay** – at which time monthly backup should be taken
**RetentionMonths** - how many months monthly backup should be retained

 **RetentionYearlyPolicy** – whether to retain yearly backup point
**YearMonthsOfYear** – at which month of the year monthly backup should be taken  {January | February | March | April | May | June | July | August | September | October | November | December}]
**YearWeeksOfMonth** – at which week of the month yearly backup should be taken {First | Second | Third | Fourth | Last} (cannot be used with YearDaysOfMonth parameter, requires YearDaysOfWeek parameter)
**YearDaysOfWeek** – at which day of the week yearly backup should be taken {Sunday | Monday | Tuesday |Wednesday | Thursday | Friday | Saturday} (cannot be used with YearDaysOfMonth parameter, requires YearWeeksOfMonth parameter)
**YearDaysOfMonth** – at which day of month yearly backup should be taken (cannot be used with YearWeeksOfMonth and **YearDaysOfWeek** parameters)
**YearTimesOfDay** – at which time yearly backup should be taken
**RetentionYears** - how many years yearly backup should be retained

It is also shown in the Recovery Services Vault blade of Azure portal:
![back](https://user-images.githubusercontent.com/48041687/132682851-053373d4-78ee-4d0e-8cc0-6ebd398a982d.png)

Dear @e0i , I am not able to create PR to this article (looks like MSOnlineBackup module documentation is inaccessible), can you please reach the author of the article?

Thank you

**Comment by e0i** [comment]
@brandonfhall Unfortunately, The article has been relocated to a different repository that is not yet open source. I think the general repository for the [Microsoft Docs Feedback](https://github.com/MicrosoftDocs/feedback) would be an appropriate venue for this issue.

Thanks.
