### ISSUE TITLE
install on win10

### ISSUE THREAD

**Issue by jkcapoeira** [MicrosoftDocs/windows-powershell-docs#1986]
There are a few RSAT features in win10. But which feature installs the Install-ADServiceAccount cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1650140-0681-0614-11f5-f78121417e03
* Version Independent ID: f76cdcf9-1d64-ca27-e9de-bed8f2b3270d
* Content: [Install-ADServiceAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/Install-ADServiceAccount?view=win10-ps)
* Content Source: [docset/windows/addsadministration/Install-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Install-ADServiceAccount.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@j0rt3g4 Hello,

The cmdlet should be in the **RSAT: Active Directory Domain Services and Lightweight Directory Services Tools** feature. You can install it with the following command:
```powershell
Add-WindowsCapability -Name Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0 -Online
````
