### ISSUE TITLE
The description of the parameter -CimSession is missing in New-ScheduledTaskTrigger

### ISSUE THREAD

**Issue by meziantou** [MicrosoftDocs/windows-powershell-docs#199]
The description of the parameter -CimSession is missing in New-ScheduledTaskTrigger

> -CimSession: {{Fill CimSession Description}}

<https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cad6aa9-2504-d30a-9a51-984f52e4f9c8
* Version Independent ID: 84be6419-e750-a16e-70fc-85a3fb0d0569
* Content: [New-ScheduledTaskTrigger (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/new-scheduledtasktrigger.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/new-scheduledtasktrigger.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @meziantou thanks for notice! I created a PR to improve the article based on your suggestion.

Thank you

**Comment by yogkumgit** [comment]
@kenwith please merge this PR, if you find it suitable

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @meziantou Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
