### ISSUE TITLE
Get-SmbShare - Example 3 listed twice

### ISSUE THREAD

**Issue by neildeadman** [MicrosoftDocs/windows-powershell-docs#1995]
Example 3 is listed twice with the second being a slightly expanded version if the first. It adds `-Property *` to the end of the cmdlet in the fist Example 3.

**Comment by RAJU2529** [comment]
@neildeadman . Which article are you referring?

**Comment by neildeadman** [comment]
Hi, sorry, I figured the info in title would be sufficient. The article was this one: https://docs.microsoft.com/en-us/powershell/module/smbshare/get-smbshare?view=win10-ps

**Comment by RAJU2529** [comment]
@neildeadman Thanks for reply This command is applies to windows server OS.   I am familiar with that. so wait for some days , expert users will reply to you.

**Comment by velkovb** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1992
