### ISSUE TITLE
Get-SmbShare - Example 2 incorrect

### ISSUE THREAD

**Issue by neildeadman** [MicrosoftDocs/windows-powershell-docs#1996]
Example 2 of the Get-SmbShar cmdlet, states that you can specify the computer to search with PS `C:\>Get-SmbShare -Name "VMS1"`. This is incorrect. The -Name property is used to specify the share name you wish to search for. This is demostrated in other cmdlet examples.

**Comment by RAJU2529** [comment]
@neildeadman . which article are you referring?

**Comment by neildeadman** [comment]
Hi, sorry, I figured the info in title would be sufficient. The article was this one: https://docs.microsoft.com/en-us/powershell/module/smbshare/get-smbshare?view=win10-ps

**Comment by RAJU2529** [comment]
@neildeadman Thanks for reply This command is applies to windows server OS.   I am familiar with that. so wait for some days , expert users will reply to you.

**Comment by velkovb** [comment]
This has been already solved in https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1992
