### ISSUE TITLE
Undocumented: New-WBBackupTarget maximum Network Path is 110 characters

### ISSUE THREAD

**Issue by danielcecil** [MicrosoftDocs/windows-powershell-docs#1997]
On the `New-WBBackupTarget` page the `NetworkPath` parameter documentation does not include the limit of a maximum path length of 110 which is undocumented until the scenario is encountered.

Please modify the documentation to state that the maximum path length is 110 characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c1e145-6a61-9698-b615-55c0e88f1103
* Version Independent ID: 5f4b7bf2-a500-fd76-d2c5-bc35b7a8a9c9
* Content: [New-WBBackupTarget (windowsserverbackup)](https://docs.microsoft.com/en-us/powershell/module/windowsserverbackup/new-wbbackuptarget?view=win10-ps)
* Content Source: [docset/windows/windowsserverbackup/New-WBBackupTarget.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/windowsserverbackup/New-WBBackupTarget.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@danielcecil  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2048

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
