### ISSUE TITLE
Cannot resolve wildcard DNS record

### ISSUE THREAD

**Issue by smokydragon** [MicrosoftDocs/windows-powershell-docs#1999]
With Resolve-DnsName I cannot resolve a wildcard DNS record, it throws an error that there is an invalid character.
Example given with the DNS A record *.example.com

```
Resolve-DnsName -Name "*.example.com"

Resolve-DnsName : *.example.com : DNS name contains an invalid character
At line:1 char:1
+ Resolve-DnsName -Name "*.example.com"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (*.example.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_INVALID_NAME_CHAR,Microsoft.DnsClient.Commands.ResolveDnsName
```

Can you please add support for wildcard DNS records?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014fb5df-2480-2136-1257-2aade82e4c4a
* Version Independent ID: 38c0b3be-3aa8-7926-716c-aa28367d6df7
* Content: [Resolve-DnsName (dnsclient)](https://docs.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname?view=win10-ps)
* Content Source: [docset/windows/dnsclient/Resolve-DnsName.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsclient/Resolve-DnsName.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@smokydragon . example.com is not an domain name . 
Enter  microsoft.com  or  Adobe.com

**Comment by smokydragon** [comment]
@RAJU2529 it's not about the domain name used, I only used example.com according to RFC 2606 as an example to illustrate the problem. It is about the fact that a wildcard entry of any domain cannot be resolved because the wildcard character is considered an invalid character.
If you want to test a valid wildcard entry, the DNS A record *.surfly.com is publicly resolvable.

**Comment by RAJU2529** [comment]
@smokydragon . i also confirmed, wildcards are not accepted, So in future Microsoft  might be considered to add this feature in future

**Comment by MaratMussabekov** [comment]
Hello,
it is mentioned in the article that wildcards are not supported
![image](https://user-images.githubusercontent.com/48041687/97091111-bbdec400-1652-11eb-8922-93287ac89156.png)
Thank you
