### ISSUE TITLE
No link to documentation on the output object

### ISSUE THREAD

**Issue by cb55555** [MicrosoftDocs/windows-powershell-docs#2000]
Why is there no link to the documentation on the output object (i.e. Microsoft.Windows.ServerManager.Commands.Feature[])?

What good is this Cmdlet if we have no idea what it's returning?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed4918e-8ebc-6b11-17fa-8c9662065bab
* Version Independent ID: 8d17a25e-ea2d-71cb-8c7d-965a8851d83d
* Content: [Get-WindowsFeature (servermanager)](https://docs.microsoft.com/en-us/powershell/module/servermanager/get-windowsfeature?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@cb55555 Hello Chin,

Thank you for trying to make MicrosoftDocs a better place. 

Unfortunately, not all classes have detailed publicly available documentation. I was not able to find anything that could be linked to the output object for this article but you can get more information about the object inside PowerShell:
```powershell
PS C:\> Get-WindowsFeature | Get-Member


   TypeName: Microsoft.Windows.ServerManager.Commands.Feature

Name                      MemberType Definition
----                      ---------- ----------
Equals                    Method     bool Equals(System.Object obj), bool IEquatable[Feature].Equals(Microsoft.Windo...
GetHashCode               Method     int GetHashCode()
GetType                   Method     type GetType()
SetProperties             Method     void SetProperties(string displayName, string description, bool installed, Micr...
ToString                  Method     string ToString()
AdditionalInfo            Property   hashtable AdditionalInfo {get;}
BestPracticesModelId      Property   string BestPracticesModelId {get;}
DependsOn                 Property   string[] DependsOn {get;}
Depth                     Property   int Depth {get;}
Description               Property   string Description {get;}
DisplayName               Property   string DisplayName {get;}
EventQuery                Property   string EventQuery {get;}
FeatureType               Property   string FeatureType {get;}
Installed                 Property   bool Installed {get;}
InstallState              Property   Microsoft.Windows.ServerManager.Commands.InstallState InstallState {get;}
Name                      Property   string Name {get;}
Notification              Property   Microsoft.Windows.ServerManager.ServerComponentManager.Internal.Notification[] ...
Parent                    Property   string Parent {get;}
Path                      Property   string Path {get;}
PostConfigurationNeeded   Property   bool PostConfigurationNeeded {get;}
ServerComponentDescriptor Property   psobject ServerComponentDescriptor {get;}
SubFeatures               Property   string[] SubFeatures {get;}
SystemService             Property   string[] SystemService {get;}

```

Let me know this is useful and if you have any questions.

**Comment by e0i** [comment]
Hello @cb55555 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation.

Thanks.
