### ISSUE TITLE
-PhysicaldiskIds parameter

### ISSUE THREAD

**Issue by stephc-msft** [MicrosoftDocs/windows-powershell-docs#2006]
Server2019 has -PhysicalDisk  and  -PhysicalDiskGuid options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c7a7fb-cf6d-3a63-a0d9-21f5f77b88c2
* Version Independent ID: a8cb92af-9176-698b-bfcd-03c1900fbe53
* Content: [Set-ClusterStorageSpacesDirectDisk (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterstoragespacesdirectdisk?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/Set-ClusterStorageSpacesDirectDisk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/Set-ClusterStorageSpacesDirectDisk.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by MaratMussabekov** [comment]
Hello, @stefanie-msft ,
i've made some research, and found out following:
1. as it was already mentioned, PhysicalDiskIds parameter was replaced by PhysicalDisk and PhysicalDiskGuid. PhysicalDisk accepts values of CimInstance#MSFT_PhysicalDisk class (it is a class of output of Get-PhysicalDisk cmdlet), and PhysicalDiskGuid accepts GUID strings. These parameters cannot be used with each other.
2. Also, it has a new Reset parameter (without value)
3. There is also CacheUsage parameter, that accepts following values: NonHybrid, Capacity, Cache, Auto

So, the syntax is following:
```
Set-ClusterStorageSpacesDirectDisk -PhysicalDiskGuid <string[]> [-CanBeClaimed <Boolean>] [-Reset] [-CacheUsage {NonHybrid | Capacity | Cache | Auto}] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
```

```
Set-ClusterStorageSpacesDirectDisk -PhysicalDisk <CimInstance#MSFT_PhysicalDisk[]> [-CanBeClaimed <Boolean>] [-Reset] [-CacheUsage {NonHybrid | Capacity | Cache | Auto}] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
```

Dear @e0i, would it be possible to contact the author of the article. It needs to be rewritten, as syntax, examples and parameters sections are incorrect? I cannot do it myself, as information about these parameters is not available in public sources.

Thank you

**Comment by e0i** [comment]
Server 2019 content is not covered yet. Thank you.

**Comment by MaratMussabekov** [comment]
Hello @e0i,
then we should just ignore it? Should I just close my PR?
Thank you

**Comment by MaratMussabekov** [comment]
Hello @e0i,
may be I should add a note that WS 2019 is not covered yet? can we ask article owner about it?
Thank you
