### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by ikishko** [MicrosoftDocs/windows-powershell-docs#201]
In the example above, you have parameter $true after NewConnectionAllowed. Instead of $true or $false it has to be yes, no or NotUntilReboot. A lot of people simply look at examples and don't read the full help so changing example will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c057372a-61ec-02a1-b041-434f801dae88
* Version Independent ID: 754c7b03-6e95-b8ae-d4cf-0f8590da6ceb
* Content: [Set-RDSessionHost (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/set-rdsessionhost?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/remotedesktop/Set-RDSessionHost.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/remotedesktop/Set-RDSessionHost.md)
* Service: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
officedocsbot close

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by Arefu** [comment]
This is still a problem.
