### ISSUE TITLE
-AccessRight parameters incorrect for Server 2012 R2

### ISSUE THREAD

**Issue by clamb123** [MicrosoftDocs/windows-powershell-docs#2011]
[Enter feedback here]
The -AccessRight parameter says:
Specifies the access right to grant to the trustee. The acceptable values for this parameter are: Full, **Modify**, or Read.

Modify is not a valid parameter it should be Change (as it is on the Windows 10/2016 version of the doc. And in Example 2 on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e6d05fb-162b-a6e6-a090-71c142b27d09
* Version Independent ID: 5df21647-a94e-09f0-4264-c7de75da6ab3
* Content: [Grant-SmbShareAccess (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/grant-smbshareaccess?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/smbshare/Grant-SmbShareAccess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/smbshare/Grant-SmbShareAccess.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@e0i . Assign user to verify the PR soon.
