### ISSUE TITLE
ServicePrincipalNames parameter help for New-ADUser is partially incorrect

### ISSUE THREAD

**Issue by SeanQuinlan** [MicrosoftDocs/windows-powershell-docs#2014]
The parameter help for ServicePrincipalNames in the New-ADUser page is partially incorrect. The help states that you can supply a hashtable to add/remove/replace SPN values, however this syntax only applies to Set-ADUser. You cannot use a hashtable for ServicePrincipalName on New-ADUser.

In my testing I could only get it to accept a string or array of strings (or $null), so the help for this parameter should be updated to remove the incorrect hashtable part.

The same issue applies to New-ADComputer (https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-adcomputer?view=win10-ps) and the same parameter help could be used there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6ebf4ba-70b6-f3d8-eedd-c083873000f4
* Version Independent ID: a4b3e99d-a16e-eac5-4895-f1a9e5083185
* Content: [New-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/New-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/New-ADUser.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@SeanQuinlan  Thank you for your feedback. We have made changes to the dov via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2049

Thanks
Sri
