### ISSUE TITLE
Required elevation?

### ISSUE THREAD

**Issue by martinbherbener** [MicrosoftDocs/windows-powershell-docs#2015]
Hi,

It appears that this cmdlet requires elevation ("as administrator"), at least if run on the server on which the service account is to be installed.  If that's true, can it be mentioned in the documentation?

thanks!

Martin

**Comment by RAJU2529** [comment]
@martinbherbener . Which article are you referring? Which cmdlet are you referring?

**Comment by martinbherbener** [comment]
install-adserviceaccount; https://docs.microsoft.com/en-us/powershell/module/addsadministration/install-adserviceaccount

thanks

Martin

> 
> 
> @martinbherbener . Which article are you referring? Which cmdlet are you referring?

**Comment by RAJU2529** [comment]
@martinbherbener . sorry i am not familiar with server OS, so let wait for few days to get replies from expert users.

**Comment by MaratMussabekov** [comment]
Hello, checked and confirmed.
I created PR #2203 to add this information.
Thank you
