### ISSUE TITLE
New-CIPolicyRule -AppID parameter is not documented

### ISSUE THREAD

**Issue by jdotmac** [MicrosoftDocs/windows-powershell-docs#2016]
When building WDAC rules I have noticed an -AppID parameter is available (win10 1909+) but there is no documentation on its use

Get-Help New-CIPolicyRule 

New-CIPolicyRule -DriverFilePath c:\somepath\some.exe -AppID c:\someapp.exe -Deny

**Comment by RAJU2529** [comment]
@jdotmac . Which article are you referring?.

**Comment by jdotmac** [comment]
https://docs.microsoft.com/en-us/powershell/module/configci/new-cipolicyrule?view=win10-ps
or 
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/configci/New-CIPolicyRule.md

**Comment by e0i** [comment]
This is a known issue with the updatable help pipeline that affects the `Get-Help` and `Update-Help` commands.

There are ongoing efforts to rework the publishing engine. Once matured, failures to update modules are also going to be addressed. Internal sources inform us, the independent collaborators that it is going to take a lot of work.

There have been multiple reports of the help commands not working so please refer to issue #2247 for tracking the progress of this situation.

Thank you.
