### ISSUE TITLE
Enabled Accounts

### ISSUE THREAD

**Issue by bmcmcm** [MicrosoftDocs/windows-powershell-docs#2017]
One of the most common needs for Get-AdUser is getting enabled accounts. This ought to be a function in Get-AdUser, like -Enabled, but in lieu of that, the documentation should have an example:

Get-ADUser -LDAPFilter "(!userAccountControl:1.2.840.113556.1.4.803:=2)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a4eb77a-834c-0412-8f9f-9c515172237e
* Version Independent ID: 0228a754-2177-71d0-92cc-ae144070947e
* Content: [Get-ADUser (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Get-ADUser.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@AndreaBarr . Will you  look in to this issue #2017.

**Comment by doctordns** [comment]
This is a really good point - which came up only yesterday in real life.

I have added an example to show this #2145. 

I also agree a **-Enabled** switch on Get-ADUser would be useful.

**Comment by RAJU2529** [comment]
@e0i . Assign user
