### ISSUE TITLE
Error thrown saying "New-IISSiteBinding" is not recognized

### ISSUE THREAD

**Issue by mkvalluri** [MicrosoftDocs/windows-powershell-docs#202]
While I was trying the cmdlets, New-IISSite works, but all the commands related to site bindings aren't working and an error is thrown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e957bb9-36da-79ad-f331-fbc5c19372a8
* Version Independent ID: 01435b2d-4b32-1529-25d1-ff25aa6ab6ac
* Content: [New-IISSiteBinding (iisadministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/New-IISSiteBinding?view=win10-ps)
* Content Source: [docset/windows/iisadministration/new-iissitebinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/iisadministration/new-iissitebinding.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by mkvalluri** [comment]
NM. Had to install latest version of IISAdministration to get this functionality.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @mkvalluri thanks for your feedback.
I created a PR to improve the documentation based on your comments.
**Thank you**

**Comment by yogkumgit** [comment]
@kenwith please merge this PR, if you find it suitable

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @mkvalluri Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
