### ISSUE TITLE
Link not found

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-powershell-docs#2022]
About updatable  help link is not found.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8c568e-c769-7534-f56c-98a1e8d77a2f
* Version Independent ID: 95937601-fdb4-ea5f-a50f-9decc46a68cb
* Content: [Microsoft Desktop Optimization Pack Automation with Windows PowerShell](https://docs.microsoft.com/en-us/powershell/mdop/get-started?view=win-mdop2-ps)
* Content Source: [docset/docs-conceptual/mdop/get-started.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/docs-conceptual/mdop/get-started.md)
* Product: **w10**
* Technology: **powershell-mdop**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@AndreaBarr . i have received error message  **Some checks haven’t completed yet**, so please look into this PR #2023

**Comment by e0i** [comment]
@RAJU2529 Please don't tag staff members as issues are being handled within a queue. It has been over a year since Andrea has retired from the project.

**Comment by e0i** [comment]
Closing via #2023
