### ISSUE TITLE
Get-vhd on a live vhdx

### ISSUE THREAD

**Issue by stephc-msft** [MicrosoftDocs/windows-powershell-docs#2024]
If the vhd/vhdx is in use, then can only run get-vhd on the system that has the vhd loaded or is running the VM that is using the vhd.
All other systems eg other nodes of a cluster with vhd's on shared storage, will give "The operation cannot be performed while the object is in use"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de2b1ce-c9e0-f7be-d8f1-9eb0ebd82677
* Version Independent ID: 776cd256-d681-539c-999e-e281be147647
* Content: [Get-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/get-vhd?view=win10-ps)
* Content Source: [docset/windows/hyper-v/Get-VHD.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/Get-VHD.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by stephc-msft** [comment]
Same if the vhd/vhdx is on a fileshare and accessed over UNC. If in use only the system using it can successfully run get-vhd. All others get "The operation cannot be performed while the object is in use" as expected.

**Comment by velkovb** [comment]
@stephc-msft Hello,

Thank you for your feedback.

Isn't this the desired behavior? 

In my understanding the VHD file is locked by the VM that is using it to avoid corruption. I guess you want to still be able to get the VHD metadata?

**Comment by stephc-msft** [comment]
Correct it is locked, but can be accessed via get-vhd from the system that is using it
This comment is to clarify that get-vhd from anywhere else will fail with object in use, as expected
Particularly when the vhd is on an smb share or a CSV

**Comment by velkovb** [comment]
Thank you for the clarification. I will update the article with a note.
