### ISSUE TITLE
-WhatIf don't work ?

### ISSUE THREAD

**Issue by PatLaPoint** [MicrosoftDocs/windows-powershell-docs#2025]
Hi!

When i ran add-printer with -WhatIf it installed the printers.
Windows server 2016 thats running powershell: 

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.3471                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.3471                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

Code: 

```
$Printers = Get-Content "C:\Temp\Printers.txt"
foreach ($Printer in $Printers){
    Add-Printer -ConnectionName "\\<PrintServer>\$Printer" -WhatIf
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd101ba3-1914-7d49-6fdb-b353eae72630
* Version Independent ID: 72a1a4dd-e6e7-3ff6-640f-05bbbfb0680f
* Content: [Add-Printer (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/add-printer?view=win10-ps)
* Content Source: [docset/windows/printmanagement/Add-Printer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/printmanagement/Add-Printer.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@PatLaPoint THank you for your feedback. We are looking into this and shall update you shortly.
