### ISSUE TITLE
Add-InsightsCapability fails when Perfgen.dll is modified 

### ISSUE THREAD

**Issue by agvardha** [MicrosoftDocs/windows-powershell-docs#2029]
With the original Perfgen.dll Add-InsightsCapability works fine. You add one line of code to PerfGen.c and rebuild PerfGen.dll then  Add-InsightsCapability fails.
PS C:\Windows\System32> Add-InsightsCapability -Name SampleSysInsight -Library C:\KCSCapability.dll -Confirm:$false
Add-InsightsCapability : System Insights failed to register one or more of data sources for capability 'SampleSysInsight'.
At line:1 char:1
+ Add-InsightsCapability -Name SampleSysInsight -Library C:\KCSCapabili ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (SampleSysInsight:String) [Add-InsightsCapability], Exception
    + FullyQualifiedErrorId : SystemInsightsError,Microsoft.SystemInsights.Management.PowerShell.AddInsightsCapabilityCommand

 It is as though Add-InsightsCapability remembers a checksum of the original Perfgen.dll and fails. Just does not make sense. The error messages don't say much. 

Another related question unless I start Perfmon Add-InsightsCapability does not succeed. So Add-InsightsCapability has a pre-requisite that Perfmon should be running. This also does not make sense. 

Please hel;p
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a606dc-b52c-5b24-8c0c-ff57f48dd8cd
* Version Independent ID: cfb93dbb-6b10-dee0-e6ec-77c0c95e4d5f
* Content: [Add-InsightsCapability](https://docs.microsoft.com/en-us/powershell/module/systeminsights/add-insightscapability?view=win10-ps)
* Content Source: [docset/windows/systeminsights/Add-InsightsCapability.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/systeminsights/Add-InsightsCapability.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by agvardha** [comment]
Hi Onur,

I just realized all Perfmon does is load Perfgen.dll. mmc.exe loads Perfmon and that loads Perfgen.dll. So my assumption of Perfmon being a requisite is wrong. I can write my own abcd.msc and make it load Perfgen.dll for that matter. So now my question boils down to why Add-InsightsCapability() fails on modified Perfgen.dll. Perfgen.dll is a MSFT provided sample please Google for details.

**Comment by sdwheeler** [comment]
This is a product question that is out of scope for this documentation. Please submit your issue to https://windowsserver.uservoice.com/forums/301869-powershell
