### ISSUE TITLE
add to Reslove-DnsName mDNS (multicast DNS) capability 

### ISSUE THREAD

**Issue by mepinto** [MicrosoftDocs/windows-powershell-docs#2038]
I think that if Resolve-DnsName would have the mDNS option it can be very useful just like the -LlmnrOnly. It's seems that dnsapi.dll(which is used by Resolve-DnsName) already implements mDNS .
mDNS is very common on local network and can help researchers in a lot of situations.

**Comment by e0i** [comment]
@mepinto 

The issue tracker of this repository is intended for product documentation issues only.

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)


Thanks.
