### ISSUE TITLE
MultipleInstancesEnum not described

### ISSUE THREAD

**Issue by colinangusmackay** [MicrosoftDocs/windows-powershell-docs#204]
There is a parameter called `-MultipleInstances` the type of which is `MultipleInstancesEnum`, however this type is not described, nor it is linked to. The upshot of this is that I don't know what are the valid values for the `MultipleInstances` parameter and what each value means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01873db6-65ca-a11d-442d-0836caca5d8e
* Version Independent ID: a1c11fee-27d9-0267-5a7a-6e0acca5d306
* Content: [New-ScheduledTaskSettingsSet (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasksettingsset?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/new-scheduledtasksettingsset.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/new-scheduledtasksettingsset.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by bladeoflight16** [comment]
The valid values can be found in the "Accepted values" row of the table below the parameter. Currently, they are `Parallel`, `Queue`, `IgnoreNew`. But yes, the meanings need to be documented.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @colinangusmackay thanks for your feedback.
A PR has been created to improve the article based on your suggestion.
Thank you!

**Comment by yogkumgit** [comment]
@kenwith please merge this PR, if you find it suitable

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @colinangusmackay Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by colinangusmackay** [comment]
Thank you. It is much appreciated.

**Comment by Rob-S** [comment]
It was noted above that:
> "Stop the existing instance" from the Task Scheduler UI conspicuously has no enum value.

Value in Task Scheduler Interface: Stop the existing instance
Value in Task XML file: StopExisting
Meaning: Kill the process for the currently running instance

That value is missing from the ` Microsoft.PowerShell.Cmdletization.GeneratedTypes.ScheduledTask.MultipleInstancesEnum` but is needed for [ComputerManagementDsc Issue#333 ScheduledTask: MultipleInstances Parameter Should Allow For 'StopExisting'](https://github.com/dsccommunity/ComputerManagementDsc/issues/333)

Question: **Where do we file the bug issue for that?**
