### ISSUE TITLE
ObjectNotFound: (MSFT_FSRMQuota:Root/Microsoft/.../MSFT_FSRMQuota) [New-FsrmQuota]

### ISSUE THREAD

**Issue by lucygoldbergmicrosoft** [MicrosoftDocs/windows-powershell-docs#2042]
When I run New-FsrmQuota in VM with Custom Image that has FSRM feature pre-installed, I run into the following exception. Any idea why? Where is the dll located for FSRM powershell commands? I guess the exception means that the dll is not loaded

New-FsrmQuota : Not found
At line:1 char:1
+ New-FsrmQuota
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_FSRMQuota:Root/Microsoft/.../MSFT_FSRMQuota) [New-FsrmQuota], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041002,New-FsrmQuota

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80260d74-bb70-2cb0-93d3-91b42b2d0c9f
* Version Independent ID: d377c1f6-6617-c915-84b8-dc02ba6bd2cc
* Content: [New-FsrmQuota (fileserverresourcemanager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/new-fsrmquota?view=win10-ps)
* Content Source: [docset/windows/fileserverresourcemanager/New-FsrmQuota.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/fileserverresourcemanager/New-FsrmQuota.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
It seems that this question can best be answered via [PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.

Thanks again.
