### ISSUE TITLE
How Do I Read the Output Of "Get-FSRMClassificationule" ?

### ISSUE THREAD

**Issue by Dan-Stafford** [MicrosoftDocs/windows-powershell-docs#2043]
[I'm lost on how to read the output of this command and am having difficulty finding any explanations or guides to this online.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 670f20be-20b8-4c6c-274f-6be44077f06c
* Version Independent ID: a0f28447-f233-8449-814a-f490a05a280c
* Content: [Set-FsrmClassificationRule (fileserverresourcemanager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/set-fsrmclassificationrule?view=win10-ps)
* Content Source: [docset/windows/fileserverresourcemanager/Set-FsrmClassificationRule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/fileserverresourcemanager/Set-FsrmClassificationRule.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@Dan-Stafford Hello Dan,

You have opened this issue on the [Set-FsrmClassificationRule (fileserverresourcemanager)](https://docs.microsoft.com/powershell/module/fileserverresourcemanager/set-fsrmclassificationrule?view=win10-ps) but you are referencing the [Get-FSRMClassificationule](https://docs.microsoft.com/powershell/module/fileserverresourcemanager/get-fsrmclassificationrule?view=win10-ps) cmdlet. Which is the correct article?

Thanks.

**Comment by e0i** [comment]
@Dan-Stafford Please follow up with the question above so that we can proceed with a fix. Thank you.

**Comment by Dan-Stafford** [comment]
Hi, Borislav, and thank you for responding.

I am currently studying for 70-412 certification and to be honest I forgot
the question. It's a lot of information to digest and I have been at it for
a few months.

I would say at this point please disregard.

Regards,

Dan Stafford
Senior IT Instructor


20-697
<https://www.youracclaim.com/badges/9351f53d-0f51-4c02-8cc6-12f135faedb8>
              20-698
<https://www.youracclaim.com/badges/01400e30-8d7f-476c-8d0f-390abce3d025>
             Win 10 MCSA
<https://www.youracclaim.com/badges/65c9a38f-7c6b-4d5b-8b5e-2b5d9a5ca970>
   70-410
<https://www.youracclaim.com/badges/3d737a46-7f0b-4865-a15c-a3739e7477af>
