### ISSUE TITLE
Clarify usage of the TaskPath Parameter

### ISSUE THREAD

**Issue by Kriegel** [MicrosoftDocs/windows-powershell-docs#2045]
Module:  scheduledtasks

My expectation was that i can pass a TaskPath without any slash. 'ThePathName'
Got an Error

So I tried an TaskPath with an Slash in front '\ThePathName'
Got an Error

i never, never thought that i have to provide a slash in Front and in back. '\ThePathName\\'

Even the Examples are not clear because they use an Star ...  '\ThePathName\\*'

so please clarify usage of the TaskPath Parameter

**Comment by RAJU2529** [comment]
@Kriegel. Which article are you referring

**Comment by Kriegel** [comment]
In the past the Articles got referenced automatically, because I have started the issue from the Article.

But in this case i must not reference a single article,
because **many cmdlets of the PowerShell  scheduledtasks Module** (which i have mentioned) **are using the -TaskPath Parameter.**

here is the one i started from:
https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/get-scheduledtask?view=win10-ps

**Comment by RAJU2529** [comment]
@Kriegel. taskpath parameter will be with this cmdlet ** New-ScheduledTask**  
for more information, see below link 
**https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtask?view=win10-ps**

**Comment by Kriegel** [comment]
@RAJU2529 

Following your Link,
at the documenting page of 'New-ScheduledTask' I did not found neither the '-TaskPath' not a '-Path' parameter.

So what should I do with your statement?

**Comment by RAJU2529** [comment]
@Kriegel , see below page 

**https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/set-scheduledtask?view=win10-ps**

**Comment by Kriegel** [comment]
@RAJU2529 
Do you ever proof your statements before posting it ?

in your Link to the 'Set-ScheduledTask' cmdlet there is a documentation for the Parameter '-TaskPath' but this documentation is lacking any needful Information.

please see attached Screen shot:
![TaskPath](https://user-images.githubusercontent.com/1510464/87141055-bb3c4080-c2a2-11ea-9f58-502cf32ff3e2.PNG)

I think ALL documented cmdlets in  Module: scheduledtasks need an overhaul  to clarify the usage of the '-TaskPath' Parameter.


I think to do this overhaul cost less work then this discussion here.

**Comment by e0i** [comment]
@Kriegel 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by Kriegel** [comment]
Thank you @e0i @velkovb @tiburd  documentation looks great now!
Better than I excpected!
Stay well!
Live long and prosper.
