### ISSUE TITLE
Spelling mistake on the "Module" name (screenshot)

### ISSUE THREAD

**Issue by billduvall** [MicrosoftDocs/windows-powershell-docs#2046]
The module name is misspelled under the page title, see screenshot.

![image](https://user-images.githubusercontent.com/12448038/86936302-70d08d80-c103-11ea-8a1f-933e0aebe600.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95401782-16b2-2fa5-7146-7051c0ac5163
* Version Independent ID: 1f7fd84b-0c0c-5954-8666-18c3dec674e4
* Content: [New-WebBinding (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-webbinding?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/New-WebBinding.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sdwheeler** [comment]
Fixed some time ago.
