### ISSUE TITLE
Cmdlet no longer working in windows version 1803

### ISSUE THREAD

**Issue by sysadminman** [MicrosoftDocs/windows-powershell-docs#205]
I've been using this command to generate certs from my local CA. I noticed that with the 1803 update, this command now errors out. It runs fine in any version of windows before 1803. I even mirrored the first example for testing, and it gives the same error:

$up = Get-Credential
Get-Certificate -Template "templatename" -Url ldap:///CN="My CA" -Credential $up -CertStoreLocation cert:\LocalMachine\My

It gives this error: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6ca4f9-e80f-780e-f8f1-975ae4ec1fae
* Version Independent ID: 1b4e0706-71ba-c218-3b03-f9c5c456b95d
* Content: [Get-Certificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/get-certificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/get-certificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/get-certificate.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by jordanmills** [comment]
I'm seeing the same thing on 1607.

**Comment by sysadminman** [comment]
https://social.technet.microsoft.com/Forums/windows/en-US/fc7162ed-c83a-4e41-bf2e-1e52158b99a2/windows-10-build-1803-unable-to-request-enterprise-ca-computer-certificates

https://old.reddit.com/r/SCCM/comments/9687cb/are_you_deploying_windows_10_1803_do_your/

Looks like they have a patch coming out later this month to fix it.

**Comment by e0i** [comment]
Hello, @sysadminman It looks like your question has been answered and the issue can be closed. Please re-open this issue if you are still experiencing problems.

Thank you for your feedback.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure._
