### ISSUE TITLE
Management Point Network Type Missing

### ISSUE THREAD

**Issue by ryanjadams** [MicrosoftDocs/windows-powershell-docs#2051]
The cmdlet parameter for MangementPointNetworkType is missing.  It should probably look something like this.

 -ManagementPointNetworkType {(Singleton: Traditional Name/IP) (Distributed: Uses node IPs) (Automatic: Default option that detects on-prem or Azure)}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09665332-491a-2c15-5f58-f871b8a8508d
* Version Independent ID: 927d6f40-42df-f07d-3c0c-2720bb84faa3
* Content: [New-Cluster (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/new-cluster?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/New-Cluster.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/New-Cluster.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@ryanjadams Hi Ryan,

Thank you for trying to make MicrosoftDocs a better place. Unfortunately, we have sections only for 2012, 2012 R2 and 2016. The parameter that you are referring to has been added in 2019 so we cannot do anything at the moment. When articles for 2019 are added I am sure the parameter will be present.

Let me know if you have any questions.

**Comment by e0i** [comment]
Hello @ryanjadams 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation.

Thanks.
