### ISSUE TITLE
New-Cluster has a flag, -s2d without info.

### ISSUE THREAD

**Issue by dharrison27** [MicrosoftDocs/windows-powershell-docs#2053]
The docs.microsoft.com isn't very helpful, some people in the official PS discord said they think it's to enable s2d immediately when creating a new cluster without having to run 
```
New-Cluster
Enable-ClusterStorageSpaceDirect
```
one after the other.

If this is the case then the docs could do with an update or if it is depreciated, then with a warning note or something.

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09665332-491a-2c15-5f58-f871b8a8508d
* Version Independent ID: 927d6f40-42df-f07d-3c0c-2720bb84faa3
* Content: [New-Cluster (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/new-cluster?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/New-Cluster.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/New-Cluster.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@dharrison27 
Thank you for your feedback.

The `-S2D` switch is for creating the cluster and enabling Storage Space Direct in one go.  I will update the description of the parameter.
