### ISSUE TITLE
Do we have a PowerShell to install a new language from internet?

### ISSUE THREAD

**Issue by jinlinxu** [MicrosoftDocs/windows-powershell-docs#2055]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60add7a6-f647-225f-7870-a073ec356b07
* Version Independent ID: c6d95f15-80d1-11a8-30db-a7ddf0a36dc3
* Content: [International](https://docs.microsoft.com/en-us/powershell/module/international/?view=win10-ps)
* Content Source: [docset/windows/international/International.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/international/International.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@jinlinxu Would you be able to clarify what needs to be updated within the documentation? Thank you.

**Comment by MaratMussabekov** [comment]
Hello,
there is no cmdlet that allows to download additional languages.
You can only do it using DISM tool
Thank you
