### ISSUE TITLE
0 is invalid for AccountExpirationDate in New-ADServiceAccount

### ISSUE THREAD

**Issue by mainred** [MicrosoftDocs/windows-powershell-docs#2059]
As documented in [AccountExpirationDate of New-ADServiceAccount](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md#-accountexpirationdate)
_When you set this parameter to 0, the account never expires. This parameter sets the AccountExpirationDate property of an account object_
However, in practise, 0 is not a valid value for AccountExpirationDate, with DateTime type.

**Comment by velkovb** [comment]
@mainred Hi Qingchuan,

Thank you for your feedback.

Very good catch, 0 does not work. If you want to have never expires when creating the account you should not specify the _AccountExpirationDate_ parameter at all. Setting the account to never expires is done with the **Clear-ADAccountExpiration** cmdlet. This is true not only for service accounts but for other objects like users and computers. I will work on updating this in the documentation.
