### ISSUE TITLE
So, what is a DNS Server Virtualization Instance?

### ISSUE THREAD

**Issue by Brain2000** [MicrosoftDocs/windows-powershell-docs#206]
At this time, this page is the ONLY page that references this command in all of Google and Bing.  Therefore, the circular reference documentation is fantastic:

Q: What does Add-DnsServerVirtualizationInstance do?
A: It adds  a DNS Virtualization Instance.

Q: What is a DNS Virtualization Instance?
A: It is something added by Add-DnsServerVirtualizationInstance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f93d5587-9805-c56c-f455-f85c5557117c
* Version Independent ID: 10f4b382-bdb4-1eb3-0f10-d824d1c3cd25
* Content: [Set-DnsServerVirtualizationInstance (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/set-dnsservervirtualizationinstance?view=win10-ps)
* Content Source: [docset/windows/dnsserver/set-dnsservervirtualizationinstance.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/set-dnsservervirtualizationinstance.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Brain2000 thanks for your feedback.
Description explaining what is a DnsVirtualizationInstance has been added to this article https://docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsservervirtualizationinstance?view=win10-ps after you posted this issue.
Hope this information helps you.
Thanks!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Brain2000 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by doctordns** [comment]
I am researching this topic - and it would have been good to have had more than a couple of sentences to describe this feature.

A worked example would really help!
