### ISSUE TITLE
Problem using New-NetTransportFilter on W10 professional

### ISSUE THREAD

**Issue by janhec** [MicrosoftDocs/windows-powershell-docs#2061]
In spite of applying to W10 according to page, New-NetTransportFilter cannot be applied in W10 professional.
The response is "New-NetTransportFilter : This feature is available on servers only."
As I occasionally open a postgresql server port for testing purposes, it performs horribly slow (like 10 kb/second) on an internet connection with latency about 10 ms and real life upload speeds of 5 MB/s. (no, not MBits, MBytes).
Creating a specific TCP setting (like Datacenter) would therefore be my first attempt at resolving this.
It does not appear possible.
Q: How, except by spending useless $$ and reinstalling my OS (or setting up a linux box), do I specify a TCP setting that does not interfere with the automatic Internet setting?
Q: if I cannot use a specific TCP setting, what non-trivial advice can you give me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220e2839-bec3-d79f-4630-f77dfcc4b721
* Version Independent ID: d24b090e-1d76-5794-92c7-a9b053ad3a1b
* Content: [New-NetTransportFilter (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/new-nettransportfilter?view=win10-ps)
* Content Source: [docset/windows/nettcpip/New-NetTransportFilter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nettcpip/New-NetTransportFilter.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by janhec** [comment]
Comment:
Get-NetTCPSetting reveals Automatic, Internet, InternetCustom, Datacenter, DatacenterCustom, Compat.
I will start by trying to apply one and if necessary, alter one (probably not).
So, If things work out, I may close this issue soon.

**Comment by janhec** [comment]
No,  cannot close, since New-NetTransportFilter is necessary.

**Comment by velkovb** [comment]
@janhec Hi,

While the article says Windows 10 and Server 2016 it does not mean all cmdlets work on both, there are purely server cmdlets in this section as well. It is more about the PowerShell version. Unfortunately, I was not able to find a way to set this setting on client OS. I tried with WMI and get the same error:
```powershell
PS C:\> New-CimInstance -ClassName MSFT_NetTransportFilter -Namespace ROOT/StandardCimv2 -Property @{SettingName="Datacenter";DestinationPrefix="192.168.0.0/16";Protocol=[uint16]6}
New-CimInstance: This feature is available on servers only.
```
