### ISSUE TITLE
Please add more examples for the ssl case

### ISSUE THREAD

**Issue by h3ct0rjs** [MicrosoftDocs/windows-powershell-docs#2063]
Hi everybody. 

Recently I was working to deploy automatically a few sites, when I was reading the examples is only one example and it works pretty well, but we can add more examples for website that are running under https protocol. 

Thank you very much, 
Sincerely, 
H

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95401782-16b2-2fa5-7146-7051c0ac5163
* Version Independent ID: 1f7fd84b-0c0c-5954-8666-18c3dec674e4
* Content: [New-WebBinding (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-webbinding?view=winserver2012-ps&redirectedfrom=MSDN&viewFallbackFrom=winserver2012r2-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/New-WebBinding.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by h3ct0rjs** [comment]
hey @e0i  how are you 😃 , hope you're doing well. I was wondering if you need anything,  I'm still looking for more powershell examples but I wasn't lucky with this one

**Comment by e0i** [comment]
@h3ct0rjs The issue has been in the backlog and is going to be addressed soon. Thank you.

**Comment by h3ct0rjs** [comment]
Hi @tiburd, 
Nice work, I was wondering if currently there is an option to specify the ssl certificate or how should I address this part. 

Best Regards, 
_H_
