### ISSUE TITLE
Enable-NetFirewallRule -Group "@FirewallAPI.dll,-28502"

### ISSUE THREAD

**Issue by RNalivaika** [MicrosoftDocs/windows-powershell-docs#2068]
Question about document: https://docs.microsoft.com/en-us/powershell/module/netsecurity/enable-netfirewallrule?view=win10-ps

Quote "Enable-NetFirewallRule -Group "@FirewallAPI.dll,-28502"
This example enables all of the File and Printer Sharing rules. Use the universal and world-ready indirect string @FirewallAPI to specify the group." end of quote.

What is "universal and world-ready indirect string @FirewallAPI" and where do I get more documentation on this ?

**Comment by velkovb** [comment]
Hi @RNalivaika 

Thank you for trying to make MicrosoftDocs a better place.

From my understanding and indirect string is something like a map in the developers world. Here is a article giving more info about it in the Windows Firewall context:
[INetFwRule::put_Grouping method (netfw.h)](https://docs.microsoft.com/windows/win32/api/netfw/nf-netfw-inetfwrule-put_grouping)

Let me know if that answers your questions.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
