### ISSUE TITLE
New-ADFineGrainedPasswordPolicy - UnClear How To Lockout duration to Administrator unlock

### ISSUE THREAD

**Issue by MarkHobart** [MicrosoftDocs/windows-powershell-docs#2075]
It is not clear how to set a lockout policy that requires the adminsitrator to unlock the account.

This appears to work however when you look at the created policy in the Active Directory Administrative centre the requred field "Reset failed logon attempts count after (mins)" is empty.

New-ADFineGrainedPasswordPolicy -name "HighlyPrivilegedGroups1111" -Precedence 10 -MinPasswordLength 15 -PasswordHistoryCount 24 -ComplexityEnabled $true -ReversibleEncryptionEnabled $false -ProtectedFromAccidentalDeletion $true -MinPasswordAge 1 -MaxPasswordAge 42 -LockoutDuration "00:00:00" -LockoutThreshold 3 -LockoutObservationWindow "00:00:00"

**Comment by velkovb** [comment]
@MarkHobart Hi Mark,

Thanks for your feedback.

If you want to have manual unlock of the account you have to set the LockoutDurtation to 0. Here is a reference: [Account lockout duration](https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/account-lockout-duration)
I will work on adding such an example.
