### ISSUE TITLE
-Signer parameter

### ISSUE THREAD

**Issue by G-Squared-NL** [MicrosoftDocs/windows-powershell-docs#208]
I tried to use the CN= notation to indicate which certificate to sign the new self-signed certificate with to no avail.
What works but wasn't clear (to me at least) is to use the thumbprint of the signing certificate instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80b6f8a-6227-63cb-391f-bd3324a57251
* Version Independent ID: e3ce9f6c-ae5f-9b4b-2d3b-d709e886c01c
* Content: [New-SelfSignedCertificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/New-SelfSignedCertificate?view=win10-ps#optional-parameters)
* Content Source: [docset/windows/pkiclient/new-selfsignedcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/new-selfsignedcertificate.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by pzprovi** [comment]
With -Signer parameter you can create a client certificate that is signed by the first(root) CA certificate. This is equal to old command:
makecert.exe -pe -ss My -sr CurrentUser -a sha1 -sky exchange -n $Subject -eku 1.3.6.1.5.5.7.3.2 -sk SignedByCA -ic $issuedTo+".cer" -iv $issuedTo+".pvk"

or you can use "itisscg.exe" with UI

**Comment by pzprovi** [comment]
To set "CN=" you need to use -Object.
To set  "dns:"  array of string you need to use -SAN

**Comment by e0i** [comment]
@G-Squared-NL Thank you for your contribution. It seems that your question has been answered. Feel free to re-open this issue if you feel that it hasn't been answered as we are closing this issue. Thanks.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure_
