### ISSUE TITLE
AllUsers description confusing, possibly incomplete

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/windows-powershell-docs#2082]
The AllUsers parameter appears to be described in english, but I can't seem to make sense of what is being said.
What does it mean for the AllUsers pameter to "work off" the parent package type. What is "parent package", generally speaking, and in this particular context? The sentence as a whole doesn't seem to communicate a coherent self-contained message, not that I could decipher.
How one supposed to "use -PackageTypeFilter" and "specify the bundle", applied to AllUsers ? Is -PackageTypeFilter too a parameter to the Remove-AppxPackage, though unlisted ? Or is it meant to be used with Get-AppxPackage, then returned bundles can be used as -Package. It is as if words are missing from the description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc0b0cd3-1201-f5e2-907e-5712eda675da
* Version Independent ID: b722fa48-0af3-27ea-9f86-4f48b9972d19
* Content: [Remove-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/Remove-AppxPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/Remove-AppxPackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sowjanya365** [comment]
Hi @avakhrushev 

Thank you for bringing it to us. We will update the document with the necessary changes. 

The word "Work off" refers to "Get rid of" something. Sorry, if it was not clear enough on your end. 

And here in this context, "Parent Package" refers to "App Package Name". 

"-PackageTypeFiler" is not a parameter for "Remove-AppxPackage" command, but here we use it with "Get-AppxPackage". We will update it on the document. 

Thank you!
