### ISSUE TITLE
Export-StartLayout command error

### ISSUE THREAD

**Issue by yezilaoda** [MicrosoftDocs/windows-powershell-docs#2089]
i am run  Export-StartLayout -Path "D:\Store\StartMenu\Marketing.bin" -As BIN

and get a error

Export-StartLayout : 找不到与参数名称“As”匹配的参数。
所在位置 行:1 字符: 61
+ Export-StartLayout -Path "D:\Store\StartMenu\Marketing.bin" -As BIN
+                                                             ~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-StartLayout]，ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Windows.StartLayout.Commands.ExportStartLayoutCommand

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 641ad128-de6e-6d5d-9414-b5cf773f06d3
* Version Independent ID: 75d4ce24-a93f-0b25-167f-b440a0e7103c
* Content: [Export-StartLayout (startscreen)](https://docs.microsoft.com/zh-cn/powershell/module/startscreen/export-startlayout?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/startscreen/Export-StartLayout.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/startscreen/Export-StartLayout.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@yezilaoda , i verified this command its worked fine .  you should  remove  ** -As BIN**
type the following comands in powershell 

**md D:\Store\StartMenu**
**Export-StartLayout -Path "D:\Store\StartMenu\Marketing.bin"**
