### ISSUE TITLE
Dropped feature?

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/windows-powershell-docs#209]
This Windows Server 2012 R2 PowerShell version of this page says it is supported, but the Windows 10 and Windows 2016 PowerShell version of this page redirect with the error: "The requested page is not available for Windows 10 and Windows Server 2016 PowerShell." Was the feature really dropped from Win10/2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b3d536-027d-e21d-f160-42c2c2d02191
* Version Independent ID: 1408677c-e0ff-aaad-f84e-d97351461a62
* Content: [Get-WindowsFeature (servermanager)](https://docs.microsoft.com/en-us/powershell/module/servermanager/get-windowsfeature?view=winserver2012r2-ps#feedback)
* Content Source: [docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md)
* Service: **unspecified**
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @breyed Thanks for your feedback.
Actually, is not that the feature was dropped but the last documented version of the cmdlet for the Windows Server 2016 version is here https://docs.microsoft.com/en-us/powershell/module/Microsoft.Windows.ServerManager.Migration/Get-WindowsFeature?view=win10-ps
Page Navigation is not being handling well the change in the name of the module, that's the reason it currently presents you with the 2012r2 version.
Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @breyed 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by breyed** [comment]
Are you planning to correct page navigation to account for the module name change? If nothing happens, there will be ongoing confusion as people search for Get-WindowsFeature, get the page for an older OS, and then wonder why they don't get a page that matches their OS. If this is a "won't fix", it makes sense to leave this closed. Otherwise, it's best to reopen this issue or open a new issue specific to page navigation.

**Comment by get-itips** [comment]
Hello @breyed I personally already reported this navigation issue internally yesterday and is being taken care of.
Thank you.

**Comment by e0i** [comment]
@officedocsbot unassign @e0i

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @breyed 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
