### ISSUE TITLE
Set-DeDupVolume: Missing help for -AutoStart parameter

### ISSUE THREAD

**Issue by ObsidianSnake** [MicrosoftDocs/windows-powershell-docs#2090]
When cycling through the paramaters for Set-DeDupVolume on my Server 2019 instance, I have noticed -AutoStart parameter is not documented in "Get-Help Set-DeDupVolume" or on https://docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupvolume?view=win10-ps

Example: **Set-DeDupVolume "S:" -MinimumFileAgeDays 0 -AutoStart**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53037750-a381-fc0c-b36f-8a6ab2e148bf
* Version Independent ID: f417a83e-dbea-2d77-b753-23e665546b8b
* Content: [Set-DedupVolume (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupvolume?view=win10-ps)
* Content Source: [docset/windows/deduplication/Set-DedupVolume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/Set-DedupVolume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
Hi @ObsidianSnake 

Thank you for your feedback.

Unfortunately, the versions supported in the help file are 2012, 2012R2 and 2016. That is why you do not see the `-AutoStart` parameter as there is not 2019 version yet.

**Comment by arielsil** [comment]
Unfor, this is also true for the 2022 document and for the 2025 (26257) OS.  No documentation of AutoStart
