### ISSUE TITLE
Get-OdbcDsn (error when DSN not found)

### ISSUE THREAD

**Issue by git-youzer** [MicrosoftDocs/windows-powershell-docs#2091]
The documentation does not include guidance when the function fails to find a DSN.

i.e.

`Get-OdbcDsn -Name 'a-non-existing-dsn'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5aa1c3b-8656-b87e-fa0e-3d94dee6853e
* Version Independent ID: 6b8568e6-3a63-624d-2847-1c1feef5ba16
* Content: [Get-OdbcDsn (wdac)](https://docs.microsoft.com/en-us/powershell/module/wdac/get-odbcdsn?view=win10-ps)
* Content Source: [docset/windows/wdac/Get-OdbcDsn.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/wdac/Get-OdbcDsn.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@git-yourzer

Thank you for your feedback.

PowerShell documentation provides working examples. I have not seen non working examples that show errors.

Could you describe in more details what do you want to see here?

My guess is that you will just see an error that the DSN does not exist.
