### ISSUE TITLE
Provide more examples

### ISSUE THREAD

**Issue by excelsi84** [MicrosoftDocs/windows-powershell-docs#210]
Please provide more examples for modifying the Input Methods etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0acfb-259d-9815-3dcf-5cda21942ffd
* Version Independent ID: 7e7fd601-419e-671d-8780-826cccd6bb81
* Content: [Set-WinUserLanguageList (international)](https://docs.microsoft.com/en-us/powershell/module/international/set-winuserlanguagelist?view=win10-ps)
* Content Source: [docset/windows/international/set-winuserlanguagelist.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/international/set-winuserlanguagelist.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @excelsi84 How are you?
Thanks for your feedback.
Article has changed heavily from the moment you created this issue, so, kindly visit the current version of the article that added more and better examples to add or change languages.
**Thank you**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @excelsi84 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
