### ISSUE TITLE
How to check SSD trim support?

### ISSUE THREAD

**Issue by arvidjaar** [MicrosoftDocs/windows-powershell-docs#2101]
Quoting document:

> SSD without TRIM support

How does Windows determine it? How can I see whether my SSD supports TRIM or not? All that I see is "SSD" for disk type; there is no further qualification (with/without TRIM support or similar). That is different from HDD where I explicitly see Thin Provisioned.

It is **not** about DsiableDeleteNotify, which is basically the only hit for this question in Google.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7fec0b3-d10a-57f9-fe43-f9603bc11305
* Version Independent ID: a0ae9539-3ad0-e8d9-1f12-f75b934ef2e7
* Content: [Optimize-Volume (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/optimize-volume?view=win10-ps)
* Content Source: [docset/windows/storage/Optimize-Volume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/Optimize-Volume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@arvidjaar . SSD manufacturer releases seperate SSD tool, to check all features whether the SSD is Working correctly or not. So we can use.

**Comment by arvidjaar** [comment]
I am sorry, I do not understand this answer. According to documentation I was commenting on, Windows somehow knows whether SSD supports TRIM or not, without using any manufacturer tool. All I am asking - how to view information that Windows already knows.

**Comment by RAJU2529** [comment]
@arvidjaar , Then only windows 10 OS programmer or designer can answer your question.

**Comment by velkovb** [comment]
@arvidjaar 
Hello Andrei,

Thank you for your feedback. This is not an issue with PowerShell documentation and probably here is not the best place to get the best answer for your question.

Based on a quick search it is **exactly** *DisableDeleteNotify*. You can check this article:
[fsutil-behavior](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-behavior)

**Comment by e0i** [comment]
It seems that your question has been answered by an independent contributor.

Note that the issues section of this repository is intended for documentation and content issues.

Should you have any further issues similar to this one, please consider opening a product support ticket here:

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.
