### ISSUE TITLE
Parameter Documentation for Set-DNSClient fails to follow best practices. 

### ISSUE THREAD

**Issue by bobfrankly** [MicrosoftDocs/windows-powershell-docs#2105]
If the auto-documentation for the parameter isn't showing the correct default value, that means the parameter isn't following best practices or written correctly. The fact that this cmdlet and parameter is breaking an otherwise functional script speaks volumes on this subject. 

![ugh](https://i.imgur.com/NFGTRhJ.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b306a8-8dcd-ff84-82d9-e5c4b8393b0f
* Version Independent ID: 7e741629-6416-0861-fef5-99c52b407dc9
* Content: [Set-DnsClient (dnsclient)](https://docs.microsoft.com/en-us/powershell/module/dnsclient/set-dnsclient?view=win10-ps)
* Content Source: [docset/windows/dnsclient/Set-DnsClient.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsclient/Set-DnsClient.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@bobfrankly 

Thank you for your feedback.

I have tested the cmdlet and it seems like the default value is None indeed. I see that in the 2012 version of the cmdlet the default value was specified as True. I will work on updating the article with the correct information.
