### ISSUE TITLE
Add Notes to Snapsht

### ISSUE THREAD

**Issue by MiguelDomingues** [MicrosoftDocs/windows-powershell-docs#2107]
It is not clear how we can add notes to the snapshot.
It is possible to read them using Get-VMSnapshot, but changing the Notes property seems to be only possible via the Hyper-V Manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa47cc3-5dbe-fb26-6612-f92009da8972
* Version Independent ID: a67aa655-77a7-a2c5-d0d6-c42065ac1a4e
* Content: [Checkpoint-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/checkpoint-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/Checkpoint-VM.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/Checkpoint-VM.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@MiguelDomingues Hello Miguel,

Thank you for trying to make MicrosoftDocs a better place.

Very interesting issues. Actually, the _Notes_ property is not part of the checkpoint but rather a property of the VM itself. A checkpoint should be an exact copy of the VM in a certain point in time so I find it reasonable that notes will be the same as when I took the snapshot and not be able to edit it.

Part of the checkpoint is a read-only copy of the VM configuration file, which should allow you to set a name of the snapshot which in term ends up to the name of the VM in this copy configuration file. Hyper-V manager seems to allow you to edit the notes as well as the name but not such way in PowerShell.

The only way that could possible change the notes is to edit the snapshot configuration which is not officially supported. 

Let me know if you have any questions.
