### ISSUE TITLE
Error in LogLevel Parameter description of Add-WindowsCapability

### ISSUE THREAD

**Issue by Syberdoor** [MicrosoftDocs/windows-powershell-docs#2108]
[Enter feedback here]

The LogLevel section in the Add-Windowscapability documentation first states 4 acceptable numeric values and their meaning while the later "Accepted values" subsection only states 3 enum values (Errors, Warnings, WarningsInfo). By my testing the latter seems to be correct, Numbers do not work and there are only 3 possible settings for the LogLevel switch (which is a little unfortunate because a verbose/debug one would be nice)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce94c11-8f4f-89b3-1d87-b349bfb63889
* Version Independent ID: b175176e-2c8c-8869-2e43-6c45f4ed5671
* Content: [Add-WindowsCapability (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/add-windowscapability?view=win10-ps)
* Content Source: [docset/windows/dism/Add-WindowsCapability.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/Add-WindowsCapability.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@Syberdoor Hi,

Thank you for you feedback.

Unfortunately, I think you are correct and there are only 3 possible log levels for this cmdlet. I will update the documentation to reflect that.
