### ISSUE TITLE
Faulty example

### ISSUE THREAD

**Issue by TimPeTwo** [MicrosoftDocs/windows-powershell-docs#2111]
The given Example 1 is IMO wrong.

_PS C:\>Remove-RDPersonalVirtualDesktopAssignment -CollectionName "Virtual Desktop Collection" -User "CONTOSO\sarahjones" -VirtualDesktopName "PVD-12"_

Parameter combinations of _CollectionName_ , _User_ AND _VirtualDesktopName_ is not possible. 
Either _CollectionName_ and _User_ or _CollectionName_ and _VirtualDesktopName_ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c070c6-b170-c71f-4374-4b6ac1cefd3f
* Version Independent ID: 905690a8-47ba-12cc-cceb-191faa6ccd38
* Content: [Remove-RDPersonalVirtualDesktopAssignment (RemoteDesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/remove-rdpersonalvirtualdesktopassignment?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/Remove-RDPersonalVirtualDesktopAssignment.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/Remove-RDPersonalVirtualDesktopAssignment.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@TimPeTwo , wait for some time to get an answer from server experienced users.

**Comment by e0i** [comment]
With the help of your feedback, the issue has been reviewed and an update to the documentation has been published via PR #2140. Thanks for your feedback.
