### ISSUE TITLE
What happens if the Reservation does not exist?

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/windows-powershell-docs#2116]
It would help if this page had some comment on what happens if the Reservation being modified does not exist.

PS. I know the answer because I experimented, but it would have been helpful to have it documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ac89f20-dfa4-12f1-dc71-6fc97a4b1adb
* Version Independent ID: 5845b029-8e4a-6f9a-be6c-61e40d9d5add
* Content: [Set-DhcpServerv4Reservation (DhcpServer)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/set-dhcpserverv4reservation?view=win10-ps)
* Content Source: [docset/windows/dhcpserver/Set-DhcpServerv4Reservation.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dhcpserver/Set-DhcpServerv4Reservation.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@martingbrown Hi Martin,

Thank you for your feedback.

PowerShell documentation provides working examples. I have not seen non working examples that show errors.

Could you describe in more details what do you want to see here?

My guess is that you will just see an error that the reservation you try to edit does not exist?
