### ISSUE TITLE
Enable-PhysicalDiskIndication doesn't have a -StoragePool parameter as indicated in the examples.

### ISSUE THREAD

**Issue by mstaylorh** [MicrosoftDocs/windows-powershell-docs#2124]
Enable-PhysicalDiskIndication doesn't have a -StoragePool parameter as indicated in the examples.  Examples should instead take in a desired MSFT_PhysicalDisk object from Get-PhysicalDisk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f82f675-9ee2-e5b4-9071-3975ce55d257
* Version Independent ID: 5fe31259-05b6-d3fd-c8b5-518ebdd3f167
* Content: [Enable-PhysicalDiskIdentification (Storage)](https://docs.microsoft.com/en-us/powershell/module/storage/enable-physicaldiskidentification?view=win10-ps)
* Content Source: [docset/windows/storage/Enable-PhysicalDiskIdentification.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/Enable-PhysicalDiskIdentification.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@mstaylorh Thank you for your feedback. Example 3 in the document takes a desired object from the get-physical disk command. The stale examples have been removed.

Hope this helps!

@e0i  This can be closed as there are no changes required in the document.

Thanks
Sri
