### ISSUE TITLE
You have a typo all over this page and possibly others for similar cmdlet for KCC

### ISSUE THREAD

**Issue by RobG-MSFT** [MicrosoftDocs/windows-powershell-docs#2126]
Reading the descriptions on each of the switches you are not using the correct name for the acronym "KCC"

You have it as:  Kerberos consistency checker (KCC)

When it is actually called:  Knowledge Consistency Checker (KCC)

I have not looked at all the commandlets but I assume it is wrong in all of them.   You also want to probably look at the Get-ADReplicationSite cmdlet as well as I assume this is miss quoted there as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4751a6ff-4f0b-a3dd-7848-19a010e58cef
* Version Independent ID: eeefa571-7b82-30a2-e251-079491dfed65
* Content: [Set-ADReplicationSite (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/Set-ADReplicationSite?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@RobG-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2147

The Get-adreplicationsite cmdlet does not have this issue.

Thanks again for the feedback.

-Sri

**Comment by doctordns** [comment]
So far as I can tell, there are several documents that are needing to be changed:
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Set-ADReplicationSite.md
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Get-ADReplicationConnection.md

IF no one objects, I'll happily fix these.

**Comment by RAJU2529** [comment]
@e0i . assign user to  verify this PR #2017

**Comment by msbemba** [comment]
@doctordns Thank you for the feedback. We are fixing this as well. It can be tracked via PR# https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2153 and  PR #https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2154

Thanks
Sri

**Comment by RobG-MSFT** [comment]
That’s what I was saying when I filed the doc bug on this.  You might need to take a look at all the ad replication command lets to verify that they do not have the word Kerberos instead of Knowledge when referring to the KCC functionality.
