### ISSUE TITLE
Documentation correction: -Confirm

### ISSUE THREAD

**Issue by ecarlseen** [MicrosoftDocs/windows-powershell-docs#2141]
[Enter feedback here]

The default value for "-Confirm" is true, not false.  This was probably intended to match the documentation, but either the functionality (preferable) or the documentation should be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 476959ba-a1ab-29dc-a25f-95b6fa34c8b8
* Version Independent ID: 5766a81c-c589-88d2-51a8-752ba136b325
* Content: [Unregister-ScheduledTask (ScheduledTasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/unregister-scheduledtask?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/Unregister-ScheduledTask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/Unregister-ScheduledTask.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by msbemba** [comment]
@ecarlseen Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2146

Thanks
Sri

**Comment by RAJU2529** [comment]
@eamonoreilly . assign user to verify this PR #2146

**Comment by e0i** [comment]
Closing via merged PR #2146.
