### ISSUE TITLE
-RecordData required when using delegated permissions to delete DNS records

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/windows-powershell-docs#2149]
Can a mention be added for the -RecordData parameter that is is is required when using specifically delegate permissions to delete any record? See also https://powershell.org/forums/topic/dns-admin-permission-denied/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0921cbb6-b852-5752-c1dd-0165d2fd8df8
* Version Independent ID: 29be8200-81bd-a278-61da-61fb9afef1bd
* Content: [Remove-DnsServerResourceRecord (DnsServer)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/remove-dnsserverresourcerecord?view=win10-ps)
* Content Source: [docset/windows/dnsserver/Remove-DnsServerResourceRecord.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/Remove-DnsServerResourceRecord.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by sowjanya365** [comment]
Hi @Bart-Hoofd 

Good Day! Hope things are well on your end! :)

Just an FYI, We have tried to reproduce this issue on our end by creating a regular user with DNS Admin permissions, and we could successfully remove a record without using -RecordData. 

Not sure, in what scenario it's failing on your end. Kindly recheck and try again. Thank you for your contribution. :)

**Comment by Bart-Hoofd** [comment]
Hi @sowjanya365 , 

Thanks for taking the time to process my feedback 👍 

I was referring to a situation where ACL permissions in a part of a DNS tree are added, to be able to delegate permissions to a regular user for a specific part of the tree. If you are a member of DNS Admins, you receive a lot of permissions throughout DNS, and those permissions are (apparently) sufficient for normal operation. 
If however the user is only assigned specific permissions on a part of the tree, the user is only able to use the Remove-DnsServerResourceRecord succesfully when adding the -RecordData parameter.
