### ISSUE TITLE
Online resize is available

### ISSUE THREAD

**Issue by claymen** [MicrosoftDocs/windows-powershell-docs#215]
Documentation states that this is an offline operation, however this is not necessarily true for current versions of Hyper-V and disks that are attached to the virtual SCSI bus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3cf084a-7eb8-529b-ccdb-e806cebd2101
* Version Independent ID: 94919249-d7be-319c-f28e-15822546aaa1
* Content: [Resize-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/resize-vhd?view=win10-ps)
* Content Source: [docset/windows/hyper-v/resize-vhd.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/resize-vhd.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith please merge this PR, if you find it suitable

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @claymen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
