### ISSUE TITLE
ActiveDirectory page should indicate version needed to work with PowerShell 7

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/windows-powershell-docs#2151]
https://docs.microsoft.com/en-us/powershell/module/addsadministration/?view=win10-ps

I believe the October 2019 update is needed for the ActiveDirectory module to be loaded correctly into PowerShell 7.

**Comment by MaratMussabekov** [comment]
Hello,
isn't it 1809? as it is stated in [PowerShell 7 module compatibility](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/module-compatibility?view=powershell-7)
Thank you
