### ISSUE TITLE
Missing info on how to install the hcs module

### ISSUE THREAD

**Issue by xyzzer** [MicrosoftDocs/windows-powershell-docs#2156]
This page describes the hcs module, but doesn't say how to install it. It doesn't seem to just work. by calling `Install-Module HostComputeService`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 258f0f3a-8bd1-fb4a-af73-74bc508a8957
* Version Independent ID: 754238a3-8baf-b660-2ceb-a2fcdbdbe9b1
* Content: [HostComputeService Module](https://docs.microsoft.com/en-us/powershell/module/hostcomputeservice/?view=win10-ps&source=docs)
* Content Source: [docset/windows/hostcomputeservice/HostComputeService.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hostcomputeservice/HostComputeService.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by sowjanya365** [comment]
Hi @xyzzer 

Thank you for reaching out to us. 

If you look at the structure of all other modules, we will understand this page(Module Home Page) only describes the module and lists the cmdlets associated with the module. 

Please let us know if you are facing any issues in executing the cmdlets. And there is a note worth mentioning here is, "We must run this cmdlet from an elevated PowerShell session."

I hope this clarifies your concern. Thank you!
