### ISSUE TITLE
Would be cool to see installation instructions for this module, please

### ISSUE THREAD

**Issue by iampeterdaniels** [MicrosoftDocs/windows-powershell-docs#2163]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b85f40-b509-b1d5-d736-a49d745e4ef3
* Version Independent ID: 4a3e8930-8c29-43b8-3989-5e1bd94eaf47
* Content: [DnsServer Module](https://docs.microsoft.com/en-us/powershell/module/dnsserver/?view=win10-ps)
* Content Source: [docset/windows/dnsserver/DnsServer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/DnsServer.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@iampeterdaniels Hi Peter,

The first line of the article mentions how it can be installed:

> DnsServer Module can be obtained either by installing DNS Server role or adding the DNS Server Tools part of Remote Server Administration Tools (RSAT) feature.

What could be explained better here in your opinion?

**Comment by iampeterdaniels** [comment]
Apologies – I must have missed that at the top.  Perhaps a link to the RSAT DL would be a nice refinement?

**Comment by velkovb** [comment]
Well, that is kind of tricky as that article is supposed to cover both Windows 10 and Server 2016.

In Server 2016 you just go and add it as a feature.

In Windows 10 recent releases you can just enable it from optional features, no need to download.

**Comment by iampeterdaniels** [comment]
Gotcha.  What about links that clarify where to go and what to do if you want to install it for Windows Server  vs Windows 10.  Or just the enabling instructions for win 10?

On v2004 build 19041.450, I just tried to enable in mine via Windows Features and Remote Server Admin Tools was not there to expand.

It would be lovely to have super simple instructions for exactly how to install (or turn on) various powershell modules – esp ones that are not found in PSGallery.

Thank you!

**Comment by velkovb** [comment]
Yes, on recent builds it is not there. It was there on previous build when you download the RSAT tools. Now it is in a different section described here:
https://docs.microsoft.com/windows-server/remote/remote-server-administration-tools#install-uninstall-and-turn-offon-rsat-tools

**Comment by iampeterdaniels** [comment]
Apologies – I’m getting confused.

I guess that’s kinda my point.  I would love to see installing various posh modules become SUPER easy:


  1.  Google something – a task a topic, etc
  2.  find a cmd-let in MS docs (yay!  There IS a cmdlet for that!)
  3.  Click a button to install the module.
  4.  Celebrate good times.

PS #Vote 😊

**Comment by velkovb** [comment]
@iampeterdaniels 

I agree with you here, it is not always trivial to find what you need.

I guess that is the idea of the [PowerShell Gallery](https://www.powershellgallery.com/) but it is not there yet.
