### ISSUE TITLE
Add clarification to Example 3

### ISSUE THREAD

**Issue by mav-cloud** [MicrosoftDocs/windows-powershell-docs#2164]
Cleans up Cluster objects in Example 3 - in other words that also means "Computer Objects" correct? You should add this in ( ) or as a note so the admin that is new to Clusters understands the whole cleanup process in regards to Active Directory objects. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ab9d75-7d3c-1c94-5d25-f205c29cbe3e
* Version Independent ID: 33980946-c8d4-2878-83d0-1fb29bfd8e11
* Content: [Remove-Cluster (FailoverClusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/remove-cluster?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/Remove-Cluster.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/Remove-Cluster.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@mav-cloud Hi,

Thank you for your feedback.

I would generally recommend to first understand how failover cluster works and what typo of objects it needs to operate before trying to use the PowerShell commands. There are two types:

CNOs - Cluster Name Object which is the access point to your cluster. It is represented via a virtual Computer Object in Active Directory.
VCOs - Virtual Computer Object which is the access point of a role running on the cluster. It is again represented via a virtual Computer Object in Active Directory.

If you have active roles you will not be able to call the **Remove-Cluster** cmdlet. When you remove roles, usually the VCOs are disabled in AD and you have to clean them up. The _CleanupAD_ parameter actually deletes the CNO object in AD as by default it is only disabled.

Probably, it is worth updating that it means it will clean up CNOs.
