### ISSUE TITLE
WinNAT (NetNat) on Windows 10 Pro?

### ISSUE THREAD

**Issue by Boilerplate4u** [MicrosoftDocs/windows-powershell-docs#2166]
Hi, is WinNAT and associated PS modules like NetNat (cmdlets Get/Set-NetNat) really supported on Win10? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a03943ab-940a-4b55-20a8-35ce2978d651
* Version Independent ID: cc948479-f74d-c44f-f5df-40ec1c5881f9
* Content: [NetNat Module](https://docs.microsoft.com/en-us/powershell/module/netnat/?view=win10-ps)
* Content Source: [docset/windows/netnat/NetNat.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netnat/NetNat.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@Boilerplate4u 

Thank you for you feedback.

Yes, the module is supported and I have used it myself on couple if times. You can test it like that:
```powershell
PS C:\> get-service WinNat
```
```output
Status   Name               DisplayName
------   ----               -----------
Running  WinNat             Windows NAT Driver
```
If the service is not running you will have to start it (as administrator).

```powershell
PS C:\> New-NetNat -Name MyNATnetwork -InternalIPInterfaceAddressPrefix 192.168.0.0/24
```
```output
Name                             : MyNATnetwork
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 192.168.0.0/24
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True
```

Here is my version of Windows 10:
```powershell
PS C:\> $PSVersionTable
```

```output
Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
