### ISSUE TITLE
New-FsrmFileManagementJob : 0x80070057, The parameter is incorrect.

### ISSUE THREAD

**Issue by charlesqingli** [MicrosoftDocs/windows-powershell-docs#2168]
hi, trying to run the example script and run into the following error. I have not been able to find out more information on the error. Any suggestion will be greatly appreciated.

New-FsrmFileManagementJob : 0x80070057, The parameter is incorrect.
At line:11 char:1
+ New-FsrmFileManagementJob -Name "Expire all data" -Namespace @("C:\Sh ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (MSFT_FSRMFileManagementJob:Root/Microsoft/...leManagementJob) [New-FsrmFileManagementJob], CimExcept 
   ion
    + FullyQualifiedErrorId : MI RESULT 4,New-FsrmFileManagementJob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c55f43d-ded4-037f-9ff4-886c301cf498
* Version Independent ID: 7ae51102-62b2-1f87-e17c-5e6db4f1b35b
* Content: [New-FsrmFileManagementJob (FileServerResourceManager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/New-FsrmFileManagementJob?view=win10-ps)
* Content Source: [docset/windows/fileserverresourcemanager/New-FsrmFileManagementJob.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/fileserverresourcemanager/New-FsrmFileManagementJob.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by MaratMussabekov** [comment]
Hello @charlesqingli ,
there is a error in the second command.
it must be:
```$task = New-FsrmScheduledTask -Time $date -Monthly 1```
I will create a PR to change it.
Thank you
