### ISSUE TITLE
Typo GPPermission(s)

### ISSUE THREAD

**Issue by Ryu-Syrius** [MicrosoftDocs/windows-powershell-docs#2173]
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-GPPermissions                                  1.0.0.0    GroupPolicy
Cmdlet          Set-GPPermissions                                  1.0.0.0    GroupPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07ed5529-b035-1519-e7d4-e07d8f90d555
* Version Independent ID: e8ed9045-8751-c073-25a7-c9a6207710f2
* Content: [Get-GPPermission (GroupPolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/get-gppermission?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/Get-GPPermission.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/Get-GPPermission.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by MaratMussabekov** [comment]
Hello, there is no any typo here, 
Get-GPPermissions is just an alias of Get-GPPermission
![изображение](https://user-images.githubusercontent.com/48041687/99151063-5febe600-26ba-11eb-98c0-528d6374adfb.png)
