### ISSUE TITLE
Renew expired adfs mfa certificate

### ISSUE THREAD

**Issue by nandaguruswamy** [MicrosoftDocs/windows-powershell-docs#2178]
If the certificate has not expired, then the renew key can be used. If the cert has already expired, then the renew is not to be used but this causes the error 'Object reference not set to instance of an object' to appear. So, to avoid this, the old cert has to be removed and then the command to create a new cert has to be run. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c72bafbf-e5c7-cd84-9c16-f6d017825f7f
* Version Independent ID: cfefffa6-78f0-124b-d91d-95f0bbecfa98
* Content: [New-AdfsAzureMfaTenantCertificate (ADFS)](https://docs.microsoft.com/en-us/powershell/module/adfs/new-adfsazuremfatenantcertificate?view=win10-ps)
* Content Source: [docset/windows/adfs/New-AdfsAzureMfaTenantCertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/New-AdfsAzureMfaTenantCertificate.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@nandaguruswamy Thank you for your feedback.

Do you suggest adding this as description to the **Renew** parameter description?

**Comment by nandaguruswamy** [comment]
hi Boris,

Im sorry i replied late, but yes, this is vital information and needs to be
added to the description. Thanks.

*Thanks & Regards*
*Nanda Guruswamy*
*------------------------------------------------------*
