### ISSUE TITLE
Set-ClusterLog cmdlet misses information

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windows-powershell-docs#2183]
Link: [https://docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterlog?view=win10-ps ](url)
Set-ClusterLog value max value of 2048MB is only applicable to WS 2019 and newer versions.
Max Value for 2016 is 1024MB
Max Value for 2012R2 is 1024MB 

Please make a note for those max values to do not confuse customers.

**Comment by MaratMussabekov** [comment]
Hello @carlosmayol ,
you were looking to the version of the article for newer versions of Windows Server. In the version for WS 2012 R2, it shows 1024Mb.
Version for WS2016 and later - https://docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterlog?view=win10-ps
Version for WS2012R2 - https://docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterlog?view=winserver2012r2-ps

Thank you

**Comment by carlosmayol** [comment]
Hello @MaratMussabekov 
Thats what I mean, the article for 2016 points out 2048MB and Windows Server 2016 can only do 1024Mb. 2048MB is only supported in WS2019. PLease fix it.

**Comment by MaratMussabekov** [comment]
Yes, sorry, you are correct, I missed that..
This info was added by https://github.com/MicrosoftDocs/windows-powershell-docs/commit/92773b22ea7bc498e910b1c74f883a8bced06598#diff-e8fa4151e0a760501051972a6a346a4eb82006ef1308d959ad0998b0704921c7
and https://github.com/MicrosoftDocs/windows-powershell-docs/commit/de9804871db683335c9e846d18eb920d4cd45ea9#diff-e8fa4151e0a760501051972a6a346a4eb82006ef1308d959ad0998b0704921c7

I will create a PR to revert these changes.

Thank you

**Comment by carlosmayol** [comment]
My preference will not to revert them, but to specify, current supported limits (hardcoded) in the product. 2048Mb is only supported in WS2019 in advance.

**Comment by carlosmayol** [comment]
any news of the pull status? thanks

**Comment by MaratMussabekov** [comment]
Hello, supported limits for both versions were specified, you can see more details in #2214 
Thank you

**Comment by carlosmayol** [comment]
Yeah, but I dont see it public available here: https://docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterlog?view=win10-ps yet, thats my question.

**Comment by e0i** [comment]
The changes are now publicly available. Thank you. @carlosmayol

**Comment by carlosmayol** [comment]
@Hello all, I dont belive after all this back and forth the documentation is not correct for my eyes:
The article for 2016 points out 2048MB and Windows Server 2016 can only do 1024Mb. 2048MB is only supported in WS2019. 
Is to hard to add 2 examples and specify 2048MB only applies to 2019 and above?

**Comment by carlosmayol** [comment]
Hello, any advance on this? this is pretty exhausting... @e0i ??
