### ISSUE TITLE
New-ADServiceAccount documentation regarding SamAccountName is incorrect

### ISSUE THREAD

**Issue by GuyWiththeHat** [MicrosoftDocs/windows-powershell-docs#2196]
The documentation for SamAccountName states the following:

    -SamAccountName <String>
        Specifies the Security Account Manager (SAM) account name of the user, group, computer, or service account. The maximum length of the description is 256 characters. To be compatible with older operating systems, create a SAM account name that is 20 characters or less. This parameter sets the SAMAccountName for an account object. The LDAP display name (ldapDisplayName) for this property is "sAMAccountName".

The maximum length for this property is actually 14 characters or less (15 characters if you include the '$' that is automatically appended to the SamAccountName).  If you attempt to create a gMSA service account with a SamAccountName greater than this limit the following error message is displayed:

New-ADServiceAccount : The service account has a samAccountName attribute of 'gsvc-Automation-DNS' which is too long; the samAccountName attribute must not be longer than 15 characters
At line:1 char:1
+ New-ADServiceAccount 'gsvc-Automation-DNS' -DNSHostName 'gsvc-Automat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (CN=gsvc-Automat...,DC=trow,DC=com:String) [New-ADServiceAccount], ArgumentException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Commands.NewADServiceAccount
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e1e7e8-00f1-6b10-e19e-fdab4eb9d493
* Version Independent ID: e66770b5-1cf3-617d-d7f6-6d334501075a
* Content: [New-ADServiceAccount (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=win10-ps)
* Content Source: [docset/windows/addsadministration/New-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/New-ADServiceAccount.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by Creteil** [comment]
> The maximum length for this property is actually **<ins>14</ins>** characters or less (**<ins>15</ins>** characters if you include the '$' that is automatically appended to the SamAccountName).

This is not true, the real fact is :

The maximum length for this property is actually **<ins>15</ins>** characters or less (**<ins>16</ins>** characters if you include the '$' that is automatically appended to the SamAccountName).
