### ISSUE TITLE
-FileName<String> produces error

### ISSUE THREAD

**Issue by cheesecracker** [MicrosoftDocs/windows-powershell-docs#2199]
I was trying to use this Export-DnsServerZone command by following this article but I kept on getting error:
https://docs.microsoft.com/en-us/powershell/module/dnsserver/export-dnsserverzone?view=win10-ps

Then I found this forum discussion:
https://social.technet.microsoft.com/Forums/windows/en-US/c50a9c32-1c73-4843-a97c-ed7add43bf3c/exportdnsserverzone-filename-does-not-work?forum=winserveripamdhcpdns

It's written that "The FileName parameter does not work as the documentation describes."

Someone please review the cmdlet or the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b72106-625e-207a-65fa-a3542006610c
* Version Independent ID: cfbe6eb1-4469-0026-759c-b43bda10f053
* Content: [Export-DnsServerZone (DnsServer)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/export-dnsserverzone?view=win10-ps)
* Content Source: [docset/windows/dnsserver/Export-DnsServerZone.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/Export-DnsServerZone.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
It seems that this question can best be answered via [PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.

Thanks again.
