### ISSUE TITLE
-update switch

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/windows-powershell-docs#2227]
Would like more information on using this switch to choose specific updates. For example, suppose I want to approve only KB45866823? Is that possible?
Get-wsusupdate has an -updateid parameter, but this requires the guid of the update, which get-wsusupdate does not return, making that particular switch quite useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a410f874-8eaa-2995-8e1b-244e57c28221
* Version Independent ID: 88d7e1f1-f5ed-48f5-15d0-bfc3fb9f28ea
* Content: [Approve-WsusUpdate (UpdateServices)](https://docs.microsoft.com/en-us/powershell/module/updateservices/approve-wsusupdate?view=win10-ps)
* Content Source: [docset/windows/updateservices/Approve-WsusUpdate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/updateservices/Approve-WsusUpdate.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@MichaelMc64 

Thank you for your feedback.

Unfortunately, I don't see a way of getting only a specific KB with the cmdlet. You will have to do client side filtering.

```powershell
PS C:\> Get-WsusUpdate -Classification Critical | Where-Object {$PSItem.Update.KnowledgebaseArticles -eq "3199986"}
```

This would give a specific update but I would rather first get all the WSUS updates in a variable and then approve the ones I want with something like that:
```powershell
PS C:\> $updates = Get-WsusUpdate -Classification Critical
PS C:\> $updates | Where-Object {$PSItem.Update.KnowledgebaseArticles -eq "3199986"} | Approve-WsusUpdate -Action Install -TargetGroupName "All Computers"
```

Let me know if that helps
