### ISSUE TITLE
Journaling does not enable using example shown above

### ISSUE THREAD

**Issue by jkobs** [MicrosoftDocs/windows-powershell-docs#223]
When using the command shown above, journaling does not get enabled - I receive this error:

Set-MsmqQueue : Missing an argument for parameter 'Journaling'. Specify a parameter of type 'System.Nullable`1[System.Boolean]' and try again.
At line:1 char:63
+ ... MsmqQueue –Name "dtriq" -QueueType Public | Set-MsmqQueue -Journaling
+                                                               ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-MsmqQueue], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Microsoft.Msmq.PowerShell.Commands.SetMSMQQueueCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970cfb6e-da9f-2eb2-dd6f-e03d4cbdc1b1
* Version Independent ID: f12e6497-dbcf-22ff-b3ee-858fb4cb4b57
* Content: [Set-MsmqQueue (msmq)](https://docs.microsoft.com/en-us/powershell/module/msmq/set-msmqqueue?view=win10-ps)
* Content Source: [docset/windows/msmq/set-msmqqueue.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/msmq/set-msmqqueue.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @jkobs 
Thanks for your comments, we really appreciate them.
I tested in a lab, and got the same error, the article should say:

Set-MsmqQueue -Journaling:$true
or
Set-MsmqQueue -Journaling:$false

I'll create a PR to fix the article.

**Thank you!**

**Comment by yogkumgit** [comment]
@kenwith please merge this PR if find it suitable

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jkobs 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
