### ISSUE TITLE
Error on sample

### ISSUE THREAD

**Issue by imartinez2** [MicrosoftDocs/windows-powershell-docs#2237]
[The sample show MAC with : but fail, must be without : ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0df3b0-da8f-87e5-c1ad-a0c42e5409f2
* Version Independent ID: b3e263ce-29e5-a1d3-99bc-5ec8ec54a21f
* Content: [Add-DhcpServerv4Reservation (DhcpServer)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/add-dhcpserverv4reservation?view=win10-ps)
* Content Source: [docset/windows/dhcpserver/Add-DhcpServerv4Reservation.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dhcpserver/Add-DhcpServerv4Reservation.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@imartinez2 Hello,

Thank you for trying to make MicrosoftDocs a better place.

I went through the article but was not able to find an MAC with `:`. Could you point me to the part that you are referring?

**Comment by e0i** [comment]
@imartinez2 The issue is being closed because the problem in question cannot be reproduced. Please feel free to re-open this issue with additional details to move forward. Thank you.
