### ISSUE TITLE
TimeSpan issue

### ISSUE THREAD

**Issue by arowswell** [MicrosoftDocs/windows-powershell-docs#224]
Param(
    [String]$UserOU = "our user OU",
    [String]$Server = "one of our DCs",
    [Object]$Credential = (Get-Credential),
    [String]$TimeSpan = "90",
)

$InactiveUsers = (Search-ADAccount -AccountInactive -UsersOnly -Credential $Credential -SearchBase $UserOU -Server $Server -TimeSpan $TimeSpan)

This returns accounts that have been logged into within 90 days, are enabled and do not have an expired password. Why? It's something to do with $TimeSpan = "90". When I change it to $TimeSpan = "90.00:00:00" it appears to work as expected. Please update the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87483a05-ea3b-19c2-3d31-4701e03e68e2
* Version Independent ID: 917d2078-1e43-895a-e3cb-d6e64844196e
* Content: [Search-ADAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/search-adaccount?view=win10-ps#outputs)
* Content Source: [docset/windows/addsadministration/search-adaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/search-adaccount.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by metamoof** [comment]
Could you please document what the default behaviour of `-AccountExpiring` and `-AccountInactive` are when no `-DateTime` or `-TimeSpan` option are?

**Comment by e0i** [comment]
@kenwith A PR #913 available for this issue. Thanks.

**Comment by e0i** [comment]
@arowswell  Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

_PS: The PR `#915` is an accidental reference to this issue, please ignore._

**Comment by e0i** [comment]
@officedocsbot close
