### ISSUE TITLE
Example incorrect.

### ISSUE THREAD

**Issue by TheUberGeeks** [MicrosoftDocs/windows-powershell-docs#2240]
The use of an array index is incorrect as the protectors are not ordered, example should be;

$blv = Get-BitLockerVolume -MountPoint 'c:'
Remove-BitLockerKeyProtector -MountPoint 'c:' -KeyProtectorId $blv.KeyProtector.Where({$_.KeyProtectorType -eq 'TpmPin'}).KeyProtectorId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 670d67ed-5c94-cd7d-0aa8-54cca8636fcd
* Version Independent ID: e4bce7f9-9c6a-da21-45b3-d664b2a9584c
* Content: [Remove-BitLockerKeyProtector (BitLocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/remove-bitlockerkeyprotector?view=win10-ps#:~:text=The%20Remove-BitLockerKeyProtector%20cmdlet%20removes%20a%20key%20protector%20for,To%20add%20a%20protector%2C%20use%20the%20Add-BitLockerKeyProtector%20cmdlet.)
* Content Source: [docset/windows/bitlocker/Remove-BitLockerKeyProtector.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/Remove-BitLockerKeyProtector.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@TheUberGeeks 

Thank you for your feedback.

I agree that the protectors are not ordered but the example is not looking for a specific type like you have mentioned. It is just saying to remove the second KeyProtector. KeyProtectors will be returned in the order they are added.

I will add this as additional info to the example and add your example as well.
