### ISSUE TITLE
new-FsrmFileScreen Passive file screen example incorrect.

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [MicrosoftDocs/windows-powershell-docs#2245]
The example for creating a passive file screen is incorrect. The example says a passive screen will be created if you do not specify the -Active parameter. In order for a passive screen to be created you must specify `-Active:$false` in the command to create a passive file screen. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3505704-69d0-e80b-f1f5-b98975e6f069
* Version Independent ID: 9d626fbd-d916-6367-32c7-8c104a0a43ae
* Content: [New-FsrmFileScreen (FileServerResourceManager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/new-fsrmfilescreen?view=win10-ps)
* Content Source: [docset/windows/fileserverresourcemanager/New-FsrmFileScreen.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/fileserverresourcemanager/New-FsrmFileScreen.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by TurnItOff-OnAgain** [comment]
![image](https://user-images.githubusercontent.com/26926284/102360848-8aaeb000-3f80-11eb-9c00-de3fbfb7f56e.png)
The image shows the command being run with and without the `-Active:$false` parameter. The output of the commands show that if ran without specifying `-Active:$false`  it will be an active file screen.

**Comment by velkovb** [comment]
@TurnItOff-OnAgain 

Thank you for your feedback.

Could you share the OS version that you are testing this on?

Thank you.

**Comment by TurnItOff-OnAgain** [comment]
The screenshots were taken on Windows Server 2016 1607 Build 14393.4046

I also had the same results on Windows Server 2019 1809 Build 17763.1518
