### ISSUE TITLE
wish list

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#225]
A -recurse option would be nice, and to be able to list all registry entries of a gpo, without having to specifiy 'hklm\software' or 'hkcu\software' as the starting key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfffe4d-599c-3d24-22f0-47f0921d7862
* Version Independent ID: 2d09f9b5-bc22-6928-e930-9a38f8f1ef9b
* Content: [Get-GPRegistryValue (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/get-gpregistryvalue?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/get-gpregistryvalue.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/get-gpregistryvalue.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @jszabo98 thanks for your comments!
This system is for declaring issues specific with documentation, to suggest new features, the user voice is more suitable, please visit https://windowsserver.uservoice.com/forums/301869-powershell
Thank you!

**Comment by yogkumgit** [comment]
@jszabo98  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
