### ISSUE TITLE
VHD commands not found on Windows 10

### ISSUE THREAD

**Issue by NikhilPr95** [MicrosoftDocs/windows-powershell-docs#2253]
HI, I'm facing disk-related issues with WSL2 and am trying to use Powershell to [compact](https://github.com/microsoft/WSL/issues/4699) the Virtual Hard Disk and return storage from WSL2 to Windows.

I am trying to use the following commands - 
```
wsl --terminate ubuntu-18.04
Optimize-VHD -Path .\ext4.vhdx -Mode full
```
However, the command is not present on my version of Windows 10 (Home) and Powershell (v5.1). I get the following error -
```
Optimize-VHD : The term 'Optimize-VHD' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Optimize-VHD ext4.vhdx
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Optimize-VHD:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

From what I read this command is [only available](https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-winapps-appscat_tools/optimize-vhd-not-found-in-windows-10-home/a727b760-0f82-4d0f-8480-d49eeaeb11a2) on the Windows 10 (Pro) Edition. Is there a way for me to use this functionality to solve my issue without having to buy the Pro version?

**Comment by doctordns** [comment]
That error message, which is pretty clear, says PowerShell can not find the command Optimize-VHD.
This command is found in the Hyper-V module.

So - can you ``Import-Module -Name Hyper-V``?  

And if not have you loaded the RSAT tools for Windows 10.  Seehttps://www.microsoft.com/en-gb/download/details.aspx?id=45520 and go from there.

**Comment by NikhilPr95** [comment]
> That error message, which is pretty clear, says PowerShell can not find the command Optimize-VHD.
> This command is found in the Hyper-V module.
> 
> So - can you `Import-Module -Name Hyper-V`?
> 
> And if not have you loaded the RSAT tools for Windows 10. Seehttps://www.microsoft.com/en-gb/download/details.aspx?id=45520 and go from there.

Thanks, I tried both of these, but it seems that Hyper-V is not available using either with the Windows 10 (Home) Edition (only with Enterprise, Pro, or Education). It seems weird to allow WSL2 on the Home edition, but not the Hyper-V tool required to manage the partitions created from using the former.

**Comment by e0i** [comment]
It seems that this question can best be answered via [PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.
