### ISSUE TITLE
Product/Version for BitsTransfer module and commands doco

### ISSUE THREAD

**Issue by LUCScape** [MicrosoftDocs/windows-powershell-docs#226]
I can see BitsTransfer powershell commands on my Windows 7 system, but the docs here does not provide a Windows 7 or Server 2008 R2 version option in the product/version list.  Would help if  windows remote admin version was also mentioned in the compatibility lists (Win 10 or Win 8.1 etc) - as I suspect that is how we have BitsTransfer on Windows 7 (I've got WRM3/Powershell 3).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9e10e0-fce5-88b0-c1c4-7e18e67c7f34
* Version Independent ID: ea117ce8-f118-53fb-e01b-0ecbe8b93f8c
* Content: [BitsTransfer](https://docs.microsoft.com/en-us/powershell/module/bitstransfer/?view=win10-ps)
* Content Source: [docset/windows/bitstransfer/bitstransfer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitstransfer/bitstransfer.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
Hello, @LUCScape 

_Windows 7_ and _Windows 2008 PowerShell_ versions will not be covered in this documentation as _Windows 7_ will reach its end of life in less than a year.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
