### ISSUE TITLE
Its not an issue but need help in sending outlook mail using powershell script

### ISSUE THREAD

**Issue by vishnuprakash9845** [MicrosoftDocs/windows-powershell-docs#2265]
I am an automation engineer

I have have automated few test cases and getting the test results. This test results I wanted to forward to team using outlook using powershell. I tried many ways to do it, but not working. 

I want an powershell script to send outlook mail to people who I configure.

Can anyone please help me out in this.

**Comment by e0i** [comment]
You may find the answers that you are looking for via [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

The issues section of this repository is intended for documentation problems.

Thanks.
