### ISSUE TITLE
Consuming Events

### ISSUE THREAD

**Issue by TylerRosolowski** [MicrosoftDocs/windows-powershell-docs#2267]
[Enter feedback here]
It would be good to explain if you use the RealtimeLocal or RealtimeRPC settings, how you then consume or view the events. e.g. how can I connect to the live session. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c35bddf8-d6a0-f462-2f5d-a86d9ff35116
* Version Independent ID: 0431a2ca-fbea-37af-d8eb-7854d2c57e51
* Content: [Set-NetEventSession (NetEventPacketCapture)](https://docs.microsoft.com/en-us/powershell/module/neteventpacketcapture/set-neteventsession?view=win10-ps)
* Content Source: [docset/windows/neteventpacketcapture/Set-NetEventSession.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/neteventpacketcapture/Set-NetEventSession.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by MaratMussabekov** [comment]
Hello, this kind of instruction would be out of the scope of the article.
For example, you can do following:
1. create net event session
2. add a network Event Packet Capture Provider
3. start the session
4. capture the events using any soft that supports ETW (like Microsoft Message Analyzer or Wireshark with ETW plugin)
5. stop the session

Thank you
