### ISSUE TITLE
failed to execute command: new-netadapter

### ISSUE THREAD

**Issue by sycki** [MicrosoftDocs/windows-powershell-docs#227]
I want to create a virtual network card and specify its address range.

OS：Windows server 2016 Datacenter

execute the command by administrator:
```
PS C:\Users\Administrator> New-NetAdapterAdvancedProperty -Name "docker1" -RegistryKeyword "docker1" -RegistryValue "1" -RegistryDataType REG_SZ
New-NetAdapterAdvancedProperty : 找不到请求的对象。
所在位置 行:1 字符: 1
+ New-NetAdapterAdvancedProperty -Name "docker1" -RegistryKeyword "dock ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_NetAdapter...ertySettingData:ROOT/StandardCi...ertySettingData) [New-NetAdapterAdvancedProperty], CimException
    + FullyQualifiedErrorId : MI RESULT 6,New-NetAdapterAdvancedProperty
```

In addition, there is a question, how do I add a custom network card and specify its IP when the docker container is initialized?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab677a6-feb3-f5ee-a8c4-34d81934e10e
* Version Independent ID: ffbac4d7-b125-978b-3e94-bf40bccbb68b
* Content: [New-NetAdapterAdvancedProperty (netadapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/new-netadapteradvancedproperty?view=win10-ps)
* Content Source: [docset/windows/netadapter/new-netadapteradvancedproperty.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netadapter/new-netadapteradvancedproperty.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by matushorvath** [comment]
Example 2 is incorrect, there is no -RegistryType "REG_SZ" parameter. And there should be such parameter to make this more useful.

**Comment by VLG17** [comment]
@sycki i have tested the same syntax on Windows Server 2016 Datancenter and i get the exact error. I recommend opening a [support ticket](https://support.microsoft.com/en-us/supportforbusiness/productselection) so that a support engineer can look into this. 

Regarding the question related to docker, we first need to understand where it runs (AKS, VM or Service Fabric).

**Comment by VLG17** [comment]
@matushorvath i have checked example 2 and i think it has been updated because it now shows -RegistryDataType REG_SZ which is correct.

**Comment by e0i** [comment]
Hello @sycki,

We are closing this issue since your question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
