### ISSUE TITLE
Clear-Tpm has undocumented UsePPI parameter as of 20H1

### ISSUE THREAD

**Issue by sewillia-msft** [MicrosoftDocs/windows-powershell-docs#2270]
As of Win10 20H1, `Clear-Tpm` now has a `-UsePPI` parameter. This parameter doesn't show up in any docs AFAICT.

Could we get MSDocs/HelpInfo updated to call out that this parameter exists? Based on the topic space, I assume this uses the TPM Physical Presence Interface to request clear/reset of a machine's TPM - it would be good to get official confirmation from the module owner, however. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73d059ad-0b17-9a9d-f630-73f7891e580a
* Version Independent ID: 58e94018-bdbe-e07c-1cba-bcfe15bc623c
* Content: [Clear-Tpm (TrustedPlatformModule)](https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/clear-tpm?view=win10-ps)
* Content Source: [docset/windows/trustedplatformmodule/Clear-Tpm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/trustedplatformmodule/Clear-Tpm.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by Kateyanne** [comment]
Hi Sean –
Sorry for the delay. Powershell is self-serve by product owners, and you are welcome to make changes to it.
New cmdlets: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/repo_docs/NEW_CMDLETS.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-docs-powershell%2Fblob%2Fmaster%2Frepo_docs%2FNEW_CMDLETS.md&data=04%7C01%7Cdmaguire%40microsoft.com%7Ce3ca0af746804865c6c108d81a2859b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637288107889263649%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y4Ft3QcbTrJDRxwTM2FTH1W3G8XKTpYZed%2Fp9MeE1bU%3D&reserved=0>
Existing cmdlets: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md
MicrosoftDocs/office-docs-powershell
PowerShell Reference for Office Products - Short URL: aka.ms/office-powershell - MicrosoftDocs/office-docs-powershell


Thanks,
Kateyanne
Kateyanne Unullisi (Aquent) I E + D Marvel Team
PubOps Project Manager
Office: (425)722-2516
Mobile: (425) 753-5016
v-kaunu@microsoft.com<mailto:william.davis@microsoft.com>

**Comment by sewillia-msft** [comment]
@Kateyanne, it appears the links provided focus on the Microsoft Office PowerShell modules - this is for a different subject area and it's unclear whether the TrustedPlatformModule module uses platyPS as well.

Moreover, I'm not the product owner of this module - there's literally no other supporting documentation available for me to source from if I were to PR an update to the HelpInfo for this module. While I can hazard a guess at what this parameter is supposed to do based on its name, I feel like this is supposed to come from the responsible PG/PO directly.

Let me know if there's any other information I can provide.

**Comment by e0i** [comment]
Pop

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by e0i** [comment]
This repository keeps track of issues related to legacy documentation like Server 2016 and 2012, and version 20H1 is not one of the versions that we cover. Thank you for the feedback.

**Comment by sewillia-msft** [comment]
@e0i, docs.microsoft.com indicates this document applies to "Windows 10 and Server 2016 Powershell" (which I would assume includes 20H1). Is there a more appropriate location for internal/external parties to request documentation updates for in-box PowerShell modules on newer versions of Windows?

**Comment by kilasuit** [comment]
@sdwheeler - can you follow up with whoever owns this module and ensure that the documentation is updated accordingly

Also as an aside we may need to think about how PowerShell documentation for Windows 10 may require splitting up for different feature versions as this is unlikely to be the last time this crops up, 
cc @joeyaiello

**Comment by e0i** [comment]
@kilasuit Thank you for the actionable follow-up.

It seems that the next best step would be to follow Sean’s recommendation here. I represent a group of independent contributors who fix errors in the articles in response to reader feedback in an open source manner. Coming up with original content that covers new cmdlet switches is out of our scope.

@sewillia-msft Thanks again for bringing this up to attention.

cc @Kateyanne
