### ISSUE TITLE
Windows Servr 2016 RDSH - Firewall rules created at every login. 

### ISSUE THREAD

**Issue by YeCherkosLij** [MicrosoftDocs/windows-powershell-docs#2273]
I have RDS environment, with UPDs on a Server 2016 platform. 
I run on Powershell ( as an Administrator)
Get-NetFirewallRule -policystore configurableservicestore |Where {$_.Owner -ne $Null} | sort Displayname, Owner

then to delete all items inside,

Error message : **Not enough storage is available to complete this operation** 

Question: 

1.  Is it possible to delete all items  "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\RestrictedServices\Configurable\System
in Register  with out consequential damage.

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
