### ISSUE TITLE
documention error

### ISSUE THREAD

**Issue by sloth-101** [MicrosoftDocs/windows-powershell-docs#2274]
the documentation mentions that the default value for the -confirm switch is false when infact it is true. 
to get no confirmation prompt you have to explicitly state -confirm:$false while the documentation suggests otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218dacfb-63be-4478-ea8e-88ad519363fb
* Version Independent ID: d2e65deb-1079-5ff9-ea3e-e2e4dadeb54b
* Content: [Reset-FsrmFileScreen (FileServerResourceManager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/reset-fsrmfilescreen?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/fileserverresourcemanager/Reset-FsrmFileScreen.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/fileserverresourcemanager/Reset-FsrmFileScreen.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by sloth-101** [comment]
someone told me this behavior is correct and intended, so i close the issue. The way the information is presented is still very much confusing.

**Comment by e0i** [comment]
Hello, @sloth-101. Yes, It is common that the switch parameters come across as very confusing to the readers. Closing as you hopefully seem to have found your way out. Thanks.
