### ISSUE TITLE
Document how to get the command's module in scope.

### ISSUE THREAD

**Issue by IDisposable** [MicrosoftDocs/windows-powershell-docs#2275]
Would be great if ANYWHERE in these Powershell documents you made it clear how to get the (in this case `Hyper-V`) module available for the commands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162fa55d-6fc7-4145-537d-bcceceae2d7d
* Version Independent ID: 6c80c1f4-8ea2-1a41-b4d8-a28f9e50cb97
* Content: [Optimize-VHD (Hyper-V)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/optimize-vhd?view=win10-ps)
* Content Source: [docset/windows/hyper-v/Optimize-VHD.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/Optimize-VHD.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@IDisposable Hi Marc, 

Thank you for your feedback. Do you mean something like this:
[Get-Command](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/get-command)

You can use the **Get-Command** cmdlet to list all commands in a module like that:
```Powershell
PS C:\> Get-Command -Module Hyper-V
```
