### ISSUE TITLE
There is no command reference for "Set-MpPreference -EnableNetworkProtection"

### ISSUE THREAD

**Issue by hidemaruki** [MicrosoftDocs/windows-powershell-docs#2278]
[フィードバックをこちらに入力してください]
The command reference of "Set-MpPreference -EnableNetworkProtection" in the following URL does not exist.
Please write a reference for the PowerShell command to enable "Network Protection".

https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection
https://docs.microsoft.com/ja-jp/powershell/module/defender/set-mppreference?view=win10-ps

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3c51683d-1b50-1930-c39a-4ba45e330369
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (Defender)](https://docs.microsoft.com/ja-jp/powershell/module/defender/set-mppreference?view=win10-ps)
* Content Source: [docset/windows/defender/Set-MpPreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/Set-MpPreference.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by MaratMussabekov** [comment]
Hello @hidemaruki ,
current version of the article is applicable to Windows Server 2016 and Windows 10 1607.
This parameter will be added when Windows Server 2019 documentation is released.
for more details, please see https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1207

Thank you
