### ISSUE TITLE
Hyper-v cmdlets can't use wsl paths

### ISSUE THREAD

**Issue by fabioDMFerreira** [MicrosoftDocs/windows-powershell-docs#2286]
This issue is a problem I'm having using `Add-VMHardDiskDrive`. Documentation is fine!

I am not able to use a WSL path as argument.
```
Add-VMHardDiskDrive -VMName test  -Path \\wsl$/Ubuntu/home/<image path>
```

This command launches the next error
```
Add-VMHardDiskDrive : 'test' failed to add resources to 
'test'.
An unexpected error occurred: The network name cannot be found. (0x80070043).
'test' failed to add resources. (Virtual machine ID 
4F4777B2-4DFD-4A07-89B6-44FFC5BE2D3F)
'main-image-1611598805' encountered an unexpected error: The network name cannot be 
found. (0x80070043). (Virtual machine ID 4F4777B2-4DFD-4A07-89B6-44FFC5BE2D3F)
At line:1 char:1
+ Add-VMHardDiskDrive -VMName test  -Path \\wsl$/Ubunt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-VMHardDiskDrive], Virtualizatio 
   nException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.A 
   ddVMHardDiskDrive
```

It seems the cmdlet can't access paths located in other network devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8343dc-9023-5a5c-c9fc-7f5d76c855ca
* Version Independent ID: 32a3f4e4-64da-438c-8c7d-130210c9742a
* Content: [Add-VMHardDiskDrive (Hyper-V)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmharddiskdrive?view=win10-ps)
* Content Source: [docset/windows/hyper-v/Add-VMHardDiskDrive.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/Add-VMHardDiskDrive.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
It seems that this question can best be answered via [PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

The issues section of this repository is for content fixes regarding documentation. 

Thank you.
