### ISSUE TITLE
New-NetworkControllerLoadBalancingRule - Example 1 is literally missing half its content

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windows-powershell-docs#2288]
It appears that whomever made this page didn't copy/paste the Example code correctly. The last line is cutoff mid-cmdlet and the entire block of code that should be referencing **_the actual cmdlet being documented_** is missing. Without the bottom of this Example, this is effectively worthless.

I believe the example was trying to mimic some of what was here:
https://docs.microsoft.com/en-us/windows-server/networking/sdn/manage/configure-slb-and-nat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baf5bb7-2171-2449-fd6b-8f750ffab45f
* Version Independent ID: 56432f1f-822c-fcc3-34e8-b837882f7893
* Content: [New-NetworkControllerLoadBalancingRule (NetworkController)](https://docs.microsoft.com/en-us/powershell/module/networkcontroller/new-networkcontrollerloadbalancingrule?view=win10-ps)
* Content Source: [docset/windows/networkcontroller/New-NetworkControllerLoadBalancingRule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/networkcontroller/New-NetworkControllerLoadBalancingRule.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
Hello @eponerine This issue is being taken care of under the duplicate issue #2287. Thank you.

**Comment by eponerine** [comment]
@BronsonMagnan is just too fast for me :P
