### ISSUE TITLE
Get-PhysicalDisk runs in memory leak 

### ISSUE THREAD

**Issue by godofglow** [MicrosoftDocs/windows-powershell-docs#2290]
If you run **Get-PhysicalDisk** (in a powershell-loop or called from a C# application) you will see after after hundreds/thousands of runs a memory-leak.

**// Test-Script**
![image](https://user-images.githubusercontent.com/39702056/106422924-bd910280-645f-11eb-82b1-96c412ea7b50.png)

**// System-Enviroment**
![image](https://user-images.githubusercontent.com/39702056/106423308-79eac880-6460-11eb-9e4c-cd1728441b0d.png)
![image](https://user-images.githubusercontent.com/39702056/106423349-90911f80-6460-11eb-878b-98f4ce2c6a51.png)

**Comment by e0i** [comment]
It seems that this question can best be answered via [PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.

Thanks again.
