### ISSUE TITLE
Get-ADUser - get of all the "memberof"

### ISSUE THREAD

**Issue by fidfbonanno** [MicrosoftDocs/windows-powershell-docs#2292]
Hi all,
I noticed that if i use the command `Get-ADUser XXX -Properties memberof` I can get only a few groups but not all... How can I get all the groups that the user is a member of?
Thank you.

F.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292908e6-a7a7-5f79-b824-e7442218f649
* Version Independent ID: a626e689-b2ba-6a11-c17b-9f1fd0e565cd
* Content: [Get-ADUser (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/Get-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Get-ADUser.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by CockneyRhymingJedi** [comment]
Hi F.

If you use the following `(Get-ADUser XXX -Properties memberOf).memberOf` it will list all groups the user XXX is a member of.

Cheers,

CRJ

**Comment by fidfbonanno** [comment]
> Hi @fidfbonanno
> 
> If you use the following `(Get-ADUser XXX -Properties memberOf).memberOf` it will list all groups the user XXX is a member of.
> 
> Cheers,
> 
> CRJ

Great!
It works, thank you very much!
