### ISSUE TITLE
No Content Here

### ISSUE THREAD

**Issue by joebeale** [MicrosoftDocs/windows-powershell-docs#2293]
This article is a stub and NEEDS content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06d2066-aa89-bca4-9231-28ff7c728cad
* Version Independent ID: bfa412d0-55ca-33b7-7966-7c08a9dc0381
* Content: [Export-Trace (provisioning)](https://docs.microsoft.com/en-us/powershell/module/provisioning/export-trace?view=win10-ps)
* Content Source: [docset/windows/provisioning/Export-Trace.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/provisioning/Export-Trace.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by msbemba** [comment]
@joebeale Thank you for your feedback. The document has been updated with information on all parameters and their description. If you like to have more information about a specific parameter, please do let us know.

Hope this helps!

Thanks
Sri
