### ISSUE TITLE
Parameter CertificateType has error in parameters

### ISSUE THREAD

**Issue by dlsmlss** [MicrosoftDocs/windows-powershell-docs#2295]
> -CertificateType
> Specifies the type and purpose of the certificate. The acceptable values for this parameter are:
> 
> Service-Communications
> **Token-Encryption**
> Token-Signing

Replace with 

> -CertificateType
> Specifies the type and purpose of the certificate. The acceptable values for this parameter are:
> 
> Service-Communications
> **Token-Decrypting**
> Token-Signing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31c38ade-0ad3-4888-b5d7-e12197885a8d
* Version Independent ID: 72baefd3-a0b3-f174-69b6-122936a31a6f
* Content: [Add-AdfsCertificate (ADFS)](https://docs.microsoft.com/en-us/powershell/module/adfs/add-adfscertificate?view=win10-ps)
* Content Source: [docset/windows/adfs/Add-AdfsCertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/Add-AdfsCertificate.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
Under investigation. Thank you for the feedback
