### ISSUE TITLE
Wrong HashAlgorithm in example 3

### ISSUE THREAD

**Issue by faix** [MicrosoftDocs/windows-powershell-docs#2299]
Hello,

The description for that example specifies that the hashalgorithm is SHA256 while the actual code says SHA1. This could lead to issues when copy pasting. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e97ed95-5f4c-da95-206a-2f7a6bc050a7
* Version Independent ID: 3e8d8dc6-b877-22f5-4318-33479174d9fd
* Content: [Install-AdcsCertificationAuthority (ADCSDeployment)](https://docs.microsoft.com/en-us/powershell/module/adcsdeployment/install-adcscertificationauthority?view=winserver2012r2-ps&redirectedfrom=MSDN)
* Content Source: [docset/winserver2012r2-ps/adcsdeployment/install-adcscertificationauthority.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/adcsdeployment/install-adcscertificationauthority.md)
* Product: **powershell**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
Thank you for the catch. An independent contributor is going to follow up with revisions accordingly.
