### ISSUE TITLE
Windows Server 2008 R2 not supported?

### ISSUE THREAD

**Issue by kcswe** [MicrosoftDocs/windows-powershell-docs#2301]
[Enter feedback here]
As per the text in this document the Get-DnsServer cmdlet is supported in Windows Server 2008 R2. 
I cannot see that it's possible. I've tested with a fully patched Windows Server 2008 R2 (without ESU) with Powershell 5.1 and the command is unrecognized.

Thanks,
/Kenny

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6df784d1-fcec-ba75-56c1-17ff67e914b6
* Version Independent ID: 1928b38e-cd31-45e4-a927-ee17e477fb61
* Content: [Get-DnsServer (DnsServer)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=win10-ps)
* Content Source: [docset/windows/dnsserver/Get-DnsServer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/Get-DnsServer.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@kcswe Thank your for your feedback.

Windows Server 2008 R2 is out of support so this information is probably outdated. I will remove it from the article.
