### ISSUE TITLE
This cmdlet outputs nothing

### ISSUE THREAD

**Issue by sukkerfri** [MicrosoftDocs/windows-powershell-docs#2306]
The cmdlet does not return any object upon successful printerport creation.
According to the doc the output of this cmdlet should be the newly created PrinterPort CimInstance object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23f3ea76-3e25-ff08-7ba8-a6308424c11a
* Version Independent ID: 23ff5a20-6da6-e2fc-22b0-e772c8af494a
* Content: [Add-PrinterPort (PrintManagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/add-printerport?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/printmanagement/Add-PrinterPort.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/printmanagement/Add-PrinterPort.md)
* Product: **powershell**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
Hello, @sukkerfri This question can best be answered via [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community). 

Thanks again.

The issues section of this repository is intended for documentation problems.

Feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.

**Comment by sukkerfri** [comment]
Hi.
I didn't mean it to be a question more a statement. The documentation states that the cmdlet will output the newly created object. But this appears to be wrong. The cmdlet does not give any output upon creating a new printer port.
