### ISSUE TITLE
EXAMPLE 2 type

### ISSUE THREAD

**Issue by luke-MEE** [MicrosoftDocs/windows-powershell-docs#231]
Example 2 is missing a closing bracket at the end of the first line of code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8826868-6a17-4641-31a6-5ec04cc5bfdc
* Version Independent ID: 5ac34549-8420-f25b-3da9-2ae370c521c3
* Content: [Reset-PhysicalDisk (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/reset-physicaldisk?view=win10-ps#feedback)
* Content Source: [docset/windows/storage/reset-physicaldisk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/reset-physicaldisk.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by luke-MEE** [comment]
typo*

**Comment by aidanfinn** [comment]
As above - missing bracket on the example, and it won't work if multiple disks match the condition. See:

$phydisk = (Get-Physicaldisk | Where-Object -FilterScript {$_.HealthStatus -Eq "Unknown"})
foreach ($item in $phydisk)
{
    Reset-PhysicalDisk -FriendlyName $item.FriendlyName
}

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @luke-MEE 

The issue that you have addressed has been fixed via the following commit. Thank you for your feedback.

[ Update reset-physicaldisk.md ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/66aae808a1d215b05a02aade88c2a50341cf1b99)

**Comment by e0i** [comment]
@officedocsbot close
