### ISSUE TITLE
Removing FSP objects from ADgroup

### ISSUE THREAD

**Issue by Jardenius** [MicrosoftDocs/windows-powershell-docs#2311]
How to remove ADgroup members that are ForeignSecurityObjects, even defining the FSP object, by its Distinguishedname, the remove-adgroupmember wont find it. The FSP object can be found using get-Adobject command though.
We have a security group with members from local domain, and from 20 trusted domains, and total user amount in group ~25000. (trusted domain members are presented  as groupmembers by FSP Object)
So far only method for this is to use old "dsmod group -rmmbr" commandline tool, but it is far from handy. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f872917-5102-3701-fbd0-64092b78f683
* Version Independent ID: d53a52b7-110c-e5af-a7ec-d5767a3c4259
* Content: [Remove-ADGroupMember (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/remove-adgroupmember?view=win10-ps)
* Content Source: [docset/windows/addsadministration/Remove-ADGroupMember.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Remove-ADGroupMember.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by MaratMussabekov** [comment]
Hello, it wouldn't work this way.
From my experience, to remove member located in another domain, you need to define it first, as follows: `$user = get-aduser User01 -server DC.domain01.local`

In my case, we had different naming convention for each domain (each user in domain01 has name D01_UserXX, in domain02 - D02_UserXX, etc.), so I used following:

```
if ($member -like D01_*){$user = get-aduser $member -server DC.domain01.local}
elseif ($member -like D02_*){$user = get-aduser $member -server DC.domain02.local}
elseif ($member -like D03_*){$user = get-aduser $member -server DC.domain03.local}
...
Remove-ADGroupMember -identity $group -Members $user
```

I would also recommend to read this - https://docs.microsoft.com/en-us/archive/blogs/adpowershell/addingremoving-members-from-another-forest-or-domain-to-groups-in-active-directory

Thank you
