### ISSUE TITLE
Better examples for -ExclusionProcess

### ISSUE THREAD

**Issue by middletonk** [MicrosoftDocs/windows-powershell-docs#2313]
Hey, we could use better examples on the ExclusionProcess param. The implication is that a full path to the EXE is required which would make this parameter less valuable than ExclusionPath. However, there is great value in being able to identify EXEs by process name regardless of file system location.

This is a valid command, is it not? So this could be a good example to include in the PoSh module browser for Add-MpPreference? 

Add-MpPreference -ExclusionProcess ComplianceAuditService.exe, Dsamain.exe, EdgeTransport.exe, fms.exe, hostcontrollerservice.exe, inetinfo.exe, Microsoft.Exchange.AntispamUpdateSvc.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 461216fa-ee02-e1f6-58e1-6dcc28cbdb2d
* Version Independent ID: 121fb94d-4a82-985c-787b-2d3f583015e9
* Content: [Add-MpPreference (Defender)](https://docs.microsoft.com/en-us/powershell/module/defender/add-mppreference?view=win10-ps)
* Content Source: [docset/windows/defender/Add-MpPreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/Add-MpPreference.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by RAJU2529** [comment]
@middletonk , i think the perfect command is  to  include  the correct file path for example 

**Add-MpPreference -ExclusionProcess C:\Windows\System32\ComplianceAuditService.exe**

or 
**Add-MpPreference -ExclusionProcess C:\Windows\System32\Comp\ComplianceAuditService.exe**

**Comment by MaratMussabekov** [comment]
Hello,
**This is a valid command, is it not?**  - yes it is. It is not mandatory to specify full path (but it would be safer to specify).
Look at this article for more details - https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-process-opened-file-exclusions-microsoft-defender-antivirus.

Thank you
