### ISSUE TITLE
Send-RDUserMessage

### ISSUE THREAD

**Issue by pear7777** [MicrosoftDocs/windows-powershell-docs#2318]
This command will not send a message to disconnected sessions.

That information is missing on this page 

Oh c'mon, do you really use GITHUB for USER support, that's the worst platform. completely user UNfriendly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9faa9fa-7446-fe9a-ff27-605b9576a96c
* Version Independent ID: 6a3124ea-cdb7-60f1-a3d5-af50b702dcef
* Content: [Send-RDUserMessage (RemoteDesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/send-rdusermessage?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/Send-RDUserMessage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/Send-RDUserMessage.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
Hello, @pear7777 

The GitHub repository is used for documentation feedback, and not user support. 

Please consider checking with PowerShell community for your problems,

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

**Comment by pear7777** [comment]
Don't tell me tell Microsoft, they sent me here.
