### ISSUE TITLE
Example is incorrect

### ISSUE THREAD

**Issue by boffies** [MicrosoftDocs/windows-powershell-docs#232]
I believe the example should only be "C" not "C:\"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec1b7d0-0636-ef29-b918-1176cffa29f9
* Version Independent ID: 21a4204c-956a-11d3-93b9-c513456e16fb
* Content: [Get-DedupProperties (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-dedupproperties?view=win10-ps#examples)
* Content Source: [docset/windows/storage/get-dedupproperties.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-dedupproperties.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @boffies 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
