### ISSUE TITLE
PSH Commands & Comments in Example #2.

### ISSUE THREAD

**Issue by yupsay** [MicrosoftDocs/windows-powershell-docs#233]
The example should rather be listed using HTML comments like this. For the PSH Comment HASH isn't working & changing the formatting instead in your ^C / ^V. Also remove the <b> PS C:\> </b> from the second line onwards.

 # This line gets all disk objects and then pipes the objects to the next command.
   Get-Disk |

 # This line selects only objects where the PartitionStyle property value equals "RAW", and then pipes the objects to the next command.
   Where-Object PartitionStyle -Eq "RAW" |

 # This line initializes all Disk objects in the pipeline and then pipes the objects to the next cmdlet.
   Initialize-Disk -PassThru |

 # This line creates a maximum sized partition on each initialized Disk object, assigns a drive letter to the partitions, and then pipes the objects to the next cmdlet.
   New-Partition -AssignDriveLetter -UseMaximumSize |

 # This line formats all newly partitioned disks.
   Format-Volume

**Comment by e0i** [comment]
@yupsay Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
