### ISSUE TITLE
Regarding "ScanPurgeItemsAfterDelay" Default Values

### ISSUE THREAD

**Issue by kahosoka** [MicrosoftDocs/windows-powershell-docs#2339]
[Enter feedback here]
Hello All,

Thank you for your cooperation.
In this public information, "ScanPurgeItemsAfterDelay" default value is indicated as "30".
However, when I run the "Get-MpPreference" command from my terminal, it returns "15".
GPO, Intune, etc., have not configured the policy that configures the above values.
Therefore, there is a possibility that there is an error in the public information, so please confirm and correct it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43741f9-62d8-4bcb-8f1e-2f9bcf0b8e92
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (Defender)](https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&viewFallbackFrom=win10-ps)
* Content Source: [docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/defender/Set-MpPreference.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by kahosoka** [comment]
Dear All, I apologize to bothering you. I guess you are verifying for it, so I'll be glad if I can get your reply when you are comfortable. Actually our customer is waiting so. Thank you.

**Comment by e0i** [comment]
Yes, An independent contributor is revising the issue. However, Please note that that "waiting customer" is not responsibility. Thanks for the feedback and expect updates soon.

**Comment by kahosoka** [comment]
Sure. Thank you.
