### ISSUE TITLE
Parameter -Confirm 

### ISSUE THREAD

**Issue by kaufmajo** [MicrosoftDocs/windows-powershell-docs#234]
Is it true that the default value of the -confirm parameter is "false", as described in the docs for Remove-ADUser?

Why do I explicitly have to set the "Confirm" Paramter to false if I want to force deletion ...--&gt; Remove-ADUser -Confirm:$false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7d3a35a-54a1-d8cf-0073-1829cf7796a1
* Version Independent ID: 0f4903f2-61b0-e857-8eb1-44f3ee71a182
* Content: [Remove-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/remove-aduser?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/remove-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/remove-aduser.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by jseerden** [comment]
I agree. If you do not specify the confirm parameter, is defaults to True.

The Notes section mentions it though:
By default, this cmdlet has the Confirm parameter set, which prompts you to confirm before a removal of the specified object type can occur. To bypass prompting for confirmation before removal, you can specify -Confirm:$False when using this cmdlet.

**Comment by kaufmajo** [comment]
Thx, seems that I missed the notes section.

**Comment by thetrav** [comment]
Why is this closed?  The docs still say it defaults to False, where it seems to default to True
