### ISSUE TITLE
Mention that the function is legacy within the documentation

### ISSUE THREAD

**Issue by iona-evans** [MicrosoftDocs/windows-powershell-docs#2342]
The documentation should mention that `Get-ADGroup` is a legacy function and should be replaced with `Get-AzAdGroup` instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3effad82-3c38-529d-42b7-8e4f51cffb82
* Version Independent ID: 429dfc0a-c3af-af29-8f72-8ed0af8227b7
* Content: [Get-ADGroup (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adgroup?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/addsadministration/Get-ADGroup.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/addsadministration/Get-ADGroup.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@iona-evans Hi Iona,

Thank you for you feedback.

I think **Get-ADGroup** and **Get-AzAdGroup** are to separate commands and are both valid. One is for on-premises AD and the other is for Azure AD. Could you provide the source of information about `Get-ADGroup` being a legacy function?
