### ISSUE TITLE
How can i remove the disk info without disk number?

### ISSUE THREAD

**Issue by Jeffrey1080** [MicrosoftDocs/windows-powershell-docs#2345]
Hi,

i map 1 lun from my storage to a windows 2016 cluster, and then unmap it.
after rescan the disk and reboot the server, and when i use "get-disk" , some disk info without disk number still shown.
how can i remove it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcf3704d-a8b4-edce-e8b6-670cc833314d
* Version Independent ID: d417c085-9397-5847-79dd-8836f0b1115d
* Content: [Get-Disk (Storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-disk?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/storage/Get-Disk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/storage/Get-Disk.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
Hello, @Jeffrey1080 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community regarding your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

If you feel that this document can also be updated with information related to your request, please comment and re-open this issue we would love to to follow-up with documentation updates.

Thank you for providing feedback.
