### ISSUE TITLE
how to select the printer port type programmatically.

### ISSUE THREAD

**Issue by Abendd** [MicrosoftDocs/windows-powershell-docs#2355]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b324c554-3222-a559-fb89-a70e254529ac
* Version Independent ID: 23ff5a20-6da6-e2fc-22b0-e772c8af494a
* Content: [Add-PrinterPort (PrintManagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/add-printerport?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/printmanagement/Add-PrinterPort.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/printmanagement/Add-PrinterPort.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
@-

The issues section of this repository is intended for documentation problems.

Closing because of the missing feedback. Please consult to [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community) for support questions. Thanks.
