### ISSUE TITLE
How can I specify the port type in parameters while adding a port? As in GUI we choose local port, Adobe PDF port monitor etc

### ISSUE THREAD

**Issue by kartikbathla** [MicrosoftDocs/windows-powershell-docs#2356]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b324c554-3222-a559-fb89-a70e254529ac
* Version Independent ID: 23ff5a20-6da6-e2fc-22b0-e772c8af494a
* Content: [Add-PrinterPort (PrintManagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/add-printerport?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/printmanagement/Add-PrinterPort.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/printmanagement/Add-PrinterPort.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@kartikbathla 

Thank you for you feedback.

I think the reason behind this is that there is no actual Port type in PowerShell. Ports are either `MSFT_PrinterPort` or `MSFT_LocalPrinterPort`. Then it actually depends on the drive used when adding the printer itself. If are adding a port to a printer that has the `Microsoft Print To PDF` driver you will be adding PDF port type. You cannot add PDF port to a printer installed with `Microsoft XPS Document Writer v4` driver for example.

Hope my explanation makes it clearer. Let me know if you have any questions.
