### ISSUE TITLE
Update-Help fails for HostNetworkingService, WindowsUpdateProvider, all locales

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-powershell-docs#236]
+ CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand

It's been there for a while.

**Comment by TheBestPessimist** [comment]
Just to make sure "+1" means that i have the same issue. (since i've +1ed multiple issues relating to `update-help`.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello, thanks for your feedback.
I think your question is more suitable for support resources like https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10

Hope this information helps you.

**Comment by TheBestPessimist** [comment]
@get-itips what are you talking about?
Is this spam?

**Comment by get-itips** [comment]
Hello @TheBestPessimist  How are you? hope you are doing great.
I replied to the original poster that now seems out of GitHub (His account appears deleted)
This issue system is specifically for issues with documentation.
Other type of issues like the one the original poster submitted are handled by support services.
Hope this clarified the information provided.
Thank you.

**Comment by TheBestPessimist** [comment]
But imo what @op said is a documentation issue. The problem with `Update-Help` happens since at least a year ago in Windows 10. 

Here's what happens on my machine:

```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> Update-Help
Update-Help : Failed to update Help for the module(s) 'HostNetworkingService, WindowsUpdateProvider' with UI culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI culture en-US. Make sure the HelpInfoUri property in the module manifest is valid or check
your network connection and then try the command again.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand

PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\WINDOWS\system32> Date

Thursday, April 4, 2019 08:39:12

```

**Comment by get-itips** [comment]
Hello @TheBestPessimist thanks for your reply.
This issue system is specific for when you find issues with how the documentation is written online, for example if some specific article is missing some parameter information.
There is this specific resource I sent when you need support, and that includes errors when you try to download/update/ the help of a cmdlet in your setup.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@TheBestPessimist  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. 
https://docs.microsoft.com/powershell/#pivot=main&panel=community

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
