### ISSUE TITLE
In Example 2: Change -RegistryValue "Disable" to -RegistryValue 0

### ISSUE THREAD

**Issue by MichaelMasuch** [MicrosoftDocs/windows-powershell-docs#2366]
[Enter feedback here]
"Set-NetAdapterAdvancedProperty" with string like "Disable" in the example section does not work. (See error below). But using "String" like 1 or 0 does work. Maybe you could change the "Example 2".

`Set-NetAdapterAdvancedProperty  -RegistryKeyword "EEELinkAdvertisement" -RegistryValue "Disable"`

    Set-NetAdapterAdvancedProperty : No matching keyword value found. The following are valid keyword values: 0, 1
    At line:1 char:1
    Set-NetAdapterAdvancedProperty  -RegistryKeyword "EEELinkAdvertisemen ...
        + CategoryInfo          : InvalidArgument: (MSFT_NetAdapter...AF8DD1057}:...):ROOT/StandardCi...ertySettingData) [Set-NetAdapterAdvancedProperty], CimException
        + FullyQualifiedErrorId : Windows System Error 87,Set-NetAdapterAdvancedProperty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1a5d7a-ea43-0654-7989-5f6cc4d86e8b
* Version Independent ID: a633b80a-4d64-6e3f-6436-b56a7f94e1ef
* Content: [Set-NetAdapterAdvancedProperty (NetAdapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/set-netadapteradvancedproperty?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/netadapter/Set-NetAdapterAdvancedProperty.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/netadapter/Set-NetAdapterAdvancedProperty.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@MichaelMasuch 
Thank you for your feedback. 

Indeed the accepter values are:
```
ValidDisplayValues        : {Off, On}
ValidRegistryValues       : {0, 1}
```
