### ISSUE TITLE
Restore-VMSnapshot: Default value for parameter "-Confirm" is wrong

### ISSUE THREAD

**Issue by Herr-Sepp** [MicrosoftDocs/windows-powershell-docs#2371]
Documentaion says:

> Default value: False

But this is not the real behavior

```
Restore-VMSnapshot -VM $vm -Name "base"
Restore-VMSnapshot -VM $vm -Name "base" -Confirm
```

Both times the user is asked for confirmation.
The default value for Confirm is "true", the switch is always "on".

You have to disable it explicitly as shown in example 2.
`-Confirm:$false`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89130772-6a19-2510-1ab6-0c80b56d84c0
* Version Independent ID: f3128f15-ff5d-df67-d8d2-6e4928e11496
* Content: [Restore-VMSnapshot (Hyper-V)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/restore-vmsnapshot?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/hyper-v/Restore-VMSnapshot.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/hyper-v/Restore-VMSnapshot.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by sdwheeler** [comment]
@Herr-Sepp Thanks for your feedback. Technically, all switch parameters default to `$false`.  When you use a switch parameter the value becomes `$true`. So you must use `-Confirm:$false` to force it to be false.

But `-Confirm` is an interesting case. The behavior of `-Confirm` depends on the value of the [`$ConfirmPreference`](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables#working-with-preference-variables) variable and the impact rating defined in the cmdlet. If the impact is high enough, you get prompted for confirmation unless you explicitly use `-Confirm:$false`. 

This is not explained well in the documentation.

**Comment by e0i** [comment]
@Herr-Sepp 

The switch parameters are a common source of confusion. Find below relevant discussion from similar issues:


https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1628#issuecomment-581492354

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1463#issuecomment-541198962

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1395#issuecomment-546609595

Thanks.
