### ISSUE TITLE
This command needs improvement

### ISSUE THREAD

**Issue by nandaguruswamy** [MicrosoftDocs/windows-powershell-docs#2376]
This command will retrieve the adfs webtheme but will not provide the name of the theme or which application the theme has been applied on. So ultimately, we know how many themes there are but we dont know which theme applies to each app which is the main idea of this command. 

Thanks
Nanda

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a46c22-b2d4-b3dd-5c65-61ccd553c9c6
* Version Independent ID: 9eb6b890-5791-3cae-f24a-a40e0c79997c
* Content: [Get-AdfsRelyingPartyWebTheme (ADFS)](https://docs.microsoft.com/en-us/powershell/module/adfs/get-adfsrelyingpartywebtheme?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/adfs/Get-AdfsRelyingPartyWebTheme.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/adfs/Get-AdfsRelyingPartyWebTheme.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by sdwheeler** [comment]
@nandaguruswamy Thanks for your feedback, but this is a product issue not a documentation issue. Please submit your feedback to https://windowsserver.uservoice.com/forums/301869-powershell.
