### ISSUE TITLE
Possible misspelled word

### ISSUE THREAD

**Issue by Wrech01** [MicrosoftDocs/windows-powershell-docs#2384]
Test-NetConnection -InformationLevel "Detailed" -DiagnoseRouting

RouteSelectionEvents:  Reason: Rechability 

"Reachability" maybe?

**Comment by e0i** [comment]
The typo doesn’t appear to be in the article for Test-NetConnection. This repository covers technical documentation, not in-app CLI messaging. You may consider checking [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community) for feedback related to the module itself.

Thanks.
