### ISSUE TITLE
only enabled ciphersuites?

### ISSUE THREAD

**Issue by martinbherbener** [MicrosoftDocs/windows-powershell-docs#239]
It appears that that this cmdlet only displays enabled ciphersuites (if I use disable-tlsciphersuite on a particular suite and then run this cmdlet, the disabled one is not listed); but documentation is not clear if this is intent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec96c08-42f2-4f28-312f-0bd043aa74c2
* Version Independent ID: 563d7048-b46e-c459-168c-ff2aa028a0d1
* Content: [Get-TlsCipherSuite (tls)](https://docs.microsoft.com/en-us/powershell/module/tls/Get-TlsCipherSuite?view=win10-ps)
* Content Source: [docset/windows/tls/get-tlsciphersuite.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/tls/get-tlsciphersuite.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @martinbherbener thanks for your feedback.
Actually, Disable-TlsCipherSuite as the documentation of that cmdlet says: 

> This cmdlet removes the cipher suite from the list of Transport Layer Security (TLS) protocol cipher suites for the computer

So Get-TlsCipherSuite is showing to you, the ones that are enabled and present in the computer.

Hope this information has helped you.

Thanks!

**Comment by martinbherbener** [comment]
Ok, well, I agree that the Disable-TlsCipherSuite documentation is clear.  However, if I want to understand what Get-TlsCipherSuite is going to do, I am reading this:

The Get-TlsCipherSuite cmdlet gets the ordered list of cipher suites for a computer that Transport Layer Security (TLS) can use.

and I don't think it's obvious that "can use" means "enabled".  Maybe no one else finds it confusing.

thanks!

Martin

**Comment by get-itips** [comment]
Thanks @martinbherbener I'll create a PR to improve the article based on your feedback.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @martinbherbener Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
