### ISSUE TITLE
Use the system user to run the command Add-AppxPackage

### ISSUE THREAD

**Issue by maysaribeiro** [MicrosoftDocs/windows-powershell-docs#2391]
I have a service that performs some processes and can even be run installation commands. This service is performed by the local system user (SID S-1-5-18).

So I sent the command below for the service to run, which it runs using powerShell as the local system

`Add-AppxPackage -Path "C:\Dir1\Dir2\Dir3\Windows\App.UWP_2.0.27.0_x64.msixbundle" -DependencyPath "C:\Dir1\Dir2\Dir3\Windows\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx", "C:\Dir1\Dir2\Dir3\Windows\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx", "C:\Dir1\Dir2\Dir3\Windows\Dependencies\x64\Microsoft.UI.Xaml.2.4.appx", "C:\Dir1\Dir2\Dir3\Windows\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx"`

However when trying to run, I get the error:

> The AppX Deployment operation for CodeWith7-CodeWith4-CodeWith4-CodeWith4-CodeWith12_2.0.27.0_neutral_ ~ 3kncj78a7wnxj failed with error 0x80073CF9. The specific error text for this failure is: Add deployment operation rejected in the CodeWith7-CodeWith4-CodeWith4-CodeWith4-CodeWith12_2.0.27.0_neutral ~ _3kncj78a7wnxj package: App.UWP_2.0.27.0_x64.msixbundle installation request because the account of the Local System is not allowed to perform this operation.

When I change the service manually so that it runs using a local administrator user, the command runs without any error. I have a business need to run this command as a local system. Does anyone know how I can do this?
Or, does anyone know how to explain to me WHAT is done in the process that requires an ADM user?

- [x] I have already verified that the machine has developer mode enabled.
- [x] Before executing the Add-AppPackage command I perform the import of the certificate, so the certificate is installed: "Import-Certificate -FilePath \"{0}\"-CertStoreLocation Cert:\\LocalMachine\\Root", Path.Combine ( directoryInstallation, item)
- [x] I tried to change the command from Add-AppPackage to Add-AppxPackage, but it also didn't work
- [x] I tried to change the command to run Add-AppDevPackage.ps1, but it also didn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5641ac1-f6b1-8ac1-51f3-21f367316168
* Version Independent ID: 6dcca508-5e35-5cb4-942b-22a20dbb1a4d
* Content: [Add-AppxPackage (Appx)](https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/appx/Add-AppxPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/appx/Add-AppxPackage.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
@maysaribeiro 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
