### ISSUE TITLE
Insufficient documentation of Get-WebBinding

### ISSUE THREAD

**Issue by buksy90** [MicrosoftDocs/windows-powershell-docs#2403]
Hi, Im an occasional user of powerShell, I have some web bindings on IIS created and need to check if certificate is assigned and if not assign new one. I know there's a AddSslCertificate() function to be used to create new certificate, but I dont know what function to use to check if there's any already assigned.

So I thought I would check documentation of "Get-WebBinding" function to see what's the return type and what methods are there to use on result. But the documentation lacks any information about the object that is being returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2ab463-2b0d-1486-99a6-2662a1efd5a1
* Version Independent ID: c379633a-98a5-f98b-49da-8d9e28f4413d
* Content: [Get-WebBinding (WebAdministration)](https://docs.microsoft.com/en-us/powershell/module/webadministration/get-webbinding?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/webadministration/Get-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/webadministration/Get-WebBinding.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by MaratMussabekov** [comment]
Hello,
Get-WebBinding provides the exact information that described in the article - protocol and port number
In your case, I would recommend to install IISAdministration powershell module and use Get-IISSiteBinding cmdlet, which provides the information about the certificate.

Thank you
