### ISSUE TITLE
Docs for PKIClient seem to have gone missing

### ISSUE THREAD

**Issue by ThadHouse** [MicrosoftDocs/windows-powershell-docs#2408]
I was trying to lookup the parameters to New-SelfSignedCertificate, so I googled the cmdlet like I always do. The top google link is https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate which 404's.  In addition, on that 404 page  there are related search results pointing to Import-Certificate (PKIClient) that also 404, and on that page more 404 links. So it seems the docs for PKIClient have been deleted somehow. By going just to PKI it works, but I want to make sure that its known that those URLs are missing in case that was accidental, or data needs to be manually propagated somewhere.

**Comment by berndp-ms** [comment]
Not only for this module - seems to affect several modules below /powershell/module/  
(my customer reported remotedesktop missing)
