### ISSUE TITLE
Add-AdfsClient ClientType Parameter

### ISSUE THREAD

**Issue by davewoodward** [MicrosoftDocs/windows-powershell-docs#241]
The documentation indicates that "Unknown" is an acceptable value for the ClientType parameter.  However, under every circumstance I've tried this value is not acceptable.  Instead, I consistently get an ADMIN0023 error stating that I provided an incorrect value for property ClientType.  Based upon this, either the documentation is incorrect or could use some additional clarification regarding when this parameter may be set to Unknown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2262e4-5a7d-0311-36b6-6cc5cb5b0379
* Version Independent ID: 039d6f74-b6b2-06c6-2204-dd4c15517575
* Content: [Add-AdfsClient (adfs)](https://docs.microsoft.com/en-us/powershell/module/adfs/Add-AdfsClient?view=win10-ps)
* Content Source: [docset/windows/adfs/add-adfsclient.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/add-adfsclient.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith please merge this PR, if you find it suitable

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @davewoodward Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot closed
