### ISSUE TITLE
Any plan to address module name change?

### ISSUE THREAD

**Issue by cheong00** [MicrosoftDocs/windows-powershell-docs#2413]
# Documentation Issue
Currently the documentation is arranged according to corresponding name of PowerShell module. However if the module name for corresponding component is changed across OS versions, user will not be able to find the link to documentation using the old name, even if they changed the targeting OS version to view.

## Context of the issue

[The problem](https://docs.microsoft.com/en-us/answers/questions/353736/404-page-not-found-with-url-httpsdocsmicrosoftcome.html) is reported on Q&A forum.

## Detailed description of the issue

Take the RDS component for example:
https://docs.microsoft.com/en-us/powershell/module/rdmgmt/get-rdserver
Apparently the corresponding module name for Win2012R2 was "[RemoteDesktop](https://techcommunity.microsoft.com/t5/ask-the-performance-team/step-by-step-instructions-for-installing-rds-session-deployment/ba-p/375569)", so the link was used to be the following:
https://docs.microsoft.com/en-us/powershell/module/remotedesktop/get-rdserver

We should add a "History" table on the [main module page](https://docs.microsoft.com/en-us/powershell/module/rdmgmt/) to list out older module names for search engines to be able to lookup the new page for help of older modules.

It would be great if we can add some redirects from old module name to current location (This will have benefit of updating search engines too. Currently search will display the "remotedesktop" link which will return 404 result. Have "link" tag with ["canonical" attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#attr-canonical) in redirect file will certainly help).

Or better, to have the module names on the menu reflect to the module name that should be at that time. (On "Windows Server 2012 R2 PowerShell", the module name should be displayed as "RemoteDesktop" instead of "RDMgmt")

**Comment by cheong00** [comment]
[Reference](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7463) to original issue on another repository.

**Comment by e0i** [comment]
@sdwheeler Can you provide some insights into this feedback that concerns module names and redirection configuration? Also please let me know if there’s something that we the independent contributors can come up with to address this issue. Thanks.

**Comment by sdwheeler** [comment]
After more research I reverted the module name back to the original. So there should be no issue anymore. All the other modules that were renamed have redirections in place now. This issue can be closed.

**Comment by e0i** [comment]
Thank you!
