### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by hewhoisnobody** [MicrosoftDocs/windows-powershell-docs#242]
I'm trying to use this command to export the start layout. But it keeps giving me an error message.

Command im using: export-startlayout -path "C:\Users\Test\Desktop\Clean.xml"

Error Message: (below)
export-startlayout : The path C:\Users\Test\Desktop\Clean.xml did not resolve to a file.
At line:1 char:1
+ export-startlayout -path "C:\Users\Test\Desktop\Clean.xml"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-StartLayout], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.Windows.StartLayout.Commands.ExportStartL
   ayoutCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c11e894-7ba6-255b-334b-309b14fcb34e
* Version Independent ID: c1208227-6428-bee1-e2f3-0cda1f35dc1c
* Content: [Export-StartLayout (startlayout)](https://docs.microsoft.com/en-us/powershell/module/startlayout/export-startlayout?view=win10-ps#feedback)
* Content Source: [docset/windows/startlayout/export-startlayout.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/startlayout/export-startlayout.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @hewhoisnobody **thanks for your feedback**.

I tested the cmdlet in my lab, and I succesfully exported the layout, the cmdlet expects that all folders on the specified path be created before running it.
I could reproduce your error when the destination path wasn't fully created.

**Hope this information helps you**.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @hewhoisnobody 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
