### ISSUE TITLE
Invoke-GPUpdate doesn't work

### ISSUE THREAD

**Issue by cooldog77** [MicrosoftDocs/windows-powershell-docs#2422]
How do you get Invoke-GPUpdate to work or is it deprecated? I'm not sure if the module is installed or what or if there is another powershell command that runs a group policy update. I know I can always run "Invoke-Command -ComputerName 'COMPUTERNAME' -ScriptBlock { gpupdate /force }" but that would fly in the face of replacing command line with PowerShell, now wouldn't it?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 711cda71-87b4-de17-a876-05562aedd975
* Version Independent ID: 37fb3294-2045-498b-0781-d3795825b8dc
* Content: [Invoke-GPUpdate (GroupPolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/invoke-gpupdate?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/grouppolicy/Invoke-GPUpdate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/grouppolicy/Invoke-GPUpdate.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
@cooldog77 
Thank you for your feedback.

This cmdlet has some requirement to work:
[GroupPolicy](https://docs.microsoft.com/powershell/module/grouppolicy/)

> This topic contains the brief descriptions of the Windows PowerShell cmdlets that are for use in administering Group Policy in Windows Server and Windows client with Remote Server Administration Tools (RSAT) installed. (RSAT includes the GPMC and the Group Policy cmdlets.)

This means you need to have Group Policy Management feature install in order to run the cmdlet.

**Comment by cooldog77** [comment]
Seems this should be a command on every computer/server and not require an additional module, especially one that requires RSAT to be installed, but thanks.

**Comment by sdwheeler** [comment]
@cooldog77 You are requesting changes to the product. For modules that ship in Windows, use the Windows Feedback Hub. For more information, see [Send feedback to Microsoft with the Feedback Hub app][1].

[1]: https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332

**Comment by cooldog77** [comment]
Submitted.
