### ISSUE TITLE
Add-DnsServerResourceRecord fails to support 2048-bit DKIM records

### ISSUE THREAD

**Issue by mcnaugha** [MicrosoftDocs/windows-powershell-docs#2423]
A note about this tool limiting TXT records to 254 characters might be useful. I lost hours to trying to find a solution but I don’t think there is one. The RFC defines TXT strings as being allowed up to 255 characters and you can have multiple strings. Microsoft knows this, at least in terms of the DNS UI tool supporting 255 characters and multiple strings. If an organisation wishes to add a 2048-bit DKIM signature to 160 zones then this tool creates a severe handicap for them. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64226e08-8175-d9b6-1272-a4e016413fb9
* Version Independent ID: fcb077f7-9145-7727-21c6-8c4ed7fda8fd
* Content: [Add-DnsServerResourceRecord (DnsServer)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
Hello, @mcnaugha You can provide feedback on the cmdlet itself via the [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community).

The issues section of this repository is intended for documentation problems.
 
Feel free to reply if there is anything else that could be done to improve the document.

Thanks.

**Comment by mcnaugha** [comment]
As my comment said... it is a documentation issue that it does not warn admins. That's what the first sentence said. It's not product feedback. I've already left the feedback in relevant forums. It needs one of those purple warning banners.

**Comment by e0i** [comment]
@mcnaugha

Thank you for the clarification! It has been ambiguous to me that whether this has been a feedback towards documentation or the module. I am routing this feedback to an independent contributor and expect an update soon.

This documentation is partially open source. Please note that if you have any further feedback, you are welcome to come up with a PR by editing the associated file via GitHub, and your contribution will be reviewed. You don’t need to do that for this specific issue.

Thank again, and stay safe.

**Comment by Levan777** [comment]
Anything on this? I just can't figure out how can I add long text in DNS by powershell :( please help someone

**Comment by velkovb** [comment]
@mcnaugha Thank you for you feedback.

I have been trying to replicate the issue but was not able to. Successfully added a txt record with 255 characters. Could your provide an example of the command that leads to the error?

What is the environment you are running this in (OS, Powershell versions)?

**Comment by e0i** [comment]
Closing the issue based on the comment above. Thanks.

**Comment by mcnaugha** [comment]
> @mcnaugha Thank you for you feedback.
> 
> I have been trying to replicate the issue but was not able to. Successfully added a txt record with 255 characters. Could your provide an example of the command that leads to the error?
> 
> What is the environment you are running this in (OS, Powershell versions)?

I would ask you the same question. Can you supply the command you used that worked? No one seems to know the syntax to support 255 characters. It's not the same as for a 1024-bit key.

**Comment by mcnaugha** [comment]
Here is an example 2048-bit key:

MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy6OAXCmjYT823gq+DXRjXdsypt7iepfl4pkvLRVN8wRwoND2Fk2aVlG+CitAeJ0nqWn7JAPjoTXpFtHnOWMN7ay/atQd+DcLLHfJkpRvsYSIQ1jkIp17CkWF6G+nwLGJcNFndOdB8oawpppyESE7+DiZae8bDicaTK8oPU0J7iogeZ1fgvmutwNtNzZHiSgwF9euCiX6lTmGe+0oZ+gRUJnUmZevh//IZ+NyDkRV2kPxQBtM8brHUp
RL1c11q/CA0kC6C3ku+Pqmf6A8CGT+qvlCeQ2lVqlBydQL5UjiixUEwkSrgUEKoKE2Hqw97WrDEJZqngtuqma9hWoAsKVbzwIDAQAB


$domain = "aitkenhead.n-lanark.sch.uk"

$dkim = "v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC7+pAFJv0q84jSLITxdjIQPpGsOtfwF+0G1cwal84rSLjzBHrrxnyiKKAqqqxqyNnLVAvhS/sE/7w9xnzRE7vGINBXkcpHziLnxfAFraMJ7qkkRLyC7TBauGwOtBT3sMwSrkNlAQovZ9JJiUPvJvSEFocmfpjHZrTgXXp5FWZGtQIDAQAB"

$dkim2 = "v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy6OAXCmjYT823gq+DXRjXdsypt7iepfl4pkvLRVN8wRwoND2Fk2aVlG+CitAeJ0nqWn7JAPjoTXpFtHnOWMN7ay/atQd+DcLLHfJkpRvsYSIQ1jkIp17CkWF6G+nwLGJcNFndOdB8oawpppyESE7+DiZae8bDicaTK8oPU0J7iogeZ1fgvmutwNtNzZHiSgwF9euCiX6lTmGe+0oZ+gRUJnUmZevh//IZ+NyDkRV2kPxQBtM8brHUp
RL1c11q/CA0kC6C3ku+Pqmf6A8CGT+qvlCeQ2lVqlBydQL5UjiixUEwkSrgUEKoKE2Hqw97WrDEJZqngtuqma9hWoAsKVbzwIDAQAB"

Add-DnsServerResourceRecord -DescriptiveText $dkim -Name sea1024._domainkey -Txt -ZoneName $domain -TimeToLive 0:1:0:0

Add-DnsServerResourceRecord -DescriptiveText $dkim2 -Name sea2048._domainkey -Txt -ZoneName $domain -TimeToLive 0:1:0:0

**Comment by velkovb** [comment]
@mcnaugha Thanks. I just did a random string with 255 characters length. I will try it again and provide the command and test you scenario. May I also ask about the PowerShell and OS versions that you are using? This issue is opened under the Server 2019 version of the article.

**Comment by mcnaugha** [comment]
Yes it’s Windows Server 2019.

Tried in both PowerShell 5.1 and 7.1.3.

**Comment by velkovb** [comment]
@mcnaugha
Apologies, I must have messed my tests. It is indeed 254 characters in MS DNS. I found this article related to [Azure DNS](https://docs.microsoft.com/azure/dns/dns-zones-records#txt-records). According to the specification if you do the following should work:

```powershell
$dkim2 = "v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy6OAXCmjYT823gq+DXRjXdsypt7iepfl4pkvLRVN8wRwoND2Fk2aVlG+CitAeJ0nqWn7JAPjoTXpFtHnOWMN7ay/atQd+DcLLHfJkpRvsYSIQ1jkIp17CkWF6G+nwLGJcNFndOdB8oawpppyESE7+DiZae8bDicaTK8oPU0J7iogeZ1fgvmutwNtNzZHiSgwF9euCiX6lTmGe+0oZ+gRUJnUmZevh//IZ+NyDkRV2kPxQBtM8brHUpRL1c11q/CA0kC6C3ku+Pqmf6A8CGT+qvlCeQ2lVqlBydQL5UjiixUEwkSrgUEKoKE2Hqw97WrDEJZqngtuqma9hWoAsKVbzwIDAQAB"
$dkim2_part1 = $dkim2.Substring(0,252)

$dkim2_part2 = $dkim2.Substring(252,$dkim2.Length - 252)

Add-DnsServerResourceRecord -DescriptiveText "$dkim2_part1`r`n$dkim_part2" -Name sea2048._domainkey -Txt -ZoneName $domain -TimeToLive 0:1:0:0
```
It does introduce a new line but according to specs clients should be able to handle that.

If it is longer that 254*2 you could probably find better logic to split it.  

I will work on adding the limit to the article.

Let me know if that helps.

**Comment by mcnaugha** [comment]
Apologies, I have had a very high workload. I just tried your suggestion and realised I'd tried this before. While this appears to result in success in the UI, it doesn't work in the real world of DNS. The key needs to be across several lines. Here is the .dns file entry from a working 2048-key:

sea1._domainkey         3600	TXT	( "v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzd4oTjghf4xR4VhiVqCb"
                        		"Gz/VUPrWx31njrxCRtQ7Q4vlu9yM7tds71LoL56zu9bn/F1HriOA+lSSwn8YXy2b"
                        		"Ha7sJsdpmjRdCCiBNyHDYBoz3iwUbXFlq5+gRvyFxJ6Zki0aqUqcdJnBhgJZCjq9"
                        		"l0hU0Aya20uzvHxfqWwYzQF0yVOHgncbuUo4KGQU2UtmOIMWBaxeawtRRUVXmrA2"
                        		"YkP35CYw3OTacMjioosz6uFFd9xkUKAcpsYklz5a5+j1nsVOnOA0/6IyHKznswvj"
                        		"I8SRNNBETNsg16VOy8E4Ap5klwAu5jYF26ztBui08T5WqzKTGYzfwNrVlvxJmHjz"
                        		"BQIDAQAB" )

Here is what you get with the substring process:

sea2048._domainkey      3600	TXT	( "v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp6yteuJRUW+NTQiKeFvv53VJs76yjf3q4HieSvXLe9HkMxwppBIjViHrb7pnLN5dSRocubQwDmmoZB6vHCHrci+LHX3LKgqW0QWtYYGKPWCJeoolBLoynRIhVVMngrzur4JuC/TfMvO0Z4ts1e9J8XAYe+79edsINzViCnzGT4geBw3awAImFCnfTTbrcAby\015\012" )

It's one continuous string. DNS service will only work with the string broken down.

This guy helped me get a 2048-key into the UI: [https://www.xeams.com/ms-dns.htm](url) but this is no good when you have hundreds of domains to add keys to. You want to use PowerShell.
