### ISSUE TITLE
Broken link: New-SelfSignedCertificate

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windows-powershell-docs#2430]
https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps

Link doesn't work anymore.

**Comment by e0i** [comment]
@JeremyTBradshaw The module path has been renamed from `pkiclient` to `pki` and hence you can access the page via this link:

https://docs.microsoft.com/en-us/powershell/module/pki/new-selfsignedcertificate

Can you also share from which documentation article this broken link appears in? We’d like to revise the article accordingly.

Thanks.

**Comment by JeremyTBradshaw** [comment]
@e0i thanks for the info.  It's the bing search results for "New-SelfSignedCertificate" that has the broken link.  Here's my address bar when I search that, in Edge browser:

https://www.bing.com/search?q=new-selfsignedcertificate&FORM=RBY050&PC=EMMX20&refcv=VMetAeLATIopVhnd.0.0.2.1269

It might just take a while to update I suppose.  I couldn't find a direct link to the new page, but you provided it so that's perfect for my temp workaround.  Thanks!
