### ISSUE TITLE
 -ErrorAction SilentlyContinue not working for Get-ADGroup 

### ISSUE THREAD

**Issue by jahube** [MicrosoftDocs/windows-powershell-docs#2433]
-ErrorAction SilentlyContinue not working for Get-ADGroup 
 
so providing above still will throw an error when checking if a group exists

considering how long the command has been around its a shame it hasn't been fixed yet

(also -Whatif ..)

Best regards, Jan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c71fbd-74aa-d80a-33ae-1b4ebadaf75e
* Version Independent ID: b694a588-c889-b1fb-140a-ca107fa61d57
* Content: [Get-ADGroup (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/activedirectory/Get-ADGroup.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
Hello, Please submit this feedback via the [PowerShell Community?](https://docs.microsoft.com/powershell/#pivot=main&panel=community) This repository is concerned with documentation feedback. Thank you.
