### ISSUE TITLE
What does HealthStatus really mean?

### ISSUE THREAD

**Issue by Kondziowy** [MicrosoftDocs/windows-powershell-docs#244]
It's a bit vague - is it tied to some SMART counters? Failure prediction? Chkdsk status?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35052498-b82f-d18d-77cb-1087cc5e22d6
* Version Independent ID: 87ce481a-ac88-aaeb-c5f7-6490376ef6e2
* Content: [Get-PhysicalDisk (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-physicaldisk?view=win10-ps)
* Content Source: [docset/windows/storage/get-physicaldisk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-physicaldisk.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@kenwith A PR is available for this issue at #915. Kindly review. Thanks.

**Comment by j0rt3g4** [comment]
@e0i Any update on this PR? thank you in advance

**Comment by j0rt3g4** [comment]
New PR #1007

**Comment by e0i** [comment]
@Kondziowy 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
