### ISSUE TITLE
Powershell version 2

### ISSUE THREAD

**Issue by dzboy15** [MicrosoftDocs/windows-powershell-docs#245]
What would be the alternative to this command if you can only use powershell version 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb2351b9-efc4-4fb0-b8e0-5dd4ad8c5e0f
* Version Independent ID: 56cd3aab-2da5-e356-f393-ebecd081cb91
* Content: [Get-SmbConnection (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/get-smbconnection?view=win10-ps)
* Content Source: [docset/windows/smbshare/get-smbconnection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/smbshare/get-smbconnection.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @dzboy15 **Thanks for taking the time to leave feedback, we really appreciate it**.
As this module was introduced for Windows Server 2012, which Ps version is 3.0, it isn't available for Ps version 2.0 nor a version for it.
You will need to run classic command console net.exe to get this information.

**Hope this information has helped you**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @dzboy15 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
