### ISSUE TITLE
The `System.Object[]` title of the page, and in the page inside is completely wrong

### ISSUE THREAD

**Issue by v-karbovnichy** [MicrosoftDocs/windows-powershell-docs#2456]
The `System.Object[]` title of the page, and in the page inside is completely wrong.

I think it should be something like `DISM` or related, because the contents are about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36c65377-c01d-2952-1265-432fffba6825
* Version Independent ID: 583e305b-89cd-15a4-15de-822209712318
* Content: [System.Object\[\] Module](https://docs.microsoft.com/en-us/powershell/module/dism/?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/dism/DISM.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/dism/DISM.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@v-karbovnichy The title of the page is now`DISM`. 

Thank you for the catch.
