### ISSUE TITLE
The description of ServicePrincipalNames is not correct

### ISSUE THREAD

**Issue by bagdxk** [MicrosoftDocs/windows-powershell-docs#246]
As title: 

-ServicePrincipalNames 
Use the DateTime syntax when you specify this parameter. Time is assumed to be local time unless otherwise specified. When a time value is not specified, the time is assumed to 12:00:00 AM local time. When a date is not specified, the date is assumed to be the current date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22bb7107-c501-6b6f-1f6a-dcb66c65b703
* Version Independent ID: b73926ab-2463-30a9-ccc9-7038fbcd98f3
* Content: [Set-ADServiceAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-adserviceaccount?view=win10-ps#optional-parameters)
* Content Source: [docset/windows/addsadministration/set-adserviceaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-adserviceaccount.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by rajeshanayaka** [comment]
**ServiceNamePrincipleNames to set access on File Share (CIFS) or all by HOST is not working :**


Set-ADServiceAccount -Identity gMSAAccount -ServicePrincipalNames @{add="HOST/computername"}
Set-ADServiceAccount : The operation failed because SPN value provided for addition/modification is not unique forest-wide
At line:1 char:1
+ Set-ADServiceAccount -Identity gMSAAccount -ServicePrincipalNames @ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (TFSBuildgMSA:ADServiceAccount) [Set-ADServiceAccount], ADException
    + FullyQualifiedErrorId : ActiveDirectoryServer:8647,Microsoft.ActiveDirectory.Management.Commands.SetADServiceAccount

**Comment by j0rt3g4** [comment]
I've worked on this issue and the additional information has been added into PR #935

**Comment by j0rt3g4** [comment]
I've created a new PR solve this issue #954

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Kindly perform copy editing on this PR. Thanks.

**Comment by dariomws306** [comment]
Hi @j0rt3g4,

**Comment by j0rt3g4** [comment]
HI, @dariomws306 What's up?

**Comment by j0rt3g4** [comment]
Write that on Teams ty.

**Comment by j0rt3g4** [comment]
Updated PR #954

**Comment by j0rt3g4** [comment]
#1006  Solves the issue.

**Comment by e0i** [comment]
@bagdxk 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
