### ISSUE TITLE
General content missing. Too much "add here"-s

### ISSUE THREAD

**Issue by JoergWu** [MicrosoftDocs/windows-powershell-docs#247]
Please review. This look like to be a corpus with missing lots of stuff.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a70dc9-0ed5-c924-7187-679f3747fea7
* Version Independent ID: 76ba113d-f32d-058d-f7a2-7c8daadba900
* Content: [Install-ProvisioningPackage (provisioning)](https://docs.microsoft.com/en-us/powershell/module/provisioning/install-provisioningpackage?view=win10-ps)
* Content Source: [docset/windows/provisioning/install-provisioningpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/provisioning/install-provisioningpackage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith kindly merge this PR if you find it suitable

**Comment by ccarls-cloudfit** [comment]
Any kind of documentation other than boiler plate template would be preferable. Is there any other documentation that can be cross referenced in the meantime while this content backlog item is worked?

**Comment by e0i** [comment]
@officedocsbot unassign @e0i

**Comment by PrinceMarkieD** [comment]
There is also Add-ProvisioningPackage. I do not know which one should be used. Add-provisioningPacakge works, but has a very strange lagginess at the command line. I have never seen a cmdlet behave that way. Tab completion takes several seconds. Install-ProvisioningPackage does not behave that way. I wonder if it means one the 2 commands should not be used.

**Comment by get-itips** [comment]
Hello @AndreaBarr can you help us locating the right people to ask here ? Thanks

**Comment by get-itips** [comment]
Hello @brianlic-msft Can you help us here? Thanks. cc @kenwith

**Comment by get-itips** [comment]
Document has been updated since the issue was opened.

@e0i please close
