### ISSUE TITLE
Please document what -ForceDrain does

### ISSUE THREAD

**Issue by mattpwhite** [MicrosoftDocs/windows-powershell-docs#248]
There is no description for what this switch actually does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047bdd2d-2bae-9dd5-bade-559e4f6eca2e
* Version Independent ID: a1926ffe-dc97-9dfa-b1d6-ffd8dca431d2
* Content: [Suspend-ClusterNode (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/suspend-clusternode?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/suspend-clusternode.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/suspend-clusternode.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@mattpwhite 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
