### ISSUE TITLE
non referenced parameters / unclear documentation

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/windows-powershell-docs#2482]
There is no reference on this site to the following parameter:
SignaturesUpdatesChannel

There is no mention on this site what the following means:
SignatureScheduleDay                         : 8
8: Never
The statement is as follows:
**The default value is 8, never.** If you specify a value of 8 or do not specify a value, Windows Defender checks for definition updates by using a **default frequency**.

Great what is the default frequency? There is no mention to this.

Per this site mysettings are as follows (is it safe to say I am never being updated because I have no clue what a default frequency means?):
SignatureAuGracePeriod                       : 0
SignatureBlobFileSharesSources               : 
SignatureBlobUpdateInterval                  : 60
SignatureDefinitionUpdateFileSharesSources   : 
SignatureDisableUpdateOnStartupWithoutEngine : False
SignatureFallbackOrder                       : MicrosoftUpdateServer|MMPC
SignatureFirstAuGracePeriod                  : 120
SignatureScheduleDay                         : 8
SignatureScheduleTime                        : 01:45:00
SignaturesUpdatesChannel                     : 0
SignatureUpdateCatchupInterval               : 1
SignatureUpdateInterval                      : 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43741f9-62d8-4bcb-8f1e-2f9bcf0b8e92
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (Defender)](https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/defender/Set-MpPreference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@SquirrelAssassin , I have used the below set-mppreference settings,i added in text file.

[set-mppreference.zip](https://github.com/MicrosoftDocs/windows-powershell-docs/files/6592157/set-mppreference.zip)


Also, windows 10 os have prebuilt default values for Microsoft defender under below location of registry key

**HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\Defender**
**HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\WindowsDefenderSecurityCenter**

**Comment by e0i** [comment]
Closing the issue based on the response provided by the community above.

Thank you for the discussion.
