### ISSUE TITLE
XML Output - Comment slightly incorrect

### ISSUE THREAD

**Issue by ivassallo19** [MicrosoftDocs/windows-powershell-docs#2484]
[Windows 10 x64 21H1 19043.985]
When generating an XML file from New-CIPolicy, just above the <SigningScenarios> line, there is a commend added:

This comment should appear above the line <SigningScenario Value="131" ID="ID_SIGNINGSCENARIO_DRIVERS_1" FriendlyName="Auto generated policy on 06-03-2021"> as this is the Driver Signing Scenario line.
And <SigningScenario Value="12" ID="ID_SIGNINGSCENARIO_WINDOWS" FriendlyName="Auto generated policy on 06-03-2021"> is the Windows / User Signing Scenario line, where an additional comment should appear:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 908ec0c8-5ab3-721a-dace-45d2c60ed3cd
* Version Independent ID: 88ae42d6-34d5-821b-bdce-5b8f61968a70
* Content: [New-CIPolicy (ConfigCI)](https://docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/configci/New-CIPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/configci/New-CIPolicy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by e0i** [comment]
@ivassallo19 Your feedback is being routed to the module owners. Thanks.
