### ISSUE TITLE
What is Measure Unit for value of AllocationUnitSize? Bytes? kB?

### ISSUE THREAD

**Issue by dakrdakr** [MicrosoftDocs/windows-powershell-docs#249]
Or can I use value like "64kB"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d639de33-d9fe-83a6-bb89-d305b93dc5f3
* Version Independent ID: dc541d59-bbc3-cc3d-9b98-79d06870564f
* Content: [Format-Volume (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/storage/Format-Volume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/storage/Format-Volume.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by banditkd** [comment]
as this is a Unit32 it appears you need to enter 64K as 65536 etc.

**Comment by e0i** [comment]
Hello @dakrdakr - ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure._
