### ISSUE TITLE
Set-CIPolicySetting is missing

### ISSUE THREAD

**Issue by TJ2215** [MicrosoftDocs/windows-powershell-docs#2490]
Set-CIPolicySetting is missing from the list of commands. It is used to add class ids to the policy xml file. 
Example available at this link : https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy#how-to-configure-settings-for-the-clsids. P.S. I am not able to create a pull request that is why I have created a new issue. If anyone is able to do it. please go ahead.

**Comment by TJ2215** [comment]
Is there any update on this? @e0i

**Comment by e0i** [comment]
@TJ2215 This is under investigation. Thank you for the feedback.

**Comment by MaratMussabekov** [comment]
Hello @TJ2215,
yes you are correct, Set-CIPolicySetting article is missing in the list of commands of ConfigCI module and the article is not presented on GitHub.
I only see the description of cmdlet on the powershell help:
Word | Binary | String} -Value <string>  [<CommonParameters>]

    Set-CIPolicySetting [-FilePath] <string> -Provider <string> -Key <string> -ValueName <string> -Delete
    [<CommonParameters>]


PARAMETERS
    -Delete

    -FilePath <string>

    -Key <string>

    -Provider <string>

    -Value <string>

    -ValueName <string>

    -ValueType <string>

    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216).


ALIASES
    None
