### ISSUE TITLE
False error message translation into German

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-powershell-docs#2491]
Unfortunately, there is no feedback channel for the `IISAdministration` powershell module (though such channel is actually advertised at the bottom of the documentation page).

Please pardon me for providing my error report here. Perhaps some MSFT staff member may forward this error:

Using the `New-IISSite` CmdLet with a non-existing physical path for the `-PhysicalPath` parameter yields the following error message in German:

```
Der Parameter "PhysicalPath" sollte nicht auf einen vorhandenen Pfad zeigen.
```
... which translates to English as:
```
The "PhysicalPath" parameter should not point to an existing path.
```

The **"not"** is wrong in this error message. It should correctly read:

```
Der Parameter "PhysicalPath" muss auf einen vorhandenen Pfad zeigen.
```
... which would translate to English as:
```
The "PhysicalPath" parameter has to point to an existing path.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a81a6051-9a39-4513-2b64-a838bcb0457f
* Version Independent ID: e17f9c7a-8817-b6e4-a693-ec56b530448c
* Content: [New-IISSite (IISAdministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/new-iissite?view=windowsserver2019-ps#parameters)
* Content Source: [docset/winserver2019-ps/iisadministration/New-IISSite.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/iisadministration/New-IISSite.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@SetTrend Thank you for your feedback. Sorry about the delay. The feedback needs to be routed to our DEV.product team and you can post your feedback directly on our main feedback portal - https://feedbackportal.microsoft.com/ so one of our Dv/product team members will check and provide you an update.

Hope this helps1

Thanks
Sri

**Comment by SetTrend** [comment]
Thanks, Sri, for replying.

I don't seem to find a matching forum in the feedback portal. Which of the forums would you suggest:

- [ ] Access
- [ ] Bookings
- [ ] Communication Compliance
- [ ] Data Loss Prevention
- [ ] Excel
- [ ] Feedback (web portal)
- [ ] Immersive Reader
- [ ] Insider Risk Management
- [ ] Launcher
- [ ] Microsoft 365 Lighthouse
- [ ] Microsoft Edge
- [ ] Microsoft Endpoint Configuration Manager
- [ ] Microsoft Family Safety
- [ ] Microsoft Forms
- [ ] Microsoft Information Protection
- [ ] Microsoft Intune
- [ ] Microsoft Stream
- [ ] Microsoft Teams
- [ ] Microsoft To Do
- [ ] Microsoft Viva Connections
- [ ] Microsoft Viva Insights
- [ ] Microsoft Viva Learning
- [ ] Microsoft Viva Topics
- [ ] OneDrive
- [ ] OneNote
- [ ] Outlook
- [ ] Outlook.com
- [ ] Planner
- [ ] PowerPoint
- [ ] Project
- [ ] School Data Sync
- [ ] SharePoint
- [ ] SharePoint Syntex
- [ ] Skype
- [ ] Sway
- [ ] Visio
- [ ] Whiteboard
- [ ] Windows 365
- [ ] Word
- [ ] Yammer

**Comment by msbemba** [comment]
@SetTrend Sorry about the delay. I might have missed this response.

The feedback can also be provided via the feedback hub app.

- https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332

Hope this helps!

Thanks
Sri

**Comment by SetTrend** [comment]
Has the translation been corrected?

**Comment by msbemba** [comment]
This feedback is not on the document but on the product page(admin portal). You will need to provide the feedback on the main feedback portal or the feedback hub. There is no action pending from our end.

Hope this helps!
