### ISSUE TITLE
GMSA - ManagedPasswordIntervalInDays - Password reset query

### ISSUE THREAD

**Issue by Afsars12** [MicrosoftDocs/windows-powershell-docs#2499]
Hi Team

I have created a gMSA account by giving 3 days as value to **ManagedPasswordIntervalInDays** parameter.

When I check the properties of my gMSA account I see the PasswordLastSet value as same as created date of account, Ideally, it should the value of 3 days back, as I have set the password interval for 3 days.

Also, advise where exactly I can check whether my password is getting reset automatically or not.

Regards
Afsar 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3276423c-b187-57ed-91a2-37133b6e12f5
* Version Independent ID: 3338b8fe-1364-ecd7-eb5c-5ab25d054df7
* Content: [New-ADServiceAccount (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012r2-ps&redirectedfrom=MSDN)
* Content Source: [docset/winserver2012r2-ps/activedirectory/New-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/activedirectory/New-ADServiceAccount.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Afsars12** [comment]
Hi Team,

Kindly help with the above issue.

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
