### ISSUE TITLE
Example 3 throws error "Unexpected token 'in' in expression or statement."

### ISSUE THREAD

**Issue by JerryCube** [MicrosoftDocs/windows-powershell-docs#2500]
So I'm a complete newbie when it comes to powershell, but I'm trying to get a script put together that will automate changing settings on printers in my organization. I tried to copy/paste this code into powershell 5 to test it and  this error keeps popping up. I'm sure this is a simple fix, but I can't find it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d0dcf31-d057-f1d5-b261-d4784af82dd9
* Version Independent ID: 37c3187a-1411-22de-4e2a-290245a3d65d
* Content: [Set-PrintConfiguration (PrintManagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/set-printconfiguration?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/printmanagement/Set-PrintConfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/printmanagement/Set-PrintConfiguration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by MaratMussabekov** [comment]
Hello @JerryCube ,
yes, it has wrong syntax. It should have ";" instead of "*"
Thank you
