### ISSUE TITLE
missing pre-requistes

### ISSUE THREAD

**Issue by NeoGit111** [MicrosoftDocs/windows-powershell-docs#2504]
[Enter feedback here]
You need to mention the pre-requites of having Hyper-V installed on the computer

I got an error...

"Mount-VHD : Hyper-V has not been installed on computer <local hostname>"

Hope you can add this to the page....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398aa37a-8b2f-c369-6919-14470ee28a27
* Version Independent ID: 7c54bbd8-d0d2-685b-ade9-40d51d07a300
* Content: [Mount-VHD (Hyper-V)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/mount-vhd?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/hyper-v/Mount-VHD.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/hyper-v/Mount-VHD.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@NeoGit111 

Thank you for your feedback.

Having Hyper-V installed on your machine might not be required as you may want to use it only for remote management of another server with Hyper-V Role. The module is usable on its own for remote management but for local management you need Hyper-Role installed.

Let me know if you have any questions.
