### ISSUE TITLE
Missing Explanations

### ISSUE THREAD

**Issue by rlsheldon** [MicrosoftDocs/windows-powershell-docs#2507]
All general documentation fields are missing explanations or clarification.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05439318-ee56-3028-5dfc-7c3a01b587da
* Version Independent ID: 659bccf4-40ab-4767-5f37-a00efd724e75
* Content: [Uninstall-ProvisioningPackage (Provisioning)](https://docs.microsoft.com/en-us/powershell/module/provisioning/uninstall-provisioningpackage?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/provisioning/Uninstall-ProvisioningPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/provisioning/Uninstall-ProvisioningPackage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by e0i** [comment]
Under investigation. Thank you for the feedback.

**Comment by msbemba** [comment]
@rlsheldon Thank you for your feedback. The Parameters have now been provided with descriptions of what it does for the cmdlet.


Thanks
Sri

**Comment by msbemba** [comment]
@e0i This can be closed.
