### ISSUE TITLE
Invalid parameter in Example 2

### ISSUE THREAD

**Issue by Foamcow** [MicrosoftDocs/windows-powershell-docs#2509]
Example 2 includes the parameter "mail".  Per the parameter list, the appropriate name is "EmailAddress".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb61649-0f07-ff16-3fbe-4029b9119c7e
* Version Independent ID: 5f3c184f-42bd-176e-5764-5411c3227c6e
* Content: [New-ADUser (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-aduser?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/activedirectory/New-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/activedirectory/New-ADUser.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by kilasuit** [comment]
Sorry the example is actually correct as `mail` is the actual attribute you pass when using the `OtherAttributes` parameter which expects a hashtable of attributes, which is what is shown.

the `EmailAddress` parameter, like many other parameters for the AD Attributes, just gives you some nice wrapping around the LDAP attributes that AD actually uses under the hood
