### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dgauthier99** [MicrosoftDocs/windows-powershell-docs#251]
In Example 3, your cmdlet is Disable-NetAdapterManagement instead of Disable-NetAdapterPowerManagement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb5489b-2d89-4e9d-bc6f-f4cb0bd7b5f3
* Version Independent ID: 71222004-a56b-fce7-0afc-f6f9ded7e150
* Content: [Disable-NetAdapterPowerManagement (netadapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/disable-netadapterpowermanagement?view=win10-ps#feedback)
* Content Source: [docset/windows/netadapter/disable-netadapterpowermanagement.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netadapter/disable-netadapterpowermanagement.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Styxxy** [comment]
I submitted PR #284 to fix this.
