### ISSUE TITLE
Write-VolumeCache -DriveLetter (can include more than one, listed together with no spaces)

### ISSUE THREAD

**Issue by JoesOtherCat** [MicrosoftDocs/windows-powershell-docs#2510]
Incredibly minor but not clear: you can cite more than one drive letter by listing them w/o spaces Etc.
I.E.
PS> Write-VolumeCache -DriveLetter cf

Alas, it is not clear to me if including a drive letter that does not exist, if the ones that do are have their cache committed to storage. Arg. In my cursory test, only a known non-existent drive letter was listed as erroneous in the command's results.

FWIW, the command like most others is not case-sensitive - just easier to read ;) 

/Longtime techie, ~newbie to PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d7bba53-24f4-e855-36e4-8e50df9aef01
* Version Independent ID: f781e976-f93a-759e-5fa9-34c3804152e0
* Content: [Write-VolumeCache (Storage)](https://docs.microsoft.com/en-us/powershell/module/storage/write-volumecache?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/storage/Write-VolumeCache.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/storage/Write-VolumeCache.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@JoesOtherCat 

Thanks your feedback.

According to the article here is the DriveLetter parameter description:

### -DriveLetter
Specifies an array of letters that identify one or more drives or volumes in the system.
The cmdlet writes the volume cache for the drives or volumes you specify.

```yaml
Type: Char[]
```

It says it can accept more than one drive and the type is `Char[]` so you example is completely valid and expect. Separating the letter via a comma also works and is probably more readable :)

Would you suggest that we include such an example in the article?
