### ISSUE TITLE
Example command incorrect

### ISSUE THREAD

**Issue by philbyj5** [MicrosoftDocs/windows-powershell-docs#2511]
Example text has the following line:

Get-WinLanguageBarOptions

There should be no 's' on the end of the command.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d25509-d895-a936-8472-5396205269e2
* Version Independent ID: 07c2f956-7f02-ea5d-57ec-9a5cd0670431
* Content: [Get-WinLanguageBarOption (International)](https://docs.microsoft.com/en-us/powershell/module/international/get-winlanguagebaroption?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/international/Get-WinLanguageBarOption.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/international/Get-WinLanguageBarOption.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
here is the proof
![powershell](https://user-images.githubusercontent.com/3296790/124356946-a46ec680-dc36-11eb-99e9-06025e50bc02.JPG)

**Comment by RAJU2529** [comment]
@e0i Please assign to verify and merge this PR #2526
