### ISSUE TITLE
Unable to find type RunLevelEnum

### ISSUE THREAD

**Issue by dakrdakr** [MicrosoftDocs/windows-powershell-docs#2514]
What is the full name of the type "RunLevelEnum"? Because I every time got following error:
```
Unable to find type [RunLevelEnum].
At line:1 char:1
+ [RunLevelEnum]::Highest
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (RunLevelEnum:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

```
You can reproduce it by type the following text in prompt in PS-ISE: _[RunLevelEnum]::Highest_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eb139-5445-3cd4-18db-6d177b7846e3
* Version Independent ID: 57bc659a-9971-ae7a-4df4-10c9c46d9ee3
* Content: [New-ScheduledTaskPrincipal (ScheduledTasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtaskprincipal?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/scheduledtasks/New-ScheduledTaskPrincipal.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/scheduledtasks/New-ScheduledTaskPrincipal.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@dakrdakr Hi David,

Thanks for your feedback. Here is the output of the command that give the RunLevel property type:
```powershell
PS C:\> (Get-Command New-ScheduledTaskPrincipal).Parameters.RunLevel

Name            : RunLevel
ParameterType   : Microsoft.PowerShell.Cmdletization.GeneratedTypes.ScheduledTask.RunLevelEnum
ParameterSets   : {[User, System.Management.Automation.ParameterSetMetadata], [Group, System.Management.Automation.ParameterSetMetadata]}
IsDynamic       : False
Aliases         : {}
Attributes      : {System.Management.Automation.ValidateNotNullOrEmptyAttribute, System.Management.Automation.ValidateNotNullAttribute, , …}
SwitchParameter : False
```

Let me know if that helps.
