### ISSUE TITLE
Comma instead of semicolon in hash table definition

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [MicrosoftDocs/windows-powershell-docs#252]
This appears to be erroneous:

`-Replace @{Attribute1LDAPDisplayName=value[], Attribute2LDAPDisplayName=value[]}`

I think this should read (with a semicolon in the middle, before Attribute2…):

`-Replace @{Attribute1LDAPDisplayName=value[]; Attribute2LDAPDisplayName=value[]}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30217138-eb8c-ab9a-4e11-991c6164cbd9
* Version Independent ID: 88ff510e-6402-5163-404f-e9154f59b381
* Content: [Set-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/set-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-aduser.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Malind19** [comment]
@kenwith Created PR 
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/921

**Comment by e0i** [comment]
@AndreaBarr Please have the PR #921 for this issue reviewed. Thanks.

**Comment by e0i** [comment]
@Daniel-Beardsmore Upon your feedback, We have updated the content with relevant changes. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
