### ISSUE TITLE
ADInvalidOperationException not explained or documented

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [MicrosoftDocs/windows-powershell-docs#253]
This is senselessly illegal:

```
> Set-ADUser foo -Description ""
Set-ADUser : replace
At line:1 char:11
+ Set-ADUser <<<<  foo -Description ""
    + CategoryInfo          : InvalidOperation: (foo:ADUser) [Set-ADUser], ADInvalidOperationException
    + FullyQualifiedErrorId : replace,Microsoft.ActiveDirectory.Management.Commands.SetADUser
```

It is—for no reason whatsoever—illegal to set any field to an empty string! It will crash if you try.

This is much worse when you write this:

`> Set-ADUser foo @somehashtable`

The error that comes back is exactly the same. There is no mention made in the documentation of this pointless restriction (that the cmdlet could and should take care of if the restriction is inside AD and not PowerShell), no mention made of the exception type and what uses of Set-ADUser might cause it, no clue in the exception name as to what is invalid about what, and no suggestion in the error message about what might be wrong.

Moreover, the word "replace" is used here even though -Replace was not invoked. So the error seems not to even bear any resemblance to the command that was invoked.

In fact, the difference between Add, Clear and Replace isn't even documented either. How do Add and Replace even differ? Are you suggesting that programs need to examine every property to see if they should be adding or replacing? Certainly it's not normal for an empty string to require Clear. If AD has some sort of distinction between the empty string and NULL, it is AD's responsibility to autoconvert as required, and the cmdlet's responsibility if AD is defective by design. From the perspective of the Windows UI, a blank Description is the empty string and it seems perfectly reasonable to ask it to be set thus. Any vagaries of AD's design flaws should not be exposed by the cmdlet in this manner, and the documentation should most certainly explain this all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30217138-eb8c-ab9a-4e11-991c6164cbd9
* Version Independent ID: 88ff510e-6402-5163-404f-e9154f59b381
* Content: [Set-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/set-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-aduser.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by jeffreymcclain** [comment]
Seconded, I also came across this exact issue in one of my scripts. I worked around it by adding an if statement to ignore empty strings, and to call the Clear command if the intent is to actually set the field to null.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Daniel-Beardsmore 
**Thanks for your feedback, we really appreciate it.**

Docs article reflect or try to reflect the functionality _provided by the cmdlet_. As you may know, this issue system only covers issues with documentation, if you have new ideas to improve the behaviour of them, I kindly suggest Powershell UserVoice. https://windowsserver.uservoice.com/forums/301869-powershell

Said that, about the procedure to set a field to en empty string, that is how the cmdlet was designed and the article tries to reflect it, for example if you need to clear the telephoneNumber attribute (or set an empty string that in this case is the same) you should use the -Clear parameter.

About Add, Clear and Replace difference, document states:

> Add: Specifies values to add to an object property.
> Replace: Specifies values for an object property that will replace the current values.
> Clear: Specifies an array of object properties that are cleared in the directory.

Hope this information helps you, thanks for your time to leave feedback!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Daniel-Beardsmore 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by Daniel-Beardsmore** [comment]
The page for Set-ADUser is still inadequate, as it does not explain any of the pitfalls with this cmdlet. If the error handling was useful, it would be less of a problem, but the meaningless error handling means that the documentation is required to note all the things you might legitimately expect to work, but that don’t. This is part of the fundamental requirements behind documentation!
