### ISSUE TITLE
Add Example with switch UseDesktopApplicationID

### ISSUE THREAD

**Issue by Pwnisher1337** [MicrosoftDocs/windows-powershell-docs#2534]
Could you add another Example Code with the Switch "UseDesktopApplicationID" in there and explain that it should be use with Windows Version1809 or higher.

I think it would help future Admins to Export the Start Layout correct and import it later on.

`Export-StartLayout -UseDesktopApplicationID -Path layout.xml`

Thanks & Kind Regards
PWN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930b8cb5-4b7f-4230-eec5-e972250d0428
* Version Independent ID: c1208227-6428-bee1-e2f3-0cda1f35dc1c
* Content: [Export-StartLayout (StartLayout)](https://docs.microsoft.com/en-us/powershell/module/startlayout/export-startlayout?view=windowsserver2019-ps&viewFallbackFrom=win10-ps)
* Content Source: [docset/winserver2019-ps/startlayout/Export-StartLayout.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/startlayout/Export-StartLayout.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by MaratMussabekov** [comment]
Hello @Pwnisher1337 ,
please have a look at https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2631
Thank you
