### ISSUE TITLE
QoS ThrottleRate "MBytes/sec" -> "Mbits/sec" documentation errors

### ISSUE THREAD

**Issue by stampycode** [MicrosoftDocs/windows-powershell-docs#2535]
Examples of `ThrottleRateActionBitsPerSecond` are listed in the output item "ThrottleRate" as 'Bytes/sec' whereas in fact they are in Bits/sec.

Please also correct '1MB' to be '1Mb' in all locations to correctly indicate 'bits' instead of 'Bytes' - the application itself is case insensitive so the outcome is the same. '1MB' input will be the same as '1Mb' input, and is output as '1.049Mbits/sec'.

Documented example:
```
PS C:\> New-NetQosPolicy -Name "FTP" -AppPathNameMatchCondition "ftp.exe" -ThrottleRateActionBitsPerSecond 1MB -PolicyStore ActiveStore
Name           : FTP 
Owner          : PowerShell / WMI 
NetworkProfile : All 
Precedence     : 127 
AppPathName    : ftp.exe 
ThrottleRate   : 1 MBytes/sec
```

Actual output:
```
Name           : ftp
Owner          : PowerShell / WMI
NetworkProfile : All
Precedence     : 127
AppPathName    : ftp.exe
JobObject      :
ThrottleRate   : 1.049 MBits/sec
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace9d8fc-967d-e9ca-44ae-dc26f2fb6703
* Version Independent ID: fd6ec687-d40a-8534-0d33-a4d5cd498d5a
* Content: [New-NetQosPolicy (NetQoS)](https://docs.microsoft.com/en-us/powershell/module/netqos/new-netqospolicy?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/netqos/New-NetQosPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/netqos/New-NetQosPolicy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@stampycode , Thanks for pointing out. I am fixing these errors.
