### ISSUE TITLE
New-ScheduledTaskTrigger Delay

### ISSUE THREAD

**Issue by devhl-labs** [MicrosoftDocs/windows-powershell-docs#2540]
The RandomDelay property is not mapped to any property in the class. Looking at the GUI I believe this should map to the "Delay task for" property but that is left unchecked and at 15 minutes, not the one minute I provided.

```ps1
New-ScheduledTaskTrigger -AtStartup -RandomDelay (New-TimeSpan -Minutes 1)

# result:
Enabled            : True
EndBoundary        :
ExecutionTimeLimit :
Id                 :
Repetition         :
StartBoundary      :
Delay              :
PSComputerName     :
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ead486f5-1dde-ccae-94d0-fe0e804bd0dd
* Version Independent ID: 84be6419-e750-a16e-70fc-85a3fb0d0569
* Content: [New-ScheduledTaskTrigger (ScheduledTasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/scheduledtasks/New-ScheduledTaskTrigger.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/scheduledtasks/New-ScheduledTaskTrigger.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
