### ISSUE TITLE
-OptionalPackagePath parameter is not documented.

### ISSUE THREAD

**Issue by 09mb** [MicrosoftDocs/windows-powershell-docs#2542]
Hi!

We recently had some challenges with installing MSIX modification packages using the command line. During our search we found a solution using -OptionalPackagePath

e.g.

`Add-AppProvisionedPackage -Online -OptionalPackagePath \\share\modificationpackage.msix -PackagePath \\share\mainpackage.msix -SkipLicense`

However, we found that the -OptionalPackagePath is not documented while I believe it is useful to have this parameter documented

regards
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84aaef21-a63f-d502-80ff-7732f5456450
* Version Independent ID: f077a336-dd7b-bcc5-a95c-451b3c9dd0d2
* Content: [Add-AppxProvisionedPackage (DISM)](https://docs.microsoft.com/en-us/powershell/module/dism/add-appxprovisionedpackage?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/dism/Add-AppxProvisionedPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/dism/Add-AppxProvisionedPackage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@JasonGerend  Sir, In this article  **Offline** title and **Online**  title, are not visible to the public.  So this article, format must be adjusted soon.

**Comment by msbemba** [comment]
@09mb Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2932

Thanks
Sri
