### ISSUE TITLE
dead link to module `PKIClient`

### ISSUE THREAD

**Issue by fbehrens** [MicrosoftDocs/windows-powershell-docs#2545]
i am trying to get the command [new-selfsignedcertificate](https://docs.microsoft.com/en-us/powershell/module/pki/new-selfsignedcertificate?view=windowsserver2019-ps) installed on my machine.

It would be helpful to include more information about module [pki](https://docs.microsoft.com/en-us/powershell/module/pki/?view=windowsserver2019-ps)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37905aab-756d-07e3-b9fb-9d9b3ffe64bf
* Version Independent ID: 6e9677e3-763f-9689-3219-69b7c8b7685d
* Content: [Windows 10 and Windows Server 2019](https://docs.microsoft.com/en-us/powershell/windows/get-started?view=windowsserver2019-ps)
* Content Source: [docset/docs-conceptual/winserver2019-ps/get-started.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/docs-conceptual/winserver2019-ps/get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@fbehrens Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2931

Thanks
Sri
