### ISSUE TITLE
PasswordExpiring is a nonexistent parameter

### ISSUE THREAD

**Issue by paulrichwine-hcps** [MicrosoftDocs/windows-powershell-docs#2547]
The description of the `-DateTime` parameter in the help doc is:
`Specifies a distinct time value for Search-ADAccount parameters such as AccountExpiring, AccountInactive, and PasswordExpiring.`

however `PasswordExpiring` is not a valid parameter for the Search-ADAccount cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55871785-5f01-4d81-b84e-fd0140a48ab0
* Version Independent ID: beea1c46-1acf-8856-48c1-36037b737b2f
* Content: [Search-ADAccount (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/search-adaccount?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/activedirectory/Search-ADAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/activedirectory/Search-ADAccount.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@paulrichwine-hcps Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2930

Thanks
Sri
