### ISSUE TITLE
Address a False return and how to fix

### ISSUE THREAD

**Issue by JamieL22** [MicrosoftDocs/windows-powershell-docs#2551]
WARNING: Test failed for Managed Service Account gmsaIISTAtlas. If standalone Managed Service Account, the account is linked to another computer object in the Active Directory. If group Managed Service Account, either this computer does not have permission to use the group MSA or this computer does not support all the Kerberos encryption types required for the gMSA. See the MSA operational log for more information.
Would be nice if this page could address this error as it looks to be one that is a default and has a probable work-around or fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc8eedf-e1dc-0cf7-5786-3ede3b12d81e
* Version Independent ID: aa5da4ed-b853-b87c-74f9-5da4f10d16a8
* Content: [Test-ADServiceAccount (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/test-adserviceaccount?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Test-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Test-ADServiceAccount.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by e0i** [comment]
Hello,

The warning in question has already been featured in Example 2, and the warning suggest the possible causes of the issue. The article in its current condition should be enough since the documentation is not for featuring bug fixes.

Thanks.
