### ISSUE TITLE
CAA records aren't supported

### ISSUE THREAD

**Issue by stephenweaver** [MicrosoftDocs/windows-powershell-docs#2562]
Is there a reason that CAA records aren't support with this cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d20ab8d9-fa00-d91d-5816-e6ebe2aff65d
* Version Independent ID: 8f0d8fc1-69c5-a2f1-e8c8-f61b248b6657
* Content: [Resolve-DnsName (DnsClient)](https://docs.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/dnsclient/Resolve-DnsName.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/dnsclient/Resolve-DnsName.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by stephenweaver** [comment]
@e0i Can you tag someone who would be able to help answer this?

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
