### ISSUE TITLE
What are "common parameters"

### ISSUE THREAD

**Issue by kennyk65** [MicrosoftDocs/windows-powershell-docs#2565]
Please explain or link to an explanation of 'common parameters'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 688a8987-58d5-e545-8b0d-1ab1973cc246
* Version Independent ID: 301f3ec5-c801-6546-bd33-6063d92ac37e
* Content: [Add-KdsRootKey (KDS)](https://docs.microsoft.com/en-us/powershell/module/kds/add-kdsrootkey?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/kds/Add-KdsRootKey.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/kds/Add-KdsRootKey.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@kennyk65 Thank you for your feedback.

Most articles actually contain info about the common parameters. I will check why it is not visualized. In the meantime here is the link [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216)
