### ISSUE TITLE
Clear-MsmqQueue expects different type than Get-MsmqQueue returns

### ISSUE THREAD

**Issue by nbarnwell** [MicrosoftDocs/windows-powershell-docs#2567]
This documentation is false because with Windows 10 version 2004 and MSMQ module 1.0, `Get-MsmqQueue` returns `Deserialized.Microsoft.Msmq.PowerShell.Commands.MessageQueue`, yet `Clear-MsmqQueue` expects `Microsoft.Msmq.PowerShell.Commands.MessageQueue`.

Either the MSMQ module is broken or this documentation is, I can't be sure which.

Cheers,

Neil Barnwell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 005be01e-1235-e355-a8fd-178e94b34246
* Version Independent ID: ca97ea3a-353e-2beb-2cb1-0626cf072ef7
* Content: [Clear-MSMQQueue (MSMQ)](https://docs.microsoft.com/en-us/powershell/module/msmq/clear-msmqqueue?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/msmq/Clear-MSMQQueue.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/msmq/Clear-MSMQQueue.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@nbarnwell > could you please share screenshots of entered commnads

**Comment by nbarnwell** [comment]
I literally typed-in the code from example 1, with the filter argument modified.

`Get-MsmqQueue -Name "Order*" | Clear-MsmqQueue`

**Comment by RAJU2529** [comment]
@nbarnwell . newly entered command is worked or not.

 I was able to made working command on windows 11 insider preview.
