### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/windows-powershell-docs#257]
On pages:
* https://docs.microsoft.com/en-us/powershell/module/wdac/Add-OdbcDsn?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/disable-odbcperfcounter?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/disable-wdacbidtrace?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/enable-odbcperfcounter?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/enable-wdacbidtrace?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/get-odbcdriver?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/get-odbcdsn?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/get-odbcperfcounter?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/get-wdacbidtrace?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/remove-odbcdsn?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/set-odbcdriver?view=winserver2012r2-ps
* https://docs.microsoft.com/en-us/powershell/module/wdac/set-odbcdsn?view=winserver2012r2-ps

New-CimSession has forward link http://go.microsoft.com/fwlink/p/?LinkId=227967, which goes to https://docs.microsoft.com/en-us/powershell/module/cim/new-cimsession but this is a dead link (should be https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/new-cimsession )

Get-CimSession has forward link http://go.microsoft.com/fwlink/p/?LinkId=227966, which goes to https://docs.microsoft.com/en-us/powershell/module/cim/get-cimsession but this is a dead link (should be https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/get-cimsession )

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by VLG17** [comment]
the link redirects have been updated and are going to the correct article.

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and sharing this explanation. @Styxxy 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
