### ISSUE TITLE
couldn't update help

### ISSUE THREAD

**Issue by joelviven22** [MicrosoftDocs/windows-powershell-docs#2572]
update-help : Failed to update Help for the module(s) 'ConfigDefender' with UI culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI culture
en-US. Make sure the HelpInfoUri property in the module manifest is valid or check your network connection and then try the command again.
At line:1 char:1
+ update-help -module ConfigDefender -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Comment by RAJU2529** [comment]
@joelviven22 @e0i  same issue is conformed by also. manifest XML is  not located for en-us culture

**Comment by KaeLL** [comment]
is this issue related to the following error?
```
> Update-Help -UICulture en-US
Update-Help: Failed to update Help for the module(s) 'Dism, Get-NetView, Kds, NetQos, PcsvDevice, PKI, PSReadline, Whea, WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

**Comment by e0i** [comment]
This is a know issue that is under investigation. Thanks for the feedback.
