### ISSUE TITLE
Example 2 is not complete

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windows-powershell-docs#2573]
Example 2: Add a new SSL site binding

The example only creates half the site binding. It does not assign a certificate to it.

That is a job just half done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d0b5b9-a348-c35e-d7d2-5c46cbda85b3
* Version Independent ID: fd8021e1-e815-0ddc-5d7a-61a02d06d6e9
* Content: [New-WebBinding (WebAdministration)](https://docs.microsoft.com/en-us/powershell/module/webadministration/new-webbinding?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/webadministration/New-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/webadministration/New-WebBinding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@Tarjei-stavanger Thank you for your feedback.

I guess the example is like that because adding the certificate is not done with this cmdlet.

I will add something to the example but in theory creating a binding and adding a certificate are two different operations.
