### ISSUE TITLE
Set-PhysicalDisk make changes survive reboot?

### ISSUE THREAD

**Issue by Joachim-Otahal** [MicrosoftDocs/windows-powershell-docs#2578]
I can use Set-PhysicalDisk to change the Mediatype, FriendlyName and so on.
When it is not in a pool: Lost after reboot.
How can we make it stick to survive a reboot without needing to have them in a pool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ecd4e66-ea2c-59f1-2534-6d17cdd05423
* Version Independent ID: f8ab4fd7-7d26-ed43-653f-4fa144b98789
* Content: [Set-PhysicalDisk (Storage)](https://docs.microsoft.com/en-us/powershell/module/storage/set-physicaldisk?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/storage/Set-PhysicalDisk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/storage/Set-PhysicalDisk.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
