### ISSUE TITLE
Missing information for start-bitstransfer 

### ISSUE THREAD

**Issue by BlackV** [MicrosoftDocs/windows-powershell-docs#2589]
The document completely ignores a parameter

`Start-BitsTransfer -SecurityFlags`

`EnableCRLCheck,                  IgnoreCertWrongUsage,            RedirectPolicyAllowReport,
IgnoreCertCNInvalid,             IgnoreUnknownCA,                 RedirectPolicyAllowSilent,
IgnoreCertDateInvalid,           RedirectPolicyAllowHttpsToHttp,  RedirectPolicyDisallow`

there no explanation here or in `get-help Start-BitsTransfer -full`
this includes powershell 7/6/5, I have not checked PS4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fb39b0-6b7e-a143-683b-5966b872c938
* Version Independent ID: 63016f51-2ccf-fdb0-5e29-16418508ce64
* Content: [Start-BitsTransfer (BitsTransfer)](https://docs.microsoft.com/en-us/powershell/module/bitstransfer/start-bitstransfer?view=windowsserver2019-ps&source=docs)
* Content Source: [docset/winserver2019-ps/bitstransfer/Start-BitsTransfer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/bitstransfer/Start-BitsTransfer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@BlackV Thank you for your feedback.

I have test with several server versions and none of them have the SecurityFlags parameter. In Windows 10 I have the parameter.

What OS did you use in your tests?
