### ISSUE TITLE
PNP DEVICE SERVER 2012 R2

### ISSUE THREAD

**Issue by zsvendo** [MicrosoftDocs/windows-powershell-docs#2598]
I need to disable some drivers on windows 2012 server r2, but it does not have the PNP Device, is there a possibility to deploy this mdules?

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
