### ISSUE TITLE
Windows 11 Export-StartLayout & Import-StartLayout

### ISSUE THREAD

**Issue by absolutionxi** [MicrosoftDocs/windows-powershell-docs#2600]
Recently was playing around with Windows 11 & start menu layouts for learning & possible Autopilot deployment when the time comes.

I exported a layout with Export-StartLayout -Path "C:\LayoutModification.json" - created the file fine. The start menu was completely blank. Here is the .json from that export.
`{"pinnedList":[]}`

I imported that file into %localappdata%\microsoft\windows\shell\LayoutModification.json and deployed the image.
The deployed image did seem to run some as the start menu was missing some icons, however, the now blank thumbnails were still working. Could right click, uninstall, launch, pin, etc.

Is this intended, or a bug? 
The json had nothing pinned, so why would any apps remain pinned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31b7cb77-3889-f738-4e72-e5a263a00775
* Version Independent ID: 60cd8847-a46f-67a7-6b98-e9a40862fefa
* Content: [Import-StartLayout (StartLayout)](https://docs.microsoft.com/en-us/powershell/module/startlayout/import-startlayout?view=windowsserver2019-ps#description)
* Content Source: [docset/winserver2019-ps/startlayout/Import-StartLayout.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/startlayout/Import-StartLayout.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
