### ISSUE TITLE
Missing details on Custom

### ISSUE THREAD

**Issue by Maraudier** [MicrosoftDocs/windows-powershell-docs#2626]
[Enter feedback here]
-AccessRight has a selection for "Custom" but does not detail how to define the parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fbee81d-7ac3-3800-65c4-d6a6a2213baf
* Version Independent ID: 1c94a3bc-e671-8a92-42ba-e7c669733135
* Content: [Grant-SmbShareAccess (SmbShare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/grant-smbshareaccess?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/smbshare/Grant-SmbShareAccess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/smbshare/Grant-SmbShareAccess.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Maraudier Thank you for your feedback. The accepted values for this parameter are: Full, Change, or Read

We have made these changes via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2803

Thanks
Sri
