### ISSUE TITLE
Valid values for -CertStoreLocation?

### ISSUE THREAD

**Issue by cosmoKenney** [MicrosoftDocs/windows-powershell-docs#266]
How does one know what values to specify for -CertStoreLocation? Let's say I want to add to local machine trusted root certification authorities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c694289c-79f5-03cd-38aa-5d2ec76988bd
* Version Independent ID: 0a5a5227-c7da-d308-9fca-857b49f6cf7c
* Content: [Import-Certificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-certificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/import-certificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/import-certificate.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by baarsd** [comment]
Hey, 

hope this helps - if you open Powershell (as admin) and type "set-location cert:" you can then type e.g. "dir" or "dir LocalMachine" to get a list of valid CertStoreLocation values -

PS Cert:\> dir LocalMachine
Name : TrustedPublisher
Name : ClientAuthIssuer
Name : Remote Desktop
Name : Root
Name : TrustedDevices
Name : CA
Name : Windows Live ID Token Issuer
Name : eSIM Certification Authorities
Name : AuthRoot
Name : AAD Token Issuer
Name : FlightRoot
Name : TrustedPeople
Name : My
Name : SmartCardRoot
Name : Trust
Name : Disallowed
Name : Homegroup Machine Certificates
Name : SMS

So to import into the local machine trusted root certification authorities store, the command would be:

Import-Certificate -FilePath C:\Path\To\cert.cer -CertStoreLocation Cert:\LocalMachine\Root

Hope that helps :-)

**Comment by cosmoKenney** [comment]
@baarsd , that's so cool! Thanks for posting it.
