### ISSUE TITLE
Wait parameter not documented

### ISSUE THREAD

**Issue by csubram** [MicrosoftDocs/windows-powershell-docs#2662]
Hi, I'm trying to figure out the behavior of the "Wait" parameter for this cmdlet but it doesn't seem to be documented on this page. A colleague has suggested that adding -Wait will cause the command to run synchronously, whereas otherwise it would run asynchronously. Is this the correct understanding? And if so, could a better description be added to this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d866884e-0037-3582-7923-351b43f4b703
* Version Independent ID: 40c9c106-abc0-ce63-6ec8-aed3f327539e
* Content: [Restart-VM (Hyper-V)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2019-ps#feedback)
* Content Source: [docset/winserver2019-ps/hyper-v/Restart-VM.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/hyper-v/Restart-VM.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@csubram Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2802

Restart-VM suppresses the PowerShell prompt and blocks the pipeline until the VM has restarted. You can use this parameter in a script to restart VM and then continue to process when the restart is finished.

The Wait parameter waits indefinitely for the VM to restart. You can use Timeout to adjust the timing and the For and Delay parameters to wait for particular services to become available on the restarted VM.

Thanks
Sri

**Comment by msbemba** [comment]
The restart doesn't give up. You can wait for the restart to complete before you run the next command. Specify a waiting time-out and query interval, and wait for particular services to be available on the restarted VM. This feature makes it practical to use Restart-VMin scripts and functions

**Comment by msbemba** [comment]
@e0i The issue can be closed as the query has been answered.

Thanks
Sri
