### ISSUE TITLE
password complexity (-ComplexityEnabled) description not complete

### ISSUE THREAD

**Issue by Kuchtui** [MicrosoftDocs/windows-powershell-docs#2668]
Dear all

I have the complexity enabled.
We getting tickets form user that they are not able to change the password.
The complexity three of the four characters types was fulfilled.
What also will be checked is the user attribute "displayname" of the user object.
Each existing word is also not allowed to be used in the password.

Example:
Displayname: Test user
Than is not allowed to have one of this words in the password.

Are they more unknown surprised attribute or something else that are forbidden?
It be very helpful to known that :-) and this issue makes absolutely sense. 

Thanks and regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b58daae-d467-9da5-7603-d56098a298ff
* Version Independent ID: cb3a67d2-4fde-8517-c634-c0ee5d7fd293
* Content: [New-ADFineGrainedPasswordPolicy (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adfinegrainedpasswordpolicy?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Kuchtui Thank you for your feedback. The passwords if set to meet complexity requirements in the default policy, Passwords may not contain the user's samAccountName (Account Name) value or entire displayName (Full Name value). Both checks aren't case-sensitive.

This is regardless of whether we use the default or the ADFineGrainedPasswordPolicy.

Hope this helps!

Thanks
Sri
