### ISSUE TITLE
Restore-MpThreatfuckingfalseAlarm

### ISSUE THREAD

**Issue by Big2thaE** [MicrosoftDocs/windows-powershell-docs#2670]
I'm not married to the name, but it doesn't seem there is a PowerShell method for restoring something that was quarantined. 

ActionSuccess                  : True
AdditionalActionsBitMask       : 0
AMProductVersion               : 4.18.2108.7
CleaningActionID               : 9
CurrentThreatExecutionStatusID : 1
DetectionID                    : {70AA73B4-50FA-4FCB-8E74-FAA1088DA03A}
DetectionSourceTypeID          : 3
DomainUser                     : CHRISTIANSON-01\ERIK
InitialDetectionTime           : 2/1/2021 1:20:47 PM
LastThreatStatusChangeTime     : 2/1/2021 1:20:47 PM
ProcessName                    : C:\Program Files (x86)\ScreenConnect Client (fd5534eb74bb7273)\ScreenConnect.WindowsClient.exe
RemediationTime                : 
Resources                      : {file:_C:\Apps\PortableApps\PortableApps\IObitUninstallerPortable\App\uninstaller\IObitUninstaler.exe}
ThreatID                       : 224054
ThreatStatusErrorCode          : 0
ThreatStatusID                 : 1
PSComputerName                 :

**Comment by msbemba** [comment]
@Big2thaE Thank you for your feedback. Currently, there is no PowerShell method to restore something that was quarantined.

This is available  via the GUI for now
Open Windows Security.
Select Virus & threat protection and then click Protection history.
In the list of all recent items, filter on Quarantined Items.
Select an item you want to keep and take an action, such as restore.

You can provide feedback on our Main feedback Portal - https://feedbackportal.microsoft.com and you will receive updates on the availability and when it will be implemented.

Hope this helps!

Thanks
Sri
