### ISSUE TITLE
Stretch Cluster Replica example is wrong regarding computernames.

### ISSUE THREAD

**Issue by Mihaly7** [MicrosoftDocs/windows-powershell-docs#2678]
The example for Stretch Cluster is bad:
Set-SRNetworkConstraint -SourceComputerName "SR-SRV01" -SourceRGName "Group01" -SourceNWInterface "Cluster Network 1","Cluster Network 2" -DestinationComputerName "SR-SRV03" -DestinationRGName "Group02" -DestinationNWInterface "Cluster Network 1","Cluster Network 2"
[Enter feedback here]

-SourceComputerName and -DestinationComputerName should be the cluster's name, not individual cluster nodes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33bdd435-62e9-3ecf-0cdd-e0e78166a116
* Version Independent ID: 5be2ee2d-01b4-cbde-b91c-72ad7ea0c57b
* Content: [Set-SRNetworkConstraint (StorageReplica)](https://docs.microsoft.com/en-us/powershell/module/storagereplica/set-srnetworkconstraint?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/storagereplica/Set-SRNetworkConstraint.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/storagereplica/Set-SRNetworkConstraint.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Mihaly7 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2811

Thanks
Sri
