### ISSUE TITLE
Error in Description section

### ISSUE THREAD

**Issue by hmcmtg** [MicrosoftDocs/windows-powershell-docs#2680]
On this page: https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps
The Description says "The Identity parameter specifies the Active Directory group to get. You can identify a group by its distinguished name (DN), GUID, security identifier (SID), Security Accounts Manager (SAM) account name, or canonical name."

The details section for the -Identity parameter says: "The acceptable values for this parameter are:

A distinguished name
A GUID (objectGUID)
A security identifier (objectSid)
A security accounts manager account name (sAMAccountName)"

It appears that the Description is wrong in that canonical name is not an acceptable value for the -Identity parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c71fbd-74aa-d80a-33ae-1b4ebadaf75e
* Version Independent ID: b694a588-c889-b1fb-140a-ca107fa61d57
* Content: [Get-ADGroup (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/activedirectory/Get-ADGroup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@hmcmtg Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2812

Thanks
Sri
