### ISSUE TITLE
It's all in the slash

### ISSUE THREAD

**Issue by brianhorizon** [MicrosoftDocs/windows-powershell-docs#269]
When trying to import the database with this command Import-DfsrClone -Volume "D:" -Path "D:\Dfsrclone\" the process would error and the log would report Event ID 2414, Error: 9111 (MSXML.DLL is not installed) . After spending hours ding research I finally came across and article form someone who had the problem exporting the DB. The"\" at the end of the path at the end of the path statement was breaking the export. I removed the "\" from the import statement and my problem was resolved, after almost a day. 

PLEASE UPDATE DOCUMENT TO LET PEOPLE KNOW THAT THE "\" AT THE END OF THE PATH BREAKS THE IMPORT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b887d07b-1685-2f88-301e-958ade180427
* Version Independent ID: 53233ad1-5fbb-1fa3-b6fd-0be775706c09
* Content: [Import-DfsrClone (dfsr)](https://docs.microsoft.com/en-us/powershell/module/dfsr/import-dfsrclone?view=win10-ps)
* Content Source: [docset/windows/dfsr/import-dfsrclone.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dfsr/import-dfsrclone.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith Please merge this PR, if find it suitable

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @brianhorizon  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
