### ISSUE TITLE
Add-ADGroupMember, able to add a Group as a Member of Itself

### ISSUE THREAD

**Issue by ccatlett1984** [MicrosoftDocs/windows-powershell-docs#2696]
I've broken a few software products in my Lab with this, since they do recursive group enumeration.
$group = Get-ADGroup -Identity "Domain Admins"
Add-ADGroupMember -Identity $group -Members $group

verified on Server 2022

**Comment by velkovb** [comment]
@ccatlett1984 Thank you for your feedback.

I have verified the behaviour. We will escalate the issue and will add a note to the article to mention that.
