### ISSUE TITLE
Remove-VpnConnection not working as intended

### ISSUE THREAD

**Issue by drullar** [MicrosoftDocs/windows-powershell-docs#2710]
[Enter feedback here]

The "Remove-VpnConnection -Name x" command would return "VPN Connection x was not found", even though the VPN name  was copied directly from "Get-VpnConnection -AllUserConnections"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afca57fb-dd24-85e9-4796-80c42d011352
* Version Independent ID: a803b6c0-e37a-b1e7-b38c-d3adf9712dbf
* Content: [Remove-VpnConnection (VpnClient)](https://docs.microsoft.com/en-us/powershell/module/vpnclient/remove-vpnconnection?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/vpnclient/Remove-VpnConnection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/vpnclient/Remove-VpnConnection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@drullar Thank you for your feedback. I was able to test this without any issues. This could be related to your local computer, The best way to get your issue resolved is to contact Microsoft Support. You can create a support ticket at https://support.serviceshub.microsoft.com/supportforbusiness

Thanks
Sri
