### ISSUE TITLE
Further explanation of the -Enforce field is needed.

### ISSUE THREAD

**Issue by mjohnsonn** [MicrosoftDocs/windows-powershell-docs#2712]
Will setting -Enforce to $False stop a file from being removed from the namespace if unfixable corruption is found?  The removal is a large problem that precludes the use of ReFS for many installations.  If setting that field to $False will sove the problem, it should be mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbe5fe03-be42-2df6-b218-4d1d18c80f31
* Version Independent ID: 19556698-0a53-f948-7cd6-d9f2189b2c49
* Content: [Set-FileIntegrity (Storage)](https://docs.microsoft.com/en-us/powershell/module/storage/set-fileintegrity?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/storage/Set-FileIntegrity.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/storage/Set-FileIntegrity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by e0i** [comment]
Related to, https://github.com/MicrosoftDocs/windowsserverdocs/issues/1120

**Comment by mechanical-snail** [comment]
There's also some relevant discussion in this Reddit post: https://www.reddit.com/r/DataHoarder/comments/scdclm/testing_refs_data_integrity_streams_corrupt_data/
