### ISSUE TITLE
Get-Volume does not work in the Windows Sandbox

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windows-powershell-docs#2717]
It might be useful to document that Get-Volume does not work in the Windows Sandbox  in the article.

BTW. Get-Disk works equally well.

I suppose that the reason for the failures are related. Even though there is a good reason, it is limiting what can be tested in the Sandbox. In my case I was trying to calculate how effective my script was at removing temp files.

The script will trigger a defrag session if it detects that it has deleted more than 20% of the content on the C: drive.

I don't mind if the defrag does not work in the sandbox as long as it behaves as if it does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 507fa303-dc37-d980-0f1c-5a4af63ce0e7
* Version Independent ID: 279ec172-464d-a85d-ec6a-eefd61728156
* Content: [Get-Volume (Storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-volume?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/storage/Get-Volume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/storage/Get-Volume.md)
* Product: **w10**
* Technology: **windows**
![Sandbox](https://user-images.githubusercontent.com/82510602/136746545-29a8c80c-9f4c-44b1-a56a-8e796b58dad4.png)

* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@Tarjei-stavanger Thank you for your feedback.

I believe this is not a PowerShell issue and should be directed to the Windows Sandbox documentation. You can also leave feedback here - [Windows Sandbox](https://docs.microsoft.com/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
