### ISSUE TITLE
Several parameters are missing

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/windows-powershell-docs#273]
Windows PowerShell reports that Get-WindowsCapability has the following parameters. The three, which I have highlighted in boldface are missing from the correspond documentation page (see below).
- **LimitAccess**
- **Source**
- **Verbose**
- LogLevel
- LogPath
- Name
- Online
- Path
- ScratchDirectory
- SystemDrive
- WindowsDirectory

**Update (2018-11-07):** Improved description of the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 551eb88d-11fd-5d28-1a91-d0c4246967ac
* Version Independent ID: c7023233-2a92-7382-d55e-a393f84c6539
* Content: [Get-WindowsCapability (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/get-windowscapability?view=win10-ps)
* Content Source: [docset/windows/dism/get-windowscapability.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/get-windowscapability.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by 3ter** [comment]
I suppose this can be closed as with the following versions everything shows as documented.

PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\WINDOWS\system32> (get-command -Name "Get-WindowsCapability").Parameters.Keys | sort
Debug
ErrorAction
ErrorVariable
InformationAction
InformationVariable
LimitAccess
LogLevel
LogPath
Name
Online
OutBuffer
OutVariable
Path
PipelineVariable
ScratchDirectory
Source
SystemDrive
Verbose
WarningAction
WarningVariable
WindowsDirectory

**Comment by skycommand** [comment]
@3ter With all due respect, when I wrote "the missing ones", I meant "missing from the documentation page on which I am providing feedback", i.e. missing from [docset/windows/dism/get-windowscapability.md](docset/windows/dism/get-windowscapability.md). They are undocumented.

**Comment by 3ter** [comment]
@skycommand Thanks for the hint. I've shortened my inconsiderate comment.

**Comment by e0i** [comment]
@skycommand Thank you for providing valuable feedback. We are looking into this documentation issue and will release a fix soon.

**Comment by e0i** [comment]
@skycommand  With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by skycommand** [comment]
@e0i Hi. I am seeing your PR #747. Please do note that `-Source` requires extensive descriptions to help system administrators understand what constitutes a valid source. I've been struggling with this PowerShell cmdlet for a long time now.
