### ISSUE TITLE
Missing details about powershell triggers

### ISSUE THREAD

**Issue by adin3d** [MicrosoftDocs/windows-powershell-docs#2743]
Hi everyone, 

I am trying to find details on how to use the powershell  New-ScheduledTaskAction,  New-ScheduledTaskTrigger and Register-ScheduledTask with multiple triggers and also how to use in powershell the triggers "On remote connection to any user session" and "On remote disconnect from any user session"

I checked through this pages and I can't find anything 

https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/?view=windowsserver2019-ps

https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=windowsserver2019-ps
 
Thank you for looking into this :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ccab8a-b1b9-dad5-1682-f526513b3c28
* Version Independent ID: 4e093fe1-bdec-0e8f-2d35-ef44181f617d
* Content: [Register-ScheduledTask (ScheduledTasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/register-scheduledtask?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/scheduledtasks/Register-ScheduledTask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/scheduledtasks/Register-ScheduledTask.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@adin3d Thank you for your feedback.

I have checked and it seems that those two options are not supported by the PowerShell cmdlet yet. As for the multiple triggers, you can just create multiple ones and pass them as an array to the scheduled task as the `-Trigger` parameter accepts an array of triggers.
