### ISSUE TITLE
Access Denied Error (even though using Domain Admin rights)

### ISSUE THREAD

**Issue by ErnestBrant** [MicrosoftDocs/windows-powershell-docs#2745]
[Enter feedback here]
Hello
I tried to use this command to add a Policy Server to a standalone windows server (as using CEP/CES). I am logged on to this standalone Windows server as the local administrator account

Add-CertificateEnrollmentPolicyServer -Url https://cescep2.global.local/KeyBasedRenewal_ADPolicyProvider_CEP_Certificate/service.svc/CEP -context Machine -Credential (Get-Credential)

I used to credential of a Domain Admin (also tried the credential of the AD service account which CEP/CES is running under). I also tried specifying no credential (in case the remote computer the error referred to was actually the local computer).

Nothing works, any ideas, please?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c91528-43f3-a787-994b-a4f96e4728bb
* Version Independent ID: d553d916-90be-27cf-d496-195932168c83
* Content: [Add-CertificateEnrollmentPolicyServer (pki)](https://docs.microsoft.com/en-us/powershell/module/pki/add-certificateenrollmentpolicyserver?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/pki/Add-CertificateEnrollmentPolicyServer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/pki/Add-CertificateEnrollmentPolicyServer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by e0i** [comment]
Hello, This is a question that can best be answered via the [Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

Thank you.
