### ISSUE TITLE
All ScheduledTask Powershell Help URI's Missing

### ISSUE THREAD

**Issue by PFarrell216** [MicrosoftDocs/windows-powershell-docs#2747]
All "help -online" queries for TaskScheduler powershell cmdlets specified for the on [this page](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/?view=windowsserver2019-ps) return the following error:

```
Get-Help:
Line |
  64 |      $help = Get-Help @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
```

**Example**: > help  New-ScheduledTaskTrigger -Online 

Running Win10 20H2 (Build 18042.985), Powershell 7.1.5 as admin after update-help 

Please let me know if this Issue would be better suited for the main powershell github as a code problem, rather than a docs problem. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 331a327f-98f0-6b07-0523-07b2bfa43324
* Version Independent ID: a93374e6-2115-c17f-bd4c-ab4efc958143
* Content: [New-ScheduledTask (ScheduledTasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtask?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/scheduledtasks/New-ScheduledTask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/scheduledtasks/New-ScheduledTask.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@PFarrell216 Thank you for your feedback. Unfortunately, this means the the link is actually missing from the version deployed in Windows. Here we can only update the documentation itself not the deployed version. Will try to see if we can route this the correct way.
