### ISSUE TITLE
Conflicting description for -LogLevel

### ISSUE THREAD

**Issue by SamHills** [MicrosoftDocs/windows-powershell-docs#2749]
The description for -LogLevel states that the default value is 3, but the table which immediately follows says: Default value None.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7cc84a6-ba25-e70f-7d2e-ad4ffffeea49
* Version Independent ID: df6fd8ab-9f1f-495d-478e-f40579b169a2
* Content: [Get-WindowsImage (DISM)](https://docs.microsoft.com/en-us/powershell/module/dism/get-windowsimage?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/dism/Get-WindowsImage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/dism/Get-WindowsImage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@SamHills Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2814

Thanks
Sri
