### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by TomicaKaniski** [MicrosoftDocs/windows-powershell-docs#276]
In the last line of the first example, you are using non-existent variables:
Register-ScheduledTask Task01 -Action $a -Principal $p

Should be replaced with:
PS C:\&gt;Register-ScheduledTask Task01 -Action $Sta -Principal $STPrin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75775a8f-71ea-4d5f-dd5e-a83603b02fc0
* Version Independent ID: 57bc659a-9971-ae7a-4df4-10c9c46d9ee3
* Content: [New-ScheduledTaskPrincipal (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtaskprincipal?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/new-scheduledtaskprincipal.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/new-scheduledtaskprincipal.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Styxxy** [comment]
I submitted PR #285 to fix this.
