### ISSUE TITLE
Is remotedesktop module still maintained?

### ISSUE THREAD

**Issue by pr1malc0de** [MicrosoftDocs/windows-powershell-docs#2763]
Struggling to find supported for the actual module, it would be great to provide a link in documents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa849e5f-5d75-eb86-54ed-9ac329898319
* Version Independent ID: aac8835d-984f-d25f-2e2a-45a606e69f7b
* Content: [RemoteDesktop Module](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/?view=windowsserver2016-ps)
* Content Source: [docset/winserver2016-ps/remotedesktop/RemoteDesktop.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2016-ps/remotedesktop/RemoteDesktop.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@pr1malc0de Thank you for your feedback.

The RemoteDesktop module is supported and available in newer Server version as well. However, the docs are still not populated. Will try to escalate this to get the newer docs here as well.
