### ISSUE TITLE
Incorrect term in example section headers

### ISSUE THREAD

**Issue by DrSigmund** [MicrosoftDocs/windows-powershell-docs#2765]
Headers of examples 2 and 3 "Add a volume recursively to a backup file specification" and "Add a volume nonrecursively to a backup file specification" must contain word "folder" instead of "volume". In both examples, a folder is being added and not a volume.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9658e51-a265-8f89-8333-77bc89b55e95
* Version Independent ID: bed50b24-77bf-b2d2-b260-65f8107b7071
* Content: [New-WBFileSpec (WindowsServerBackup)](https://docs.microsoft.com/en-us/powershell/module/windowsserverbackup/new-wbfilespec?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/windowsserverbackup/New-WBFileSpec.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/windowsserverbackup/New-WBFileSpec.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@DrSigmund Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2816

Thanks
Sri
