### ISSUE TITLE
IPv2 typo

### ISSUE THREAD

**Issue by vasek-cz** [MicrosoftDocs/windows-powershell-docs#2767]
Small typo on IP versions:

    IPv2
    IPv6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc2f37c-f837-694d-3ba5-a36d38fb76f8
* Version Independent ID: fcd15ec5-dd76-a06e-083c-09b9a071b888
* Content: [New-VpnTrafficSelector (RemoteAccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/new-vpntrafficselector?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/remoteaccess/New-VpnTrafficSelector.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/remoteaccess/New-VpnTrafficSelector.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by kilasuit** [comment]
@vasek-cz I've just submitted a PR to fix this typo

**Comment by tiburd** [comment]
This issue should close when this PR is merged: #2768
