### ISSUE TITLE
Examples for New-ScheduledTask are incorrect and out of sync

### ISSUE THREAD

**Issue by CamyDee** [MicrosoftDocs/windows-powershell-docs#2771]
Examples for New-ScheduledTask are incorrect and out of sync. The description mentions variables such as $T and $D which do not exist in the script. Also, these examples do not work in PowerShell 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 331a327f-98f0-6b07-0523-07b2bfa43324
* Version Independent ID: a93374e6-2115-c17f-bd4c-ab4efc958143
* Content: [New-ScheduledTask (ScheduledTasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtask?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/scheduledtasks/New-ScheduledTask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/scheduledtasks/New-ScheduledTask.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@CamyDee Thank you for your feedback. I don't think this documentation is targeting PowerShell 7. What is the error that you are getting there?

We will update the incorrect variable names.
