### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by meluvalli** [MicrosoftDocs/windows-powershell-docs#2783]
Get-DHCPServerv4OptionDefinition : Failed to get option definitions on DHCP server [My ServerName].
At line:1 char:1
+ Get-DHCPServerv4OptionDefinition
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (COLO355:root/Microsoft/...ptionDefinition) [Get-DhcpServerv4OptionDefinit
   ion], CimException
    + FullyQualifiedErrorId : WIN32 1722,Get-DhcpServerv4OptionDefinition

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd5debb-9083-54e2-bd2c-a0e1055bf5e9
* Version Independent ID: 940b863d-fffb-50ca-fd27-997fa2a15b86
* Content: [Get-DhcpServerv4OptionDefinition (DhcpServer)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4optiondefinition?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/dhcpserver/Get-DhcpServerv4OptionDefinition.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/dhcpserver/Get-DhcpServerv4OptionDefinition.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
