### ISSUE TITLE
New-adfsaccesscontrolpolicy

### ISSUE THREAD

**Issue by T00ber** [MicrosoftDocs/windows-powershell-docs#2784]
The help file mentions that a metadata file needs to be used but there is no mention on how this file is created?

Can someone shed some light?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15848e3d-f506-f20a-39eb-f139667084f7
* Version Independent ID: f7335255-2961-e7f1-a5e5-54b982745afb
* Content: [New-AdfsAccessControlPolicy (ADFS)](https://docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@T00ber Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2817

You can get the file from https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata

Thanks
Sri
