### ISSUE TITLE
-Filter parameter definition is ambiguous 

### ISSUE THREAD

**Issue by RichMath** [MicrosoftDocs/windows-powershell-docs#2789]
In the "Syntax" section of the Get-ADComputer cmdlet the definition for the filter parameter is "-Filter <&lt>String<&gt>" (as it is in the "about_ActiveDirectory_Filter" topic), but in the "Parameters" section the description of the -Filter shows it to be a script block (<&lt>filter<&gt> ::= "{" <&lt>FilterComponentList<&gt> "}").

Is the intention that the actual filter is a script block enclosed with quotes? Or is the filter string definition for the cmdlet's -Filter parameter incorrect and the filter string should not be using those curly braces at all and the string should be just a literal string or a variable that contains a string?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f36f37-7bc3-35c7-d54b-c62670fbf185
* Version Independent ID: a0f9a9fe-80eb-89be-f73a-7c46a85319ad
* Content: [Get-ADComputer (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-adcomputer?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/activedirectory/Get-ADComputer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/activedirectory/Get-ADComputer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
