### ISSUE TITLE
The “-AddMember” parameter “Accept wildcard characters” “False” seems inaccurate

### ISSUE THREAD

**Issue by likelinyang** [MicrosoftDocs/windows-powershell-docs#2799]
The “-AddMember” parameter “Accept wildcard characters” “False” seems inaccurate, I can add the IP subnet like “172.20.1.*” in lab WS2019 NFS server as below. But only accept one *, “172.20.*.*” or “172.*.*.*” not work.

ClientGroupName ClientGroupMembers
--------------- ------------------
G1              {172.20.1.*}
G2              {1.2.3.*}
G3              {10.20.30.1, 10.20.30.2}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816adce4-dd8b-b6eb-74a1-134626466cc4
* Version Independent ID: 686f8d1d-9393-dd53-2fd9-85d4c54b3d63
* Content: [New-NfsClientgroup (NFS)](https://docs.microsoft.com/en-us/powershell/module/nfs/new-nfsclientgroup?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/nfs/New-NfsClientgroup.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/nfs/New-NfsClientgroup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@likelinyang Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2815

Thanks
Sri

**Comment by msbemba** [comment]
@likelinyang Did you try it on the WS2019 NFS server? Could you please share the cmdlet used and the result?

**Comment by likelinyang** [comment]
> @likelinyang Did you try it on the WS2019 NFS server? Could you please share the cmdlet used and the result?

Yes, it was tested on WS2019 as below.

PS C:\Users\administrator.CORP> (Get-WmiObject win32_operatingsystem).name
Microsoft Windows Server 2019 Standard|C:\Windows|\Device\Harddisk0\Partition2
PS C:\Users\administrator.CORP> Get-NfsClientgroup

ClientGroupName ClientGroupMembers
--------------- ------------------
G1              {172.20.1.*}
G2              {1.2.3.*}
G3              {10.20.30.1, 10.20.30.2}


PS C:\Users\administrator.CORP> New-NfsClientgroup -name "G4" -AddMember "192.168.1.*"
PS C:\Users\administrator.CORP> Get-NfsClientgroup

ClientGroupName ClientGroupMembers
--------------- ------------------
G1              {172.20.1.*}
G2              {1.2.3.*}
G3              {10.20.30.1, 10.20.30.2}
G4              {192.168.1.*}
