### ISSUE TITLE
Default Behaviour

### ISSUE THREAD

**Issue by metamoof** [MicrosoftDocs/windows-powershell-docs#280]
Could you please document what the default behaviour for `-AccountExpiring` and `-AccountInactive` are when not used with a `-DateTime` or `-TimeSpan` parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87483a05-ea3b-19c2-3d31-4701e03e68e2
* Version Independent ID: 917d2078-1e43-895a-e3cb-d6e64844196e
* Content: [Search-ADAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/search-adaccount?view=win10-ps)
* Content Source: [docset/windows/addsadministration/search-adaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/search-adaccount.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit
