### ISSUE TITLE
Get-DnsServerResourceRecordA...etc All Gone

### ISSUE THREAD

**Issue by PowershellPerson** [MicrosoftDocs/windows-powershell-docs#281]
After the most recent update(07/12/18) on windows 10 1803, all Get-DnsServerResourceRecord cmdlets besides the base cmdlet of "Get-DnsServerResourceRecord"are missing. Was this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26d20419-9d03-1303-93cd-606fa58704c0
* Version Independent ID: 4a3e8930-8c29-43b8-3989-5e1bd94eaf47
* Content: [DnsServer](https://docs.microsoft.com/en-us/powershell/module/dnsserver/?view=win10-ps)
* Content Source: [docset/windows/dnsserver/dnsserver.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/dnsserver.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @PowershellPerson , thank you for your feedback.

Could you detail what cmdlets are missing? Thanks.

**Comment by yogkumgit** [comment]
@PowershellPerson We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by yogkumgit** [comment]
@officedocsbot close
