### ISSUE TITLE
hyper-v

### ISSUE THREAD

**Issue by dehec** [MicrosoftDocs/windows-powershell-docs#2818]
[Enter feedback  @here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716da5f5-885b-057d-3962-159289361fd9
* Version Independent ID: 78c48168-10bf-4598-4ebe-2113bbaa1632
* Content: [Set-VMResourcePool (Hyper-V)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmresourcepool?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/hyper-v/Set-VMResourcePool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/hyper-v/Set-VMResourcePool.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@dehec Thank you for trying to make MicrosoftDocs a better place.

Could you explain in more details your issue?

**Comment by scanum** [comment]
@dehec We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
