### ISSUE TITLE
the -password parameter for Register-ScheduledTask show as plain text in event log

### ISSUE THREAD

**Issue by mythkapo** [MicrosoftDocs/windows-powershell-docs#282]
the -password parameter for Register-ScheduledTask show as plain text in event log, this parameter should accept PScredential or secureString 

Otherwise, people will be able to see the password through event viewer powershell log

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by VLG17** [comment]
Hi @mythkapo 

thank you for your feedback. Indeed, the password should not be shown in plain text. I recommend that you create a suggestion using the UserVoice channel for Windows Server -https://windowsserver.uservoice.com/forums/295047-general-feedback

**Comment by yogkumgit** [comment]
@mythkapo  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested by @VLG17 please logg this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
