### ISSUE TITLE
New-ADGroup fails when passing -otherAttribute with multiple 'objectclass' attribute values

### ISSUE THREAD

**Issue by VeeFu** [MicrosoftDocs/windows-powershell-docs#283]
The following syntax was used to attempt to create a dynamic object in AD:

```
New-ADGroup -OtherAttributes @{'objectClass'="Group","DynamicObject";'entryTTL'=180} 
-Name 'Deleted in 180 Seconds' -Path $myGroupsOu -GroupScope DomainLocal

```
The -OtherAttributes parameter seems to adhere to documentation, but the following error persists:

```
<#
New-ADGroup : Unable to cast object of type 'System.String[]' to type 'System.String'.
At line:2 char:1
+ New-ADGroup -OtherAttributes @{'objectClass'="Group","DynamicObject"; ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CN=Deleted in 1...dc=state,dc=sbu:String) [New-ADGroup], InvalidCastException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.InvalidCastException,Microsoft.ActiveDirectory.Management.Commands.NewADGroup

```

Is this a failure of the -OtherAttributes parameter or incorrect documentation?

**Comment by VeeFu** [comment]
Further details of the problem are documented on [StackOverflow](https://stackoverflow.com/questions/51262478/can-new-adgroup-be-used-with-an-additional-objectclass-attribute-values?noredirect=1#comment89538049_51262478)

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by e0i** [comment]
@officedocsbot unassign @e0i

**Comment by dariomws** [comment]
Hi @VeeFu, thank you for your feedback and sorry for the delay.

I've done some testing, and it seems that New-ADGroup and New-ADUser do not support the dynamicObject creation with the OtherAttributes parameter. So you should use another tool like LDIFDE.
If you still need help, I suggest that you open a support case. If you found a solution, please share it with us.

Thank you again.

**Comment by VeeFu** [comment]
Thanks @dariomws for the reply. Gosh it's been ages since I opened this! 

I appreciate the confirmation about 'dynamicObject' class. I suspected something was special about this object class type. The StackOverflow link seems to show that I dropped into an ADSI interface to achieve my goal at the time.

There is still something strange about `-otherAttribtues`, though. 

Here's a test that demonstrates. I've modified the schema to include the 'drink' multi-value attribute in my user object class before performing this test:

```
New-ADUser -name Thirsty -OtherAttributes @{'drink'='water', 'orange juice'}
```
gives an error response of:
```
Invalid type 'System.Collections.ArrayList'.
Parameter name: drink
    + CategoryInfo          : InvalidArgument: (CN=Thirsty,CN=Users,DC=pacman,DC=local:String) [New-ADUser], ArgumentE
   xception
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Comm
   ands.NewADUser
```

If we store the hash table first, however:
```
$multiDrinks = @{'drink'='water', 'orange juice'}
New-ADUser -name Thirsty -OtherAttributes $multiDrinks
```
There is no problem.


Similar for Set-ADUser

```
Set-ADUser Thirsty -Add @{'drink'= 'coffee', 'tea'}
```
yields an error
```
Invalid type 'System.Management.Automation.PSObject'.
Parameter name: drink
    + CategoryInfo          : InvalidArgument: (Thirsty:ADUser) [Set-ADUser], ArgumentException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Comm
   ands.SetADUser
```

but the following is fine:
```
$moreDrinks = @{'drink'= 'coffee', 'tea'}
Set-ADUser Thirsty -Add $moreDrinks
```

**Comment by dariomws** [comment]
@VeeFu I think I cannot help more here because we are limited to documentation issues and improvements.

If you still need help, the best way forward is to open a service ticket in your tenant, so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

I hope you understand. Thank you!
