### ISSUE TITLE
Set-MMAgent documentation is outdated.

### ISSUE THREAD

**Issue by kotenok2000** [MicrosoftDocs/windows-powershell-docs#2842]
It seems something has changed and "Set-MMAgent MaxOperationAPIFiles 128" does not work
"Set-MMAgent -MaxOperationAPIFiles 128" works

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3f748-52f5-eea1-8e8e-06b475298642
* Version Independent ID: 86ec07fd-b14b-555b-1091-896c0dceb1ad
* Content: [Set-MMAgent (MMAgent)](https://docs.microsoft.com/en-us/powershell/module/mmagent/set-mmagent?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/mmagent/Set-MMAgent.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/mmagent/Set-MMAgent.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@kotenok2000 Hi Kiril,

Thank you for you feedback.

I believe the example has a typo. Will work on fixing that.
