### ISSUE TITLE
Clearer parameter usage instructions

### ISSUE THREAD

**Issue by AreJayAreEm** [MicrosoftDocs/windows-powershell-docs#2849]
There is no clear guidance on how to use the "verbose" parameter. Current advice states "The Verbose parameter displays a count of all backlogged updates.". I have tried both verbose and /verbose but neither of these appear to work, I get the following errors:

Get-DfsrBacklog : No replicated folders were found on the member. Member name: RACPDCGSC1002 Replicated folder: "*"
Replication group: "verbose"
At line:1 char:1
+ Get-DfsrBacklog verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-DfsrBacklog], DfsrException
    + FullyQualifiedErrorId : Get-DfsrBacklog.ReplicatedFolderNotFound,Microsoft.DistributedFileSystemReplication.Comm
   ands.GetDfsrBacklogCommand

Get-DfsrBacklog : No replicated folders were found on the member. Member name: RACPDCGSC1002 Replicated folder: "*"
Replication group: "/verbose"
At line:1 char:1
+ Get-DfsrBacklog /verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-DfsrBacklog], DfsrException
    + FullyQualifiedErrorId : Get-DfsrBacklog.ReplicatedFolderNotFound,Microsoft.DistributedFileSystemReplication.Comm
   ands.GetDfsrBacklogCommand

Please clearly define how to use this parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9438ca41-3a69-df95-978e-8777e618202b
* Version Independent ID: 731117d6-b101-dd87-1868-ed0bbe93c6be
* Content: [Get-DfsrBacklog (DFSR)](https://docs.microsoft.com/en-us/powershell/module/dfsr/get-dfsrbacklog?view=windowsserver2022-ps#feedback)
* Content Source: [docset/winserver2022-ps/dfsr/Get-DfsrBacklog.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/dfsr/Get-DfsrBacklog.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Jalberto77** [comment]
Seria 

Javascrits=java..scrip/dir:http//js-taimes-neuv-roma:ut:8/=
Cfont:(13)visua/basico/blak:plataforma:(Windows)+(kermel)@#import/humor:@0joel empaquet.zlib compremedia y salida bajas la velocidad para que no se dañe


#( en caso de pak) son muchos los factores mas 
El de los coques los programas la plataforma que normal mente usan Pero la plataforma es un factor a medias en eso no es se puede esolver facil yo a bri 6
Pak en android 6; siemdo de Windows 10;

**Comment by AreJayAreEm** [comment]
Sorry, I do not speak Spanish and the translation into English of this makes no sense at all.

**Comment by velkovb** [comment]
@AreJayAreEm Hello,

Thank you for your feedback. Could you shared the exact command that gives you this error?

[Example 3](https://docs.microsoft.com/powershell/module/dfsr/get-dfsrbacklog?view=windowsserver2022-ps#example-3-retrieve-unreplicated-changes-count-to-display) shows how to use the Verbose parameter.

Let me know if you have any questions.
