### ISSUE TITLE
Default Set Name Parameter Incorrect

### ISSUE THREAD

**Issue by CBelford** [MicrosoftDocs/windows-powershell-docs#286]
In the "Documentation" section is, 

> To specify a new default quick mode cryptographic set, run this cmdlet to specify the default set with the Name parameter value set to {E5A5D32A-4BCE-4e4d-B07F-4AB1BA7E5FE1}.

I think this is a copy/paste error from the Rename-NetIPsecMainModeCryptoSet documentation.  The name for the Quick Mode cryptographic set is E5A5D32A-4BCE-4E4D-B07F-4AB1BA7E5FE2 (ends with "2").

See https://msdn.microsoft.com/en-us/library/ff720028.aspx, or run Get-NetIPsecQuickModeCryptoSet after configuring Windows Firewall &gt; Properties &gt; IPsec Settings &gt; IPsec Defaults &gt; Customize &gt; Data Protection (Quick Mode) to have "Advanced" selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8485af2d-82eb-030c-9609-0d1b16bb9a65
* Version Independent ID: 654a2e12-ab79-14d8-2864-67f8e8115483
* Content: [Rename-NetIPsecQuickModeCryptoSet (netsecurity)](https://docs.microsoft.com/en-us/powershell/module/netsecurity/rename-netipsecquickmodecryptoset?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/netsecurity/Rename-NetIPsecQuickModeCryptoSet.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/netsecurity/Rename-NetIPsecQuickModeCryptoSet.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@kenwith There is a new PR available for the issue #746

**Comment by e0i** [comment]
@officedocsbot close
