### ISSUE TITLE
LockedOut peoperty in Get-ADUser response

### ISSUE THREAD

**Issue by hmble2** [MicrosoftDocs/windows-powershell-docs#2864]
Hi, trying to find out exact logic of how Get-ADUser command calculates property 'LockedOut' (this attribute is not available when I query AD through LDAP so I assume Get-ADUser calculates it somehow). I was relying on lockoutTime however it seems even if the user is unlocked, lockedTime is not reset until and unless lockedout user logs back into the system after unlock. I am creating a service (Java based) that would indicate whether or not an specific user is locked out or not. Please help with the logic on how to accurately determine in realtime whether an account is locked or not. @tiburd  @denisebmsft

**Comment by get-itips** [comment]
Hello @hmble2 have a look at this article https://docs.microsoft.com/en-us/windows/win32/adschema/a-lockouttime especially the remarks section.
