### ISSUE TITLE
Module missing on Windows Server 2022, Windows 10 and Windows 11?

### ISSUE THREAD

**Issue by ward-horsfall** [MicrosoftDocs/windows-powershell-docs#2865]
Hi,

I am trying to install and utilize the VPN client can you provide the steps to install this module.

It seems that Install-Module does not work. I also tried downloading the latest version of PowerShell and no luck.

I am sure there is something I am missing here.

Even better if these were just integrated within Windows 10, 11 and Server 2022. So user does not need to install

Thanks,

Ward

**Comment by velkovb** [comment]
@ward-horsfall Hello,

Could you provide a link to the module documentation that you are trying to use?
