### ISSUE TITLE
Add-NetIPHttpsCertBinding added information

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windows-powershell-docs#2869]
I think it would be useful to mention in the documentation that with the WebAdministration module loaded, it is useful to use Get-Childitem and Remove-Item with "IIS:\SSLbindings" to get information or to remove a port binding.

Import-Module WebAdministration;

$result = Remove-Item -path IIS:\SSLbindings\$ipPort;

$result = Get-ChildItem -path IIS:\SSLbindings\*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a15eeaa-604e-1620-2927-370749151835
* Version Independent ID: ad1f5a0d-4fac-d809-f683-ebed799d70da
* Content: [Add-NetIPHttpsCertBinding (NetworkTransition)](https://docs.microsoft.com/en-us/powershell/module/networktransition/add-netiphttpscertbinding?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/networktransition/Add-NetIPHttpsCertBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/networktransition/Add-NetIPHttpsCertBinding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
Hi @Tarjei-stavanger 

Thank you for your feedback.

The idea of this module is to provide a more PowerShell native way of dealing with such tasks and it includes the cmdlets **Remove-NetIPHttpsCertBinding** and **Get-NetIPHttpsConfiguration** which have the functionality you have described.
