### ISSUE TITLE
Not mentioning when Add-NetIPHttpsCertBinding will not work

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windows-powershell-docs#2872]
Powershell version 5.1

It appears that there are issues with Add-NetIPHttpsCertBinding  which will keep it from adding a certificate binding. We really need to know the circumstances when that procedure will work or not work.

From a quick google search it appears that others have problems making  Add-NetIPHttpsCertBinding work.

I use Get-ChildItem -path IIS:\SSLbindings\*; to verify that there is no certificate bound to the port I'm trying to bind the certificate to.

The screenshot shows the command line. I just copied the line and added double quotes to make it printable.

A netsh command will have the same problem when executed in the same process, but it will still create the binding.
     SSL Certificate add failed, Error: 183
     Cannot create a file when that file already exists.

---
![PowerShell_bug](https://user-images.githubusercontent.com/82510602/152105473-df2cfc63-e15d-46ec-b1b8-4868f81c72e4.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a15eeaa-604e-1620-2927-370749151835
* Version Independent ID: ad1f5a0d-4fac-d809-f683-ebed799d70da
* Content: [Add-NetIPHttpsCertBinding (NetworkTransition)](https://docs.microsoft.com/en-us/powershell/module/networktransition/add-netiphttpscertbinding?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/networktransition/Add-NetIPHttpsCertBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/networktransition/Add-NetIPHttpsCertBinding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Tarjei-stavanger** [comment]
I have already pointed out that I have checked that there is no certificate bound to the port.

Please pay attention.

**Comment by JamesKehr** [comment]
Hei @Tarjei-stavanger, does the certificate you are using have Subject Alternate Names (SAN)?

**Comment by scanum** [comment]
@Tarjei-stavanger We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Tarjei-stavanger** [comment]
I'm pretty certain that I answered that the certificate had a Subject Alternate Name. However I might have forgotten to save the answer or it got lost somewhere. Sorry about that.

The certificate comes from Let's Encrypt and contains a Subject Alternative Name.
