### ISSUE TITLE
Command does not work with single RD Connection Broker despite what documentation says

### ISSUE THREAD

**Issue by cmc099** [MicrosoftDocs/windows-powershell-docs#2877]
Documentation states "For a deployment that includes a single Remote Desktop Connection Broker (RD Connection Broker) server, provide the fully qualified domain name (FQDN) of the RD Connection Broker server."

However when running this command on a single RD Connection Broker deployment the following error is returned:
Set-RDClientAccessName : The RD Connection Broker server is not configured for high availability.

**Comment by e0i** [comment]
Duplicate of #2878.
