### ISSUE TITLE
Command does not work with single RD Connection Broker despite what documentation says

### ISSUE THREAD

**Issue by cmc099** [MicrosoftDocs/windows-powershell-docs#2878]
Documentation states "For a deployment that includes a single Remote Desktop Connection Broker (RD Connection Broker) server, provide the fully qualified domain name (FQDN) of the RD Connection Broker server."

However when running this command on a single RD Connection Broker deployment the following error is returned:
Set-RDClientAccessName : The RD Connection Broker server is not configured for high availability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ae6517-7ba8-779a-1b91-edbd8ba8eb43
* Version Independent ID: 79a770ba-46a6-7916-8094-aa8677f18654
* Content: [Set-RDClientAccessName (RDMgmt)](https://docs.microsoft.com/en-us/powershell/module/rdmgmt/set-rdclientaccessname?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/rdmgmt/Set-RDClientAccessName.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/rdmgmt/Set-RDClientAccessName.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@cmc099 Thank you for your feedback.

We have confirmed the behavior and will escalate this.
