### ISSUE TITLE
Issue with " -AuthenticationType"

### ISSUE THREAD

**Issue by bharath993** [MicrosoftDocs/windows-powershell-docs#288]
Hi Guys,
          In the help of the Connect-IscsiTarget command it says the options for the -AuthenticationType are None, OneWayCHAP and MutualCHAP . However the type must be specified in all uppercase for it to work and will just error out saying authentication failure rather than telling you the parameter is incorrect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b37c8a20-08fd-66d2-38a8-04991ca5b814
* Version Independent ID: 9e898c18-a931-3b6f-a373-bb93242c0efe
* Content: [Connect-IscsiTarget (iscsi)](https://docs.microsoft.com/en-us/powershell/module/iscsi/connect-iscsitarget?view=win10-ps)
* Content Source: [docset/windows/iscsi/connect-iscsitarget.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/iscsi/connect-iscsitarget.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@AndreaBarr Please have the PR #932 for this issue reviewed. Thanks.

**Comment by e0i** [comment]
@bharath993 Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
