### ISSUE TITLE
Remove-AppxPackage

### ISSUE THREAD

**Issue by cccsss01** [MicrosoftDocs/windows-powershell-docs#2881]
I find that remove-appxpackage fullpackagename -user SID doesn't actually remove the product. When running as system or admin

For OS 20H2, Powershell 5.1.19041.1320

[Enter feedback here]

$appx = get-ciminstance Win32_installedStoreProgram | where {($_.Name
-like "*OfficeHub*")}$
for ($i=0; $i -lt $appx.PackageUserInformation.UserSecurityID.sid.length; $i++) { if ($appx[$i].Version -lt
"18.2106.12410.0") {remove-ciminstance -inputObject $appx[$i]}}

--or--

$appxHEIF = get-appxpackage Microsoft.HEIF* -allusers | where {$_.Version -lt
"1.0.32532.0"}
for ($i=0;$i -lt $appxHEIF.PackageUserInformation.UserSecurityId.sid.length; $i++) {
$appxHEIF.PackageUserInformation.UserSecurityID.sid.length; $i++) {
remove-appxpackage $AppxHEIF.PackageFullName -user
$appxHEIF.PackageUserInformation.UserSecurityID.sid[$i]

}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516dd39c-0d3a-3f7b-1075-2a22a95509a8
* Version Independent ID: 914c97a9-7dc2-6ddd-4756-7ec210db3fe8
* Content: [Remove-AppxPackage (Appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=windowsserver2022-ps#feedback)
* Content Source: [docset/winserver2022-ps/appx/Remove-AppxPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/appx/Remove-AppxPackage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by arjunbalip** [comment]
Below scripts format work for me in powershell to remove package from another user but its not working on C# 

other script working fine in c# like get all package , remove package for all user , I run the visual studio as Admin

after running script from powershell its work fine
after running script from c# application status updated as 'NeedsRemediation'

I am writing this in WPF application

There is no error or bug in code its just executed without error but app state not change


Format
```powershell
Get-AppxPackage -User SID | Where PackageFullName -eq packagefullname | Remove-AppxPackage -User

Remove-AppxPackage -Package packagefullname -User SID
```

script
```powershell
Get-AppxPackage -User S-1-5-21-1982064058-2852822003-722279830-1009 | Where PackageFullName -eq FACEBOOK.FACEBOOK_2021.927.1.0_neutral__8xx8rvfyw5nnt | Remove-AppxPackage -User S-1-5-21-1982064058-2852822003-722279830-1009

Remove-AppxPackage -Package 5319275A.WhatsAppDesktop_2.2216.8.0_x64__cv1g1gvanyjgm -User S-1-5-21-1982064058-2852822003-722279830-1009

```

C#
```c#
using (PowerShell PowerShellInst = PowerShell.Create())
{
    PowerShellInst.AddScript(removeCommand, false);
    var PSOutput = PowerShellInst.Invoke();
    if (PowerShellInst.Streams.Error.Count > 0)
    {
    }
}
```

**Comment by arjunbalip** [comment]
@velkovb 
Now I am facing very wired issue with PowerShell , above script working fine with install appx packages and paint but when I try to remove calculator from specific user its not removing in first attempt I need to execute same query twice for same 

like I execute query then restart machine and again then execute query then remove the calculator
