### ISSUE TITLE
-Server option: add port

### ISSUE THREAD

**Issue by fidfbonanno** [MicrosoftDocs/windows-powershell-docs#2884]
The page syas that with the "-Server" i can put "_Fully qualified directory server name and port_", but how? I need an example, because "`server:port`" and "`server port`" don't work.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f224958-1e01-e762-a552-6116c76a04e7
* Version Independent ID: b013a1e2-5879-5924-9dbd-a8db54885d10
* Content: [Get-ADUser (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/activedirectory/Get-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/activedirectory/Get-ADUser.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
@fidfbonanno 
Hello and thank you for your feedback.

Example 4 show how to specify the port and I have just tested this syntax and it worked on my side.
```powershell
Get-ADUser -Filter * -Server dc01:389
```
