### ISSUE TITLE
No Property Parameter

### ISSUE THREAD

**Issue by randy1200** [MicrosoftDocs/windows-powershell-docs#289]
If you type example 2 at a PowerShell prompt on Windows Server 2016, you get the following error:
Get-WebConfigurationProperty : A parameter cannot be found that matches parameter name 'Property'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87e7042-ffb8-c7ec-8b1e-3edf4c5325d6
* Version Independent ID: 6f865835-b34c-ac28-0118-1f60a9c7a945
* Content: [Get-WebConfigurationProperty (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/get-webconfigurationproperty?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/Get-WebConfigurationProperty.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/Get-WebConfigurationProperty.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
Hello, @randy1200 Thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
