### ISSUE TITLE
LDAP of -Office

### ISSUE THREAD

**Issue by rbreton** [MicrosoftDocs/windows-powershell-docs#2890]
It the section -Office, the LDAP display name is note "office" but "physicalDeliveryOfficeName"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b429becd-35bd-e4ad-f970-ad6a51efd01a
* Version Independent ID: 5f3c184f-42bd-176e-5764-5411c3227c6e
* Content: [New-ADUser (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-aduser?view=windowsserver2022-ps#syntax)
* Content Source: [docset/winserver2022-ps/activedirectory/New-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/activedirectory/New-ADUser.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@rbreton Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3196

Once the author approves, the changes will be live.

THanks
Sri
