### ISSUE TITLE
Sample command does not work in WS 2016

### ISSUE THREAD

**Issue by JBarreraMS** [MicrosoftDocs/windows-powershell-docs#2891]
[Enter feedback here]

Hello!

The sample command to retrieve user data does not work as it is in the article, as per the documentation I attempted a different approach and that did work:

Doesn't work:

- user@domain
- user

Does work:

- Domain\user

The example states:

Get-SyncUserStatus -User "User01" -SyncShare "Share01"

Which might confuse some users. 

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca44a0b6-f726-793c-36e5-62294fc214b7
* Version Independent ID: 0fa963e1-a5aa-7309-fc37-093999c6dff5
* Content: [Get-SyncUserStatus (SyncShare)](https://docs.microsoft.com/en-us/powershell/module/syncshare/get-syncuserstatus?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/syncshare/Get-SyncUserStatus.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/syncshare/Get-SyncUserStatus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
