### ISSUE TITLE
migrate driver example is invalid

### ISSUE THREAD

**Issue by lachlann562** [MicrosoftDocs/windows-powershell-docs#2892]
The migrate sample code initializes a variable $dsnArray however it loops on a variable $dsnArr, since this variable was not initialized the rest of the code doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1a60eb-a37d-8b59-5b67-fa4bde46cb17
* Version Independent ID: c67b845b-c7d3-d084-52ba-154f7ddb4ab2
* Content: [Add-OdbcDsn (Wdac)](https://docs.microsoft.com/en-us/powershell/module/wdac/add-odbcdsn?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/wdac/Add-OdbcDsn.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/wdac/Add-OdbcDsn.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@lachlann562 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3195

Once the author approves, the changes will be live.

Thanks
Sri
