### ISSUE TITLE
OK, so how do I install WebAdministration module? Where do I get it?

### ISSUE THREAD

**Issue by dataflownow** [MicrosoftDocs/windows-powershell-docs#2894]
OK, so how do I install WebAdministration module? Where do I get it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ff5afdb-4e5e-ded3-b40b-96941ae19557
* Version Independent ID: 976f34b0-b757-700a-38f5-abc4e1a6a54b
* Content: [WebAdministration Module](https://docs.microsoft.com/en-us/powershell/module/webadministration/?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/webadministration/WebAdministration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2019-ps/webadministration/WebAdministration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
