### ISSUE TITLE
Hello - I am trying to find the documentation on: Set-NetAdapterSriov -Name "Ethernet 2" -NumVFs 31 -VPorts 64 -NumQueuePairsForDefaultVPort 2 -NumQueuePairsForNonDefaultVPort 2

### ISSUE THREAD

**Issue by n8botelho** [MicrosoftDocs/windows-powershell-docs#2897]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c560bf7d-43a4-03ef-ad1a-69b284dfeb97
* Version Independent ID: 8b3f3d52-e71b-f01b-7ee8-569041207b20
* Content: [Set-NetAdapterSriov (NetAdapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/set-netadaptersriov?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/netadapter/Set-NetAdapterSriov.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/netadapter/Set-NetAdapterSriov.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
