### ISSUE TITLE
How About Testing Load Balancers

### ISSUE THREAD

**Issue by MarkAllenPhillips** [MicrosoftDocs/windows-powershell-docs#2899]
What can be used to test Load Balancers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f33c79b-283d-cda6-c4c0-904cc365fdea
* Version Independent ID: 563d7048-b46e-c459-168c-ff2aa028a0d1
* Content: [Get-TlsCipherSuite (TLS)](https://docs.microsoft.com/en-us/powershell/module/tls/get-tlsciphersuite?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/tls/Get-TlsCipherSuite.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/tls/Get-TlsCipherSuite.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
