### ISSUE TITLE
Resume-VMReplication not working on Win2016

### ISSUE THREAD

**Issue by bithost** [MicrosoftDocs/windows-powershell-docs#290]
Hello, 
  I have:
2 x HP DL360 Gen10 both running Windows Server 2016 Standart in Hyper-v Cluster. I have installed Azure Site recovery provider on both machines. 
Now i want to create a script which will suspend VM replication to Azure. So i do like this:
`Suspend-VMReplication -VMName VM01`
And this works. Now i want to enable replication back again:
`Resume-VMReplication -VMName VM01` 
And this time i get this: 

> Resume-VMReplication : Hyper-V encountered an error trying to access an object on computer 'server01' because the object was not found. The object might have been deleted, or you might not have permission
> to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
> At line:1 char:1
>  Resume-VMReplication -VMName VM01
>  CategoryInfo          : ObjectNotFound: (:) [Resume-VMReplication], VirtualizationException
> FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.ResumeVMReplication

I tried running: 

> mofcomp  %systemroot%\system32\WindowsVirtualization.v2.mof
> mofcomp %systemroot%\system32\en-US\WindowsVirtualization.v2.mfl 

Nothing changed. I just installed Windows on my machines, so it is clean OS with only Hyper-V, FailoverCluster and Azure Site Recovery provider.

What i should try to make that cmdlet to work?

Thanks,  
  Tadas

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@bithost Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. 
https://docs.microsoft.com/powershell/#pivot=main&panel=community

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
