### ISSUE TITLE
Example 2 uses -VPorts parameter that does not exist

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/windows-powershell-docs#2903]
Example 2 

```
Set-NetAdapterSriov -Name "Ethernet 2" -NumVFs 31 -VPorts 64 -NumQueuePairsForDefaultVPort 2 -NumQueuePairsForNonDefaultVPort 2
```

The **VPorts** parameter does not exist for this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c560bf7d-43a4-03ef-ad1a-69b284dfeb97
* Version Independent ID: 8b3f3d52-e71b-f01b-7ee8-569041207b20
* Content: [Set-NetAdapterSriov (NetAdapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/set-netadaptersriov?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/netadapter/Set-NetAdapterSriov.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/netadapter/Set-NetAdapterSriov.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@scanum This can be closed.
