### ISSUE TITLE
LogLevel options are incorrect

### ISSUE THREAD

**Issue by edwardg-MSFT** [MicrosoftDocs/windows-powershell-docs#291]
The "accepted values" list in the parameter description lists four options; only three are valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becc68a9-a1af-212a-af7b-ca89dea4c23e
* Version Independent ID: 3e786ce6-7640-2ec3-d5d4-1b2b0549476d
* Content: [New-WindowsImage (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/new-windowsimage?view=win10-ps)
* Content Source: [docset/windows/dism/new-windowsimage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/new-windowsimage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith Please merge this PR, if you find it suitable

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @edwardg-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
