### ISSUE TITLE
Please redirect to the Mount-DiskImage command for when Hyper-V is not available

### ISSUE THREAD

**Issue by ilias-selfhost** [MicrosoftDocs/windows-powershell-docs#292]
Hello,
These commandlets are great, but they come with Hyper-V feature. Having to install Hyper-V to manage virtual disks is not always possible. It would not be an option in a production environment that does not have Hyper-V deployed already, or on WinPE. Mount-DiskImage commands can do the trick, but they are less discoverable because they don't mention VHD by name. It would have been tremendously helpful if this page would mention their existence.
Thanks,
ilia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcb5998-ffb1-3a68-95f2-4ca26db9e4d5
* Version Independent ID: 7c54bbd8-d0d2-685b-ade9-40d51d07a300
* Content: [Mount-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/mount-vhd?view=win10-ps)
* Content Source: [docset/windows/hyper-v/mount-vhd.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/mount-vhd.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by ScotiaBaker** [comment]
Concur.  The existence of the *-VHD cmdlets leads people to using (or trying to use) those cmdlets even when the *-DiskImage cmdlets are more appropriate.  Please cross-reference the cmdlets in their documentation so people are aware of both and choose appropriately.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by PCNerd2001** [comment]
The below command will mount a vhd/vhdx and assign a specific drive letter using PowerShell.

#Set the F Drive
$Volumes_VHDX = Mount-VHD -Path "C:\My_Disk2.vhdx" -PassThru | Get-Disk | Get-Partition | Get-Volume | Select-Object DriveLetter

Set-Partition -DriveLetter $Volumes_VHDX.DriveLetter -NewDriveLetter F -Confirm:$false -ErrorAction SilentlyContinue

**Comment by dariomws306** [comment]
Hi @ilias-selfhost, thank you for your feedback.

I am adding Mount-DiskImage under Related Notes.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @ilias-selfhost Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
