### ISSUE TITLE
Hyper-V commands missing

### ISSUE THREAD

**Issue by Ammar-AlDabbagh** [MicrosoftDocs/windows-powershell-docs#2925]
No information about:

```
Add-VMGpuPartitionAdapter

Get-VMGpuPartitionAdapter

Remove-VMGpuPartitionAdapter
```

**Comment by msbemba** [comment]
@Ammar-AlDabbagh Thank you for your feedback. 

The below links take you to the documents you are looking for

https://learn.microsoft.com/en-us/powershell/module/hyper-v/add-vmgpupartitionadapter?view=windowsserver2022-ps

https://learn.microsoft.com/en-us/powershell/module/hyper-v/get-vmgpupartitionadapter?view=windowsserver2022-ps

https://learn.microsoft.com/en-us/powershell/module/hyper-v/remove-vmgpupartitionadapter?view=windowsserver2022-ps

Hope this helps!

Thanks
Sri

**Comment by Ammar-AlDabbagh** [comment]
Thanks. I hope it's fine to ask this under this issue, but ever since I'd added the GPU partition to a VM, I could never get the system to fully revert. Though everything works as intended, even after using `Remove-VMGpuPartitionAdapter` and fully uninstalling Hyper-V, task manager still displays that the GPU VRAM is split. 

![image](https://github.com/MicrosoftDocs/windows-powershell-docs/assets/94621418/c6a34792-ff02-4e6f-b4bd-1e9c5d85114c)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
