### ISSUE TITLE
Keywords missing at -RemoteAddress Parameter

### ISSUE THREAD

**Issue by tgusset** [MicrosoftDocs/windows-powershell-docs#293]
Parameter -RemoteAddress accepts also keywords like LocalSubnet, DNS, DHCP, ...
These keywords are missing in the docu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a81ceb77-8de5-8c07-c0c4-fa3d616d859f
* Version Independent ID: 736dd392-788a-c102-dfcb-29a08c2c9f9d
* Content: [New-NetFirewallRule (netsecurity)](https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps)
* Content Source: [docset/windows/netsecurity/new-netfirewallrule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netsecurity/new-netfirewallrule.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot close
