### ISSUE TITLE
What {text} means in provided samples?

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/windows-powershell-docs#2936]
The article mentions `{text}` many times, e.g.:

> New-SelfSignedCertificate -Type Custom -Subject "E=patti.fuller@contoso.com,CN=Patti Fuller" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.4","2.5.29.17={text}email=patti.fuller@contoso.com&upn=pattifuller@contoso.com") -KeyAlgorithm RSA -KeyLength 2048 -SmimeCapabilities -CertStoreLocation "Cert:\CurrentUser\My"

or

> Policy Mapping 2.5.29.33={text}oid=oid&oid=oid…

What does it mean? Is this a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cc6356-761f-c845-6ccb-8fd12b1dc7ba
* Version Independent ID: 08045f21-38f3-4c0a-bbeb-c51cdb6615e8
* Content: [New-SelfSignedCertificate (pki)](https://docs.microsoft.com/en-us/powershell/module/pki/new-selfsignedcertificate?view=windowsserver2022-ps#example-5=)
* Content Source: [docset/winserver2022-ps/pki/New-SelfSignedCertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/pki/New-SelfSignedCertificate.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by abatishchev** [comment]
@dingmeng-xue do you know someone form the technical writers side who could take a look at this issue, please?

**Comment by dingmeng-xue** [comment]
No idea to this module. You can contact [JasonGerend](https://github.com/JasonGerend) or [sdwheeler](https://github.com/MicrosoftDocs/windows-powershell-docs/commits?author=sdwheeler) according to the history of that page.

**Comment by abatishchev** [comment]
@sdwheeler can you please take a look at this issue? Or add someone who might be able to,

**Comment by abatishchev** [comment]
Adding @alradmsft and @PhilHallin.

**Comment by sdwheeler** [comment]
Although not standard PKI, this syntax has its roots from pre-PowerShell PKI admin tools that come with Windows so would be familiar to our customers. 

```
C:\Users\alrad>certreq.exe -new -?
Usage: removing a bunch of stuff for brevity… 

[NewRequest]
...

[Extensions]
    2.5.29.17 = "{text}"        ; Subject Alternative Name/2.5.29.18: Issuer Alternative Name
    _continue_ = [UPN=User@Domain.com&](mailto:UPN=User@Domain.com&)
    _continue_ = [EMail=User@Domain.com&](mailto:EMail=User@Domain.com&)
    _continue_ = "DNS=Machine.Domain.com&"
    _continue_ = "DirectoryName=CN=Name,DC=Domain,DC=com&"
    _continue_ = "URL=http://Machine.Domain.com/default.html&"
    _continue_ = "IPAddress=10.0.0.1&"
    _continue_ = "RegisteredId=1.2.3...4.5&"
    _continue_ = "1.2.3...4.6.1={utf8}String&"
    _continue_ = "1.2.3...4.6.2={octet}AAECAwQFBgc=&"
    _continue_ = "1.2.3...4.6.2={octet}{hex}00 01 02 03 04 05 06 07&"
    _continue_ = "1.2.3...4.6.3={asn}BAgAAQIDBAUGBw==&"
    _continue_ = "1.2.3...4.6.3={hex}04 08 00 01 02 03 04 05 06 07"

    2.5.29.37 = "{text}"        ; Enhanced Key Usage
    _continue_ = "1.3.6.1.5.5.7.3.2,"
    _continue_ = "1.3.6.1.5.5.7.3.1"

    2.5.29.19 = "{text}ca=0&pathlength=3"       ; Basic Constraints
    Critical = 2.5.29.19
```

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
