### ISSUE TITLE
Get-DfsnFolder: parameter "-Path" "Accept wildcard characters" should be changed to "true"

### ISSUE THREAD

**Issue by Boilerplate4u** [MicrosoftDocs/windows-powershell-docs#2937]
"**Get-DfsnFolder**" parameter "**-Path**" "Accept wildcard characters" should be changed to "**true**" as shown in example 2: `PS C:\> Get-DfsnFolder -Path "\\Contoso\AccountingResources\*"`
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dfd24fc-c865-48b6-cb62-1b8ff618d540
* Version Independent ID: ff2577ab-056a-e855-034f-b77a8228eb94
* Content: [Get-DfsnFolder (DFSN)](https://docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnfolder?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/dfsn/Get-DfsnFolder.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/dfsn/Get-DfsnFolder.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Boilerplate4u Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3217

Once the author approves, the changes will be live.

Thanks
Sri
