### ISSUE TITLE
Backwards

### ISSUE THREAD

**Issue by bjessie** [MicrosoftDocs/windows-powershell-docs#294]
Regarding DisableRealtimeMonitoring and many others, this document states setting it to $true enables monitoring, which is backwards from actual behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbad993c-9f2b-9f51-6438-b56cd913ba1b
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (defender)](https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=win10-ps)
* Content Source: [docset/windows/defender/set-mppreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/set-mppreference.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @bjessie , thank you for your feedback.

Updates to this article are coming in the next days to fix these issues.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @bjessie Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
