### ISSUE TITLE
get-apppackagemanifest : 指定されたファイルが見つかりません。 (HRESULT からの例外:0x80070002)

### ISSUE THREAD

**Issue by me-oct** [MicrosoftDocs/windows-powershell-docs#2940]
I have got an error on  execution of Get-AppPackageManifest for the some specified apps.
For example,
~~~
PS C:\WINDOWS\system32> get-apppackagemanifest -Package Microsoft.VCLibs.140.00.UWPDesktop_14.0.27323.0_x64__8wekyb3d8bbwe
get-apppackagemanifest : 指定されたファイルが見つかりません。 (HRESULT からの例外:0x80070002)
発生場所 行:1 文字:1
+ get-apppackagemanifest -Package Microsoft.VCLibs.140.00.UWPDesktop_14 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AppxPackageManifest], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Windows.Appx.PackageManager.Commands.GetAppxPackageManifestCommand
~~~
I wonder what is the problem with this commandlet.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3deefd92-ef3d-986a-f8d3-347444975207
* Version Independent ID: 5ad15ccc-9880-d971-c7c0-e5ef9f8d9f5a
* Content: [Get-AppxPackageManifest (Appx)](https://docs.microsoft.com/ja-jp/powershell/module/appx/get-appxpackagemanifest?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/appx/Get-AppxPackageManifest.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2019-ps/appx/Get-AppxPackageManifest.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by me-oct** [comment]
I found that the error cases have the empty 'InstallLocation' property.
Are they normal cases or caused by the UWP uninstaller' bug?

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
