### ISSUE TITLE
Trusted Platform Module Technology Overview does not work

### ISSUE THREAD

**Issue by Gunock** [MicrosoftDocs/windows-powershell-docs#2943]
`Trusted Platform Module Technology Overview` link does not work for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cf0c159-2686-71a9-aae0-a471f9c52712
* Version Independent ID: 5b1a9309-8949-60d6-9424-4237dbe53af1
* Content: [Disable-TpmAutoProvisioning (TrustedPlatformModule)](https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/disable-tpmautoprovisioning?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/trustedplatformmodule/Disable-TpmAutoProvisioning.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/trustedplatformmodule/Disable-TpmAutoProvisioning.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Gunock Thank you for your feedback. The link works now.

@scanum  This can be closed.

Thanks
Sri

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
