### ISSUE TITLE
Get-MpComputerStatus unexpected behavior.

### ISSUE THREAD

**Issue by jvinterberg** [MicrosoftDocs/windows-powershell-docs#2945]
I and other fellow colleagues are experiencing that our PowerShell session unexpected closes the running sessions when we execute "Get-MpComputerStatus" I don't see that behavior being described in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b1d3d6-3f25-abb8-3d58-dd3481203100
* Version Independent ID: 192ecac7-fbc7-24e4-43c7-163550e211fa
* Content: [Get-MpComputerStatus (Defender)](https://docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus?view=windowsserver2022-ps#feedback)
* Content Source: [docset/winserver2022-ps/defender/Get-MpComputerStatus.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/defender/Get-MpComputerStatus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@jvinterberg , No issues with  this  **Get-MpComputerStatus** on windows 11.

**Comment by msbemba** [comment]
@jvinterberg Thank you for your feedback. We have tested it in multiple test machines and there is no unexpected timeout. If this continues to be a problem, I'd recommend you contact support for further assistance.

Hope this helps!

Thanks
Sri

**Comment by jvinterberg** [comment]
My sincere and late apologies, we found that it was eliminated by a 3rd party security tool "Cylance" only found out as our security department asked why i kept generating logs for this.

**Comment by scanum** [comment]
Thanks for getting back to us, closing this issue as resolved.
