### ISSUE TITLE
Bugs for Private Key

### ISSUE THREAD

**Issue by Melbit-haixingzhang** [MicrosoftDocs/windows-powershell-docs#295]
Private Key is missing if running with this PS command. Workaround is to use certutil to import. The link below also reported this issue: https://social.technet.microsoft.com/Forums/en-US/ea287f42-8a17-4c76-be41-61d66f645a63/bug-in-ps-importpfxcertificate-verify?forum=winserverpowershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f36c4f79-411b-f859-7488-456b65e61e73
* Version Independent ID: 9a5652dd-c33c-a658-9ee1-3af47189136a
* Content: [Import-PfxCertificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-pfxcertificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/import-pfxcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/import-pfxcertificate.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by pilcherd** [comment]
I have discovered this too.  The Private Key is not imported.

**Comment by mgreschl** [comment]
This bug is interesting because mmc shows the certificate and private key but using powershell to retrieve the private key does not work. Importing the same certificate through certutil allows the private key to be retrieved through powershell.

**Comment by anthonyangel** [comment]
I'm having an issue where import-pfx is working when I run it whilst creating an image (i.e. immediately after running it I can verify that I can access the private key), but once the machine is sysprepped I can't access the key.

I'm pretty sure that this isn't just a permission issue, as I tested by setting the ACL's on the cert & key pre-imaging to include the Administrators group and got the same. It also happened when I checked on the post-image machine as the SYSTEM user

**Comment by Sikkesoft** [comment]
Import-PfxCertificate imports the key in a CNG-store, which requires different code to access the key. 
This is not visible in the MMC, when running 'certutil -user -store "MY"  <thumbprint>' you will see in the output:   'Provider = Microsoft Software Key Storage Provider'; which is a CNG-store.

**Comment by SykieChen** [comment]
Use the following method instead
``` powershell
# import new cert
$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
$cert.Import("PATH_OF_CERT", "PASSWORD_OF_CERT", [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]"PersistKeySet")
$store = New-object System.Security.Cryptography.X509Certificates.X509Store -argumentlist "MY", LocalMachine
$store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::"ReadWrite")
$store.Add($cert)
$store.Close()
```

**Comment by e0i** [comment]
@Melbit-haixingzhang Would you confirm that the response provided by @SykieChen answers your question? Thanks.

**Comment by e0i** [comment]
@Melbit-haixingzhang 

We are closing this issue as there hasn't been a response from your side.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
