### ISSUE TITLE
Give Examples

### ISSUE THREAD

**Issue by trboomer** [MicrosoftDocs/windows-powershell-docs#2953]
Give examples please. I am wasting my time trying to figure this out . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d389b383-b784-53af-872a-823200f547e0
* Version Independent ID: 05808383-de8d-6cc6-80d2-eb19e304e3ba
* Content: [Set-VMFirmware (Hyper-V)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmfirmware?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/hyper-v/Set-VMFirmware.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/hyper-v/Set-VMFirmware.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@trboomer Thank you for your feedback. We have added three different examples to the document. 

Hope this helps!

If you are requesting a specific parameter, do open up an issue mentioning the same so we can try to add that to the document.

Thanks
Sri

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
