### ISSUE TITLE
Example is incorrect

### ISSUE THREAD

**Issue by Hugh-1901** [MicrosoftDocs/windows-powershell-docs#2954]
It definitely does not create a tier with that name!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2f57dd-f9aa-547a-69ee-0023eb832c35
* Version Independent ID: 90b2d622-393b-53d5-2ef3-0a95b4d0c578
* Content: [New-StorageTier (Storage)](https://docs.microsoft.com/en-us/powershell/module/storage/new-storagetier?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/storage/New-StorageTier.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/storage/New-StorageTier.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Hugh-1901 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3216

Once the author approves, the changes will be live.

Thanks
Sri
