### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by virag004** [MicrosoftDocs/windows-powershell-docs#297]
I wanted to change the paper size so I used the first example for it, it didn't say any error when I pressed enter but it didn't change the size of the paper on that printer, what should I do differently, somebody has any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbd437e5-03c2-aac7-0dff-8d40af430122
* Version Independent ID: 37c3187a-1411-22de-4e2a-290245a3d65d
* Content: [Set-PrintConfiguration (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/set-printconfiguration?view=win10-ps)
* Content Source: [docset/windows/printmanagement/set-printconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/printmanagement/set-printconfiguration.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by skille** [comment]
don't seem to obey color parameter when set to $false, color option is still selected / preferred.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @virag004 and @skille , thanks for your feedback.

I have tried PaperSize and Color parameters and I could change them. Could you try again?

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @virag004 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
