### ISSUE TITLE
Copy-UserInternationalSettingsToSystem

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windows-powershell-docs#2970]
[Why does this command not work for Windows Server 2022? Same family as Windows 11.] --- #### Detalhes do ⚠ documento *Não edite esta seção. É necessário para docs.microsoft.com ➟ gitHub emissão vinculando.* * ID: ccd7281a-ec32-c07a-930c-dfbcf9f30d9b * Versão ID Independente: dd1bd3bf-f9f3-3418-7197-1c910ac7185d * Conteúdo: [Copy-UserInternationalSettingsToSystem (International)](https://docs.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem?view=windowsserver2022-ps) * Fonte de conteúdo:  [docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md] (https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md) * Produto: **w11** * Tecnologia: **** * GitHub Login: @erik0686 * Microsoft Alias: **ertorres**

**Comment by gabrielluizbh** [comment]
![image](https://user-images.githubusercontent.com/31531703/167986880-2e942536-ad90-4ce5-91c3-9e4f8a433fd8.png)

**Comment by telvgehc** [comment]
Does not work here.

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
