### ISSUE TITLE
Examples: Example 1 incorrect

### ISSUE THREAD

**Issue by BinaryInk** [MicrosoftDocs/windows-powershell-docs#298]
Code sample should be

PS C:\&gt; $BLV = Get-BitLockerVolume -MountPoint "C:"
Remove-BitlockerKeyProtector -MountPoint "C:" -KeyProtectorId $BLV.KeyProtector[1].KeyProtectorId

The property has to be explicitly identified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4237511d-d058-4fe6-5361-356102f96f73
* Version Independent ID: e4bce7f9-9c6a-da21-45b3-d664b2a9584c
* Content: [Remove-BitLockerKeyProtector (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/remove-bitlockerkeyprotector?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/bitlocker/Remove-BitLockerKeyProtector.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/bitlocker/Remove-BitLockerKeyProtector.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@BinaryInk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
