### ISSUE TITLE
Examples conflict with parameter -SizeBytes

### ISSUE THREAD

**Issue by bogdantomasciuc** [MicrosoftDocs/windows-powershell-docs#2980]
[Enter feedback here]

In the documentation the parameter -Size is used and in the examples -SizeBytes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155844ca-89aa-e073-23ab-26a29ca01a24
* Version Independent ID: 36e22e21-2784-7ec2-b8b4-57d065a71f27
* Content: [New-IscsiVirtualDisk (IscsiTarget)](https://docs.microsoft.com/en-us/powershell/module/iscsitarget/new-iscsivirtualdisk?view=windowsserver2016-ps)
* Content Source: [docset/winserver2016-ps/iscsitarget/New-IscsiVirtualDisk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2016-ps/iscsitarget/New-IscsiVirtualDisk.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@bogdantomasciuc Thank you for your feedback. Size is an alias for Sizebytes and can be used when you mention the values in MB or GB. We have added it as Alias to the document.

Hope this helps!

Thanks
Sri

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by bogdantomasciuc** [comment]
Yes. It was resolved. Thank you for clarifying the docs!
