### ISSUE TITLE
Identitcal description for two different attributes

### ISSUE THREAD

**Issue by FlorentATo** [MicrosoftDocs/windows-powershell-docs#2982]
Hello,
the description for both `-AutoReusePortRangeNumberOfPorts` and `-AutoReusePortRangeStartPort` is identical. I believe the description for `-AutoReusePortRangeStartPort` is incorrect and should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e593bd-4eaa-6497-ae1d-3ca113a4f768
* Version Independent ID: 9f4845b0-2bf6-b031-971f-26977651b527
* Content: [Set-NetTCPSetting (NetTCPIP)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/set-nettcpsetting?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/nettcpip/Set-NetTCPSetting.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/nettcpip/Set-NetTCPSetting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@FlorentATo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3197

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by FlorentATo** [comment]
Merged by @tiburd, thank you to everyone involved 👍
