### ISSUE TITLE
Typo in Example

### ISSUE THREAD

**Issue by sreekumarr84** [MicrosoftDocs/windows-powershell-docs#299]
Example2 mentions -DependencyPath where as the command takes -DependencyPackagePath

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f91ac99-18af-f5ab-47c0-6ab193f8a99d
* Version Independent ID: f077a336-dd7b-bcc5-a95c-451b3c9dd0d2
* Content: [Add-AppxProvisionedPackage (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/add-appxprovisionedpackage?view=win10-ps)
* Content Source: [docset/windows/dism/add-appxprovisionedpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/add-appxprovisionedpackage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Malind19** [comment]
Created Pull Request
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/868

**Comment by e0i** [comment]
@officedocsbot close
