### ISSUE TITLE
-DateTime parameter not usable with -PasswordExpired switch

### ISSUE THREAD

**Issue by RichMath** [MicrosoftDocs/windows-powershell-docs#2992]
The description of the -DateTime parameter states "Specifies a distinct time value for Search-ADAccount parameters such as AccountExpiring, AccountInactive, and **PasswordExpired**." However, the -DateTime parameter is not part of the same parameter set as the -PasswordExpired switch. Attempting to use -DateTime results in the error "Search-ADAccount : Parameter set cannot be resolved using the specified named parameters."
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46db85df-847a-3114-aab6-c0fc70d4dcb5
* Version Independent ID: beea1c46-1acf-8856-48c1-36037b737b2f
* Content: [Search-ADAccount (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/search-adaccount?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/activedirectory/Search-ADAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/activedirectory/Search-ADAccount.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
