### ISSUE TITLE
Useless for all intents and purposes.

### ISSUE THREAD

**Issue by rlDawsonShaper** [MicrosoftDocs/windows-powershell-docs#300]
I understand that folks are busy, but this is possibly the least helpful help document I have ever seen. There are few explanations of any of the parameters and the "examples" are so minimal as to be useless. Can we get this fleshed out some more please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa1689cc-8dfe-b83a-5740-1f6b22f3b022
* Version Independent ID: 7abb97e3-3631-982f-4cdd-d2402d6776f9
* Content: [New-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/new-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/new-vm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/new-vm.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by sowjanya365** [comment]
Hi @rlDawsonShaper 

Thank you for reporting and making the docs better. Much appreciated. 

I think the document is updated now. Could you please go through the content now and let us know if you think we are missing anything here. Thank you!
