### ISSUE TITLE
Copy-UserInternationalSettingsToSystem : The term 'Copy-UserInternationalSettingsToSystem' is not recognized

### ISSUE THREAD

**Issue by telvgehc** [MicrosoftDocs/windows-powershell-docs#3001]
Seems like this function does not exist in powershell but it does in the documentation?

Copy-UserInternationalSettingsToSystem : The term 'Copy-UserInternationalSettingsToSystem' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ Copy-UserInternationalSettingsToSystem
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Copy-UserInternationalSettingsToSystem:String) [], CommandNotFoundExcep
   tion
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by RAJU2529** [comment]
@telvgehc Command is executed without errors.

![Screenshot 2022-07-07 213937](https://user-images.githubusercontent.com/3296790/177820652-f45a43c6-3604-4c1a-84a9-91ad201c8016.jpg)

**Comment by telvgehc** [comment]
> @telvgehc Command is executed without errors.
> 
> ![Screenshot 2022-07-07 213937](https://user-images.githubusercontent.com/3296790/177820652-f45a43c6-3604-4c1a-84a9-91ad201c8016.jpg)

Mabey this is an windows 11 feature only?

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
