### ISSUE TITLE
The parameters for the command do not match the returned values of the command

### ISSUE THREAD

**Issue by bpodfwgit** [MicrosoftDocs/windows-powershell-docs#3006]
When the command is run, it returns the Number of the Disk on the system not any UniqueId or ObjectId so when you want to filter you cannot really use anything useful. I have several IaaS systems with Windows 2019 on them and when trying to create a storage pool using managed disks you have absolutely no way to filter on drives, they have no serial#, the same FriendlyName "Msft Virtual Disk" for all of them. The only identifying parameter is Number and that is not an option in this command. If the command is to be useful it should return the values of the parameters that it expects such as ObjectId or UniqueID otherwise it fails to return any meaningful information or it should allow the use of Number which it does return.

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
