### ISSUE TITLE
Inverted logic in Windows Defender documentation

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/windows-powershell-docs#301]
In the file https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/set-mppreference.md
nearly all parameters starting with "disable" are wrong.

A parameter of "-Disable*" like e.g. "DisableRealtimeMonitoring" does cause the oposite action from what is documented there.

Executing "Set-MPPreference -DisableRealtimeMonitoring $true", will disable Realtime monitoring instead of enabling it. I just tried it with a newly installed copy of Windows Server 2016.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @agowa338, thank you for your feedback.

If you activate parameters starting with "Disable*" you will disable this feature. You activate them with $true.
If you set these paremeters to $false, it won't disable the feature.

**Comment by agowa338** [comment]
It's still inconsistent and misleading, examples:

### DisableEmailScanning
> If you specify a value of $False or do not specify a value, Windows Defender performs email scanning. If you specify a value of $True or do not specify a value, Windows Defender does not perform email scanning.

### DisableScanningNetworkFiles
> If you specify a value of $False or do not specify a value, Windows Defender scans network files. If you specify a value of $True or do not specify a value, Windows Defender does not scan network files. 

What does it do if neither $True or $False is specified? Do we have some Schrödinger cats here?

**Comment by dariomws306** [comment]
Thank you @agowa338!

Both parameters are now fixed.

**Comment by agowa338** [comment]
@dariomws306 There are more like this, I only picket these two. Can you have a look at the others too?

**Comment by dariomws306** [comment]
Hi @agowa338 ,

I have verified and I cannot see more missing. Thanks.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @agowa338 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
