### ISSUE TITLE
Couldn't Update-Help (ConfigDefender primary concern)

### ISSUE THREAD

**Issue by jat-247** [MicrosoftDocs/windows-powershell-docs#3011]
I get the following error when running Update-Help (Administrative PowerShell):

PS C:\WINDOWS\system32> Update-Help
```
Update-Help : Failed to update Help for the module(s) 'ConfigDefender, ConfigDefenderPerformance, PSReadline' with UI
culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI culture en-US. Make sure the HelpInfoUri property
in the module manifest is valid or check your network connection and then try the command again.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand
```

I stumbled upon this because I was looking into the module ConfigDefender specifically, because when trying to use PowerShell within a Visual Studio project and calling the command Get-MpPreference it throws an exception:
`"System.Management.Automation.CommandNotFoundException: The 'Get-MpPreference' command was found in the module 'ConfigDefender', but the module could not be loaded. For more information, run 'Import-Module ConfigDefender'.`

Unfortunately, I can't get any information on ConfigDefender without some help files, and google results didn't turn up much if anything. I tried running the command `Import-Module ConfigDefender` and it runs without any error, however if I try `Remove-Module ConfigDefender` I get the following error:

```
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those
modules exist in the runspace.
At line:1 char:1
+ Remove-Module ConfigDefender
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand
```

Any help/guidance would be much appreciated.

**Comment by randomxusr** [comment]
Bump.

Same issue with ConfigDefender, ConfigDefenderPerformance, HostNetworkingService, and PSReadline

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
