### ISSUE TITLE
-CertStoreLocation parameter not recognized in Powershell

### ISSUE THREAD

**Issue by kpeirce** [MicrosoftDocs/windows-powershell-docs#3013]
I am trying to use the New-SelfSignedCertificate cmdlet with the -CertStoreLocation parameter. I am using the value of "Cert:\CurrentUser\My". the error message I get back is "A parameter cannot be found that matches parameter name 'CertStoreLocation'"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cc6356-761f-c845-6ccb-8fd12b1dc7ba
* Version Independent ID: 08045f21-38f3-4c0a-bbeb-c51cdb6615e8
* Content: [New-SelfSignedCertificate (pki)](https://docs.microsoft.com/en-us/powershell/module/pki/new-selfsignedcertificate?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/pki/New-SelfSignedCertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/pki/New-SelfSignedCertificate.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
