### ISSUE TITLE
Extraneous results returned

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windows-powershell-docs#302]
When resolving SRV records (example: Resolve-DnsName -Name "_kerberos._tcp.dc._msdcs.$env:userdnsdomain" -Type SRV), the cmdlets also attempts to resolve any returned A or AAAA records and sends them to the pipeline as a separate object collection.  This breaks pretty much any attempt to sort, group, filter, or otherwise process the data.  How can we make it not return A and AAAA records for SRV queries?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afa91db9-871e-8548-6a08-9ec59fb1d678
* Version Independent ID: 8f0d8fc1-69c5-a2f1-e8c8-f61b248b6657
* Content: [Resolve-DnsName (dnsclient)](https://docs.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/dnsclient/Resolve-DnsName.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/dnsclient/Resolve-DnsName.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by finickyadmin** [comment]
You can filter on 'Section' by choosing either Answer or Additional.

Answer returns what you're expecting, such as the _Kerberos SRV records.  Additional returns information for connecting to the Answer responses, reducing the need for additional DNS queries.

Example:

$results = Resolve-DnsName '_kerberos._tcp.dc._msdcs.contoso.com' -Type SRV
$results | where Section -eq 'Answer' | ft -a
<Answer results w/ NameTarget specified - that's what correlates to the Additional info>
$results | where Section -eq 'Additional' | ft -a
< Answer results w/ IP Address information >

**Comment by jordanmills** [comment]
Yeah, you can do that, but not unnecessarily returning data that isn't requested should be a core feature.

**Comment by e0i** [comment]
Hello, @jordanmills 

Thank you for your valuable input.

Please note that the feedback form you have used is intended for content issues only.

For product feedback, consider consider creating those via [Product Feedback](https://windowsserver.uservoice.com/forums/301869-powershell) link.

Regardless, We have created a UserVoice post with your feedback regarding the issue: [Extraneous results returned with Resolve-DnsName (dnsclient)](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/37056805-extraneous-results-returned-with-resolve-dnsname) 

Thanks.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure._
