### ISSUE TITLE
Run delayed if time missed?

### ISSUE THREAD

**Issue by Crims-on** [MicrosoftDocs/windows-powershell-docs#3022]
I think it would be necessary to specify if the task still gets run ASAP if the task missed its time. For example, if I have the arguments `-Daily -At 5AM` and I start my computer at 10 AM will the task get run by then, or does it only run when the time matches?

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
