### ISSUE TITLE
Get-WindowsOptionalFeature -Online run error

### ISSUE THREAD

**Issue by shanxing2** [MicrosoftDocs/windows-powershell-docs#3033]
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online
Get-WindowsOptionalFeature : 不支持此接口
所在位置 行:1 字符: 1
+ Get-WindowsOptionalFeature -Online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand

Log from setupdiag.exe

`
Error: SetupDiag reports Optional Component installation failed to open OC Package.
Last Phase: Finalize 
Last Operation: Remove System Restore checkpoints
Package Name: Foundation
Error: 0x8007001F`

**Comment by shanxing2** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的邮件，看到之后会尽快给您回复。

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by shanxing2** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的邮件，看到之后会尽快给您回复。
