### ISSUE TITLE
Rewording of Export-VM Description

### ISSUE THREAD

**Issue by jonjunell** [MicrosoftDocs/windows-powershell-docs#3039]
I would suggest a rewrite for this paragraph:

The Export-VM cmdlet exports a virtual machine to disk. This cmdlet creates a folder at a specified location having three subfolders: Snapshots, Virtual Hard Disks, and Virtual Machines. The Snapshots and Virtual Hard Disks folders contain the snapshots of and virtual hard disks of the specified virtual machine respectively. The Virtual Machines folder contains the configuration XML of the specified virtual machine.

Changing the third sentence to read more easily:

Each of these folders contains the associated files.  The Snapshots folder contains the associated Snapshots, and the Virtual Hard Disk folder contains the specified virtual machine's virtual disks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 406f9b72-70b6-a452-e079-e1173fca02d4
* Version Independent ID: ba568860-97d9-41a7-dd41-9898665b1948
* Content: [Export-VM (Hyper-V)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/export-vm?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/hyper-v/Export-VM.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/hyper-v/Export-VM.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@jonjunell Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3527

Once the author approves, the changes will be live.

Thanks
Sri
