### ISSUE TITLE
-Force option is poorly documented

### ISSUE THREAD

**Issue by nobrassring** [MicrosoftDocs/windows-powershell-docs#304]
This document describes -Force as forcing, which is not useful. What does the command do differently when -Force is (or is not) specified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff41017e-0b1d-f23a-c828-940161f6afad
* Version Independent ID: afccc44c-a70f-669c-c6f4-01a6e12b772f
* Content: [Sync-AppvPublishingServer (appvclient)](https://docs.microsoft.com/en-us/powershell/module/appvclient/sync-appvpublishingserver?view=win10-ps)
* Content Source: [docset/windows/appvclient/sync-appvpublishingserver.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appvclient/sync-appvpublishingserver.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @nobrassring , thank you for your feedback.

I think this parameter was updated since you have published this issue. Could you check? Thanks.

**Comment by nobrassring** [comment]
If it has been changed, it is not much of an improvement. The definition of '-Force' still uses the word 'force', which makes the description circular as in 
    "Q: What is a dog?  A: A dog is a dog."
If I ran the command without '-Force' when would it fail to sync?  Why would it fail to sync?
Those are the questions this description should answer.

**Comment by dariomws306** [comment]
Ok, I am adding more detail.

Thank you for your feedback.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @nobrassring Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by nobrassring** [comment]
Much better now. Thank you.

**Comment by dariomws306** [comment]
You're welcome!

Thank you for your contribution!
