### ISSUE TITLE
Example 5 not valid

### ISSUE THREAD

**Issue by JDBKJK** [MicrosoftDocs/windows-powershell-docs#3042]
The line of code in example 5 is not valid: $EAPXml = [xml]Get-Content -Path C:\eap-config.xml
This gives an error in powershell: "Unexpected token 'Get-Content' in expression or statement."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7d5a1fe-8a47-9466-f82a-da01dac1e41a
* Version Independent ID: 338bfafe-80bd-1bdb-8d9b-d43a04e007c6
* Content: [Add-VpnConnection (VpnClient)](https://docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/vpnclient/Add-VpnConnection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/vpnclient/Add-VpnConnection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@JDBKJK Thank you or your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3537

Once the author approves, the changes will be live.

Thanks
Sri
