### ISSUE TITLE
cert parameter does not accept multiple objects

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windows-powershell-docs#305]
The documentation says that the cert parameter can accept an array of certificate objects.  But it does not.  If you pass it a single object of System.Security.Cryptography.X509Certificates.X509Certificate2, it works as expected.  If you pass it an array or collection of System.Security.Cryptography.X509Certificates.X509Certificate2, it fails with "Export-Certificate : Cannot convert 'System.Object[]' to the type 'Microsoft.CertificateServices.Commands.Certificate' required by parameter 'Cert'. Specified method is not supported."

Demonstration:
```
# select more than one certificate 
$cert = Get-ChildItem -Path cert:\localmachine -recurse | out-gridview -passthru
# This works as expected
Export-Certificate -Cert $cert[0] -Type sst -FilePath C:\Users\Public\Documents\certexport.sst
# this throws an error
Export-Certificate -Cert $cert -Type sst -FilePath C:\Users\Public\Documents\certexport.sst
# This constructs an array of certificates and throws an error too
$cert | foreach-object -Begin { $cert2 = @() } -Process { $cert2 += $_ }
# even though they are both arrays
$cert.gettype()
$cert2.gettype()
# and they are arrays of System.Security.Cryptography.X509Certificates.X509Certificate2
$cert | get-member
$cert2 | get-member
# it looks like the problem is a fault in the new constructor of Microsoft.CertificateServices.Commands.Certificate
[Microsoft.CertificateServices.Commands.Certificate]::new($cert[0]) | Get-member
# That should not be a PSCustomObject
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c6b91f-0156-26c1-76f6-60f11d39bc37
* Version Independent ID: aedf27ba-abfc-7e5d-4c69-cbf370fdac2b
* Content: [Export-Certificate (pki)](https://docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=win10-ps)
* Content Source: [docset/windows/pki/export-certificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pki/export-certificate.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by jordanmills** [comment]
Uh it looks like this thing ate my hash marks and made headings.  Everything in the big bold type should be preceded by a #

**Comment by e0i** [comment]
Hello @jordanmills 

In our investigation we have been able to reproduce the issue as a bug. The issue is being escalated as a bug. 

Thank you for your valuable input.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by kumark18** [comment]
@e0i Can you please let me know if there is any page which has solution to this problem, or any steps are documented to solve the problem mentioned above

**Comment by bender-the-greatest** [comment]
This still appears to be a problem, why was this issue closed?

**Comment by jordanmills** [comment]
> This still appears to be a problem, why was this issue closed?

Microsoft closes all of these, regardless of actual status.  That way it looks like there are no bugs or problems.

**Comment by jordanmills** [comment]
And again a month later.

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by jordanmills** [comment]
> This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
> 
> I suggest you try posting your issue with context in one of the available [community support forums](https://docs.microsoft.com/powershell/scripting/community/community-support).

No, it has nothing to do with support.  Either the documentation or the product needs to be fixed.  Has either been done?
