### ISSUE TITLE
UseDesktopApplicationID is not documneted here

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-powershell-docs#306]
The switch UseDesktopApplicationID needs to be documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c11e894-7ba6-255b-334b-309b14fcb34e
* Version Independent ID: c1208227-6428-bee1-e2f3-0cda1f35dc1c
* Content: [Export-StartLayout (startlayout)](https://docs.microsoft.com/en-us/powershell/module/startlayout/export-startlayout?view=win10-ps)
* Content Source: [docset/windows/startlayout/export-startlayout.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/startlayout/export-startlayout.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hoyty76 thanks for your suggestion. I created a PR to improve the article adding the missing parameter.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hoyty76 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
