### ISSUE TITLE
Example Block - Missing Line Break and confusing/ incorrect

### ISSUE THREAD

**Issue by JCoreMS** [MicrosoftDocs/windows-powershell-docs#3060]
Looks like the Example is missing a line break! 

$creds = Get-Credential New-SmbGlobalMapping -RemotePath \\fs1.contoso.com\public -Credential $creds -LocalPath G:

Status Local Path Remote Path 
------ ---------- ----------- 
OK     G:         \\fs1.contoso.com\public

********  SHOULD maybe be this instead?? *********

$creds = Get-Credential
New-SmbGlobalMapping -RemotePath \\fs1.contoso.com\public -Credential $creds -LocalPath G:

Status Local Path Remote Path 
------ ---------- ----------- 
OK     G:         \\fs1.contoso.com\public

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8444a866-0018-8607-ca2c-040c5967840c
* Version Independent ID: 7aced3e1-6ecc-bf15-5e80-8e5df67225e6
* Content: [New-SmbGlobalMapping (SmbShare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/new-smbglobalmapping?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/smbshare/New-SmbGlobalMapping.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/smbshare/New-SmbGlobalMapping.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@JCoreMS Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3528

Once the author approves, the changes will be live.

Thanks
Sri
