### ISSUE TITLE
Remove-IscsiTargetPorta TargetPortalPortNumber parameter does not work.

### ISSUE THREAD

**Issue by jorimp** [MicrosoftDocs/windows-powershell-docs#3061]
Remove-IscsiTargetPortal does not work as documented with the TargetPortalPortNumber parameter.

PS C:\Users\Administrator> Remove-IscsiTargetPortal -TargetPortalAddress 192.168.130.101 -TargetPortalPortNumber 49152 -Confirm:$false
Remove-IscsiTargetPortal : Type mismatch for parameter "TargetPortalPortNumber"
At line:1 char:1
+ Remove-IscsiTargetPortal -TargetPortalAddress 192.168.130.101 -Target ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : InvalidType: (MSFT_iSCSITarge...2.168.130.101"):ROOT/Microsoft/...CSITargetPortal) [Remove-IscsiTargetPortal], CimEx   ception    + FullyQualifiedErrorId : HRESULT 0x80041005,Remove-IscsiTargetPortal
Remove-IscsiTargetPortal (iSCSI)
Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29ebe521-a188-121d-556b-ddd059b659c6
* Version Independent ID: c44f26a6-ed30-b532-2589-13a2442ff9fb
* Content: [Remove-IscsiTargetPortal (iSCSI)](https://docs.microsoft.com/en-us/powershell/module/iscsi/remove-iscsitargetportal?view=windowsserver2016-ps)
* Content Source: [docset/winserver2016-ps/iscsi/Remove-IscsiTargetPortal.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2016-ps/iscsi/Remove-IscsiTargetPortal.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
