### ISSUE TITLE
New-AppLockerPolicy documentation examples fail at execution

### ISSUE THREAD

**Issue by anderZubi** [MicrosoftDocs/windows-powershell-docs#3069]
Examples for New-AppLockerPolicy fail at execution. See example below:

```
PS C:\Users\User> Get-ChildItem C:\Windows\System32\*.exe | Get-AppLockerFileInformation | New-AppLockerPolicy -RuleType Publisher, Hash -User Everyone -RuleNamePrefix System32
New-AppLockerPolicy: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
New-AppLockerPolicy: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
New-AppLockerPolicy: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
New-AppLockerPolicy: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
New-AppLockerPolicy: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
```

I have not been able to successfuly execute the command. Therefore I don't know if problem is in the documentation or implementation of the module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83a5c40e-a011-4331-a36d-fd060ace4386
* Version Independent ID: 0cc63de0-b088-e96d-8b09-4c9c23ebd6e4
* Content: [New-AppLockerPolicy (AppLocker)](https://docs.microsoft.com/en-us/powershell/module/applocker/new-applockerpolicy?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/applocker/New-AppLockerPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2019-ps/applocker/New-AppLockerPolicy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@anderZubi  Thank you for your feedback. This looks more like a technical issue and I'd recommend you contact Microsoft support for further assistance.

Sorry about the delay in getting back to you.

Thanks
Sri

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
