### ISSUE TITLE
`Reset-AppxPackage` syntax is formatted incorrectly

### ISSUE THREAD

**Issue by aisgbnok** [MicrosoftDocs/windows-powershell-docs#3071]
### Description

The[ `Reset-AppxPackage` syntax is formatted incorrectly](https://learn.microsoft.com/powershell/module/appx/reset-appxpackage#syntax) resulting in a malformed render on the live page.

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/3aa42ba93b7cd3739c21116694252b7165c65a43/docset/winserver2022-ps/appx/Reset-AppxPackage.md?plain=1#L17-L24
![Reset-AppxPackage Syntax](https://github.com/MicrosoftDocs/windows-powershell-docs/assets/10838153/8befb53e-4a62-4ea0-8e06-92cc10aa3fa2)

Meanwhile other articles such as [`Add-AppxPackage`](https://learn.microsoft.com/powershell/module/appx/add-appxpackage#syntax), have proper syntax and render properly:

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/3aa42ba93b7cd3739c21116694252b7165c65a43/docset/winserver2022-ps/appx/Add-AppxPackage.md?plain=1#L16-L27

![Add-AppxPackage](https://github.com/MicrosoftDocs/windows-powershell-docs/assets/10838153/7eeb7870-506c-421d-83ee-eb58b8a70891)

**Comment by msbemba** [comment]
@aisgbnok Thank you for your feedback. We have made changes to all versions of the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3529

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by aisgbnok** [comment]
Hey @msbemba, thank you for taking a look at this issue, but I already opened PR #3072 10 months ago to resolve this. Unfortunately, it hasn't been merged yet.
