### ISSUE TITLE
`Remove-AppxPackageAutoUpdateSettings` 2022 has placeholder information

### ISSUE THREAD

**Issue by aisgbnok** [MicrosoftDocs/windows-powershell-docs#3073]
### Description

The [`Remove-AppxPackageAutoUpdateSettings`](https://docs.microsoft.com/powershell/module/appx/remove-appxpackageautoupdatesettings?view=windowsserver2022-ps) for Windows Server 2022 has placeholder information.

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/8e5c38ded70e24ca064e63dbc70705d2d6e55e08/docset/winserver2022-ps/appx/Remove-AppxPackageAutoUpdateSettings.md?plain=1#L11-L33

This is also present on the main AppX page.

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/8e5c38ded70e24ca064e63dbc70705d2d6e55e08/docset/winserver2022-ps/appx/Appx.md?plain=1#L69-L70

### Screenshots

![image](https://user-images.githubusercontent.com/10838153/185786862-bdaea790-c1c7-472a-86f4-e8e0291daa80.png)
![image](https://user-images.githubusercontent.com/10838153/185786878-1e29dfbd-56ba-40d8-8a69-1bb6ab168ebc.png)

**Comment by msbemba** [comment]
@aisgbnok Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3536

Once the author approves, the changes will be live.

Thanks
Sri
