### ISSUE TITLE
Typo on type

### ISSUE THREAD

**Issue by DavidHomerOxford** [MicrosoftDocs/windows-powershell-docs#3074]
The valid values for "Type" in the description block are incorrect - it states that IPAddress and IPv6Address are valid - but underneath in the table it correctly states that only IPv4Address is valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 168a6949-9d18-1cef-5aa4-a9dd50a5d76d
* Version Independent ID: e0d36882-535f-87f1-ee08-c1743db42a93
* Content: [Add-DhcpServerv4OptionDefinition (DhcpServer)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/add-dhcpserverv4optiondefinition?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/dhcpserver/Add-DhcpServerv4OptionDefinition.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/dhcpserver/Add-DhcpServerv4OptionDefinition.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@DavidHomerOxford Thank  you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3530

Once the author approves, the changes will be live.

Thanks
Sri
