### ISSUE TITLE
Test-DnsServer not present in Windows 11

### ISSUE THREAD

**Issue by aarond12** [MicrosoftDocs/windows-powershell-docs#3078]
PS C:\Users\aaron> **Test-DnsServer -IPAddress 192.168.1.1**
Test-DnsServer : The term 'Test-DnsServer' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Test-DnsServer -IPAddress 192.168.1.1
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Test-DnsServer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54f77075-d4c7-a2b3-dded-918468c9cd21
* Version Independent ID: 9977d1dc-e2c3-4a70-e25d-593a1a14126e
* Content: [Test-DnsServer (DnsServer)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/test-dnsserver?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/dnsserver/Test-DnsServer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/dnsserver/Test-DnsServer.md)
* Product: **w11**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
