### ISSUE TITLE
Module NetSecurity GPOSession

### ISSUE THREAD

**Issue by firerain-fd** [MicrosoftDocs/windows-powershell-docs#3083]
Why were the Get-NetFirewallRule, Set-NetFirewallRule, Remove-NetFirewallRule commands removed from the GPOSession?
How can I use GPOSession in these cmdlets now?

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
