### ISSUE TITLE
Clarify description of Remove-MpThreat cmdlet

### ISSUE THREAD

**Issue by vci-steven** [MicrosoftDocs/windows-powershell-docs#3086]
Clarify description.
"Removes active threats" as in attempts to remediate a detected threat or as in removes the "threat" from the list of active threats and has nothing to do with trying to clean, quarantine, or otherwise remediate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3e29ff-868d-6624-0f65-2c2ae830bcfa
* Version Independent ID: ff8a389b-a31c-7178-9cb2-3d6142f3a595
* Content: [Remove-MpThreat (Defender)](https://docs.microsoft.com/en-us/powershell/module/defender/remove-mpthreat?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/defender/Remove-MpThreat.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/defender/Remove-MpThreat.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@vci-steven Thank you for your feedback. That is right, It removes the "threat" from the list of active threats. It does not clean, quarantine, or remediate.

Hope this helps!

Thanks
Sri

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
