### ISSUE TITLE
NetWnv module is not available in W2022 datacenter

### ISSUE THREAD

**Issue by eva02g** [MicrosoftDocs/windows-powershell-docs#3087]
PS C:\Users\administrator.corp> Import-Module netWnv
Import-Module : The specified module 'netWnv' was not loaded because no valid module file was found in any module
directory.
At line:1 char:1
+ Import-Module netWnv
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (netWnv:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

If configured through SCVMM:

Error (50362)
Logical networks that use network virtualization and are not managed by Network Controller are not supported on the selected host ('sdnhost1.sdn.lab') OS version.

Recommended Action
Logical Networks that use Network Virtualization without Network Controller are not supported on Windows Server 2019 and above. Please manage the logical network using Network Controller for Network Virtualization.

PS C:\Users\administrator.corp> systeminfo

Host Name:                 SDNHOST1
OS Name:                   Microsoft Windows Server 2022 Datacenter
OS Version:                10.0.20348 N/A Build 20348
OS Manufacturer:           Microsoft Corporation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35ba03f9-84d4-a1a3-b771-27c38f39e94a
* Version Independent ID: 18405455-dc92-a2ca-d24f-25eba3b4a7f4
* Content: [NetWNV Module](https://docs.microsoft.com/en-us/powershell/module/netwnv/?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/netwnv/NetWNV.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/netwnv/NetWNV.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
