### ISSUE TITLE
SslFlags has additional values, but the cmdlet does not support them.

### ISSUE THREAD

**Issue by hahndorf** [MicrosoftDocs/windows-powershell-docs#3097]
The `SslFlags` Parameter is limited here to value 0 to 3, but in Server 2022 there are many more flags possible, checking all check-boxes in the GUI results in SslFlags of 125 in `ApplicationHost.config`

This is a problem with the cmdlet itself, the documentation is correctly listing the possible values, but the cmdlet must be updated to support all new flags. After that this page needs to be updated to reflect all the new flag values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00cd9b7b-b58d-e5c8-76d3-7bdf566e0b51
* Version Independent ID: fd8021e1-e815-0ddc-5d7a-61a02d06d6e9
* Content: [New-WebBinding (WebAdministration)](https://docs.microsoft.com/en-us/powershell/module/webadministration/new-webbinding?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/webadministration/New-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/webadministration/New-WebBinding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
