### ISSUE TITLE
Misleading examples

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/windows-powershell-docs#310]
The examples given here are wrong; it took me a lot of time and efforts to realize it. In both examples, "C:\Windows\winsxs" is given as the source. But unfortunately, this implies that one can extract capabilities from one's own running copy of Windows into an offline image. What adds credit to this belief is the fact that in Windows Vista and later, Windows aggressively claims C: for the system partition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a11a3f-a432-fd7e-d05e-8b80e891b3af
* Version Independent ID: 256de206-99fd-d0d4-4f1a-3321432d36f8
* Content: [Add-WindowsCapability (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/add-windowscapability?view=win10-ps)
* Content Source: [docset/windows/dism/add-windowscapability.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/add-windowscapability.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @skycommand , thank you for your feedback.

I think we should remove "-Source "C:\Windows\winsxs"" from these examples, this paremeters is not requiered.
Are you agree? Thanks.

**Comment by skycommand** [comment]
@dariomws306 Hi. Theoretically, replacing "C:\Windows\winsxs" with "\\REMOTE-PC\Windows-share\winsxs" should do the trick.

In practice, however, I cannot answer your question with certainty. If I could, I'd have filed a pull request instead. You see, even before 1809, when Microsoft still published FODv2 discs, I could not use this command with a "-Source" parameter. In a last-ditch effort, I replaced it with "Add-Package", which worked!

I was hoping that by filing this feedback item, someone who knows about the problem or one of Microsoft developers weigh in.

**Comment by skycommand** [comment]
I'm afraid I cannot say I agree. I did a few tests.

This command works:

    Add-WindowsCapability -Online -Name "Msix.PackagingTool.Driver~~~~0.0.1.0"

But this do not:

    Add-WindowsCapability -Path "E:\Queue\mp\" -Name "Msix.PackagingTool.Driver~~~~0.0.1.0"

So, no. Removing "-Source" does not solve the problem.

Also, I tried adding -Source switch. It looks like in all cases, DISM was looking for `Msix-PackagingTool-Driver-Package~31bf3856ad364e35~amd64~~.cab` at the path I specified as the source.

**Comment by dariomws306** [comment]
Second example works for me:
Add-WindowsCapability -Name "Language.TextToSpeech~~~fr-FR~0.0.1.0" -Online -LimitAccess -Source "C:\Windows\winsxs"

I cannot test the first example because I don't have an OS image in my disk to add this capability. But It will use the same files in "C:\Windows\winsxs", so it should work.

Have you test in another OS/Machine?

**Comment by skycommand** [comment]
Hi. Thanks for writing back.

> Have you test in another OS/Machine?

Dozens. My job requires that I work on many different machines. And anyway, I cannot reproduce it on a pristine VM.

> Second example works for me: Add-WindowsCapability -Name "Language.TextToSpeech~~~fr-FR~0.0.1.0" -Online -LimitAccess -Source "C:\Windows\winsxs"

May I please know what does "works for me" exactly means here? Do you mean that when you run it, it completes without generating an error message? That, I am afraid, is not enough; this command tells the servicing stack to add the French language from your running OS to your running OS. In other words, nothing! I am sure you agree that a command that does nothing meaningful isn't a good example of using PowerShell to help admin accomplish their business-critical goals.

Perhaps it is better that I contact Microsoft Premium Support about this. Nevertheless, the writers of Doc pages are responsible for writing examples that are easily reproducible and useful at the same time. Don't you agree?

**Comment by dariomws306** [comment]
Hi @skycommand.

Yes I think that if you are trying to use in complex scenarios the cmdlet and it doesn't work the best place to go is support.
Here we are available to help people to fix docs mistakes and improve them. And you are in the right direction about that examples are usually simple examples with easy and useful purpose.

Thank you again for your feedback.

**Comment by skycommand** [comment]
@dariomws306 Good news. Microsoft Support agent referred me to the old documentation pages for the old `dism.exe`. They are much clearer. I'll probably submit a PR to fix this documentation page based on that. I think it is safe that I close this topic and take it off your plate. (After all, you can reopen it if you felt it is needed, right?)
