### ISSUE TITLE
NetEventPacketCapture needs to support chained capture files

### ISSUE THREAD

**Issue by Malcolm-Stewart** [MicrosoftDocs/windows-powershell-docs#3103]
LOGMAN supports chained capture files (-Mode NewFile) with %d in the file name to indicate where to increment the file number.
NETSH does not support this, but you can work around it like this (.CMD syntax of %):

netsh trace start capture=yes maxsize=1 TRACEFILE=.\deleteme.etl
logman start ndiscap -p Microsoft-Windows-NDIS-PacketCapture -mode newfile -max 200 -o .\realdata%%d.etl -ets

Is there something similar with the PowerShell commands?
Can we capture the Microsoft-Windows-NDIS-PacketCapture event or similar event for network and firewall packet captures?

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
