### ISSUE TITLE
Is there a Powershell equivalent of PKTMON for network captures?

### ISSUE THREAD

**Issue by Malcolm-Stewart** [MicrosoftDocs/windows-powershell-docs#3104]
Is there a Powershell equivalent of PKTMON for network captures?

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
