### ISSUE TITLE
configuring IPv6 DoH

### ISSUE THREAD

**Issue by inoperable** [MicrosoftDocs/windows-powershell-docs#3106]
How do you add/change IPv6 DoH Addresses and Templates explicitly?
How do you add add a CPE ID argument to the DoH queries?
Is the DoH resolver actually capable of sending the CPE ID parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2a32c20-48aa-742d-7065-3b60fff17831
* Version Independent ID: a2bc0216-304a-2038-b0d7-2a37f9b56c14
* Content: [Remove-DnsClientDohServerAddress (DnsClient)](https://docs.microsoft.com/en-us/powershell/module/dnsclient/remove-dnsclientdohserveraddress?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by inoperable** [comment]
So after a month you still can't answer those questions?

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by inoperable** [comment]
So, basically IPv4 is here but IPv6 isn't?
