### ISSUE TITLE
Official options differ from example

### ISSUE THREAD

**Issue by JoergWu** [MicrosoftDocs/windows-powershell-docs#311]
The official option is called -AllowClear and the example shows: Initialize-Tpm -ForceClearAllowed -PhysicalPresenceAllowed. But the option ForceClearAllowed is shown and explained in detail. So whats wright here. Either this or the other one or did you missed the 3rd option overall? Sorry but that way the documentation does not make really sense!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03d0904d-0e38-d8d5-0e56-e0f235156e7f
* Version Independent ID: be656af1-a203-0dc9-8d56-11a42fe30f49
* Content: [Initialize-Tpm (trustedplatformmodule)](https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/initialize-tpm?view=win10-ps)
* Content Source: [docset/windows/trustedplatformmodule/initialize-tpm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/trustedplatformmodule/initialize-tpm.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@AndreaBarr Please have the PR #931 for this issue reviewed. Thanks.

**Comment by e0i** [comment]
The issue had been addressed via PR #456

**Comment by e0i** [comment]
@officedocsbot close
