### ISSUE TITLE
Incorrect description for New-NetQosPolicy's -Cluster argument.

### ISSUE THREAD

**Issue by JamieSee** [MicrosoftDocs/windows-powershell-docs#3110]
The description for -Cluster is incorrect. The current text reads:

> -Cluster
> Specifies the Microsoft cluster service, which uses the default SQL server TCP/UDP port 3343.

I propose the following edit:

> Specifies the Microsoft Windows Cluster Service, which uses the Cluster network driver TCP/UDP port 3343.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a8b1893-07ba-96cb-3f60-739a5b16dccd
* Version Independent ID: fd6ec687-d40a-8534-0d33-a4d5cd498d5a
* Content: [New-NetQosPolicy (NetQoS)](https://docs.microsoft.com/en-us/powershell/module/netqos/new-netqospolicy?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/netqos/New-NetQosPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/netqos/New-NetQosPolicy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@JamieSee Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3531

Once the author approves, the changes will be live.

Thanks
Sri
