### ISSUE TITLE
Add reservations from a file

### ISSUE THREAD

**Issue by BorisESRA** [MicrosoftDocs/windows-powershell-docs#3113]
[Enter feedback here]
Hi, I'm a newbie trying to add reservations from a file. 

I've tried this, on the computer wich runs the DHCP server service:
c:\>Import-Csv -Path "Reservations.csv" | Add-DhcpServerv4Reservation -ComputerName "dhcpserver.contoso.com"

My csv file is set up as required, 25 lines, each line for each reservation.
ScopeId,        IPAddress,    Name,                                ClientId,                   Description
192.168.30.0,192.168.30.1,Eisenstein-01.esraparis.lan,9c-76-0e-43-4d-94,Ordi Eisen 1
etc

![image](https://user-images.githubusercontent.com/113610811/190418289-f84a01ea-0f17-4e74-81cc-d99c95a453ee.png)

What am I doing wrong?
Thanks for the help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e68a0ce-d9a2-987d-c842-60ca8aa0c6fb
* Version Independent ID: b3e263ce-29e5-a1d3-99bc-5ec8ec54a21f
* Content: [Add-DhcpServerv4Reservation (DhcpServer)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/add-dhcpserverv4reservation?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/dhcpserver/Add-DhcpServerv4Reservation.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/dhcpserver/Add-DhcpServerv4Reservation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
