### ISSUE TITLE
Default Printer?

### ISSUE THREAD

**Issue by darksidemilk** [MicrosoftDocs/windows-powershell-docs#312]
Why isn't there a property for the current default printer?
There is one in what this appears to be based on, the wmi/cim class win32_printer but this populates much faster. If both get and set had access to that property this would become an even more amazing module. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 739c313b-cd7f-0f09-8304-276c7f7f53e5
* Version Independent ID: de0937d6-56af-873c-544c-5dcc046246e2
* Content: [Get-Printer (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/get-printer?view=win10-ps)
* Content Source: [docset/windows/printmanagement/get-printer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/printmanagement/get-printer.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @darksidemilk 
Thanks for your feedback.
As this issue system is specific for issues found in documentation and what you describe belongs exclusively to the cmdlet/module I suggest you to kindly visit this resource https://windowsserver.uservoice.com/forums/301869-powershell to make this suggestion.
**Thank you!**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @darksidemilk 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot closed
