### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by dmenafro** [MicrosoftDocs/windows-powershell-docs#313]
The examples have a typo. Adding an S to the end of the actual command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c059a771-884f-1b4d-e119-9baa87b4e459
* Version Independent ID: 84b88652-6e1f-b66b-f736-b7e9434e1d0b
* Content: [Set-StorageSetting (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/set-storagesetting?view=win10-ps)
* Content Source: [docset/windows/storage/set-storagesetting.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/set-storagesetting.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@kenwith A PR #751 is available for this issue. Please review. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
