### ISSUE TITLE
Invalid property name

### ISSUE THREAD

**Issue by simondel** [MicrosoftDocs/windows-powershell-docs#314]
Example 4 contains the property `-Member` on line 3 while this should be the plural `-Members`.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: e3d171bf-8203-db11-713f-05d25a5895fd
* Version Independent ID: e67ef480-2442-7610-879d-c0442034fbcb
* Content: [Add-ADGroupMember (addsadministration)](https://docs.microsoft.com/nl-nl/powershell/module/addsadministration/Add-ADGroupMember?view=win10-ps#related-links)
* Content Source: [docset/windows/addsadministration/add-adgroupmember.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/add-adgroupmember.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by simondel** [comment]
@brianlic-msft Why are you tagged in my post? 🤔

**Comment by brianlic-msft** [comment]
It's because I'm currently tagged as the owner in the topic metadata. :)

**Comment by simondel** [comment]
Shall I open a PR to fix this?

**Comment by brianlic-msft** [comment]
yes please. Thank you!
