### ISSUE TITLE
Possible invalid documentation

### ISSUE THREAD

**Issue by InteXX** [MicrosoftDocs/windows-powershell-docs#315]
This documentation appears to be obsolete. It refers to pre-2016 XML configuration files, which were superseded nearly two years ago. In addition, usage examples are omitted for the new file names (*.vmcx). See https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/what-s-new-in-hyper-v-on-windows#BKMK_Config.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42fa5406-e41f-9941-9bc4-3c305f9135af
* Version Independent ID: 3274511d-d9d5-6397-f168-db8918a4bebb
* Content: [Import-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/import-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/import-vm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/import-vm.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @InteXX 
Thanks for your feedback. I created a pull request to improve the article updating the examples to the new vcmx format.
Thank you

**Comment by InteXX** [comment]
@get-itips Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR #1112  and kindly provide your feedback

**Comment by sdubrick** [comment]
Hi, this is still wrong on https://docs.microsoft.com/en-us/powershell/module/hyper-v/import-vm?view=win10-ps, the Server 2016 page incorrectly shows the old XML format

**Comment by get-itips** [comment]
Hello @sdubrick currently there is a general issue with this repo where the PRs delay on being reflected. The team is working on that. We Will close again this issue. Thanks.
