### ISSUE TITLE
-Timespan parameter isnt a timespan

### ISSUE THREAD

**Issue by Jonathan-Quilter** [MicrosoftDocs/windows-powershell-docs#3150]
given that PowerShell has New-Timespan that has a concept of a start time and an end time then this parameter name is misleading in both what type of value(s) it might accept and what its effect on the results might be.

I propose that the Get-ClusterLog function should accept a start time (-StartTime) and an end time (-EndTime) so that a specific section of the cluster log can be retrieved. For example the case where an event occurred overnight (eg 19:00 - 19:15 yesterday), which requires investigation at 09:00 today. using the current syntax you would need to execute Get-ClusterLog with a -Timespan value 840 and then subsequently remove 825 minutes of the content already drawn across the network. 

If it was possible to send in a -StartTime and -EndTime parameter value of [yesterdaysdate]19:00 and [yesterdaysdate]19:15 then only the relevant part of the log would get retrieved over the network for review.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68d301be-e57f-e1fd-2b61-76c4ef8d5b02
* Version Independent ID: d0e38cb2-0342-dd00-b46b-db54ea311670
* Content: [Get-ClusterLog (FailoverClusters)](https://learn.microsoft.com/en-us/powershell/module/failoverclusters/get-clusterlog?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/failoverclusters/Get-ClusterLog.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/failoverclusters/Get-ClusterLog.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by sdwheeler** [comment]
The documentation is correct as written for this cmdlet. You are providing product feedback.

Please use the Windows Feedback Hub. For more information, see [Send feedback to Microsoft with the Feedback Hub app][1].

[1]: https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
