### ISSUE TITLE
The default value for -Timeout is incorrect

### ISSUE THREAD

**Issue by RutujaShirali** [MicrosoftDocs/windows-powershell-docs#3152]
The default value for the recursion timeout is 0x8. Its wrongly mentioned as 0xF

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 901ab0d1-4d3b-3932-4e07-5f455c91a035
* Version Independent ID: c602ce3c-53f4-b0fd-ce91-de26574cc33e
* Content: [Set-DnsServerRecursion (DnsServer)](https://learn.microsoft.com/en-us/powershell/module/dnsserver/set-dnsserverrecursion?view=windowsserver2022-ps&source=docs)
* Content Source: [docset/winserver2022-ps/dnsserver/Set-DnsServerRecursion.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/dnsserver/Set-DnsServerRecursion.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@RutujaShirali Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3538

Once the author approves, the changes will be live.

Thanks
Sri
