### ISSUE TITLE
find module for a cmdlet

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/windows-powershell-docs#3155]
If I have a cmdlet, say `New-EventLog`, and I want to find the module to install, how do I do that?  Isn't a critical step in this process that should be documented? 🤔

Some stuff would be obvious I guess but not everything.

Did I miss that when reading the doc page? 🤔

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 260321a5-4821-e33d-f413-4a30d3898a5a
* Version Independent ID: 09aa75ed-0c52-30e7-cd7b-a682684766a1
* Content: [PowerShell 7 module compatibility](https://learn.microsoft.com/en-us/powershell/windows/module-compatibility?view=windowsserver2022-ps)
* Content Source: [docset/docs-conceptual/winserver2022-ps/module-compatibility.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/docs-conceptual/winserver2022-ps/module-compatibility.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by sdwheeler** [comment]
You can search for cmdlets in two places:
- The PowerShell module browser https://learn.microsoft.com/en-us/powershell/module/
- The PowerShell Gallery https://www.powershellgallery.com/

**Comment by spottedmahn** [comment]
related: [this solved my problem](https://github.com/PowerShell/PowerShell/issues/18281#issuecomment-1278393032)
