### ISSUE TITLE
Test-Netconnection using -informationlevel 'Quiet' did not throw error if computername is empty

### ISSUE THREAD

**Issue by SwissPowershell** [MicrosoftDocs/windows-powershell-docs#3159]
I've gone trough a "bug" where informationlevel is winning against erroraction preference which imo is a non sense
the following code try to do a "ping" on a computername which is empty string

you can see that the error is correctly catched 
(Resolve-DnsName : Cannot validate argument on parameter 'Name'. The argument is null or empty)

`PS C:\> try {Test-NetConnection -ComputerName '' -erroraction 'stop'} Catch {Write-Host 'There was error(s)'}
There was error(s)
`
The same function using 'Informationlevel' return $true

`PS C:\> try {Test-NetConnection -ComputerName '' -erroraction 'stop' -informationlevel 'quiet'} Catch {Write-Host 'There was error(s)'}
true
`
Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3735122-5f7a-5ff5-0894-df4f01e81ea9
* Version Independent ID: 2a976f70-cc7b-cf2c-341b-ba1612744f13
* Content: [Test-NetConnection (NetTCPIP)](https://learn.microsoft.com/en-us/powershell/module/nettcpip/test-netconnection?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/nettcpip/Test-NetConnection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/nettcpip/Test-NetConnection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
