### ISSUE TITLE
M$ "Docs", `Stop-VM`: Please explain how to disable the stupid warning: "WARNING: The virtual machine is already in the specified state"

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windows-powershell-docs#3175]
Hello

As you know, PowerShell has great concepts and proposals and the CmdLet `Stop-VM` violates these recommendations: If a user stops a VM and it is already stopped, then the user is forced to get the stupid message _"WARNING: The virtual machine is already in the specified state"_.

This behavior violates the mostly great PowerShell recommendations: If such a message is displayed, it is definitely only when the user explicitly invokes the command with -Verbose.

**Therefore, the M$ "Docs" should explain how it's possible to make `Stop-VM` behave as PowerShell proposes and *not* display this useless message.** Otherwise, the Users / Admins get warning message spam and it happens that they overlook real warnings 😢. 

Btw.: This message is stupid because if something is already in the expected new state, then for sure, it must never be a warning. Everything is in the desired state.

Otherwise, PowerShell must start displaying Warnings if a user deletes a file that is already deleted. If a Service is already stopped he tries to stop it. In the end, M$ will get a lot of angry PowerShell users because the console is full of spam.

Thanks a lot, kind regards,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac588444-835c-ed7a-30e5-8f6e2f961e8a
* Version Independent ID: 2e43e92a-3320-994b-c95a-06f763b779b2
* Content: [Stop-VM (Hyper-V)](https://learn.microsoft.com/en-us/powershell/module/hyper-v/stop-vm?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/hyper-v/Stop-VM.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/hyper-v/Stop-VM.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
