### ISSUE TITLE
Module docs need info on how to find

### ISSUE THREAD

**Issue by TimCurwick** [MicrosoftDocs/windows-powershell-docs#318]
All of the top-level Module docs (including, for example, the below referenced doc for the DNSServer module), need a section explaining how to find the module.

Examples of the sort of information that is needed:

This module is a core part of PowerShell and is installed or upgraded by upgrading to PowerShell X.x or higher.

This module ships with Windows version X.x or higher or Windows Server X.x or higher.

This module is available as part of Windows version X.x or higher or Windows Server X.x or higher. Annoyingly, it is not installed and available for use until Windows Feature RSAT-Or-Whatever-Feature is installed. Here is the code for checking for it. Here is the code for installing it. Annoyingly, the above code must be run as an administrator.

This module is just kind of there in the OS, but updates are maintained and pushed out through a different pipeline as follows. Or whatever.

In addition, it would also be helpful to have a central doc summarizing all PowerShell modules past and present created by any Microsoft team, with version information, current status, where to find it, what team is responsible for it, with links to the docs, source code, feedback, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26d20419-9d03-1303-93cd-606fa58704c0
* Version Independent ID: 4a3e8930-8c29-43b8-3989-5e1bd94eaf47
* Content: [DnsServer](https://docs.microsoft.com/en-us/powershell/module/dnsserver/?view=win10-ps)
* Content Source: [docset/windows/dnsserver/dnsserver.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/dnsserver.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by archmangler** [comment]
How to get this specific module installed for Linux' powershell ?
I understand this is not part of .NetCore but is there a workaround to get it installed on Linux so that it can be used in powershell to carry out remote dns administration of windows dns servers?

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @TimCurwick thanks for your feeedback. I found your suggestion useful, I'll propose thru a Pull Request, the addition of that information to this module.
Thank you.

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR #1109 #1110 #1111  and kindly provide your feedback

**Comment by tseward** [comment]
I'm good with the PRs.

**Comment by dariomws306** [comment]
Looks good!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @TimCurwick Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
