### ISSUE TITLE
Typo in the Docs page

### ISSUE THREAD

**Issue by lulMeow** [MicrosoftDocs/windows-powershell-docs#3189]
There is a Typo in this sentence:

**This** cmdlet **this** runs on both UEFI and BIOS (non-UEFI) computers.

the second "This" should be deleted because grammatically incorrect and most likely put there by mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f849d0b-e013-8248-85c2-a51ae26a1933
* Version Independent ID: fbe31ff2-671c-d506-b107-dbe5b8180f46
* Content: [Format-SecureBootUEFI (SecureBoot)](https://learn.microsoft.com/en-us/powershell/module/secureboot/format-securebootuefi?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/secureboot/Format-SecureBootUEFI.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/secureboot/Format-SecureBootUEFI.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by BWMerlin** [comment]
Have created a pull request for this https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3245

**Comment by tiburd** [comment]
fixed in https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3190
