### ISSUE TITLE
Must be ran from a local session, does not support remote powershell session

### ISSUE THREAD

**Issue by hiway65n** [MicrosoftDocs/windows-powershell-docs#319]
If you try to run Get-BitsTransfer from a remote powershell session it will give you an error stating that "The remote use of BITS is not supported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8f0b98-7849-423a-22e7-82642093489f
* Version Independent ID: bb8a115f-c9c0-4e1f-3a96-d4227b3bc06e
* Content: [Get-BitsTransfer (bitstransfer)](https://docs.microsoft.com/en-us/powershell/module/bitstransfer/Get-BitsTransfer?view=win10-ps)
* Content Source: [docset/windows/bitstransfer/get-bitstransfer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitstransfer/get-bitstransfer.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by VLG17** [comment]
@hiway65n "Starting with Windows 10, version 1607, you can run PowerShell Cmdlets, BITSAdmin, or other applications that use the BITS interfaces from a PowerShell Remote command line connected to another machine (physical or virtual). This capability is not available when using a PowerShell Direct command line to a virtual machine on the same physical machine, and it is not available when using WinRM cmdlets." 

https://docs.microsoft.com/en-us/windows/desktop/Bits/using-windows-powershell-to-create-bits-transfer-jobs#manage_ps_remote_sessions

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and sharing this explanation. @hiway65n 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
