### ISSUE TITLE
EnableControlledFolderAccess

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windows-powershell-docs#3194]
Observing the Enable Controlled Folder Access parameter, identify from the GPO that option 3, which would block and audit generating event id 1123, does not work. Only option 1 of blocking is generating in the event log and blocking.

I am MVP Microsoft ID 5003815.

I left the video where I demonstrate the bug.

https://user-images.githubusercontent.com/31531703/202588796-20b167ea-8310-49db-8e28-773ad8eaf876.mp4

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44f43117-c0f9-84e2-9a2a-0335f516f7d0
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (Defender)](https://learn.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2022-ps#feedback)
* Content Source: [docset/winserver2022-ps/defender/Set-MpPreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/defender/Set-MpPreference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
