### ISSUE TITLE
Module of RemoteDesktop & PowerShell Core

### ISSUE THREAD

**Issue by RobertKustra** [MicrosoftDocs/windows-powershell-docs#3199]
Is there any change to use/import PowerShell module of Remote Desktop with PSVersion Core 7.3.0 or any other version of powershell core? 

PS C:\> Import-Module RemoteDesktop -SkipEditionCheck
Add-Type: (35,16): error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.         public CertificateRole
Role { get; private set; }                ^
Add-Type: (44,29): error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.                       
CertificateRole role,                             ^
Add-Type: Cannot add type. Compilation errors occurred.
ParserError: Attribute argument must be a constant or a script block.
Import-Module: The module to process 'DeploymentProperties.psm1', listed in field 'NestedModules' of module manifest 'C:\Program Files\WindowsPowerShell\Modules\RemoteDesktop\RemoteDesktop.psd1' was not processed because no valid module was found in any module directory.

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
