### ISSUE TITLE
-PrincipalsAllowedToDelegateToAccount is destructive not additive.

### ISSUE THREAD

**Issue by thesmall** [MicrosoftDocs/windows-powershell-docs#321]
Might be worth mentioning that configuring this parameter is a destructive action, not additive, meaning that if you delegate one principal, and then need to delegate another principal, and your second Set-ADComputer call doesn't contain both principals, you will overwrite the first principal with the second principal. This kind of information should honestly be documented for all parameters where the modification of the state of data is not intuitive. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd58820d-4c65-ef14-5a9c-6e1bccd9f660
* Version Independent ID: 82496095-f9a6-aa7e-10b2-9b7de50f39eb
* Content: [Set-ADComputer (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-adcomputer?view=win10-ps)
* Content Source: [docset/windows/addsadministration/set-adcomputer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-adcomputer.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @thesmall Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
