### ISSUE TITLE
A fourth situation in Windows 10 Pro 

### ISSUE THREAD

**Issue by IntelligentSiliconLtd** [MicrosoftDocs/windows-powershell-docs#322]
Powershell version 5.1.16299.98 
Win 10 Pro version 10.0.16299.0 
New offline PC when checking system before putting it online,  Powershell running with administrator level security, Get-SecureBootPolicy returns the error message "Cmdlet not supported on this platform: 0xC0000003", this is despite Confirm-SecureBootUEFI returning True.
Nothing online in search engines to suggest what to do in this situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a9f651d-39bc-bfdc-66ea-10e1c93e2e6d
* Version Independent ID: b9c4f848-e8b0-78e8-5230-88c0732f563c
* Content: [Get-SecureBootPolicy (secureboot)](https://docs.microsoft.com/en-us/powershell/module/secureboot/get-securebootpolicy?view=win10-ps)
* Content Source: [docset/windows/secureboot/get-securebootpolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/secureboot/get-securebootpolicy.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by IntelligentSiliconLtd** [comment]
The command "get-command get-securebootpolicy" returns
CommandType Cmdlet
Name Get-SecureBootPolicy
Version 2.0.0.0
Source SecureBoot

So the cmdlet appears to be installed.
Its a Dell Optiplex machine this situation is seen on.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @IntelligentSiliconLtd thanks for your feedback.

I think that this support resource https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10 better fits your request, kindly check it.

**Thank you**

**Comment by yogkumgit** [comment]
@IntelligentSiliconLtd  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution.

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
