### ISSUE TITLE
BaseReachable time default value is 30000 instead of 30

### ISSUE THREAD

**Issue by Brain2000** [MicrosoftDocs/windows-powershell-docs#3222]
The BaseReachable time has this description:
The default value is 30.

However, the default value is 30000. I think someone was thinking "30 seconds" instead of milliseconds.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8c56f7f-b2aa-febc-805a-1f3a944135a3
* Version Independent ID: 6e686f18-dba9-5ad0-d000-af6d10578866
* Content: [Get-NetIPInterface (NetTCPIP)](https://learn.microsoft.com/en-us/powershell/module/nettcpip/get-netipinterface?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/nettcpip/Get-NetIPInterface.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/nettcpip/Get-NetIPInterface.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Brain2000 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3475

Once the author approves, the changes will be live.

Thanks
Sri
