### ISSUE TITLE
Start-MpScan -ScanType FullScan ignores ExclusionExtension preference

### ISSUE THREAD

**Issue by atrenton** [MicrosoftDocs/windows-powershell-docs#3225]
Potential workaround would be to allow the -ScanPath parameter to accept a String[] of drive letters when using -ScanType CustomScan ( E.G., -ScanPath “C:,D:” )

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
