### ISSUE TITLE
Remove-ADComputer -Confirm parameter documentation is incorrect and/or inconsistent with itself.

### ISSUE THREAD

**Issue by mmseng** [MicrosoftDocs/windows-powershell-docs#3227]
The default value for the `-Confirm` parameter of `Remove-ADComputer` is documented as being `False`, under the "Parameters" heading. However this is not the case, and the page even states at the bottom under the "Notes" heading that:

```
By default, this cmdlet has the Confirm parameter set, which prompts you to confirm before a removal of the specified object type can occur. To bypass prompting for confirmation before removal, you can specify -Confirm:$False when using this cmdlet.
```

If the default value is actually `True`, then IMO the documentation under the "Parameters" heading should just be corrected, and the statement under the "Notes" heading should be removed.

IME, normally cmdlets which prompt by default use a `-Force` or similar parameter instead to change that behavior. But I'm no expert in the underlying PowerShell convention infrastructure.

The cmdlet behavior is the same in both PS 7.2.8 as well as PS 5.1, and the documentation has this flaw in both of the following pages (and probably all other versions):
  - https://learn.microsoft.com/en-us/powershell/module/activedirectory/remove-adcomputer?view=windowsserver2022-ps
  - https://learn.microsoft.com/en-us/powershell/module/activedirectory/remove-adcomputer?view=windowsserver2019-ps

This issue was also reported here: https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2033, however the poster erroneously closed it due to apparently conflating the issue with some other issue.

Regards,
== mmseng

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 750ecc07-49ec-afc6-8bde-e2608fa1d6f8
* Version Independent ID: 0d78bf04-4c4f-6f92-7e20-0c261d7ae090
* Content: [Remove-ADComputer (ActiveDirectory)](https://learn.microsoft.com/en-us/powershell/module/activedirectory/remove-adcomputer?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/activedirectory/Remove-ADComputer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/activedirectory/Remove-ADComputer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@mmseng Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3474

Once the author approves, the changes will be live.

Thanks
Sri
