### ISSUE TITLE
issue with testing the domain on 2016 core.

### ISSUE THREAD

**Issue by Blankf** [MicrosoftDocs/windows-powershell-docs#323]
i've installed my new dc with install-addsdomaincontroller and the installation completed, server rebooted and i have myself a new domain controller.
replication seems fine and domain seems fine, so far so good.

but when running Test-ADDSDomainControllerInstallation gives the following error: The specified argument 'ConfirmGc' was not recognized.

Also another Install-ADDSDomainController run will give me the same error.

Message                                                                                                                        Context                                                 RebootRequired  Status
-------                                                                                                                        -------                                                 --------------  ------
Test VerifyAdminTrustedForDelegation completed successfully                                                                    Test.VerifyAdminTrustedForDelegation.DCPromo.General.1           False Success
Test VerifyADPrepPrerequisites completed successfully                                                                          Test.VerifyADPrepPrerequisites.ADPrep.General.0                  False Success
Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGc' was not recognized... Test.VerifyDcPromoCore.DCPromo.General.77                        False   Error
Test VerifyOutboundReplicationEnabled completed successfully                                                                   Test.VerifyOutboundReplicationEnabled.DCPromo.General.1          False Success

i have this all in the xADDomaincontroller dsc document, but with normal commandlets i have the issue so cant use any desired state at the moment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80116797-a4bd-8cd3-2e01-29053fc466d5
* Version Independent ID: 05095324-22ef-6c13-4e96-a530bc8d51c3
* Content: [Test-ADDSDomainControllerInstallation (addsdeployment)](https://docs.microsoft.com/en-us/powershell/module/addsdeployment/test-addsdomaincontrollerinstallation?view=win10-ps)
* Content Source: [docset/windows/addsdeployment/test-addsdomaincontrollerinstallation.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsdeployment/test-addsdomaincontrollerinstallation.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @blankf thanks for your feedback. We really appreciate it.

I think that this support resource https://support.microsoft.com/en-us/supportforbusiness/productselection better fits your request, kindly check it.

Thank you

**Comment by yogkumgit** [comment]
@Blankf Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
