### ISSUE TITLE
This is sad, the folder doesn't exist et neither the files. Remove this if you don't care making it work.

### ISSUE THREAD

**Issue by RichardTPLQ** [MicrosoftDocs/windows-powershell-docs#3230]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae5ef1bc-bfa7-018b-0b4d-861f6fe996d9
* Version Independent ID: 3ed3598d-cb43-b7ae-85de-4d26a243fc4a
* Content: [Backup-WebConfiguration (WebAdministration)](https://learn.microsoft.com/en-us/powershell/module/webadministration/backup-webconfiguration?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/webadministration/Backup-WebConfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/webadministration/Backup-WebConfiguration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RichardTPLQ** [comment]
Remove this code, it doesn't work.

**Comment by msbemba** [comment]
@RichardTPLQ Thank you for your feedback. This works fine as documented. If you still need help, I'd recommend contacting Microsoft support to troubleshoot the issue.

Hope this helps!

Thanks
Sri

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
