### ISSUE TITLE
The format of the time period is not correct.

### ISSUE THREAD

**Issue by roupec** [MicrosoftDocs/windows-powershell-docs#3233]
I used the following format, which worked for me:

 Set-ADDefaultDomainPasswordPolicy -Identity xxx.local -MaxPasswordAge 999.00:00:00

There is a mistake after Day - it must be "dot" instead of "column"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa08f21b-f13b-43fe-df53-42a829fa971c
* Version Independent ID: d0ef6532-c477-0217-6666-7df8eb357aa2
* Content: [Set-ADDefaultDomainPasswordPolicy (ActiveDirectory)](https://learn.microsoft.com/en-us/powershell/module/activedirectory/set-addefaultdomainpasswordpolicy?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/activedirectory/Set-ADDefaultDomainPasswordPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/activedirectory/Set-ADDefaultDomainPasswordPolicy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by BWMerlin** [comment]
The only example I could of the colon being used after day was from -LockoutObservationWindow and I have created a pull request. https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3244

**Comment by msbemba** [comment]
@roupec Thank you for your feedback. I have checked all versions of the document and it is now updated to D.H:M:S.F.

Hope this helps!

Thanks
Sri

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
