### ISSUE TITLE
Get appx application name from id in package property?  

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#3235]
[Enter feedback here]
How do you go from the application (appx) id, to the program name?  This is for "microsoft.windows.startmenuexperiencehost" according to the firewall control panel.

Get-NetFirewallRule -DisplayName Start | Get-NetFirewallApplicationFilter

Program : Any
Package : S-1-15-2-515815643-2845804217-1874292103-218650560-777617685-4287762684-137415000

Program : Any
Package : S-1-15-2-515815643-2845804217-1874292103-218650560-777617685-4287762684-137415000

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93952d47-14fb-2d9e-a1c9-8250a2b0099d
* Version Independent ID: 8921130b-d3e4-c7f3-7e14-c1cb9f6b2cbc
* Content: [Get-NetFirewallApplicationFilter (NetSecurity)](https://learn.microsoft.com/en-us/powershell/module/netsecurity/get-netfirewallapplicationfilter?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/netsecurity/Get-NetFirewallApplicationFilter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/netsecurity/Get-NetFirewallApplicationFilter.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by jszabo98** [comment]
You might add the answer to the docs.
