### ISSUE TITLE
numeric range filter?

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#324]
Is there a way to do a numeric range filter, like [int]employeeid -gt 100000 -and [int]employeeid -lt 200000, without treating the property like a string?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0b9f4db-305b-847a-1ab6-ad3b547a91f7
* Version Independent ID: a626e689-b2ba-6a11-c17b-9f1fd0e565cd
* Content: [Get-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/get-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/get-aduser.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jszabo98 
Thanks for your feedback.
Your question is more related to general powershell than the cmdlet so I kindly suggest you look on how to cast data types in Powershell, as this system is specific for issues with documentation.

**Thank you**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jszabo98 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
