### ISSUE TITLE
Small Typo in the document

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-powershell-docs#3241]
in here:
https://learn.microsoft.com/en-us/powershell/module/hyper-v/set-vmprocessor?view=windowsserver2022-ps#-exposevirtualizationextensions

> Specifies whether the hypervisor should expose the presence of virtualization extensions to the virtual machine, which enables support for nested virtualization,.

there is an extra `,` at the end, before the `.`

![image](https://user-images.githubusercontent.com/118815227/213459066-f84aa36e-ad03-4beb-a10a-928810ce44f0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96416c6d-1491-2224-adf7-ebf8f9c92e9a
* Version Independent ID: cd348f47-0522-b6de-353c-c0e8ecf86cf2
* Content: [Set-VMProcessor (Hyper-V)](https://learn.microsoft.com/en-us/powershell/module/hyper-v/set-vmprocessor?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/hyper-v/Set-VMProcessor.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/hyper-v/Set-VMProcessor.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by BWMerlin** [comment]
I have created a pull request https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3243

**Comment by msbemba** [comment]
@HotCakeX Thank you for your feedback. We have created a PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3472 to fix all versions of the document.

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by HotCakeX** [comment]
Thank you
