### ISSUE TITLE
Conflict between description of Windows Defender cmdlet and Group Policy for the same setting

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-powershell-docs#3251]
### Windows Security (Defender) has this PowerShell cmdlet with this description in the attached Microsoft document:

**-CheckForSignaturesBeforeRunningScan**

Indicates whether to check for new virus and spyware definitions before Windows Defender runs a scan. If you specify a value of $True, Windows Defender checks for new definitions. If you specify $False or don't specify a value, the scan begins with existing definitions. **This value applies to scheduled scans and to scans that you start from the command line, but it doesn't affect scans that you start from the user interface.**

<hr style="border:1px solid gray">

### That option also exists in Group Policy and its description is this:

This policy setting allows you to manage whether a check for new virus and spyware security intelligence will occur before running a scan. 

**This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or to the ones started from the command line using "mpcmdrun -Scan".**
If you enable this setting, a check for new security intelligence will occur before running a scan.
If you disable this setting or do not configure this setting, the scan will start using the existing security intelligence.

<hr style="border:2px solid gray">

### These 2 lines are in conflict:

- PowerShell cmdlet's description says: 

**This value applies to scheduled scans and to scans that you start from the command line, but it doesn't affect scans that you start from the user interface.**

- Group Policy's description says:

**This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or to the ones started from the command line using "mpcmdrun -Scan"**

## Problem:

We don't know whether or not that setting applies to scans initiated from command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44f43117-c0f9-84e2-9a2a-0335f516f7d0
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (Defender)](https://learn.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/defender/Set-MpPreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/defender/Set-MpPreference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by HotCakeX** [comment]
![image](https://user-images.githubusercontent.com/118815227/214546652-21a0b9ab-9895-4033-8041-1663ed71010a.png)

- Edition	Windows 11 Pro for Workstations Insider Preview
- Version	22H2
- Installed on	‎1/‎24/‎2023
- OS build	25276.1000
- Experience	Windows Feature Experience Pack 1000.25276.1000.0

**Comment by msbemba** [comment]
@HotCakeX Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3301

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by HotCakeX** [comment]
@msbemba Thanks for letting me know!
