### ISSUE TITLE
Export-StartLayout creates a JSON file, not XML.  Import-StartLayout can't consume it.

### ISSUE THREAD

**Issue by lucent-sea** [MicrosoftDocs/windows-powershell-docs#3267]
This is on Windows 11.

The `Export-StartLayout` cmdlet creates a JSON file, but the documentation says it creates XML.

If you try to import the JSON file that results from this cmdlet, you'll get the error:

```
Import-StartLayout : The file {path-to-file} is not a valid layout file
```

The JSON file looks like this, which is clearly intended for Windows 11:

```
{
    "pinnedList": [
        {
            "desktopAppLink": "%ALLUSERSPROFILE%\\Microsoft\\Windows\\Start Menu\\Programs\\Microsoft Edge.lnk"
        }
        // etc.
    ]
}
```

If you use the `UseDesktopApplicationID` switch with the export command, then it creates XML.  However, the content within it is clearly meant for Windows 10, since it contains tiles and sizes.  And it doesn't reflect what's pinned in the Windows 11 start menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b2acb98-04c8-242f-8ee8-3c5150160eb5
* Version Independent ID: c1208227-6428-bee1-e2f3-0cda1f35dc1c
* Content: [Export-StartLayout (StartLayout)](https://learn.microsoft.com/en-us/powershell/module/startlayout/export-startlayout?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/startlayout/Export-StartLayout.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/startlayout/Export-StartLayout.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RuuneWoW** [comment]
Still running into this issue as of July 2023. 
`Export-StartLayout -Path "C:\Layouts\StartLayout.xml"` 
results in a JSON file with an XML file extension

**Comment by Tsjippy** [comment]
still an issue

**Comment by JustinBrow** [comment]
Still an issue. Windows 11 version of `Export-StartLayout` needs Windows 11 specific documentation.

**Comment by Fabelwesen** [comment]
And.. still an issue! 2024

**Comment by NiRasm** [comment]
Still an issue :(

**Comment by Qaddoumi** [comment]
still an issue 😢 aug,10 2024

**Comment by eadamsintel** [comment]
Why was this closed? This is still a problem at least for me.  My Start Menu broke and won't let me pin any tasks. I tried every guide but it stays broken. I found that I can Export the start layout but it is really surprising to me that I can't just import that file back because it is in the wrong format. I am now stuck with the last configuration of my Start Menu with no seeming way to fic it.

**Comment by PCAssistSoftware** [comment]
same issue with Windows 11 24H2, not sure why this was closed?

**Comment by mcarteramacon** [comment]
It appears they updated documentation for Import-StartLayout:
[https://learn.microsoft.com/en-us/powershell/module/startlayout/import-startlayout](https://learn.microsoft.com/en-us/powershell/module/startlayout/import-startlayout)

There's now a section saying
> "The Import-StartLayout cmdlet is deprecated in Windows 11. It has no effect on either Start or Taskbar layout. To configure the Start layout in Windows 11, see Customize the Windows 11 Start layout. To configure Taskbar layout in Windows 11, see Customize the Taskbar."

My interpretation is they don't see a point in updating Export-StartLayout for Windows 11 if the corresponding import command is officially unsupported now.

**Comment by flyingllama87** [comment]
@mcarteramacon Good find. That solves that mystery.

If MS only supports a method that requires the config to be baked into the image ("TaskbarLayoutModification.XML"), I think that there is room for a third party tool to programmatically create taskbar icons (e.g. [using this API](https://learn.microsoft.com/en-us/windows/apps/design/shell/pin-to-taskbar)), it'll prompt the user but admins can set this to run at first login under the user context.
