### ISSUE TITLE
Missing -sanitize Flag

### ISSUE THREAD

**Issue by Geinsbeing** [MicrosoftDocs/windows-powershell-docs#327]
Sanitize flag has not been documented. Knowing what overwrite algorithm it uses would be informational.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2e08ccd-4682-8fdf-7ad6-67710d5ba29f
* Version Independent ID: 385a14b2-fca1-2534-d16f-a239fd113f55
* Content: [Clear-Disk (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/clear-disk?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/storage/Clear-Disk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/storage/Clear-Disk.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by nudlsoop** [comment]
In the newly-released version of Windows Server 2019 getting help on the Clear-Disk cmdlet is missing the "-Sanitize" parameter, 
`PS > help Clear-Disk -Parameter sanitize`
`Get-Help : No parameter matches criteria sanitize.`

**Comment by sowjanya365** [comment]
Hi @Geinsbeing 

Thanks for your patience and contribution. Much appreciated.

We've observed that there is no association between "Clear-Disk" cmdlet and the -sanitize flag.

If you think our understanding of this issue is incorrect would you be so kind as to elaborate more on this? It would help us to understand it better and take appropriate steps to correct it or clarify. Thank you.

**Comment by e0i** [comment]
Hello @Geinsbeing,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by AlphaR3C0N** [comment]
![iseclear-disk](https://user-images.githubusercontent.com/58408155/75637357-d8288d80-5c8a-11ea-8108-9bb358cae01e.png)

Powershell ISE seems to think there is an association.
(Windows Server 2019 Datacenter, Version: 1809, OS Build: 17763.107)

**Comment by joegasper** [comment]
Please see this [detailed research on the _sanitize_ switch parameter ](https://stackoverflow.com/questions/70634041/what-does-the-sanitize-switch-of-the-clear-disk-cmdlet-do-in-powershell) of the Clear-Disk cmdlet but still is undocumented.
