### ISSUE TITLE
Error running Get-AppxPackage

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/windows-powershell-docs#3272]
[Enter feedback here]
When I try to run Get-AppxPackage on a Windows 10 system with 7, I get the following.

Get-Process: A positional parameter cannot be found that accepts argument 'Get-AppxPackage'.

The document at https://learn.microsoft.com/en-us/powershell/windows/module-compatibility?view=windowsserver2022-ps says it must be run using compatibility layer with PowerShell 7.1.  Can something be added stating how that is done, or at least a link to the steps?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7886f254-9ca3-0a2e-9338-b92d08dc4bf7
* Version Independent ID: ef40ae25-6d2b-6b0a-1fa7-dc3a7c97df0a
* Content: [Get-AppxPackage (Appx)](https://learn.microsoft.com/en-us/powershell/module/appx/get-appxpackage?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/appx/Get-AppxPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/appx/Get-AppxPackage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
