### ISSUE TITLE
incorrect IP address shown in example 1

### ISSUE THREAD

**Issue by dmc-tech** [MicrosoftDocs/windows-powershell-docs#3281]
Example 1 uses IP address 10.1.1.10, but the output shows BgpIdentifier            : 192.168.1.10
This is incorrect according to the other examples and is confusing for the reader

PS C:\>Add-BgpRouter -BgpIdentifier 10.1.1.10-LocalASN 64522 -PassThru
RoutingDomain            : 
BgpIdentifier            : 192.168.1.10
LocalASN                 : 64522
CompareMEDAcrossASN      : False
DefaultGatewayRouting    : False
IPv6Routing              : Disabled
LocalIPv6Address         : 
PeerName                 : 
PolicyName               : 
TransitRouting           : Disabled
RouteReflector           : Disabled
ClusterId                : 
ClientToClientReflection :

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b093767b-a520-689a-da34-e1a060d755fd
* Version Independent ID: f7955b94-a3e3-5935-6072-7f5363a2f76b
* Content: [Add-BgpRouter (RemoteAccess)](https://learn.microsoft.com/en-us/powershell/module/remoteaccess/add-bgprouter?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/remoteaccess/Add-BgpRouter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/remoteaccess/Add-BgpRouter.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@dmc-tech Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3621

Once the author approves, then changes will be live.

Thanks
Sri
