### ISSUE TITLE
Reference URL to this page

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/windows-powershell-docs#329]
When I issue a `Get-Help Get-AppxPackage -Online` command in PowerShell, this page (see the URL in the "Content Source" field below) must open. But it doesn't. Instead, I am taken to some [irrelevant destination](https://docs.microsoft.com/en-us/uwp/api/Windows.Management.Deployment.PackageManager).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b59ed2d-1535-135c-bdaf-95dd93a3ef6b
* Version Independent ID: 6dcca508-5e35-5cb4-942b-22a20dbb1a4d
* Content: [Add-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/add-appxpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/add-appxpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @skycommand Thanks for your suggestion, I created a pull request to improve the article based on your comments.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @skycommand Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
