### ISSUE TITLE
Get-ADGroupMember does not work if group has member from child domain

### ISSUE THREAD

**Issue by mcdonamw** [MicrosoftDocs/windows-powershell-docs#3294]
This article mentions Get-ADGroupMember would fail if a group contains a member from another forest, however this appears to also fail if the group has a member from a child domain in the same forest, but the page does not state this.

I'm running into this problem with Powershell v7 x64.  Is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c38b18a-4e4c-e0f9-a709-865c0043340e
* Version Independent ID: 559b8531-73a7-93b9-eb3d-64f0cad86312
* Content: [Get-ADGroupMember (ActiveDirectory)](https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adgroupmember?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/activedirectory/Get-ADGroupMember.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/activedirectory/Get-ADGroupMember.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
