### ISSUE TITLE
-FullFormat

### ISSUE THREAD

**Issue by Gatorz4eva** [MicrosoftDocs/windows-powershell-docs#330]
The parameter in example#2 that reads "-FullFormat" is incorrect. According to the Syntax, you should omit "Format" and instead type "-Full". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a00ccf-8824-b9ca-29f2-f5c8e8278bef
* Version Independent ID: dc541d59-bbc3-cc3d-9b98-79d06870564f
* Content: [Format-Volume (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/storage/Format-Volume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/storage/Format-Volume.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by skycommand** [comment]
Filed a pull request for this: https://github.com/MicrosoftDocs/windows-powershell-docs/pull/384

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
The PR for this issue has been merged. The issue can be closed @AndreaBarr

**Comment by Gatorz4eva** [comment]
This documentation, Example 2, still reads "-FullFormat" instead of "-Full". -FullFormat in incorrect.

**Comment by skycommand** [comment]
It's been corrected here on GitHub but it is not being pushed to docs.microsoft.com or PowerShell help. When Microsoft does this kind of stuff to a product, it is usually a sign that the product is getting the ax.

**Comment by msbemba** [comment]
@Gatorz4eva  Thank you for your feedback. We have modified the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1970 to reflect the change.

Thanks
Sri
