### ISSUE TITLE
Incorrect Partition parameter description

### ISSUE THREAD

**Issue by ostrynskyy** [MicrosoftDocs/windows-powershell-docs#3304]
Starting the Windows Server 2016 version of the page, the Partition parameter has an incorrect description.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2485763-79c0-2ff5-2b82-1d3675f3b6af
* Version Independent ID: 66f25855-82d8-f3d0-26a4-b639405ce47d
* Content: [Get-ADPrincipalGroupMembership (ActiveDirectory)](https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adprincipalgroupmembership?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/activedirectory/Get-ADPrincipalGroupMembership.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/activedirectory/Get-ADPrincipalGroupMembership.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@ostrynskyy Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3591

Once the author approves, the changes will be live.

Thanks
Sri
