### ISSUE TITLE
Installation instructions needed.

### ISSUE THREAD

**Issue by meatbobstrat** [MicrosoftDocs/windows-powershell-docs#3307]
Where to get this module, and how to install would be extremely helpful. I can't find it in the psgallery.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7dab144e-a4b2-18ab-d29d-3dc151d505cd
* Version Independent ID: c56224e1-6594-09c6-8425-a07370b0b69a
* Content: [UpdateServices Module](https://learn.microsoft.com/en-us/powershell/module/updateservices/?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/updateservices/UpdateServices.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/updateservices/UpdateServices.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
