### ISSUE TITLE
more examples for typical scenarios needed

### ISSUE THREAD

**Issue by gitterman** [MicrosoftDocs/windows-powershell-docs#331]
A typical scenario in the Linux world is to have a read only install NFS share for every host in an IP range.
That said I am missing an example how to allow any user (even root) from all my linux boxes to read data from an installation share.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80da8016-ab02-32fb-d14a-f488cf86f69f
* Version Independent ID: f610fad9-478c-c667-84dd-857d96b4dd7e
* Content: [Grant-NfsSharePermission (nfs)](https://docs.microsoft.com/en-us/powershell/module/nfs/grant-nfssharepermission?view=win10-ps)
* Content Source: [docset/windows/nfs/grant-nfssharepermission.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nfs/grant-nfssharepermission.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @gitterman 
Thanks for your feedback, we appreciate it.
I created a PR to add an example for a UNIX-type sharing, please keep in mind that more steps are needed that are out of the scope of this specific cmdlet article.

Hope you find it useful.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @gitterman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
