### ISSUE TITLE
Adding Policy via New-NetQosPolicy results in error in GPEdit GUI

### ISSUE THREAD

**Issue by ucgeek** [MicrosoftDocs/windows-powershell-docs#332]
Error in GPEdit GUI is "Errors while reading policies from this GPO, not all policies are displayed". Seen this on Server 2012R2 and Server 2016. Is this by design? If so doc's should mention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4bb7cf2-5414-66e5-9a92-254d72a222ba
* Version Independent ID: fd6ec687-d40a-8534-0d33-a4d5cd498d5a
* Content: [New-NetQosPolicy (netqos)](https://docs.microsoft.com/en-us/powershell/module/netqos/new-netqospolicy?view=win10-ps)
* Content Source: [docset/windows/netqos/new-netqospolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netqos/new-netqospolicy.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ucgeek thanks for your feedback.
Article was updated after you added this suggestion, https://github.com/MicrosoftDocs/windows-powershell-docs/commit/c9539f5da3dde4a34fb6ad4028a8815283cb089a#diff-656ae923cdc063b67fd62eba3653bb06 thank you

**Comment by yogkumgit** [comment]
@ucgeek Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            
https://answers.microsoft.com/en-us/windows/forum/windows_10?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
