### ISSUE TITLE
Quality: Refactoring documentation for hgsclient module 

### ISSUE THREAD

**Issue by Spoonsk** [MicrosoftDocs/windows-powershell-docs#3328]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/Spoonsk/windows-powershell-docs/tree/main/docset/winserver2022-ps/hgsclient

### Summary

Refactor help for all commandlets to fit the __PowerShell-Docs style guide__

**Comment by michaeltlombardi** [comment]
@Spoonsk would you mind resubmitting this as a [Quality Improvement issue](https://github.com/MicrosoftDocs/windows-powershell-docs/issues/new?assignees=&labels=project-quality&template=02-quality.yml&title=Quality%3A+)? That helps us keep the labels and everything else working smoothly. Thanks!
