### ISSUE TITLE
Throttle Parameters

### ISSUE THREAD

**Issue by maglaubig** [MicrosoftDocs/windows-powershell-docs#333]
Regarding the InputOutputThrottle parameter, is it possible to include some indication if lower values allow for more or less throttling to the deduplication task?  In the InputOutputThrottleLevel parameter it makes a bit more sense to me where Low means little to no throttling.  There isn't a lot of detail out on the Internet for this other than essentially copying the description from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f6e74c-4b27-e045-d262-8cac31d2f9a3
* Version Independent ID: e6eb6dde-2f79-14ff-ad20-067c256ee50e
* Content: [Start-DedupJob (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/start-dedupjob?view=win10-ps)
* Content Source: [docset/windows/deduplication/start-dedupjob.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/start-dedupjob.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by e0i** [comment]
@officedocsbot unassign @e0i

**Comment by get-itips** [comment]
Hello @AndreaBarr  any updates on this? Thanks

**Comment by AndreaBarr** [comment]
@get-itips  I'm still working on figuring out who can help us on this.

**Comment by get-itips** [comment]
Thank you @AndreaBarr

**Comment by dyehya** [comment]
I agree that this needs to be clearer in terms of Low meaning little throttling and high means it is throttled more but the documentation doesn't explicitly state this and not sure of the actual behavior here.

**Comment by sgadsby** [comment]
Yes, please clarify this the documentation everywhere these parameters are specified including Set-DedupSchedule. Dedup Optimisation has a huge impact on IO performance and these parameters are the only way of controlling that impact. The documentation needs to be clearer. It would be helpful to also clarify ThrottleLimit since it uses the same term but I believe is unrelated to IO.

**Comment by sgadsby** [comment]
Hi e0i, what changes have been made? It appears the documentation has not yet been updated for this issue. Cheers.
