### ISSUE TITLE
Quality: Clean up formatting on Add-MpPreference.md

### ISSUE THREAD

**Issue by majst32** [MicrosoftDocs/windows-powershell-docs#3332]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/defender/add-mppreference?view=windowsserver2022-ps

### Summary

Clean up line length, trailing spaces, and add spaces between headers.

### Suggested Fix

Clean up line length, trailing spaces, and add spaces between headers.

**Comment by michaeltlombardi** [comment]
Hi, @majst32! Would you mind reopening this as a [quality project issue](https://github.com/MicrosoftDocs/windows-powershell-docs/issues/new?assignees=&labels=project-quality&template=02-quality.yml&title=Quality%3A+)? We have some automation that triggers on it and that helps us keep things organized. Thanks!
