### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by s-n-ushakov** [MicrosoftDocs/windows-powershell-docs#337]
It would be great to have a list of valid values for the "-CertStoreLocation" parameter incorporated here explicitly, without need for the readers to look for closed issues somewhere...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c694289c-79f5-03cd-38aa-5d2ec76988bd
* Version Independent ID: 0a5a5227-c7da-d308-9fca-857b49f6cf7c
* Content: [Import-Certificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-certificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/import-certificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/import-certificate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @s-n-ushakov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
