### ISSUE TITLE
what are the units???

### ISSUE THREAD

**Issue by arthas1123** [MicrosoftDocs/windows-powershell-docs#340]
this command gives detail information about the disk, but what are the unit??
For example, it shows read and write max latency, but the units are not shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6566d5bd-df6f-e4dc-3075-ad47cc1fa1d5
* Version Independent ID: 33407294-d33e-887a-9265-a91a753f2dee
* Content: [Get-StorageReliabilityCounter (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-storagereliabilitycounter?view=win10-ps#outputs)
* Content Source: [docset/windows/storage/get-storagereliabilitycounter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-storagereliabilitycounter.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @arthas1123 Thanks for your feedback.

At the bottom of the article you will find Outputs, as the cmdlet returns a MSFT_StorageReliabilityCounter object, you can find the units of the output of this cmdlet at 
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/stormgmt/msft-storagereliabilitycounter

Hope this information helps you.

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @arthas1123 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
