### ISSUE TITLE
Not connected to PowerShell help

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/windows-powershell-docs#341]
This page seems not connected to PowerShell help. When I issue a `Get-Help Remove-AppxPackage -Online`, the browser does not open [this page](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps). (It opens the [PackageManager Class](https://docs.microsoft.com/en-us/uwp/api/Windows.Management.Deployment.PackageManager) page instead.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f43873-0e34-6ec2-8bde-479945d49ed9
* Version Independent ID: 914c97a9-7dc2-6ddd-4756-7ec210db3fe8
* Content: [Remove-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/remove-appxpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/remove-appxpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @skycommand thanks for your feedback.

I created a PR to improve the article so the online version link points to a valid url.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @skycommand Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
