### ISSUE TITLE
example 2 parameter wrong

### ISSUE THREAD

**Issue by tofkamp** [MicrosoftDocs/windows-powershell-docs#342]
-StoragePoolFriendlyName should be -FriendlyName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c0bab3-cc82-997f-7125-904880eeb22b
* Version Independent ID: 1860b37c-e780-4241-72f5-49cf8771b218
* Content: [Get-StorageTier (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-storagetier?view=win10-ps)
* Content Source: [docset/windows/storage/get-storagetier.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-storagetier.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Malind19** [comment]
@kenwith Created the PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/922

**Comment by e0i** [comment]
@AndreaBarr Please have the PR #922 for this issue reviewed. Thanks.

**Comment by e0i** [comment]
@tofkamp  Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
