### ISSUE TITLE
Update documentation to include parameter `-AllUsers`

### ISSUE THREAD

**Issue by Borkason** [MicrosoftDocs/windows-powershell-docs#343]
Windows version 1803 ships command `Remove-AppxProvisionedPackage` with a parameter `-AllUsers`. This parameter is not documented and needs to be added.

Edit: A working example is important as `-AllUsers` throws a errors when used. See #344 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e68b166-c0e9-8a54-6791-8d7d4ffc27cc
* Version Independent ID: f27cda42-9366-2d0f-a332-8b494962fe25
* Content: [Remove-AppxProvisionedPackage (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/remove-appxprovisionedpackage?view=win10-ps)
* Content Source: [docset/windows/dism/remove-appxprovisionedpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/remove-appxprovisionedpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by martinzugec** [comment]
Agree, was surprised to find out this is not mentioned in documentation.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by martinzugec** [comment]
Could we get better explanation of what it does @e0i please? Currently it says "Execute the command to all users."

My understanding is that -AllUsers will not affect provisioning (the main purpose of the cmdlet), but rather removed already provisioned apps from existing profiles. I am afraid that the help section does not really explain what this is used for. Thanks!

**Comment by Borkason** [comment]
The update is lazy and doesn't even work. See #344.

@officedocsbot open

**Comment by Borkason** [comment]
@officedocsbot open

**Comment by Borkason** [comment]
@coreyp-at-msft Please reopen this ticket. I can't get @officedocsbot to do it.

**Comment by Borkason** [comment]
It's probably my fault that I didn't merge both issues. This left #343 in a bit of a haze. Glad that I could clear this up however.

**Comment by e0i** [comment]
See: #344

**Comment by e0i** [comment]
@officedocsbot close
