### ISSUE TITLE
How exactly does -AllUsers work?

### ISSUE THREAD

**Issue by Borkason** [MicrosoftDocs/windows-powershell-docs#344]
How exactly does `-AllUsers` work? I have never - since it was introduced - managed to remove a single package with `-AllUsers`. Please clarify the documentation.

```powershell
PS C:\> Get-AppxPackage -AllUsers -Name Microsoft.MicrosoftSolitaireCollection | select name

Name
----
Microsoft.MicrosoftSolitaireCollection


PS C:\> Get-AppxPackage -AllUsers -Name Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage -AllUsers
Remove-AppxPackage : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
At line:1 char:74
+ ... Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage -AllUsers
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand

PS C:\> Get-AppxPackage -Name Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage -AllUsers
Remove-AppxPackage : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
At line:1 char:64
+ ... Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage -AllUsers
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand

PS C:\> Get-AppxPackage -Name Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage
PS C:\> # Without -AllUsers this finally worked.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f43873-0e34-6ec2-8bde-479945d49ed9
* Version Independent ID: 914c97a9-7dc2-6ddd-4756-7ec210db3fe8
* Content: [Remove-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/remove-appxpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/remove-appxpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Borkason Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by Borkason** [comment]
@yogkumgit No man, the PR is trash. I commented about that there. The commands are broken and the PR doesn't address how they work at all. You should have at least looked at that before closing this ticket. This makes not wanna try to improve documentations at all anymore, if you at Microsoft don't take the time to quality check.

I hope this wasn't a waste of my time...

**Comment by Borkason** [comment]
@yogkumgit Have you looked at my comments about that PR? The explanation is wrong. The quality is bad. And worst of all, the PR does not address this issue **at all**, which is blatantly obvious but you didn't even care to read into it.

I expected more from a project manager and consultant, than closing a valid issue that is still very much unsolved!

This is the second time a ticket of mine was closed for stupid reasons. If that is how it works, I will stop contributing anything, because I know better things to *waste my time* with.

Goodbye.

**Comment by kenwith** [comment]
@yogkumgit @get-itips see above.

@Borkason - we are doing the best we can and really appreciate your contributions. We don't take offense when we make a mistake on closing one and it is OK to re-open. We are all learning and trying to get better.

**Comment by Borkason** [comment]
> We don't take offense when we make a mistake on closing one and it is OK to re-open

It would be easier if we could reopen ourselves. Communication is hard enough with Microsoft as it is. I don't really want to hope and pray that it's being reopened. This is stressful. I just wanna do it.

**Comment by kenwith** [comment]
I agree. I thought the person that opened the original issue could also open it again themselves. I wonder if it has to do with the Issue being opened from the document in docs.microsoft.com (bottom of the page).

I think if an issue is opened in GitHub directly then person that opened it can re-open at any time. 

I am going to look into how these can be changed so you can re-open. I agree if someoen can open an issue they should be able to re-open an issue.

**Comment by Borkason** [comment]
No, I couldn't re-open the ticket as well as the other one. The button wasn't there. I can only close my open tickets. Thanks for looking into this.

**Comment by e0i** [comment]
@Borkason In our investigation we have found that there might be a bug.

Our team has been reviewing the issue for couple of days and they have not been able to "find a working combination of the Remove-AppXPProvisionedPackage with the -AllUsers parameter"
 
We suspect that "AllUsers parameter might be in the source code but doesn't work;" and note, "-AllUsers parameter seems to be valid for Get-AppxPackage and Remove-AppXPPackage"

We are doing our best to track this down and get this issue resolved accordingly.

Thank you for your comments and patience.

**Comment by kenwith** [comment]
@Borkason - I believe we have functionality now where the person that originally opened an issue can reopen a closed issue by just commenting on it. I am going to close this one and please try to comment and let's see if it opens automatically. If not I will manually reopen it.

**Comment by Borkason** [comment]
Test to reopen.

**Comment by kenwith** [comment]
Just an update, @AndreaBarr is looking for a member of product team to discuss this with. We are hoping to find the right contact soon.

**Comment by levick93** [comment]
I am having this issue also. I need to remove ZuneVideo from all users as some of our users dont have admin permissions to run the Remove-AppxPackage command and we cant set VLC media player as default with ZunoVideo installed. Looking forward to a solution.

**Comment by jszabo98** [comment]
-AllUsers works in Windows 10 1809 only.

**Comment by get-itips** [comment]
Hello @jszabo98 thanks for your contribution, I could also verify that -AllUsers works in 1809 build.
Hope it works for @Borkason too, in the meantime, I'll add a pull request to propose modifying the current note in the article.

**Comment by Borkason** [comment]
@get-itips I can't confirm that for 1809 at this point, because I am on 20H1 (Build 18922). But if it works for 1809, it should work for 20H1, no?

This is what I get.

```PowerShell
PS C:\WINDOWS\system32> Get-AppxPackage -Name Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage -AllUsers     Remove-AppxPackage : Removal failed. Please contact your software vendor.                                               Deployment Remove operation with target volume C: on Package
Microsoft.MicrosoftSolitaireCollection_4.4.6132.0_x64__8wekyb3d8bbwe from:   failed with error 0x80070002. See
http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
At line:1 char:64
+ ... Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage -AllUsers
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Comman
   ds.RemoveAppxPackageCommand

PS C:\WINDOWS\system32> Get-AppxPackage -Name Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage
PS C:\WINDOWS\system32>
```PowerShell

**Comment by get-itips** [comment]
@Borkason what I ran was:

`Get-AppxPackage -Name Microsoft.MicrosoftSolitaireCollection -AllUsers | Remove-AppxPackage -AllUsers `

Using -AllUsers in both cmdlets.

**Comment by Borkason** [comment]
@get-itips Thanks for noticing. Even with your command, same error. Perhaps it's a problem with the insider build. I need to check with my 1903 build at work, next week.

**Comment by get-itips** [comment]
@Borkason yes, insiders can be a whole different story. Please get back with the 1903 result next week.
Thanks

**Comment by jszabo98** [comment]
Try taking the -allusers off get-appxpackage.  All you need is the fullpackagename.

**Comment by Borkason** [comment]
I can confirm that it works in 1809.

**Comment by chrismholmes1** [comment]
I still see these issues in both 1909 and 20H2, but I believe it to also be a bug in the deisgn.

If I tried to remove all packages of a particular version, it works, however in our Enterprise, its seems more complicated than that.

Take for instance: 
Microsoft.WebMediaExtensions

I have two versions installed after running a store update. (1.0.13321.0 and 1.0.40831.0)
4 users have 1.0.13321.0
1 user and the system account has 1.0.40831.0
I need to remove the older version per Cyber Team.

Technically I should be able to run: 
Get-AppxPackage -allusers Microsoft.WebMediaExtensions*| Where-Object Version -lt '1.0.40631.0'|Remove-AppxPackage -allusers

But this fails when running from as the system account with the same error message from the top of this request.
If I run it as an admin account that is remote but not logged in I get: Remove-AppxPackage : An error occurred because a user was logged off.
If I run the command as an administrator that has a full profile logged on to the machine it works, but I have to run it twice.

Is this by design?
Why is the store not updating the plugin and removing the old one entirely?

If needed, I am happy to open a new request.
