### ISSUE TITLE
FilePathRule accepts wildcard characters but the document says it doesn't

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-powershell-docs#3461]
FilePathRule parameter:

https://learn.microsoft.com/en-us/powershell/module/configci/new-cipolicyrule?view=windowsserver2022-ps#-filepathrule

Accepts wildcards but its description says it doesn't.

There are even examples in the same document that shows it accepts wildcards:
https://learn.microsoft.com/en-us/powershell/module/configci/new-cipolicyrule?view=windowsserver2022-ps#example-4-specify-a-policy-rule-for-a-folder-path-with-wildcards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d20e9-996d-98cc-1866-261ca4d51f46
* Version Independent ID: e971f828-e670-0108-f95a-7ae602b4ad94
* Content: [New-CIPolicyRule (ConfigCI)](https://learn.microsoft.com/en-us/powershell/module/configci/new-cipolicyrule?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/configci/New-CIPolicyRule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/configci/New-CIPolicyRule.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@HotCakeX Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3593

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by HotCakeX** [comment]
@msbemba Thank you!
