### ISSUE TITLE
Not workling in Windows 10

### ISSUE THREAD

**Issue by prochor666** [MicrosoftDocs/windows-powershell-docs#3464]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8444a866-0018-8607-ca2c-040c5967840c
* Version Independent ID: 7aced3e1-6ecc-bf15-5e80-8e5df67225e6
* Content: [New-SmbGlobalMapping (SmbShare)](https://learn.microsoft.com/en-us/powershell/module/smbshare/new-smbglobalmapping?view=windowsserver2022-ps&viewFallbackFrom=windowsserver2019-ps)
* Content Source: [docset/winserver2022-ps/smbshare/New-SmbGlobalMapping.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/smbshare/New-SmbGlobalMapping.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
