### ISSUE TITLE
Jessica Quintanilla 

### ISSUE THREAD

**Issue by diaz405** [MicrosoftDocs/windows-powershell-docs#347]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 365e840b-b205-3514-bc91-e5be2b1992d5
* Version Independent ID: 155d4094-ae65-d476-b476-8d9e73016ab1
* Content: [Set-ADDomainMode (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/set-addomainmode?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Set-ADDomainMode.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Set-ADDomainMode.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello, @diaz405 could you please tell us what is the issue description for the referenced article? thank you

**Comment by yogkumgit** [comment]
@diaz405  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by yogkumgit** [comment]
@officedocsbot close
