### ISSUE TITLE
Document preconditions

### ISSUE THREAD

**Issue by keccs** [MicrosoftDocs/windows-powershell-docs#348]
An exception is thrown if the apppool is already stopped when this is called.
Please document this behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eab160df-e007-21d9-b75d-32a0c7a4c4d9
* Version Independent ID: 728ad110-f266-9b0b-431b-644532d11656
* Content: [Stop-WebAppPool (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/stop-webapppool?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/Stop-WebAppPool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/Stop-WebAppPool.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @keccs 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
