### ISSUE TITLE
When it isn't successful, then what?

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/windows-powershell-docs#349]
"The Disable-WindowsErrorReporting cmdlet returns $True if it is successful. Otherwise, it returns $False." That's great. So when it returns $False, what's the next step to get it to return $True?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf6dc60-7aff-ff5b-f426-09dc77a55f1f
* Version Independent ID: 69d5a644-2750-6d63-3ac9-cabb3eff1c02
* Content: [Disable-WindowsErrorReporting (windowserrorreporting)](https://docs.microsoft.com/en-us/powershell/module/windowserrorreporting/disable-windowserrorreporting?view=win10-ps)
* Content Source: [docset/windows/windowserrorreporting/disable-windowserrorreporting.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/windowserrorreporting/disable-windowserrorreporting.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by VLG17** [comment]
@MichaelMc64 you can use other methods such as 

1. "Services.msc" -> set Windows Error Reporting Service to disabled.
2. HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting -> set Disabled DWORD to 1 (or create it if it's not present)

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and sharing this explanation. @MichaelMc64 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
