### ISSUE TITLE
can you provide the possible values expected/returned by the command.  i.e., running, stopped, etc.

### ISSUE THREAD

**Issue by unofficiallyInsave** [MicrosoftDocs/windows-powershell-docs#3492]
can you provide the possible values expected/returned by the command.  i.e., running, stopped, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43cf4b12-5f26-c81c-554e-127149c6edd0
* Version Independent ID: 1573d864-40af-1a70-fc6c-b0a5390e3c3d
* Content: [Get-WebAppPoolState (WebAdministration)](https://learn.microsoft.com/en-us/powershell/module/webadministration/get-webapppoolstate?view=windowsserver2022-ps&wt.mc_id=ps-gethelp)
* Content Source: [docset/winserver2022-ps/webadministration/Get-WebAppPoolState.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/webadministration/Get-WebAppPoolState.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
