### ISSUE TITLE
PowerShell 7 module compatibility not in WindowsCompatibility

### ISSUE THREAD

**Issue by crisman** [MicrosoftDocs/windows-powershell-docs#3497]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/windows/module-compatibility?view=windowsserver2022-ps
- https://learn.microsoft.com/en-us/powershell/windows/module-compatibility?view=windowsserver2019-ps
- https://learn.microsoft.com/en-us/powershell/windows/module-compatibility?view=windowsserver2016-ps

### Summary

The docs for PowerShell 7 module compatibility have this text:

> ```
> If you have information to share or issues with specific modules, please file an issue in the
> [WindowsCompatibility repo](https://github.com/PowerShell/WindowsCompatibility).
> ```

It is not the place to file an issue as that repo was archived in 2021 and it is not possible to open a new issue there.

Archived 2021 June 16:
https://github.com/PowerShell/WindowsCompatibility

**Comment by sdwheeler** [comment]
For modules that ship in Windows, use the Windows Feedback Hub. For more information,
see [Send feedback to Microsoft with the Feedback Hub app][1].

[1]: https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
