### ISSUE TITLE
Link for CreateNonDADkmContainer.ps1 does not work

### ISSUE THREAD

**Issue by aszego** [MicrosoftDocs/windows-powershell-docs#35]
In windows-powershell-docs/docset/windows/adfs/install-adfsfarm.md, example 5 and 6 refer to CreateNonDADkmContainer.ps1.

I couldn't find where CreateNonDADkmContainer is documented, and the link on this page is broken - furthermore, formatting is wrong - instead of appearing as an actual link <a/>, it's inserted into to the text with missing whitespace.

**Comment by brianlic-msft** [comment]
@aszego Thanks for the feedback.  I've passed it along to the engineering team.

**Comment by tvuylsteke** [comment]
I believe the content has now been made available. Both the script and the guidance are now succesfully reachable when following the fwd link. Meaning https://go.microsoft.com/fwlink/?linkid=832923 now actually links to the correct content. So this issue can probably be closed.

**Comment by kdutt** [comment]
Link is broken again?
