### ISSUE TITLE
Missing info on `-AutomaticCheckpointsEnabled` 

### ISSUE THREAD

**Issue by MiguelAlho** [MicrosoftDocs/windows-powershell-docs#350]
I am not totally aware if this switch should be documented (or not). I have ound it used in some projects (such as Vagrant as in https://github.com/hashicorp/vagrant/blob/8aa74a03a09bfab203d1866fc5f3e4476bb1657f/plugins/providers/hyperv/scripts/configure_vm.ps1#L109 or Packer in https://github.com/hashicorp/packer/blob/master/common/powershell/hyperv/hyperv.go#L281) but the current documentation does not mention it.

There is some TechNet forum posts refering to it also (https://social.technet.microsoft.com/Forums/en-US/2b8225c6-4bbd-4871-adf5-95ca71590601/purpose-of-quotautomatic-checkpointsquot-in-hyperv-2012-r2?forum=winserverhyperv) and some confusion between the value in Win10 and Server 2016. 

I don't know enough about it to submit a PR, and some doc would be useful to debug a problem I currently have on a command that trys to set that switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44052838-1ef0-1252-fcd6-eae568fde8de
* Version Independent ID: 880e9868-f548-49ef-717a-a06a3c58cf2a
* Content: [Set-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/set-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/set-vm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/set-vm.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @MiguelAlho  thanks for your feedback.
Article was updated after you added this suggestion, thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @MiguelAlho 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
