### ISSUE TITLE
DisableSmtpParsing parameter is missing in Set-MpPreference

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-powershell-docs#3505]
`DisableSmtpParsing` parameter is available in Windows 11 build 22621.1778 Stable channel in Defender module's Set-MpPreference cmdlet but isn't listed in [the document page.](https://learn.microsoft.com/en-us/powershell/module/defender/set-mppreference)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44f43117-c0f9-84e2-9a2a-0335f516f7d0
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (Defender)](https://learn.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/defender/Set-MpPreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/defender/Set-MpPreference.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@HotCakeX Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3684

Once the author approves, the changes will be live.

Thanks
Sri
