### ISSUE TITLE
Example 2: Create BITS transfer jobs that download multiple files, precision

### ISSUE THREAD

**Issue by 4lex11s** [MicrosoftDocs/windows-powershell-docs#351]
If the contents of the file do not have a header (that is, the first line composed as follows: Source, Destination):
    Import-CSV -Path filelist.txt -Header Source ,Destination  |  Start-BitsTransfer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2562033-cf25-0447-81e1-397a973c5c49
* Version Independent ID: 63016f51-2ccf-fdb0-5e29-16418508ce64
* Content: [Start-BitsTransfer (bitstransfer)](https://docs.microsoft.com/en-us/powershell/module/bitstransfer/start-bitstransfer?view=win10-ps)
* Content Source: [docset/windows/bitstransfer/start-bitstransfer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitstransfer/start-bitstransfer.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
hello @4lex11s 
Thanks for your comments.
I created a PR to improve the article based in your comments.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @4lex11s Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
