### ISSUE TITLE
International module missing

### ISSUE THREAD

**Issue by marfarfan01** [MicrosoftDocs/windows-powershell-docs#3513]
How can I install International module?
Find-Module -Filter international only provides one result that does not match with the required

I need to use Copy-UserInternationalSettingsToSystem or something similar

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbd958ae-eeae-3b6e-f6cd-c6706c2e2b77
* Version Independent ID: 6b8f863d-6ddf-7a68-299e-edff51bd3a68
* Content: [International Module](https://learn.microsoft.com/en-us/powershell/module/international/?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/international/International.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/international/International.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by marfarfan01** [comment]
I thought the documentation was wrong because the module does not exist. That's why I used this channel.
