### ISSUE TITLE
Call out the migration of the user password

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-powershell-docs#3514]
While it might be implied to some readers, other migration tools, such as Microsoft's ADMT have special considerations for migrating passwords across domains. It would be helpful for this article to state that the cmdlet moves the user's password when a user (or computer?) object is moved across domains within a forest.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc3dc3a0-1880-7778-0a45-9161d4c0cf2c
* Version Independent ID: 32af66e6-eb73-89fc-8545-7d922b415885
* Content: [Move-ADObject (ActiveDirectory)](https://learn.microsoft.com/en-us/powershell/module/activedirectory/move-adobject?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/activedirectory/Move-ADObject.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/activedirectory/Move-ADObject.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Mike-Crowley Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3592

Once the author approves, the changes will be live.

Thanks
Sri
