### ISSUE TITLE
Please provide guidelines to download for users of Windows 11

### ISSUE THREAD

**Issue by serdar** [MicrosoftDocs/windows-powershell-docs#3515]
Hello,
The RSAT tools are not available for Windows 11 (pro) users via Optional Features. Can you please suggest an alternative method to use the ActiveDirectory module on Windows 11 clients.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71f02a40-4deb-c9b6-a306-bc5765b2e1bc
* Version Independent ID: f1aad6a1-fbc4-df50-d470-81e5cd83fabc
* Content: [ActiveDirectory Module](https://learn.microsoft.com/en-us/powershell/module/activedirectory/?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/activedirectory/ActiveDirectory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/activedirectory/ActiveDirectory.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by HotCakeX** [comment]
Hi, they are available, you can find them in this path:

Settings => Apps => Optional Features => View features

![image](https://github.com/MicrosoftDocs/windows-powershell-docs/assets/118815227/3d7d5e7a-7ccd-4dd4-ad4e-52f14bb6892c)
