### ISSUE TITLE
Usage of -ServicePrincipalNames when creating gMSA accounts

### ISSUE THREAD

**Issue by dhirajhn** [MicrosoftDocs/windows-powershell-docs#353]
As per the example the usage will look like below for gMSA accounts,
New-ADServiceAccount gMSAsqlservice -ServicePrincipalNames @{Add='MSSQLSvc/sqlserver.contoso.com:GMSA','MSSQLSvc/sqlserver.contoso.com:&lt;port#&gt;'} -DNSHostName gMSAsqlservice.contoso.com -PrincipalsAllowedToRetrieveManaged SQL_gMSA_group

We always get the below error,

New-ADServiceAccount : The name reference is invalid
At line:1 char:1
+ New-ADServiceAccount gMSAsqlservice -ServicePrincipalNames @{Add="MSSQLSvc/sql ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CN=gMSAsqlservice,CN=Man...=contoso,DC=com:String) [New-ADServiceAccount], ADException
    + FullyQualifiedErrorId : ActiveDirectoryServer:8373,Microsoft.ActiveDirectory.Management.Commands.NewADServiceAccount

Was able to fix the issue using the below format. Not sure if the approach was correct but SPNs did get auto-registered in SQL Server.

New-ADServiceAccount gMSAsqlservice -ServicePrincipalNames ("MSSQLSvc/sqlserver.contoso.com:GMSA","MSSQLSvc/sqlserver.contoso.com:&lt;port#&gt;") -DNSHostName gMSAsqlservice.contoso.com PrincipalsAllowedToRetrieveManaged SQL_gMSA_group
************************************************************************************************************
Questions :
*****************************************
1&gt; Which is the correct syntax to create gMSA using -ServicePrincipalNames ? 
2&gt; In the above example I have just used one server SPNs[ie., sqlserver]. But when we have several servers added to the gMSA Security Group, how do we use -ServicePrincipalNames?

I feel we need to have more elaborate explanations to the -ServicePrincipalNames. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd731d8-61d8-f6b3-0e8a-3decfe25a184
* Version Independent ID: 3338b8fe-1364-ecd7-eb5c-5ab25d054df7
* Content: [New-ADServiceAccount (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps#required-parameters)
* Content Source: [docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @dhirajhn thanks for your feedback.
The examples present in the live current version of the article, for -ServicePrincipalNames are actually valid for the Set- cmdlet. Will create a PR to remove them. The valid example is the one at the top in the Examples section.
Thanks for noting this.

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR #https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1138     and kindly provide your feedback

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @dhirajhn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
