### ISSUE TITLE
Get-SystemPrefferedUILanguage in Example is misspelled.

### ISSUE THREAD

**Issue by dfishel** [MicrosoftDocs/windows-powershell-docs#3532]
Example Get-SystemPrefferedUILanguage should be Get-SystemPreferredUILanguage

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d537110e-e53c-10ed-ee95-308881fab1cf
* Version Independent ID: cabd2a86-b526-7512-6eef-1b376a07068f
* Content: [Get-SystemPreferredUILanguage (LanguagePackManagement)](https://learn.microsoft.com/en-us/powershell/module/languagepackmanagement/get-systempreferreduilanguage?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/languagepackmanagement/Get-SystemPreferredUILanguage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/languagepackmanagement/Get-SystemPreferredUILanguage.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@scanum There is already a PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3533 to fix this.
