### ISSUE TITLE
ServicePrincipalNames examples are wrong

### ISSUE THREAD

**Issue by jvierrajrv** [MicrosoftDocs/windows-powershell-docs#354]
ServicePrincipalNames examples are wrong.  They are for "Set-ServiceAccount". "New-ServiceAccout takes a [string[]] and not a hash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8e2b47-a29a-04c7-261d-752df5afa122
* Version Independent ID: e66770b5-1cf3-617d-d7f6-6d334501075a
* Content: [New-ADServiceAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=win10-ps)
* Content Source: [docset/windows/addsadministration/new-adserviceaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/new-adserviceaccount.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by poortom1004** [comment]
For the DNSHostName parameter, what exactly is supposed to be sepecified?  The DNS record that will be using the gmsa?

**Comment by e0i** [comment]
@AndreaBarr Please have the PR #909 for this issue reviewed. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
