### ISSUE TITLE
New-StoragePool command return code 61002 

### ISSUE THREAD

**Issue by BenM3RS** [MicrosoftDocs/windows-powershell-docs#3545]
On Azure VM (2016) 
New-StoragePool command I get the following error
New-StoragePool -StorageSubSystemUniqueId $storageuniqueid -FriendlyName 'Mypool' -PhysicalDisks $Disks
New-StoragePool : The operation failed with return code 61002 
with Err, I found it's related to : "INVALID_VERSION_LEVEL" but no more information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba9f3c2-455a-e866-56fb-b9b3425559a6
* Version Independent ID: b2332c94-b147-fcfb-1b8a-83c0dd1f99a3
* Content: [New-StoragePool (Storage)](https://learn.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/storage/New-StoragePool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/storage/New-StoragePool.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@BenM3RS Thank you for your feedback. This seems to be a technical issue as the cmdlet works fine on another machine. We recommend contacting Microsoft support, so that our support engineers can help you fix this issue.

Hope this helps!

Thanks
Sri
