### ISSUE TITLE
error on the examples

### ISSUE THREAD

**Issue by tofkamp** [MicrosoftDocs/windows-powershell-docs#355]
Error on example 1
Enable-ClusterStorageSpacesDirect : A parameter cannot be found that matches parameter name 'cluster'.
At line:1 char:35
Error on example 2
Enable-ClusterStorageSpacesDirect : The input object cannot be bound to any parameters for the command either because
the command does not take pipeline input or the input and its properties do not match any of the parameters that take
pipeline input.
At line:1 char:15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1028227e-51ad-854a-ca48-e176894cdb34
* Version Independent ID: 1967653d-ebb8-7a06-af67-8359e8a85bdd
* Content: [Enable-ClusterStorageSpacesDirect (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/enable-clusterstoragespacesdirect?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/enable-clusterstoragespacesdirect.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/enable-clusterstoragespacesdirect.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tofkamp thanks for your feedback, I created a pair of pool requests to correct the examples. 
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR Removed non working examples #1139 and Removed non working examples #1140  and kindly provide your feedback

**Comment by tseward** [comment]
Looks good.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @tofkamp Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
