### ISSUE TITLE
List of available keyboard

### ISSUE THREAD

**Issue by boivsamuel** [MicrosoftDocs/windows-powershell-docs#356]
It wouldn't hurt if there was a link to other possible values for -InputTip than the English US provided in the example. Been looking for the French Canadian value for 15 minutes!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d39c4f9b-ac44-600e-baac-9be75e37bff0
* Version Independent ID: 38f79fa5-f789-912b-a77b-7434c1ef99dd
* Content: [Set-WinDefaultInputMethodOverride (international)](https://docs.microsoft.com/en-us/powershell/module/international/set-windefaultinputmethodoverride?view=win10-ps)
* Content Source: [docset/windows/international/set-windefaultinputmethodoverride.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/international/set-windefaultinputmethodoverride.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Jadaw1n** [comment]
What's the value and where did you find that?

**Comment by mancze** [comment]
Doh, looking for the same list. I'm trying to solve the problem when win10 adds keyboard layouts on its own and they are not even listed in the languages settings so cannot be removed. Boo!

**Comment by sowjanya365** [comment]
Hi @boivsamuel 

Thanks for your patience and contribution. Much appreciated. 

Please refer to the below URL for "Default Input Profiles (Input Locales) in Windows". 

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs

Hope this information helps you. Kindly confirm. Thank you.

**Comment by e0i** [comment]
Hello @boivsamuel 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
