### ISSUE TITLE
New-Cluster for Win2022 is missing a parameter "-ManagementPointNetworkType"

### ISSUE THREAD

**Issue by codebuilder8** [MicrosoftDocs/windows-powershell-docs#3560]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/failoverclusters/new-cluster?view=windowsserver2022-ps

### Summary

New-Cluster for Win2019 has a parameter for -ManagementPointNetworkType but the doc for Win2022 is missing it.

### Suggested Fix

Include -ManagementPointNetworkType in the parameter for Win2022.

**Comment by msbemba** [comment]
@codebuilder8 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3590

Once the author approves, the changes will be live.

Thanks
Sri
