### ISSUE TITLE
Get-PrintJob  -id  - use with wildcard generates an error - documentation is ambiguous.

### ISSUE THREAD

**Issue by Ferretaa** [MicrosoftDocs/windows-powershell-docs#3583]
This is information needs to be updated.
 At the top it states  "You can use wildcard characters." but then below it has "Accept wildcard characters:	False". 
No further information is provided on what wildcard characters are accepted. 
In my testing if I use "*" I get the following error: 
"
Get-PrintJob : Cannot process argument transformation on parameter 'ID'. Cannot convert value "*" to type "System.UInt32". Error: "Input string was not in a correct
format."
At line:1 char:18
+ get-printjob -id *
+                  ~
    + CategoryInfo          : InvalidData: (:) [Get-PrintJob], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-PrintJob

"

-ID
Specifies the ID of the print job to retrieve. You can use wildcard characters.

Type:	UInt32
Position:	Named
Default value:	None
Accept pipeline input:	False
Accept wildcard characters:	False

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edbed07-de9b-d08f-9d50-83437779a89f
* Version Independent ID: dd366084-4245-efd6-ec7b-60301e948e9f
* Content: [Get-PrintJob (PrintManagement)](https://learn.microsoft.com/en-us/powershell/module/printmanagement/get-printjob?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/printmanagement/Get-PrintJob.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/printmanagement/Get-PrintJob.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@Ferretaa Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3589

Once the author approves, the changes will be live.

Thanks
Sri
