### ISSUE TITLE
Typo at description of Password argument

### ISSUE THREAD

**Issue by MarcoEnxuto** [MicrosoftDocs/windows-powershell-docs#3585]
Name should be replaced by Password.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7691a0e7-40bf-6237-98af-fd094c265a36
* Version Independent ID: a7caa3ef-80f2-8d9d-cc28-1850e30166ff
* Content: [Enable-WebCentralCertProvider (WebAdministration)](https://learn.microsoft.com/en-us/powershell/module/webadministration/enable-webcentralcertprovider?view=windowsserver2022-ps&source=docs)
* Content Source: [docset/winserver2022-ps/webadministration/Enable-WebCentralCertProvider.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/webadministration/Enable-WebCentralCertProvider.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@MarcoEnxuto Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3587

Once the author approves, the changes will be live.

Thanks
Sri
