### ISSUE TITLE
Export-StartLayout always export a default menu , but not my current layout

### ISSUE THREAD

**Issue by Tsjippy** [MicrosoftDocs/windows-powershell-docs#3586]
When I use the Export-StartMenu command like this: `Export-StartLayout -Path d:\layout.xml -UseDesktopApplicationID` it always export a file as shown below and not my current layout. If use the command without the UseDesktopApplicationID param it works, but I get the json, not the xml. I use the latest version of Windows 11

THe file:

`<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" mlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification" Version="1">
  <LayoutOptions StartTileGroupCellWidth="6"/>
    <DefaultLayoutOverride>
      <StartLayoutCollection>
        <defaultlayout:StartLayout GroupCellWidth="6">
          <start:Group Name="Productivity">
            <start:Folder Name="" Size="2x2" Column="2" Row="0">
              <start:SecondaryTile AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" TileID="6501008900" DisplayName="" Size="2x2" Column="4" Row="0" Arguments="-contentTile -url 0 https://excel.office.com" Square71x71LogoUri="ms-appdata:///local/PinnedTiles/6501008900/tinytile.png" Square150x150LogoUri="ms-appdata:///local/PinnedTiles/6501008900/squaretile.png" Wide310x150LogoUri="ms-appx:///" Square310x310LogoUri="ms-appx:///" ShowNameOnSquare150x150Logo="true" ShowNameOnWide310x150Logo="false" BackgroundColor="#ff404040" ForegroundText="light"/>
            <start:SecondaryTile AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" TileID="38975140460" DisplayName="" Size="2x2" Column="2" Row="2" Arguments="-contentTile -url 0 https://powerpoint.office.com" Square71x71LogoUri="ms-appdata:///local/PinnedTiles/38975140460/tinytile.png" Square150x150LogoUri="ms-appdata:///local/PinnedTiles/38975140460/squaretile.png" Wide310x150LogoUri="ms-appx:///" Square310x310LogoUri="ms-appx:///" ShowNameOnSquare150x150Logo="true" ShowNameOnWide310x150Logo="false" BackgroundColor="#ff404040" ForegroundText="light"/>
            <start:SecondaryTile AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" TileID="7603651830" DisplayName="" Size="2x2" Column="2" Row="0" Arguments="-contentTile -url 0 https://word.office.com" Square71x71LogoUri="ms-appdata:///local/PinnedTiles/7603651830/tinytile.png" Square150x150LogoUri="ms-appdata:///local/PinnedTiles/7603651830/squaretile.png" Wide310x150LogoUri="ms-appx:///" Square310x310LogoUri="ms-appx:///" ShowNameOnSquare150x150Logo="true" ShowNameOnWide310x150Logo="false" BackgroundColor="#ff404040" ForegroundText="light"/>
              <start:Tile Size="2x2" Column="4" Row="2" AppUserModelID="Microsoft.Office.OneNote_8wekyb3d8bbwe!microsoft.onenoteim"/>
              <start:SecondaryTile AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" TileID="26310719480" DisplayName="" Size="2x2" Column="0" Row="0" Arguments="-contentTile -url 0 https://outlook.com" Square71x71LogoUri="ms-appdata:///local/PinnedTiles/26310719480/tinytile.png" Square150x150LogoUri="ms-appdata:///local/PinnedTiles/26310719480/squaretile.png" Wide310x150LogoUri="ms-appx:///" Square310x310LogoUri="ms-appx:///" ShowNameOnSquare150x150Logo="true" ShowNameOnWide310x150Logo="false" BackgroundColor="#ff404040" ForegroundText="light"/>
              <start:Tile Size="2x2" Column="0" Row="4" AppUserModelID="Microsoft.SkypeApp_kzf8qxf38zg5c!App"/>
              <start:DesktopApplicationTile Size="2x2" Column="0" Row="2" DesktopApplicationID="Microsoft.SkyDrive.Desktop"/>
            </start:Folder>
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="2" DesktopApplicationID="MSEdge"/>
            <start:Tile Size="2x2" Column="2" Row="2" AppUserModelID="Microsoft.Windows.Photos_8wekyb3d8bbwe!App"/>
            <start:TargetedContentTile Size="2x2" Column="4" Row="2" TileID="T~DynamicLayouts:1!1"/>
            <start:Tile Size="2x2" Column="4" Row="0" AppUserModelID="microsoft.windowscommunicationsapps_8wekyb3d8bbwe!Microsoft.WindowsLive.Mail"/>
            <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe!Microsoft.MicrosoftOfficeHub"/>
           </start:Group>
            <start:Group Name="Explore">
              <start:Folder Name="Play" Size="2x2" Column="4" Row="2">
                <start:TargetedContentTile Size="2x2" Column="4" Row="0" TileID="T~DynamicLayouts:2!3"/>
                <start:TargetedContentTile Size="2x2" Column="2" Row="0" TileID="T~DynamicLayouts:2!2"/>
                <start:TargetedContentTile Size="2x2" Column="4" Row="2" TileID="T~DynamicLayouts:2!6"/>
                <start:TargetedContentTile Size="2x2" Column="0" Row="2" TileID="T~DynamicLayouts:2!4"/>
                <start:TargetedContentTile Size="2x2" Column="2" Row="2" TileID="T~DynamicLayouts:2!5"/>
                <start:TargetedContentTile Size="2x2" Column="0" Row="0" TileID="T~DynamicLayouts:2!1"/>
              </start:Folder>
              <start:TargetedContentTile Size="2x2" Column="0" Row="2" TileID="T~DynamicLayouts:1!4"/>
              <start:TargetedContentTile Size="2x2" Column="2" Row="2" TileID="T~DynamicLayouts:1!5"/>
              <start:TargetedContentTile Size="2x2" Column="4" Row="0" TileID="T~DynamicLayouts:1!3"/>
              <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.WindowsStore_8wekyb3d8bbwe!App"/>
              <start:TargetedContentTile Size="2x2" Column="2" Row="0" TileID="T~DynamicLayouts:1!2"/>
            </start:Group>
          </defaultlayout:StartLayout>
  </StartLayoutCollection>
  </DefaultLayoutOverride>
</LayoutModificationTemplate>`

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
