### ISSUE TITLE
Request clarity on the description of parameter DNSHostName

### ISSUE THREAD

**Issue by SQLHorizons** [MicrosoftDocs/windows-powershell-docs#359]
It is not clear as to what value this parameter must be set to, and the community opinion seem to be split into two camps:-
	• host that uses the managed service account
	• a domain controller in the forest where the gMSA is defigned (Ref: https://social.technet.microsoft.com/Forums/azure/en-US/9a66d1d5-44e9-4ea1-ba9c-88862023c4e1/why-does-a-gmsa-need-a-dns-host-name-e-g-newadserviceaccount-dnshostname?forum=winserver8gen)

I would request this documentation is updated to define the clear function of this parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd731d8-61d8-f6b3-0e8a-3decfe25a184
* Version Independent ID: 3338b8fe-1364-ecd7-eb5c-5ab25d054df7
* Content: [New-ADServiceAccount (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by dgcoward** [comment]
It looks like there are a few of us trying to find out what this mandatory parameter should be set to.  Please update this documentation.

**Comment by Ventilios** [comment]
Any visibility when the -DNSHostName parameter is defined with a better description? From my understanding DnsHostName is the fully qualified domain name of your Service Account Name object (Name parameter + FQDN).

**Comment by ojrb** [comment]
@e0i The PR #985 solved the issue, I have described in detail the parameter **-DNSHostName** to clarify the use of it with the command.

**Comment by e0i** [comment]
@SQLHorizons 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
