### ISSUE TITLE
What does "uses a placeholder a.b.c.0/24 to represent a public Internet address prefix" mean?

### ISSUE THREAD

**Issue by IanMercer** [MicrosoftDocs/windows-powershell-docs#360]
It's not clear from the context or from general usage of the term what a "placeholder" is. Please define the term and/or give a real example with numbers if it's not something you actually type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4152f9f1-ec61-b069-3f15-b5e7a88ee81c
* Version Independent ID: d46c0cf4-2846-b7d2-9918-acada446e05b
* Content: [New-NetNat (netnat)](https://docs.microsoft.com/en-us/powershell/module/netnat/new-netnat?view=win10-ps)
* Content Source: [docset/windows/netnat/new-netnat.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netnat/new-netnat.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@IanMercer 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
