### ISSUE TITLE
Parameter error

### ISSUE THREAD

**Issue by intWang** [MicrosoftDocs/windows-powershell-docs#3603]
[Enter feedback here]

PS C:\Users\rcadmin\Desktop> Set-WinUserLanguageList -LanguageList fi-FR -Confirm Y
Set-WinUserLanguageList : A positional parameter cannot be found that accepts argument 'Y'.
At line:1 char:1
+ Set-WinUserLanguageList -LanguageList fi-FR -Confirm Y
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-WinUserLanguageList], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.InternationalSettings.Commands.SetWinUserLanguageL
   istCommand

PS C:\Users\rcadmin\Desktop> Set-WinUserLanguageList -LanguageList fi-FR -Confirm True
Set-WinUserLanguageList : A positional parameter cannot be found that accepts argument 'True'.
At line:1 char:1
+ Set-WinUserLanguageList -LanguageList fi-FR -Confirm True
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-WinUserLanguageList], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.InternationalSettings.Commands.SetWinUserLanguageL
   istCommand

PS C:\Users\rcadmin\Desktop> Set-WinUserLanguageList -LanguageList fi-FR -Confirm 1
Set-WinUserLanguageList : A positional parameter cannot be found that accepts argument '1'.
At line:1 char:1
+ Set-WinUserLanguageList -LanguageList fi-FR -Confirm 1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-WinUserLanguageList], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.InternationalSettings.Commands.SetWinUserLanguageL
   istCommand

PS C:\Users\rcadmin\Desktop> Set-WinUserLanguageList -LanguageList fi-FR -Confirm $True
Set-WinUserLanguageList : A positional parameter cannot be found that accepts argument 'True'.
At line:1 char:1
+ Set-WinUserLanguageList -LanguageList fi-FR -Confirm $True
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-WinUserLanguageList], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.InternationalSettings.Commands.SetWinUserLanguageL
   istCommand

I want to skip Confirm check .but -Confirm parameter is invalied.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25c7ad20-8060-9e2e-ba64-f45199ded84e
* Version Independent ID: 7e7fd601-419e-671d-8780-826cccd6bb81
* Content: [Set-WinUserLanguageList (International)](https://learn.microsoft.com/en-us/powershell/module/international/set-winuserlanguagelist?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/international/Set-WinUserLanguageList.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/international/Set-WinUserLanguageList.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@intWang 
You can use  this  **Set-WinUserLanguageList -LanguageList fi-FR -Force**

other command
**Set-WinUserLanguageList -LanguageList fi-FR -Confirm**
 then press Y
then press Y

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
