### ISSUE TITLE
Certificate store infr

### ISSUE THREAD

**Issue by gaknigge** [MicrosoftDocs/windows-powershell-docs#363]
There are several PowerShell commands in this section that require the -CertStoreLocation information. but the Examples are not complete. For example, if a command lists \LocalMachine\My, what would be the Current User equivalent? And to what certificate store does My refer? One can take guesses by issuing a command like 
get-childitem cert:\LocalMachine (or cert:\CurrentUser), but again, what tells the reader the My refers to the Personal certificate store? 

It would be too much repetition to include the full list of stores and their parent containers, but if that were done in one document, then this could be referred to in the Related Links area of those PowerShell commands that require a CertStoreLocation parameter..

LocalMachine (Local Computer) certificate stores
TrustedPublisher (Trusted Publishers)
Root (Trusted Root Certification Authorities)
CA (Intermediate Certification Authorities)
My (Personal)
etc.
Thank you for your consideration.
Gary Knigge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c694289c-79f5-03cd-38aa-5d2ec76988bd
* Version Independent ID: 0a5a5227-c7da-d308-9fca-857b49f6cf7c
* Content: [Import-Certificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-certificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/import-certificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/import-certificate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dariomws306** [comment]
Hi @gaknigge, thank you for your feedback.

I have added a reference link about certificate store locations to all the cmdlets in this section with the CertStoreLocation parameter.

**Comment by e0i** [comment]
@gaknigge 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
