### ISSUE TITLE
Error in examples

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/windows-powershell-docs#364]
Example #1 and #3 contain a parameter "-member" but this is not a valid option. The option should be "-members".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 760e7358-72e3-70ff-c581-6a07ed9ad81e
* Version Independent ID: 7b00da3a-b276-0da1-2023-460174a7aab3
* Content: [Remove-ADGroupMember (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/remove-adgroupmember?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Remove-ADGroupMember.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Remove-ADGroupMember.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Malind19** [comment]
@e0i Created PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/973

**Comment by e0i** [comment]
@ggbce  Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
