### ISSUE TITLE
Fixes for clustered DTCs

### ISSUE THREAD

**Issue by dave-sampson13** [MicrosoftDocs/windows-powershell-docs#366]
Do you accept fixes to these cmdlets from the community? I recently had to make a couple of changes to the Test-Dtc cmdlet so that it would work correctly when testing with a clustered DTC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb83e47-15b2-86aa-f296-06a44ff798a5
* Version Independent ID: 68a4a153-4502-6620-4edc-d76829e3bc07
* Content: [Test-Dtc (msdtc)](https://docs.microsoft.com/en-us/powershell/module/msdtc/test-dtc?view=win10-ps)
* Content Source: [docset/windows/msdtc/test-dtc.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/msdtc/test-dtc.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @dave-sampson13 
What kind of fixes? The documentation is open to propose changes but afaik the cmdlets belonging to this module not, can you confirm if the current documentation needs any fix?
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @dave-sampson13 
as explained please feel free to contribute with your expertise to improve the documentation. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
