### ISSUE TITLE
Needs more context for the examples

### ISSUE THREAD

**Issue by darksidemilk** [MicrosoftDocs/windows-powershell-docs#368]
As far as I can find, there's no documentation on what a dynamic category is nor how to make it work.
The context of it makes it seem that you could make ComputerModel type categories for each computer model you have in your network and then use wsus to deploy microsoft update drivers to them. Which would solve the common problem of getting too many drivers from windows update when you try to sync any built in driver product.

However in trying to do this it's a huge pain.
For one it isn't documented that one of the steps to make these even remotely work you need to do something like this
```
$wsus = get-wsusserver -name 'wsus' -port 8530;
$wsusConfig = $wsus.GetConfiguration();
$wsusConfig.TrackDynamicCategories = $true;
$wsusConfig.Save($true);
```
That (which I figured out from member definitions of the iupdateserver object and the configuration methods members, so props on the namings) sets a wsus server to start tracking the dynamic updates you add with this add-wsusdynamic category.
However, adding a dynamic category with this and setting it to be synced causes sync failures with unknown error types. I added a computerModel type dynamic category with the name matching one of the models as listed in wsus. When I set that category to blocked status my syncs started working again.

That's just all a long winded example of what I was able to figure out but because of a lack of documentation on what a dynamic category is and how to fully make it work this function goes unused by most.

So perhaps an about_wsusdynamicCategories needs to exist and be related here.

I have looked at the docs for the IdynamicCategory type but found nothing helpful in explaning what it is just more on the memebers of the class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32519aed-bcec-430c-92d6-2d7d9a49b772
* Version Independent ID: 62dbe24f-05cd-1cc4-adcc-66500ab79267
* Content: [Add-WsusDynamicCategory (wsus)](https://docs.microsoft.com/en-us/powershell/module/wsus/add-wsusdynamiccategory?view=win10-ps)
* Content Source: [docset/windows/wsus/add-wsusdynamiccategory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/wsus/add-wsusdynamiccategory.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by ojrb** [comment]
Hi @e0i The PR #991 solved this issue, please review it and merge !

**Comment by darksidemilk** [comment]
Well thank you good sir. So basically it's something that works with SCCM and not wsus alone.

**Comment by e0i** [comment]
Hello, @darksidemilk We'll close this issue once the referenced PR gets merged.

Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot reopen

**Comment by e0i** [comment]
@darksidemilk 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
