### ISSUE TITLE
Grant-VMConnectAccess is still working?

### ISSUE THREAD

**Issue by fxzxmicah** [MicrosoftDocs/windows-powershell-docs#3685]
I cannot use vmconnect.exe with non-administrator privileges after I have added access permission using this command for my user account. Is this normal?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84b2057a-c2b1-32fe-b516-b50439217f4f
* Version Independent ID: 7c8e1ead-de49-4e0a-b69f-3bc9f3f6b5ab
* Content: [Grant-VMConnectAccess (Hyper-V)](https://learn.microsoft.com/en-us/powershell/module/hyper-v/grant-vmconnectaccess?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/hyper-v/Grant-VMConnectAccess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/hyper-v/Grant-VMConnectAccess.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
