### ISSUE TITLE
repair-virtualdisk vs repair-volume

### ISSUE THREAD

**Issue by boffies** [MicrosoftDocs/windows-powershell-docs#370]
Please explain the difference between using repair-virtualdisk and repair-volume.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5aa827a-0c73-3c62-5b15-c240cc4d2e1b
* Version Independent ID: b59d7a31-3c1b-12b4-b0ab-5de6f6017de6
* Content: [Repair-VirtualDisk (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/repair-virtualdisk?view=win10-ps)
* Content Source: [docset/windows/storage/repair-virtualdisk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/repair-virtualdisk.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @boffies 
Thanks for your feedback, 
You can find the diff between this two concepts [here](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/stormgmt/msft-volume) and [here](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/stormgmt/msft-virtualdisk) 

Besides that, I do not see a need to change the referenced article.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @boffies
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
officedocsbot close

**Comment by yogkumgit** [comment]
@officedocsbot close
