### ISSUE TITLE
What Does This Do Exactly?

### ISSUE THREAD

**Issue by aolszowka** [MicrosoftDocs/windows-powershell-docs#371]
At very least it appears to disable the Registry Key in HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting by setting Disabled = 1 however there are several other options here, for us we also expect to have DontShowUI Set, but this tooling obviously does not do it perhaps it would be good to link the underlying documentation and describe what is done by this task https://docs.microsoft.com/en-us/windows/desktop/wer/wer-settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf6dc60-7aff-ff5b-f426-09dc77a55f1f
* Version Independent ID: 69d5a644-2750-6d63-3ac9-cabb3eff1c02
* Content: [Disable-WindowsErrorReporting (windowserrorreporting)](https://docs.microsoft.com/en-us/powershell/module/windowserrorreporting/disable-windowserrorreporting?view=win10-ps)
* Content Source: [docset/windows/windowserrorreporting/disable-windowserrorreporting.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/windowserrorreporting/disable-windowserrorreporting.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by MaratMussabekov** [comment]
Hello @aolszowka , please check https://github.com/MicrosoftDocs/windows-powershell-docs/pull/865 , is it what are you talking about? or you mean anything else?
Thank you

**Comment by e0i** [comment]
@kenwith PR #865 available for the issue.

**Comment by aolszowka** [comment]
@MaratMussabekov Not quite; we want to understand which registry keys are being disabled by this specific task.

Based on the Windows Documentation there are plenty of things that *could* be happening; but because the documentation for this task is vague its unclear. Is there a link to the implementation of this cmdlet?

**Comment by MaratMussabekov** [comment]
Dear @aolszowka , this cmdlet set registry key "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\Disabled" to the value 1. 
However, cmdlet descriptions in Microsoft docs do not usually specify this kind of information. I mean, it is usually "cmdlet disables Windows Error Reporting on the server...", not "this cmdlet changes the value of the registry key..."

What do you think?

Thank you

**Comment by aolszowka** [comment]
@MaratMussabekov Sounds good to me; the reason I think this originally came about is we thought that you needed to set DontShowUI in addition to setting the disable flag. I think we can close it out as resolved with the additional documentation change to link the Windows Docs as you did in your PR.
