### ISSUE TITLE
New Idea, Move Tickets to GitHub instead of away from it....

### ISSUE THREAD

**Issue by agowa** [MicrosoftDocs/windows-powershell-docs#3717]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

Is this supposed to be a joke? WTF?!?

This is not an improvement, this is one huge step backward (or fifty) and a huge recession. If at all you should move more stuff to GitHub. And if your only issue is about "having to login and register", well let one of your bots open the tickets instead...

At a minimum you could be honest why you're moving away. It has clearly nothing to do with people "having to login and register at GitHub", as letting one of your countless bots just post to GitHub using a webhook would have been way easier...

### Details

> To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 
> 
> As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.
> 
> If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.
> 
> With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.
> 
> Here's what the new experience looks like.
> 
> **Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.
> 
> First, select whether the article was helpful:
> 
> ![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)
> 
> Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:
> 
> | Article was helpful | Article was unhelpful |
> |:--|:---|
> |![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|
> 
> Finally, select **Submit** and you're done!

_Originally posted by @officedocspr5 in https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3302#issuecomment-1846483251_
            

### Proposed Content Type

About Topic, Concept, Other / Unknown

**Comment by darrelle-kn** [comment]
I agree - the issues being public is a huge benefit. I quite often find solutions in open issues when the documentation has missing, inaccurate, or unclear information. I have also posted solutions to missing documentation on github issues. A private "feedback" form is not a replacement for a public issue tracker. Turning all of this private is objectively worse for all Microsoft customers.

**Comment by dstrome** [comment]
Thanks for taking the time to send us your thoughts on the new feedback system. We’ll pass along your comments to the appropriate teams.
