### ISSUE TITLE
-User must have sid (Remove-AppxPackage) (-User not functioning)

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#374]
It looks to me like the -user parameter only takes an sid.

PS C:\> Remove-AppxPackage -Package Microsoft.WindowsAlarms_10.1804.1101.0_x64__8wekyb3d8bbwe -user user
Remove-AppxPackage : The security ID structure is invalid.
The security ID structure is invalid.
At line:1 char:1
+ Remove-AppxPackage -Package Microsoft.WindowsAlarms_10.1804.1101.0_x6 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Comman
   ds.RemoveAppxPackageCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f43873-0e34-6ec2-8bde-479945d49ed9
* Version Independent ID: 914c97a9-7dc2-6ddd-4756-7ec210db3fe8
* Content: [Remove-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/remove-appxpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/remove-appxpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@jszabo98 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by jszabo98** [comment]
If what I'm talking about was done, the help would look like this:

-User
If you specify this parameter, the cmdlet removes the app package for only the user that this cmdlet specifies. To remove a package for a user profile other than the profile of the current user, you must run this command by using administrator permissions. The user name can be in one of these formats:

SID-string
