### ISSUE TITLE
Cleanup switch

### ISSUE THREAD

**Issue by swatt6400** [MicrosoftDocs/windows-powershell-docs#375]
The document states the obvious: that the Cleanup switch "attempts to force a clean-up of the root target in Active Directory Domain Services".  But one is still left wondering what this cleanup entails, that the delete of the target does not already accomplish.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85cdb14-7ddb-bb14-fa9e-b19e563cd80e
* Version Independent ID: c6b90405-cd80-c45c-4812-dbc6100f6bfb
* Content: [Remove-DfsnRootTarget (dfsn)](https://docs.microsoft.com/en-us/powershell/module/dfsn/remove-dfsnroottarget?view=win10-ps)
* Content Source: [docset/windows/dfsn/remove-dfsnroottarget.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dfsn/remove-dfsnroottarget.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by sowjanya365** [comment]
Hi @swatt6400 

Thanks for reaching out!

-Cleanup parameter attempts to force a clean-up of the root target in Active Directory Domain Services (AD DS). We can add this parameter when you have a situation where the cmdlet would otherwise fail, but can be convinced to complete the action.

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by swatt6400** [comment]
Ah yes, that does clarify a bit more, thanks for giving it some
    attention to improve for everyone!  :)
    ________________________________________________________
        Sandra Watt, B.Sc., MCITP Enterprise Administrator, MCTS .NET
        WPF
        Bermuda Information Technology Systems (BITS) Ltd.
        sandras@technologist.com / sandra.watt@bits.bm
        (441) 504-6404
      
    
    On 4/25/2019 9:20 AM, sowjanya365
      wrote:
    
    
      Hi @swatt6400
      Thanks for reaching out!
      -Cleanup parameter attempts to force a clean-up of the root
        target in Active Directory Domain Services (AD DS). We can add
        this parameter when you have a situation where the cmdlet would
        otherwise fail, but can be convinced to complete the action.
      Hope this information is helpful. Kindly confirm. Thank you.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/windows-powershell-docs","title":"MicrosoftDocs/windows-powershell-docs","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/windows-powershell-docs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sowjanya365 in #375: Hi @swatt6400 \r\n\r\nThanks for reaching out!\r\n\r\n-Cleanup parameter attempts to force a clean-up of the root target in Active Directory Domain Services (AD DS). We can add this parameter when you have a situation where the cmdlet would otherwise fail, but can be convinced to complete the action.\r\n\r\nHope this information is helpful. Kindly confirm. Thank you."}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/windows-powershell-docs/issues/375#issuecomment-486649206"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/windows-powershell-docs/issues/375#issuecomment-486649206",
"url": "https://github.com/MicrosoftDocs/windows-powershell-docs/issues/375#issuecomment-486649206",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by e0i** [comment]
Hello @swatt6400,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
