### ISSUE TITLE
Confirm switch default is not False

### ISSUE THREAD

**Issue by swatt6400** [MicrosoftDocs/windows-powershell-docs#376]
Running on Windows 10 without -Confirm switch, you get prompted to confirm.  Based on that, I would say that the default value for this switch is true, not false.

Also, the syntax is -Confirm:$False to specify not to confirm.  It would be nice to show this example, because it's not an intuitive syntax like for path, target, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85cdb14-7ddb-bb14-fa9e-b19e563cd80e
* Version Independent ID: c6b90405-cd80-c45c-4812-dbc6100f6bfb
* Content: [Remove-DfsnRootTarget (dfsn)](https://docs.microsoft.com/en-us/powershell/module/dfsn/remove-dfsnroottarget?view=win10-ps)
* Content Source: [docset/windows/dfsn/remove-dfsnroottarget.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dfsn/remove-dfsnroottarget.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by ojrb** [comment]
Hi @e0i  The PR #994 Solve this issue ! I updated the documentation for the confirm swhitch. Please review and Merge !

**Comment by e0i** [comment]
Content has had been merged.
