### ISSUE TITLE
-Members

### ISSUE THREAD

**Issue by arowswell** [MicrosoftDocs/windows-powershell-docs#377]
The -Members paragraph talks about "Adding" users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7016ebc2-6472-8242-c1f6-04657ee9e0b9
* Version Independent ID: d53a52b7-110c-e5af-a7ec-d5767a3c4259
* Content: [Remove-ADGroupMember (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/remove-adgroupmember?view=win10-ps)
* Content Source: [docset/windows/addsadministration/remove-adgroupmember.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/remove-adgroupmember.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @arowswell thanks for your feedback, I created a pull request to correct the article.
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR  Corrected members parameter description #1141 and kindly provide your feedback

**Comment by dariomws306** [comment]
I am ok.

**Comment by tseward** [comment]
Looks good.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @arowswell Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
