### ISSUE TITLE
Invalid example

### ISSUE THREAD

**Issue by jskiba99** [MicrosoftDocs/windows-powershell-docs#379]
The example above shows "Update-MPIOClaimedDisk" whereas the article is for "Update-MPIOClaimedHW"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22deda1d-7761-0284-e553-f23ef68a5e41
* Version Independent ID: 36f05044-351e-d9ca-2914-ac5ebddbc938
* Content: [Update-MPIOClaimedHW (mpio)](https://docs.microsoft.com/en-us/powershell/module/mpio/update-mpioclaimedhw?view=win10-ps)
* Content Source: [docset/windows/mpio/update-mpioclaimedhw.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/mpio/update-mpioclaimedhw.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jskiba99 thanks for your feedback, created a pull request to correct the article.
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR  Corrected cmdlet from Example #1142 and kindly provide your feedback

**Comment by dariomws306** [comment]
Ok!

**Comment by tseward** [comment]
Looks good.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jskiba99 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
