### ISSUE TITLE
ThreatDefaultAction not explained

### ISSUE THREAD

**Issue by rbarna1** [MicrosoftDocs/windows-powershell-docs#380]
By default a Windows installation (I am using Server 2016) has set the HighThreatDefaultAction, MediumThreatDefaultAction, and LowThreatDefaultAction to 0.
This documentation does not explain which ThreatAction option 0 maps to.  
Additionally, description or reference to what happens in each of the settings would be very useful.

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rbarna1 
Thanks for your feedback.
There is no article referenced in your issue, but I think that this is what you are looking for 
https://docs.microsoft.com/en-us/windows/desktop/lwef/mpthreat-action

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @rbarna1 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
