### ISSUE TITLE
Error in "Example 1: Disable automatic unlocking for a volume"

### ISSUE THREAD

**Issue by DesertBear** [MicrosoftDocs/windows-powershell-docs#386]
There's an error in "Example 1: Disable automatic unlocking for a volume".

It needs to be changed from:
Disable-AutoUnlock -MountPoint "E:"

To:
Disable-BitLockerAutoUnlock -MountPoint "E:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ff60783-113a-0913-9574-0d90adc4de4f
* Version Independent ID: eed53b45-e8a1-58b7-0d23-54b87c108104
* Content: [Disable-BitLockerAutoUnlock (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/disable-bitlockerautounlock?view=win10-ps)
* Content Source: [docset/windows/bitlocker/disable-bitlockerautounlock.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/disable-bitlockerautounlock.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DesertBear 
Thanks for your feedback, I created a pull request to correct the article.
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR  Corrected example cmdlet #1143 and kindly provide your feedback

**Comment by dariomws306** [comment]
Ok!

**Comment by tseward** [comment]
Looks good to me

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @DesertBear Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
