### ISSUE TITLE
-BindingState Parameter Correction

### ISSUE THREAD

**Issue by stanjoseph** [MicrosoftDocs/windows-powershell-docs#388]
This parameter requires a Boolean value rather than a String. So the acceptable values shouldn't be listed as "True" or "False" which are Strings. The values should be listed as "$True" or "$False". This mistake is also shown in Example 1. Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f576924-fd7d-e655-6f95-a6d8d507d855
* Version Independent ID: 6fd5ecff-2595-c745-98cf-d07c79ea706a
* Content: [Set-DhcpServerv4Binding (dhcpserver)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/set-dhcpserverv4binding?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/dhcpserver/Set-DhcpServerv4Binding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/dhcpserver/Set-DhcpServerv4Binding.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot close
