### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#389]
Just trying to get at some more useful examples.  Unfortunately, get-appxpackage doesn't give user specific information unless you pass -allusers, then it gives a packageuserinformation array with every related user.  You can't pipe user to remove-appxpackage anyway.  It also seems like a lot of appx packages of a different user can't be deleted this way -- "remove-appxpackage : Removal failed. Please contact your software vendor. (Exception from HRESULT: 0x80073CFA".  

```
$apps = get-appxpackage -alluser

foreach ($app in $apps) {
  foreach ($info in $app.packageuserinformation) {
    if ($info.installstate -eq 'installed') {
      [pscustomobject]@{name=$app.name; username=$info.usersecurityid.username}
      #remove-appxpackage -package $app.packagefullname -user $info.usersecurityid.sid -whatif 
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f43873-0e34-6ec2-8bde-479945d49ed9
* Version Independent ID: 914c97a9-7dc2-6ddd-4756-7ec210db3fe8
* Content: [Remove-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/remove-appxpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/remove-appxpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@jszabo98 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
