### ISSUE TITLE
Missing documentation (Invoke-CommandInDesktopPackage)

### ISSUE THREAD

**Issue by yay-jake** [MicrosoftDocs/windows-powershell-docs#391]
{{Fill in the Synopsis}} 
{{Fill in the Description}}
{{ Add example code here }}
{{ Add example description here }}
{{Fill Command Description}}

etc. isn't particularly useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bf19233-551b-9616-691f-9627355e6889
* Version Independent ID: 3e7d49de-73dd-db9e-5cdd-2eb42402bb63
* Content: [Invoke-CommandInDesktopPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/invoke-commandindesktoppackage?view=win10-ps)
* Content Source: [docset/windows/appx/invoke-commandindesktoppackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/invoke-commandindesktoppackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by c-don** [comment]
fixed. added the missing elements in the documentation.
