### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by Digger937** [MicrosoftDocs/windows-powershell-docs#395]
Every once and a while a "move-clustersharedvolume" fails, errors output to the console, but are not catchable. 

What I have tried,

1) try catch, no error thrown.

2) | Out-File, nothing is written to the file.

3) Assign results to a variable for parsing. Always returns an empty object. 

There doesn't seem to be a way to capture the result of the move. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d1e6aba-11a2-bec0-e11a-d7340869c534
* Version Independent ID: 0f22fefb-9f13-7404-04a2-122c44eb5d1e
* Content: [Move-ClusterSharedVolume (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/move-clustersharedvolume?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/move-clustersharedvolume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/move-clustersharedvolume.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @Digger937  thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
