### ISSUE TITLE
Better examples please

### ISSUE THREAD

**Issue by danabrash** [MicrosoftDocs/windows-powershell-docs#409]
I see too many documents like this where the example uses only the most minimal of possible syntax examples and does not bother to explain.  In this example, 'name' is defined as "Specifies the FQDN of a DNS application directory partition", however the example uses only NetBIOS naming.

This level of documentation for powershell cmdlets widespread and near useless.  Please be more thorough providing examples to address real world scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9cf2700-29be-c000-d1f1-837d80df6e8f
* Version Independent ID: 34c37722-6df1-9e69-6cfe-38c97d9ec876
* Content: [Register-DnsServerDirectoryPartition (dnsserver)](https://docs.microsoft.com/en-us/powershell/module/dnsserver/register-dnsserverdirectorypartition?view=win10-ps)
* Content Source: [docset/windows/dnsserver/register-dnsserverdirectorypartition.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsserver/register-dnsserverdirectorypartition.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@danabrash 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
