### ISSUE TITLE
Client vs. Server OS differentiation

### ISSUE THREAD

**Issue by MacGydver** [MicrosoftDocs/windows-powershell-docs#411]
This is a Windows 10 and Windows Server 2016 Power Shell Reference. It appears the deduplication feature is not available on Windows 10 so having something like "works on xxxxx" in this guide woudl be helpful since not all commands work between client/server OS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36ed61aa-2f66-ad9f-7d9c-4cd4a39faa59
* Version Independent ID: 175a235a-b8fa-e1e7-b672-630f4b1b4c9b
* Content: [Deduplication](https://docs.microsoft.com/en-us/powershell/module/deduplication/?view=win10-ps)
* Content Source: [docset/windows/deduplication/deduplication.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/deduplication.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @MacGydver Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
