### ISSUE TITLE
Example 3 Title Typo

### ISSUE THREAD

**Issue by CameronDMcLean** [MicrosoftDocs/windows-powershell-docs#412]
Example 3: Create an active-active failover relationship with specified load balacne amount
Balance is misspelled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9481d396-6308-1fda-53ff-561164eb6712
* Version Independent ID: 44f5efd6-ce9e-e77e-2ad8-6351fab68008
* Content: [Add-DhcpServerv4Failover (dhcpserver)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/add-dhcpserverv4failover?view=win10-ps)
* Content Source: [docset/windows/dhcpserver/add-dhcpserverv4failover.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dhcpserver/add-dhcpserverv4failover.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Malind19** [comment]
Created pull request
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/870

**Comment by e0i** [comment]
Changes had already been fixed via #433 
@officedocsbot close
