### ISSUE TITLE
CommandType References Cmdlets not Functions

### ISSUE THREAD

**Issue by tommymaynard** [MicrosoftDocs/windows-powershell-docs#413]
It might just be me, but any discussion of a command, or commands, should use the proper command type. Get-Command, when invoked against the Defender module, indicates that each command in this module is a function, not a cmdlet. I believe that the community expects that the command type will be properly relayed in documentation, online or shipped, and in discussions. There's a difference between functions and cmdlets, and so I believe it's practical that we use the proper language when referencing both. /2¢

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb01131-d23a-2bda-e2fd-97168b5b1f88
* Version Independent ID: 10fb6781-ff32-e3d6-3ea7-8dadb252eb30
* Content: [Defender](https://docs.microsoft.com/en-us/powershell/module/defender/index?view=win10-ps)
* Content Source: [docset/windows/defender/defender.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/defender.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tommymaynard thanks for your feedback, As I could also verify, they are actually functions, I will propose a change in the article and see if it gets approved, because I still have some doubts, besides being 100% accurate, what the authors wants in this case.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @tommymaynard Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
