### ISSUE TITLE
Add a Note Warning About ConsoleHost_history.txt

### ISSUE THREAD

**Issue by DesertBear** [MicrosoftDocs/windows-powershell-docs#415]
There should be a note in "Example 1: Enable BitLocker" warning that if you enable BitLocker in this way, the password will be stored in the following location in plain text:

%userprofile%\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline\ConsoleHost_history.txt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35517b3c-d00e-c08d-c274-8b606ad87bfa
* Version Independent ID: 3428c627-8703-752e-fbdf-52526f281f57
* Content: [Enable-BitLocker (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/enable-bitlocker?view=win10-ps)
* Content Source: [docset/windows/bitlocker/enable-bitlocker.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/enable-bitlocker.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by msbemba** [comment]
@DesertBear  Thank you for your feedback. We have added the note to the example via PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1308

**Comment by e0i** [comment]
@DesertBear 

Upon your feedback, We have updated the content with relevant changes accordingly via PR https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4831. Thank you.
