### ISSUE TITLE
Resiliencysetting

### ISSUE THREAD

**Issue by sthoward0914** [MicrosoftDocs/windows-powershell-docs#417]
If you look at what is written for the ResiliencySetting option, you used the same wording for the definition as is in the term itself. This makes it useless to someone who is trying to look up what this setting actually does, or what the options are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915197ed-248f-4e41-4647-20f02bcd9989
* Version Independent ID: b2332c94-b147-fcfb-1b8a-83c0dd1f99a3
* Content: [New-StoragePool (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps)
* Content Source: [docset/windows/storage/new-storagepool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/new-storagepool.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sthoward0914 thanks for your feedback.
I created a pull request to improve the description of that parameter.
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR  Improved resiliencysettingnamedefault description #1144 and kindly provide your feedback

**Comment by dariomws306** [comment]
...to use for virtual disks **_the_** created in the specified storage pool...

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @sthoward0914 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by dariomws306** [comment]
Ok now!
