### ISSUE TITLE
Error when using Set-DfsrMembership

### ISSUE THREAD

**Issue by jdurlewanger** [MicrosoftDocs/windows-powershell-docs#419]
Why am I receiving "WARNING: The -DfsnPath parameter is not validated. An incorrect path will not produce an error." when using this cmdlet? I do not see -DfsnPath as a valid parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57d517d8-523e-4315-0850-bac9a112e682
* Version Independent ID: 0371dbb2-1ab4-22e4-c3f8-4c8a54da5d4c
* Content: [Set-DfsrMembership (dfsr)](https://docs.microsoft.com/en-us/powershell/module/dfsr/set-dfsrmembership?view=win10-ps)
* Content Source: [docset/windows/dfsr/set-dfsrmembership.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dfsr/set-dfsrmembership.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @jdurlewanger  thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
