### ISSUE TITLE
problem with Link

### ISSUE THREAD

**Issue by JM2K69** [MicrosoftDocs/windows-powershell-docs#42]
Hi  all 
markdown File when we ahve un link to an other cmdlet the link don't work because the link inside the file is ./Get-gpo in the markdown file but the filename is get-gpo.md case sensitive. . .

For test Open the file get-gpo and test the link remove-gpo it don't work because ine the file get-gpo.md the link to remove-gpo is ./Remove-gpo and we have an error 404 file not found.

**Comment by brianlic-msft** [comment]
@JM2K69 I'm not able to reproduce this.  Are you still seeing a 404 error when you do the steps above?

**Comment by JM2K69** [comment]
To reproduce this above here the step :
- Navigate to docset/windows
- Launch index.md
- Click to Windows Deployment Services
- Click to Add-WDSDriverPackage
- and 404

I found the error the link is to Add-WDSDriverPackage but the file has the filename add-WDSDriverPackage case sensitive.

**Comment by brianlic-msft** [comment]
@JM2K69 Ah!  I understand now.  The links within GitHub are case sensitive, but the links as they render on TechNet are not.  For example, the links on this page work without error: https://technet.microsoft.com/en-us/itpro/powershell/windows/wds/wds

We use [PlatyPS](https://github.com/powershell/platyps) to create the stubbed markdown files, which creates them with a mixed case, but we've standardized on TechNet and docs.microsoft.com to use all lowercase file names.  With that said, the links work on TechNet and Docs, but they do not work within Github.com.
