### ISSUE TITLE
Deleting sites in a "Noninteractive" mode

### ISSUE THREAD

**Issue by Rychard** [MicrosoftDocs/windows-powershell-docs#420]
Is there no way to remove a site without prompting the user for confirmation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e199f48a-be4c-9a29-99dc-94324a3860ba
* Version Independent ID: 513fd12f-da8d-ab94-cc8d-50a97e327fe0
* Content: [Remove-IISSite (iisadministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/remove-iissite?view=win10-ps)
* Content Source: [docset/windows/iisadministration/remove-iissite.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/iisadministration/remove-iissite.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **brianlic**

**Comment by AndyP2** [comment]
Try `Remove-IISSite -Confirm:$False`

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Rychard thanks for your feedback.
As @AndyP2 said, you can achieve that passing a $false to Confirm parameter, as I could test too.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Rychard 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
