### ISSUE TITLE
Where is "New-IISAppPool" and "Remove-IISAppPool" ?

### ISSUE THREAD

**Issue by Rychard** [MicrosoftDocs/windows-powershell-docs#421]
Where are the Cmdlets for `New-IISAppPool` and `Remove-IISAppPool`?  

These seem to be an obvious omission, but perhaps I'm missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26a9267-a3fd-7692-db3f-70f13703ea11
* Version Independent ID: c3640b58-3848-b06b-aaab-e96757c25223
* Content: [Get-IISAppPool (iisadministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisapppool?view=win10-ps)
* Content Source: [docset/windows/iisadministration/get-iisapppool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/iisadministration/get-iisapppool.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
Hello, @Rychard 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about any of your similar problems problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by olaeld** [comment]
Clearly, this information should be in the docs, not hidden away in this issue.

**Comment by Scorito-Dev** [comment]
I do not agree @e0i  it doesn't seem like his question is answered, this is a workaround.
The question was; Where are the Cmdlets for New-IISAppPool and Remove-IISAppPool?

Could these be added in the future or are they left out on purpose?

**Comment by robinmalik** [comment]
@Scorito-Dev I don't think any dev is being done on this "new" module. The publish date for the latest is 02/08/2017 21:03:35.
