### ISSUE TITLE
CompressionType parameter

### ISSUE THREAD

**Issue by BryanLaValley** [MicrosoftDocs/windows-powershell-docs#422]
CompressionType isn't documented well. Maybe highlight the three options in bold or put them first in the bullet points like the loglevel parameter and that they have to be lower case. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becc68a9-a1af-212a-af7b-ca89dea4c23e
* Version Independent ID: 3e786ce6-7640-2ec3-d5d4-1b2b0549476d
* Content: [New-WindowsImage (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/new-windowsimage?view=win10-ps)
* Content Source: [docset/windows/dism/new-windowsimage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/new-windowsimage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@BryanLaValley 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
