### ISSUE TITLE
Get-AppBackgroundTask can only be run once then it will error forever

### ISSUE THREAD

**Issue by AveYo** [MicrosoftDocs/windows-powershell-docs#424]
```
PS C:\> Get-AppBackgroundTask
Get-AppBackgroundTask : A general error occurred that is not covered by a more specific error code.
At line:1 char:1
+ Get-AppBackgroundTask
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (PS_BackgroundTask:ROOT/Microsoft/..._BackgroundTask) [Get-AppBackgroundTa
   sk], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Get-AppBackgroundTask

PS C:\>
```

Definitely looks ignored on purpose since 2015. How about it, Microsoft?

**Comment by e0i** [comment]
Hello, @AveYo  

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by e0i** [comment]
We are closing this issue since we haven't got response from your side regarding issue details.

Feel free to re-open this is issue and specify the documentation. We'd like to follow-up with content updates.

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
