### ISSUE TITLE
does not add driver to driverstore

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#426]
This command doesn't add a new driver to the driverstore on a live system.  The documentation is unclear.  Pnputil is still needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23e82de8-e4ad-8d7b-96e5-d95c2d0d9179
* Version Independent ID: 93c85b76-2682-284e-586d-3752984979da
* Content: [Add-PrinterDriver (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/add-printerdriver?view=win10-ps)
* Content Source: [docset/windows/printmanagement/add-printerdriver.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/printmanagement/add-printerdriver.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by johnsmith2679** [comment]
Try to update your driver manually and download the driver and install them. If you are Windows 10 user and facing a problem with your HP laptop with the HP Accelerometer tool app fix your error click on [HP Accelerometer](https://hpetechnicalsupportnumber.com/blog/fix-hp-accelerometer-error-windows-10/). It fixes the driver problem, error in the opening of Accelerometer software, removal of corrupted driver etc.

**Comment by e0i** [comment]
Hello, @jszabo98 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
