### ISSUE TITLE
Clear-AssignedAccess cmdlet Description & Parameters Unclear

### ISSUE THREAD

**Issue by danieldjewell** [MicrosoftDocs/windows-powershell-docs#428]
Hello MS Docs Team, 

The Clear-AssignedAccess cmdlet description indicates "The Clear-AssignedAccess cmdlet removes the **_specified user account_** from assigned access and returns the user to default settings." 

However, when looking at the definitions for the functions of both Clear-AssignedAccess and Set-AssignedAccess (using Get-Command Clear-AssignedAccess | fl), it's clear that the way this works is that there is only one AssignedAccess instance supported (" Check if an instance already exists. We only allow a single instance of WEDL_AssignedAccess. (AssignedAccess.psm1::297 / Module AssignedAccess - GUID {9E72217E-9E27-45F7-81FC-048763587E0A} v1.0) 

So from this, it would _appear_ that: 

1. Only one user can be set with Set-AssignedAccess at a time (because Set-AssigneedAccess will *delete* and *replace* the WEDL_AssignedAccess class 
2. The Clear-AssignedAccess function clears *all* assigned access (because there is only ever *one* user assigned access) ... although the documentation does not indicate this.

At a minimum, it would be nice for the documentation to be updated to clarify this - if indeed the intention is to allow multiple users to have assigned access, then the AssignedAccess module would seemingly need to be updated and the Clear-AssignedAccess function would need to be modified to accept Username input. 

(On a side note, since I couldn't find a place on the MS site or Github on the actual AssignedAccess *module* itself (e.g. AssignedAccess.psm1) -- it would be nice if these functions accepted piped input from say Get-LocalUser etc.) 

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ef4aad-a24e-2b97-e14a-48c94ab67d59
* Version Independent ID: 883fc01b-90ba-3a88-bc00-17d942a49411
* Content: [Clear-AssignedAccess (assignedaccess)](https://docs.microsoft.com/en-us/powershell/module/assignedaccess/clear-assignedaccess?view=win10-ps)
* Content Source: [docset/windows/assignedaccess/clear-assignedaccess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/assignedaccess/clear-assignedaccess.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @danieldjewell 
Thanks for your feedback.
I created a pull request to correct the wording in the article, to reflect that there can be only one AssignedAccess at a time, [as I could verify](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/wedl-assignedaccess).

Thank you

**Comment by get-itips** [comment]
Also, for feature requests, I need to kindly suggest to visit [this resource ](https://windowsserver.uservoice.com/forums/301869-powershell)

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR Changed wording #1145 and kindly provide your feedback

**Comment by dariomws306** [comment]
Looks good!

**Comment by tseward** [comment]
Looks good.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @danieldjewell Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
