### ISSUE TITLE
Name parameter properties

### ISSUE THREAD

**Issue by gregbradley** [MicrosoftDocs/windows-powershell-docs#430]
In using this module it does appear that the -Name parameter does indeed support wildcard characters even though this document says it does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa09ddd-2a5e-430a-cb41-a00439e9d500
* Version Independent ID: fb5b52b0-1834-8d8c-ef1e-09d4f49a2a00
* Content: [Restart-WebAppPool (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/restart-webapppool?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/Restart-WebAppPool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/Restart-WebAppPool.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @gregbradley thanks for your feedback.
I created a pull request to correct the article, as I could verify, thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR Changed property of parameter #1146 and kindly provide your feedback

**Comment by tseward** [comment]
@yogkumgit looks good to me.

**Comment by dariomws306** [comment]
Looks good!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @gregbradley Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
