### ISSUE TITLE
Cannot Specify 0 (as documented) to HwThreadCountPerCore

### ISSUE THREAD

**Issue by Silvenga** [MicrosoftDocs/windows-powershell-docs#432]
It appears that `Set-VMProcessor -HwThreadCountPerCore` does not support an option of 0. Is this a supported option as documented?

When running the following command:

```
$vm | Set-VMProcessor `
  -CompatibilityForMigrationEnabled $true `
  -HwThreadCountPerCore 2 `
  -Count $coreCount
```

The following is printed:

```
Set-VMProcessor : Failed to modify device 'Processor'.
Cannot assign the specified number of threads per core.
'RETRACTED' failed to modify device 'Processor'. (Virtual machine ID F4294DE3-3614-4563-B6CF-B4FB41ABCA3D)
Cannot assign the specified number of threads per core for virtual machine 'RETRACTED' is out of range. The
range is 1 through 2. (Virtual machine ID F4294DE3-3614-4563-B6CF-B4FB41ABCA3D)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0021f5c8-75b3-93b7-9c54-4b7518bf2f8d
* Version Independent ID: cd348f47-0522-b6de-353c-c0e8ecf86cf2
* Content: [Set-VMProcessor (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmprocessor?view=win10-ps)
* Content Source: [docset/windows/hyper-v/set-vmprocessor.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/set-vmprocessor.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@Silvenga 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
