### ISSUE TITLE
Stop using acroynms in documentation and provide valid input VALUES ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/windows-powershell-docs#442]
Completely new to this topic (trying to add roles/features via powershell), the documentation states:

"The Install-WindowsFeature cmdlet installs the specified rrsandf_plural on..."

What the h@ll is "rrsandf_plural" ? -- no clue!, continue reading ...

"This cmdlet works similarly to the arfw in ..."

What the h@ll is "arfw" ? -- no clue!

All I get when I read these docs are more questions!  For example, the REQUIRED -Name option -- WHERE does one go to find the list of valid names to be used with this parameter?  Either present a list of valid names that may be used or provide link to such a list or provide the command that produces a list of valid names.  HOW is anyone supposed to use this command when you are left to guess the inputs !??  Good Grief!

While I am ranting, my goal is to (via powershell):
a) Install IIS (latest version)
b) Install specific version of .Net Framework and all features, i.e.: 4.6.2

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d05b2e2-d244-3807-ef9a-c88b0e7a207a
* Version Independent ID: 5e7493c1-7e9e-1a48-4318-7059eb1d3e26
* Content: [Install-WindowsFeature (servermanager)](https://docs.microsoft.com/en-us/powershell/module/servermanager/install-windowsfeature?view=winserver2012r2-ps#description)
* Content Source: [docset/winserver2012r2-ps/servermanager/Install-WindowsFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/servermanager/Install-WindowsFeature.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by coreyp-at-msft** [comment]
Hi @bdcoder2 , This command performs the same function as the Add Roles and Features Wizard (ARFW)

To get a list of valid feature names on your server, use  `Get-WindowsFeature`
SYNOPSIS
Gets information about Windows Server roles, role services, and features that are available for installation and installed on a specified server

Note that you are looking at Windows Server 2012R2 documentation that is no longer updated.

**Comment by bdcoder2** [comment]
Hi @coreyp-at-msft - Thank-you -- the information you provided will definitely help!   And yes, I was aware I was looking at 2012R2, but one has to look anywhere one can when information is not provided in the "current" docs.

Any clue as to what "rrsandf_plural" means?

Cheers

**Comment by e0i** [comment]
Hello, @bdcoder2 



Hello, @bdcoder2 

The rrsandf_plural values have actually been typos and have been fixed with recent changes to documentation. See issue #581 for details.

Thanks for providing feedback.

**Comment by e0i** [comment]
@bdcoder2,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
