### ISSUE TITLE
Test-DNSServer documentation in Examples in error

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#443]
In windows-powershell-docs/docset/windows/dnsserver/test-dnsserver.md, the output for the first two examples is incorrect.

In my testing (on Win2019), TCP is ever tried. Here are three examples:

```powershell
PS C:\Foo> Test-DnsServer -IPAddress 10.10.10.10 -Context DnsServer

IPAddress   Result  RoundTripTime TcpTried UdpTried
---------   ------  ------------- -------- --------
10.10.10.10 Success 00:00:00      False    True    

PS C:\Foo> Test-DnsServer -IPAddress 10.10.10.10 -Context RootHints

IPAddress   Result  RoundTripTime TcpTried UdpTried
---------   ------  ------------- -------- --------
10.10.10.10 Success 00:00:00      False    True    

PS C:\Foo> Test-DnsServer -IPAddress 10.10.10.10 -ZoneName 'Reskit.Org' 

IPAddress   Result  RoundTripTime TcpTried UdpTried
---------   ------  ------------- -------- --------
10.10.10.10 Success 00:00:00      False    True    
```
In all three cases, TcpTried is False, not (as the documentation show) True.

Not sure if this is a bug in the cmdlet, but the expected output is not being seen.

**Comment by e0i** [comment]
@doctordns  Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by doctordns** [comment]
https://docs.microsoft.com/en-us/powershell/module/dnsserver/test-dnsserver is the page. The issue also notes the GitHub Path.

In my case, I never see TCPTried being TRUE. In my home domain I see this:

```powershell
PS [C:\foo> ]> Test-DnsServer -IPAddress 10.10.10.10 -ComputerName Cookham1 -Context Forwarder

IPAddress   Result     RoundTripTime TcpTried UdpTried
---------   ------     ------------- -------- --------
10.10.10.10 NoResponse 00:00:12      False    True
```

**Comment by e0i** [comment]
@doctordns Thanks for clarification. We will investigate and follow up with an update accordingly.

**Comment by e0i** [comment]
@doctordns 
Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
