### ISSUE TITLE
Vm-Group support for Checkpoints

### ISSUE THREAD

**Issue by GeoSimos** [MicrosoftDocs/windows-powershell-docs#444]
Is it possible to checkpoint multiple VMs in a VM-Group?
If not, it would be a great feature especially when upgrading multi-tier systems, for training Labs or Work Labs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 371caf6b-b1eb-f91e-110f-a0914607c4e9
* Version Independent ID: 3a47edd3-8eee-35e0-7a67-cca46de5ebf1
* Content: [Checkpoint-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/checkpoint-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/checkpoint-vm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/checkpoint-vm.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot unassign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @GeoSimos how are you?
Currently, Checkpoint-VM does not accept pipelined input from Get-VMGroup.
I agree with you that it would be a good idea, I kindly redirect you to suggest that idea to User Voice https://windowsserver.uservoice.com/
Thank you!

**Comment by yogkumgit** [comment]
@GeoSimos  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
