### ISSUE TITLE
The `-Thumbprint` parameter not found in CmdLet

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/windows-powershell-docs#445]
When running the `Set-RDCertificate` CmdLet with the `-Thumbprint` parameter, I receive an error saying that the parameter cannot be found.

```
PS C:\Users\administrator.PEXIP\Desktop&gt; Set-RDCertificate -Role RDRedirector -Thumbprint xxxxxxxxxxxxxxxxxxxxxxxxxx
Set-RDCertificate : A parameter cannot be found that matches parameter name 'Thumbprint'.
At line:1 char:38
+ Set-RDCertificate -Role RDRedirector -Thumbprint xxxxxxxx...
+                                      ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-RDCertificate], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-RDCertificate
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de72abc-be59-61d0-282b-b6515d01d595
* Version Independent ID: 88da75ef-8a82-52d7-54db-23c3487aa5fb
* Content: [Set-RDCertificate (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/set-rdcertificate?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/set-rdcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/set-rdcertificate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Stofferl** [comment]
I also want to report this.

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot unassign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @swinster how are you? Hope you are doing just fine.
-Thumbprint parameter is available in Windows Server 2019, not in 2016, I'll add a note to the current version of the article.
Thanks

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR #1107  and kindly provide your feedback

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @swinster Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
