### ISSUE TITLE
Effect of DisableAntiSpyware=0 and DisableRealTimeMonitoring=0 policies

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-powershell-docs#446]
Hi,
Do DisableAntiSpyware=0 and DisableRealTimeMonitoring=0 policies affect WDAV state (passive/auto-disabled/active) when third-party AV is installed, effectively forcing active mode regardless of having third-party AV installed and healthy (which should typically make it go passive)?
Any interactions of those policies with onboarding third-party AV device on WDATP?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb01131-d23a-2bda-e2fd-97168b5b1f88
* Version Independent ID: 10fb6781-ff32-e3d6-3ea7-8dadb252eb30
* Content: [Defender](https://docs.microsoft.com/en-us/powershell/module/defender/index?view=win10-ps)
* Content Source: [docset/windows/defender/defender.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/defender.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot unassign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @juanand how are you?
I think this resource has the answer you are looking for https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility
Hope this helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @juanand 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
