### ISSUE TITLE
How to retrieve encryption method from powershell

### ISSUE THREAD

**Issue by valentijnscholten** [MicrosoftDocs/windows-powershell-docs#447]
Hi,

Is there any way to get Get-BitlockerVolume to display the encryption method?
Specifically if hardware or software encryption is being used?

Valentijn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3b0c94-181c-f2d8-70b0-d65c46f1c92b
* Version Independent ID: 9bae55ce-a087-0878-8bb6-5edee5f9d33b
* Content: [Get-BitLockerVolume (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/get-bitlockervolume?view=win10-ps)
* Content Source: [docset/windows/bitlocker/get-bitlockervolume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/get-bitlockervolume.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by valentijnscholten** [comment]
I just observed that when the output is converted to JSON, there's the EncryptionMethod field.
PS C:\Windows> Get-BitLockerVolume | ConvertTo-Json

{
...
    "EncryptionMethod":  6,
...
}

A numeric value for which I cannot find any official documentation, but 6 seems to be XTS-AES128. What would be the value when hardware encryption is being used?

**Comment by valentijnscholten** [comment]
I know, but I need the mapping to numeric values as all our scripts are json based

**Comment by BasvanH** [comment]
You can find the values here: https://blogs.technet.microsoft.com/dubaisec/2016/03/04/bitlocker-aes-xts-new-encryption-type/

**Comment by valentijnscholten** [comment]
I've seen that but it only specifies 1-7, the values for software encryption. 0 seems to no encryption. Could not find the value for hardware encryption.

**Comment by jonathanweinberg** [comment]
Check here @valentijnscholten [Win32_EncryptableVolume](https://docs.microsoft.com/en-us/windows/desktop/secprov/getencryptionmethod-win32-encryptablevolume)


Value | Meaning
-- | --
None 0 | The volume is not encrypted.
AES_128_WITH_DIFFUSER 1 | The volume has been fully or partially encrypted with the Advanced Encryption Standard (AES) algorithm enhanced with a diffuser layer, using an AES key size of 128 bits. This method is no longer available on devices running Windows 8.1 or higher.
AES_256_WITH_DIFFUSER 2 | The volume has been fully or partially encrypted with the Advanced Encryption Standard (AES) algorithm enhanced with a diffuser layer, using an AES key size of 256 bits. This method is no longer available on devices running Windows 8.1 or higher.
AES_128 3 | The volume has been fully or partially encrypted with the Advanced Encryption Standard (AES) algorithm, using an AES key size of 128 bits.
AES_256 4 | The volume has been fully or partially encrypted with the Advanced Encryption Standard (AES) algorithm, using an AES key size of 256 bits.
HARDWARE_ENCRYPTION 5 | The volume has been fully or partially encrypted by using the hardware capabilities of the drive.
XTS_AES_128 6 | The volume has been fully or partially encrypted with XTS using the Advanced Encryption Standard (AES), and an AES key size of 128 bits. This method is only available on devices running Windows 10, version 1511 or higher.
XTS_AES_256 7 | The volume has been fully or partially encrypted with XTS using the Advanced Encryption Standard (AES), and an AES key size of 256 bits. This method is only available on devices running Windows 10, version 1511 or higher.
(uint32) –1 | UNKNOWNThe volume has been fully or partially encrypted with an unknown algorithm and key size.

**Comment by e0i** [comment]
@valentijnscholten From our understanding this issue has been resolved. Please re-open the issue if you feel it has not been resolved. Thanks for your input.

@AndreaBarr Recommended closure. Thanks.

**Comment by e0i** [comment]
@AndreaBarr Recommended closure. Thanks.

**Comment by valentijnscholten** [comment]
I don't see any of the suggested changes/additions made to the page?
