### ISSUE TITLE
Where can I get this module?

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/windows-powershell-docs#448]
Where can I (or how do I) get this module?

I wasn't able to find it at https://www.powershellgallery.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a425544-5041-25bd-2259-3474a5c97d41
* Version Independent ID: 4a4f55f3-1753-d8f9-3d1e-3310a77c3423
* Content: [NetLdpAgent](https://docs.microsoft.com/en-us/powershell/module/netldpagent/?view=win10-ps)
* Content Source: [docset/windows/netldpagent/netldpagent.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netldpagent/netldpagent.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by gjdd** [comment]
Hi, module seems to be embedded into Remote Server Administration Tools for Windows 10.
https://www.microsoft.com/fr-fr/download/confirmation.aspx?id=45520

After installing this package, I found the cmdlet onto my windows 10.
Regards
