### ISSUE TITLE
Set-ADAccountPassword -WhatIf is known to not work with (At least) 2012r2

### ISSUE THREAD

**Issue by SotoDucani** [MicrosoftDocs/windows-powershell-docs#450]
Please see https://windowsserver.uservoice.com/forums/304621-active-directory/suggestions/10844361-set-adaccountpassword-whatif-does-not-work

Of all the parameters to A) Not actually work and B) Not be correctly documented when there is a known problem, -WhatIf is probably one of the worst ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0faee09-fab7-1195-a96f-332f40a86abc
* Version Independent ID: 0ac9706b-ade6-fa93-5748-ca97fa47ff8e
* Content: [Set-ADAccountPassword (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/set-adaccountpassword?view=winserver2012-ps&viewFallbackFrom=winserver2012r2-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Set-ADAccountPassword.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Set-ADAccountPassword.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
Hello, @SotoDucani 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@SotoDucani 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by curspice** [comment]
This bit me in the ass really good yesterday and today.  This really needs to be fixed.
