### ISSUE TITLE
incorrect output parameter names?

### ISSUE THREAD

**Issue by poenn** [MicrosoftDocs/windows-powershell-docs#452]
Running this command appears to return 'SizeMax' and 'SizeMin' rather than 'MaximumSize' and 'MinimumSize' as shown in this document's example.

Sample Output:
![image](https://user-images.githubusercontent.com/13856906/48162794-fc997300-e2ab-11e8-81d2-3534f324c543.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7582541-5c8e-2a7f-5a8b-d7a08570f8e9
* Version Independent ID: 976b2d36-9c01-712a-3d9b-330151794e20
* Content: [Get-PartitionSupportedSize (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-partitionsupportedsize?view=win10-ps)
* Content Source: [docset/windows/storage/get-partitionsupportedsize.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-partitionsupportedsize.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by sowjanya365** [comment]
Hi @poenn 

Thank you for reporting and making the docs better. Much appreciated. 

We've modified the output label names now. Kindly verify and confirm. Thank you.

**Comment by e0i** [comment]
@poenn

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
