### ISSUE TITLE
InterfaceAlias DOES take wildcards.

### ISSUE THREAD

**Issue by jmwolfe** [MicrosoftDocs/windows-powershell-docs#455]
The docs say that the --InterfaceAlias option does not take wildcards. However, I find it does.

Namely, using * works fine. This is on Win 2016 Server STandard edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f9afadf-377c-e00a-a23e-5c7127945f94
* Version Independent ID: 6efb7c0d-7e37-65e5-b508-0d1b286a1fc1
* Content: [Get-NetIPAddress (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/get-netipaddress?view=win10-ps)
* Content Source: [docset/windows/nettcpip/get-netipaddress.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nettcpip/get-netipaddress.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jmwolfe thanks for your feedback.
I could reproduce, so I created a pull request to correct the article.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jmwolfe Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
