### ISSUE TITLE
Example 1 has typo

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windows-powershell-docs#458]
Removed-VMSwitchTeamMember 

Removed is not the proper verb, extra "d" in the word.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 553547e3-cb10-2036-5ced-059b3c5f7cda
* Version Independent ID: b95ead68-4cc5-22b4-4508-d7f2789446cf
* Content: [Remove-VMSwitchTeamMember (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/remove-vmswitchteammember?view=win10-ps)
* Content Source: [docset/windows/hyper-v/remove-vmswitchteammember.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/remove-vmswitchteammember.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Malind19** [comment]
PR for this issue https://github.com/MicrosoftDocs/windows-powershell-docs/pull/923

**Comment by e0i** [comment]
@AndreaBarr Please have the PR #923  for this issue reviewed. Thanks.

**Comment by e0i** [comment]
@eponerine  With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
