### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by hoytler** [MicrosoftDocs/windows-powershell-docs#459]
Both in powershell help files and in this article, there are no documented details for this cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 192ebef7-3fd8-5691-2d89-3616ab2a44fc
* Version Independent ID: 088e91d5-11c8-d20e-2593-9d92853e1c36
* Content: [Disable-TlsEccCurve (tls)](https://docs.microsoft.com/en-us/powershell/module/tls/disable-tlsecccurve?view=win10-ps)
* Content Source: [docset/windows/tls/disable-tlsecccurve.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/tls/disable-tlsecccurve.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by powellbc** [comment]
Specifically, details about the release version as well required OS level.

**Comment by bigmaggot** [comment]
Disable-TlsEccCurve "curve25519";

**Comment by sowjanya365** [comment]
Hi @hoytler 

Thank you for reaching out!

I think the document is updated now. Could you please go through the content now and let us know if you think we are missing anything here.  Happy to assist. Thank you!
