### ISSUE TITLE
AutoConnectEnabled description is missing

### ISSUE THREAD

**Issue by fdcastel** [MicrosoftDocs/windows-powershell-docs#467]
Ditto :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8e9abf-fcbb-7ecb-b743-1ccc5256be74
* Version Independent ID: 421c66e0-2f38-2323-4cf4-73af0eec54ce
* Content: [Add-VpnS2SInterface (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/add-vpns2sinterface?view=win10-ps)
* Content Source: [docset/windows/remoteaccess/add-vpns2sinterface.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remoteaccess/add-vpns2sinterface.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@fdcastel 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
