### ISSUE TITLE
Bad links to all zero GUID file

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/windows-powershell-docs#471]
There are a bunch of placeholder/bad links that might have come in with an initial conversion
https://github.com/MicrosoftDocs/windows-powershell-docs/search?q=%5B00000000-0000-0000-0000-000000000000%5D%2800000000-0000-0000-0000-000000000000%29&unscoped_q=%5B00000000-0000-0000-0000-000000000000%5D%2800000000-0000-0000-0000-000000000000%29

**Comment by e0i** [comment]
@nschonni

The documentation is currently being progressively updated to address the group of articles involved with this issue.

Thank you for bringing this to attention.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by nschonni** [comment]
Since there are still 300+ affected files, should this be closed before the work is done?

**Comment by e0i** [comment]
This issue has recently been addressed via a group of PRs during a mass-update, example: https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2114

**Comment by nschonni** [comment]
@e0i the search is still returning a few hits, but it looks like you're down to 20 files 👍

**Comment by e0i** [comment]
> @e0i the search is still returning a few hits, but it looks like you're down to 20 files 👍

Yes, This is because another set of PRs that address variety of link issues within the repository are in draft that also address the remaining 20. Thank you for following up.
