### ISSUE TITLE
Partition help content incorrect

### ISSUE THREAD

**Issue by SeanQuinlan** [MicrosoftDocs/windows-powershell-docs#474]
The help content for the -Partition parameter is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0b9f4db-305b-847a-1ab6-ad3b547a91f7
* Version Independent ID: a626e689-b2ba-6a11-c17b-9f1fd0e565cd
* Content: [Get-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/get-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/get-aduser.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SeanQuinlan 
Thanks for your feedback.
I created a pull request to correct the description of Partition parameter.
Many thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @SeanQuinlan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
