### ISSUE TITLE
Parameter descriptions contain template

### ISSUE THREAD

**Issue by TheGhost2804** [MicrosoftDocs/windows-powershell-docs#475]
None of the parameter descriptions is provided they all look like "{{Fill &lt;ParameterName&gt; Description}}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c402cdf-7948-b74e-93de-449a90eaf56a
* Version Independent ID: beea1c46-1acf-8856-48c1-36037b737b2f
* Content: [Search-ADAccount (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/search-adaccount?view=winserver2012-ps&viewFallbackFrom=winserver2012r2-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Search-ADAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Search-ADAccount.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @TheGhost2804 Thanks for your feedback. I created a PR to add the missing description of parameters. Hopefully, it will be reflected on live version soon.
Thanks again

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @TheGhost2804 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by TheGhost2804** [comment]
err... this is still not resolved! Please fix it!

**Comment by get-itips** [comment]
Hello @TheGhost2804 the article is fixed, althought there is currently an issue with the repo being out of sync with the published version of articles (@kenwith any updates on this?), the team is working on it, if you want to see the fix you can take a look at the referenced pull request. 
@yogkumgit please close this again.
