### ISSUE TITLE
incorrect explanation of -RemoveDnsDelegation

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-powershell-docs#477]
"By default, this parameter is set to False, which means DNS delegations that point to this server from the parent DNS zone will not be retained after uninstallation of the domain controller"

If the value by default is false, then that would mean do NOT remove DNS delegation.  Instead this doc says the complete opposite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0586dde-2fa1-78b7-0b3a-0de5c32c7d59
* Version Independent ID: 2b495e47-648a-af88-623f-c15e619f4f7e
* Content: [Uninstall-ADDSDomainController (addsdeployment)](https://docs.microsoft.com/en-us/powershell/module/addsdeployment/uninstall-addsdomaincontroller?view=win10-ps)
* Content Source: [docset/windows/addsdeployment/uninstall-addsdomaincontroller.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsdeployment/uninstall-addsdomaincontroller.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@poortom1004 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
