### ISSUE TITLE
Typo in URL

### ISSUE THREAD

**Issue by gabriuz** [MicrosoftDocs/windows-powershell-docs#478]
URL for "Storage Cmdlets" has a typo:
https://docs.microsoft.com/en-us/powershell/module/stroage
it should be:
https://docs.microsoft.com/en-us/powershell/module/storage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1516d5c3-4895-cf8b-f5a9-370e2bd0f1e6
* Version Independent ID: 6e9677e3-763f-9689-3219-69b7c8b7685d
* Content: [Windows 8.1 and Windows Server 2012 R2](https://docs.microsoft.com/en-us/powershell/windows/get-started?view=winserver2012r2-ps)
* Content Source: [docset/docs-conceptual/winserver2012r2-ps/get-started.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/docs-conceptual/winserver2012r2-ps/get-started.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Malind19** [comment]
Created PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/924

**Comment by e0i** [comment]
@gabriuz  Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
