### ISSUE TITLE
Get-ADUser is not recognized

### ISSUE THREAD

**Issue by michcleary** [MicrosoftDocs/windows-powershell-docs#479]
When I tried using this command, I get:
Get-ADUser : The term 'Get-ADUser' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.

Also, your SearchBase string isn't identified in your example.  I'm not sure what those parts are referring to.  Not very helpful page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4cb3748-12d0-b494-5fff-71c06e2973d1
* Version Independent ID: b013a1e2-5879-5924-9dbd-a8db54885d10
* Content: [Get-ADUser (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Get-ADUser.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by doctordns** [comment]
The error message tells you that PowerShell cannot find the Get-ADUser cmdlet. That means you do not have the module loaded.
You can easily add the AD RSAT tools to provide this module. Or use implicit remoting to import the module into your current PowerShell session.
Seachhbase is the OU you want this command to Target. This means the cmdlet just returns the AD uses in the specified OU or the OU and child OUs.
The port 3268 is the port to connect to the Global Catalog.

**Comment by e0i** [comment]
Hello @michcleary ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure._

**Comment by Rajkishore123** [comment]
You can check out one of the best solution on the same issue 
<a href="https://azurelessons.com/the-term-get-aduser-is-not-recognized-as-the-name-of-a-cmdlet/">Here</a>
