### ISSUE TITLE
How do I *get* this module?

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/windows-powershell-docs#480]
The module is not pre-installed on a Server 2012 computer.  So the first line should be "how do I get this module" rather than how to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4fd4e69-851d-3c4e-744c-0f797dc8da1e
* Version Independent ID: f1aad6a1-fbc4-df50-d470-81e5cd83fabc
* Content: [ActiveDirectory](https://docs.microsoft.com/en-us/powershell/module/activedirectory/?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/ActiveDirectory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/ActiveDirectory.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by PetRose** [comment]
Either one knows to get to GitHub (see link near bottom) or a more friendly approach would be to have a reverence to this 'common' description for Windows 10 and Windows Server 2016:
   https://docs.microsoft.com/en-us/powershell/module/addsadministration/?view=win10-ps

**Comment by e0i** [comment]
Hello, @Pxtl @PetRose 

Does the description from a [related PR #212](https://github.com/MicrosoftDocs/windows-powershell-docs/pull/212/files) answers your question?

We'd like to follow-up and perform relevant changes accordingly.

Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
