### ISSUE TITLE
Mux Echo Responder is ping?

### ISSUE THREAD

**Issue by wangkanai** [MicrosoftDocs/windows-powershell-docs#481]
How is even work?

PS C:\Windows\system32&gt; Enable-MuxEchoResponder -TargetVIP "122.155.92.194"

ErrorMsg Status
-------- ------
         Success

PS C:\Windows\system32&gt; ping 122.155.92.194

Pinging 122.155.92.194 with 32 bytes of data:
Request timed out.
Request timed out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c117af5-962f-6d09-73f4-acba27a9491c
* Version Independent ID: f6017006-6005-d5f8-ca4e-8f5123af3013
* Content: [Enable-MuxEchoResponder (hnvdiagnostics)](https://docs.microsoft.com/en-us/powershell/module/hnvdiagnostics/enable-muxechoresponder?view=win10-ps)
* Content Source: [docset/windows/hnvdiagnostics/enable-muxechoresponder.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hnvdiagnostics/enable-muxechoresponder.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @AndreaBarr can you help us finding the right people here? Thanks

**Comment by get-itips** [comment]
Hello @wangkanai thanks for your feedback.
After investigating this, I could find that these cmdlets have been deprecated and they do not have to be used anymore.
I created a pull request to add this info to the cmdlet's documentation.
Hope this info helps you. Thanks!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @wangkanai Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
