### ISSUE TITLE
Optimisation de l'intérieur

### ISSUE THREAD

**Issue by GowaP** [MicrosoftDocs/windows-powershell-docs#483]
Cette commande ne permet d’optimiser un fichier VHD/VHDX dans tous les cas d’usage. 
Comment traiter les disque virtuels d’une VM répliqué ?
Ce qu’il manque, c’est une commande pour exécuter l’optimisation directement de l’intérieur de la VM.
Une sorte de "Optimize-VHD -parent" que l’on exécuterait dans le client (into OS VM) et non pas dans l'hyperviseur, qui procèderait au "Prezeroed" puis demandera la réduction du VHDX auprès de l'hyperviseur via les services d'intégrations. 
En synthèse : Piloter l’optimisation cela de l'intérieur.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9a37cff7-cc5c-0de2-e84e-a2c56cde57cc
* Version Independent ID: 6c80c1f4-8ea2-1a41-b4d8-a28f9e50cb97
* Content: [Optimize-VHD (hyper-v)](https://docs.microsoft.com/fr-fr/powershell/module/hyper-v/optimize-vhd?view=win10-ps#feedback)
* Content Source: [docset/windows/hyper-v/optimize-vhd.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/optimize-vhd.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @GowaP thanks for your feedback, honestly, I do not know french, but I used a translator and, correct me if I am wrong, you are suggesting a feature request to handle VHD files.
As this issue resource is specifically to address issues in documentation, I need to kindly suggest you to visit [this resource](https://windowsserver.uservoice.com/forums/295047-general-feedback) to propose that idea.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @GowaP 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
