### ISSUE TITLE
How to SET DEFAULT DOMAIN of WCF SERVICE using Basic Authentication Via POWERSHELL

### ISSUE THREAD

**Issue by anagbh** [MicrosoftDocs/windows-powershell-docs#485]
IIS->DefaultWebsite->WCFService->Authentication-Basic->Edit->Set Default Domain
My question is to set Default Domain of WCF Service
Document is good

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20a2f3ef-d3cc-5786-423e-403be37a7864
* Version Independent ID: 9eae6b1d-94ae-ab0f-f407-3891f9f2ec1b
* Content: [Set-WebConfigurationProperty (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/set-webconfigurationproperty?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/Set-WebConfigurationProperty.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/Set-WebConfigurationProperty.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @anagbh 
Thanks for your feedback.
I pulled my lab and came up with an example to set the required config, so I created a pull request to add this example to the article, hopefully, it will go live in a couple of days, but you can take a look at the pr too.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @anagbh Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
