### ISSUE TITLE
Security Requirments

### ISSUE THREAD

**Issue by fran-ki** [MicrosoftDocs/windows-powershell-docs#487]
There is no mention that you must be an administrator to successfully call this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cedbec5-7d91-2cda-2161-1f93d5aa5438
* Version Independent ID: a45e8acc-b68f-6dd2-cedd-876b29685087
* Content: [Get-RDSessionCollection (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/get-rdsessioncollection?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/get-rdsessioncollection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/get-rdsessioncollection.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Malind19** [comment]
@e0i Can we please check from the tech team whether user needs to be on that machine administrator group or the domain admin group?

**Comment by Malind19** [comment]
Created PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/981

**Comment by e0i** [comment]
@fran-ki 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
