### ISSUE TITLE
Security Requirements

### ISSUE THREAD

**Issue by fran-ki** [MicrosoftDocs/windows-powershell-docs#488]
There are no comments that mention you must be an administrator to call this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0de4931b-85fa-75b6-dc56-8b61627dc73e
* Version Independent ID: 29f899d7-e8e6-57f0-2c94-9651bacefdc6
* Content: [Get-RDSessionHost (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/get-rdsessionhost?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/get-rdsessionhost.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/get-rdsessionhost.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Duplicate of #487

**Comment by e0i** [comment]
@officedocsbot close
