### ISSUE TITLE
Lots of "fill in the blank" areas

### ISSUE THREAD

**Issue by TaylorTWBrown** [MicrosoftDocs/windows-powershell-docs#491]
The documentation is mostly a bare template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21e83761-34d2-8331-fef5-5cfbc9bc2f43
* Version Independent ID: ea8bb5e4-0cd2-6e7b-b0ac-37491acfdf9d
* Content: [Export-ProvisioningPackage (provisioning)](https://docs.microsoft.com/en-us/powershell/module/provisioning/export-provisioningpackage?view=win10-ps)
* Content Source: [docset/windows/provisioning/export-provisioningpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/provisioning/export-provisioningpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @TaylorTWBrown thanks for your feedback.
I added some of the missing information and more information will be added later as we get it from product team. We will proceed closing this. @yogkumgit 
Thank you.

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR #1072 and provide your feedback here

**Comment by yogkumgit** [comment]
@officedocsbot close
