### ISSUE TITLE
Get-WindowsUpdateLog does create a human readable WindowsUpdateLog using PSSession

### ISSUE THREAD

**Issue by GuyWiththeHat** [MicrosoftDocs/windows-powershell-docs#492]
When using Get-WindowsUpdateLog using a PSSession the etl files are not properly decoded using the MS symbol server.

How to duplicate this issue.
Log into a Windows 2016 Server
Run Get-WindowsUpdateLog.
Validate that the log file is human readable and it decoded.  Eg.  2018-11-05 05:06:42.6402602 2024  4948  Shared          * START * Service startup

Connect to the Windows 2016 Server using Enter-PSSession (Enter-PSSession &lt;servername&gt;)
Run Get-WindowsUpdateLog cmdlet
Exit the PSSession.
Validate that the log file is not human readable.  Eg.  1600/12/31 19:00:00.0000000 2024  4948                  Unknown( 15): GUID=1f9e54c8-9e31-3e53-867d-d9f39756ad7f (No Format Information found).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520e85e5-7bee-f078-7cd2-5467e7deccb8
* Version Independent ID: f419c42e-f6c4-a6ae-bd91-cba3e2f1a41a
* Content: [Get-WindowsUpdateLog (windowsupdate)](https://docs.microsoft.com/en-us/powershell/module/windowsupdate/get-windowsupdatelog?view=win10-ps)
* Content Source: [docset/windows/windowsupdate/get-windowsupdatelog.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/windowsupdate/get-windowsupdatelog.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by RAJU2529** [comment]
I think .etl  can be converted  into .log text file on windows 10 pro .
Also .etl can be read using WPR tool

**Comment by e0i** [comment]
Hello, @GuyWiththeHat  thank you for providing feedback.

Note that the issue tracker of this repository is intended for product documentation issues only.

Please consider opening a support ticket for product issues and bugs via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You can also check relevant resources and ask the community regarding your problem via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
