### ISSUE TITLE
The description of the parameter -ThrottleLimit is missing in New-ScheduledTaskTrigger

### ISSUE THREAD

**Issue by Fydon** [MicrosoftDocs/windows-powershell-docs#493]
The description of the parameter -ThrottleLimit is missing in New-ScheduledTaskTrigger

> {{Fill ThrottleLimit Description}}

https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps#optional-parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cad6aa9-2504-d30a-9a51-984f52e4f9c8
* Version Independent ID: 84be6419-e750-a16e-70fc-85a3fb0d0569
* Content: [New-ScheduledTaskTrigger (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps#optional-parameters)
* Content Source: [docset/windows/scheduledtasks/new-scheduledtasktrigger.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/new-scheduledtasktrigger.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by ojrb** [comment]
Hi @e0i ! the PR #1014 solve the issue ! Please review and Merge !

**Comment by e0i** [comment]
@Fydon 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
