### ISSUE TITLE
High risk "example 2"

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/windows-powershell-docs#494]
As per the notes on "friendlyname", it is not guaranteed to be unique. Therefore the example:
```
PS C:\&gt; $phydisk = (Get-Physicaldisk | Where-Object -FilterScript {$_.HealthStatus -Eq "Unhealthy"}
PS C:\&gt; Reset-PhysicalDisk -FriendlyName $phydisk.FriendlyName
```

Will reset all disks sharing that friendly name. I have reviewed this in our environment - attempting to reset one unhealthy disk using this command will reset every single SSD in the cluster. This is obviously a dangerous suggestion.

Can I recommend using -UniqueId in the example for a reader who may miss this detail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8826868-6a17-4641-31a6-5ec04cc5bfdc
* Version Independent ID: 5ac34549-8420-f25b-3da9-2ae370c521c3
* Content: [Reset-PhysicalDisk (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/reset-physicaldisk?view=win10-ps)
* Content Source: [docset/windows/storage/reset-physicaldisk.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/reset-physicaldisk.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by doctordns** [comment]
Interesting report. 

First there is a typo in the first line of the 2nd example anyway - so the example is awful! 
And looking at the cmdlet, the `FriendlyName` parameter only takes a String, not a String[] array. So the cmdlet can only affect a single disk. Indeed - if $phydisk ends up with more than one disk, the sample script would generate and exception. Finally, the idea of using UinqueID is a great one- good catch!

The 2nd example would better be:

```powershell
$BadDisks = (Get-Physicaldisk | Where-Object -FilterScript {$_.HealthStatus -Eq "Unhealthy"}
Foreach ($BadDisk in $BadDisks) 
{
  Reset-PhysicalDisk -UniqueId $BadDisk.UniqueId
}
```

**Comment by technion** [comment]
Thanks for that!

I believe that's still not valid, there's still an extra `(` on the first line.

**Comment by doctordns** [comment]
Yes - in the above there _was_ an extra (.
That is removed in the PR.

**Comment by technion** [comment]
Thanks!
