### ISSUE TITLE
Type DataPort missing

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/windows-powershell-docs#495]
For Server 2019 the Type "DataPort" ist missing, but I´m not sure what is does

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f6e74c-4b27-e045-d262-8cac31d2f9a3
* Version Independent ID: e6eb6dde-2f79-14ff-ad20-067c256ee50e
* Content: [Start-DedupJob (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/start-dedupjob?view=win10-ps)
* Content Source: [docset/windows/deduplication/start-dedupjob.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/start-dedupjob.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @Stroell  thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Stroell** [comment]
Hey @e0i,
from my understanding this is a documentation issue, because the paramenter "Type -DataPort" is not documented. It is available on Server 2019, but missing in the documentation

**Comment by e0i** [comment]
@officedocsbot reopen

**Comment by e0i** [comment]
Hello @Stroell, Thank you for clarification.

We'll pass this issue to technical writing team for review and keep you posted on updates.

Regards.

**Comment by e0i** [comment]
Hello, @Stroell 

The content for Server 2019 is not available and the existing documentation only covers up to Windows Server 2016.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Chirishman** [comment]
Why is the content for 2019 not available? It's not like it's preview anymore, it's GA. Also to date no one has explained anywhere that I can find what `-type DataPort` does anywhere that I can find and I don't think that's acceptable.

**Comment by eponerine** [comment]
@e0i - it's almost calendar year 2020 and there's still no 2019 documentation for deduplication? This is absolutely insane.

**Comment by DarrylvanderPeijl** [comment]
Maybe @wmgries can help.

**Comment by Chirishman** [comment]
@e0i @traya1 it has been 435 days since the official non-preview release of Server 2019.

Is it Microsoft's actual position that the world just doesn't need **any** Server 2019 documentation outside of that Getting Started doc?

**Comment by Zetanova** [comment]
+1

**Comment by Krytical13** [comment]
> @e0i @traya1 it has been 435 days since the official non-preview release of Server 2019.
> 
> Is it Microsoft's actual position that the world just doesn't need **any** Server 2019 documentation outside of that Getting Started doc?
> 
> It's not like this repo is named windows-powershell-docs-up-through-2016-only and there's some 2019 repo this should be raised on instead.

@e0i

**Comment by eponerine** [comment]
Adding @coreyp-at-msft and @AndreaBarr

**Comment by JasonGerend** [comment]
Hi everyone - thanks for bringing this to our attention, and sorry for the confusion. I'm asking around on why we haven't updated the labeling and content for the Windows Server 2016 PowerShell commandlets yet. In general, the existing reference content applies to Windows Server 2019 and Azure Stack HCI as well, though the newer operating systems might add some options or commandlets we should document.
				
With regards to the dataport parameter, the dataport job type lets you start a deduplication job that loads the chunk index into memory. Once the chunk index is in memory, you can operate on it using the dataport COM APIs if you're sufficiently motivated, but I think most of our customers will want to just ignore it.

Thanks again,

Jason Gerend–Technical Writer for Azure Stack HCI, Windows Admin Center, and Windows Server

**Comment by Krytical13** [comment]
> Hi everyone - thanks for bringing this to our attention, and sorry for the confusion. I'm asking about updating the labeling and content for the Windows Server 2016 PowerShell commandlets - I know it'd be good to have the content refreshed. The existing reference content applies to Windows Server 2019 and Azure Stack HCI as well, though there are a few places where the newer operating systems add options or commandlets that would be good to document.
> 
> With regards to the dataport parameter, the dataport job type lets you start a deduplication job that loads the chunk index into memory. Once the chunk index is in memory, you can operate on it using the dataport COM APIs if you're sufficiently motivated, but I think most of our customers will want to just ignore it.
> 
> Thanks again,
> 
> Jason Gerend–Technical Writer for Azure Stack HCI, Windows Admin Center, and Windows Server

Thank you very much for the response!

In all this time, it's astounding that nobody even thought or cared enough to give a brief summary to the people directly asking.

So again, thank you!

The rest of this... Is not personally directed towards any individual:

P.S. that whole "2016 reference content applies to 2019 etc"
All that means is... You guys didn't change most of the OS, so the documentation hasn't changed.
Problem being, many of the places the OS HAS changed, hasn't been documented, so users are left speculating...

Does MS not realize that the documentation is lacking in many areas?
If this is the case, I'd suggest that points to larger organizational/management issues related to developers/documentation/assignment of responsibilities/deadlines... 

How about:
Is MS so large, and invested in saving money, that MS doesn't keep enough people to do documentation for all of their many software's?

Another person's perspective might be:
Do they not care about the customers/product enough to spend money on making sure the documentation is complete?

Or my personal view:
Does MS purposely keep certain aspects of their documentation vague, to push customers to pay for specialized support from Microsoft?  (Lookin at you "Premier" support)

**Comment by Chirishman** [comment]
Holy crap, an answer!

Seriously though, thank you for actually answering the question. **Please also follow up by adding this information to the actual document in question** as it does not yet reflect this additional information.

Most interactions with Microsoft in recent years seem to go like this, either taking years to get a non #wontfix answer or in a few cases getting explicitly told that I should work for a bigger company which has Premier and report it that way if I actually want it fixed or taken seriously.
