### ISSUE TITLE
https://support.microsoft.com/app/content/api/content/feeds/sap/vi-vn/489e3a24-a9c2-5b39-14bc-d68a0274ab6b-label/rss

### ISSUE THREAD

**Issue by QuyenNguyenCDA** [MicrosoftDocs/windows-powershell-docs#496]
https://support.microsoft.com/app/content/api/content/feeds/sap/vi-vn/489e3a24-a9c2-5b39-14bc-d68a0274ab6b-label/rss

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 4224af90-6318-aa88-3f92-4819f346e72f
* Version Independent ID: 37c45257-8112-874e-2fb3-8cd863ae72e1
* Content: [Enable-WindowsErrorReporting (windowserrorreporting)](https://docs.microsoft.com/vi-vn/powershell/module/windowserrorreporting/Enable-WindowsErrorReporting?view=win10-ps#related-links)
* Content Source: [docset/windows/windowserrorreporting/enable-windowserrorreporting.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/windowserrorreporting/enable-windowserrorreporting.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by doctordns** [comment]
not sure what the issue is - the URL cited by OP give a 404.

**Comment by e0i** [comment]
@officedocsbot close
