### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by KurtBuff** [MicrosoftDocs/windows-powershell-docs#50]
There appears to be a redundancy in example 2 for the cmdlet:

----------Begin Example 2----------
    Example 2: Remove replication groups using a wildcard

    PS C:\> Remove-DfsReplicationGroup -GroupName "RG*" -RemoveReplicatedFolders -Domain corp.contoso.com -RemoveReplicatedFolders
    Performing this operation will remove the replication group "RG01" and the subscriptions members have to this replication group. Are you sure you want to continue to remove this replication group? [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

    Performing this operation will remove the replication group "RG02" and the subscriptions members have to this replication group. Are you sure you want to continue to remove this replication group? [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

    Performing this operation will remove the replication group "RG03" and the subscriptions members have to this replication group. Are you sure you want to continue to remove this replication group? [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

    This command removes all replication groups that include the pattern RG* in domain corp.contoso.com, even if the groups include replicated folders.
----------End Example 2----------

Notice the parameter -RemoveReplicatedFolders being used twice? This seems to be redundant

Kurt

**Comment by brianlic-msft** [comment]
@KurtBuff Thanks for catching this!  I've updated it and the change should be published shortly.
