### ISSUE TITLE
Timeout settings

### ISSUE THREAD

**Issue by Jodyl1971** [MicrosoftDocs/windows-powershell-docs#502]
When installing a rather large provisioning package, I get the following error:
Install-ProvisioningPackage : Process 'c:\windows\system32\provtool.exe' with args '"D:\CustomAppPackage.ppkg' /quiet /source PSCmdlet' took longer than '180000' milli-sec

Of course it does - the full deployment takes 11 minutes, or 660000 milliseconds roughly. How do I get this to continue? I do not see any options to set the timeout at all. This should be added for things that take longer than 3 minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a70dc9-0ed5-c924-7187-679f3747fea7
* Version Independent ID: 76ba113d-f32d-058d-f7a2-7c8daadba900
* Content: [Install-ProvisioningPackage (provisioning)](https://docs.microsoft.com/en-us/powershell/module/provisioning/install-provisioningpackage?view=win10-ps)
* Content Source: [docset/windows/provisioning/install-provisioningpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/provisioning/install-provisioningpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by brookspeppin** [comment]
I am seeing the same thing. Can you add a parameter to control the timeout?

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Jodyl1971 thanks for your feedback.
From documentation side, I can tell you that there isn't currently a timeout parameter on it.
As this is a resource to report of issues in documentation, i found more suitable in this case a support resource, please visit https://support.microsoft.com and also this one https://windowsserver.uservoice.com/forums/301869-powershell which _accepts bug reports as well as feedback and suggestions_
Thank You

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Jodyl1971 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
