### ISSUE TITLE
Get-ScheduledTask - Wildcard characters are allowed

### ISSUE THREAD

**Issue by Brian9770** [MicrosoftDocs/windows-powershell-docs#505]
The wildcard character is allowed to query TaskScheduler by TaskName. The documentation should be corrected. Example: GetScheduledTask -TaskName "*" will return all scheduled tasks whereas GetScheduledTask -TaskName "M*" will filter the results by those beginning with "M".  String search are case insenstive also so GetScheduledTask -TaskName "m*" return the same results as the prior example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e47f429-41d8-3638-65ea-079a354e3f1f
* Version Independent ID: 9166ee0e-e609-fd42-7b0a-4b396a6187d6
* Content: [Get-ScheduledTask (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/get-scheduledtask?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/get-scheduledtask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/get-scheduledtask.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@Brian9770 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
