### ISSUE TITLE
-CategoryList switch <ul> is missing StorageReplication

### ISSUE THREAD

**Issue by j1mmyfever** [MicrosoftDocs/windows-powershell-docs#509]
It's in the accepted value list below it, but the &lt;ul&gt; stands out more and it's missing there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a27c09b9-02f9-6591-3ed8-1a92a86d3c09
* Version Independent ID: 76a11880-0878-30f9-a8d6-f6a7bef156fe
* Content: [Set-SmbBandwidthLimit (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/set-smbbandwidthlimit?view=win10-ps)
* Content Source: [docset/windows/smbshare/set-smbbandwidthlimit.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/smbshare/set-smbbandwidthlimit.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @j1mmyfever 
Thanks for your feedback, I created a Pull Request to include the missing parameter value.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @j1mmyfever Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
