### ISSUE TITLE
There is no "-Credential" parameter in WS2016 RTM

### ISSUE THREAD

**Issue by niuke** [MicrosoftDocs/windows-powershell-docs#51]
I tried this cmdlet on Windows Server 2016 Datacenter RTM, it doesn't have "-Credential" parameter there. Please check out the source code in "Debug-NetworkControllerConfigurationState.psm1", you'll find it.

**Comment by brianlic-msft** [comment]
@niuke Thanks for reporting this!  I've reached out to the engineering team and will report back.

**Comment by brianlic-msft** [comment]
@anirbanpaul Can you help with this one?

**Comment by AnirbanPaul** [comment]
@niuke, can you check once again. I can see the Credential parameter on Server builds. Please paste the output of Get-Help Debug-NetworkControllerConfigurationState.

**Comment by niuke** [comment]
@AnirbanPaul , here you go.


PS C:\Users\Administrator> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0


PS C:\Users\Administrator>  Get-Help Debug-NetworkControllerConfigurationState

NAME
    Debug-NetworkControllerConfigurationState

SYNTAX
    Debug-NetworkControllerConfigurationState [-NetworkController] <string> [[-ResourceId] <string>] [[-ResourceType] <string>]  [<CommonParameters>]


ALIASES
    None


REMARKS
    Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help.
        -- To download and install Help files for the module that includes this cmdlet, use Update-Help.



PS C:\Users\Administrator> Get-Command Debug-NetworkControllerConfigurationState

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Debug-NetworkControllerConfigurationState          1.0.0.0    NetworkControllerDiagnostics


PS C:\Users\Administrator>

**Comment by AnirbanPaul** [comment]
Thanks. It is possible that this parameter was added after the Server 2016 release. If you need to use this parameter, you can either move to RS3 build (when it is released), or you can use the attached script in your setup.
To use the attached script, 
a. Download the script to the machine where you want to run it. Extract the script from the zip file.
b. On a Powershell prompt, run the cmldet import-module Debug-NetworkControllerConfigurationState.psm1
c. Now,  run the cmdlet  Debug-NetworkControllerConfigurationStatev2 (Note the change in the noun)
[Debug-NetworkControllerConfigurationState.zip](https://github.com/MicrosoftDocs/windows-powershell-docs/files/1086341/Debug-NetworkControllerConfigurationState.zip)

**Comment by AnirbanPaul** [comment]
[Debug-NetworkControllerConfigurationState.zip](https://github.com/MicrosoftDocs/windows-powershell-docs/files/1086346/Debug-NetworkControllerConfigurationState.zip)

**Comment by niuke** [comment]
@AnirbanPaul , thank you.
