### ISSUE TITLE
AuditSmb1Access Missing Description

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/windows-powershell-docs#510]
Looks like someone left a placeholder in the description field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ef5cd9-be58-e25b-8ceb-d5ce997e1239
* Version Independent ID: 33e79b50-9b3a-1fa7-0950-aa902d128d44
* Content: [Set-SmbServerConfiguration (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=win10-ps)
* Content Source: [docset/windows/smbshare/set-smbserverconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/smbshare/set-smbserverconfiguration.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ChrisKibble thanks for your feedback.
I created a Pull Request to improve the article adding the missing description.
Thank You

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ChrisKibble Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
