### ISSUE TITLE
what about SSL?

### ISSUE THREAD

**Issue by stylerOD** [MicrosoftDocs/windows-powershell-docs#511]
How do you specify the certificate to use with the binding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da76afd1-11fc-fc9d-5464-21338af39224
* Version Independent ID: fa45b9ca-a904-105b-9b3b-a346b013f0da
* Content: [Set-WebBinding (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/set-webbinding?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/Set-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/Set-WebBinding.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
Hello, @stylerOD  thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by stylerOD** [comment]
My product documentation issue is that the documentation for Set-WebBinding makes no mention of how to specify the certificate being bound to a site when using port 443.

**Comment by nicksterx** [comment]
@stylerOD It's not well documented how to do it. But you have to use Get-WebBinding and then AddSslCertificate.

This stackoverflow post helped me
https://serverfault.com/a/757904/50097

Relevant PowerShell:
```
$bind = Get-WebBinding -Name $webSiteDNSName -Protocol https
$bind.AddSslCertificate($webServerCert.GetCertHashString(), "my")
```
