### ISSUE TITLE
-MountPath Errata

### ISSUE THREAD

**Issue by msun-km** [MicrosoftDocs/windows-powershell-docs#512]
The documentation states to import a .xml to a mounted Windows image, you can use the powershell command: 
  PS C:\&gt; Import-StartLayout -LayoutPath "Layout.xml" -MountPath "E:\MountedImage\"

This will generate an error.  You cannot end -MountPath with a '\' character, if you do, PowerShell throws the error: 
  Import-StartLayout : The path B:\WIMs\Test\ did not resolve to a file.

If you format the command: 
   PS C:\&gt; Import-StartLayout -LayoutPath "Layout.xml" -MountPath "E:\MountedImage"
You will receive the following error:
  Import-StartLayout : Could not find a part of the path
  'E:\MountedImageUsers\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml'.
Note the missing '\' character between "MountedImage" and "Users"
This appears to be an error in the Import-StartLayout commandlet.  

For a workaround, I used Junction64.exe to create the expected 'E:\MountedImageUsers' junction targeted to 'E:\MountedImage\Users'

At this point, the command completed successfully.  I removed the dummy junction, and was able to commit the changes and Un-Mount the wim file.
 PS C:\ DISM.exe /Unmount-Wim /MountDir:'E:\MountedImage' /commit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145bea4e-cfa0-496b-a76f-47afa5aafcb2
* Version Independent ID: 60cd8847-a46f-67a7-6b98-e9a40862fefa
* Content: [Import-StartLayout (startlayout)](https://docs.microsoft.com/en-us/powershell/module/startlayout/import-startlayout?view=win10-ps)
* Content Source: [docset/windows/startlayout/import-startlayout.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/startlayout/import-startlayout.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by AceLearnGit** [comment]
I  pin my app to start and then use "PS C:\> Export-StartLayout -Path "C:\Layouts\Marketing.xml" to export a .xml file, then i use "PS C:\> Import-StartLayout -LayoutPath "Layout.xml" -MountPath "C:\Layouts\Marketing.xml" cmd to import the .xml but powershell return error"can't find path C:\Layout.xml"
why?

**Comment by e0i** [comment]
@msun-km 

The issues section of this repository is intended for documentation problems.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
