### ISSUE TITLE
Origabank.net

### ISSUE THREAD

**Issue by Origa7jeffrey** [MicrosoftDocs/windows-powershell-docs#513]
[origabank.net]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6ab1f4-9e55-465e-535a-e00d080c8151
* Version Independent ID: aa6493bc-4002-bdfd-9ddc-b4a3e22ea097
* Content: [Add-ADDSReadOnlyDomainControllerAccount (addsdeployment)](https://docs.microsoft.com/en-us/powershell/module/addsdeployment/add-addsreadonlydomaincontrolleraccount?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/addsdeployment/Add-ADDSReadOnlyDomainControllerAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/addsdeployment/Add-ADDSReadOnlyDomainControllerAccount.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by Origa7jeffrey** [comment]
Donation point

**Comment by Origa7jeffrey** [comment]
Hmmm, sorry for the report, I'm stuck while trying to reproduce it using the test template, it might be something else in my code. Will reopen if I find the trigger is on A to Z

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure._
