### ISSUE TITLE
Get-PhysicalExtent Example 1 DOES NOT WORK - AT ALL

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/windows-powershell-docs#514]
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-physicalextent.md

Example 1 currently says:

> # Example 1: Get all physical extents on a disk
>
> `PS C:\>Get-PhysicalExtent -PhysicalDisk (Get-PhysicalDisk -FriendlyName "PhysicalDisk4")`
>
> This command gets all physical extents on the physical disk named PhysicalDisk4. The command uses Get-PhysicalDisk to obtain PhysicalDisk4.

This DOES NOT WORK - AT ALL.

```powershell
PS C:\WINDOWS\system32> get-physicaldisk

FriendlyName            SerialNumber    MediaType CanPool OperationalStatus HealthStatus Usage            Size
------------            ------------    --------- ------- ----------------- ------------ -----            ----
Samsung SSD 860 EVO 4TB S3YNNB0KA01262B SSD       False   OK                Healthy      Auto-Select   3.64 TB
Crucial_CT1050MX300SSD1 1652152B887B    SSD       False   OK                Healthy      Auto-Select 978.09 GB


PS C:\WINDOWS\system32> get-physicaldisk -FriendlyName "Samsung SSD 860 EVO 4TB"

FriendlyName            SerialNumber    MediaType CanPool OperationalStatus HealthStatus Usage          Size
------------            ------------    --------- ------- ----------------- ------------ -----          ----
Samsung SSD 860 EVO 4TB S3YNNB0KA01262B SSD       False   OK                Healthy      Auto-Select 3.64 TB


PS C:\WINDOWS\system32> Get-PhysicalExtent -PhysicalDisk (get-physicaldisk -FriendlyName "Samsung SSD 860 EVO 4TB")
Get-PhysicalExtent : Not Supported
Activity ID: {7ba2cd2e-bd23-4b54-b4dc-c6a9ae118492}
At line:1 char:1
+ Get-PhysicalExtent -PhysicalDisk (get-physicaldisk -FriendlyName "Sam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PhysicalExtent], CimException
    + FullyQualifiedErrorId : StorageWMI 1,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand,Get-PhysicalExtent

```

# Additional Notes:

1. `-FriendlyName` is not guaranteed to be unique.  In AWS EBS gp2 volumes, all volumes have the same friendly name: "NVMe Amazon Elastic B". All ephemeral storage volumes also have the same friendly name: "NVMe Amazon EC2 NVMe"
2. Passing in `-SerialNumber` gives a vague Not supported error message.
3. How do I select a unique disk id and get the physical extent info for it? I tried generalizing the example in Get-PhysicalExtent but I get unhelpful "Not supported" messages
```powershell
PS C:\Users\John.Zabroski>  get-physicalextent -physicaldisk $(Get-PhysicalDisk | Where { $_.UniqueId -eq "vol00a4d94952a9503a80001Amazon Elastic Block Store              1D0F" })
get-physicalextent : Not Supported
Activity ID: {ca3f517d-6f2b-4b9c-a2f7-9151584db3e2}
At line:1 char:2
+  get-physicalextent -physicaldisk $(Get-PhysicalDisk | Where { $_.Uni ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PhysicalExtent], CimException
    + FullyQualifiedErrorId : StorageWMI 1,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand,Get-P
   hysicalExtent
```

**Comment by jzabroski** [comment]
@e0i  Hi - I think the issue here is that the phrase "extent" is overloaded in Microsoft-land, and the examples in isolation don't make it clear what extent this doc is referring to when you land on it from Google Search.

**Comment by e0i** [comment]
Hello, @jzabroski 

We are investigating this issue and will follow up with updates.

Thank you for your feedback and following up.

**Comment by jzabroski** [comment]
@e0i  Someone on StackOverflow already answered my questions. One second while I update this response with the stackoverflow answer - effectively, the issue is the documentation is not clear that this command doesn't work for regular extents, because the word extent is overloaded and not really documented well by MSFT

**Comment by jzabroski** [comment]
https://serverfault.com/questions/946676/how-do-i-use-get-physicalextent-on-get-physicaldisk/946834#946834

**Comment by jzabroski** [comment]
To be clear, please don't close this, as I still think this is wicked confusing.

**Comment by j0rt3g4** [comment]
To be honest @jzabroski  I replicated the issue as well on my computer (Virtual machine with WS 2019)
http://prntscr.com/ng26y5

This, however, is a "Cmdlet issue" instead of a lack of documentation, I've expanded the documentation but we need to wait for the author to be present about it. on PR #1011 

@e0i We need to contact the author so he can expand the knowledge about it because the cmdlet didn't work as expected and is not on the documentation

**Comment by e0i** [comment]
@jzabroski 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
