### ISSUE TITLE
How About Non Interactive Mode ?

### ISSUE THREAD

**Issue by KaizounaTOR** [MicrosoftDocs/windows-powershell-docs#519]
Hi,

I want use this command in non interactive mode. It seems impossible right now.
The "confirm" switch to false does not work :/

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50c2b30-1fa3-e773-5a33-6db1ee3cffe0
* Version Independent ID: b6a614dc-8130-b85a-ceec-1296fb5b594a
* Content: [New-NetLbfoTeam (netlbfo)](https://docs.microsoft.com/en-us/powershell/module/netlbfo/new-netlbfoteam?view=win10-ps)
* Content Source: [docset/windows/netlbfo/new-netlbfoteam.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netlbfo/new-netlbfoteam.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@KaizounaTOR

Note that the issues section of this repository is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
