### ISSUE TITLE
Resolve-DnsName is missing in the list for W10 and W2016 operating systems

### ISSUE THREAD

**Issue by docteurdid** [MicrosoftDocs/windows-powershell-docs#520]
Below the link for this cmdlet:
https://docs.microsoft.com/en-us/powershell/module/dnsclient/Resolve-DnsName?view=winserver2012r2-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d783b08d-bb01-da8f-e49c-7e18aac96e43
* Version Independent ID: eee454be-aacf-d781-ff57-bd9f19c32191
* Content: [DnsClient](https://docs.microsoft.com/en-us/powershell/module/dnsclient/?view=win10-ps)
* Content Source: [docset/windows/dnsclient/dnsclient.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsclient/dnsclient.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @docteurdid thanks for your feedback.
I created a pull request to add the article to the current version of Windows.
Hopefully, it will be on the live version in the next couple of days.
Thank You

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @docteurdid Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
