### ISSUE TITLE
Invalid module names in table

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/windows-powershell-docs#522]
In the table column "Module Name (sorted by)", a number of module names are missing and displayed as "&lt;!--", e.g. for CisAgent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1516d5c3-4895-cf8b-f5a9-370e2bd0f1e6
* Version Independent ID: 6e9677e3-763f-9689-3219-69b7c8b7685d
* Content: [Windows 8.1 and Windows Server 2012 R2](https://docs.microsoft.com/en-us/powershell/windows/get-started?view=winserver2012r2-ps)
* Content Source: [docset/docs-conceptual/winserver2012r2-ps/get-started.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/docs-conceptual/winserver2012r2-ps/get-started.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by jawn** [comment]
Example of the issue in this page:

![image](https://user-images.githubusercontent.com/1705112/50684644-9c5a4f80-1016-11e9-8460-ba3c3a94ab84.png)

**Comment by e0i** [comment]
@jawn 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
