### ISSUE TITLE
MSOL Powershell commands have been removed from Azure AD PowerShell v2

### ISSUE THREAD

**Issue by rodsaw11** [MicrosoftDocs/windows-powershell-docs#523]
The commandlets *-MSOL* are the legacy commands from MSOnline module.  Example 1 on this page needs to be updated with the new commandlets in the Azure Active Directory V2 module.  Here's the blurb about the MSOnline module being legacy:
MSOnline
Note: this is the older MSOnline V1 PowerShell module for Azure Active Directory. Customers are encouraged to use the newer Azure Active Directory V2 PowerShell module instead of this module. For more information about the V2 module please see Azure Active Directory V2 PowerShell.
https://docs.microsoft.com/en-us/powershell/module/msonline/?view=azureadps-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38a7b30-5986-1637-ec51-a9ce42f3061e
* Version Independent ID: cfefffa6-78f0-124b-d91d-95f0bbecfa98
* Content: [New-AdfsAzureMfaTenantCertificate (adfs)](https://docs.microsoft.com/en-us/powershell/module/adfs/new-adfsazuremfatenantcertificate?view=win10-ps)
* Content Source: [docset/windows/adfs/new-adfsazuremfatenantcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/new-adfsazuremfatenantcertificate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@rodsaw11 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@rodsaw11 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Midacts** [comment]
This might not be the best place to ask, but is this stating the v2 of the AzureAD PowerShell module can replace the MSOL PowerShell module?
