### ISSUE TITLE
Error in documentation re DfsnPath, it is more than just a descriptive field

### ISSUE THREAD

**Issue by mossywell** [MicrosoftDocs/windows-powershell-docs#525]
Whilst it is true that the cmdlet doesn't check the path, the DfsnPath field can be used to "link" a replication group to a namespace folder. E.g. if the RG is called "MyFiles" and a separate folder was also created called "MyFiles", they will be treated as separate in the DFS GUI even though they have the same name. Use of DfsnPath links the two as if "publish to namespace" had been done. This has important implications when editing the replication group as it also then automatically affects the namespace.  Therefore, it is more than just cosmetic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 389de5cf-f3a3-3051-0fb7-aa1d061986ae
* Version Independent ID: e54bb1e3-da8b-81f1-6613-50867a66436f
* Content: [Set-DfsReplicatedFolder (dfsr)](https://docs.microsoft.com/en-us/powershell/module/dfsr/set-dfsreplicatedfolder?view=win10-ps)
* Content Source: [docset/windows/dfsr/set-dfsreplicatedfolder.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dfsr/set-dfsreplicatedfolder.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@mossywell 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
