### ISSUE TITLE
Error in PowerShell code example

### ISSUE THREAD

**Issue by sejool** [MicrosoftDocs/windows-powershell-docs#526]
On line two the variable ends with a "1" that should not be there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 512b540d-1286-5344-4eb3-da79bdcbb601
* Version Independent ID: ca132b3a-24a0-46a6-8fc7-1bbf6930c29a
* Content: [New-WinUserLanguageList (international)](https://docs.microsoft.com/en-us/powershell/module/international/new-winuserlanguagelist?view=win10-ps)
* Content Source: [docset/windows/international/new-winuserlanguagelist.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/international/new-winuserlanguagelist.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by doctordns** [comment]
resolved in PR #530

**Comment by e0i** [comment]
@officedocsbot close
