### ISSUE TITLE
No return value or exceptions list

### ISSUE THREAD

**Issue by jason-neumann** [MicrosoftDocs/windows-powershell-docs#527]
The documentation should show the return value of all commands, even if it returns nothing. Similarly, if there are exceptions that the command can throw, that should be included in the documentation as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 396d4612-0240-2ddb-442c-43910d659d41
* Version Independent ID: 4700a39a-5694-1d2d-e166-354704cd19f3
* Content: [Install-ADDSDomainController (addsdeployment)](https://docs.microsoft.com/en-us/powershell/module/addsdeployment/install-addsdomaincontroller?view=win10-ps)
* Content Source: [docset/windows/addsdeployment/install-addsdomaincontroller.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsdeployment/install-addsdomaincontroller.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@jason-neumann 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
