### ISSUE TITLE
New-FSRMStorageReport - Example 3 returns an error

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#529]
I am attempting to reproduce example 3 and am failing. Here is what I see:

```powershell
PS C:\foo&gt; # The first command gets a **DateTime** object and stores it in the $d variable.
$d = (get-date "12:00am")

# This second command returns an **FsrmScheduledTask** object that describes a schedule that runs the task at midnight on the first day of the month. The command stores results in the $task variable.
$task = new-FsrmScheduledTask -Time $d.ToFileTimeUtc() -Monthly 1

# The third command creates a LargeFiles storage report named "Find large files" that generates a Large Files report on any folders whose Folder Usage property includes the User Data value. The command sets the schedule for the report stored in the $task variable.
New-FsrmStorageReport -Name "Find large files" -Namespace @("[FolderUsage=User Data]") -Schedule $task -ReportType @("LargeFiles")
New-FsrmStorageReport : 0x80070057, The parameter is incorrect.
At line:8 char:1
+ New-FsrmStorageReport -Name "Find large files" -Namespace @("[FolderU ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (MSFT_FSRMStorageReport:Root/Microsoft/...RMStorageReport) [New-FsrmStorageReport], CimE 
   xception
    + FullyQualifiedErrorId : MI RESULT 4,New-FsrmStorageReport
 ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5769cf18-192d-898d-21f5-05f8bd7bbb84
* Version Independent ID: 1b8d4e9e-9ce3-4091-0d80-edd253cb1550
* Content: [New-FsrmStorageReport (fileserverresourcemanager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/new-fsrmstoragereport?view=win10-ps#feedback)
* Content Source: [docset/windows/fileserverresourcemanager/new-fsrmstoragereport.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/fileserverresourcemanager/new-fsrmstoragereport.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by MaratMussabekov** [comment]
Dear @doctordns ,
I had the same issue, when i tried.
it looks like there is a error in **$task = new-FsrmScheduledTask -Time $d.ToFileTimeUtc() -Monthly 1**
When I run **$task = new-FsrmScheduledTask -Time $d -Monthly 1**
The command run successfully.
I will perform further investigation then create a PR for this issue.

Thank you

**Comment by e0i** [comment]
@doctordns 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
