### ISSUE TITLE
Description for -MaxMBFileSize is incorrect, I think

### ISSUE THREAD

**Issue by TheFiZi** [MicrosoftDocs/windows-powershell-docs#531]
After reviewing this page: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc726869(v=ws.10)

I believe the description for "" should read "Specifies the maximum size on disk all audit logs can consume, in megabytes (MB)." not "Specifies the maximum size of the audit log, in megabytes (MB)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa17e0c-cb56-0370-304b-bcaa6366f360
* Version Independent ID: a9f5129b-3939-e712-03a1-b10e9febcc35
* Content: [Set-DhcpServerAuditLog (dhcpserver)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/set-dhcpserverauditlog?view=win10-ps)
* Content Source: [docset/windows/dhcpserver/set-dhcpserverauditlog.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dhcpserver/set-dhcpserverauditlog.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@TheFiZi  

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
