### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by PaulDrumm** [MicrosoftDocs/windows-powershell-docs#533]
It would be IMMENSELY helpful if it was documented what the log levels 0-5 meant on this page.
0 is disabled
1 is error
2 is warning
3 is Default when the cluster is installed  which is info
4 is verbose
5 is debug

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eadb86d1-35c4-450b-cbd5-53d74502cc1d
* Version Independent ID: 59186918-a2ce-5a0e-7f42-f5953c7eebd3
* Content: [Set-ClusterLog (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterlog?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/set-clusterlog.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/set-clusterlog.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@PaulDrumm 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
