### ISSUE TITLE
Command not behaving as expected

### ISSUE THREAD

**Issue by JFarthing** [MicrosoftDocs/windows-powershell-docs#535]
I have an issue when running Set-NetConnectionProfile on a Virtual Machine with 2 seperate NICs. I have a requirement for one NIC to be a Private profile, the other is Public. When running the command against either of the 2 NIC Profiles (using -InterfaceAlias or -InterfaceIndex) the command always changes the profile for both connections.

I've tried using the command as per the example and it doesn't function at all. The "$Profile.NetworkCategory = Public" line fails with the following error:
"Public : The term 'Public' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

I only have this behaviour in a Server 2016 Virtual Machine, in Server 2012R2 it works as expected and I can set the profiles independently.

Any help would be appreciated! James.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18e96475-a601-25ea-66c8-0c646042cbfb
* Version Independent ID: f42c8e2b-b5bd-cf1e-188b-7c4f7836a5b2
* Content: [Set-NetConnectionProfile (netconnection)](https://docs.microsoft.com/en-us/powershell/module/netconnection/set-netconnectionprofile?view=win10-ps)
* Content Source: [docset/windows/netconnection/set-netconnectionprofile.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netconnection/set-netconnectionprofile.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @JFarthing  thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
