### ISSUE TITLE
Missing cimsession

### ISSUE THREAD

**Issue by DKusnir** [MicrosoftDocs/windows-powershell-docs#536]
Is it possible to create trigger using Event source ? i cannot find any example for that . Can you list some example ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cad6aa9-2504-d30a-9a51-984f52e4f9c8
* Version Independent ID: 84be6419-e750-a16e-70fc-85a3fb0d0569
* Content: [New-ScheduledTaskTrigger (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/new-scheduledtasktrigger.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/new-scheduledtasktrigger.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DKusnir 
Thanks for your feedback.
As the article says _Event-based triggers include starting a task when the system starts up or when a user logs on to the computer_
Those are currently, the event-based triggers available to be created.
About the cimSession, I'll create a pull request to add the missing description.
Thank you

**Comment by get-itips** [comment]
Hello @DKusnir I could confirm that the Pull Request will be reflected soon. We will proceed closing this. Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @DKusnir 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
