### ISSUE TITLE
Bad example?

### ISSUE THREAD

**Issue by AndyChips** [MicrosoftDocs/windows-powershell-docs#537]
At the time of writing, the example doesn't look valid to me:
@{navigationLink=@{uri=http://go.microsoft.com/fwlink/p/?LinkId=113302; linkText=Format-List}; #text=System.Management.Automation.PSObject[]}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64ee4119-15f0-28b0-171e-da91a788054e
* Version Independent ID: 6cb284c5-9bb1-f1ee-1e6c-0610af0105bb
* Content: [Disconnect-VpnUser (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/disconnect-vpnuser?view=win10-ps)
* Content Source: [docset/windows/remoteaccess/disconnect-vpnuser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remoteaccess/disconnect-vpnuser.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@AndyChips 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
