### ISSUE TITLE
New-DFSNRootTarget creates spurious error

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#541]
I am using **New-DFSNRootTarget** to create a second DFSN target to a new DFSN namespace. If I do the following:

```powershell
 $NSHT2 = @{
   Path       = '\\Reskit.Org\ShareData'
   TargetPath = '\\SRV2\ShareData'
 } 
 New-DfsnRootTarget @NSHT2 | Out-Null
 ```
Those step produces this output:
```powershell
New-DfsnRootTarget : The requested object could not be found.
At line:5 char:1
+ New-DfsnRootTarget @NSHT2 | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_DfsNamespaceRootTarget:ROOT\Microsoft\...spaceRootTarget)
                              [New-DfsnRootTarget], CimException
    + FullyQualifiedErrorId : MI RESULT 6,New-DfsnRootTarget
```
There is no real clue as to what object can not be found, but the DFSN is created just fine. If I use **Get-DFSNRootTarget**, I can see the second target just fine:
```powershell
PS C:\Foo> Get-DfsnRootTarget -Path \\Reskit.Org\ShareData
Path                   TargetPath                  State  ReferralPriorityClass ReferralPriorityRank
----                   ----------                  -----  --------------------- --------------------
\\Reskit.Org\ShareData \\SRV1.Reskit.Org\ShareData Online sitecost-normal       0                   
\\Reskit.Org\ShareData \\SRV2.Reskit.Org\ShareData Online sitecost-normal       0        
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1efe011-5f75-9929-8de7-d35d4ff9116f
* Version Independent ID: 8418a00d-7ba8-eb17-0d05-8e9e1f3cf0ee
* Content: [New-DfsnRootTarget (dfsn)](https://docs.microsoft.com/en-us/powershell/module/dfsn/new-dfsnroottarget?view=win10-ps#feedback)
* Content Source: [docset/windows/dfsn/new-dfsnroottarget.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dfsn/new-dfsnroottarget.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @doctordns 
Thanks for your feedback.
This issue resource is specifically to address issues in documentation.
Besides that, please see [this](https://social.technet.microsoft.com/Forums/SqlServer/en-US/21038481-5508-4bc8-b31a-f3898130f511/newdfsnroottarget-gives-quotrequested-object-could-not-be-foundquot-but-seems-to-succeed?forum=winserverfiles)
and [this](https://support.microsoft.com/de-de/help/244380/how-to-configure-dfs-to-use-fully-qualified-domain-names-in-referrals)

Hope this information helps you.
Thanks

**Comment by doctordns** [comment]
The cmdlet still creates a spurious error message. :-)

**Comment by get-itips** [comment]
I agree with you @doctordns  that the cmdlet should better describe the error, please visit this resource to suggest that improvement https://windowsserver.uservoice.com/forums/301869-powershell as that is out of the scope of Docs.
Thank you

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by jiju-s-1983** [comment]
Using the above script , I cannot create the DFS Root target to Network Share . I have a requirement where I need to access the Share using the Root name space in 2016 Server . 
With 2019 I am getting error  like 
 New-DfsnRootTarget : One or more parameter values passed to the method were invalid. 
with 2016 I am getting error like : 

New-DfsnRootTarget :  Can't add DFS Namespace Folder target "\\Hostname\Share" 
Windows System error 1168 , New-DfsnFolder Target . 

What changes you made to update the DFS Root target folder to Network Share .

**Comment by jonvickers** [comment]
you need to use the FQDN Fully Qualified Domain Name when using at least the -TargetPath argument.
