### ISSUE TITLE
Why doesn't this support -alluserconnection

### ISSUE THREAD

**Issue by michaelkrieger** [MicrosoftDocs/windows-powershell-docs#542]
This can't be applied to -alluserconnection VPN Connections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d70f95-0d79-c79d-407e-62ce149c1dfd
* Version Independent ID: 92eed0c2-bd40-4b49-1fb7-a1060771fa1e
* Content: [Set-VpnConnectionTriggerDnsConfiguration (vpnclient)](https://docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectiontriggerdnsconfiguration?view=win10-ps)
* Content Source: [docset/windows/vpnclient/set-vpnconnectiontriggerdnsconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/vpnclient/set-vpnconnectiontriggerdnsconfiguration.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @michaelkrieger 
Thanks for your feedback.
Can you kindly tell me if is there any specific issue you see with the documentation of the cmdlet?
Tell me please if I misunderstood but I think that maybe your question is more suitable for user voice, kindly visit here.
https://windowsserver.uservoice.com/forums/295047-general-feedback

Thank you

**Comment by yogkumgit** [comment]
@officedocsbot close
