### ISSUE TITLE
Use of Quota Notification Variables

### ISSUE THREAD

**Issue by gdukevt** [MicrosoftDocs/windows-powershell-docs#544]
One of the most useful aspects of the notifications is the ability to use Quota Notification Variables, so that a single quota template can be used for many quotas, which send alerts with useful details pertaining to a specific quota. I have found that the variables can also be used in the various string arguments for this cmdlet, which is the only feasible way to create email notifications that go to end users, for example, for home directory quotas.

See https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc788122%28v%3dws.10%29#quota-notification-variables . I hope this doc doesn't disappear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d5a4bde-48cb-e338-ae35-fea6719b3ea6
* Version Independent ID: dff89e35-1f4a-efbd-15aa-02d5ce0ab606
* Content: [New-FsrmAction (fileserverresourcemanager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/new-fsrmaction?view=win10-ps)
* Content Source: [docset/windows/fileserverresourcemanager/new-fsrmaction.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/fileserverresourcemanager/new-fsrmaction.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @gdukevt thanks for your feedback.
Could you please specify what you think should be corrected in the New-FsrmAction article? Or, if you are just suggesting that the _Quota notification variables_ article be maintained?
We appreciate, thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @gdukevt We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
