### ISSUE TITLE
Link for CreateNonDADkmContainer.ps1 does not work

### ISSUE THREAD

**Issue by kdutt** [MicrosoftDocs/windows-powershell-docs#545]
Looks like the link is broken again
In windows-powershell-docs/docset/windows/adfs/install-adfsfarm.md, example 5 and 6 refer to CreateNonDADkmContainer.ps1.

Same as Issue #35

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @AndreaBarr can you help us finding the right people to ask here? Thanks

**Comment by get-itips** [comment]
Link is not present in the article anymore.
@yogkumgit please close this one.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kdutt 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
