### ISSUE TITLE
Global Catalog Example

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/windows-powershell-docs#546]
It would be better to use service name and not service number in example 4 above: 
```PowerShell
# current example
Get-ADDomainController -Discover -Service 2
# more understandable
Get-ADDomainController -Discover -Service GlobalCatalog
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ce46c3-32ef-1794-87a5-e6698f9d5aa2
* Version Independent ID: e065dc85-7ad4-cc7c-ccbc-6fdfbe8ca985
* Content: [Get-ADDomainController (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-addomaincontroller?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Get-ADDomainController.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Get-ADDomainController.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by iricigor** [comment]
I did not see it immediately within `Get-Help`... Examples 3 and 4 are the same just, one is using number and the other one service name. Should one of these be removed or somehow explanation extended?

```text
-------------------------- EXAMPLE 3 --------------------------

    C:\PS>Get-ADDomainController -Discover -Service "GlobalCatalog"

    Description

    -----------

    Get a global catalog in the current forest using Discovery.
    -------------------------- EXAMPLE 4 --------------------------

    C:\PS>Get-ADDomainController -Discover -Service 2

    Description

    -----------

    Get a global catalog in the current forest using Discovery.
```

**Comment by Malind19** [comment]
@e0i , Created PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1024

**Comment by e0i** [comment]
@iricigor 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
