### ISSUE TITLE
Office LDAP display name incorrect

### ISSUE THREAD

**Issue by jeffreymcclain** [MicrosoftDocs/windows-powershell-docs#547]
The documentation states "this property is office" when it's actually "physicalDeliveryOfficeName".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30217138-eb8c-ab9a-4e11-991c6164cbd9
* Version Independent ID: 88ff510e-6402-5163-404f-e9154f59b381
* Content: [Set-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/set-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-aduser.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Malind19** [comment]
@e0i Created PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1025

**Comment by e0i** [comment]
@jeffreymcclain 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
