### ISSUE TITLE
Size of Cluster Log

### ISSUE THREAD

**Issue by yupsay** [MicrosoftDocs/windows-powershell-docs#549]
Starting Windows 2019 this can go up to 2048 MB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eadb86d1-35c4-450b-cbd5-53d74502cc1d
* Version Independent ID: 59186918-a2ce-5a0e-7f42-f5953c7eebd3
* Content: [Set-ClusterLog (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterlog?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/set-clusterlog.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/set-clusterlog.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @yupsay 

In our investigation we have found that the article might not need to be updated.

As expressed in the section title, the article applies to _Windows 10_ and _Windows Server 2016_, and it is not known yet whether a _Windows Server 2019_ section will be added.

We are closing this issue but feel free to re-open and comment anything we might have missed.

Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
