### ISSUE TITLE
Mandatory params defined in NetworkControllerAdapter not shown for get cmdlet

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/windows-powershell-docs#55]
_From @SteveL-MSFT on August 12, 2016 18:27_

Repro steps:

> help new-NetworkControllerState

NAME
    Get-NetworkControllerState
SYNTAX
    Get-NetworkControllerState [-ConnectionUri <uri>] [-CertificateThumbprint <string>] [-Credential <pscredential>]
    [-PassInnerException]  [<CommonParameters>]

Mandatory parameter defined in NetworkControllerAdapter.cs ConnectionUri is shows as optional in ps.

_Copied from original issue: PowerShell/PowerShell#1754_

**Comment by joeyaiello** [comment]
_From @SteveL-MSFT on September 29, 2016 20:14_

TFS:8384570

**Comment by joeyaiello** [comment]
Moved this one over from our repo. Looks like `-ConnectionUri` isn't supposed to optional (though I don't have a Server '16 box handy to check, sorry). 

Best way to verify truth vs. the help is to use `Get-Command -Syntax Get-NetworkControllerState` and see if the square brackets are there or not (if they're there, it's really optional).

**Comment by brianlic-msft** [comment]
@anirbanpaul Can you help with this one?

**Comment by AnirbanPaul** [comment]
I have updated the cmdlet. This should be a mandatory parameter
