### ISSUE TITLE
SslFlags is confusing

### ISSUE THREAD

**Issue by MikeChristensen** [MicrosoftDocs/windows-powershell-docs#550]
What is the difference between the regular certificate in Windows storage and a "central certificate store"?  Where exactly would I use different values of SslFlags?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd15223d-e472-cbe7-15d6-dbbd4a373351
* Version Independent ID: 87dd59f6-b943-fc82-9b39-d79c2f487dd1
* Content: [New-WebBinding (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-webbinding?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/New-WebBinding.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@MikeChristensen 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by velkovb** [comment]
@MikeChristensen Hi Mike,  Thanks for reaching out and helping improve MS Docs. Please let me know if this article helps - https://docs.microsoft.com/iis/configuration/system.applicationhost/sites/site/bindings/binding#configuration

**Comment by MikeChristensen** [comment]
Yup, perfect!

**Comment by e0i** [comment]
@MikeChristensen 

We are closing this issue since your question seems to be answered.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
