### ISSUE TITLE
Credentials variable error

### ISSUE THREAD

**Issue by ChrisParrBIE** [MicrosoftDocs/windows-powershell-docs#551]
Something strange is happening when I try and reuse a Credential variable against this cmdlet.

$Cred = Get-Credential
$Name = "server01"
Get-WindowsFeature -ComputerName $Name -Credential $Cred #Command 1
Get-winEvent -ComputerName $Name -Credential $Cred -MaxEvents 1 -LogName application #Command 2
Get-WindowsFeature -ComputerName $Name -Credential $Cred #Command 3
Get-winEvent -ComputerName $Name -Credential $Cred -MaxEvents 1 -LogName application #Command 4

Commands 1, 2, and 4 work as expected. Command 3 fails with this error:

Get-WindowsFeature : The WinRM client cannot process the request. Requests must include user name and password when Basic or Digest authentication mechanism is used. Add the
user name and password or change the authentication mechanism and try the request again.
At line:1 char:1
+ Get-WindowsFeature -ComputerName $Name -Credential $Cred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsFeature], CimException
    + FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,Microsoft.Windows.ServerManager.Commands.GetWindowsFeatureCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b3d536-027d-e21d-f160-42c2c2d02191
* Version Independent ID: 1408677c-e0ff-aaad-f84e-d97351461a62
* Content: [Get-WindowsFeature (servermanager)](https://docs.microsoft.com/en-us/powershell/module/servermanager/get-windowsfeature?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
Hello, @ChrisParrBIE thank you for providing feedback.

Note that the issue tracker of this repository is intended for product documentation issues only.

Please consider opening a support ticket for product issues and bugs via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You can also check relevant resources and ask the community regarding your problem via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
