### ISSUE TITLE
Example 2 is meaningless

### ISSUE THREAD

**Issue by AndyChips** [MicrosoftDocs/windows-powershell-docs#552]
As of writing, Example 2 is meaningless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8acb1a7-ec07-4b38-d5f7-d9e41cf04528
* Version Independent ID: f0399407-f57e-edee-1411-96e9f25cb826
* Content: [Get-RemoteAccessConnectionStatistics (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/get-remoteaccessconnectionstatistics?view=win10-ps)
* Content Source: [docset/windows/remoteaccess/get-remoteaccessconnectionstatistics.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remoteaccess/get-remoteaccessconnectionstatistics.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@AndyChips 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
