### ISSUE TITLE
Documentation Error?

### ISSUE THREAD

**Issue by GlennJC** [MicrosoftDocs/windows-powershell-docs#553]
1. The Notes has a duplicated line:
"This cmdlet does not work with a read-only domain controller."

2. Example 2 refers to moving RODC servers to a specific site. Given the advice in the notes, is that a valid example? Or does this example need to be executed from a non-RODC server in order to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a53d11b-c3fe-4f51-b4d1-d8122edeb5e2
* Version Independent ID: 4a47188e-745f-b37c-b393-59c2e41ea7b0
* Content: [Move-ADDirectoryServer (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/move-addirectoryserver?view=win10-ps)
* Content Source: [docset/windows/addsadministration/move-addirectoryserver.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/move-addirectoryserver.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by joinimran** [comment]
@GlennJC Thank you for your feedback and help to make docs better. The duplicate line has been removed. And to answer your 2nd question, you need to run the command from Non-RODC server.

**Comment by e0i** [comment]
@kenwith A PR #926 available for this issue. Please review. Thanks.

**Comment by e0i** [comment]
@GlennJC  Upon your feedback, We have updated the content with relevant changes accordingly. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
