### ISSUE TITLE
Inconsistent values specified for -ReplicationMode

### ISSUE THREAD

**Issue by GitHubBJW** [MicrosoftDocs/windows-powershell-docs#554]
The text for -ReplicationMode reads:
Specifies the replication mode of the virtual machines whose replication statistics you want to get. Valid values are "None", "Primary", "Replica" and "TestReplica".

But just below that in the section "Accepted values:" is found:
None, Primary, Replica, TestReplica, ExtendedReplica

Notice the 'ExtendedReplica' value is listed in Accepted Values, but not in the introductory text

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf7b380-389e-f0f9-9ff2-906501abc18f
* Version Independent ID: 9ff08da6-5b0b-1a60-1258-e90a80998af3
* Content: [Measure-VMReplication (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/measure-vmreplication?view=win10-ps)
* Content Source: [docset/windows/hyper-v/measure-vmreplication.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/measure-vmreplication.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@GitHubBJW 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
