### ISSUE TITLE
-DestinationPath is optional

### ISSUE THREAD

**Issue by BlackV** [MicrosoftDocs/windows-powershell-docs#555]
It is not mentioned what happens if it is not speficied.
Does it automatically use the parent path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4131d8dd-33e8-0f5b-898f-0a0d65ddeba9
* Version Independent ID: 05fc922a-bde2-93ff-7515-c2f14d820fad
* Content: [Merge-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/merge-vhd?view=win10-ps)
* Content Source: [docset/windows/hyper-v/merge-vhd.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/merge-vhd.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by sowjanya365** [comment]
Hi @BlackV 

Thanks for reaching out!

Yes, the -DestinationPath parameter is optional. If we don't mention it in the command, it transfer the contents of the differencing disk into its parent. The differencing disk is destroyed at the end of this operation. 

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by e0i** [comment]
Hello @BlackV ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
