### ISSUE TITLE
New-NetFirewallRule - add option to skip dropped packets logging

### ISSUE THREAD

**Issue by UnityUser** [MicrosoftDocs/windows-powershell-docs#556]
I could not find Windows Firewall page on MicrosoftDocs, so I ask here.
I have created the rule:
`New-NetFirewallRule -DisplayName 'Explorer' -Description 'C:\Windows\explorer.exe' -Program 'C:\Windows\explorer.exe' -Direction Outbound -Group "USER" -Protocol TCP -RemotePort '443' -Action Block`
So now I ALWAYS see events about blocked connections.
I don't need to know anything about it.
The same with 
"\device\harddiskvolume4\program files\parallels\client\tsclient.exe".
I could not find a key (parameter) to force skip logging of the dropped packets for a program.

**Comment by e0i** [comment]
@UnityUser

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
