### ISSUE TITLE
Credentials switch doesn't accept empty credentials objects

### ISSUE THREAD

**Issue by ChrisParrBIE** [MicrosoftDocs/windows-powershell-docs#557]
Unlike most Cmdlets that take a credentials parameter, get-windowsfeatures doesn't accept empty credentials variables.
So calling get-windowsfeatures from within a function that takes a credentials variable defined as follows throws an error if no credentials are supplied to the calling function.
        [ValidateNotNull()]
        [System.Management.Automation.PSCredential]
        [System.Management.Automation.Credential()]
        $Credential = [System.Management.Automation.PSCredential]::Empty

Calling Get-WinEvents, Get-WmiObject etc with an empty credentials value works normally, but get-windowsfeature fails with "Get-WindowsFeature : Object reference not set to an instance of an object."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b3d536-027d-e21d-f160-42c2c2d02191
* Version Independent ID: 1408677c-e0ff-aaad-f84e-d97351461a62
* Content: [Get-WindowsFeature (servermanager)](https://docs.microsoft.com/en-us/powershell/module/servermanager/get-windowsfeature?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/servermanager/Get-WindowsFeature.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@ChrisParrBIE

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
