### ISSUE TITLE
Set-Culture does not work in ScriptBlock

### ISSUE THREAD

**Issue by quickware** [MicrosoftDocs/windows-powershell-docs#558]
$server = "server1.xyz.com"
Invoke-Command -ComputerName $server -ScriptBlock{
            #Requires -RunAsAdministrator
            Set-Culture -CultureInfo en-GB;           
            Set-TimeZone -id "GMT Standard Time"
            Get-UICulture                 
            Get-Culture           
}

Event though it is working when run directly on the server, Set-Culture does not work on the remote server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c3d9f2e-a037-cd47-8c16-1ac463bea7a7
* Version Independent ID: df4184ad-7066-084b-da1b-2ecf46803043
* Content: [Set-Culture (international)](https://docs.microsoft.com/en-us/powershell/module/international/set-culture?view=win10-ps)
* Content Source: [docset/windows/international/set-culture.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/international/set-culture.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @quickware 
Thanks for your feedback.
I tested and could verify what you experienced. Also I assume you are taking into account [this](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/33983191-powershell-sessions-don-t-support-mixed-culture-va)

Although, this issue resource system is specifically to address issues in documentation, so I encourage you to please visit this resource for further help:
https://support.microsoft.com

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @quickware 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
