### ISSUE TITLE
16 bit apps, and OS/2

### ISSUE THREAD

**Issue by Brain2000** [MicrosoftDocs/windows-powershell-docs#559]
So, what you're telling me is, I can use the Task Scheduler to run my old 16 bit apps that I can no longer run in a 64 bit operating system!?  This is fantastic!  Have you let the other developers know this exists yet?

Oh, and OS/2!  Where's my old floppy disks, I can run them again.  Oh, where have you been all my life!?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac89430-e60f-5988-11f4-172793fb8883
* Version Independent ID: 4e093fe1-bdec-0e8f-2d35-ef44181f617d
* Content: [Register-ScheduledTask (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/register-scheduledtask?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/register-scheduledtask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/register-scheduledtask.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Amaroq-Clearwater** [comment]
I'm not sure that's what they meant. Remember, this documentation is also for Windows 10, which has a 32-bit version. On 64-bit installations of Windows, the emulators for MS-DOS applications, 16-bit Windows applications and OS/2 applications have never been implemented. In fact, the OS/2 subsystem was actually removed in a previous version of Windows NT.

I'm really sorry to be the bringer of bad news.

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit
