### ISSUE TITLE
the get-dhcpserverv4reservation command returns the reservation when query the specific client ID when the ID is only leased not reserved

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/windows-powershell-docs#56]
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dhcpserver/get-dhcpserverv4reservation.md

when use 
`Get-DhcpServerv4Reservation -ScopeId  $ScopeId -ComputerName $DHCPServer -ClientId $ClientId`
it returns the leased (not reserved) client IP if the ClientID exists and is active in the given scope 
There is a workaround = collect all reservations for the given scope and search in the result against ClientID

**Comment by coreyp-at-msft** [comment]
Hi @Michal-Ziemba , if this is returning leases and not reservations, it is a bug, since Get-DHCPServerv4Lease returns leases. I've assigned it to Networking for investigation.

**Comment by JesseHermes** [comment]
I also see this behavior on a Server 2012 R2 DHCP server failover cluster.   Passing the client ID of a client which has an active lease but not a reservation returns the lease instead of Not Found.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Michal-Ziemba 
Thanks for this feedback!
I would have to kindly suggest to visit Support resources http://support.microsoft.com or User Voice https://windowsserver.uservoice.com/forums/295047-general-feedback to redirect this inquiry that looks like a bug in the cmdlet.
Thank you

**Comment by Michal-Ziemba** [comment]
@get-itips is it a way we should report bugs about commands?

**Comment by yogkumgit** [comment]
@Michal-Ziemba . Yes. This this channel is only for the documentation update.
@get-itips  Thank you very much for the contribution and sharing this explanation. @Michal-Ziemba 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
