### ISSUE TITLE
Parameter documentation issues

### ISSUE THREAD

**Issue by logmod** [MicrosoftDocs/windows-powershell-docs#560]
1) Set-VMNetworkAdapterVlan can also be used to configure managementOS interfaces. This is not explained further in the documentation and there are also no examples. VLANs for the management OS are configured for a virtual switch denoted by "VMNetworkAdapterName". However this parameter is documented as "Specifies the name of the virtual machine network adapter". This seems to be a copy paste error from "VMNetworkAdapter" that describes the virtual NIC name. A virtual switch is not the same as a virtual adapter.

2) Parameter -VMName is used in all examples. It is unclear what -VM of type virtualmachine[] does.

3) In general the documentation should be improved to explain what parameters actually do instead of just repeating the parameter name in the explanation. Examples for explanations that would make more sense are: 
-Access configures an untagged virtual port for the VLANId (port based VLAN),
-Trunk configures a tagged virtual port that passes all allowed VLANId tags to the VM adapter, traffic with the NativeVLANId is passed untagged to the VM adapter,
- etc. 
Not everybody uses Cisco switches or can assume that MS parameters have the same effect as Cisco parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34c3056-8695-b58a-8923-58e0cd021797
* Version Independent ID: 2d7487a1-a8af-aaad-3232-21c5338af554
* Content: [Set-VMNetworkAdapterVlan (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmnetworkadaptervlan?view=win10-ps)
* Content Source: [docset/windows/hyper-v/set-vmnetworkadaptervlan.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/set-vmnetworkadaptervlan.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dariomws306** [comment]
Hi @logmod, thank you for your feedback.

It's true that virtual switch is not the same as a virtual adapter, but you see virtual switchs in your Hyper-V host (management OS) as Network Adapter.

I don't have more information about -VM parameter.

I have added more detail to -Access and -Trunk.

@coreyp-at-msft, could you help here with more information/detail? Thanks.

**Comment by yturbi** [comment]
It's "funny", but NativeVLANId options doesn't means "traffic with the NativeVLANId is passed untagged to the VM adapter" as Martin suggest. In Hyper-V virtual switch NativeVLANId option it is VLAN Id that is used to tag (!!!) untagged traffic received on this trunk endpoint/port. So if you want untagget traffic pass thru virtual switch from VM to phisycal switch you have to add native VLAN (802.1Q) in AllowedVLANidList option and set NativeVLANId to 0. That so confused!
