### ISSUE TITLE
Wrong command

### ISSUE THREAD

**Issue by grimson73** [MicrosoftDocs/windows-powershell-docs#562]
Example 1: Disable automatic claim for iSCSI
PS C:\&gt; Disable-MSDSMAutomaticClaimSettings -BusType "iSCSI"
should be Disable-MSDSMAutomaticClaim -BusType "iSCSI"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd658bd-0287-9aac-1095-7be8810ddf99
* Version Independent ID: 50ba1ad1-de2b-bb8d-06b3-593ae438d347
* Content: [Disable-MSDSMAutomaticClaim (mpio)](https://docs.microsoft.com/en-us/powershell/module/mpio/disable-msdsmautomaticclaim?view=win10-ps)
* Content Source: [docset/windows/mpio/disable-msdsmautomaticclaim.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/mpio/disable-msdsmautomaticclaim.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by msbemba** [comment]
@grimson73  Thank you for the feedback. We have made the necessary changes to the cmdlet in the example on PR# https://github.com/MicrosoftDocs/windows-powershell-docs/pull/733 .

**Comment by e0i** [comment]
@coreyp-at-msft There is a proposed Pull Request regarding the issue. Please review. Thanks. #733

**Comment by e0i** [comment]
@kenwith There is a proposed Pull Request regarding the issue. Please review. Thanks. #733

**Comment by e0i** [comment]
@officedocsbot close
