### ISSUE TITLE
Doesn't work in Win10?

### ISSUE THREAD

**Issue by silversword411** [MicrosoftDocs/windows-powershell-docs#563]
Doesn't seem to give any data in Win10, was this removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6566d5bd-df6f-e4dc-3075-ad47cc1fa1d5
* Version Independent ID: 33407294-d33e-887a-9265-a91a753f2dee
* Content: [Get-StorageReliabilityCounter (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-storagereliabilitycounter?view=win10-ps)
* Content Source: [docset/windows/storage/get-storagereliabilitycounter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-storagereliabilitycounter.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @silversword411 
Thanks for your feedback.
If you refer to this:

```
DeviceId Temperature ReadErrorsUncorrected Wear PowerOnHours
-------- ----------- --------------------- ---- ------------
0                                          0
```

Actually, if you run the example as in the documentation, it will only list by default those attributes, but if you add a | Format-List it will list all possible attributes, and some of them, with data. So I'll create a Pull Request to improve the example.
Please take note that, for some attributes to have data, it depends on the features provided by the storage hardware.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @silversword411 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
