### ISSUE TITLE
Export ALL GPOs to a folder

### ISSUE THREAD

**Issue by Big2thaE** [MicrosoftDocs/windows-powershell-docs#564]
In order to export ALL of the GPOs, I open a PS ISE and run the following: 
CD C:\Temp
Get-GPO -All |? { $_.gpostatus -match 'enabled'}| % {$_.GenerateReport('html') | Out-File "$($_.DisplayName).htm"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03772765-030f-44fe-fd3f-97eaf2fd09f7
* Version Independent ID: 8aa369fb-436b-a38f-c4a7-cb420ec58d0a
* Content: [Get-GPOReport (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/get-gporeport?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/get-gporeport.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/get-gporeport.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by aheusdens** [comment]
I'm noticing the report does not includes all values for the every GPO. Specifically ran across this when working with Software Restriction policies. The text description for these policies are not included in the report ,only their setting values.

**Comment by e0i** [comment]
@Big2thaE Thank you for providing feedback.

Would you clarify the subject of your request? 

If you would like to provide specific feedback for the documentation content, we would like to learn more about your suggestions and follow-up.

Note that if you are experiencing problems with PowerShell or have specific questions to ask about a difficulty you are experiencing, please seek advice via PowerShell Community via the link here:  [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@Big2thaE 

We are closing this issue since we couldn't get a response. Feel free to re-open this issue with more  more details and we will follow-up accordingly.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
