### ISSUE TITLE
Example seems to miss a named parameter

### ISSUE THREAD

**Issue by 3ter** [MicrosoftDocs/windows-powershell-docs#566]
Running the example 
Set-NpsRadiusClient -Name "WirelessAP" -Address "10.0.0.201" $False -SharedSecret "1234567890"
gives me an error, presumably because -Enabled is missing in front of the Boolean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb23b7dc-17aa-fa0c-d7a8-ebd3dc831821
* Version Independent ID: 19a7def1-340b-153b-486b-36d020b31807
* Content: [Set-NpsRadiusClient (nps)](https://docs.microsoft.com/en-us/powershell/module/nps/set-npsradiusclient?view=win10-ps)
* Content Source: [docset/windows/nps/set-npsradiusclient.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nps/set-npsradiusclient.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @3ter  thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@officedocsbot open

**Comment by e0i** [comment]
@officedocsbot reopen

**Comment by joinimran** [comment]
@3ter Thank you for sharing your feedback. Can you please format the whole command that works for you so that we can further look in this issue.

**Comment by 3ter** [comment]
```Powershell
Set-NpsRadiusClient -Name "WirelessAP" -Address "10.0.0.201" -Enabled $False -SharedSecret "1234567890"
```

**Comment by e0i** [comment]
@3ter  With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
