### ISSUE TITLE
Not all values for all GPOs are included in the report

### ISSUE THREAD

**Issue by aheusdens** [MicrosoftDocs/windows-powershell-docs#568]
I'm noticing the XML report does not include all values for the every GPO. Specifically ran across this when working with Software Restriction policies. The text description for these policies are not included in the report ,only their setting values under Report.GPO.Computer.ExtensionData.Extension.General

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03772765-030f-44fe-fd3f-97eaf2fd09f7
* Version Independent ID: 8aa369fb-436b-a38f-c4a7-cb420ec58d0a
* Content: [Get-GPOReport (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/get-gporeport?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/get-gporeport.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/get-gporeport.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @aheusdens thank you for providing feedback.

Note that the issue tracker of this repository is intended for product documentation issues only.

Please consider opening a support ticket for product issues and bugs via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You can also check relevant resources and ask the community regarding your problem via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
