### ISSUE TITLE
AuthenticationType value is case sensitive!

### ISSUE THREAD

**Issue by jwhelms** [MicrosoftDocs/windows-powershell-docs#569]
Just about beat my head against a wall trying to set up two-way CHAP when I came across a wordpress site stating that the authenticationtype is case sensitive and must be ALL CAPS (MUTUALCHAP).  And NO, it will not work with MutualCHAP as listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3bc9f58-cca2-c3a4-d135-f742d46e2558
* Version Independent ID: c5739614-a93d-8c5a-b19c-7c378094e40a
* Content: [New-IscsiTargetPortal (iscsi)](https://docs.microsoft.com/en-us/powershell/module/iscsi/new-iscsitargetportal?view=win10-ps)
* Content Source: [docset/windows/iscsi/new-iscsitargetportal.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/iscsi/new-iscsitargetportal.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@jwhelms 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@jwhelms 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
