### ISSUE TITLE
Broken help URI for Import-PfxCertificate

### ISSUE THREAD

**Issue by AndreHimself** [MicrosoftDocs/windows-powershell-docs#571]
Currrent help URI (https://go.microsoft.com/fwlink/?LinkId=386826) for Import-PfxCertificate redirects to page below, which lands in a page not found.

Current unwrapped URI: https://docs.microsoft.com/en-us/powershell/module/pki/import-pfxcertificate

Also, it would be great if this documentation had possible errors this cmdlet may throw.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f36c4f79-411b-f859-7488-456b65e61e73
* Version Independent ID: 9a5652dd-c33c-a658-9ee1-3af47189136a
* Content: [Import-PfxCertificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-pfxcertificate?view=win10-ps#feedback)
* Content Source: [docset/windows/pkiclient/import-pfxcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/import-pfxcertificate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by sowjanya365** [comment]
Hello @AndreHimself 

Thank you for your feedback and patience. 
 
For "Import-PfxCertificat" could you please refer to the following URL? Let us know if you find any issues in accessing this link. 

https://docs.microsoft.com/powershell/module/pkiclient/import-pfxcertificate 

Thank you so much for your contribution and we appreciate it.
