### ISSUE TITLE
Is there a Get-Deployment or similar?

### ISSUE THREAD

**Issue by thetrav** [MicrosoftDocs/windows-powershell-docs#572]
Apart from installing windows features, what does this cmdlet actually do?  

If it outputs null how do I check whether it was successful?
If I run it multiple times is it idempotent?
Are there alternative cmdlets for achieving the same result?

When I executed it on my windows 2016 server it appeared to succeed, however the deployment was not visible via the "server manager" GUI, I was only able to manage it via powershell after that invocation.  

Is there another cmdlet to enable the server manager GUI, or is there something missing from this one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4fdc2e-72df-d7ba-68e3-df6bb25ae8ad
* Version Independent ID: 054c9e86-0b4b-d06b-8a56-bad322c2788f
* Content: [New-RDSessionDeployment (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/New-RDSessionDeployment?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/new-rdsessiondeployment.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/new-rdsessiondeployment.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @thetrav thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
