### ISSUE TITLE
why no documentation of the properties of this method?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-powershell-docs#573]
At least state that the type name is...

Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/Defender/MSFT_MpComputerStatus

...and this is documented at

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/defender/msft-mpcomputerstatus

I'm looking for what "ComputerState" property means; it should be explained here; if not, it should link as above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8412d990-8ebe-45fe-9e5e-0c573e88226d
* Version Independent ID: 192ecac7-fbc7-24e4-43c7-163550e211fa
* Content: [Get-MpComputerStatus (defender)](https://docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus?view=win10-ps)
* Content Source: [docset/windows/defender/get-mpcomputerstatus.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/get-mpcomputerstatus.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by msbemba** [comment]
@anwarmahmood1 Thank you for your Feedback. We have added the link to properties in this doc via PR# https://github.com/MicrosoftDocs/windows-powershell-docs/pull/736

**Comment by e0i** [comment]
@coreyp-at-msft There is a proposed Pull Request regarding the issue. Please review. Thanks. #736

**Comment by e0i** [comment]
@kenwith  There is a proposed Pull Request regarding the issue. Please review. Thanks. #736

**Comment by e0i** [comment]
@officedocsbot close

**Comment by yerttle** [comment]
Hi guys, I appreciate this issue is closed so feel free to direct me to create a new ticket.

However I am inttrested in creating an app that will report one the Windows Defender status and having a break down of the different computer state intigers would be very helpful. I appreciate the addtion of a link to the properties however there is no more detail for the computer state property.

![image](https://user-images.githubusercontent.com/30318189/60080755-6de94180-9728-11e9-8d53-92b53f81717f.png)

**Comment by megamih** [comment]
Hi @anwarmahmood1 and @yerttle ,
Hope [this](https://systemcenter.wiki/?GetElement=Microsoft.WindowsDefender.ProtectedServer.MalwareActivity.GetInfectionStatusWmiProbeType&Type=ProbeActionModuleType&ManagementPack=Microsoft.WindowsDefender&Version=7.1.10128.1) can shed some light:

```
                #typedef enum tagAMCOMPUTER_STATE
                #        {
                #            CLEAN                    = 0,
                #            PENDING_FULL_SCAN        = 1,
                #            PENDING_REBOOT           = 2,
                #            PENDING_MANUAL_STEPS     = 4,
                #            PENDING_OFFLINE_SCAN     = 8,
                #            PENDING_CRITICAL_FAILURE = 16
                #        }
```
