### ISSUE TITLE
Invoking New-RDSessionDeployment on the target machine via WinRM fails

### ISSUE THREAD

**Issue by thetrav** [MicrosoftDocs/windows-powershell-docs#574]
If I attempt to invoke this Cmdlet via a WinRM connection it fails with this error:
```
New-RDSessionDeployment : Validation failed for the "RD Connection Broker" parameter. &lt;SERVER URL&gt; _x0009_ Unable to connect to the server by using Windows PowerShell remoting. Verify that you can connect to the server.
```

If you search for that error message there are numerous examples of this issue striking, it appears to be related to the Cmdlet being unhappy "remoting" to the server it's already on.

Is this an intended/known constraint?  Are there any switches that can be applied to modify the remoting option used?  Or even to get a more verbose output so I can see what specifically is failing in the connection

The WinRM connection I'm using is secured by TLS, so it's possible that the Cmdlet attempts to remote over a non secured channel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4fdc2e-72df-d7ba-68e3-df6bb25ae8ad
* Version Independent ID: 054c9e86-0b4b-d06b-8a56-bad322c2788f
* Content: [New-RDSessionDeployment (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/new-rdsessiondeployment?view=win10-ps)
* Content Source: [docset/windows/remotedesktop/new-rdsessiondeployment.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/new-rdsessiondeployment.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @thetrav  thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
