### ISSUE TITLE
Windows 10 and RSAT

### ISSUE THREAD

**Issue by MarkusRich** [MicrosoftDocs/windows-powershell-docs#575]
As it get more and more complicated to install the powershell modules for ActiveDirectory on windows 10 is there a replacement available which makes it easier or out of the box possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ccc946-9393-581d-8ca2-e32d4c8ce99c
* Version Independent ID: 50982f9a-ac84-9554-3fe5-414e60368b92
* Content: [Set-ADAccountPassword (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-adaccountpassword?view=win10-ps)
* Content Source: [docset/windows/addsadministration/set-adaccountpassword.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-adaccountpassword.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @MarkusRich thanks for your feedback.
As this issue resource is intended to address issues present specifically in documentation, I need to kindly redirect you to https://support.microsoft.com/en-us to get support on your case.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @MarkusRich 
Hope this comment is helpful for you. Considering the nature of the issue, as advised , please open a service ticket in your tenant and follow with them for the resolution.

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
