### ISSUE TITLE
set-nettcpsetting allows changing non custom settings

### ISSUE THREAD

**Issue by rnitsch70** [MicrosoftDocs/windows-powershell-docs#576]
powershell/module/nettcpip/set-nettcpsetting

It should be mentioned that on client OS the settings can't be modified as they are read-only.

Since Windows Server 2016 you can also configure the non-custom settings (Internet and Datacenter). Previously only the custom settings could be changed.
This statement is wrong in the article is wrong:
You can only modify the Custom TCP setting.

Also the sample is wrong - there is no SettingName 'Custom'. 
Set-NetTCPSetting -SettingName "Custom" -CongestionProvider CTCP -InitialCongestionWindowMss 6

**Comment by rnitsch70** [comment]
Hi
https://docs.microsoft.com/en-us/powershell/module/nettcpip/set-nettcpsetting?view=win10-ps
This is the documentation for set-nettcpsetting on MSDN

**Comment by msbemba** [comment]
@rnitsch70  Thank you for the feedback. We have created a PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/757

**Comment by e0i** [comment]
@officedocsbot close
