### ISSUE TITLE
can't download MDOP with powershell

### ISSUE THREAD

**Issue by balaban** [MicrosoftDocs/windows-powershell-docs#577]
Hello guys, we have all subscriptions to Microsoft but I still can't figure out on how to download MDOP with powershell for automation, any help would be appreciated! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8c568e-c769-7534-f56c-98a1e8d77a2f
* Version Independent ID: 95937601-fdb4-ea5f-a50f-9decc46a68cb
* Content: [Microsoft Desktop Optimization Pack Automation with Windows PowerShell](https://docs.microsoft.com/en-us/powershell/mdop/get-started?view=win-mdop2-ps)
* Content Source: [docset/docs-conceptual/mdop/get-started.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/docs-conceptual/mdop/get-started.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @balaban thanks for your feedback, based on your inquiry, and as this issue resource is intended to address issues in documentation, I need to kindly suggest you to visit https://support.microsoft.com/en-us to get support on your case.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @balaban
Hope this comment is helpful for you. Considering the nature of the issue, as advised , please open a service ticket in your tenant and follow with them for the resolution.
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
