### ISSUE TITLE
Possible typo in -Cluster explanation

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windows-powershell-docs#580]
Is there a reason why the description refers to SQL Server? More specifically, that it's SQL Server's "default port" is 3343?

I'm pretty sure that's Cluster's default port, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4bb7cf2-5414-66e5-9a92-254d72a222ba
* Version Independent ID: fd6ec687-d40a-8534-0d33-a4d5cd498d5a
* Content: [New-NetQosPolicy (netqos)](https://docs.microsoft.com/en-us/powershell/module/netqos/new-netqospolicy?view=win10-ps)
* Content Source: [docset/windows/netqos/new-netqospolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netqos/new-netqospolicy.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@coreyp-at-msft PR available for the issue: #727

**Comment by e0i** [comment]
@kenwith PR available for the issue: #727

**Comment by e0i** [comment]
@officedocsbot close
