### ISSUE TITLE
Typo in this page, look for rrsandf_plural in the Description section

### ISSUE THREAD

**Issue by craig-martin** [MicrosoftDocs/windows-powershell-docs#581]
Obvious typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d05b2e2-d244-3807-ef9a-c88b0e7a207a
* Version Independent ID: 5e7493c1-7e9e-1a48-4318-7059eb1d3e26
* Content: [Install-WindowsFeature (servermanager)](https://docs.microsoft.com/en-us/powershell/module/servermanager/install-windowsfeature?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/servermanager/Install-WindowsFeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/servermanager/Install-WindowsFeature.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@brianlic-msft A PR is available for this issue. Please review.

**Comment by craig-martin** [comment]
this part does not look fixed yet:
```
â—? "UserName"
â—? "Domain\User"
â—? "User@Domain.com"
â—? A Credential object returned by the Get-Credentialhttp://go.microsoft.com/fwlink/p/?LinkID=113311 cmdlet.
```

**Comment by e0i** [comment]
@brianlic-msft A full PR is available for review for this issue. #734

**Comment by e0i** [comment]
@kenwith A full PR is available for review for this issue. #734

**Comment by e0i** [comment]
@AndreaBarr The PR has been merged. The issue can be closed.
