### ISSUE TITLE
Example 5 -Action AllowBypass Incorrect Value

### ISSUE THREAD

**Issue by My-Random-Thoughts** [MicrosoftDocs/windows-powershell-docs#583]
The `-Action` parameter only accepts `Allow`, `Deny`, or `NotConfigured`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a81ceb77-8de5-8c07-c0c4-fa3d616d859f
* Version Independent ID: 736dd392-788a-c102-dfcb-29a08c2c9f9d
* Content: [New-NetFirewallRule (netsecurity)](https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps)
* Content Source: [docset/windows/netsecurity/new-netfirewallrule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netsecurity/new-netfirewallrule.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by msbemba** [comment]
@My-Random-Thoughts Thank you for the Feedback. We have raised a PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/732 to make necessary changes in Example 5.

**Comment by e0i** [comment]
@coreyp-at-msft There's a new PR available for this issue #732

**Comment by e0i** [comment]
@kenwith There's a new PR available for this issue #732

**Comment by e0i** [comment]
@officedocsbot close
