### ISSUE TITLE
Please add this note to the -AllUsers parameter

### ISSUE THREAD

**Issue by indyjason79** [MicrosoftDocs/windows-powershell-docs#584]
You must have v1709 (Fall Creator's Update) to use the "-AllUsers" flag

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f43873-0e34-6ec2-8bde-479945d49ed9
* Version Independent ID: 914c97a9-7dc2-6ddd-4756-7ec210db3fe8
* Content: [Remove-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/remove-appxpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/remove-appxpackage.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@kenwith There is a new PR (#740) available for this issue for review. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
