### ISSUE TITLE
Winthreshold Parameter not explained.

### ISSUE THREAD

**Issue by Rookerith** [MicrosoftDocs/windows-powershell-docs#60]
In the AD DS module, many of the Cmdlets have parameters such as DomainMode and ForestMode that have a possible value of "winthreshold" and "Default".  I think it would be useful if you explain the expected behavior of those.  I'm not 100% positive winthreshold will default it to Server2016, and it doesn't look like that is a parameter that is explicitly possible to pick, as the highest available server value according to the documentation is 6 or "Win2012R2".

**Comment by brianlic-msft** [comment]
@billmath Can you take a look?

**Comment by brianlic-msft** [comment]
@Rookerith the install-addsforest cmdlet was just updated.  Thanks!
