### ISSUE TITLE
Powershell documentation on the TECHNET/Windows IT CENTER is completely flawed

### ISSUE THREAD

**Issue by whytoe** [MicrosoftDocs/windows-powershell-docs#62]
Multiple features are broken and this severely limits usability and general faith in Microsoft as a company.

- Hyper V cmdlets for Windows 2012R2 have been reference has been removed
- Links to the appropriate resources redirect to Server 2016 and Windows 10
- no drops downs to display dependencies on a cmdlet level

**Comment by brianlic-msft** [comment]
@whytoe Thank you for the feedback.  The Windows Server 2012 R2 cmdlets are still available on TechNet [here](https://technet.microsoft.com/en-us/library/dn249523.aspx).  The Windows Server 2016 and Windows 10 resources should redirect under [here](https://technet.microsoft.com/itpro/powershell/windows/index).  We'd like to bring drop downs back but we don't have a ETA on when this will happen yet.
