### ISSUE TITLE
Mistake in Add-NetEventPacketCaptureProvider and Set-NetEventPacketCaptureProvider documentation

### ISSUE THREAD

**Issue by pportnoy** [MicrosoftDocs/windows-powershell-docs#64]
Documentation:

- https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/neteventpacketcapture/add-neteventpacketcaptureprovider.md

- https://technet.microsoft.com/en-us/itpro/powershell/windows/neteventpacketcapture/set-neteventpacketcaptureprovider

The `CaptureType` parameter documentation specifies accepted values that are different from the `AcceptedValues` in the code example. It also means that the documentation for different values is not provided.

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @pportnoy Thanks for your feedback and noting this.
I created a pull request to correct the article.
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR #1114 and kindly provide your feedback

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @pportnoy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
