### ISSUE TITLE
Spelling Error in New-SelfSignedCertificate -KeyUsage parameter help / documentation

### ISSUE THREAD

**Issue by GitHubBJW** [MicrosoftDocs/windows-powershell-docs#65]
Get-Help New-SelfSignedCertificate -Full shows the -KeyUsage parameter as "DigitalSiganture" instead of the intended "DigitalSignature".
This error is online and in the offline help in the PowerShell console as well.  It persists even after an Update-Help -Module PKI

![image](https://user-images.githubusercontent.com/15986948/27102737-f6d0b71a-504b-11e7-9f6a-d66eeb486de0.png)

**Comment by brianlic-msft** [comment]
@GitHubBJW Thanks for catching this!  I've fixed it in the source so it'll be updated on TechNet shortly.
