### ISSUE TITLE
New-SelfSignedCertificate always includes "Key Usage"

### ISSUE THREAD

**Issue by GitHubBJW** [MicrosoftDocs/windows-powershell-docs#66]
The -KeyUsage parameter indicates the default as None.   Later the help indicates thus:
The default value, None, indicates that this cmdlet **does not include the KeyUsage extension in the new certificate.**

Even if I specify -KeyUsage None, the new certificate has a "Key Usage" extension in the cert with values of "Digital Signature" & "Key Encipherment" regardless.  I've also tried specifying None on -KeySpec and -KeyUsageProperty and various combinations, with the same results.  You can, however, specify different values for -KeyUsage and it will change to those values, but those will also get the yellow warning sign and propagate to the newly minted certs

After creating a certificate that way as a Root CA, the certificates created and signed with that RootCA inherit the problem.

Here is some code that will demonstrate the difference between the output of MakeCert.exe and New-SelfSignedCertficate:

##MAKECERT example
$RootCA = "Hyper-V Replication Certificate Authority"
$ReplicaServer = "MyServerName-01"
##Create root cert
.\makecert.exe -pe -n "CN=$RootCA" -ss root -sr LocalMachine -sky signature -r ".\$RootCA.cer"
##Create new cert using rootCA
.\makecert.exe -pe -n "CN=$ReplicaServer" -ss my -sr LocalMachine -sky exchange -eku 1.3.6.1.5.5.7.3.1,1.3.6.1.5.5.7.3.2 -in "$RootCA" -is root -ir LocalMachine -sp "Microsoft RSA SChannel Cryptographic Provider" -sy 12

Generates a cert with no issues:
![image](https://user-images.githubusercontent.com/15986948/27103468-550750f8-504e-11e7-93a3-bedc491c247f.png)

##New-SelfSignedCertificate example
##Create Root Cert
$RootCA = "Hyper-V Replication Certificate Authority"
$ReplicaServer = "MyServerName-01"
$Cert = New-SelfSignedCertificate  `
		-Type Custom `
		-KeyExportPolicy Exportable `
		-Subject "CN=$RootCA" `
		-KeySpec Signature `
		-KeyUsage "None" `
		-KeyUsageProperty All `
		-CertStoreLocation Cert:\LocalMachine\My `
		-NotAfter (Get-Date -Date "12/31/2039 18:59:59")
##Note the above certificate would need to be moved to the Root store to be a valid root certificate in the chain.  But the example I'm trying to show is evident without doing that.

##Create new cert from RootCA
New-SelfSignedCertificate `
	-Type Custom `
	-Subject "CN=$ReplicaServer" `
	-KeySpec KeyExchange `
	-CertStoreLocation Cert:\LocalMachine\My `
	-KeyExportPolicy Exportable `
	-TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.1,1.3.6.1.5.5.7.3.2") `
	-Signer "Cert:LocalMachine\My\$($Cert.Thumbprint)" `
	-Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" `
	-NotAfter (Get-Date -Date "12/31/2039 18:59:59")

Generates a cert with a warning icon on the "Key Usage" extension:
![image](https://user-images.githubusercontent.com/15986948/27103517-8890c954-504e-11e7-8980-133d91caa7ef.png)

**Comment by chrischu** [comment]
I have the same problem!

**Comment by roadsunknown** [comment]
Also experiencing the issue related to the forced "critical" flag (yellow warning sign) on the -KeyUsage property. Critical flag should not be set by default. As with -TextExtension, the Critical flag should be optional.

https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @GitHubBJW 
Thanks for your feedback.
I tested this in my lab and I could verify that if, you do not specify -KeyUsage "None" while creating the certificate (even though you created the root one with it) you will see "Digital Signature, Key Encipherment". But, if you specify -KeyUsage "None" on it, it will honor this and do not include this field.
I will create a pull request to improve this article based on your suggestion.
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR #1113  and kindly provide your feedback

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @GitHubBJW Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by YetiNerd** [comment]
As i am trying to create a selfsigned certificate with New-SelfSignedCertificate like @GitHubBJW described in his initial comment i am getting the same "error".
Even though i specified -KeyUsage None in both the RootCA and the certificate. 

The following Script for a Root also didnt work:

`New-SelfSignedCertificate -Type Custom -KeySpec Signature `
-Subject "CN=RootCA" `
-KeyExportPolicy Exportable `
-KeyUsageProperty All `
-KeyUsage None `
-KeyAlgorithm rsa `
-HashAlgorithm sha256 -KeyLength 4096 `
-CertStoreLocation Cert:\LocalMachine\My `
-TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.1") `
-NotAfter (Get-Date).AddYears(5)`

**Comment by Aralox** [comment]
This issue has not been resolved at all. The original problems still remain
- Setting KeyUsage to None does not work
- KeyUsage made critical

Can we please re-open this issue?

**Comment by Techsteps** [comment]
This should be reopen. KeyUsage made critical (as mentioned by @roadsunknown) no matter what is an issue still.

**Comment by ZianAtFirstWatch** [comment]
I was able to generate a pair of public and private keys without the KeyUsage extension by setting Type to Custom, KeyUsage to None, and KeyUsageProperty to All.

Sample code:
```
New-Variable -Visibility Private -Option Constant -Name "GOOGLE_CLOUD_KEY_REQUIREMENTS" -Value ([pscustomobject]@{
		Algorithm = "RSA"
		KeyLength = 2048
		Subject   = ""
	})
New-Variable -Visibility Private -Option Constant -Name "NEVER_ENDING_PRODUCTION_CERTIFICATE" -Value ([datetime]"9999-12-31")
$private:newCertificateParameters = @{
	Subject           = $private:GOOGLE_CLOUD_KEY_REQUIREMENTS.Subject
	KeyAlgorithm      = $private:GOOGLE_CLOUD_KEY_REQUIREMENTS.Algorithm
	KeyLength         = $private:GOOGLE_CLOUD_KEY_REQUIREMENTS.KeyLength
	CertStoreLocation = "Cert:\CurrentUser\My"
	KeyExportPolicy   = "Exportable"
	NotAfter          = $private:NEVER_ENDING_PRODUCTION_CERTIFICATE
	KeyUsage          = "None"
	KeyUsageProperty  = "All"
	Type              = "Custom"
}
$private:certificate = New-SelfSignedCertificate @private:newCertificateParameters
```
The documentation should say that the KeyUsage and KeyUsageProperty parameters will be ignored when Type is not set to custom.
