### ISSUE TITLE
Get-TlsEccCurve documention somewhat sparse

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#70]
The documentation for the Get-TlsEccCurve cmdlet is virtually non-existent, there is no synopsis, no examples and no clue as to what IT Pros should use this cmdlet for.

Is there some further documentation? If so, I'll happily knock together a P/R to add this information.

Also: other cmdlets in the TLS module are equally as sparse.

**Comment by brianlic-msft** [comment]
@rodmhgl thanks for the updates!  I've merged this PR and the changes should be live soon.
