### ISSUE TITLE
Example in Get-TlsCiperSuite does not work with WIndows 10

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#71]
The second example in the documentation of Get-TlsCiperSuite uses the command:

Get-TlsCipherSuite -Name "SSL"

On both Serer 2016 and Windows 10 (1703) this example returns no cipher suites.

Should the example be updated?

**Comment by brianlic-msft** [comment]
@rodmhgl thanks for the updates!  I've merged this PR and the changes should be live soon.
