### ISSUE TITLE
-filter is a string, not a script block

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#718]
The filter is a string, not script block, despite the Backus-Naur form.  The get-aduser doc has the same error.

&lt;filter&gt; ::= "{" &lt;FilterComponentList&gt; "}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a11d541-b67b-d5e4-6ca3-05db321746cd
* Version Independent ID: 3eb1d45a-94e9-239f-613f-19fd837ab24e
* Content: [Get-ADComputer (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adcomputer?view=win10-ps)
* Content Source: [docset/windows/addsadministration/get-adcomputer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/get-adcomputer.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Malind19** [comment]
Created pull request 
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/871

**Comment by kenwith** [comment]
@Malind19 - did you also create a PR for the get-aduser that the issue mentions? thanks.

**Comment by Malind19** [comment]
@kenwith Shall I make it "{" <FilterComponentList> "}" | " <Script> "? Is that the correct syntax? for a string and  a script block

**Comment by e0i** [comment]
@kenwith Two PRs, #911 and #912 are available for review. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
