### ISSUE TITLE
Please Clarify: Inability to run Deduplication on Boot Volumes

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [MicrosoftDocs/windows-powershell-docs#721]
Why is Deduplication on bootable volumes not supported? Has it merely not been implemented yet, or has the functionality purposefully been excluded for safety reasons?

**Comment by HumanEquivalentUnit** [comment]
https://docs.microsoft.com/en-us/previous-versions/technet-magazine/cc137769(v=msdn.10)

> in order to read the boot files off the disk, you need the file system driver, but the file system driver is on the disk, which you can't read until you've loaded the file system driver. Oh no, Catch-22!
> 
> The vicious cycle is broken by having a miniature file system driver built into the critical boot files. This miniature driver knows just barely enough to locate files in the root directory and load them into memory. Those files can, in turn, get the operating system off the ground, at which point the real file system driver can take over and look for files in much fancier places like subdirectories.

The same applies to deduplication, [it runs through a filesystem filter driver Dedup.sys](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/understand) ; you couldn't boot the OS from disk until the filesystem drivers are loaded, but they need the OS running before they are available. 

There is likely no reason or plan to build the miniature driver out until it can do everything (I have no inside knowledge), but Dedupe is not supported on client versions of Windows, and Server builds have many more resources and would be very easy to plan in advance to have separate boot drives and data drives, so it seems very unlikely.

**Comment by Amaroq-Clearwater** [comment]
So it's like NTFS Compression, in that case.

**Comment by e0i** [comment]
Hello @Amaroq-Clearwater  ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure._
