### ISSUE TITLE
Credential Guard

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/windows-powershell-docs#722]
It looks like when Windows Credential Guard is enabled, if you run this cmdlet against a 2016 DC, it fails with "user has not been authenticated"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f89dbca0-9343-3bf6-af5c-ff238a02389a
* Version Independent ID: 21938055-e032-51c5-3b13-5f5802d8a1e1
* Content: [Get-ADPrincipalGroupMembership (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adprincipalgroupmembership?view=win10-ps)
* Content Source: [docset/windows/addsadministration/get-adprincipalgroupmembership.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/get-adprincipalgroupmembership.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot unassign e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @dsolodow  thank you for providing feedback.

Note that the form that you have submitted this feedback from is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
