### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by brdly-smith** [MicrosoftDocs/windows-powershell-docs#723]
CreateNonDADkmContainer.ps1 url is broken.

https://go.microsoft.com/fwlink/?linkid=832923

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc41e3a-88ae-772d-6df1-05331c689c75
* Version Independent ID: 050fc16d-9e32-9156-bfdf-be70f2cd9fa8
* Content: [Install-AdfsFarm (adfs)](https://docs.microsoft.com/en-us/powershell/module/adfs/install-adfsfarm?view=win10-ps)
* Content Source: [docset/windows/adfs/install-adfsfarm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/install-adfsfarm.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by MaratMussabekov** [comment]
@e0i ,
article, where link should point (https://docs.microsoft.com/windows-server/identity/ad-fs/deployment/Install-AD-FS-Delegated-Admin), does not exist anymore.

There is still the same article in different locale (https://docs.microsoft.com/cs-cz/windows-server/identity/ad-fs/deployment/install-ad-fs-delegated-admin)

Onur, what should we do?

Thank you

**Comment by e0i** [comment]
This issue is same as #545 which in turn is same as #35 .
