### ISSUE TITLE
You would think this would return a field for success or failure.

### ISSUE THREAD

**Issue by parappsys** [MicrosoftDocs/windows-powershell-docs#726]
All I see is Path, Online, and RestartNeeded. That property could be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583cf3ca-55c4-0a64-f71f-5196dfed8d4a
* Version Independent ID: 015bf296-2438-b403-5871-85ba37823b52
* Content: [Enable-WindowsOptionalFeature (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/enable-windowsoptionalfeature?view=win10-ps)
* Content Source: [docset/windows/dism/enable-windowsoptionalfeature.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dism/enable-windowsoptionalfeature.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @parappsys thanks for your feedback.
To propose changes or improvements in cmdlets, I need to kindly suggest you to visit https://windowsserver.uservoice.com/forums/295047-general-feedback where you can propose your idea as this is issue resource is intended to address issues in documentation.
Thank you

**Comment by yogkumgit** [comment]
@parappsys  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
