### ISSUE TITLE
Description of -ID parameter is incorrect.

### ISSUE THREAD

**Issue by noelhibbard** [MicrosoftDocs/windows-powershell-docs#728]
The description of -ID says has a typo. It says "you can use wildcards" But should read "you canNOT use wildcards".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d378f090-790e-f6af-6f77-1d1a7dcf8798
* Version Independent ID: 5cb43ccf-3a7b-f9aa-80e9-342e788216aa
* Content: [Suspend-PrintJob (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/suspend-printjob?view=win10-ps)
* Content Source: [docset/windows/printmanagement/suspend-printjob.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/printmanagement/suspend-printjob.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@noelhibbard  Thank you for the feedback. We have made the changes to the Doc via PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/996

**Comment by e0i** [comment]
@noelhibbard 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
