### ISSUE TITLE
Clarify how to NOT use WinLogonCredential with MSCAPv2

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/windows-powershell-docs#729]
Hi, We need to have a username + password configured as part of the VPN setup. That may not be best practice for many VPN setups but it is for us. This document fails to explain how to use NON windows credentials. Maybe it is not possible at all. If that is the case it would be good to mention that in the document too. Thank you.

-UseWinlogonCredential
Indicates that MSCHAPv2 or EAP-MSCHAPv2 is used as the authentication method, and that Windows logon credentials are used automatically when connecting with the VPN connection profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd7dfc2a-8614-7435-ed17-31a20fcab943
* Version Independent ID: edaa5545-0b10-a11b-318b-3dbd978c8530
* Content: [New-EapConfiguration (vpnclient)](https://docs.microsoft.com/en-us/powershell/module/vpnclient/new-eapconfiguration?view=win10-ps)
* Content Source: [docset/windows/vpnclient/new-eapconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/vpnclient/new-eapconfiguration.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@blouwagie 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@blouwagie 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
