### ISSUE TITLE
Example 3 (S/MIME certificate) does not work for me

### ISSUE THREAD

**Issue by CDC86** [MicrosoftDocs/windows-powershell-docs#730]
Thank you for the nice documentation. However, Example 3 (S/MIME certificate with alternate email addresses) did not work for me. I had to make the following changes to get a certificate that is accepted by both Thunderbird 60.5.1 and Outlook 2010:

"KeyUsage" must be "DigitalSignature,KeyEncipherment" (Thunderbird also accepts "None", but Outlook not). "DigitalSignature" is required for signing and "KeyEncipherment" is required for encryption.

The syntax for alternate email addresses is
"2.5.29.17={text}email=adr1@example.com&email=adr2@example.org&email=adr3@example.net"
UPNs as used in the example do not work here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80b6f8a-6227-63cb-391f-bd3324a57251
* Version Independent ID: e3ce9f6c-ae5f-9b4b-2d3b-d709e886c01c
* Content: [New-SelfSignedCertificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/new-selfsignedcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/new-selfsignedcertificate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @CDC86 thanks for your feedback.
I decided to add your example on a pull request, and leave the current too because it can still be valid for someone else.
It should go live in a couple of days.
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR Added an example #1148 and kindly provide your feedback

**Comment by CDC86** [comment]
The new example still won't work because`-KeyUsage DigitalSignature,KeyEncipherment` is missing, see explanation in my original request.
I'd also be grateful if someone could ascertain that there is a setting at all where example 3 will work for creating a working S/MIME certificate and document that setting. Otherwise it would not make much sense to keep the example.

**Comment by get-itips** [comment]
Hello @CDC86 
Thanks for your feedback, I worked on an issue where the default KeyUsage for this cmdlet  was indeed DigitalSignature,KeyEncipherment please see [here](https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1113) that's the reason i did not changed that in my last PR, I did not notice the use of KeyUsage in that example, so I'll remove it now as DigitalSignature,KeyEncipherment is the default.

**Comment by CDC86** [comment]
Thank you for working on this. I've finally found my notes from February. It does not seem to be possible any more to create an working S/MIME certificate in one command because Thunderbird insists on certificates signed by a CA (a nuisance inherited from Firefox).

A more complete example would be:
`New-SelfSignedCertificate -CertStoreLocation cert:\currentuser\my -DnsName cert.contoso.com -NotAfter  (Get-Date).AddYears(3) -KeyUsage CertSign,CRLSign -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.2,1.3.6.1.5.5.7.3.1,1.3.6.1.5.5.7.3.4,1.3.6.1.5.5.7.3.3,1.3.6.1.5.5.7.3.8,1.3.6.1.5.5.7.3.1","2.5.29.19={critical}{text}ca=TRUE")`
Creates a CA certificate for signing other certificates valid for three years. The output of this command is a fingerprint which will be needed for the next command.
`New-SelfSignedCertificate -Type Custom -Subject "E=patti.fuller@contoso.com,CN=Patti Fuller" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.4","2.5.29.17={text}email=patti.fuller@contoso.com&email=pattifuller@contoso.com&email=p.fuller@contoso.com") -KeyUsage DigitalSignature,KeyEncipherment -KeyAlgorithm RSA -KeyLength 4096 -SmimeCapabilities -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter (Get-Date).AddYears(3) -signer cert:\currentuser\my\<fingerprint from previous command>`
will create a S/MIME certificate signed by the CA created above. This certificate has the subject alternative names of patti.fuller@contoso.com, pattifuller@contoso.com and p.fuller@contoso.com and will expire after three years. 
**Note:** If `DigitalSignature,KeyEncipherment` is the default for `KeyUsage`, this should also work without explicitly specifying it, but I have not verified that it does work.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @CDC86 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
