### ISSUE TITLE
-WhatIf parameter does not follow documented behavior

### ISSUE THREAD

**Issue by amaiman** [MicrosoftDocs/windows-powershell-docs#731]
This documentation states that using the -WhatIf parameter will result in: "The cmdlet is not run."
This is not the observed behavior.  The parameter is ignored and the command is executed (which causes test commands to actually change the environment.)

(I'm aware this is supposed to be for documentation issues, not bugs, but technically the documentation is wrong since it doesn't match reality.  The Microsoft maintainer of this document should be able to pass this on to the relevant product team.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34c0224f-9a51-1588-e358-89b78137837a
* Version Independent ID: 1198037f-ee7d-c1e7-8340-15db23fcf506
* Content: [Set-SRGroup (storagereplica)](https://docs.microsoft.com/en-us/powershell/module/storagereplica/set-srgroup?view=win10-ps)
* Content Source: [docset/windows/storagereplica/set-srgroup.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storagereplica/set-srgroup.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @AndreaBarr can you help us finding the right person? Thanks

**Comment by get-itips** [comment]
Hello @amaiman thanks for your feedback, I can confirm that a bug has already been filed to the product team on this. @AndreaBarr

**Comment by amaiman** [comment]
Thanks for looking into it!  (I unfortunately only thought to come back and check this thread because I have to go report this on a different cmdlet which has the same problem.)  [https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1231]

**Comment by yogkumgit** [comment]
@amaiman as mentioned bug is filed to product team for investigation hence we proceed to close the issues here.
If you see a documentation update is required, please feel free to open an issue for the same. Please keep contributing with your suggestions to improve the documentation.
