### ISSUE TITLE
No Thumbprint Parameter

### ISSUE THREAD

**Issue by Stofferl** [MicrosoftDocs/windows-powershell-docs#735]
No Thumbprint Parameter, please fix it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de72abc-be59-61d0-282b-b6515d01d595
* Version Independent ID: 88da75ef-8a82-52d7-54db-23c3487aa5fb
* Content: [Set-RDCertificate (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/set-rdcertificate?view=win10-ps#feedback)
* Content Source: [docset/windows/remotedesktop/set-rdcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remotedesktop/set-rdcertificate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Stofferl 
Thanks for your feedback, a note stating in which version of Windows Server the Thumbprint is available has been added, please see here https://github.com/MicrosoftDocs/windows-powershell-docs/commit/d0ff4616b0c071190f91f4e6e8f78b5736ebcde5#diff-21c9e9075a905fa82a0da3c07a0526c7

It should go on the live version in a while.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Stofferl 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
