### ISSUE TITLE
Get-NetIPConfiguration and Get-NetIPAddress wildcards

### ISSUE THREAD

**Issue by furyritchie** [MicrosoftDocs/windows-powershell-docs#742]
The documents for both Get-NetIPConfiguration and Get-NetIPAddress list InterfaceAlias as not accepting wildcard characters, however, thankfully they both do and perhaps the documentation needs to be tweaked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69207cc3-e1e8-acea-2e0f-b4127b59479a
* Version Independent ID: 3d72b1f1-7dfb-8b9e-fa14-424fc98b33b1
* Content: [Get-NetIPConfiguration (nettcpip)](https://docs.microsoft.com/en-us/powershell/module/nettcpip/get-netipconfiguration?view=win10-ps#feedback)
* Content Source: [docset/windows/nettcpip/get-netipconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nettcpip/get-netipconfiguration.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @furyritchie thanks for your feedback, I created a pull request to correct the documentation.
Thank you

**Comment by yogkumgit** [comment]
@tseward and @dariomws306 please review PR  InterfaceAlias accepts wildcards #1147 and kindly provide your feedback

**Comment by dariomws306** [comment]
Was Get-NetIPAddress also updated?

**Comment by get-itips** [comment]
@dariomws306 When I was about to edit Get-NetIPAddress, I noticed already has the change made, you won't see it on the live version because of the stalling currently facing this repo.

**Comment by dariomws306** [comment]
Nice!

**Comment by tseward** [comment]
Looks good :)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @furyritchie Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
