### ISSUE TITLE
Set-VpnServerIPsecConfiguration vs Set-VpnServerConfiguration

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-powershell-docs#753]
This article confuses two cmdlets, one of which isn't properly documented:

&gt;  Set-VpnServerConfiguration
&gt;  Set-VpnServerIPsecConfiguration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1f61ad-1367-5a1f-d273-5e56403a1398
* Version Independent ID: 51dc34fc-6aab-5fc4-0b98-0baeee3624f4
* Content: [Set-VpnServerConfiguration (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/set-vpnserverconfiguration?view=win10-ps#feedback)
* Content Source: [docset/windows/remoteaccess/set-vpnserverconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remoteaccess/set-vpnserverconfiguration.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @andrewwillett 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.
