### ISSUE TITLE
IPAddressRange parameter

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-powershell-docs#754]
Only the first IPv4 address range supplied to this parameter is added to the VPN server configuration. The documentation states that multiple ranges will be added:

StartIPRange1, EndIPRange1, StartIPRange2, EndIPRange2, StartIPRange3, EndIPRange3, and so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905472f1-5c82-cd92-7ffd-20f34f90ee5f
* Version Independent ID: 49f5651c-39cd-c8e0-9c29-54938dfd4375
* Content: [Install-RemoteAccess (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/install-remoteaccess?view=win10-ps#optional-parameters)
* Content Source: [docset/windows/remoteaccess/install-remoteaccess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remoteaccess/install-remoteaccess.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@andrewwillett 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@andrewwillett The issue is currently under investigation. Thanks.

**Comment by VLG17** [comment]
@andrewwillett Could you please provide the exact cmdlet that you are running and also some details about the infrastructure? 

According to the documentation, the prerequisite for specifying multiple ranges is to have a cluster with multiple nodes (and for each node you specify a certain range). Is this true in your case?

**Comment by andrewwillett** [comment]
It looks like you're right in terms of documentation, this behaviour isn't intuitive however.
