### ISSUE TITLE
SstpPorts/Ikev2Ports number increase

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-powershell-docs#756]
Increasing the number of SSTP/IKEv2 ports is unreliable without a full server restart, not just a restart of the RemoteAccess server as advised by a PowerShell warning message.

This is possibly related to increasing WanEndpoints higher than MaxWanEndpoints value. Decreasing the number of ports is unaffected.

Incidentally netsh.exe ras set wanports=n is similarly broken/unreliable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1f61ad-1367-5a1f-d273-5e56403a1398
* Version Independent ID: 51dc34fc-6aab-5fc4-0b98-0baeee3624f4
* Content: [Set-VpnServerConfiguration (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/set-vpnserverconfiguration?view=win10-ps)
* Content Source: [docset/windows/remoteaccess/set-vpnserverconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remoteaccess/set-vpnserverconfiguration.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@andrewwillett 

The issue tracker of this repository is intended for product documentation issues only.

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)


Thanks.

**Comment by e0i** [comment]
@officedocsbot close
