### ISSUE TITLE
It's Micsorofts Shame #25142, that M$$ is not reviewing it's "Docs"

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windows-powershell-docs#759]
Of course, "Default value: None" is almost always wrong. The Script has to select a Default value, e.g. for the parameter CaptureLiveState.

But you're right: it's the cheapest 'solution' to write 'this kind of docs'.
They're wrong, incomplete and it's a shame, but we're paying the licenses - so what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bac34fdd-0e44-a1d7-959e-bc0d455254bd
* Version Independent ID: ba568860-97d9-41a7-dd41-9898665b1948
* Content: [Export-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/export-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/export-vm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/export-vm.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by SergeGrd** [comment]
This article is wrong when saying "The Virtual Machines folder contains the configuration XML of the specified virtual machine"
Question : For how long time don't we use XML files anymore in Hyper-V

**Comment by troglobytor** [comment]
It would be nice to state we could just copy the VM directory and its contents to another location.
