### ISSUE TITLE
Help page is not valid to the specified command

### ISSUE THREAD

**Issue by OleksiiKondratiev** [MicrosoftDocs/windows-powershell-docs#763]
This help page is about different command Get-IpamIpAuditEvent that does not exist in Windows Server 2016. Please update data with correct command documentation Get-IpamIpAddressAuditEvent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c95d24-6e5d-4aa0-3eeb-9817159795fb
* Version Independent ID: 297ae8c7-e332-051e-6868-0c0f72333597
* Content: [Get-IpamIpAddressAuditEvent (ipamserver)](https://docs.microsoft.com/en-us/powershell/module/ipamserver/get-ipamipaddressauditevent?view=win10-ps#feedback)
* Content Source: [docset/windows/ipamserver/get-ipamipaddressauditevent.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/ipamserver/get-ipamipaddressauditevent.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@OleksiiKondratiev 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@Oleksandr-Kosariev 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
