### ISSUE TITLE
Limited documentation on SDN Cmdlets

### ISSUE THREAD

**Issue by rdbartram** [MicrosoftDocs/windows-powershell-docs#77]
Most cmdlets have a required Properties field. Using the examples and reverse engineering the sdnexpress scripts allowed me to find out some properties but can we please get documentation about what properties there are for each specific class. thanks

**Comment by brianlic-msft** [comment]
I reached out to the SDN engineering team.  I'll post an update here when I hear back.

**Comment by AnirbanPaul** [comment]
Hi
I agree that this is challenging. You can do a couple of things: 
a. If you look at the "New" cmdlets for each noun, you will see the inputs needed for the resource in the description of "Properties" field and the "Inputs" field. 
b. Additionally, if you look at the example, you will find the actual object being used for the Properties, like "Microsoft.Windows.NetworkController.RouteProperties". Enumerating this will also give you the exact properties' names. 

We are planning to add the exact property names as well to the cmdlet documentation soon.

Thanks
Anirban

**Comment by rdbartram** [comment]
I ended up pulling the NetworkController Module apart and found the definitions for Microsoft.Windows.NetworkController but I guess this is only a list of the options supported by the module not everything supported by the API.

@AnirbanPaul Are there plans to add the property names directly to the cmdlets or just to the documentation. The reason I ask is because I am currently developing a .NET Core module to do the same crud operations but with simpler command syntax. Is there a plan to open source the module so I can contribute rather than me having a completely separate module?

**Comment by AnirbanPaul** [comment]
Hi
There is no plan to change the cmdlets at this point. So, to be able to add new resources to the Network Controller, you will have to use the "New" cmdlets in their current form. We are looking to bolster the documentation for this, but for now, you can take a look at the examples in all the "New" cmdlets to understand how you can add/update a resource.

Thanks
Anirban
