### ISSUE TITLE
Get-TroubleshootingPack -Answer - Does not create answer file correctly in Server 2016

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windows-powershell-docs#84]
I am trying to use the -Answer parameter to Get-TroubleshootingPack in Server 2016 to generate an answer file. I am using, in this case, The WindowsUpdateDiagnostic and want to create an answer file that attempts both fixes.

The interactive version of this troubleshooter was very successful in fixing a bunch of WU issues - so I want to automate this for the future!

If I run the pack interactively, I go through a dialog. If I use the Get-TroubleshootingPack and supply the answer file I have two issues: first, the questions asked are NOT the same as when running the troubleshooter interactively and second the generated answer file does not automate fully the checking and I still get prompted. 

I reported this (https://social.technet.microsoft.com/Forums/windowsserver/en-US/c930cf4b-d517-4bce-a4dd-75bc637b75f9/problems-using-gettroubleshootingpack?forum=winserverpowershell) and have had one poster unhelpful answers. but his final answer suggests that this stuff is broken.

Is this cmdlet broken in WIndows Server 2016, or is there some magic formula that we need to document to make this feature work?

**Comment by doctordns** [comment]
Anyone have any ideas about this??

**Comment by e0i** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @doctordns 
Thanks for your feedback.
I analyzed your inquiry and also read the post you made in forum.
As this issue resource is specifically to address about issues in documentation, and I could verify that the article is ok, I need to suggest different resources for your inquiry, like User Voice https://windowsserver.uservoice.com and Support Services https://support.microsoft.com/en-us/supportforbusiness/productselection

Hope this information helps you.

**Comment by doctordns** [comment]
SO please update the documentation to show how to make this work?

**Comment by get-itips** [comment]
Hello @doctordns how are you? Hope you are doing good.
If the cmdlet does not work as intended, this needs to be suggested either on UserVoice or Support services, once the cmdlet is improved or changed based on valuable user feedback (like yours), the article can reflect that change, otherwise, I couldn't identify anything to change on current article (all examples in the article work and there are no missing description for parameters, for example)

Thank you

**Comment by doctordns** [comment]
I guess it would have been helpful to note that -Answer files do not work in Server 2016 and above.
