### ISSUE TITLE
Set-MpPreference -SignatureScheduleTime do not take 'minutes' as value

### ISSUE THREAD

**Issue by ronak-itility** [MicrosoftDocs/windows-powershell-docs#85]
### Fail Case
When tried to set the value as 
`Set-MpPreference -SignatureScheduleTime 120` it did not set the parameter.

### Working Case
When did it this way 
` Set-MpPreference -SignatureScheduleTime 03:00:00` the parameter was set.

**Comment by brianlic-msft** [comment]
@ronak-itility I reached out to the engineering team and they said number of minutes after midnight (e.g. 120) is supported.

**Comment by worlvlhole** [comment]
FYI - Just encountered this exact issue..

Windows Server 2016  
OS version: 1607
Build : 14393.2363

**Comment by jakemarston** [comment]
Why is this closed? This issue is still present.
