### ISSUE TITLE
VirtualDesktopAllocation

### ISSUE THREAD

**Issue by ivassallo19** [MicrosoftDocs/windows-powershell-docs#874]
Could you please update this document set, to give more detail around this parameter.

-VirtualDesktopAllocation &lt;Hashtable&gt;

There is no great explanation on the values for this Hashtable.
This seems to be directly related to the Virtual Desktop Allocation screen from Server Manager, where the values indicate how many machines are to be created per server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ddf1f0-4d7a-289d-a657-c9ba991972c1
* Version Independent ID: ad5a9db3-1e00-54d7-2a7a-38e3dc46c599
* Content: [New-RDVirtualDesktopCollection (remotedesktop)](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/new-rdvirtualdesktopcollection?view=winserver2012r2-ps#feedback)
* Content Source: [docset/winserver2012r2-ps/remotedesktop/New-RDVirtualDesktopCollection.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/remotedesktop/New-RDVirtualDesktopCollection.md)
* Product: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@ivassallo19 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
