### ISSUE TITLE
Documentation error in Set-MpPreference

### ISSUE THREAD

**Issue by cfalta** [MicrosoftDocs/windows-powershell-docs#876]
The documentation for the parameter "-ThreatIDDefaultAction_Actions" in the cmdlets (Set/Add)-MpPreference is inconsistent.

This link (https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=win10-ps) states that 

> -ThreatIDDefaultAction_Actions
> Specifies an array of the actions to take for the IDs specified by using the ThreatIDDefaultAction_Ids parameter. The acceptable values for this parameter are:
> 
> 1: Clean
> 2: Quarantine
> 3: Remove
> **4: Allow**
> 8: UserDefined
> 9: NoAction
> 10: Block

This link (https://docs.microsoft.com/en-us/previous-versions/windows/desktop/defender/add-msft-mppreference) states that the value for "Allow" is "6"

> ThreatIDDefaultAction_Actions [in]
> 
> Default actions for threats upon which default action should not be taken when detected. The actions need to be in the same order as their respective Ids specified in the ThreatIDDefaultAction_Ids property.
> 
> Clean (1)
> Quarantine (2)
> Remove (3)
> **Allow (6)**
> UserDefined (8)
> NoAction (9)
> Block (10)

I think the correct value would be "6" for "Allow".

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@cfalta 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
