### ISSUE TITLE
XML file format

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-powershell-docs#884]
What about the format of the XML file? Is it the same file that can be get when executing the below PowerShell
Get-ProcessMitigation -RegistryConfigFilePath settings.xml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8a834a-0684-307a-a5b5-ce4b8d439b46
* Version Independent ID: 92d92261-527d-9273-517d-d10f43898522
* Content: [Set-ProcessMitigation (processmitigations)](https://docs.microsoft.com/en-us/powershell/module/processmitigations/set-processmitigation?view=win10-ps#feedback)
* Content Source: [docset/windows/processmitigations/set-processmitigation.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/processmitigations/set-processmitigation.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@LuigiBruno Thank you for your feedback. That is correct, The get-processmitigation Gets all settings from the registry and saves them to the xml file settings.xml and the same file can be used to set-processmitigation as well.

Hope this helps!

Thanks
Sri

**Comment by LuigiBruno** [comment]
> @LuigiBruno Thank you for your feedback. That is correct, The get-processmitigation Gets all settings from the registry and saves them to the xml file settings.xml and the same file can be used to set-processmitigation as well.
> Hope this helps!
> Thanks
> Sri

Thank you @msbemba.

**Comment by e0i** [comment]
Hello @LuigiBruno  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by LuigiBruno** [comment]
> Hello @LuigiBruno  ,
> The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
> Thanks.

Thank you @e0i.
