### ISSUE TITLE
-DnsHostname and -restricttosinglehost issues

### ISSUE THREAD

**Issue by AndresPae** [MicrosoftDocs/windows-powershell-docs#904]
In theory -DNS hostname IS NOT server hostname! 
It is kind of account DNS name. So you can in result have duplicated hostnames ( for server and MAservice )  or if you specify -restricttosinglehost  cmdlet fails with "Parameter set cannot be resolved using the specified named parameters. "

Please see https://social.technet.microsoft.com/Forums/windowsserver/en-US/9a66d1d5-44e9-4ea1-ba9c-88862023c4e1/why-does-a-gmsa-need-a-dns-host-name-e-g-newadserviceaccount-dnshostname?forum=winserver8gen  reply from JinjaAdmin 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8e2b47-a29a-04c7-261d-752df5afa122
* Version Independent ID: e66770b5-1cf3-617d-d7f6-6d334501075a
* Content: [New-ADServiceAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=win10-ps)
* Content Source: [docset/windows/addsadministration/new-adserviceaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/new-adserviceaccount.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@AndresPae 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
