### ISSUE TITLE
Firewall group is wrong

### ISSUE THREAD

**Issue by zrbrc** [MicrosoftDocs/windows-powershell-docs#905]
The above command to open the firewall ports is wrong.

It should be "Distributed Transaction Coordinator" group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb83e47-15b2-86aa-f296-06a44ff798a5
* Version Independent ID: 68a4a153-4502-6620-4edc-d76829e3bc07
* Content: [Test-Dtc (msdtc)](https://docs.microsoft.com/en-us/powershell/module/msdtc/test-dtc?view=win10-ps#feedback)
* Content Source: [docset/windows/msdtc/test-dtc.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/msdtc/test-dtc.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
