### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by MrSent** [MicrosoftDocs/windows-powershell-docs#906]
Where are the examples? When I issue the command with no parameters it lists all printers, but because the text is so long in some of the output it truncates the data so I cannot see it. How do you stop the stupid command from truncating the text? Give me a tool but blind me before seeing the output. Great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2618eb99-2119-5afc-7609-621a59e30d7e
* Version Independent ID: 135dbe3e-7eeb-4fac-68b6-784819aa4a51
* Content: [Get-PrinterPort (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/get-printerport?view=win10-ps)
* Content Source: [docset/windows/printmanagement/get-printerport.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/printmanagement/get-printerport.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by alexkuc** [comment]
Use command Format-List to show the text in a list rather than the table. Then the text won't be truncated. For example, "Get-PrinterPort | Format-List *" or "Get-PrinterPort | FL *". Asterisk is used to avoid omitting any properties.

**Comment by e0i** [comment]
@MrSent It seems that your question has been answered by the community.

Note that the issues section of this repository is intended for documentation and content issues only.

Should you have any further issues similar to this one, please consider opening a product support ticket here:

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
