### ISSUE TITLE
No warnings??

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windows-powershell-docs#907]
If Update-VMVersion is started by using the Hyper-V Manager, then it displays strange warnings that "this operation will discard all saved state etc."
Therefore, we expect a clear description for those warnings about what exactly will be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707f6902-9162-daaa-9c9f-cfc649f49f3d
* Version Independent ID: 9aaca787-1832-6b37-77f1-55bb1236a63c
* Content: [Update-VMVersion (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/update-vmversion?view=win10-ps)
* Content Source: [docset/windows/hyper-v/update-vmversion.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/update-vmversion.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by sowjanya365** [comment]
Hi @schittli 

Thank you for reaching out!

Saved state, in a virtualization context, is a way to store the current state of a virtual machine i.e, Open programs, cache etc. So all the open programs, system cache and temp files on disk gets deleted. 

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by e0i** [comment]
Hello @schittli  ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
