### ISSUE TITLE
Examples for -Service?

### ISSUE THREAD

**Issue by eeegs** [MicrosoftDocs/windows-powershell-docs#914]
I can't find any information on the -Service option. Could an example be provided?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35517b3c-d00e-c08d-c274-8b606ad87bfa
* Version Independent ID: 3428c627-8703-752e-fbdf-52526f281f57
* Content: [Enable-BitLocker (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/enable-bitlocker?view=win10-ps)
* Content Source: [docset/windows/bitlocker/enable-bitlocker.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/enable-bitlocker.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@eeegs  Thank you for your feedback. The -service parameter is used as a switch to Indicate that the system account for that computer can unlock the encrypted volume. The system account is local to the computer similar to an administrator accounts. The system account is used by the operating system and by services that run under Windows.

Hope this helps!

Thanks
Sri

**Comment by e0i** [comment]
Hello @eeegs  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
