### ISSUE TITLE
 Corrupt files 

### ISSUE THREAD

**Issue by theoamaya** [MicrosoftDocs/windows-powershell-docs#919]
Thank you your the best 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc610a0c-fc0d-8a00-a443-3447eb3ec6f0
* Version Independent ID: 2902add4-6897-0d89-9d80-685c58bf1239
* Content: [Add-PartitionAccessPath (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/Add-PartitionAccessPath?view=win10-ps#feedback)
* Content Source: [docset/windows/storage/add-partitionaccesspath.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/add-partitionaccesspath.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @theoamaya 

Would you clarify the subject of the issue?

Is the document misleading? What needs to be updated?

We would like to follow-up with content updates accordingly.

Thank you for providing feedback.

**Comment by theoamaya** [comment]
I have no fucking idea what talking about

**Comment by e0i** [comment]
@theoamaya The issue is being closed since there is no further clarification regarding the subject of the issue.

**Comment by e0i** [comment]
@officedocsbot close
