### ISSUE TITLE
Set-AssignedAccess System Error 1376 on non-English locale

### ISSUE THREAD

**Issue by Mugbaz** [MicrosoftDocs/windows-powershell-docs#925]
When Set-AssignedAccess is run on an non-English localization of Windows an internal net command produces a System Error 1376 when looking for a group specifically titled "administrators" which in this case does not exist. 

The following snippet is from a Finnish localization saying "System Error 1376" and "Specified group does not exist."

```
PS C:\> Set-AssignedAccess -AppUserModelId Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge -UserName myusername
C:\windows\system32\net.exe : J„rjestelm„virhe 1376.
At line:1 char:1
+ C:\windows\system32\net.exe localgroup administrators
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (J„rjestelm„virhe 1376.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
M„„ritetty„ paikallista ryhm„„ ei ole.
```

This can be remedied by creating a local group titled "Administrators" and adding it to the localized administrators group before running the cmdlet.

The behavior is also described on this blog post: [http://www.osd-couture.com/2018/07/windows-10-kiosk-modefix-unable-to-add.html](http://www.osd-couture.com/2018/07/windows-10-kiosk-modefix-unable-to-add.html)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Mugbaz 

The issue tracker of this repository is intended for product documentation issues only.

Please consider consulting PowerShell UserVoice channel regarding your bug report via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
