### ISSUE TITLE
Missing details in Synopsis section

### ISSUE THREAD

**Issue by AndreasL53** [MicrosoftDocs/windows-powershell-docs#93]
Please add information to the SYNOPSIS section:

From Section 3.5 in https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/hyper-converged-solution-using-storage-spaces-direct

This article states that enable-clusterstoragespacesdirect implements various steps:

Step 3.5: Enable Storage Spaces Direct

After creating the cluster, use the Enable-ClusterStorageSpacesDirect PowerShell cmdlet, which will put the storage system into the Storage Spaces Direct mode and do the following automatically:
Create a pool: Creates a single large pool that has a name like "S2D on Cluster1".
Configures the Storage Spaces Direct caches: If there is more than one media (drive) type available for Storage Spaces Direct use, it enables the fastest as cache devices (read and write in most cases)
Tiers: Creates 2 tiers as default tiers. One is called "Capacity" and the other called "Performance". The cmdlet analyzes the devices and configures each tier with the mix of device types and resiliency.

It should be clearly stated what this cmdlet actually does...

**Comment by StevenEk** [comment]
Thank you for the feedback.

**Comment by Malind19** [comment]
@e0i I see this clearly explained. Kindly suggest what else is to add.

**Comment by Malind19** [comment]
@AndreasL53 Thank you very much for the feedback. Can you kindly suggest what are we missing in this explanation. I can see the command it self explained with details. How can we improve the whole explanation in that section?

**Comment by e0i** [comment]
@AndreasL53 

We couldn't get further clarification regarding suggested improvements. Feel free to re-open this issue with further clarification if you feel that it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
