### ISSUE TITLE
Cannot add hostname for RemoteAddress in New-NetFirewall

### ISSUE THREAD

**Issue by RUGANDH** [MicrosoftDocs/windows-powershell-docs#933]
The -RemoteAddress parameter specifies this parameter value can be an IPv4 or IPv6 address, hostname, subnet, range, or the following keyword: Any. However the acceptable formats for this parameter are only address, subnet or a range. We cannot add hostname for this parameter.
I request you to change this public documentation.

One of our Microsoft customers requires this change to be made and to provide him a documentation for this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a81ceb77-8de5-8c07-c0c4-fa3d616d859f
* Version Independent ID: 736dd392-788a-c102-dfcb-29a08c2c9f9d
* Content: [New-NetFirewallRule (netsecurity)](https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps#feedback)
* Content Source: [docset/windows/netsecurity/new-netfirewallrule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netsecurity/new-netfirewallrule.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@RUGANDH 

The issue tracker of this repository is intended for product documentation issues only.

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)


Thanks.

**Comment by e0i** [comment]
@officedocsbot close
