### ISSUE TITLE
get-help get-smbshare -examples

### ISSUE THREAD

**Issue by Curtmcgirt** [MicrosoftDocs/windows-powershell-docs#94]
example 2 (incorrectly) says 

"Get-SmbShare –Name VMS1 --- retrieves the SMB shares on the computer named VMS1."

the -name switch is for the name of the share, not the name of a remote computer.

**Comment by brianlic-msft** [comment]
@Curtmcgirt Thanks for the feedback!  This was fixed in pull request 95.
