### ISSUE TITLE
Legitimate Switches

### ISSUE THREAD

**Issue by CW-Nyobi** [MicrosoftDocs/windows-powershell-docs#944]
In example2 there is a switch -RegistryType, which doesn't actually exist. If its not valid it shouldn't be there.

-In addition the set-netadapteradvancedproperty doesn't succeed if the registrykeyword isn't preexisting. As I would like to set the PnpCapabilities key on each of my adapters to 24(currently not existing), this seems rather a large short coming. Having the -RegistryType would make sense on setting/creation of values that don't exist. Can this functionality be enabled/readded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9772c9ad-a7f7-0fca-0f68-ac842b076062
* Version Independent ID: a633b80a-4d64-6e3f-6436-b56a7f94e1ef
* Content: [Set-NetAdapterAdvancedProperty (netadapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/set-netadapteradvancedproperty?view=win10-ps#feedback)
* Content Source: [docset/windows/netadapter/set-netadapteradvancedproperty.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netadapter/set-netadapteradvancedproperty.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by velkovb** [comment]
@CW-Nyobi Hello,
Thank you for your trying to impove MicrosoftDocs. 

I will work on fixing the first part of your issue. Regarding the second one, Set-NetAdapterAdvancedProperty is used to modify existing properties. If you would like to set (create) registry values you can try - [New-NetAdapterAdvancedProperty](https://docs.microsoft.com/en-us/powershell/module/netadapter/new-netadapteradvancedproperty?view=win10-ps)
