### ISSUE TITLE
parameters insufficiently described

### ISSUE THREAD

**Issue by fijam** [MicrosoftDocs/windows-powershell-docs#949]
I assume PFS1, PFS2 and PFS2048 correspond to DH groups 1, 2 and 14 but what is PFSMM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb2472e-4c1f-b26f-709b-12336de2728b
* Version Independent ID: e0eff45a-be41-6dbb-ab48-724c08a854b5
* Content: [Set-VpnConnectionIPsecConfiguration (vpnclient)](https://docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionipsecconfiguration?view=win10-ps#feedback)
* Content Source: [docset/windows/vpnclient/set-vpnconnectionipsecconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/vpnclient/set-vpnconnectionipsecconfiguration.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@fijam

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by sowjanya365** [comment]
Hi @fijam 

Thank you for reaching out.

All parameters PFS1, PFS2, PFS2048, ECP256, ECP384, PFSMM, and PFS24 belongs to PfsGroup. So PFSMM is also a field in the PfsGroup. 

For more details, please see the below links. 

https://docs.microsoft.com/azure/templates/microsoft.network/2018-11-01/vpngateways/vpnconnections?view=azure-dotnet

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.fluent.models.pfsgroup?view=azure-dotnet

Hope this clarifies your query. Kindly confirm.

**Comment by fijam** [comment]
Hi,

Thank you for the reply.

A few comments:

* The first problem is that your designations for various DH groups don't
follow a discernible scheme. It's helpful to remember that Diffie-Hellman
groups used for IKE ("DHGroup") and later Child SA rekeying ("PfsGroup")
are the same thing. They are defined by Internet Assigned Numbers Authority
as follows:
http://www.iana.org/assignments/ikev2-parameters/ikev2-parameters.xhtml#ikev2-parameters-8

The naming scheme selected in Windows 10 switches between using the
assigned IANA id ("Group14"), the group length ("PFS2048" which is
equivalent) or both (Azure documentation lists both PFS14 and PFS2048 - are
they synonyms?) while ECP groups are treated separately (ECP256, ECP384).
Then there is PFSMM which is not really a group at all (Main Mode
applicable only for IKEv1). None of this is apparent from the documentation
and can be only arrived at by conjecture. Each DH parameter used for both
IKE and PFS should be unambiguously matched with its corresponding IANA id.

* This ties into the second problem, which is poor separation of parameters
into those related to IKE exchange and ESP.  Intuitively, there should be
four options controlling IKE (encryption method, integrity algorithm,
pseudo-random function, DH groups) and either three (non-AEAD encryption
method, integrity algorithm, DH groups) or two (AEAD encryption method, DH
groups) options controlling ESP. Meanwhile, we have EncryptionMethod and
DHGroup for IKE and CipherTransformConstants and PfsGroup for ESP.
IntegrityCheckMethod apparently applies to both IKE and ESP (unless GCM is
selected) with the IKE pseudo-random function automatically derived from
it. This is also undocumented.

* Then there is idiosyncratic behavior (also not documented) such as that
selection of ECP groups requires the machine certificate to be also signed
with ECDSA. I don't know of other ipsec implementations with that
requirement.

All of this had to be pieced together by trial and error.

Best regards,
Jan

**Comment by sowjanya365** [comment]
Hello @fijam 

Thank you so much for your valuable inputs and recommendations. Appreciate your efforts in making the docs better. 

We kindly request you to submit your recommendations here in this user voice forum. 

https://wpdev.uservoice.com/forums/110705-universal-windows-platform

We believe that product team will definitely look into it. And please share with us the out come. We will definitely make the necessary changes on the document. Thank you for your time. Have a nice day!

**Comment by e0i** [comment]
@officedocsbot close
