### ISSUE TITLE
Firewall feedback is wrong.

### ISSUE THREAD

**Issue by dozer75** [MicrosoftDocs/windows-powershell-docs#955]
The tools is broken.

I have disabled the firewalls on both computers, but still getting warnings about firewall rules that is disabled. The firewall rules doesn't even exists on Windows 10/Windows Server 2016.

Because of this, it will stop with the following error:

DTC security settings and firewall settings should be fixed in order to complete the transactions propagation test.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb83e47-15b2-86aa-f296-06a44ff798a5
* Version Independent ID: 68a4a153-4502-6620-4edc-d76829e3bc07
* Content: [Test-Dtc (msdtc)](https://docs.microsoft.com/en-us/powershell/module/msdtc/test-dtc?view=win10-ps#feedback)
* Content Source: [docset/windows/msdtc/test-dtc.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/msdtc/test-dtc.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @dozer75 thank you for providing feedback.

Note that the issue tracker of this repository is intended for product documentation issues only.

Please consider checking any relevant resources and asking the community about your problem via the following link.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
