### ISSUE TITLE
Get-NfsMappedIdentity not working with UserIdentifier 0

### ISSUE THREAD

**Issue by ivoruetsche** [MicrosoftDocs/windows-powershell-docs#958]
When I try to check the mapped username to uid 0, I don't get a result:
(Get-NfsMappedIdentity -AccountType User -UserIdentifier 0).UserName
Every uid &gt; 0 works, also (Get-NfsMappedIdentity -AccountType Group -GroupIdentifier 0).GroupName works fine, but not uid=0
(Windows 2012)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852407bf-e8f2-7cb2-13a9-636576e87215
* Version Independent ID: dd352e1e-a322-c60f-42b3-f69192d87db7
* Content: [Get-NfsMappedIdentity (nfs)](https://docs.microsoft.com/en-us/powershell/module/nfs/get-nfsmappedidentity?view=win10-ps#feedback)
* Content Source: [docset/windows/nfs/get-nfsmappedidentity.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/nfs/get-nfsmappedidentity.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @ivoruetsche  thank you for providing feedback.

Note that the issue tracker of this repository is intended for product documentation issues only.

Please consider opening a support ticket for product issues and bugs via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You can also check relevant resources and ask the community regarding your problem via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
