### ISSUE TITLE
Supported range for LocalASN parameter

### ISSUE THREAD

**Issue by tdimli** [MicrosoftDocs/windows-powershell-docs#962]
LocalASN parameter is defined as UInt32 but only values between 1 and 65534 are supported by this cmdlet. It would be helpful to have the valid range documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6198f91-958e-f682-a09f-50622b790b28
* Version Independent ID: f7955b94-a3e3-5935-6072-7f5363a2f76b
* Content: [Add-BgpRouter (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/add-bgprouter?view=win10-ps#feedback)
* Content Source: [docset/windows/remoteaccess/add-bgprouter.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remoteaccess/add-bgprouter.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Borkason** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@tdimli 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
