### ISSUE TITLE
-Reset parameter not needed

### ISSUE THREAD

**Issue by AvrumFocus** [MicrosoftDocs/windows-powershell-docs#964]
From my experience the -reset parameter is not needed when resetting a password, simply using -newpassword with a value without providing an -oldpassword parameter value will also reset the password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ccc946-9393-581d-8ca2-e32d4c8ce99c
* Version Independent ID: 50982f9a-ac84-9554-3fe5-414e60368b92
* Content: [Set-ADAccountPassword (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-adaccountpassword?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/set-adaccountpassword.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/set-adaccountpassword.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @AvrumFocus

Would you specify which version you have observed the mentioned behavior with? We would like to follow-up with content updates if necessary.

Thank you for your feedback.

**Comment by e0i** [comment]
@AvrumFocus 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
