### ISSUE TITLE
Typo Example 2

### ISSUE THREAD

**Issue by javincraig** [MicrosoftDocs/windows-powershell-docs#966]
Example 2: Get all IPv4 DHSP servers in the IPAM server inventory
I believe should be 
Example 2: Get all IPv4 DHCP servers in the IPAM server inventory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99397990-a9e6-4c7d-27d1-243ef44eb179
* Version Independent ID: 4bd48375-f086-455d-e50c-8cbb349a06b5
* Content: [Get-IpamServerInventory (ipamserver)](https://docs.microsoft.com/en-us/powershell/module/ipamserver/get-ipamserverinventory?view=win10-ps#feedback)
* Content Source: [docset/windows/ipamserver/get-ipamserverinventory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/ipamserver/get-ipamserverinventory.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
