### ISSUE TITLE
Remove the optional flags [ ] for the mandatory parameters

### ISSUE THREAD

**Issue by 3ter** [MicrosoftDocs/windows-powershell-docs#968]
Hi there,

when you run `Search-ADAccount` there is no default parameter set. You have to specify one e.g. `-AccountDisabled`.
In the output of `Search-ADAccount -?` the [ ] are also missing to reflect that it is mandatory to specify at least one of these parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87483a05-ea3b-19c2-3d31-4701e03e68e2
* Version Independent ID: 917d2078-1e43-895a-e3cb-d6e64844196e
* Content: [Search-ADAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/search-adaccount?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/search-adaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/search-adaccount.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot add label test

**Comment by e0i** [comment]
@officedocsbot delete label test

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@3ter  Thank you for your feedback. The Search-Adaccount does not have a mandatory parameter however needs to have at least one of these parameters specified. We have mentioned that in the description, "The Search-ADAccount cmdlet retrieves one or more user, computer, or service accounts that meet the criteria specified by the parameters."

Hope this helps.

Thanks
Sri

**Comment by 3ter** [comment]
I agree, that - individually - they are not mandatory parameters but as a group they are.
On [ss64](https://ss64.com/ps/search-adaccount.html) they are called `SearchSwitch` to differentiate them from the other (really optional) parameters.

I was confused when I first executed the cmdlet without paramters as every single one is enclosed in the optional marking brackets `[ -optional ]`.
I thought it would be better to have the brackets removed and instead grouped all those together as in the reference above.

Feel free to close the issue when you think the help conventions are valid. Most likely there's no single solution to write the help 100% consistent.

**Comment by msbemba** [comment]
Thank you @3ter. I have checked with the authors/reviewers and they have confirmed that there are no changes required at this time. Thank you for the feedback.

Thanks
Sri

**Comment by msbemba** [comment]
@e0i  This can be closed.
