### ISSUE TITLE
Errors on Remove-WebVirtualDirectory doc

### ISSUE THREAD

**Issue by wvoyek** [MicrosoftDocs/windows-powershell-docs#974]
`Site` and `Application` are listed as optional but are actually required from my experience using this command.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00544400-b443-d558-a315-e03392d528ff
* Version Independent ID: 35c13c66-4b89-a2e3-cc0a-08e744877492
* Content: [Remove-WebVirtualDirectory (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/remove-webvirtualdirectory?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/webadminstration/Remove-WebVirtualDirectory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/Remove-WebVirtualDirectory.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @wvoyek 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by get-itips** [comment]
Hello @velkovb It seems that -Name is also required, so we need to remove the [ ]
