### ISSUE TITLE
Additional Parameters for Remove-WebVirtualDirectory

### ISSUE THREAD

**Issue by wvoyek** [MicrosoftDocs/windows-powershell-docs#975]
Please add a `-Recurse` parameter and/or a `-Force` parameter for this cmdlet.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00544400-b443-d558-a315-e03392d528ff
* Version Independent ID: 35c13c66-4b89-a2e3-cc0a-08e744877492
* Content: [Remove-WebVirtualDirectory (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/remove-webvirtualdirectory?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/webadminstration/Remove-WebVirtualDirectory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/Remove-WebVirtualDirectory.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
The feedback is being passed to a writer for revision. Thank you.

**Comment by VLG17** [comment]
@wvoyek Thank you for the valid feedback. I recommend submitting this feedback through [UserVoice for Powershell](https://windowsserver.uservoice.com/forums/301869-powershell), since this needs to be looked at and come from the Product Group.
