### ISSUE TITLE
Name used in Example 3 code snip does not match text below it: MyWeekendOptimization != MyWeekdayOptimization

### ISSUE THREAD

**Issue by severud** [MicrosoftDocs/windows-powershell-docs#979]
The code snipet of Example 3 has the text "MyWeekendOptimization" but the discussion below the code reads "MyWeekdayOptimization". The code line should be modified to have "MyWeekdayOptimization" since that is what the other parameters are set to, namely Mon-Fri optimization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d4fee7-0557-f699-17e6-1b7729c9b9f4
* Version Independent ID: c16640d7-524c-4a5b-fe78-a6855ea32181
* Content: [New-DedupSchedule (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/new-dedupschedule?view=win10-ps#feedback)
* Content Source: [docset/windows/deduplication/new-dedupschedule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/new-dedupschedule.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@severud 

The issue is being routed to Windows PowerShell writing team for investigation. You'll be notified with relevant updates as content gets updated.

Thank you for providing feedback.

**Comment by sowjanya365** [comment]
Hi @severud 

Thank you for sharing your views and making the docs better. We appreciate it. 

The typo has been corrected. Please find the below PR link for your reference. 

https://github.com/MicrosoftDocs/windows-powershell-docs/pull/976

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
