### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by JimHume** [MicrosoftDocs/windows-powershell-docs#98]
Information is incomplete or missing from a large percentage of the articles in the repository. 

"As an administrator, it is hard to rely on the documentation when it is incomplete, and very difficult to use any of the functionality in its entirety without sufficient documentation."

**Comment by rodmhgl** [comment]
That's the purpose of this repository / project. Can you please be more specific with the cmdlets / areas you're seeing incomplete documentation in so we can target them?

**Comment by JimHume** [comment]
There are 48 instances of "{{Fill in the description}}". The pattern of text is easy enough to find if searching for "{{Fill":
https://github.com/MicrosoftDocs/windows-powershell-docs/search?utf8=%E2%9C%93&q=%7B%7BFill&type=

**Comment by brianlic-msft** [comment]
@jimhume Thanks for reporting this! We're working on getting some of these corrected. For now, you can use [PowerShell cmdlets for provisioning Windows 10 (reference)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-powershell) for the provisioning module. 

If you see descriptions that are missing and would like to contribute, please submit a pull request and I can working on getting it merged.  Thanks!
