### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by danofnz** [MicrosoftDocs/windows-powershell-docs#982]
The cmdlet is incorrect, 'Get-PartitionSupportedSizes'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7582541-5c8e-2a7f-5a8b-d7a08570f8e9
* Version Independent ID: 976b2d36-9c01-712a-3d9b-330151794e20
* Content: [Get-PartitionSupportedSize (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/get-partitionsupportedsize?view=win10-ps#feedback)
* Content Source: [docset/windows/storage/get-partitionsupportedsize.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/get-partitionsupportedsize.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@danofnz 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@danofnz 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
