### ISSUE TITLE
Screening Type doesn't appear to default to "Passive"

### ISSUE THREAD

**Issue by si1ic0ngh0st** [MicrosoftDocs/windows-powershell-docs#987]
The documentation for the -Active parameter states that the default Screening Type will be Passive unless the -Active parameter is specified.  I just created a new file screen _without_ specifying the -Active parameter, and it was created as an Active screen (files blocked when triggered).  Re-running the command with -Active:$false resolved this issue and it creates as Passive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3426798e-f30e-e921-df75-94a795737227
* Version Independent ID: 9d626fbd-d916-6367-32c7-8c104a0a43ae
* Content: [New-FsrmFileScreen (fileserverresourcemanager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/new-fsrmfilescreen?view=win10-ps#feedback)
* Content Source: [docset/windows/fileserverresourcemanager/new-fsrmfilescreen.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/fileserverresourcemanager/new-fsrmfilescreen.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@si1ic0ngh0st 

In our investigation we have been able to reproduce the problematic behavior and the issue is being passed to the product team as a bug.

Thank you for taking the time to provide feedback. Much appreciated.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@si1ic0ngh0st 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
