### ISSUE TITLE
InitiatorLatency Unit

### ISSUE THREAD

**Issue by martinohansen** [MicrosoftDocs/windows-powershell-docs#989]
Hi,

What unit is InitiatorLatency reported in, msec or usec? We're having trouble getting what this page: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/clusstorageqosprov/msft-storageqosflow says to correspond to what we see.

Thanks,
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdbfded-de5b-552a-ec30-4a87833772a9
* Version Independent ID: 18dcc03c-386c-01c3-38af-0c4a5dbbf0ce
* Content: [Get-StorageQoSFlow (storageqos)](https://docs.microsoft.com/en-us/powershell/module/storageqos/get-storageqosflow?view=win10-ps#feedback)
* Content Source: [docset/windows/storageqos/get-storageqosflow.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storageqos/get-storageqosflow.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by velkovb** [comment]
@martinohansen Hi Martin, Thank you for contributing to MicrosoftDocs. The documentation specifies that this InitiatorLatency is in microseconds. What is the difference that you are seeing?

**Comment by e0i** [comment]
@martinohansen

We are closing this issue as we couldn't get response from your side regarding additional details. Feel free to re-open this issue with clarifications and we'll follow-up with a PR. Thank you.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by martinohansen** [comment]
Hi @velkovb, sorry for the late response. I've tried to show the conflicting information in below snippet from our environment. The first output is clearly presented in milliseconds and the seconds matching up.

Maybe i'm misunderstanding the output format and its not `MSFT_StorageQoSFlow class` with below commands? I hope you can help us, thanks. 

```
PS C:\Windows\system32> Get-StorageQoSFlow -CimSession ech-hvc-7 | Select-Object -First 5 | Format-Table ; Get-StorageQoSFlow -CimSession ech-hvc-7 | select InitiatorName,InitiatorIOPS,InitiatorLatency,InitiatorBandwidth | Select-Object -First 5 | Format-Table

InitiatorName FilePath                                                                                                      InitiatorIOPS InitiatorLatency InitiatorBandwidth PSComputerName
------------- --------                                                                                                      ------------- ---------------- ------------------ --------------
TKE-TSM03     C:\ClusterStorage\ech-rgv-vnx8000-1-lun-1\TKE-TSM03\TKE-TSM03_2.VHDX                                          1             0.5 ms           0 MB/s             ech-hvc-7     
MHH-ECIT-RDS1 C:\ClusterStorage\ech-rgv-vnx8000-1-lun-1\MHH-ECIT-RDS1\WINSRV2016STD.VHDX                                    27            0.6 ms           0.2 MB/s           ech-hvc-7     
TKE-SBS-BG    C:\ClusterStorage\ech-rgv-vnx8000-1-lun-1\TKE-SBS-BG\TKE-SBS-BG.VHDX                                          2             0.5 ms           0 MB/s             ech-hvc-7     
PLUS-RDGW01   C:\ClusterStorage\ech-rgv-vnx8000-1-lun-1\PLUS-RDGW01\WINDOWS SERVER 2012 R2 DATACENTER WITH GUI - GEN 2.VHDX 3             0.6 ms           0 MB/s             ech-hvc-7     
TKE-TSG01     C:\ClusterStorage\ech-rgv-vnx8000-1-lun-1\TKE-TSG01\TKE-TSG01-000001.VHDX                                     1             0.9 ms           0 MB/s             ech-hvc-7     


InitiatorName InitiatorIOPS InitiatorLatency InitiatorBandwidth
------------- ------------- ---------------- ------------------
TKE-TSM03                 1           0,5271               6144
MHH-ECIT-RDS1            27           0,6295             192512
TKE-SBS-BG                2           0,5344              13312
PLUS-RDGW01               3            0,609              19456
TKE-TSG01                 1           0,8538               6144
```

**Comment by velkovb** [comment]
Hi @martinohansen,

That shuld be the correct class. The format file actually adds ms but the documentation says microseconds.
![image](https://user-images.githubusercontent.com/10958657/59837535-12007080-9356-11e9-99e4-3ffa4aaf2ee5.png)

@e0i I believe https://docs.microsoft.com/en-us/previous-versions/windows/desktop/clusstorageqosprov/msft-storageqosflow should be edited so says miliseconds instead of microseconds.
