### ISSUE TITLE
Time is said to be seconds when it should be minutes

### ISSUE THREAD

**Issue by si1ic0ngh0st** [MicrosoftDocs/windows-powershell-docs#992]
All settings on this page that adjust the time between events firing off are said to be in seconds (eg: "the minimum number of seconds"), when it should be in minutes.  I am getting this information from the File Server Resource Manager (MMC) GUI, where it shows that these values are in minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df5fe9ea-9a3a-4670-1154-4def9eb83968
* Version Independent ID: c93b900a-9054-7222-28ef-67db661154b7
* Content: [Set-FsrmSetting (fileserverresourcemanager)](https://docs.microsoft.com/en-us/powershell/module/fileserverresourcemanager/set-fsrmsetting?view=win10-ps)
* Content Source: [docset/windows/fileserverresourcemanager/set-fsrmsetting.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/fileserverresourcemanager/set-fsrmsetting.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@si1ic0ngh0st 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
